### ISSUE TITLE
Dúvida - início do script

### ISSUE THREAD

**Issue by raphaelmro** [mpcabete/bombcrypto-bot#1]
Opa @mpcabete ! Primeiramente parabens pelo script!
Gostaria de saber a partir de que momento é ideal dar o start nele? Na tela do dashboard, do treasure hunt ou dentro da heroes?

**Comment by mpcabete** [comment]
Opa, perdao a demora. 
Entao, usa o commom so na parte de rodar a tela pra baixo, n sei se vc ja reparou, mas rodar com a rodinha do mouse n funciona mto bem.
O bot clicka no commom e arrasta pra cima pra rolar a tela.
Eu n sei mto bem como ta funcionando, mas imagino q n vai fazer mta diferença no seu caso ele nao ver o commom, como vc n precisa rolar a tela.
Em relaçao ao conect wallet, eu tava tendo problemas, mas dps de um tempo analizando percebi q o problema eh q ele tava esperando mto pra clickar no botao "sign" da metamask, dai o jogo acabava nao reconhecendo.
Eu dei uma arrumada nisso, mas se ele realmente n estiver reconhecendo o botao, vc pode tentar tirar um print screen dele e substituir a imagem nos arquivos do programa.

**Comment by madDANET** [comment]
opa bom dia! Traceback (most recent call last):
  File "C:\Users\Maddanet\Desktop\bombcrypto-bot-main\index.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'  ta dando isso! Sabe como eu arrumo? Se esse trem funcionar eu vou te doar todo dia pq pqp... saudades de noites de sono!

**Comment by mpcabete** [comment]
Bom dia, tenta o comando
`pip install requests`

**Comment by madDANET** [comment]
Amigo ta dando boa o bot me passa sua carteirA Metamask pfv

Em qua, 10 de nov de 2021 18:18, mpcabete ***@***.***>
escreveu:
