### ISSUE TITLE
Bot funcionando já ? 

### ISSUE THREAD

**Issue by nezkaum** [mpcabete/bombcrypto-bot#100]
Bot já voltou a funcionar ?

**Comment by Psicrow** [comment]
ja que voce nao ta ajudando em nada. nao abre topico pra fazer pergunta besta. olha os outros topicos...

**Comment by nezkaum** [comment]
eu estou apenas fazendo uma pergunta irmão, se não estiver funcionando ainda, bastasse dizer não, não precisa vir com essa sua ignorancia não

**Comment by Psicrow** [comment]
entao nao crie um topico so pra isso. veja os outros... senao na proxima outro vai dar patada

**Comment by mvpalves** [comment]
É só ler a página inicial... o cara já ta trabalhando nisso.

Criando tópico assim parece que tu ta cobrando por algo que sequer pagou, fica difícil defender.
