### ISSUE TITLE
solução Metamask janela exterior, no meu código.

### ISSUE THREAD

**Issue by Psicrow** [mpcabete/bombcrypto-bot#101]
eu uso o navegador opera e toda vez que clico pra conectar a carteira, ele abre uma janela exterior. o codigo que criei pra resolver esse b.o foi esse logo a baixo. nao é o meu codigo inteiro, meu codigo foi baseado no do mpcabete entao tem variaveis iguais mas alguns metodos sao diferentes, pq fiz em POO.
meu repositório.
https://github.com/Psicrow/Bbot

**Comment by THEBESTSZ** [comment]
Aoba, vc resolveu o captcha no seu?

**Comment by Psicrow** [comment]
@THEBESTSZ  não, nao consegui ter tempo pra parar e ver isso ainda. eu até sugeri e estou estudando esse código aqui pra adaptar
https://github.com/mpcabete/bombcrypto-bot/issues/95#issuecomment-984970195

**Comment by LRBarbieri** [comment]
Eu parei de ter esse problema quando mudei a imagem do Sign do Metamask para um print que eu tirei. Loga dboa

**Comment by Psicrow** [comment]
> Eu parei de ter esse problema quando mudei a imagem do Sign do Metamask para um print que eu tirei. Loga dboa

a questão amigo, é que cada navegador age de um jeito diferente. nao é a questçao da imagem de assinar far erro. no opera por exemplo a metamask abre em uma janela reduzida e tem que rolar pra baixo. ja no chrome se nao me engano, ja é uma janela em formato de popup esticada, nao precisando rolar pra baixo. tlg?
