### ISSUE TITLE
Erro ao executar pip uninstall opencv-python pip install --upgrade opencv-python==4.5.3.56

### ISSUE THREAD

**Issue by cesarfran12** [mpcabete/bombcrypto-bot#103]
![image](https://user-images.githubusercontent.com/73753868/144540518-46f7829e-4ba5-4942-a2b9-47ac2e072cda.png)

**Comment by mpcabete** [comment]
vc ja tentou aquela ultima ali? a 4.5.3.56

**Comment by gian-lepear** [comment]
Cara, qual a sua versão do python? se não me engano o projeto usa a versão 3.10, pode ser que vc esteja usando uma versão que não seja compativel com a sua versão, link da versão certa do opencv: https://pypi.org/project/opencv-python/4.5.3.56/

**Comment by cesarfran12** [comment]
> vc ja tentou aquela ultima ali? a 4.5.3.56

Estou com um erro novo 
Traceback (most recent call last):
  File "C:\bomb1\index.py", line 595, in <module>
    solveCapcha()
  File "C:\bomb1\index.py", line 560, in solveCapcha
    pieces_start_pos = getPiecesPosition()
  File "C:\bomb1\index.py", line 502, in getPiecesPosition
    popup_pos = positions(robot)
  File "C:\bomb1\index.py", line 170, in positions
    result = cv2.matchTemplate(img,target,cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.5.4-dev) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

**Comment by cesarfran12** [comment]
> 

esse consegui resolver

**Comment by cesarfran12** [comment]
> vc ja tentou aquela ultima ali? a 4.5.3.56

Tenho esse erro novo consegue ajudar?

**Comment by fguide** [comment]
Experimente rodar sem atualizar, no WIndows pelo menos funcionou para mim.

**Comment by fguide** [comment]
Eu consegui rodar no windows sem atualizar o opencv, mas parece que sua atualização nao entrou, também tem erros pedindo o build tools, talvez seja interessante verificar a instalação do python/pip.

**Comment by gabrielwjesus** [comment]
pip3 install --upgrade opencv-python==4.5.3.56
são dois comandos diferentes ai
primeiro voce pode tentar fazer o uninstall ou remove do opencv
e depois a instalação da versão atualizada
mas não as duas juntas
e tente pip3

**Comment by sportano** [comment]
> pip3 install --upgrade opencv-python==4.5.3.56 são dois comandos diferentes ai primeiro voce pode tentar fazer o uninstall ou remove do opencv e depois a instalação da versão atualizada mas não as duas juntas e tente pip3

Utilizei dessa forma e tá dando o mesmo erro que o da imagem do primeiro post, alguma solução?

**Comment by Gaboo134** [comment]
Bom dia! Eu tive o mesmo erro acima e após esse erro quando tento executar algum comando PIP o CMD informa
( 'pip' não é reconhecido como um comando interno ou externo, um programa operável ou um arquivo em lotes.) 
sou bem leigo, se alguém puder me ajudar agradeço!

**Comment by Gaboo134** [comment]
![image](https://user-images.githubusercontent.com/95483887/144610415-0953f6a6-0c2f-45db-a11a-72acbb2c1ffd.png)

**Comment by Gaboo134** [comment]
![image](https://user-images.githubusercontent.com/95483887/144610614-eaced7fc-22f1-473d-a1fe-8f32cf651f49.png)

**Comment by fguide** [comment]
> Bom dia! Eu tive o mesmo erro acima e após esse erro quando tento executar algum comando PIP o CMD informa ( 'pip' não é reconhecido como um comando interno ou externo, um programa operável ou um arquivo em lotes.) sou bem leigo, se alguém puder me ajudar agradeço!

Aparentemente o caminho do python não está nas variaveis do windows, rode o instalador do python novamente e selecione a opção "Add Python 3.10 to PATH" na tela inicial, depois disso deve funcionar.
