### ISSUE TITLE
Loop Inifinito

### ISSUE THREAD

**Issue by joaovitorbogo** [mpcabete/bombcrypto-bot#104]
O bot em determinado momento quando vai mandar os heroes pra trabalhar, entra num loop infinito do captcha e não faz nada

**Comment by fguide** [comment]
Você fez o merge por sua conta? Se for isso tem algum erro, seria interessante aguardar o oficial que deve sair hoje.

**Comment by Dfcrespi** [comment]
Como faz esse merge?

**Comment by fguide** [comment]
É só clonar a branch puzzle, comparar com o codigo da main e fazer os ajustes para funcionarem juntos.

Se você não está familiarizado com esse tipo de trabalho, é recomendável aguardar o o merge oficial, até porque talvez venha com outras correções e funções.
