### ISSUE TITLE
duvida do time

### ISSUE THREAD

**Issue by rnesheiksilvestre** [mpcabete/bombcrypto-bot#105]
teria como eu configurar ele para executar em horarios random exemplo de 30 a 60 minutos....

**Comment by fguide** [comment]
O tempo é fixo nas configurações, pelo arquivo config.yaml, no momento não é possível configurar intervalos random.

**Comment by THEBESTSZ** [comment]
Cara, possível é, procura sobre a biblioteca "from random import randint"

**Comment by rnesheiksilvestre** [comment]
> Cara, possível é, procura sobre a biblioteca "from random import randint"

eu estava vendo que é possivel porem la na parte dos times, ele chama uma variavel ai não sei como declarar :( não manjo de python

**Comment by fguide** [comment]
> > Cara, possível é, procura sobre a biblioteca "from random import randint"
> 
> eu estava vendo que é possivel porem la na parte dos times, ele chama uma variavel ai não sei como declarar :( não manjo de python

o parametro do tempo fica no arquivo config.yaml, mais precisamente o send_heroes_for_work é o que envia para o trabalho, você pode procurar por 'send_heroes_for_work' no index.py e estudar como fazer a alteração, a sugestão acima funciona, importe o random e use randint(), randrange(), etc

https://docs.python.org/3/library/random.html

**Comment by rnesheiksilvestre** [comment]
> > > Cara, possível é, procura sobre a biblioteca "from random import randint"
> > 
> > 
> > eu estava vendo que é possivel porem la na parte dos times, ele chama uma variavel ai não sei como declarar :( não manjo de python
> 
> o parametro do tempo fica no arquivo config.yaml, mais precisamente o send_heroes_for_work é o que envia para o trabalho, você pode procurar por 'send_heroes_for_work' no index.py e estudar como fazer a alteração, a sugestão acima funciona, importe o random e use randint(), randrange(), etc
> 
> https://docs.python.org/3/library/random.html

[https://i.ibb.co/tXWPZPX/Captura-de-Tela-2021-12-03-a-s-17-40-07.png](url)

como eu disse ele chama uma variavel lá no index.py porem não sei como fazer essa alteração

**Comment by morgado198028** [comment]
qual quer coisa assim dava mas o problema e inplementar  

print(random.randint(1, 100))
