### ISSUE TITLE
Monitorameno de tela - AVISO

### ISSUE THREAD

**Issue by fguide** [mpcabete/bombcrypto-bot#106]
Pessoal, hoje vi o comunicado dos admins abaixo, aparentemente estão  monitorando a tela de alguma forma.

No windows eu já percebi que o microsoft gaming abre quando o jogo inicia, no linux obiamente nao. Apenas para alertar e para que fiquem atentos com possíveis bans já que na home está descrito que ainda não haviam se pronunciado.

**Am I allowed to use a Bot/Auto-clicker/macros?**
No! Since 1/12/2021 you are completely prohibited from using bot/auto-clicker/macros! Bombcrypto is saving users movements and ID's in order to ban accounts from using this kind of software, please do not use bots!

**Comment by nazgul3301** [comment]
Creio que randomizar os movimentos do mouse por si só nao resolva o problema, o que penso que estão fazendo é verificar movimentos em linha reta do mouse, caso seja isso seria basicamente implementar funções trigonometricas para o mouse realizar movimentos meio circulares

**Comment by wanderaugusto** [comment]
Vai ter que implementar isso no bot entao ?

**Comment by LuisBonatti** [comment]
Bom pessoal, não sei como será a implementação de melhoria de código à respeito desse track. Mas procurando no código do bomb, achei esse pedaço de código que pelo que pesquisei ele grava o movimento do mouse. Eu iria colocar aqui o caminho pro script, mas não sei o quão errado isso seria. Mas enfim, quando a feature de melhora não for mais o puzzle, creio que podemos ir mais a fundo nesse carinha

```{
    canvas.addEventListener("click", (function(ev) {
        if (!Browser.pointerLock && Module["canvas"].requestPointerLock) {
            Module["canvas"].requestPointerLock();
            ev.preventDefault()
        }
    }), false)
}}})

**Comment by victorblevi** [comment]
Cara, fazendo esses ajustes, vai ficar muito safe. É muito dificil dectar macros, além do que eles rodam no navegador, que não disponibiliza tanto recursos para decção assim...

**Comment by fguide** [comment]
> Cara, fazendo esses ajustes, vai ficar muito _safe_. É muito dificil dectar macros, além do que eles rodam no navegador, que não disponibiliza tanto recursos para decção assim...

O navegador em si não, mas sinceramente não entendo nada de Unity, talvez tenham algo integrado com o OS.

Alguém mais reparou aquela barra preta do Windows Gaming quando inicia o jogo? É a mesma que aparece com Win+G ou em jogos, para clipar tela, fazer stream, etc.

Aqui ao menos sempre aparece quando eu inicio o jogo, começou após a atualização, então deve ter algo relacionado.

Se alguém que é dev de game e sabe como isso funciona com a unity, dê uma luz aí para nós.

**Comment by Dfcrespi** [comment]
Seria melhor não usar o bot por agora então... sendo que todos que estiverem usando estará clicando no mesmo lugar?

**Comment by rnesheiksilvestre** [comment]
> 

se for bot simples de repetição de movimentos sem detectação da pra fazer pelo jitbit facil com detecção tbm dá

**Comment by madDANET** [comment]
> Pessoal, hoje vi o comunicado dos admins abaixo, aparentemente estão monitorando a tela de alguma forma.
> 
> No windows eu já percebi que o microsoft gaming abre quando o jogo inicia, no linux obiamente nao. Apenas para alertar e para que fiquem atentos com possíveis bans já que na home está descrito que ainda não haviam se pronunciado.
> 
> **Am I allowed to use a Bot/Auto-clicker/macros?** No! Since 1/12/2021 you are completely prohibited from using bot/auto-clicker/macros! Bombcrypto is saving users movements and ID's in order to ban accounts from using this kind of software, please do not use bots!

Use BRAVE browser it disables movement sensors on bombcrypto

**Comment by fguide** [comment]
> > Pessoal, hoje vi o comunicado dos admins abaixo, aparentemente estão monitorando a tela de alguma forma.
> > No windows eu já percebi que o microsoft gaming abre quando o jogo inicia, no linux obiamente nao. Apenas para alertar e para que fiquem atentos com possíveis bans já que na home está descrito que ainda não haviam se pronunciado.
> > **Am I allowed to use a Bot/Auto-clicker/macros?** No! Since 1/12/2021 you are completely prohibited from using bot/auto-clicker/macros! Bombcrypto is saving users movements and ID's in order to ban accounts from using this kind of software, please do not use bots!
> 
> Use BRAVE browser it disables movement sensors on bombcrypto

Thanks mate, I'll check it.

**Comment by Yumiizera** [comment]
> > Pessoal, hoje vi o comunicado dos admins abaixo, aparentemente estão monitorando a tela de alguma forma.
> > No windows eu já percebi que o microsoft gaming abre quando o jogo inicia, no linux obiamente nao. Apenas para alertar e para que fiquem atentos com possíveis bans já que na home está descrito que ainda não haviam se pronunciado.
> > **Am I allowed to use a Bot/Auto-clicker/macros?** No! Since 1/12/2021 you are completely prohibited from using bot/auto-clicker/macros! Bombcrypto is saving users movements and ID's in order to ban accounts from using this kind of software, please do not use bots!
> 
> Use BRAVE browser it disables movement sensors on bombcrypto

E como desativaria o sensor de movimento pelo Brave?

**Comment by mgramelich** [comment]
> > Cara, fazendo esses ajustes, vai ficar muito _safe_. É muito dificil dectar macros, além do que eles rodam no navegador, que não disponibiliza tanto recursos para decção assim...
> 
> O navegador em si não, mas sinceramente não entendo nada de Unity, talvez tenham algo integrado com o OS.
> 
> Alguém mais reparou aquela barra preta do Windows Gaming quando inicia o jogo? É a mesma que aparece com Win+G ou em jogos, para clipar tela, fazer stream, etc.
> 
> Aqui ao menos sempre aparece quando eu inicio o jogo, começou após a atualização, então deve ter algo relacionado.
> 
> Se alguém que é dev de game e sabe como isso funciona com a unity, dê uma luz aí para nós.

Aqui não aparece essa barra do Windows não, tanto em VM quanto no real

**Comment by Mikebriza** [comment]
> BRAVE browser it disables movement sensors

Vai nas config do BRAVE, na lupa no canto direito superior digita "sensor", ele ja vai destacar que está no menu de "sites e proteção". Clica nele, vai em "permissões adicionais" e a opção pro sensor vai estar la

**Comment by newerton** [comment]
> Bom pessoal, não sei como será a implementação de melhoria de código à respeito desse track. Mas procurando no código do bomb, achei esse pedaço de código que pelo que pesquisei ele grava o movimento do mouse. Eu iria colocar aqui o caminho pro script, mas não sei o quão errado isso seria. Mas enfim, quando a feature de melhora não for mais o puzzle, creio que podemos ir mais a fundo nesse carinha
> 
> ```
>     canvas.addEventListener("click", (function(ev) {
>         if (!Browser.pointerLock && Module["canvas"].requestPointerLock) {
>             Module["canvas"].requestPointerLock();
>             ev.preventDefault()
>         }
>     }), false)
> }}})
> ```

Esse código só está identificando se o ponteiro do mouse ficou travado ao clicar.

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock

**Comment by Gaboo134** [comment]
galera vocês estão conseguindo rodar normal com o capt? baixei o puzzle e não identificou

**Comment by Gaboo134** [comment]
no caso esse sensor de movimento é o mesmo que da para desativar no chrome? pelo chrome://settings/content/sensors ou somente no navegador BRAVE que tem essa possibilidade

**Comment by newerton** [comment]
> no caso esse sensor de movimento é o mesmo que da para desativar no chrome? pelo chrome://settings/content/sensors ou somente no navegador BRAVE que tem essa possibilidade

Esse sensor é de movimento e sensor de luz. Não capta nenhum sensor de mouse.

**Comment by LuisBonatti** [comment]
> > Bom pessoal, não sei como será a implementação de melhoria de código à respeito desse track. Mas procurando no código do bomb, achei esse pedaço de código que pelo que pesquisei ele grava o movimento do mouse. Eu iria colocar aqui o caminho pro script, mas não sei o quão errado isso seria. Mas enfim, quando a feature de melhora não for mais o puzzle, creio que podemos ir mais a fundo nesse carinha
> > ```
> >     canvas.addEventListener("click", (function(ev) {
> >         if (!Browser.pointerLock && Module["canvas"].requestPointerLock) {
> >             Module["canvas"].requestPointerLock();
> >             ev.preventDefault()
> >         }
> >     }), false)
> > }}})
> > ```
> 
> Esse código só está identificando se o ponteiro do mouse ficou travado ao clicar.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock

Bom, viajei então na pesquisa haha

Mas ai, tu como um bom 'frontender' sabe dizer o que o bomb poderia usar pra identificar esse bot?

**Comment by newerton** [comment]
> > > Bom pessoal, não sei como será a implementação de melhoria de código à respeito desse track. Mas procurando no código do bomb, achei esse pedaço de código que pelo que pesquisei ele grava o movimento do mouse. Eu iria colocar aqui o caminho pro script, mas não sei o quão errado isso seria. Mas enfim, quando a feature de melhora não for mais o puzzle, creio que podemos ir mais a fundo nesse carinha
> > > ```
> > >     canvas.addEventListener("click", (function(ev) {
> > >         if (!Browser.pointerLock && Module["canvas"].requestPointerLock) {
> > >             Module["canvas"].requestPointerLock();
> > >             ev.preventDefault()
> > >         }
> > >     }), false)
> > > }}})
> > > ```
> > 
> > 
> > Esse código só está identificando se o ponteiro do mouse ficou travado ao clicar.
> > https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock
> 
> Bom, viajei então na pesquisa haha
> 
> Mas ai, tu como um bom 'frontender' sabe dizer o que o bomb poderia usar pra identificar esse bot?

Hoje não tem nada implementado nos javascript do site, que coleta essas informações. Primeiro eles tem que resolver esse problema de infra. Mas acho que o bot não é a preocupação deles, eles deveria se preocupar mais com bugs do jogo (unity) que faz com que usuários dobre o valor das recompensar, fazendo assim a queima da moeda ser mais rapida que o planejado.

**Comment by acacioosorio** [comment]
Capaz do Tracking do mouse estar sendo feito pelo Firebase.

Ainda sim é perigoso, dar uma "randomizada" no percurso do Mouse até o ponto variar um pouco onde ele clica já torna o bot safe.

Estou pensando em ver isso aqui e fazer um Pull Request, mas ando meio sem tempo

**Comment by newerton** [comment]
> Capaz do Tracking do mouse estar sendo feito pelo Firebase.
> 
> Ainda sim é perigoso, dar uma "randomizada" no percurso do Mouse até o ponto variar um pouco onde ele clica já torna o bot safe.
> 
> Estou pensando em ver isso aqui e fazer um Pull Request, mas ando meio sem tempo

De onde você tirou que o firebase está capturando evento de mouse? Nem no firebase-app.js e firebase-analytcis.js, não existe nenhum evento de mouse dentro desses arquivos.
