### ISSUE TITLE
peuqeno gigante problema ao executar esse comando ( i already use version 3.10) pip install --upgrade opencv-python==4.5.3.56

### ISSUE THREAD

**Issue by madDANET** [mpcabete/bombcrypto-bot#107]
C:\Users\Maddanet>pip install --upgrade opencv-python==4.5.3.56
Collecting opencv-python==4.5.3.56
  Using cached opencv-python-4.5.3.56.tar.gz (89.2 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\Maddanet\AppData\Local\Temp\pip-standalone-pip-7_i_l5im\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\Maddanet\AppData\Local\Temp\pip-build-env-od81nivr\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version>='"'"'3.6'"'"' and sys_platform == '"'"'linux'"'"' and platform_machine == '"'"'aarch64'"'"'' 'numpy==1.21.0; python_version>='"'"'3.6'"'"' and sys_platform == '"'"'darwin'"'"' and platform_machine == '"'"'arm64'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version>='"'"'3.9'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"''
       cwd: None
  Complete output (235 lines):
  Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.6" and sys_platform == "linux" and platform_machine == "aarch64"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Collecting setuptools
    Using cached setuptools-59.4.0-py3-none-any.whl (952 kB)
  Collecting wheel
    Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Collecting scikit-build
    Using cached scikit_build-0.12.0-py2.py3-none-any.whl (73 kB)
  Collecting cmake
    Using cached cmake-3.22.0-py2.py3-none-win_amd64.whl (38.1 MB)
  Collecting pip
    Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
  Collecting numpy==1.19.3
    Using cached numpy-1.19.3.zip (7.3 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\Maddanet\AppData\Local\Temp\tmpg_t39gxl_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Maddanet\AppData\Local\Temp\tmpt0qg895c'
         cwd: C:\Users\Maddanet\AppData\Local\Temp\pip-install-um63dx75\numpy_3ee5d29ef8be481284123466a0f12ca3
    Complete output (204 lines):
    setup.py:67: RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.10.
      warnings.warn(
    Running from numpy source directory.
    setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    C:\Users\Maddanet\AppData\Local\Temp\pip-install-um63dx75\numpy_3ee5d29ef8be481284123466a0f12ca3\tools\cythonize.py:67: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      from distutils.version import LooseVersion
    Processing numpy/random\_bounded_integers.pxd.in
    Processing numpy/random\bit_generator.pyx
    Processing numpy/random\mtrand.pyx
    Processing numpy/random\_bounded_integers.pyx.in
    Processing numpy/random\_common.pyx
    Processing numpy/random\_generator.pyx
    Processing numpy/random\_mt19937.pyx
    Processing numpy/random\_pcg64.pyx
    Processing numpy/random\_philox.pyx
    Processing numpy/random\_sfc64.pyx
    Cythonizing sources
    blas_opt_info:
    blas_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    C:\Users\Maddanet\AppData\Local\Temp\pip-install-um63dx75\numpy_3ee5d29ef8be481284123466a0f12ca3\numpy\distutils\system_info.py:1914: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    blas_info:
      libraries blas not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    C:\Users\Maddanet\AppData\Local\Temp\pip-install-um63dx75\numpy_3ee5d29ef8be481284123466a0f12ca3\numpy\distutils\system_info.py:1914: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    blas_src_info:
      NOT AVAILABLE

    C:\Users\Maddanet\AppData\Local\Temp\pip-install-um63dx75\numpy_3ee5d29ef8be481284123466a0f12ca3\numpy\distutils\system_info.py:1914: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
      NOT AVAILABLE

    non-existing path in 'numpy\\distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\lib
      libraries tatlas,tatlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\lib
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\libs
      libraries tatlas,tatlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\lib
      libraries satlas,satlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\lib
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\libs
      libraries satlas,satlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\lib
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\libs
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\lib
      libraries f77blas,cblas,atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\lib
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\libs
      libraries f77blas,cblas,atlas not found in C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\', 'C:\\Users\\Maddanet\\AppData\\Local\\Programs\\Python\\Python310\\libs']
      NOT AVAILABLE

    C:\Users\Maddanet\AppData\Local\Temp\pip-install-um63dx75\numpy_3ee5d29ef8be481284123466a0f12ca3\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE

    C:\Users\Maddanet\AppData\Local\Temp\pip-install-um63dx75\numpy_3ee5d29ef8be481284123466a0f12ca3\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    numpy_linalg_lapack_lite:
      FOUND:
        language = c
        define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

    C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running dist_info
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build\src.win-amd64-3.10
    creating build\src.win-amd64-3.10\numpy
    creating build\src.win-amd64-3.10\numpy\distutils
    building library "npymath" sources
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
  WARNING: Discarding https://files.pythonhosted.org/packages/cb/c0/7b3d69e6ee68bc54c97ba51f8c3c3e43ff1dbc7bd97347cc19a1f944e60a/numpy-1.19.3.zip#sha256=35bf5316af8dc7c7db1ad45bec603e5fb28671beb98ebd1d65e8059efcfd3b72 (from https://pypi.org/simple/numpy/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\Maddanet\AppData\Local\Temp\tmpg_t39gxl_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Maddanet\AppData\Local\Temp\tmpt0qg895c' Check the logs for full command output.
  ERROR: Could not find a version that satisfies the requirement numpy==1.19.3 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0rc1, 1.20.0rc2, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0rc1, 1.21.0rc2, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.22.0rc1)
  ERROR: No matching distribution found for numpy==1.19.3
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/01/9b/be08992293fb21faf35ab98e06924d7407fcfca89d89c5de65442631556a/opencv-python-4.5.3.56.tar.gz#sha256=3c001d3feec7f3140f1fb78dfc52ca28122db8240826882d175a208a89d2731b (from https://pypi.org/simple/opencv-python/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\Users\Maddanet\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\Maddanet\AppData\Local\Temp\pip-standalone-pip-7_i_l5im\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\Maddanet\AppData\Local\Temp\pip-build-env-od81nivr\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version>='"'"'3.6'"'"' and sys_platform == '"'"'linux'"'"' and platform_machine == '"'"'aarch64'"'"'' 'numpy==1.21.0; python_version>='"'"'3.6'"'"' and sys_platform == '"'"'darwin'"'"' and platform_machine == '"'"'arm64'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version>='"'"'3.9'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement opencv-python==4.5.3.56 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60)
ERROR: No matching distribution found for opencv-python==4.5.3.56

**Comment by fguide** [comment]
as per this error:

> error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

I think you should start by checking if you have build tools installed, looks like this is where the build error happens.

Not very familiarized with Windows, though I was able to run it without updating open-cv when I tested.

**Comment by nickksoares** [comment]
Yes, you need to install the C++ development for windows tools

**Comment by dionatharibeiro** [comment]
Boa noite,
Isto ocorre devido a sua versão do Python, possivelmente baixou a 3.10, e ela da mesmo este erro, baixe a versão 3.9.11 ou 3.9.10 e problema resolvido.
