### ISSUE TITLE
Bot com anticaptcha nao manda pta trabalhar

### ISSUE THREAD

**Issue by amatoxd** [mpcabete/bombcrypto-bot#109]
Entao, o anticaptcha ta funcionando perfeitamente, bem como o bot tambem entra no inventario pra mandar os herois pro campo minado e tudo mais, porém o bot acaba saindo e nao manda nenhum ptra trabalhar, nem mesmo os verdes, e tb n arrasta a barrinha pra baixo pra ver todos. Alguem conhece uma forma pra solucionar?

**Comment by fguide** [comment]
Como descrito na página principal, o merge oficial ainda nao foi lancado, se voce fez por sua conta nao temos como ajudar.

Sugiro aguardar sair o merge oficial, assim podemos ajudar com o suporte.

**Comment by THEBESTSZ** [comment]
> Como descrito na página principal, o merge oficial ainda nao foi lancado, se voce fez por sua conta nao temos como ajudar.
> 
> Sugiro aguardar sair o merge oficial, assim podemos ajudar com o suporte.

você poderia me passar a sua versão com merge, por favor?

**Comment by fguide** [comment]
A branch puzzle ja esta com o merge o feito, porem versao alpha ainda, possivel que tenha alguns erros.

**Comment by amatoxd** [comment]
> A branch puzzle ja esta com o merge o feito, porem versao alpha ainda, possivel que tenha alguns erros.
> 
> Sugiro olhar os outros topicos aqui tambem, porque agora o uso de bot esta oficialmente proibido, portanto atente-se com a seguranca.

Eu tô mesmo com 2 errinhos chatos: não tá mais entrando no jogo automaticamente, ou seja, conectando a carteira e assinando, e nem mandando mais pro trabalho. Porém resolve o captcha, entra nos menus e dá new map normalmente. O jeito é esperar o merge, ou esperar alguem mandando a correção, que tenha tido o msm problema.

**Comment by llFerreira** [comment]
> > A branch puzzle ja esta com o merge o feito, porem versao alpha ainda, possivel que tenha alguns erros.
> > Sugiro olhar os outros topicos aqui tambem, porque agora o uso de bot esta oficialmente proibido, portanto atente-se com a seguranca.
> 
> Eu tô mesmo com 2 errinhos chatos: não tá mais entrando no jogo automaticamente, ou seja, conectando a carteira e assinando, e nem mandando mais pro trabalho. Porém resolve o captcha, entra nos menus e dá new map normalmente. O jeito é esperar o merge, ou esperar alguem mandando a correção, que tenha tido o msm problema.

se for o erro que eu consegui identificar e corrigir, é so tu dar uma olhada no #111
