### ISSUE TITLE
ajustes finos no puzzle

### ISSUE THREAD

**Issue by jeanvetorello** [mpcabete/bombcrypto-bot#110]
Boa tarde, Estou  testando o anti captcha e está rolando super bem,

segue algumas sugestões. 

colocar uma opçao no config de X tempo verificar o capcha  semelhante ao  check disconncet. e se não conseguir resolver, dar um reload na pagina.

**Comment by jeanvetorello** [comment]
algumas vezes acontece esse erro

puzzle not found
Traceback (most recent call last):
  File "index.py", line 589, in <module>
    main()
  File "index.py", line 576, in main
    solveCapcha()
  File "index.py", line 225, in solveCapcha
    piece_end, _, _, _ = getRightPiece(pieces_end_pos)
  File "index.py", line 125, in getRightPiece
    xs = [row[0] for row in puzzle_pieces]
TypeError: 'NoneType' object is not iterable

**Comment by mpcabete** [comment]
Opa, ta feito chefe! hehehe
