### ISSUE TITLE
Corrigindo pequeno erro no envio dos herois

### ISSUE THREAD

**Issue by llFerreira** [mpcabete/bombcrypto-bot#111]
Boa tarde, amigo. Encontrei um pequeno erro no codigo que impossibilita dele enviar os herois para o mapa, segue abaixo o erro na linha 435. Ao inves de ser: 

solveCapcha()
    # time.sleep(5)
clickBtn(hero_img)
    # time.sleep(5)

É:

clickBtn(hero_img)
    # time.sleep(5)
solveCapcha()
    # time.sleep(5)

Primeiro ele verifica o capcha para depois clicar no envio, porém o capcha é depois do click. 
Espero ter ajudado :)
![Screenshot 2021-12-03 171033](https://user-images.githubusercontent.com/41524514/144667517-05b090bf-03c5-4190-91a6-c032f13b99b4.png)

**Comment by yassbeno** [comment]
Testado e aprovado

**Comment by amatoxd** [comment]
> clickBtn(hero_img)
> # time.sleep(5)
> solveCapcha()
> # time.sleep(5)

No meu, o bot até manda pra trabalhar, investigando minuciosamente, mas o meu problema mesmo é que após fazer o captcha, ele vai pra tela dos heróis, fica alguns poucos minutos la parado, nao coloca ngm para trabalhar, e volta pro mapa com todos dormindo, mesmo todos full. Esse é o erro que seu código corrige?

**Comment by fguide** [comment]
Eu fiz dessa maneira também e realmente funciona, o solveCapcha() deve ficar abaixo do clickBtn().

**Comment by llFerreira** [comment]
> > clickBtn(hero_img)
> > # time.sleep(5)
> > solveCapcha()
> > # time.sleep(5)
> 
> No meu, o bot até manda pra trabalhar, investigando minuciosamente, mas o meu problema mesmo é que após fazer o captcha, ele vai pra tela dos heróis, fica alguns poucos minutos la parado, nao coloca ngm para trabalhar, e volta pro mapa com todos dormindo, mesmo todos full. Esse é o erro que seu código corrige?

Nao, o meu ele verificava o capcha antes de clicar no heroi, porem o capcha aparece so depois de clicar e nao antes como ta no codigo. Isso eu corrigi, agora esse problema seu ai nao sei, baixa os arquivos denovo e muda isso ai que falei e testa pra ver, custa nada :)

**Comment by llFerreira** [comment]
> > Eu fiz dessa maneira também e realmente funciona, o solveCapcha() deve ficar abaixo do clickBtn().
> 
> Sou meio leigo nesse quesito. Qual arquivo dentro da pasta eu abro para substituir a linha de código? E qual aplicativo eu posso usar pra abri-lo? Desde já, muito obrigado!

O arquivo INDEX, clica com o botao direito nele e tem a opcao de EDIT WITH IDLE, apos isso, tu desce ate a linha que informei e inverte a posiçao deles

**Comment by amatoxd** [comment]
> > > clickBtn(hero_img)
> > > # time.sleep(5)
> > > solveCapcha()
> > > # time.sleep(5)
> > 
> > 
> > No meu, o bot até manda pra trabalhar, investigando minuciosamente, mas o meu problema mesmo é que após fazer o captcha, ele vai pra tela dos heróis, fica alguns poucos minutos la parado, nao coloca ngm para trabalhar, e volta pro mapa com todos dormindo, mesmo todos full. Esse é o erro que seu código corrige?
> 
> Nao, o meu ele verificava o capcha antes de clicar no heroi, porem o capcha aparece so depois de clicar e nao antes como ta no codigo. Isso eu corrigi, agora esse problema seu ai nao sei, baixa os arquivos denovo e muda isso ai que falei e testa pra ver, custa nada :)

Vou tentar sim, obrigado, às vzs é o mesmo erro, porém eu não te expliquei direito. Sobre meu reply acima, vc pode tirar essa duvida, por favor? Obgd.

**Comment by llFerreira** [comment]
> > > > clickBtn(hero_img)
> > > > # time.sleep(5)
> > > > solveCapcha()
> > > > # time.sleep(5)
> > > 
> > > 
> > > No meu, o bot até manda pra trabalhar, investigando minuciosamente, mas o meu problema mesmo é que após fazer o captcha, ele vai pra tela dos heróis, fica alguns poucos minutos la parado, nao coloca ngm para trabalhar, e volta pro mapa com todos dormindo, mesmo todos full. Esse é o erro que seu código corrige?
> > 
> > 
> > Nao, o meu ele verificava o capcha antes de clicar no heroi, porem o capcha aparece so depois de clicar e nao antes como ta no codigo. Isso eu corrigi, agora esse problema seu ai nao sei, baixa os arquivos denovo e muda isso ai que falei e testa pra ver, custa nada :)
> 
> Vou tentar sim, obrigado, às vzs é o mesmo erro, porém eu não te expliquei direito. Sobre meu reply acima, vc pode tirar essa duvida, por favor? Obgd.

Me chama no discord que é melhor pra explicar e entender, Ferreira#7417 . Ou entao, faz como falei no comentario acima que respondi no lugar do outro rapaz

**Comment by amatoxd** [comment]
> > > > > clickBtn(hero_img)
> > > > > # time.sleep(5)
> > > > > solveCapcha()
> > > > > # time.sleep(5)
> > > > 
> > > > 
> > > > No meu, o bot até manda pra trabalhar, investigando minuciosamente, mas o meu problema mesmo é que após fazer o captcha, ele vai pra tela dos heróis, fica alguns poucos minutos la parado, nao coloca ngm para trabalhar, e volta pro mapa com todos dormindo, mesmo todos full. Esse é o erro que seu código corrige?
> > > 
> > > 
> > > Nao, o meu ele verificava o capcha antes de clicar no heroi, porem o capcha aparece so depois de clicar e nao antes como ta no codigo. Isso eu corrigi, agora esse problema seu ai nao sei, baixa os arquivos denovo e muda isso ai que falei e testa pra ver, custa nada :)
> > 
> > 
> > Vou tentar sim, obrigado, às vzs é o mesmo erro, porém eu não te expliquei direito. Sobre meu reply acima, vc pode tirar essa duvida, por favor? Obgd.
> 
> Me chama no discord que é melhor pra explicar e entender, Ferreira#7417 . Ou entao, faz como falei no comentario acima que respondi no lugar do outro rapaz

Agr que eu vi seu comentário acima, não havia recarregado a página, mt obrigado @llFerreira

**Comment by itxtoledo** [comment]
Você tem que criar uma PR

**Comment by amatoxd** [comment]
@llFerreira Fiz aqui e agr ele não tá fazendo o captcha quando sai do mapa pra clicar em Heroes. Aparece isso no CMD:
![BOMB](https://user-images.githubusercontent.com/95452652/144671859-c04a9dc6-4456-4e6a-948f-62aa1a4bc3e5.png)

O que eu alterei foi isso:

![image](https://user-images.githubusercontent.com/95452652/144671982-ba6f3863-730d-4526-bdc6-57524861673c.png)

**Comment by amatoxd** [comment]
Agr q eu vi q escrevi captcha, deve ser isso kkkkkkkkk

**Comment by llFerreira** [comment]
> Agr q eu vi q escrevi captcha, deve ser isso kkkkkkkkk

funcionou? e tu ta abrindo ele pelo cmd ou abrindo direto? Eu abro direto e nao ta ocorrendo error nenhum ainda

**Comment by amatoxd** [comment]
> > Agr q eu vi q escrevi captcha, deve ser isso kkkkkkkkk
> 
> funcionou? e tu ta abrindo ele pelo cmd ou abrindo direto? Eu abro direto e nao ta ocorrendo error nenhum ainda

To abrindo pelo cmd. Como nao ta sincronizando bem, ja q meus heroes tao tudo sem energia, n da pra saber ainda. Vou ficar monitorando até acontecer o q eu tava tendo de problema e falo pra ver se solucionou

**Comment by amatoxd** [comment]
Acabou de mandar pro work, mas não apareceu o captcha ainda. Vou continuar monitorando!

**Comment by mpcabete** [comment]
Opa amigo, obrigado pela sugestao, eu tinha colocado antes pq quano tava testano ontem, o captcha apareceu logo q o bot clickou no botao de voltar, n tinha reparado q ele pedia dps de clickar no heroi as vezes. Vou colocar ele pra checar antes e depois, ai nao tem erro! hehehe

**Comment by llFerreira** [comment]
> 

Tem capcha na tela principal? Nao sabia. Entao o codjgo esta correto, so tem que adicionar mais um capcha hehehehe

**Comment by amatoxd** [comment]
> > 
> 
> Tem capcha na tela principal? Nao sabia. Entao o codjgo esta correto, so tem que adicionar mais um capcha hehehehe

Deu certo, mano! Valeu mesmo, agr vou esperar o merge do mpcabete pra corrigir quando o capcha vem antes, qd clica no botão de voltar kkk Vc sabe o que tem que adicionar às linhas de codigos pra isso?

**Comment by llFerreira** [comment]
> > > 
> > 
> > 
> > Tem capcha na tela principal? Nao sabia. Entao o codjgo esta correto, so tem que adicionar mais um capcha hehehehe
> 
> Deu certo, mano! Valeu mesmo, agr vou esperar o merge do mpcabete pra corrigir quando o capcha vem antes, qd clica no botão de voltar kkk Vc sabe o que tem que adicionar às linhas de codigos pra isso?

Sim, é so adiciionar mais uma linha do capcha em cima do click, que ai vai ficar SolveCapcha.... click...solvecapcha
Eu estou pelo google remote e por isso nao consigo envjar o formato certo, mas é so colocar mais um capcha em cima do click que da certo

**Comment by fguide** [comment]
Fiz o meu fork para testes:

https://github.com/fguide/bombcrypto-bot

**Comment by amatoxd** [comment]
> Fiz o meu fork para testes:
> 
> https://github.com/fguide/bombcrypto-bot

Seu fork tem a solução do capcha antes e apos o envio dos herois? Se sim vou usa-lo hahhaeaw

**Comment by fguide** [comment]
Eu rodei por boas horas com ele sem problemas, faz um teste para saber com certeza.

**Comment by amatoxd** [comment]
![image](https://user-images.githubusercontent.com/95452652/144683206-71ae63e3-089f-4265-b999-f2e6d50bd282.png)


@llFerreira deu esse erro quando foi mudar de mapa e aí o bot parou de funcionar. Sabe alguma soluçao?

**Comment by llFerreira** [comment]
> ![image](https://user-images.githubusercontent.com/95452652/144683206-71ae63e3-089f-4265-b999-f2e6d50bd282.png)
> 
> @llFerreira deu esse erro quando foi mudar de mapa e aí o bot parou de funcionar. Sabe alguma soluçao?

cheguei agora em casa, pelo oque entendi, ele deu erro ao movimento o ponteiro/mouse para o botao de new map. Isso so o criador do macro que sabe, eu entendo so 1% de programaçao kkkkk
