### ISSUE TITLE
KeyError: 'check_for_capcha'

### ISSUE THREAD

**Issue by Igorlegacy** [mpcabete/bombcrypto-bot#114]
`def main():
    time.sleep(5)
    t = c['time_intervals']

    last = {
    "login" : 0,
    "heroes" : 0,
    "new_map" : 0,
    "check_for_capcha" : 0,
    "refresh_heroes" : 0
    }

    while True:
        now = time.time()

        if now - last["check_for_capcha"] > t['check_for_capcha'] * 60:
            last["check_for_capcha"] = now
            logger('Checking for capcha.')
            solveCapcha()

        if now - last["heroes"] > t['send_heroes_for_work'] * 60:
            last["heroes"] = now
            logger('Sending heroes to work.')
            refreshHeroes()

        if now - last["login"] > t['check_for_login'] * 60:
            logger("Checking if game has disconnected.")
            sys.stdout.flush()
            last["login"] = now
            login()

        if now - last["new_map"] > t['check_for_new_map_button']:
            last["new_map"] = now
            if clickBtn(new_map_btn_img):
                with open('new-map.log','a') as new_map_log:
                    new_map_log.write(str(time.time())+'\n')
                logger('New Map button clicked!')

        if now - last["refresh_heroes"] > t['refresh_heroes_positions'] * 60 :
            solveCapcha()
            last["refresh_heroes"] = now
            logger('Refreshing Heroes Positions.')
            refreshHeroesPositions()

        #clickBtn(teasureHunt)
        logger(None, progress_indicator=True)

        sys.stdout.flush()

        time.sleep(1)

main()`

`Traceback (most recent call last):
  File "C:\bomb\index.py", line 592, in <module>
    main()
  File "C:\bomb\index.py", line 555, in main
    if now - last["check_for_capcha"] > t['check_for_capcha'] * 60:
KeyError: 'check_for_capcha'`

**Comment by mpcabete** [comment]
hey, have you download only the index.py right, there was a change also in the config.yaml, try downloading the whole bot as an zip again
