### ISSUE TITLE
Bot depois da att

### ISSUE THREAD

**Issue by wanderaugusto** [mpcabete/bombcrypto-bot#116]
Galera o bot ta randomizado? alguem ai ja ta usando e pode falar se levou ban ou se corre esse risco ?

**Comment by Nydoehar** [comment]
Estou usando e ate agora não fui banido; mas o risco existe.

**Comment by wanderaugusto** [comment]
> Estou usando e ate agora não fui banido; mas o risco existe.

vc randonizou os movimentos?
