### ISSUE TITLE
Quais as chances do BOT ser detectado?

### ISSUE THREAD

**Issue by Nydoehar** [mpcabete/bombcrypto-bot#117]
Pergunta para os programadores de plantão: 

1. O BOT é fácil de ser detectado pelos Devs? 
2. É possível torná-lo mais difícil de ser detectado?

**Comment by ppchlrie97** [comment]
Essa resposta está no leia me do arquivo amigo.

**Comment by Nydoehar** [comment]
> Essa resposta está no leia me do arquivo amigo.

"O bot não interage diretamente com o jogo, ele somente tira print da tela do game para encontrar os botões e simula movimentos do mouse, isso faz com que diferenciar o bot de um humano seja muito difícil." - - - É isso?

Acho que me expressei mal, eu gostaria de saber quais métodos são usados para identificar um bot. Ou seja, o que os programadores do jogo podem fazer para tentar detectar um bot? Gravar a tela? Analisar os movimentos do mouse??

**Comment by ppchlrie97** [comment]
https://github.com/mpcabete/bombcrypto-bot/issues/106

vai te ajudar amigo

**Comment by Nydoehar** [comment]
> #106
> 
> vai te ajudar amigo

Obriagado, era isso mesmo. Li esse tópico hoje de manhã mas queria confirmar.
