### ISSUE TITLE
Auto click não acontece ao encaixar o quebra cabeça

### ISSUE THREAD

**Issue by ppchlrie97** [mpcabete/bombcrypto-bot#118]
Opa tudo bem? Primeiramente mt obg por tudo! Funcionou perfeitamente pra mim antes dessa nova atualização do bomb, esperei vocês terminarem de dar o update no bot pra voltar a usar, baixei ainda agora e funciona tudo certo, menos no início do jogo no encaixe da peça, ele coloca lá certinho, mas não clica, sendo assim não abre o bomb, poderia me salvar? Valeu!!!
Logo menos contribuirei também no projeto!

**Comment by jhonsstn** [comment]
Não sei se e o mesmo problema que esta tendo, mas o problema aqui é que se a função de resolver o captcha que estiver rodando for a que e acionada durante o jogo para por os heróis para trabalhar, o bot não procura pelo botão de login da Metamask. Ele só procura o botão da Metamask se for a primeira interação dele com o jogo, usando a função login().

**Comment by ppchlrie97** [comment]
Não é isso não brother, é somente o encaixe da peça que não ocorre, fica parado e não clica novamente, sendo assim ficam trocando as figuras e ele não consegue entrar no jogo.
