### ISSUE TITLE
Anticaptcha falha em acertar localização da peça do puzzle

### ISSUE THREAD

**Issue by doranelle** [mpcabete/bombcrypto-bot#119]
Após a troca de todas as targets (menos a piece.png pois não sei como gerá-la) o bot iniciou o funcionamento, mas ao reconhecer o captcha desliza o botão muito rapidamente até o final e volta devagar, mas não acerta a localização, gerando o aparecimento de outro captcha infinitamente até eventual erro no jogo.

**Comment by Gaboo134** [comment]
ocorreu isso comigo também, ele tentou 2 captcha, estava olhando então fiz o terceiro manualmente, ele acerta somente o que esta na imagem puzzle ou estou enganado

**Comment by Gaboo134** [comment]
bom dia alguém conseguindo rodar normal decifrando os pluzzle

**Comment by Nydoehar** [comment]
> bom dia alguém conseguindo rodar normal decifrando os pluzzle

O meu está funcionando bem, estou usando a versão main que ele atualizou ontem.

**Comment by doranelle** [comment]
eu estou com a última versão também, mas segue sem conseguir resolver

**Comment by ppchlrie97** [comment]
O meu também na última versão, mas ainda não funciona.

**Comment by doranelle** [comment]
Tentei redimensionar a imagem de acordo com a minha resolução, mas sem sucesso.

**Comment by amatoxd** [comment]
Aqui funcionando normal. Só baixei a main, desinstalei a anterior e reinstalei os requirements. O único erro que acontece às vezes é que ele faz o captcha e acaba não colocando nenhum boneco pra trabalhar, volta pro mapa e só depois de alguns minutos ele volta novamente e coloca os bonecos para trabalhar.

**Comment by ppchlrie97** [comment]
Como desinstalo o main anterior ? 
só exclui e coloquei o novo na pasta, não sei se esse é o erro

**Comment by ppchlrie97** [comment]
> Aqui funcionando normal. Só baixei a main, desinstalei a anterior e reinstalei os requirements. O único erro que acontece às vezes é que ele faz o captcha e acaba não colocando nenhum boneco pra trabalhar, volta pro mapa e só depois de alguns minutos ele volta novamente e coloca os bonecos para trabalhar.

Desinstalei a main e coloquei a nova, mesmo assim na hora que ele coloca a peça no lugar não clica, sendo assim não abre.

**Comment by raphaeldan** [comment]
como vocÊs desinstalaram a antiga? EU deletei a pasta, descompactei e rodei o  pip install -r requirements.txt

Poderiam descrever o processo de desinstalar e instalar a nova versão?

**Comment by raphaeldan** [comment]
segue erro

Traceback (most recent call last):
File "C:\bomb\index.py", line 593, in
main()
File "C:\bomb\index.py", line 559, in main
solveCapcha()
File "C:\bomb\index.py", line 208, in solveCapcha
pieces_start_pos = getPiecesPosition()
File "C:\bomb\index.py", line 151, in getPiecesPosition
popup_pos = positions(robot)
File "C:\bomb\index.py", line 327, in positions
result = cv2.matchTemplate(img,target,cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

**Comment by doranelle** [comment]
Eu estou com a versão correta e todos os requisitos instalados, acredito que seja mesmo a substituição da imagem.

**Comment by raphaeldan** [comment]
> Eu estou com a versão correta e todos os requisitos instalados, acredito que seja mesmo a substituição da imagem.

Você tirou alguma print de algo da tela?

Eu só deletei a pasta antiga, baixei a nova e rodei

**Comment by doranelle** [comment]
> > Eu estou com a versão correta e todos os requisitos instalados, acredito que seja mesmo a substituição da imagem.
> 
> Você tirou alguma print de algo da tela?
> 
> Eu só deletei a pasta antiga, baixei a nova e rodei
> 

Eu tentei! Tentei com o print da peça editado no ps e com a imagem original redimensionada. Como eu não usei as outras versões já cheguei direto nessa última com o merge!!

**Comment by ppchlrie97** [comment]
> > > Eu estou com a versão correta e todos os requisitos instalados, acredito que seja mesmo a substituição da imagem.
> > 
> > 
> > Você tirou alguma print de algo da tela?
> > Eu só deletei a pasta antiga, baixei a nova e rodei
> 
> Eu tentei! Tentei com o print da peça editado no ps e com a imagem original redimensionada. Como eu não usei as outras versões já cheguei direto nessa última com o merge!!

queria só meu sono de volta kkkkk

**Comment by doranelle** [comment]
> > > > Eu estou com a versão correta e todos os requisitos instalados, acredito que seja mesmo a substituição da imagem.
> > > 
> > > 
> > > Você tirou alguma print de algo da tela?
> > > Eu só deletei a pasta antiga, baixei a nova e rodei
> > 
> > Eu tentei! Tentei com o print da peça editado no ps e com a imagem original redimensionada. Como eu não usei as outras versões já cheguei direto nessa última com o merge!!
> 
> queria só meu sono de volta kkkkk

@mpcabete ajuda a gente por favor? 😅

**Comment by ppchlrie97** [comment]
> > > > > Eu estou com a versão correta e todos os requisitos instalados, acredito que seja mesmo a substituição da imagem.
> > > > 
> > > > 
> > > > Você tirou alguma print de algo da tela?
> > > > Eu só deletei a pasta antiga, baixei a nova e rodei
> > > 
> > > 
> > > Eu tentei! Tentei com o print da peça editado no ps e com a imagem original redimensionada. Como eu não usei as outras versões já cheguei direto nessa última com o merge!!
> > 
> > 
> > queria só meu sono de volta kkkkk
> 
> @mpcabete ajuda a gente por favor? 😅

OI! Conseguiu resolver?

**Comment by doranelle** [comment]
> > > > > > Eu estou com a versão correta e todos os requisitos instalados, acredito que seja mesmo a substituição da imagem.
> > > > > 
> > > > > 
> > > > > Você tirou alguma print de algo da tela?
> > > > > Eu só deletei a pasta antiga, baixei a nova e rodei
> > > > 
> > > > 
> > > > Eu tentei! Tentei com o print da peça editado no ps e com a imagem original redimensionada. Como eu não usei as outras versões já cheguei direto nessa última com o merge!!
> > > 
> > > 
> > > queria só meu sono de volta kkkkk
> > 
> > @mpcabete ajuda a gente por favor? 😅
> 
> OI! Conseguiu resolver? 

Ainda não
