### ISSUE TITLE
O bot funciona na VM?

### ISSUE THREAD

**Issue by mvpalves** [mpcabete/bombcrypto-bot#12]
Olá! Parabéns pelo projeto! Está ajudando muita gente com ele! :D

Tenho 3 contas no jogo, então iria usar 3 VMs distintas para usar o bot. O problema é que não consegui fazer funcionar kkk

Instalei conforme instruído, incluindo todas as dependencias, porém, ao iniciar o bot ele não faz **nenhuma** ação no jogo, mas também não da nenhum erro. Até reparei o Python e reiniciei a VM, porém, sem sucesso.

Ele fica assim infinito:
![bot_bombcrypto](https://user-images.githubusercontent.com/94149149/141387249-9a9cd736-de09-4754-a4da-fb5fc7241a96.jpg)

Estou usando o Oracle VM VirtualBox, com um ISO do Windows 10 64 bits.

Será que to esquecendo de algo? kkk

Vlwzão pelo help!

**Comment by mvpalves** [comment]
Aaahhhh muleque, deu certo hahaha

Vou deixar a dúvida aqui para se caso alguém tenha o mesmo problema.

COMO RESOLVI:
Era problema na resolução, o jogo tem que estar na resolução de 100% para que o Bot funcione.
Foi só colocar 100% que começou a funcionar


Vlwww <3

**Comment by mpcabete** [comment]
Que bom que conseguiu : ) , se você estiver feliz com o bot e puder fazer uma contribuição eu ficaria muito feliz ^-^
