### ISSUE TITLE
Algumas observações sobre solveCapcha e time.sleep

### ISSUE THREAD

**Issue by Malk4viano** [mpcabete/bombcrypto-bot#120]
Boa noite @mpcabete, sou um programador iniciante e tenho algumas sugestões em relação a quando chamar os métodos solveCapcha() e time.sleep.
Não entendo perfeitamente o seu código para saber até que ponto seria bom ou a partir de quando seria exagero implementar essas minhas sugestões, porém espero contribuir.

Até agora, observei que é necessário chamar o método solveCapcha() sempre após a clicar em um dos botões a seguir: new_map_btn_img, arrow_img, hero_img, teasureHunt_icon_img, connect_wallet_btn_img.

Pelo o que eu entendi de seu código, que nem sempre após o bot clicar em um desses botões o método solveCapcha() esta sendo chamado. Acho que seria interessante estar implementando sempre após todos eles. Fiz por conta própria essa modificação aqui nos meus arquivos locais e após isso aparentou não estar ficando mais travado em nenhum captcha.

Outra implementação que fiz, mas não tenho certeza se é realmente necessária, ou se já está sendo realizada pelo seu código, foi adicionar um time.sleep(1) ao final do "def solveCapcha()" e sempre antes e depois de todos os clickBtn() referentes aos botões que citei acima.

Espero que tenha me feito entender.

Agora uma dúvida que tenho em relação a algumas aleatoriedades que foram comentadas em outros issues aqui do git.
Você chegou a vê-las? Tem previsão de implementar alguma delas?

Obrigado pelo seu tempo e dedicação, seu trabalho é muito bom!

**Comment by rnesheiksilvestre** [comment]
> Boa noite @mpcabete, sou um programador iniciante e tenho algumas sugestões em relação a quando chamar os métodos solveCapcha() e time.sleep. Não entendo perfeitamente o seu código para saber até que ponto seria bom ou a partir de quando seria exagero implementar essas minhas sugestões, porém espero contribuir.
> 
> Até agora, observei que é necessário chamar o método solveCapcha() sempre após a clicar em um dos botões a seguir: new_map_btn_img, arrow_img, hero_img, teasureHunt_icon_img, connect_wallet_btn_img.
> 
> Pelo o que eu entendi de seu código, que nem sempre após o bot clicar em um desses botões o método solveCapcha() esta sendo chamado. Acho que seria interessante estar implementando sempre após todos eles. Fiz por conta própria essa modificação aqui nos meus arquivos locais e após isso aparentou não estar ficando mais travado em nenhum captcha.
> 
> Outra implementação que fiz, mas não tenho certeza se é realmente necessária, ou se já está sendo realizada pelo seu código, foi adicionar um time.sleep(1) ao final do "def solveCapcha()" e sempre antes e depois de todos os clickBtn() referentes aos botões que citei acima.
> 
> Espero que tenha me feito entender.
> 
> Agora uma dúvida que tenho em relação a algumas aleatoriedades que foram comentadas em outros issues aqui do git. Você chegou a vê-las? Tem previsão de implementar alguma delas?
> 
> Obrigado pelo seu tempo e dedicação, seu trabalho é muito bom!

boa noite mano, poderia me da um help como eu poderia adicionar um time random no codigo do mpcabete para executar o macro, agradeço

**Comment by HugoZanco** [comment]
> > Boa noite @mpcabete, sou um programador iniciante e tenho algumas sugestões em relação a quando chamar os métodos solveCapcha() e time.sleep. Não entendo perfeitamente o seu código para saber até que ponto seria bom ou a partir de quando seria exagero implementar essas minhas sugestões, porém espero contribuir.
> > Até agora, observei que é necessário chamar o método solveCapcha() sempre após a clicar em um dos botões a seguir: new_map_btn_img, arrow_img, hero_img, teasureHunt_icon_img, connect_wallet_btn_img.
> > Pelo o que eu entendi de seu código, que nem sempre após o bot clicar em um desses botões o método solveCapcha() esta sendo chamado. Acho que seria interessante estar implementando sempre após todos eles. Fiz por conta própria essa modificação aqui nos meus arquivos locais e após isso aparentou não estar ficando mais travado em nenhum captcha.
> > Outra implementação que fiz, mas não tenho certeza se é realmente necessária, ou se já está sendo realizada pelo seu código, foi adicionar um time.sleep(1) ao final do "def solveCapcha()" e sempre antes e depois de todos os clickBtn() referentes aos botões que citei acima.
> > Espero que tenha me feito entender.
> > Agora uma dúvida que tenho em relação a algumas aleatoriedades que foram comentadas em outros issues aqui do git. Você chegou a vê-las? Tem previsão de implementar alguma delas?
> > Obrigado pelo seu tempo e dedicação, seu trabalho é muito bom!
> 
> boa noite mano, poderia me da um help como eu poderia adicionar um time random no codigo do mpcabete para executar o macro, agradeço

Eu não entendo sobre essa parte, mano. Vi algumas pessoas comentando sobre nos outros issues que tem aberto aqui no git. Da uma procurada ai que talvez você consiga tirar sua duvida ou ajuda de alguém que entenda. Foi mal

**Comment by rnesheiksilvestre** [comment]
> > > Boa noite @mpcabete, sou um programador iniciante e tenho algumas sugestões em relação a quando chamar os métodos solveCapcha() e time.sleep. Não entendo perfeitamente o seu código para saber até que ponto seria bom ou a partir de quando seria exagero implementar essas minhas sugestões, porém espero contribuir.
> > > Até agora, observei que é necessário chamar o método solveCapcha() sempre após a clicar em um dos botões a seguir: new_map_btn_img, arrow_img, hero_img, teasureHunt_icon_img, connect_wallet_btn_img.
> > > Pelo o que eu entendi de seu código, que nem sempre após o bot clicar em um desses botões o método solveCapcha() esta sendo chamado. Acho que seria interessante estar implementando sempre após todos eles. Fiz por conta própria essa modificação aqui nos meus arquivos locais e após isso aparentou não estar ficando mais travado em nenhum captcha.
> > > Outra implementação que fiz, mas não tenho certeza se é realmente necessária, ou se já está sendo realizada pelo seu código, foi adicionar um time.sleep(1) ao final do "def solveCapcha()" e sempre antes e depois de todos os clickBtn() referentes aos botões que citei acima.
> > > Espero que tenha me feito entender.
> > > Agora uma dúvida que tenho em relação a algumas aleatoriedades que foram comentadas em outros issues aqui do git. Você chegou a vê-las? Tem previsão de implementar alguma delas?
> > > Obrigado pelo seu tempo e dedicação, seu trabalho é muito bom!
> > 
> > 
> > boa noite mano, poderia me da um help como eu poderia adicionar um time random no codigo do mpcabete para executar o macro, agradeço
> 
> Eu não entendo sobre essa parte, mano. Vi algumas pessoas comentando sobre nos outros issues que tem aberto aqui no git. Da uma procurada ai que talvez você consiga tirar sua duvida ou ajuda de alguém que entenda. Foi mal

de boa mano é que na parte do time ele chama uma variavel e não manjo muito de python então não sei como implementar um random ali
