### ISSUE TITLE
Alguem já está usando ? Como está ?

### ISSUE THREAD

**Issue by nezkaum** [mpcabete/bombcrypto-bot#121]
Pessoal que já está utilizando, como está indo ? Tranquilo ? Estou querendo voltar a usar já e gostaria de saber do feedback de vocês. @mpcabete seu trampo é foda irmão, quando sacar já te mando aquela moral, tmjj

**Comment by FDNiisan** [comment]
Cara... 
Eu estou usando desde ontem.
Apesar do bot se perder as vezes, ele tá indo muito bem

**Comment by Nydoehar** [comment]
> Pessoal que já está utilizando, como está indo ? Tranquilo ? Estou querendo voltar a usar já e gostaria de saber do feedback de vocês. @mpcabete seu trampo é foda irmão, quando sacar já te mando aquela moral, tmjj



> Cara... Eu estou usando desde ontem. Apesar do bot se perder as vezes, ele tá indo muito bem

O mesmo comigo: "Apesar do bot se perder as vezes, ele tá indo muito bem"

**Comment by alexandernicacio** [comment]
como faço pra pegar essa versão que já esta funcionando parcialmente?

**Comment by FDNiisan** [comment]
> como faço pra pegar essa versão que já esta funcionando parcialmente?

Só substituir os arquivos da pasta que está instalado o script.
Hoje o bot tá 110%
