### ISSUE TITLE
Como aplicar o randommovimentmouse?

### ISSUE THREAD

**Issue by THEBESTSZ** [mpcabete/bombcrypto-bot#123]
Eu vi essa função em um tópico atrás do usuário "jotapepinheiro":

def randomMouseMovement():
    effects = [
        pyautogui.easeInQuad, 
        pyautogui.easeOutQuad, 
        pyautogui.easeInOutQuad,
        pyautogui.easeInBounce,
        pyautogui.easeInElastic
        ]
    x = np.random.randint(0, c['screen_width'])
    y = np.random.randint(0, c['screen_height'])
    e = np.random.choice(effects)
    pyautogui.moveTo(x, y, np.random.randint(1,2), e)

Fiquei na dúvida em como encaixar ela dentro do código, alguém saberia como?

**Comment by Nydoehar** [comment]
> Eu vi essa função em um tópico atrás do usuário "jotapepinheiro":
> 
> def randomMouseMovement(): effects = [ pyautogui.easeInQuad, pyautogui.easeOutQuad, pyautogui.easeInOutQuad, pyautogui.easeInBounce, pyautogui.easeInElastic ] x = np.random.randint(0, c['screen_width']) y = np.random.randint(0, c['screen_height']) e = np.random.choice(effects) pyautogui.moveTo(x, y, np.random.randint(1,2), e)
> 
> Fiquei na dúvida em como encaixar ela dentro do código, alguém saberia como?

Eu tambem gostaria de saber.

**Comment by wanderaugusto** [comment]
Galera pelo pouco que entendo da pra soltar em qualquer lugar ai na parte inicial do bot que funciona

**Comment by Alt4s** [comment]
Gostaria que isto funcionasse
