### ISSUE TITLE
I want to know how to find the piece image

### ISSUE THREAD

**Issue by kaofang38573** [mpcabete/bombcrypto-bot#124]
I want to know how to find the piece image because I have my screen size set to 50% it's not working, what should I do?
please help me

**Comment by doranelle** [comment]
@mpcabete I would also like to know if possible, it's the only step remaining for the bot to work perfectly here.

**Comment by cesarfran12** [comment]
you have to set screen size to 100% otherwise it wont work

**Comment by kaofang38573** [comment]
> you have to set screen size to 100% otherwise it wont work

Because I want to continue to develop it to open 50%, so I want a way to find a piece.

**Comment by mpcabete** [comment]
try uncommenting the show function on line 183, and then tanking a printscreen. I had to edit it a little bit in photoshop to remove some of the pixels in the middle, but it may work with just the print

**Comment by ppchlrie97** [comment]
> @mpcabete I would also like to know if possible, it's the only step remaining for the bot to work perfectly here.

Conseguiu colocando uma nova imagem?

**Comment by doranelle** [comment]
> > @mpcabete I would also like to know if possible, it's the only step remaining for the bot to work perfectly here.
> 
> Conseguiu colocando uma nova imagem?

Ainda não. Vou ajustar a linha 187 como o @mpcabete falou, mas até então com a imagem do print editada e a original redimensionada não funcionou.

**Comment by ppchlrie97** [comment]
> > > @mpcabete I would also like to know if possible, it's the only step remaining for the bot to work perfectly here.
> > 
> > 
> > Conseguiu colocando uma nova imagem?
> 
> Ainda não. Vou ajustar a linha 183 como o @mpcabete falou, mas até então com a imagem do print editada e a original redimensionada não funcionou.

Aqui também n foi, @mpcabete salva a gente please

**Comment by doranelle** [comment]
> > > @mpcabete I would also like to know if possible, it's the only step remaining for the bot to work perfectly here.
> > 
> > 
> > Conseguiu colocando uma nova imagem?
> 
> Ainda não. Vou ajustar a linha 183 como o @mpcabete falou, mas até então com a imagem do print editada e a original redimensionada não funcionou.

@mpcabete usei a imagem gerada com o print (linha 183) e seguiu dando o mesmo erro, limpei a imagem também no photoshop e deixei o mais semelhante possível à do código original, sem sucesso.

**Comment by kaofang38573** [comment]
![img](https://user-images.githubusercontent.com/58837369/144744238-36fe2554-e001-4f0e-a4ee-66ede0a8d5bf.png)
@mpcabete What should I do to make the image centered?
