### ISSUE TITLE
Aparece isto !

### ISSUE THREAD

**Issue by Logiko94** [mpcabete/bombcrypto-bot#125]
o meu continua a aparecer isto
C:\Bomb>python index.py
Traceback (most recent call last):
  File "C:\Bomb\index.py", line 1, in <module>
    from cv2 import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by cesarfran12** [comment]
abre cmd 
cd\bomb
pip install -r requirements.txt 

deve funcionar depois

**Comment by Logiko94** [comment]
> 

C:\Bomb>pip install -r requisitos.txt
'pip' is not recognized as an internal or external command,
operable program or batch file.
