### ISSUE TITLE
esse bot pode dar ban?

### ISSUE THREAD

**Issue by thierryboiago** [mpcabete/bombcrypto-bot#13]
eu posso levar ban na minha conta se usar isso? é um risco?

**Comment by mvpalves** [comment]
Thierry, pelo o que eu entendi é muito difícil você levar ban usando esse BOT.

Ele não abre nenhum programa de macro/bot, roda direto pelo console/cmd. E ele também não injeta nada no jogo, ele apenas lê a tela e clica onde precisa ser clicado.

Então acho muuuito difícil dar merda por causa do BOT em si.

**Comment by thierryboiago** [comment]
funciona no mac? se n souber vou tentar kkk

**Comment by mvpalves** [comment]
Eu instalei aqui dentro de uma Virtual Machine (Oracle VM Virtual Box). Dessa forma eu posso minimizar e continuar usando o PC normalmente, já que a máquina está sendo emulada.

Instalei no Ubuntu pra consumir menos memória/processamento.

Tem funcionado perfeito aqui

**Comment by mpcabete** [comment]
Cara, o risco sempre existe, não me responsabilizo case role algo. Dito isso, tenho usado a bastante tempo e não deu ban ainda.
