### ISSUE TITLE
telegram function req

### ISSUE THREAD

**Issue by mkroxm** [mpcabete/bombcrypto-bot#130]
Hello, I Really Appreciate yours work it's just awesome it would be more better if we will include telegram remote function

like send logs, screenshot , start stop bot from telegram 
it's just suggestions if you will like you can include else ignore  

Thanks once again

**Comment by juniortopanotti** [comment]
Like this? I've already made this function, its pretty easy. Maybe i make a pull request to introduce this feature.
![image](https://user-images.githubusercontent.com/19753097/144745274-07801537-6f6b-46e6-af14-e3fe2a80983d.png)

**Comment by mkroxm** [comment]
@juniortopanotti  Well That would b Nice :) 👍

**Comment by kerferber** [comment]
@juniortopanotti Excelente, se quiser compartilhar como você fez isso, seria muito bom. Obrigado

**Comment by kerferber** [comment]
> Like this? I've already made this function, its pretty easy. Maybe i make a pull request to introduce this feature. ![image](https://user-images.githubusercontent.com/19753097/144745274-07801537-6f6b-46e6-af14-e3fe2a80983d.png)

Consegui enviar mensagens via  telegram com o código abaixo:
`import requests

def telegram_bot_sendtext(bot_message):
    bot_token = 'API_XXX'
    bot_chatID = 'ID_XXX'
    send_text = 'https://api.telegram.org/bot' + bot_token + '/sendMessage?chat_id=' + bot_chatID + '&parse_mode=Markdown&text=' + bot_message
    response = requests.get(send_text)
    return response.json()

test = telegram_bot_sendtext("Fernando iniciou Bot. É hora de faturar alguns BCoins!!!")`


Incluí este código em alguns locais abaixo da função de grava no logger e está funcionando bem, porém não tenho ideia de como fez para enviar o print com o saldo em Bcoins. Alguma luz por favor?

**Comment by kerferber** [comment]
Consegui implementar os avisos por telegram.

O Dr Lagarto é zoação kkk ainda tô arrumando.

Coloquei pra avisar qdo:
- o bot for ligado
- quando enviar algum herói full para minerar. Nesse caso sempre que enviar um herói enviará o saldo também.
- e quando desbloquear novo mapa irá enviar saldo.

![Uploading Screenshot_20211206-202320_Telegram.jpg…]()

**Comment by kerferber** [comment]
Posso colocar aqui como fiz, lembrando que não sou programador, apenas fiz algumas adaptações
