### ISSUE TITLE
Problema quando o jogo fica carregando

### ISSUE THREAD

**Issue by THEBESTSZ** [mpcabete/bombcrypto-bot#131]
Opa glr, blz?

Então, como o título sugere, quando o jogo fica carregando infinitamente e fica preso em uma porcentagem, basicamente percebi que o o bot não detecta isso e não dá f5, então considero que é um problema, alguém passou por isso? Como resolveu?

**Comment by jeanvetorello** [comment]
Teria que ter um contorno de a cada x tempo dar um f5 na pagina localmente coloquei um refresh a cada 45 min na pagina

**Comment by raphaeldan** [comment]
> Teria que ter um contorno de a cada x tempo dar um f5 na pagina localmente coloquei um refresh a cada 45 min na pagina

como você fez isso?

**Comment by guirar** [comment]
https://github.com/mpcabete/bombcrypto-bot/pull/84

**Comment by fguide** [comment]
A #115 é semelhante para aguardar a tela dos herois carregarem.
