### ISSUE TITLE
[Feature] Log estilizado

### ISSUE THREAD

**Issue by newerton** [mpcabete/bombcrypto-bot#133]
@mpcabete Dei uma estilizada no log, para futuras implementações de comunicação com o Telegram de algumas ações do bot.

MR: https://github.com/mpcabete/bombcrypto-bot/pull/132

Preview:
![image](https://user-images.githubusercontent.com/4175945/144725967-6aa5f3f7-66b1-4d78-9f7c-390cf6efb7a5.png)

**Comment by Nucito** [comment]
Very good 👍

**Comment by TeteuInfinity** [comment]
> @mpcabete Dei uma estilizada no log, para futuras implementações de comunicação com o Telegram de algumas ações do bot.
> 
> MR: #132
> 
> Preview: ![image](https://user-images.githubusercontent.com/4175945/144725967-6aa5f3f7-66b1-4d78-9f7c-390cf6efb7a5.png)

o do vin350 e seguro de usar? https://github.com/newerton/bombcrypto-bot
