### ISSUE TITLE
RANDOMIZAR

### ISSUE THREAD

**Issue by Alt4s** [mpcabete/bombcrypto-bot#134]
Olá pessoal, alguém consegue fazer um comando para randomizar os clicks na tela, e também deixar os tempos para verificar herois e voltar telas mais randômicos? 

Também dá para colocar um comando de clicar no baú, como se estivesse vendo quantos bcoin foram ganhos até o momento, de tempos em tempos, não tão curtos

Assim dá para ficar mais tranquilo, sem neurar com detecção de bot

**Comment by gabrielwjesus** [comment]
https://github.com/gabrielwjesus/bcryp
eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. 
agora o movimento do mouse eu não sei se é tão importante

**Comment by Nucito** [comment]
> https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante

So faltou clonar o repositório completo... tente criar um fork e modificar as opções... assim fica mais facil de usar sua modificação :)

**Comment by gabrielwjesus** [comment]
> > https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante
> 
> So faltou clonar o repositório completo... tente criar um fork e modificar as opções... assim fica mais facil de usar sua modificação :)

eu não manjo mto de github ainda, estou tentando aprender pra ajudar a atualizar o projeto do mpcabete. 
por isso que não copiei o resto dos arquivos mas só aqueles que estou modificando.

**Comment by kerferber** [comment]
> > > https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante
> > 
> > 
> > So faltou clonar o repositório completo... tente criar um fork e modificar as opções... assim fica mais facil de usar sua modificação :)
> 
> eu não manjo mto de github ainda, estou tentando aprender pra ajudar a atualizar o projeto do mpcabete. por isso que não copiei o resto dos arquivos mas só aqueles que estou modificando.

Eu tbm não manjo muito de github mas gostei das tuas modificações. Deixa eu perguntar pra vc ou pra quem souber responder:

O mpcabete ou outros devs aqui do github costumam adicionar estas "melhorias" no seu próprio código? 

Pergunto pois existem outras melhorias interessantes, como as de tratamento de erro, e uma que chama o Solve Capcha sempre antes de qualquer tela, visto que aparentemente o capcha aparece em lugares aleatórios...

Centralizar todas essas modificações em um único código (o original) acredito que seria mais viável, Será que isso será feito pelo @mpcabete ? Obrigado

**Comment by gabrielwjesus** [comment]
> > > > https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante
> > > 
> > > 
> > > So faltou clonar o repositório completo... tente criar um fork e modificar as opções... assim fica mais facil de usar sua modificação :)
> > 
> > 
> > eu não manjo mto de github ainda, estou tentando aprender pra ajudar a atualizar o projeto do mpcabete. por isso que não copiei o resto dos arquivos mas só aqueles que estou modificando.
> 
> Eu tbm não manjo muito de github mas gostei das tuas modificações. Deixa eu perguntar pra vc ou pra quem souber responder:
> 
> O mpcabete ou outros devs aqui do github costumam adicionar estas "melhorias" no seu próprio código?
> 
> Pergunto pois existem outras melhorias interessantes, como as de tratamento de erro, e uma que chama o Solve Capcha sempre antes de qualquer tela, visto que aparentemente o capcha aparece em lugares aleatórios...
> 
> Centralizar todas essas modificações em um único código (o original) acredito que seria mais viável, Será que isso será feito pelo @mpcabete ? Obrigado

então, a minha versão ja esta fazendo isso, após realizar cada click ele procura pelo captcha e de tempos em tempos ele procura novamente. 
assim que eu aprender a fazer atualização e apoio no projeto do mpcabete eu vou levantar minhas atualizações 
mas aqui por enqto está rodando perfeito

**Comment by Nucito** [comment]
> > > > https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante
> > > 
> > > 
> > > So faltou clonar o repositório completo... tente criar um fork e modificar as opções... assim fica mais facil de usar sua modificação :)
> > 
> > 
> > eu não manjo mto de github ainda, estou tentando aprender pra ajudar a atualizar o projeto do mpcabete. por isso que não copiei o resto dos arquivos mas só aqueles que estou modificando.
> 
> Eu tbm não manjo muito de github mas gostei das tuas modificações. Deixa eu perguntar pra vc ou pra quem souber responder:
> 
> O mpcabete ou outros devs aqui do github costumam adicionar estas "melhorias" no seu próprio código?
> 
> Pergunto pois existem outras melhorias interessantes, como as de tratamento de erro, e uma que chama o Solve Capcha sempre antes de qualquer tela, visto que aparentemente o capcha aparece em lugares aleatórios...
> 
> Centralizar todas essas modificações em um único código (o original) acredito que seria mais viável, Será que isso será feito pelo @mpcabete ? Obrigado

Para centralizar tudo no repositório dele vc precisar criar um fork do projeto atual e dps lançar uma pull request com as modificações que vc fez, depois disso o dono do repositório precisa aprovar... mas no caso ja tem 5 pull e o mpcabete não aceitou nenhuma :D Recomendo vc apenas criar um fork e ir atualizando seu próprio código :)

**Comment by Nucito** [comment]
> > > > > https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante
> > > > 
> > > > 
> > > > So faltou clonar o repositório completo... tente criar um fork e modificar as opções... assim fica mais facil de usar sua modificação :)
> > > 
> > > 
> > > eu não manjo mto de github ainda, estou tentando aprender pra ajudar a atualizar o projeto do mpcabete. por isso que não copiei o resto dos arquivos mas só aqueles que estou modificando.
> > 
> > 
> > Eu tbm não manjo muito de github mas gostei das tuas modificações. Deixa eu perguntar pra vc ou pra quem souber responder:
> > O mpcabete ou outros devs aqui do github costumam adicionar estas "melhorias" no seu próprio código?
> > Pergunto pois existem outras melhorias interessantes, como as de tratamento de erro, e uma que chama o Solve Capcha sempre antes de qualquer tela, visto que aparentemente o capcha aparece em lugares aleatórios...
> > Centralizar todas essas modificações em um único código (o original) acredito que seria mais viável, Será que isso será feito pelo @mpcabete ? Obrigado
> 
> então, a minha versão ja esta fazendo isso, após realizar cada click ele procura pelo captcha e de tempos em tempos ele procura novamente. assim que eu aprender a fazer atualização e apoio no projeto do mpcabete eu vou levantar minhas atualizações mas aqui por enqto está rodando perfeito

Estou usando o codigo com as suas modificações e rodou perfeitamente 👍 Mas para facilitar tudo poderia deixar ele em formato OOP para deixar o codigo mais legivel.

**Comment by Alt4s** [comment]
Estou usando para testar. Existe uma modificação também para eleusar a nova tab de herois, o triangulo no meio inferior da tela , 
de outro usuário.Não sei como integrar ele

**Comment by PhScars** [comment]
Oi Pessoal, curti essa ideal de Randomizar tudo, tentei rodar aqui mas não sei se deu muito certo.
Basta baixar os arquivos e substituir na pasta, ou precisa fazer alguma coisa? Valeu gente

**Comment by mauriciobsilva** [comment]
Para randomizar eu alterei a funcao main() nas linhas que tem (* 60) eu coloquei (random.randint(60, 90)) não esquecer de colocar a (import random) no começo do fonte.

**Comment by eshabib** [comment]
> Oi Pessoal, curti essa ideal de Randomizar tudo, tentei rodar aqui mas não sei se deu muito certo. Basta baixar os arquivos e substituir na pasta, ou precisa fazer alguma coisa? Valeu gente

Também gostaria de saber como faz, fiquei meio perdido aqui hahah

**Comment by gabrielwjesus** [comment]
> > > > > https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante
> 
> > > > 
> 
> > > > 
> 
> > > > So faltou clonar o repositório completo... tente criar um fork e modificar as opções... assim fica mais facil de usar sua modificação :)
> 
> > > 
> 
> > > 
> 
> > > eu não manjo mto de github ainda, estou tentando aprender pra ajudar a atualizar o projeto do mpcabete. por isso que não copiei o resto dos arquivos mas só aqueles que estou modificando.
> 
> > 
> 
> > Eu tbm não manjo muito de github mas gostei das tuas modificações. Deixa eu perguntar pra vc ou pra quem souber responder:
> 
> > 
> 
> > O mpcabete ou outros devs aqui do github costumam adicionar estas "melhorias" no seu próprio código?
> 
> > 
> 
> > Pergunto pois existem outras melhorias interessantes, como as de tratamento de erro, e uma que chama o Solve Capcha sempre antes de qualquer tela, visto que aparentemente o capcha aparece em lugares aleatórios...
> 
> > 
> 
> > Centralizar todas essas modificações em um único código (o original) acredito que seria mais viável, Será que isso será feito pelo @mpcabete ? Obrigado
> 
> 
> 
> Para centralizar tudo no repositório dele vc precisar criar um fork do projeto atual e dps lançar uma pull request com as modificações que vc fez, depois disso o dono do repositório precisa aprovar... mas no caso ja tem 5 pull e o mpcabete não aceitou nenhuma :D Recomendo vc apenas criar um fork e ir atualizando seu próprio código :)

https://github.com/gabrielwjesus/bombcrypto-bot
Fork feito

**Comment by gabrielwjesus** [comment]
Nessa minha versão os arquivos são diferentes pois separei dois módulos 

Eu tinha feito ações randômicos mas estava lento de mais. Ainda vou corrigir isso.

Mas o tempo que ele realiza cada ação é randômica, o que já muda muita coisa

E na hora de escolher os heróis Tbem é randômico : ou todos ou só verdes ou só completos 

Gostei da ideia de clicar no baú pra ver o saldo ... só pra fazer de conta que está navegando 
Farei isso amanhã 

Outra coisa que meu fork está fazendo é:
Quando tem lag ele espera a próxima tela abrir por completo antes de realizar a próxima ação

**Comment by Nydoehar** [comment]
> Nessa minha versão os arquivos são diferentes pois separei dois módulos
> 
> Eu tinha feito ações randômicos mas estava lento de mais. Ainda vou corrigir isso.
> 
> Mas o tempo que ele realiza cada ação é randômica, o que já muda muita coisa
> 
> E na hora de escolher os heróis Tbem é randômico : ou todos ou só verdes ou só completos
> 
> Gostei da ideia de clicar no baú pra ver o saldo ... só pra fazer de conta que está navegando Farei isso amanhã
> 
> Outra coisa que meu fork está fazendo é: Quando tem lag ele espera a próxima tela abrir por completo antes de realizar a próxima ação

Ainda vou testar mas já deixo meu muito obrigado!!!

**Comment by jhonsstn** [comment]
> https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante

Referente ao movimento do mouse, essa implementação parece ser interessante. https://stackoverflow.com/questions/44467329/pyautogui-mouse-movement-with-bezier-curve

**Comment by PhScars** [comment]
> > > > > > https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > So faltou clonar o repositório completo... tente criar um fork e modificar as opções... assim fica mais facil de usar sua modificação :)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > eu não manjo mto de github ainda, estou tentando aprender pra ajudar a atualizar o projeto do mpcabete. por isso que não copiei o resto dos arquivos mas só aqueles que estou modificando.
> > 
> > 
> > > 
> > 
> > 
> > > Eu tbm não manjo muito de github mas gostei das tuas modificações. Deixa eu perguntar pra vc ou pra quem souber responder:
> > 
> > 
> > > 
> > 
> > 
> > > O mpcabete ou outros devs aqui do github costumam adicionar estas "melhorias" no seu próprio código?
> > 
> > 
> > > 
> > 
> > 
> > > Pergunto pois existem outras melhorias interessantes, como as de tratamento de erro, e uma que chama o Solve Capcha sempre antes de qualquer tela, visto que aparentemente o capcha aparece em lugares aleatórios...
> > 
> > 
> > > 
> > 
> > 
> > > Centralizar todas essas modificações em um único código (o original) acredito que seria mais viável, Será que isso será feito pelo @mpcabete ? Obrigado
> > 
> > 
> > Para centralizar tudo no repositório dele vc precisar criar um fork do projeto atual e dps lançar uma pull request com as modificações que vc fez, depois disso o dono do repositório precisa aprovar... mas no caso ja tem 5 pull e o mpcabete não aceitou nenhuma :D Recomendo vc apenas criar um fork e ir atualizando seu próprio código :)
> 
> https://github.com/gabrielwjesus/bombcrypto-bot Fork feito

Eu pecisei adicionar esses dois itens ao Requirements pra funcionar :)

numpy
pynput

**Comment by thecashi** [comment]
> Nessa minha versão os arquivos são diferentes pois separei dois módulos
> 
> Eu tinha feito ações randômicos mas estava lento de mais. Ainda vou corrigir isso.
> 
> Mas o tempo que ele realiza cada ação é randômica, o que já muda muita coisa
> 
> E na hora de escolher os heróis Tbem é randômico : ou todos ou só verdes ou só completos
> 
> Gostei da ideia de clicar no baú pra ver o saldo ... só pra fazer de conta que está navegando Farei isso amanhã
> 
> Outra coisa que meu fork está fazendo é: Quando tem lag ele espera a próxima tela abrir por completo antes de realizar a próxima ação

No seu projeto não tem a aba de Issues, o seu bot está dando erro no momento da seleção dos heróis para trabalho, baixei a última versão que lançou, onde atualizou o index.py.
![bot](https://user-images.githubusercontent.com/95629078/144870367-92a24ed5-1562-447b-8627-9adb6428bed6.png)

**Comment by gabrielwjesus** [comment]
> > Nessa minha versão os arquivos são diferentes pois separei dois módulos
> 
> > 
> 
> > Eu tinha feito ações randômicos mas estava lento de mais. Ainda vou corrigir isso.
> 
> > 
> 
> > Mas o tempo que ele realiza cada ação é randômica, o que já muda muita coisa
> 
> > 
> 
> > E na hora de escolher os heróis Tbem é randômico : ou todos ou só verdes ou só completos
> 
> > 
> 
> > Gostei da ideia de clicar no baú pra ver o saldo ... só pra fazer de conta que está navegando Farei isso amanhã
> 
> > 
> 
> > Outra coisa que meu fork está fazendo é: Quando tem lag ele espera a próxima tela abrir por completo antes de realizar a próxima ação
> 
> 
> 
> No seu projeto não tem a aba de Issues, o seu bot está dando erro no momento da seleção dos heróis para trabalho, baixei a última versão que lançou, onde atualizou o index.py.
> 
> ![bot](https://user-images.githubusercontent.com/95629078/144870367-92a24ed5-1562-447b-8627-9adb6428bed6.png)
> 
> 

Verifique as imagens na pasta target se estão todas iguais

**Comment by thecashi** [comment]
> 

Falta a home_btn_img = cv2.imread('targets/home.png'). Poderia atualizar os targets? Obrigado.

**Comment by raphaeldan** [comment]
up

**Comment by lifarrx** [comment]
Ótima implementação, pela experiência que tenho com uso de bots, para identificar um bot da forma que o jogo é aplicado, somente por padrões, se conseguir randomizar todas as ações fica impossível de identificar um bot.

Essa sua versão já está utilizável? ou precisa fazer alterações antes de usar ?
Se sim, poderia deixar uma explicação do que é necessário mexer ?

**Comment by PhScars** [comment]
Fala @gabrielwjesus tudo certo?
Gostaria de saber se é possível, ai serve como uma ideia, randomizar também a posição do clique, eu fiz de uma forma meio feia aqui kkkkk, tirei 5 prints e sorteio os prints onde ele deve clicar.
Mas se for possível randomizar a largura e a altura, ia ser bem mais pratico e ia ficar semi impossível a detecção.

**Comment by Franksinastra** [comment]
Alguem já foi pego utilizando o bot ? Ainda nao encontrei relatos... mas acho que com a randomização de movimentos e de tempo ficaria perfeito mesmo!

**Comment by raphaeldan** [comment]
> Alguem já foi pego utilizando o bot ? Ainda nao encontrei relatos... mas acho que com a randomização de movimentos e de tempo ficaria perfeito mesmo!

acho que ninguém foi pego, mas nao custa nada dificultarmos né?

Alguém mais entendido poderia nos ajudar?
Como funciona esse novo código?
Só colocar em outra pasta e chamar o comando python index?

**Comment by rodtanci** [comment]
> https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante

A randomização não teria que ficar em config onde você estipula os horários que vai ser feito os clicks ?

**Comment by rodtanci** [comment]
![16388256248231134253201276881562](https://user-images.githubusercontent.com/94814382/144924485-7e0c8970-1c77-4d90-a94d-d72913a6edfc.jpg)

Fui testar seu fork e me deparei com este erro, sabe me dizer oque é?

**Comment by rodtanci** [comment]
> são

![16388257307188559618968632817824](https://user-images.githubusercontent.com/94814382/144924658-058a3a0c-0bc8-47e9-8caa-9bbf4880b070.jpg)

Fui testar seu fork e me deparei com este erro, sabe me dizer oque está faltando ?

**Comment by rodtanci** [comment]
> > > > > > https://github.com/gabrielwjesus/bcryp eu deixei todo o main.py randomizável em todas as ações. E cada vez que ele vai fazer uma ação ele alterna o tempo novamente pra nunca fazer a mesma sequencia de ações e nunca levar o mesmo tempo para fazer cada ação. agora o movimento do mouse eu não sei se é tão importante
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > So faltou clonar o repositório completo... tente criar um fork e modificar as opções... assim fica mais facil de usar sua modificação :)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > eu não manjo mto de github ainda, estou tentando aprender pra ajudar a atualizar o projeto do mpcabete. por isso que não copiei o resto dos arquivos mas só aqueles que estou modificando.
> > 
> > 
> > > 
> > 
> > 
> > > Eu tbm não manjo muito de github mas gostei das tuas modificações. Deixa eu perguntar pra vc ou pra quem souber responder:
> > 
> > 
> > > 
> > 
> > 
> > > O mpcabete ou outros devs aqui do github costumam adicionar estas "melhorias" no seu próprio código?
> > 
> > 
> > > 
> > 
> > 
> > > Pergunto pois existem outras melhorias interessantes, como as de tratamento de erro, e uma que chama o Solve Capcha sempre antes de qualquer tela, visto que aparentemente o capcha aparece em lugares aleatórios...
> > 
> > 
> > > 
> > 
> > 
> > > Centralizar todas essas modificações em um único código (o original) acredito que seria mais viável, Será que isso será feito pelo @mpcabete ? Obrigado
> > 
> > 
> > Para centralizar tudo no repositório dele vc precisar criar um fork do projeto atual e dps lançar uma pull request com as modificações que vc fez, depois disso o dono do repositório precisa aprovar... mas no caso ja tem 5 pull e o mpcabete não aceitou nenhuma :D Recomendo vc apenas criar um fork e ir atualizando seu próprio código :)
> 
> https://github.com/gabrielwjesus/bombcrypto-bot Fork feito

 
![16388258802502693818148091841566](https://user-images.githubusercontent.com/94814382/144924988-080ac90b-6713-40b8-8945-a7093c05366c.jpg)
 
Referente ao seu fork está acusando este erro, sabe me dizer oque está faltando ?

**Comment by thecashi** [comment]
numpy
pynput

no requirements

**Comment by Budokay** [comment]
Galera ta dando esse erro comigo tbm.. oque fazer?
from pynput.mouse import Controller
ModuleNotFoundError: No module named 'pynput'

**Comment by lifarrx** [comment]
> Galera ta dando esse erro comigo tbm.. oque fazer? from pynput.mouse import Controller ModuleNotFoundError: No module named 'pynput'

tem que adicionar essas frases no arquivo requirements

numpy
pynput

e salvar o arquivo
pronto.

**Comment by rodtanci** [comment]
> numpy pynput
> 
> no requirements

Já foi adicionado e o erro persistente
![16388339020238300646512316596437](https://user-images.githubusercontent.com/94814382/144939854-231badc5-604c-42b8-9d0f-38e50a490ca6.jpg)

**Comment by Budokay** [comment]
é só utilizar o
pip install -r requirements.txt
de novo agora que você modificou

**Comment by Budokay** [comment]
> > Galera ta dando esse erro comigo tbm.. oque fazer? from pynput.mouse import Controller ModuleNotFoundError: No module named 'pynput'
> 
> tem que adicionar essas frases no arquivo requirements
> 
> numpy pynput
> 
> e salvar o arquivo pronto.

muito obrigado <3 me ajudou muito :) ta funcionando direitinho aqui

**Comment by lifarrx** [comment]
@gabrielwjesus o meu aqui quando abre a tela dos heros ele marca um tempinho depois atualiza a pagina, Heroes screen not loaded o erro, daí ele volta pro login, que hero screen é essa kk ?

**Comment by rodtanci** [comment]
> é só utilizar o pip install -r requirements.txt de novo agora que você modificou


Parece que foi, vou testar

**Comment by rodtanci** [comment]
Ele resolve o CAPTCHA e depois quando abre a metamask ele clica pra fora dela, minimizando ela e fazendo assim que ele não faça o login, alguém já teve esse problema ?

**Comment by raphaeldan** [comment]
fiz aqui o pip install -r requirements.txt com os numpy e pynput. Deixei rodando aqui, mas nao percebi muita diferença para o original. Poderia descrever o que ele faz exatamente de diferente e como?

obg pelo trabalho

**Comment by lifarrx** [comment]
@gabrielwjesus DICA de implementação, as vezes quando clica em conect e aparece a barra de carragamento ela trava em 50% 
85%
 20%
aconteceu aqui agora, o bot não consegue identificar, pois não da erro, simplesmente fica travado, seria legal implementar um F5 caso identificasse esse travamento, pra tentar logar novamente.

**Comment by gabrielwjesus** [comment]
> @gabrielwjesus DICA de implementação, as vezes quando clica em conect e aparece a barra de carragamento ela trava em 50% 
> 
> 85%
> 
>  20%
> 
> aconteceu aqui agora, o bot não consegue identificar, pois não da erro, simplesmente fica travado, seria legal implementar um F5 caso identificasse esse travamento, pra tentar logar novamente.
> 
> 

O bot continua rodando como se não tivesse visto erro, mas lá na frente ele vai verificar que algo tá errado e então reinicia, mas o processo é lento

**Comment by lifarrx** [comment]
> > @gabrielwjesus DICA de implementação, as vezes quando clica em conect e aparece a barra de carragamento ela trava em 50%
> > 85%
> > 20%
> > aconteceu aqui agora, o bot não consegue identificar, pois não da erro, simplesmente fica travado, seria legal implementar um F5 caso identificasse esse travamento, pra tentar logar novamente.
> 
> O bot continua rodando como se não tivesse visto erro, mas lá na frente ele vai verificar que algo tá errado e então reinicia, mas o processo é lento


Ahh blz, show então !! 

sabes dizer oque é esse hero screen still not loaded ? o meu aqui ta nessa, não manda nenhum boneco pro farm, daí tem uma contagem de 5 e reinicia a pagina.

**Comment by Psicrow** [comment]
gente a solução que achei aqui e creio que ta bem humana é essa
importar a lib random e usar o comando random.randrange
eu salvei a variancia dentro de 
randonrangeclick = int(random.randrange(-30, 30)) # (ele vai randomizar entre -30 até 30)
ai criei uma funçao de click assim:
ai todo click sai em uma variância aleatória de ente 30pixels,voce pode deixar pra alterar isso em botões que são pequenos, mas acho que 30px é uma taxa aceitável, até pq o bot do mpcabete clica no meio da img


```
def Click_Location(x, y, mb = 'LEFT'):

        pydirectinput.moveTo(x+self.randonrangeclick , y+self.randonrangeclick )
        pyautogui.click(button=mb)

        return True

```

**Comment by Franksinastra** [comment]
> gente a solução que achei aqui e creio que ta bem humana é essa importar a lib random e usar o comando random.randrange eu salvei a variancia dentro de randonrangeclick = int(random.randrange(-30, 30)) # (ele vai randomizar entre -30 até 30) ai criei uma funçao de click assim: ai todo click sai em uma variância aleatória de ente 30pixels,voce pode deixar pra alterar isso em botões que são pequenos, mas acho que 30px é uma taxa aceitável, até pq o bot do mpcabete clica no meio da img
> 
> ```
> def Click_Location(x, y, mb = 'LEFT'):
> 
>         pydirectinput.moveTo(x+randonrangeclick , y+randonrangeclick )
>         pyautogui.click(button=mb)
> 
>         return True
> ```

Poderia ajudar um leigo heheheh, to aprendendo ainda como funciona o bot e linguagem python

**Comment by morgado198028** [comment]
o bot esta constantemente a fazer refresh a pagina pk

**Comment by morgado198028** [comment]
anyone is getting this error 

Traceback (most recent call last):
  File "C:\bot\index.py", line 354, in <module>
    main()
  File "C:\bot\index.py", line 320, in main
    solveCapModule.solveCaptcha()
  File "C:\bot\solveCapModule.py", line 143, in solveCaptcha
    x,y = slider_start_pos
TypeError: cannot unpack non-iterable bool object
