### ISSUE TITLE
Tratamento de Erro

### ISSUE THREAD

**Issue by gabrielwjesus** [mpcabete/bombcrypto-bot#135]
A lentidão e quedas não é normal, parece ser proposital para pegar os bots
então as vezes demora de mais pra entrar em algumas telas 
voce clica pra ir em herois e a tela dos herois demora muito para abrir
precisava achar uma forma de criar um WHILE (enquanto a imagem não for da tela dos herois, aguarde).. 
ai quando aparecer a tela dos herois ele vai pra função de enviar herois

outro ponto é a tela de login na parte de porcentagem... as vezes demora de mais pra subir pra 100% e entrar no jogo
precisava fazer outro laço de While (enquanto a imagem não for da tela inicial do jogo, aguarde)

**Comment by newerton** [comment]
@gabrielwjesus Tem essa MR (https://github.com/mpcabete/bombcrypto-bot/pull/115) que é sobre aguardar a tela de herois ser carregada.

E essa MR (https://github.com/mpcabete/bombcrypto-bot/pull/84) e quando o jogo trava, ai faz um reload na página depois de alguns minutos travado.

**Comment by gabrielwjesus** [comment]
> @gabrielwjesus Tem essa MR (#115) que é sobre aguardar a tela de herois ser carregada.
> 
> E essa MR (#84) e quando o jogo trava, ai faz um reload na página depois de alguns minutos travado.

cara, excelente, foi alem do que eu estava tentando fazer 
na tela inicial aparece uns 3 tipos de mensagens que eu não sei se ja esta sendo tratado tbem
![image](https://user-images.githubusercontent.com/54075771/144732546-41e86120-7648-4b3a-bdf3-d46976ab2302.png)
outra falando do login failed e outra de um tipo de erro de conexão... 

no main o primeiro if é para enviar os players pro jogo, eu troquei pra primeiro verificar a conexão 
https://github.com/gabrielwjesus/bcryp
eu tbem separei algumas funções em modulo, tentando deixar o codigo mais organizado até mesmo para tratar os erros mais fácil 
alem de testar o tempo todo (apos qualquer click) se há captcha pra resolver
e coloquei random time para todas as ações do jogo.

**Comment by viniciusfontao** [comment]
Uma coisa que notei é que se depois de clicar em connect to wallet -> fazer o captcha -> demorar pra abrir a janela de da metamask com o botão de sign-in, as vezes o bot se perde e não clica no botão.
Na próxima "rodada" do fluxo, ele vai detectar que tem o botão de connect to wallet e tentar clicar nele, fazendo com que a janela da metamask vá pra trás do browser e ai ele não loga nunca

**Comment by gabrielwjesus** [comment]
Mais uma melhoria que precisa ser feita urgentemente e trabalharei nela hoje.
Ficar num laço de WHILE até aparecer a imagem da tela que precisamos.
Fica esperando até aparecer o conectar carteira antes de ir pro proximo passo
Fica esperando de novo até aparecer o botão de assinar (sign) antes de ir pro proximo passo
Fica esperando até aparecer a tela inicial do jogo antes de ir pro próximo passo
E assim por diante. 
Então a função é, fazer print screen da tela e verificar se a tela é a próxima tela que estamos esperando.
Se não for ele espera, se for segue para o próximo passo
Mas tem um limite de tempo de espera que será aleatorio entre 1 minuto a 5 minutos, estourando o tempo da CTRL + F5 para atualizar o jogo do zero e recomeçar 

alguem ai abre um grupo no telegram pra gente trabalhar em cima disso?

**Comment by amatoxd** [comment]
@gabrielwjesus Ola, boan oite. é só pegar seus arquivos e jogar na pasta do bot e substituir tudo?

**Comment by fguide** [comment]
> Mais uma melhoria que precisa ser feita urgentemente e trabalharei nela hoje. Ficar num laço de WHILE até aparecer a imagem da tela que precisamos. 


Isso esta feito para a tela dos herois na #115, pode servir de exemplo para outras telas também.

**Comment by gabrielwjesus** [comment]
> > Mais uma melhoria que precisa ser feita urgentemente e trabalharei nela hoje. Ficar num laço de WHILE até aparecer a imagem da tela que precisamos.
> 
> Isso esta feito para a tela dos herois na #115, pode servir de exemplo para outras telas também.

mas ele só esta fazendo na tela dos herois, eu fiz em todas as telas e em todas as funções, está funcionando legal aqui
fiz um fork (ainda estou aprendendo a mexer aqui no github)
Criei uma função chamada findImage pra usar no principal laço do while ... ele só vai entrar na função que estiver na tela, se não pula e vai pra próxima até descobrir em qual tela esta
https://github.com/gabrielwjesus/bombcrypto-bot

**Comment by amatoxd** [comment]
@gabrielwjesus no seu bot ele tem aquela função que o mbcapete adicionou de checar pelo capcha antes e depois de abrir a tela do heroes? No caso essa da imagem. Obrigado!
![image](https://user-images.githubusercontent.com/95452652/144769167-6cce8472-168c-4d8c-8822-cf64605db650.png)

**Comment by fguide** [comment]
> > > Mais uma melhoria que precisa ser feita urgentemente e trabalharei nela hoje. Ficar num laço de WHILE até aparecer a imagem da tela que precisamos.
> > 
> > 
> > Isso esta feito para a tela dos herois na #115, pode servir de exemplo para outras telas também.
> 
> mas ele só esta fazendo na tela dos herois, eu fiz em todas as telas e em todas as funções, está funcionando legal aqui fiz um fork (ainda estou aprendendo a mexer aqui no github) Criei uma função chamada findImage pra usar no principal laço do while ... ele só vai entrar na função que estiver na tela, se não pula e vai pra próxima até descobrir em qual tela esta https://github.com/gabrielwjesus/bombcrypto-bot

Dei uma olhada rápida, parece bem eficiente, faça um Pull Request para o branch main do projeto principal, dai fica mais fácil para outras pessoas verem e testarem.

**Comment by gabrielwjesus** [comment]
> @gabrielwjesus no seu bot ele tem aquela função que o mbcapete adicionou de checar pelo capcha antes e depois de abrir a tela do heroes? No caso essa da imagem. Obrigado! ![image](https://user-images.githubusercontent.com/95452652/144769167-6cce8472-168c-4d8c-8822-cf64605db650.png)

sim, na realidade ele verifica captcha constantemente e apos clicar em algum lugar

**Comment by amatoxd** [comment]
@gabrielwjesus ta dando esse erro 
![image](https://user-images.githubusercontent.com/95452652/144769584-a9465620-7028-44c9-b410-88e47294c6c5.png)

**Comment by gabrielwjesus** [comment]
> @gabrielwjesus ta dando esse erro 
> 
> ![image](https://user-images.githubusercontent.com/95452652/144769584-a9465620-7028-44c9-b410-88e47294c6c5.png)
> 
> 

pip install pynput 
 Tem que instalar esse modulo

**Comment by amatoxd** [comment]
Consegui, instalei o pynput. Procurei um tutorial.

**Comment by rodrigobragamg** [comment]
Gabriel, testei o seu script e notei que está com o mesmo "problema" (sendo detalhista) do script do mpcabete, que no caso é, se por algum motivo ficar parado na tela dos herois, ele não identifica e clica nos botões e volta ao mapa. Eu tinha feito um ajuste encima do dele, se quiser implementar no seu.

Por exemplo, junto to comando do Refreshheroes (que é executado por padrão a cada 3 mins), coloquei para ele identificar o botão "Work" e, se houver, ele botava para trabalhar e volta ao mapa:

`        if now - last["refresh_heroes"] > t['refresh_heroes_positions'] * 60 :
            last["refresh_heroes"] = now
            logger('Refreshing Heroes Positions.')
            refreshHeroesPositions()
            if clickBtn(commom_img):

                if c['select_heroes_mode'] == "full":
                    logger("Sending heroes with full stamina bar to work!")
                elif c['select_heroes_mode'] == "green":
                    logger("Sending heroes with green stamina bar to work!")

                buttonsClicked = 1
                empty_scrolls_attempts = 2

                while(empty_scrolls_attempts >0):
                    if c['select_heroes_mode'] == 'full':
                        buttonsClicked = clickFullBarButtons()
                    elif c['select_heroes_mode'] == 'green':
                        buttonsClicked = clickGreenBarButtons()
                    else:
                        buttonsClicked = clickButtons()

                    if buttonsClicked == 0:
                        empty_scrolls_attempts = empty_scrolls_attempts - 1
                    scroll()
                    sleep(randint(1,3))
            logger('{} heroes sent to work so far'.format(hero_clicks))
            goToGame()`

**Comment by rodrigobragamg** [comment]
OBS: O ajuste que fiz acima foi na pressa, bem tosco. Dá pra melhorar criando só uma seção e juntar ao config claro... Ou no caso do seu script, colocar um "or" no comando de colocar para trabalhar.

Mas, achei outro bug no seu cript... Faça um teste de iniciar script quando estiver na tela de "NEW MAP"... Ele vai entrar em loop e não fazer mais nada.

**Comment by gabrielwjesus** [comment]
Cara.
Perfeito.
A ideia é criar um laço de while que leia a tela e baseado na tela vá para sua função específica.
Então se está na tela com new map, clicar em ok
Se for mandar herois precisa ter algo da tela de heróis
Outra coisa
Se ele foi pra tela de heróis pra mandar os heróis e a tela ficar travada por alguns segundos e não exibir os heróis, então de um F5 e comece o jogo do zero

**Comment by BBencee** [comment]
@gabrielwjesus I've tested your script edit, https://github.com/gabrielwjesus/bombcrypto-bot 
I am writing you here because I could not open an issue at your github.
First of all thank you all for your work!

For some reason it gets stuck in a loop for some reason:

```
=> Waiting to show screen [[[ 83  73  64]
  [ 83  73  64]
  [146 146 132]
  ...
  [ 90  51  43]
  [ 90  51  43]
  [  0   0   0]]

 [[ 83  73  64]
  [ 83  73  64]
  [146 146 132]
  ...
  [ 90  51  43]
  [ 90  51  43]
  [  0   0   0]]

 [[172 151 132]
  [172 151 132]
  [255 255 255]
  ...
  [185 105  89]
  [185 105  89]
  [ 13   9   7]]
```
This is mainly after the game refreshes itself even if there is no problem, and I'm stuck at the login sreen. 

Also when I change the 10 mins send to work time to 40 mins it seems like the script does not care and send the heroes to work on a random time. Is it because the random trigger? Also it often selects all the heroes not just the ones with green stamina bar does not matter if its set to "green".

**Comment by gabrielwjesus** [comment]
> @gabrielwjesus I've tested your script edit, https://github.com/gabrielwjesus/bombcrypto-bot I am writing you here because I could not open an issue at your github. First of all thank you all for your work!
> 
> For some reason it gets stuck in a loop for some reason:
> 
> ```
> => Waiting to show screen [[[ 83  73  64]
>   [ 83  73  64]
>   [146 146 132]
>   ...
>   [ 90  51  43]
>   [ 90  51  43]
>   [  0   0   0]]
> 
>  [[ 83  73  64]
>   [ 83  73  64]
>   [146 146 132]
>   ...
>   [ 90  51  43]
>   [ 90  51  43]
>   [  0   0   0]]
> 
>  [[172 151 132]
>   [172 151 132]
>   [255 255 255]
>   ...
>   [185 105  89]
>   [185 105  89]
>   [ 13   9   7]]
> ```
> 
> This is mainly after the game refreshes itself even if there is no problem, and I'm stuck at the login sreen.
> 
> Also when I change the 10 mins send to work time to 40 mins it seems like the script does not care and send the heroes to work on a random time. Is it because the random trigger? Also it often selects all the heroes not just the ones with green stamina bar does not matter if its set to "green".

first of all: I was trying to print the printscreen (matrix), but now I will change it. 
second: I need to improve the function that wait the Right Screen to continue and when the screen is stuck try F5 to restart everything
third: bellow you can see a list of three heroes type: Just full stamina, Any Green and All heroes.. And "choice" you pick a random of anyone. Then send those heroes to game.
select_heroes = ["full","green","all"]
selected = choice(select_heroes)

I'm trying to create the most human bot to play, you know? But I saw I made the game more slow than normal. BUT impossible to get as bot.

**Comment by BBencee** [comment]
I see, thank your for your work, I will just wait for you to update the files.

**Comment by BBencee** [comment]
> > @gabrielwjesus I've tested your script edit, https://github.com/gabrielwjesus/bombcrypto-bot I am writing you here because I could not open an issue at your github. First of all thank you all for your work!
> > For some reason it gets stuck in a loop for some reason:
> > ```
> > => Waiting to show screen [[[ 83  73  64]
> >   [ 83  73  64]
> >   [146 146 132]
> >   ...
> >   [ 90  51  43]
> >   [ 90  51  43]
> >   [  0   0   0]]
> > 
> >  [[ 83  73  64]
> >   [ 83  73  64]
> >   [146 146 132]
> >   ...
> >   [ 90  51  43]
> >   [ 90  51  43]
> >   [  0   0   0]]
> > 
> >  [[172 151 132]
> >   [172 151 132]
> >   [255 255 255]
> >   ...
> >   [185 105  89]
> >   [185 105  89]
> >   [ 13   9   7]]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is mainly after the game refreshes itself even if there is no problem, and I'm stuck at the login sreen.
> > Also when I change the 10 mins send to work time to 40 mins it seems like the script does not care and send the heroes to work on a random time. Is it because the random trigger? Also it often selects all the heroes not just the ones with green stamina bar does not matter if its set to "green".
> 
> first of all: I was trying to print the printscreen (matrix), but now I will change it. second: I need to improve the function that wait the Right Screen to continue and when the screen is stuck try F5 to restart everything third: bellow you can see a list of three heroes type: Just full stamina, Any Green and All heroes.. And "choice" you pick a random of anyone. Then send those heroes to game. select_heroes = ["full","green","all"] selected = choice(select_heroes)
> 
> I'm trying to create the most human bot to play, you know? But I saw I made the game more slow than normal. BUT impossible to get as bot.

`Traceback (most recent call last):
  File "index.py", line 354, in <module>
    main()
  File "index.py", line 334, in main
    refreshHeroes()
  File "index.py", line 265, in refreshHeroes
    waitHeroes()
  File "index.py", line 233, in waitHeroes
    home_pos = positions(home_btn_img, threshold=ct['go_to_work_btn'])
  File "index.py", line 86, in positions
    result = cv2.matchTemplate(img.astype(np.uint8),target,cv2.TM_CCOEFF_NORMED)

cv2.error: OpenCV(4.5.4-dev) D:\a\opencv-python\opencv-python\opencv\modules\img
proc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U ||
depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::m`

This is a new error when it has to click the work button.

**Comment by gabrielwjesus** [comment]
> > > @gabrielwjesus I've tested your script edit, https://github.com/gabrielwjesus/bombcrypto-bot I am writing you here because I could not open an issue at your github. First of all thank you all for your work!
> 
> > > For some reason it gets stuck in a loop for some reason:
> 
> > > ```
> 
> > > => Waiting to show screen [[[ 83  73  64]
> 
> > >   [ 83  73  64]
> 
> > >   [146 146 132]
> 
> > >   ...
> 
> > >   [ 90  51  43]
> 
> > >   [ 90  51  43]
> 
> > >   [  0   0   0]]
> 
> > > 
> 
> > >  [[ 83  73  64]
> 
> > >   [ 83  73  64]
> 
> > >   [146 146 132]
> 
> > >   ...
> 
> > >   [ 90  51  43]
> 
> > >   [ 90  51  43]
> 
> > >   [  0   0   0]]
> 
> > > 
> 
> > >  [[172 151 132]
> 
> > >   [172 151 132]
> 
> > >   [255 255 255]
> 
> > >   ...
> 
> > >   [185 105  89]
> 
> > >   [185 105  89]
> 
> > >   [ 13   9   7]]
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > This is mainly after the game refreshes itself even if there is no problem, and I'm stuck at the login sreen.
> 
> > > Also when I change the 10 mins send to work time to 40 mins it seems like the script does not care and send the heroes to work on a random time. Is it because the random trigger? Also it often selects all the heroes not just the ones with green stamina bar does not matter if its set to "green".
> 
> > 
> 
> > first of all: I was trying to print the printscreen (matrix), but now I will change it. second: I need to improve the function that wait the Right Screen to continue and when the screen is stuck try F5 to restart everything third: bellow you can see a list of three heroes type: Just full stamina, Any Green and All heroes.. And "choice" you pick a random of anyone. Then send those heroes to game. select_heroes = ["full","green","all"] selected = choice(select_heroes)
> 
> > 
> 
> > I'm trying to create the most human bot to play, you know? But I saw I made the game more slow than normal. BUT impossible to get as bot.
> 
> 
> 
> `Traceback (most recent call last):
> 
>   File "index.py", line 354, in <module>
> 
>     main()
> 
>   File "index.py", line 334, in main
> 
>     refreshHeroes()
> 
>   File "index.py", line 265, in refreshHeroes
> 
>     waitHeroes()
> 
>   File "index.py", line 233, in waitHeroes
> 
>     home_pos = positions(home_btn_img, threshold=ct['go_to_work_btn'])
> 
>   File "index.py", line 86, in positions
> 
>     result = cv2.matchTemplate(img.astype(np.uint8),target,cv2.TM_CCOEFF_NORMED)
> 
> 
> 
> cv2.error: OpenCV(4.5.4-dev) D:\a\opencv-python\opencv-python\opencv\modules\img
> 
> proc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U ||
> 
> depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::m`
> 
> 
> 
> This is a new error when it has to click the work button.

Look your targets path if the png are all there 
I had this error when I didn't put the right images inside the target path
