### ISSUE TITLE
Devo me preocupar?

### ISSUE THREAD

**Issue by caiquefarias** [mpcabete/bombcrypto-bot#136]
![Virus](https://user-images.githubusercontent.com/95562708/144738058-dc1568ba-45b8-44d0-ad5f-7f3a8653896c.png)

Fui fazer o download e apareceu isso

**Comment by THEBESTSZ** [comment]
O programa é código aberto amigo, não sei de onde vc baixou esse bot, mas impossível ter vírus, vc mesmo pode ver o código

**Comment by caiquefarias** [comment]
Se eu tivesse baixado de outro lugar não teria postado aqui, né?

**Comment by Nucito** [comment]
> Se eu tivesse baixado de outro lugar não teria postado aqui, né?

O codigo é de codigo aberto, você pode analisar ele completamente e ver se existe algum tipo de virus '-'

**Comment by ricardofernandess** [comment]
O repo tem 265 estrelas e é código aberto, "basta ler" (o código rsrs...)

**Comment by caiquefarias** [comment]
"basta ler" kk emocionados, eu sei ler os códigos, baixei a primeira vez e não deu nada de vírus, agora fui baixar de novo e o antivírus apitou, se vocês não querem ajudar, não venham digitar coisas obvias. Pro antivírus ter detectado alguma coisa é por que tem alguma coisa no arquivo que baixei, só perguntei se devo me preocupar pois pode ser um falso positivo 👍

**Comment by ricardofernandess** [comment]
Sim, delete imediatamente

**Comment by llFerreira** [comment]
Ele não detectou vírus e sim está informando que o aplicativo/pasta é um Trojan.Script e que faz os comandos de um invasor. Sim e faz, pois ele tira print e mexe o mouse para funcionar o bot. Você pode tanto baixar como copiar os códigos/arquivos manualmente e ir salvando pelo bloco de notas, caso tenha dúvidas e botar pra fazer uma checagem que ele acusará normalmente. Eu tenho um dos melhores anti vírus que é o Malwarebytes e ele não acusa, e recomendo ter ele pra quem mexe com jogos da metamask
