### ISSUE TITLE
Alguns erros/bugs

### ISSUE THREAD

**Issue by llFerreira** [mpcabete/bombcrypto-bot#138]
Bom dia, brow. Achei mais alguns erros e por ruim nao consegui resolver.
1- Essa nova checagem de capcha está dando bug nas demais funçoes se ele vier ao mesmo tempo, tipo, depois de um tempo se o tempo da checagem bater ao mesmo tempo que o de apertar no botao WORK, ele checa e da NOT FOUND CAPCHA (isso está certo), porém o bot cancela a funçao de colocar os bonecos para trabalhar. Ele meio que cancela qualquer funçao que vier junto com a checagem.
2- Ele nao ta identificando o botao OK, quando da error apos fazer login ou quando da error de servidor off dentro do jogo.
3- Ele ta identificando rapidamente o "login attempts many" e fazendo atualizaçao da pagina. Pra ter uma noçao de tempo, ele ta fazendo atualizaçao de pagina a cada 1x que poem os bonecos para trabalhar. Eles trabalham um pouco e logo recarrega a pagina.

Por enquanto esses foram os 3 bugs/erros que identifiquei, e esqueci de tirar os prints.

**Comment by LRBarbieri** [comment]
> Bom dia, brow. Achei mais alguns erros e por ruim nao consegui resolver. 1- Essa nova checagem de capcha está dando bug nas demais funçoes se ele vier ao mesmo tempo, tipo, depois de um tempo se o tempo da checagem bater ao mesmo tempo que o de apertar no botao WORK, ele checa e da NOT FOUND CAPCHA (isso está certo), porém o bot cancela a funçao de colocar os bonecos para trabalhar. Ele meio que cancela qualquer funçao que vier junto com a checagem. 2- Ele nao ta identificando o botao OK, quando da error apos fazer login ou quando da error de servidor off dentro do jogo. 3- Ele ta identificando rapidamente o "login attempts many" e fazendo atualizaçao da pagina. Pra ter uma noçao de tempo, ele ta fazendo atualizaçao de pagina a cada 1x que poem os bonecos para trabalhar. Eles trabalham um pouco e logo recarrega a pagina.
> 
> Por enquanto esses foram os 3 bugs/erros que identifiquei, e esqueci de tirar os prints.

Ué, que estranho. Até agora não deu nenhum desses erros para mim.
