### ISSUE TITLE
Não Consigo Instalar os Requirements

### ISSUE THREAD

**Issue by martineix** [mpcabete/bombcrypto-bot#14]
Boa tarde, brother! Tudo bem?
Estou tentando instalar para poder jogar e doar. Mas dá esses erros. Como consigo resolver?

![Erro](https://user-images.githubusercontent.com/67521151/141514493-0141fd47-ef0d-433b-8d84-045a63112bbd.png)

**Comment by martineix** [comment]
Encontrei meu erro. Obrigado!

**Comment by Marques1233** [comment]
fala mano, blza. O meu da o mesmo erro o que fez pra corrigir?
