### ISSUE TITLE
[HELP MAC USERS] [MAC OS AJUDA]

### ISSUE THREAD

**Issue by LoboNFT** [mpcabete/bombcrypto-bot#140]
HELLO GUYS
How i can install python script at macbook m1 pro?

Boa tarde,
como eu faço para instalar o script no macbook?

**Comment by rnesheiksilvestre** [comment]
somente com uma vm tentei botar aqui no meu hackintosh não fazia as execuções 100%

**Comment by Yanrs** [comment]
Você vai precisar instalar o [brew](https://brew.sh/index_pt-br).
depois só rodar:
`brew install python3`
vá ate a pasta usando `cd`
`pip3 install -r requirements.txt`
após isso vai poder executar usando:
`python3 index.py`

**Comment by LoboNFT** [comment]
@Yanrs vou testar, qualquer coisa te aciono aqui!

**Comment by LoboNFT** [comment]
> Você vai precisar instalar o [brew](https://brew.sh/index_pt-br). depois só rodar: `brew install python3` vá ate a pasta usando `cd` instale as bibliotecas necessárias `pip3 install -r requirements.txt` após isso vai poder executar usando: `python3 index.py`
> 
> Assegure de colocar a resolução em 1920x1080p

nao consegui chegar na parte do CD, isso seria no proprio mac?

**Comment by Yanrs** [comment]
Tudo que escrevi se passa dentro do terminal, tudo no mac OSX.
Se não esta familiarizado com o comando `cd` recomendo ver um vídeo sobre conhecimento básico de utilização do terminal.

**Comment by LoboNFT** [comment]
consegui executar o script via terminal, porem nao consigo mudar a resoluçao, so conectando monitor externo... porém o bot nao aceita mais de 1 monitor ligado.. o que eu faço? @Yanrs

**Comment by lucasayres** [comment]
Aqui também não funciona no meu mac

**Comment by mdavinicius** [comment]
Ninguém pessoal? :(

**Comment by wesleyalberini** [comment]
Dependendo da versao do SO precisa ir na regra de acessibilidade e liberar o terminal.
Security Preferences > Security & Privacy > Privacy > Accessibility
Aqui esta acontecendo outra situacao, ele so move o mouse para o canto inferior direito e nao faz mais nada

**Comment by joaopedrorc** [comment]
@wesleyalberini  aqui está acontecendo a mesma coisa. Você conseguiu resolver?

**Comment by joaopedrorc** [comment]
> Dependendo da versao do SO precisa ir na regra de acessibilidade e liberar o terminal. Security Preferences > Security & Privacy > Privacy > Accessibility Aqui esta acontecendo outra situacao, ele so move o mouse para o canto inferior direito e nao faz mais nada


@wesleyalberini aqui está acontecendo a mesma coisa. Você conseguiu resolver?
