### ISSUE TITLE
Tá dando ban usar o bot?

### ISSUE THREAD

**Issue by BenitoMarculanoRibeiro** [mpcabete/bombcrypto-bot#141]
O "anti-bot" deles é apenas o captcha para tentar impedir, ou realmente estão banindo que usa bot?

**Comment by Nucito** [comment]
> O "anti-bot" deles é apenas o captcha para tentar impedir, ou realmente estão banindo que usa bot?

Todo dia apos as manutenções eu verifico se algo mudou no codigo fonte do jogo mas ate o momento a unica coisa que existe é o captcha 👍 Mas a questão desse tempo fixo é possivel banir por conta disso...

**Comment by Nicolas-Freitas** [comment]
@Nucito como faz para verificar o codigo fonte?

**Comment by LRBarbieri** [comment]
Sim, agora se detectarem bot pode dar ban, antes do captcha era liberado. Agora é usar e torcer para não tomar kkkk. Eu uso só para dormir, de dia eu mesmo coloco manualmente.

**Comment by Wanderlei7** [comment]
Também tô usando pra dormir, durante o dia deixo vários despertadores de 1 em 1 hora, assim não perco nem 1 minuto de Farm

**Comment by LRBarbieri** [comment]
> Também tô usando pra dormir, durante o dia deixo vários despertadores de 1 em 1 hora, assim não perco nem 1 minuto de Farm

Eu coloco para trabalhar a cada 1h47 minutos, que é o tempo de um herói com 50 de estamina trabalhar e recuperar totalmente a estamina.

**Comment by Wanderlei7** [comment]
> > Também tô usando pra dormir, durante o dia deixo vários despertadores de 1 em 1 hora, assim não perco nem 1 minuto de Farm
> 
> Eu coloco para trabalhar a cada 1h47 minutos, que é o tempo de um herói com 50 de estamina trabalhar e recuperar totalmente a estamina.

Os meus tem 2 com bateria e 50 stamina, então da uns 50 minutos de espera, aí boto 1 hora que tem o tempo deles quebrar as caixas.

**Comment by pedrokeplerpkpv** [comment]
> Sim, agora se detectarem bot pode dar ban, antes do captcha era liberado. Agora é usar e torcer para não tomar kkkk. Eu uso só para dormir, de dia eu mesmo coloco manualmente.

é possivel identificar? eles não estçao conseguindo nem deixar  o servidor no ar.

**Comment by LRBarbieri** [comment]
> > Sim, agora se detectarem bot pode dar ban, antes do captcha era liberado. Agora é usar e torcer para não tomar kkkk. Eu uso só para dormir, de dia eu mesmo coloco manualmente.
> 
> é possivel identificar? eles não estçao conseguindo nem deixar o servidor no ar.

Então, entendo o básico do básico de programação, mas creio que ser possível sim. O bot sempre clica nos mesmos lugares e com um tempo igual também, coisa que é praticamente impossível para um humano fazer igual.
