### ISSUE TITLE
Economizar energia e vida útil. Ligar e desligar o Pc remotamente 

### ISSUE THREAD

**Issue by kerferber** [mpcabete/bombcrypto-bot#142]
Pessoal. Eu estava pensando em uma forma de economizar energia sem precisar deixar o computador ligado 24hrs,  e com isso prolongar a vida útildo computador.

Com um interruptor SonOff daria pra ligar e desligar o computador à distância através do celular.

Será que é viável automatizar isto e, por exemplo, quando acabar a stamina de todos os heróis, programar o computador pra desligar por "X" minutos, e após ligar novamente e conectar no jogo?

Ou será que não vale o esforço? Kkk Valeu

**Comment by LRBarbieri** [comment]
> Pessoal. Eu estava pensando em uma forma de economizar energia sem precisar deixar o computador ligado 24hrs, e com isso prolongar a vida útildo computador.
> 
> Com um interruptor SonOff daria pra ligar e desligar o computador à distância através do celular.
> 
> Será que é viável automatizar isto e, por exemplo, quando acabar a stamina de todos os heróis, programar o computador pra desligar por "X" minutos, e após ligar novamente e conectar no jogo?
> 
> Ou será que não vale o esforço? Kkk Valeu

Não acho que valha o esforço, além de que com um interruptor você só vai ligar/desligar a energia do computador, ele em si não vai iniciar. Comprei um robôzinho que consegue apertar o botão de ligar o pc, e vou usar para conseguir ligar/desligar remotamente. Além de que com 30/40 reais por mês você aluga uma vps.

**Comment by fguide** [comment]
Não vejo praticidade, é simples fazer isso com vários recursos, WakeOn Lan, timer digital de tomada, etc, porém vai depender de tempo para ajustar o script e ter muitos pontos de falha, como sugerido alugar uma VPS, ou fazer uma conta trial no google cloud resolveria seu problema.

Em VPS precisa apenas estar atento em como vai fazer a conexão, se fizer por RDP a tela fica travada ao desconectar, porém tem alternativas para isso em: #76

**Comment by kerferber** [comment]
> > Pessoal. Eu estava pensando em uma forma de economizar energia sem precisar deixar o computador ligado 24hrs, e com isso prolongar a vida útildo computador.
> > Com um interruptor SonOff daria pra ligar e desligar o computador à distância através do celular.
> > Será que é viável automatizar isto e, por exemplo, quando acabar a stamina de todos os heróis, programar o computador pra desligar por "X" minutos, e após ligar novamente e conectar no jogo?
> > Ou será que não vale o esforço? Kkk Valeu
> 
> Não acho que valha o esforço, além de que com um interruptor você só vai ligar/desligar a energia do computador, ele em si não vai iniciar. Comprei um robôzinho que consegue apertar o botão de ligar o pc, e vou usar para conseguir ligar/desligar remotamente. Além de que com 30/40 reais por mês você aluga uma vps.

Tem como configurar na BIOS para assim que energizar, ligar o notebook.

Mas gostei da ideia do robôzinho, pode dar mais detalhes? Valor e link para eu olhar? Obrigado

**Comment by kerferber** [comment]
> Não vejo praticidade, é simples fazer isso com vários recursos, WakeOn Lan, timer digital de tomada, etc, porém vai depender de tempo para ajustar o script e ter muitos pontos de falha, como sugerido alugar uma VPS, ou fazer uma conta trial no google cloud resolveria seu problema.
> 
> Em VPS precisa apenas estar atento em como vai fazer a conexão, se fizer por RDP a tela fica travada ao desconectar, porém tem alternativas para isso em: #76

Pois é... não tenho nenhum conhecimento de Vps, vou dar uma pesquisada, valeu pela dica.

**Comment by LRBarbieri** [comment]
> > > Pessoal. Eu estava pensando em uma forma de economizar energia sem precisar deixar o computador ligado 24hrs, e com isso prolongar a vida útildo computador.
> > > Com um interruptor SonOff daria pra ligar e desligar o computador à distância através do celular.
> > > Será que é viável automatizar isto e, por exemplo, quando acabar a stamina de todos os heróis, programar o computador pra desligar por "X" minutos, e após ligar novamente e conectar no jogo?
> > > Ou será que não vale o esforço? Kkk Valeu
> > 
> > 
> > Não acho que valha o esforço, além de que com um interruptor você só vai ligar/desligar a energia do computador, ele em si não vai iniciar. Comprei um robôzinho que consegue apertar o botão de ligar o pc, e vou usar para conseguir ligar/desligar remotamente. Além de que com 30/40 reais por mês você aluga uma vps.
> 
> Tem como configurar na BIOS para assim que energizar, ligar o notebook.
> 
> Mas gostei da ideia do robôzinho, pode dar mais detalhes? Valor e link para eu olhar? Obrigado

Não sabia dessa opção da BIOS, interessante. O robô comprei por esse link, mas acho que acha mais barato direto da China. https://needthis.shop/products/robo-inteligente-automatico-adaptativo

**Comment by kerferber** [comment]
> > > > Pessoal. Eu estava pensando em uma forma de economizar energia sem precisar deixar o computador ligado 24hrs, e com isso prolongar a vida útildo computador.
> > > > Com um interruptor SonOff daria pra ligar e desligar o computador à distância através do celular.
> > > > Será que é viável automatizar isto e, por exemplo, quando acabar a stamina de todos os heróis, programar o computador pra desligar por "X" minutos, e após ligar novamente e conectar no jogo?
> > > > Ou será que não vale o esforço? Kkk Valeu
> > > 
> > > 
> > > Não acho que valha o esforço, além de que com um interruptor você só vai ligar/desligar a energia do computador, ele em si não vai iniciar. Comprei um robôzinho que consegue apertar o botão de ligar o pc, e vou usar para conseguir ligar/desligar remotamente. Além de que com 30/40 reais por mês você aluga uma vps.
> > 
> > 
> > Tem como configurar na BIOS para assim que energizar, ligar o notebook.
> > Mas gostei da ideia do robôzinho, pode dar mais detalhes? Valor e link para eu olhar? Obrigado
> 
> Não sabia dessa opção da BIOS, interessante. O robô comprei por esse link, mas acho que acha mais barato direto da China. https://needthis.shop/products/robo-inteligente-automatico-adaptativo

Dá um Google, é uma função utilizada pra o pc ligar após uma queda de energia por exemplo. Ela muda de placa mãe para placa mãe e talvez nem todas tenham essa função. Confesso que ainda não testei no meu note.

E sobre o robô, gostei da ideia, não conhecia. Vou dar uma pesquisada. Obrigado novamente

**Comment by gabrielwjesus** [comment]
da pra implementar em python uma função para dar reboot no computador e ligar após X minutos
mas ai teria que colocar o script pra rodar na inicialização 
o problema é que toda vez que voce for ligar o computador , o script vai ligar tbem.. e ai tem que lembrar de desligar

um dos desafios é que esse tipo de script vai exigir privilégios de Adm na máquina
