### ISSUE TITLE
Duas janelas do navegador

### ISSUE THREAD

**Issue by Lordblackhat** [mpcabete/bombcrypto-bot#144]
Será que é possível otimizar o código para que ele reconheça pelo menos duas janelas do navegador?
![image](https://user-images.githubusercontent.com/95567948/144827290-942b797f-5916-4678-82a5-9c10d114ce79.jpeg)

**Comment by sistemdestroyer** [comment]
Eu gostaria muito tambem, Se caso voce conseguir fazer algo. Avisa por favor. Ja tentei bastante coisa. Mais nada com sucesso

**Comment by JoelFreitas** [comment]
Boa @Wanderlei7 , parece uma solução temporária perfeita!

**Comment by fabiodesouzafernandes** [comment]
Bom dia, será que existe a possibilidade do Bot trabalhar com as duas telas abertas como está na imagem, mas em determinado momento só clicar apenas do lado direito e na sequencia apenas do lado esquerdo.
