### ISSUE TITLE
Tempo de execução aleatório

### ISSUE THREAD

**Issue by cardic1** [mpcabete/bombcrypto-bot#145]
Amigo, pensa em implementar no código algum esquema para randomizar o tempo de execução entre as ações?
Dessa forma a detectação seria mais difícil não acha?

**Comment by fabriciodelima06** [comment]
usei a função 'gauss' para gerar um tempo aleatório entre as funções.

**Comment by raphaeldan** [comment]
> usei a função 'gauss' para gerar um tempo aleatório entre as funções.

onde vc usou e como? Poderia colocar aqui o seu index?

**Comment by lifarrx** [comment]
Passa o index aí heheh
Ou ensina a fazer

**Comment by andrepecosta** [comment]
Além dessa parte de tempo aleatória, estou tentando colocar o local que ele clica como aleatório, tem alguma ideia?

**Comment by fabriciodelima06** [comment]
ainda estou testando, estou sem tempo, fiz poucas alterações.

importei no inicio -> from random import gauss

e em cada if coloque para gerar um numero aleatório. coloque a variação em 1, mas pode ser customizada.

if now - last["check_for_capcha"] > t['check_for_capcha'] * 60:
        
            #Gerar time aleatório
            t['check_for_capcha'] = gauss(t['check_for_capcha'], 1)
            
            last["check_for_capcha"] = now
            logger('Checking for capcha.')
            solveCapcha()

        if now - last["heroes"] > t['send_heroes_for_work'] * 60:
        
            #Gerar time aleatório
            t['send_heroes_for_work'] = gauss(t['send_heroes_for_work'], 1)
            
            last["heroes"] = now
            logger('Sending heroes to work.')
            refreshHeroes()

        if now - last["login"] > t['check_for_login'] * 60:
        
            #Gerar time aleatório
            t['check_for_login'] = gauss(t['check_for_login'], 1)
            
            logger("Checking if game has disconnected.")
            sys.stdout.flush()
            last["login"] = now
            login()

        if now - last["new_map"] > t['check_for_new_map_button']:
        
            #Gerar time aleatório
            t['check_for_new_map_button'] = gauss(t['check_for_new_map_button'], 1)
            
            last["new_map"] = now
            if clickBtn(new_map_btn_img):
                with open('new-map.log','a') as new_map_log:
                    new_map_log.write(str(time.time())+'\n')
                logger('New Map button clicked!')
        
        if now - last["refresh_heroes"] > t['refresh_heroes_positions'] * 60 :
        
            #Gerar time aleatório
            t['refresh_heroes_positions'] = gauss(t['refresh_heroes_positions'], 1)
            
            solveCapcha()
            last["refresh_heroes"] = now
            logger('Refreshing Heroes Positions.')
            refreshHeroesPositions()

obs: não sou experiente em python, eu programo em java.
