### ISSUE TITLE
Anticaptcha

### ISSUE THREAD

**Issue by doranelle** [mpcabete/bombcrypto-bot#146]
Após mudança das targets, utilização do print da linha 183 e limpeza no photoshop, o bot funciona perfeitamente até o aparecimento de algum captcha, quando arrasta o cursor rapidamente até a extremidade e solta, gerando outro captcha em loop. Uso a versão correta, com brave browser, windows 11, 100% de resolução. Alguém teria alguma sugestão do que poderia estar travando o bot?

**Comment by thecashi** [comment]
Executa o bot na tela de seleção dos modos, que ñ tem erro.

**Comment by doranelle** [comment]
Desculpa, qual seria essa tela?

**Comment by doranelle** [comment]
Com o pribt da linha 192 ele mostra exatamente onde as peças estão também, só não executa o puzzle.

**Comment by ppchlrie97** [comment]
> Executa o bot na tela de seleção dos modos, que ñ tem erro.

Se puder explicar como podemos executar o comando nessa tela amigo, seremos gratos, estamos a 3 dias tentando rsrs

**Comment by rickboi9z** [comment]
can you tell me how to handle anti captcha?
I can't do it

**Comment by doranelle** [comment]
Pessoal, descobri e é a coisa mais tosca do mundo no meu caso. A resolução do browser tem que ficar 100% e a da tela tbm, minha tela tava 125%.

**Comment by ppchlrie97** [comment]
@doranelle  fico feliz por voce!! Cara aqui ainda nada, infelizmente to mt chateado de não ir e acho que perguntar as coisas aqui é meio inconveniente né rsrs, se puder me dar uma ajuda isaacreisdeassiscosta@gmail.com
