### ISSUE TITLE
Uma feature interessante que poderia ser adicionada.

### ISSUE THREAD

**Issue by thecashi** [mpcabete/bombcrypto-bot#147]
Olá, acredito que uma feature interessante seria de fazer com que o captcha não acertasse 100% das vezes, ou que acertasse, mas não tão centralizado, visto que o jogo aceita até mesmo se faltar uma pontinha pra completar.

**Comment by kerferber** [comment]
Esta idéia é interessante. Merece prosperar!

**Comment by Nucito** [comment]
> Olá, acredito que uma feature interessante seria de fazer com que o captcha não acertasse 100% das vezes, ou que acertasse, mas não tão centralizado, visto que o jogo aceita até mesmo se faltar uma pontinha pra completar.

Atualmente o jogo não envia a resposta para o servidor... então atualmente essa feature não teria absolutamente nenhuma utilidade 😁
Para ser sincero o jogo nem envia onde vc clica ele apenas envia o horário que vc clicou ksksksks

**Comment by jhonsstn** [comment]
> > Olá, acredito que uma feature interessante seria de fazer com que o captcha não acertasse 100% das vezes, ou que acertasse, mas não tão centralizado, visto que o jogo aceita até mesmo se faltar uma pontinha pra completar.
> 
> Atualmente o jogo não envia a resposta para o servidor... então atualmente essa feature não teria absolutamente nenhuma utilidade 😁 Para ser sincero o jogo nem envia onde vc clica ele apenas envia o horário que vc clicou ksksksks

Tenho uma duvida com respeito a isso. O javascript do navegador não envia nada, mas e a propria engine do jogo, a Unity? Porque pelo que vi aqui não é possível nem inspecionar o jogo em si.

Desculpem se eu estiver falando alguma besteira por falta de conhecimento.

**Comment by mpcabete** [comment]
@Nucito interessante, eu dei uma olhada ja nos requests do jogo, e percebi q a comunicação eh feita por websockets, como vc fez pra analisar isso?

**Comment by Nucito** [comment]
> @Nucito interessante, eu dei uma olhada ja nos requests do jogo, e percebi q a comunicação eh feita por websockets, como vc fez pra analisar isso?

Tenho um certo conhecimento sobre analise de pacotes, tinha um projeto para criar um custom server de um jogo chamado Mirage Realms mas no final eu abandonei o jogo pois enjoei kkkkkk mas eu tinha um cliente modificado que eu conseguia controlar varias coisas modificando os pacotes que o jogo enviava... no caso do bomb a unica coisa que salvou ele foi o md5 que ele envia junto com o pacote... daria mt trabalho pra achar onde estaria essa função por isso não fiz algumas modificações nele :D
Uma falha que poderia ser explorada é que mesmo com o personagem sem energia ele consegue explodir os blocos se ele soltar varias bombas antes de morrer kkkkkk se eu tivesse o md5 poderia farmar mesmo com os personagens dormindo😶

**Comment by Yumiizera** [comment]
@Nucito Então é tranquilo eu utilizar o bot por enquanto?

**Comment by MaxPlayBR** [comment]
> @Nucito Então é tranquilo eu utilizar o bot por enquanto? Que eles não irão saber onde clico, as sequencias de cliques, essas coisas

Entenda que o codigo do jogo pode ser alterado a qualquer momento pelos devs, mas ate esse momento o jogo não envia nada alem do tempo em Unix que vc clicou... Oq eu recomendaria era para deixar isso de maneira aleatória :)
Alem do mais eles tem outras coisas mais importantes para se preocupar kkkkkkk o servidor, comunidade, vip, claim etc...

**Comment by Yumiizera** [comment]
@MaxPlayBR Consigo alterar os horarios no config.yaml?

**Comment by MaxPlayBR** [comment]
> @MaxPlayBR Consigo alterar os horarios no config.yaml?

Atualmente o BOT tem essa configuração implementada, mas se você souber um pouco de programação vai achar a parte para modificar :D

**Comment by Yumiizera** [comment]
@MaxPlayBR Eu não entendo de programação

**Comment by Yumiizera** [comment]
@mpcabete Como faço pra deixar aleatório nas configs? Pode explicar

**Comment by mpcabete** [comment]
oi @Yumiizera eu ja adicionei 10% de aleatoriedade nos intervalos, e 10 pixels de aleatoriedade nos movimentos do mouse, so precisa baixar a ultima versao do bot q ja ta implementado.

**Comment by mpcabete** [comment]
@Nucito nem conhecia o q era o md5, tive q jogar na wikipedia aqui heeuheuhe.
Q ferramentas vc usa pra analisar os pacotes? 
Quando eu tava começando a fazer o bot dei uma fuçada pra ver se encontrava alguma coisa, eu cheguei a ver os pacotes pela ferramentas do desenvolvedor mesmo:
![image](https://user-images.githubusercontent.com/69962256/144957761-aa960323-ca24-4761-9c4f-43d699e924b9.png)
Mas acabei nao me aprofundando mais.
tenho bastante curiosidade de dar uma fuçada nos pacotes pra aprender mesmo.

**Comment by Nucito** [comment]
> @Nucito nem conhecia o q era o md5, tive q jogar na wikipedia aqui heeuheuhe. Q ferramentas vc usa pra analisar os pacotes? Quando eu tava começando a fazer o bot dei uma fuçada pra ver se encontrava alguma coisa, eu cheguei a ver os pacotes pela ferramentas do desenvolvedor mesmo: ![image](https://user-images.githubusercontent.com/69962256/144957761-aa960323-ca24-4761-9c4f-43d699e924b9.png) Mas acabei nao me aprofundando mais. tenho bastante curiosidade de dar uma fuçada nos pacotes pra aprender mesmo.

kkkkkk é bem chatinho de aprender no começo, a principal coisa que você precisa é de muitooo tempo disponivel :D demorei cerca de 1 mês para mapear todos os esquemas de envio do Mirage Realms.
Do bombcrypto daria para fazer isso se fosse possivel saber oq ele faz o hash kkkkk Se precisar de ajuda tem um otimo tutorial para iniciar nessa area:
https://www.youtube.com/watch?v=TG_FVzBijrk&t=394s
https://www.youtube.com/watch?v=irhcfHBkfe0
https://www.youtube.com/watch?v=hABj_mrP-no&t=1454s
Tem um outro gringo que fez um mod server em C++ mas perdi o link dele ksksks se eu achar em algum outro lugar eu edito minha postagem aqui.
 Em resumo vc precisa estudar sobre:
 - Socket
 - Hexadecimal
 - XOR
 - Hash
 Se precisar de ajuda so me adicionar no discord: Cartman#6666
 Não estou usando mais o bots no bombcrypto mas gostei do seu projeto 👍

**Comment by THEBESTSZ** [comment]
> @Nucito nem conhecia o q era o md5, tive q jogar na wikipedia aqui heeuheuhe. Q ferramentas vc usa pra analisar os pacotes? Quando eu tava começando a fazer o bot dei uma fuçada pra ver se encontrava alguma coisa, eu cheguei a ver os pacotes pela ferramentas do desenvolvedor mesmo: ![image](https://user-images.githubusercontent.com/69962256/144957761-aa960323-ca24-4761-9c4f-43d699e924b9.png) Mas acabei nao me aprofundando mais. tenho bastante curiosidade de dar uma fuçada nos pacotes pra aprender mesmo.

Como vc fez pra ver essa tela no google chrome?

**Comment by Nucito** [comment]
> > @Nucito nem conhecia o q era o md5, tive q jogar na wikipedia aqui heeuheuhe. Q ferramentas vc usa pra analisar os pacotes? Quando eu tava começando a fazer o bot dei uma fuçada pra ver se encontrava alguma coisa, eu cheguei a ver os pacotes pela ferramentas do desenvolvedor mesmo: ![image](https://user-images.githubusercontent.com/69962256/144957761-aa960323-ca24-4761-9c4f-43d699e924b9.png) Mas acabei nao me aprofundando mais. tenho bastante curiosidade de dar uma fuçada nos pacotes pra aprender mesmo.
> 
> Como vc fez pra ver essa tela no google chrome?

Va no F12 depois clique na aba de Redes
