### ISSUE TITLE
Novo macro do bombcrypto com ant bot e full randomização

### ISSUE THREAD

**Issue by BombFarm** [mpcabete/bombcrypto-bot#148]
pessoal desse disc aqui desenvolveu um bot monstro porem é pago https://discord.gg/Xa8pE6vf

**Comment by fguide** [comment]
Essa não é nossa intenção aqui, estamos buscando soluções e melhorias para esse bot que é open source, não para divulgar vendas de trabalho alheio feito com base nele.

**Comment by BombFarm** [comment]
feito com base nele não amigo, tem bem antes desse código ser lançado só tô passando a boa pra galera c:
afinal se ta ganhando dinheiro gaste dinheiro para ganhar um pouco a mais c:

**Comment by HugoZanco** [comment]
> feito com base nele não amigo, tem bem antes desse código ser lançado só tô passando a boa pra galera c: afinal se ta ganhando dinheiro gaste dinheiro para ganhar um pouco a mais c:

Agora deixa eu adivinhar...

Coincidentemente você é um dos que tira lucro com a venda desse bot que você se empenha tanto em fazer propaganda, né?

Aaaaaah, por favor né! Ta passando vergonha aqui.

**Comment by fguide** [comment]
> feito com base nele não amigo, tem bem antes desse código ser lançado só tô passando a boa pra galera c: afinal se ta ganhando dinheiro gaste dinheiro para ganhar um pouco a mais c:

De toda forma, está no lugar errado para divulgações, ou assuntos  que não sejam relacionados a esse projeto.

**Comment by dionatharibeiro** [comment]
Nunca usem nada que venha compilado, seja pago ou gratuito, estes programas quase sempre possuem keylogger ou mesmo ações que irão pegar sua key da metamask e você irá perder todo o dinheiro dela, além de nunca mais poder utiliza-la, já que eles colocam a conta em um bot que retira qualquer movimentação antes de você. Se forem usar algo, que seja com o código aberto.
