### ISSUE TITLE
problema de auto-login do jogo

### ISSUE THREAD

**Issue by vaskhan** [mpcabete/bombcrypto-bot#150]
amigo, o próprio bot não faz login na carteira e não entra na escolha dos heróis. primeiro você precisa entrar no jogo e entrar no menu de heróis para começar a enviá-los para o trabalho

**Comment by andrepecosta** [comment]
Você está usando o metamask em português ou inglês?

**Comment by lifarrx** [comment]
O meu estava assim, consegui resolver. primeiro o metamask tem que estar em inglês e a imagem que vem no arquivo que ele disponibiliza não está boa para identificar, tem que recortar só a parte que está escrito "SIGN" e deixar bem quadradinho ali, substitui o arquivo dentro da pasta target com o mesmo nome, por essa nova imagem que você fez.
