### ISSUE TITLE
Não consigo fazer a doação pro Mateus

### ISSUE THREAD

**Issue by lifarrx** [mpcabete/bombcrypto-bot#151]
![donate](https://user-images.githubusercontent.com/95596140/144901563-58cbbfca-bb38-4615-91cb-61d36c6ce9e2.png)

alguma outra forma de doar? sem scam pls.

**Comment by jeanvetorello** [comment]
doa enviando para carteira dele está no README , pela metamask mesmo irmão.  fiz minha doaçao pela carteira dele.

**Comment by lifarrx** [comment]
Valeu, não tinha me atentado, realmente tem la, vou ter que colocar um saldo la na metamask pra doar então.
