### ISSUE TITLE
Estou com problemas,o bot simplesmente não faz nada 

### ISSUE THREAD

**Issue by FergusonxD** [mpcabete/bombcrypto-bot#152]
Antes o bot funcionava normalmente
agora não está fazendo mais nada,
Peço ajuda,vlwsão!

**Comment by cabralgt** [comment]
Estou com o mesmo problema aqui. Não gera erro no console nem nada.

**Comment by FergusonxD** [comment]
> Estou com o mesmo problema aqui. Não gera erro no console nem nada.

exatamente

**Comment by JoelFreitas** [comment]
Mesmo erro aqui. O mouse fica tipo "piscando" depois da atualização do captcha. No log do CMD mostra sempre "0 BUTTONS detected" "0 stamina bars detected", etc. Vocês estão usando multitela ou mexeram algo no Python?

**Comment by FergusonxD** [comment]
nada,tudo normal até reinstalei o python pra ver se mudava algo.Mas nada
