### ISSUE TITLE
DOAÇÕES VAMOS AJUDAR GALERA.

### ISSUE THREAD

**Issue by lifarrx** [mpcabete/bombcrypto-bot#155]
Pessoal vamos ajudar com pouco que seja, não da pra ficar só sugando do projeto também sem colocar nada do bolso, vamos ter bom senso e por a mão na consciência, tem uma pessoa trabalhando pra disponibilizar isso aqui pra gente, então vamos colaborar que não fica pesado pra ninguém.
![donatemateus](https://user-images.githubusercontent.com/95596140/144935838-2a08e4e9-d820-482d-9ff9-95751a37a366.png)
 
@mpcabete

**Comment by mpcabete** [comment]
Mto obrigado 💜

**Comment by mpcabete** [comment]
Eu vou fechar o issue, vc pode testar pra mim se consegue abrir de novo?

**Comment by lifarrx** [comment]
Não consigo abrir de novo 👍 kk

**Comment by mpcabete** [comment]
vlww
