### ISSUE TITLE
plausible api adicionada

### ISSUE THREAD

**Issue by filipecavalc** [mpcabete/bombcrypto-bot#156]
por que isso foi adicionado?

headers = {
    'authority': 'plausible.io',
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36',
    'content-type': 'text/plain',
    'accept': '*/*',
    'sec-gpc': '1',
    'origin': 'https://mpcabete.xyz',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://mpcabete.xyz/',
    'accept-language': 'en-US,en;q=0.9',
}

data = '{"n":"pageview","u":"https://mpcabete.xyz/bombcryptodebug/","d":"mpcabete.xyz","r":"https://mpcabete.xyz/","w":1182}'

response = requests.post('https://plausible.io/api/event', headers=headers, data=data)

**Comment by mpcabete** [comment]
Oi amigo, plausible eh um site de analytics open source, era so pra eu ter ideia de quantas pessoas estavam usando.
Minha conta tryal no plausible acabou, vou aproveitar q vc me lembrou e tirar.

**Comment by filipecavalc** [comment]
taca um analytics depois, e seta com uma opção de ambiente pro pessoal deixar ligado se quiser,
