### ISSUE TITLE
DICA DE IMPLEMENTAÇÃO NO BOT

### ISSUE THREAD

**Issue by lifarrx** [mpcabete/bombcrypto-bot#157]
DICA de implementação, as vezes quando clica em connect e aparece a barra de carregamento ela trava em 50% 
85%
 20%
aconteceu aqui agora, o bot não consegue identificar, pois não da erro, simplesmente fica travado, seria legal implementar um F5 caso identificasse esse travamento, pra tentar logar novamente.

**Comment by Nydoehar** [comment]
> DICA de implementação, as vezes quando clica em connect e aparece a barra de carregamento ela trava em 50% 85% 20% aconteceu aqui agora, o bot não consegue identificar, pois não da erro, simplesmente fica travado, seria legal implementar um F5 caso identificasse esse travamento, pra tentar logar novamente.

Seria uma ótima adição ao bot.

**Comment by llFerreira** [comment]
> DICA de implementação, as vezes quando clica em connect e aparece a barra de carregamento ela trava em 50% 85% 20% aconteceu aqui agora, o bot não consegue identificar, pois não da erro, simplesmente fica travado, seria legal implementar um F5 caso identificasse esse travamento, pra tentar logar novamente.

Se nao me engano, tem essa opçao e é o "loggin attempts", que se ele nao identificar o jogo funcionando a cada 3 checagem dele, ele automaticamente atualiza o jogo (CTRL F5). O ruim, que comigo ele ta fazendo isso ate mesmo com os bonecos ativos no mapa e ja fiz de tudo e nao consigo corrigir :/
