### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by neemiasbj** [mpcabete/bombcrypto-bot#158]
Boa noite, já está resolvendo captcha?

**Comment by mpcabete** [comment]
tá sim

**Comment by ppchlrie97** [comment]
@mpcabete Meu nobre o meu e de uma pessoa que falou ali no issues não está indo por que não clica quando resolve o captcha, poderia nos ajudar pfvr? grato por tudo

**Comment by ppchlrie97** [comment]
O bot faz tudo certinho, mas quando chega na imagem ele coloca a peça puzzle mas não clica, sendo assim fica dando um erro pois não entra o game.
