### ISSUE TITLE
Dica para a lista de requerimentos usados no projeto

### ISSUE THREAD

**Issue by BenitoMarculanoRibeiro** [mpcabete/bombcrypto-bot#159]
Usa a função nativa do python para poder saber exatamente qual versão da biblioteca está sendo usado:
pip freeze > requirements.txt

Vai resultar em algo mais ou menos assim:

requirements.txt:

certifi==2021.10.8
charset-normalizer==2.0.9
idna==3.3
MouseInfo==0.1.3
mss==6.1.0
numpy==1.21.4
opencv-python==4.5.4.60
Pillow==8.4.0
PyAutoGUI==0.9.53
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pyperclip==1.8.2
PyRect==0.1.4
PyScreeze==0.1.28
pytweening==1.0.4
PyYAML==6.0
requests==2.26.0
urllib3==1.26.7

**Comment by mpcabete** [comment]
ahh dahora, so meio iniciante em python vlwss

**Comment by mpcabete** [comment]
tem algum jeito de fazer o comando mostrar so as que estao sendo usadas no script, e nao todas instaladas?

**Comment by BenitoMarculanoRibeiro** [comment]
Se você usar um ambiente de desenvolvimento só para o projeto não precisa. O que estiver instalado é nescessário.
Nota: ambiente de desenvolvimento que me refiro é o virtualenv.
Para quem não conhece, com o comando python -m virtualenv env você cria um ambiente python separado para poder mexer. Só tem que selecionar/ativar o ambiente e instalar as dependências que quer usar. Depois de ativado no terminal se usar o freeze no ambiente ele vai anotar apenas as bibliotecas usadas no ambiente

**Comment by mpcabete** [comment]
fiz isso! atualizei o arquivo la, vlw!
Vc acha q faz sentido incluir a pasta do virtualenv no repositório? ficaria mais fácil pro pessoal usar assim ou não faz diferença?

**Comment by BenitoMarculanoRibeiro** [comment]
No geral, essa pasta funciona só para você, se colocá-la simplesmente em outro computador poderia dar bug por incompatibilidade. 
O certo é cada um criar seu ambiente e instalar os requisitos.
O certo mesmo é criar um Docker para ser universal. Mas vai de cada um.
