### ISSUE TITLE
Existe algum changelog?

### ISSUE THREAD

**Issue by kerferber** [mpcabete/bombcrypto-bot#160]
Pessoal, sou bem iniciante aqui no github

Percebi que alguns arquivos do bot foram atualizados a 38 minutos. Existe algum changelog ou algo do tipo onde a gente consiga ver oq foi modificado?

Se sim, onde encontro?
Obrigado e desculpem se for uma pergunta tosca

**Comment by mpcabete** [comment]
Oi amigo, por enquanto nao tenho feito um changelog nao...
Vou ver se consigo colocar um logo menos.
se vc quiser checar os commits e o q foi mudado no codigo vc pode ver o [historico](https://github.com/mpcabete/bombcrypto-bot/commits/main), mas vou admitir q n deixei mto claro nas descrições o que eu fiz em cada commit hehhe
