### ISSUE TITLE
alguem sofreu alguma punição pós implementação do captcha?

### ISSUE THREAD

**Issue by filipecavalc** [mpcabete/bombcrypto-bot#161]

**Comment by CmPedro** [comment]
acredito que não e parece que na ultima mudança agora o bot se movimenta mais randomicamente

**Comment by Redexote** [comment]
> acredito que não e parece que na ultima mudança agora o bot se movimenta mais randomicamente

amigo essa mudanca ja foi feita?, onde baixo ela?

**Comment by CmPedro** [comment]
> > acredito que não e parece que na ultima mudança agora o bot se movimenta mais randomicamente
> 
> amigo essa mudanca ja foi feita?, onde baixo ela?

apaga os arquivos e baixa de novo, foi a ultima modificação
