### ISSUE TITLE
Discussão sobre a randomização de tempo

### ISSUE THREAD

**Issue by THEBESTSZ** [mpcabete/bombcrypto-bot#164]
Sobre essa parte do código que é rodado em um while true:

if now - last["heroes"] > addRandomness(t['send_heroes_for_work'] * 60):

Não seria melhor algo desse tipo:
 if now - last["heroes"] > t['send_heroes_for_work'] * 60:
       t['send_heroes_for_work'] = addRandomness(t['send_heroes_for_work'] * 60) ?

Visto que ao colocar a randomização na condição do if, ao passar pelo laço várias vezes ele vai checando com diferentes valores randomicos em cada laço

Percebi também que em alguns casos ele considera o mesmo valor randomico muitas vezes

**Comment by neurose0** [comment]
mais de algum nao esta conseguindo reconectar mais ?? o meu para na hora que tem que aceitar na metamask

**Comment by Redexote** [comment]
> Sobre essa parte do código que é rodado em um while true:
> 
> if now - last["heroes"] > addRandomness(t['send_heroes_for_work'] * 60):
> 
> Não seria melhor algo desse tipo: if now - last["heroes"] > t['send_heroes_for_work'] * 60: t['send_heroes_for_work'] = addRandomness(t['send_heroes_for_work'] * 60) ?
> 
> Visto que ao colocar a randomização na condição do if, ao passar pelo laço várias vezes ele vai checando com diferentes valores randomicos em cada laço
> 
> Percebi também que em alguns casos ele considera o mesmo valor randomico muitas vezes


Amigo esse código funciona?
