### ISSUE TITLE
Desabilitar os prints no prompt

### ISSUE THREAD

**Issue by kerferber** [mpcabete/bombcrypto-bot#166]
Pessoal,

Alguma dica de como desabilitar os prints no prompt nesta última versão do código?

A meu ver, não é necessário imprimir tanta informação no prompt, apenas executar.

Que linhas eu poderia # comentar pra interromper estas impressões?
Obrigado

**Comment by fguide** [comment]
Não entendi muito bem sua pergunta, mas parece que você não quer imprimi as mensagens no prompt, pra fazer isso você pode emular a função logger vazia, segue exemplo:

comentar a linha 5:
` #from src.logger import logger, loggerMapClicked`

e adicionar no index.py a função vazia:
```
def logger(message, progress_indicator = False, color = 'default'):
    return

def loggerMapClicked():
    return
```
Deve suprimir as mensagens, não consegui testar em completo para erros.

**Comment by kerferber** [comment]
> Não entendi muito bem sua pergunta, mas parece que você não quer imprimir as mensagens no prompt, pra fazer isso você pode emular a função logger vazia, segue exemplo:
> 
> comentar a linha 5: ` #from src.logger import logger, loggerMapClicked`
> 
> e adicionar no index.py a função vazia:
> 
> ```
> def logger(message, progress_indicator = False, color = 'default'):
>     return
> 
> def loggerMapClicked():
>     return
> ```
> 
> Deve suprimir as mensagens, não consegui testar em completo para erros.

Perfeito. Exatamente isso que precisava. O corretor trocou prints por principais kkk.
Obrigado!
