### ISSUE TITLE
ALTERNAR NAVEGADOR

### ISSUE THREAD

**Issue by martineix** [mpcabete/bombcrypto-bot#167]
Grande irmão e colegas!

Existe algum comando que faça com o que o BOT, de tempos em tempos, troque de navegador e execute os comandos em uma segunda conta minha?

Criei a conta Num2 e gostaria que o BOT tb manuseasse ela.

Não é issue, mas é que não tem como falar com vocês de outra forma.

**Comment by fguide** [comment]
Acredito que isso não esteja implementado, de toda forma tem outras alternativas, você pode fazer máquinas virtuais com VMWare, Virtualbox, etc, ou mesmo rodar no Windows SandBox.

Outra alternativa é deixar os dois navegadores logados, e criar uma rotina no seu sistema operacional para alternar a visualização entre eles, com Task Scheduler do windows  ou cron em abientes *nix.
