### ISSUE TITLE
Tempo entre operaçoes aleatorios.

### ISSUE THREAD

**Issue by jeanvetorello** [mpcabete/bombcrypto-bot#168]
send_heroes_for_work:[1,10]
refresh_heroes_positions:[2,5]
interval_between_moviments: [1,2]

mpcabete oque acha de nesses item tem um range de tempo por exemplo send_heroes_for_work: [2,10] tempo iniciial e tempo final,   e lá no main fazer um rand nesse tempo?

vlw mano.

**Comment by nosredna77** [comment]
Iria propor o mesmo acima, colocar tempos e intervalos aleatórios e configuráveis. Vlw
