### ISSUE TITLE
the bot can't  click the sign button?i need help

### ISSUE THREAD

**Issue by panghuahua2017** [mpcabete/bombcrypto-bot#170]
Why the bot can't  click the sign button? I tried to take a screenshot several times, but it couldn't be recognized, and there was no problem with other functions.please help me,thanks!!!

**Comment by antoniocarlosmd** [comment]
> Why the bot can't click the sign button? I tried to take a screenshot several times, but it couldn't be recognized, and there was no problem with other functions.please help me,thanks!!!

Crop the image removing the white part, it worked for me.
