### ISSUE TITLE
Já descobri a causa. obrigado a todos q tentaram ajudar com o problema. Ao resto que só fez retribuir espalhando o ódio. meus sentimento. espero que melhorem 

### ISSUE THREAD

**Issue by xinombr** [mpcabete/bombcrypto-bot#171]

**Comment by Hermanyo** [comment]
O código é aberto, pode olhar o que ele faz. Não escreve besteira.

**Comment by xinombr** [comment]
boa sorte então pra quem quiser... ele faz referencias a outras coisas. pode olhar quem quiser tb.. justo pelo código ser aberto.. vc por acaso fez algum review que alguem comitou ? não escreve besteira

**Comment by xinombr** [comment]
Qndo juntou os 41 .. na noite q junta . coincidente mente o money some.. só o bot aberto no meu pc e o bomb crypto...

**Comment by THEBESTSZ** [comment]
Bixo, não escreve besteira, não tem nada no código que faz desviar o saldo...

**Comment by kimcavalcanti** [comment]
Povo ta fazendo fakenews em código aberto haha a que ponto chegamos

**Comment by mfsousa** [comment]
Melhor vc ver o código de novo... se o seu bcoin foi desviado certamente não foi devido a este bot. Pode ser outro programa aberto em background ou mesmo um outro contrato malicioso que vc tenha aceite anteriormente que esta desviando o bcoin. Ou então é mesmo algum erro no bombcrypto que faz com que o seu bcoin esteja oculto. Já tentou ver se consegue resolver através https://report.bombcrypto.io ?

**Comment by xinombr** [comment]
Já sim, só tem uma transação de saída da minha carteira, nem no log do meu meta mask tem.. essa bosta do metamask deveria ter um 2FA.. mas nem isso aí a carteira fica livre aí pra qualquer um meter a mão sossegado.. tem problema não. é bom q vira xp pra próxima.. boa sorte aí pra quem quiser continuar usando.. segue o meu relato

**Comment by mfsousa** [comment]
Acho q vc esta falando do que não sabe. Basicamente, olhe o código e aponte qual parte faz desviar o saldo? Não tem! Melhor vc ir procurar bem o que esta acontecendo de verdade, se o saldo foi mesmo desviado é provável que lhe aconteça de novo.

**Comment by walterdis** [comment]
Cara, entende uma coisa.
A pessoa tem que ser muito louca de postar um sistema de código aberto com código malicioso nele em um lugar que a maioria é desenvolvedor.

Estuda programação e python por uma semana que vais ver que não tem nada de mais no código do cara (isso partindo do principio que você esta falando sério e não está aqui apenas causando).

**Comment by Nydoehar** [comment]
1 - So sistema é de código aberto, você pode ver tudo o que ele faz.

2 - Se não souber ler código, é só ficar olhando para a tela que você vê exatamente o que o bot está fazendo.

3 - Todo mundo aqui usa o bot a semanas e você é o único com problema... suspeito.

**Comment by Nydoehar** [comment]
1 - O sistema é de código aberto, você pode ver tudo o que ele faz.

2 - Se não souber ler código, é só ficar olhando para a tela que você vê exatamente o que o bot está fazendo.

3 - Todo mundo aqui usa o bot a semanas e você é o único com problema... suspeito.

**Comment by IrohsTeahouse** [comment]
Venho acompanhando varios bots do bomb, e esse sem duvidas por ser código aberto e a comunidade auxliar no seu desenvolvimento de forma GRATUITA é a melhor coisa que tem, logo, se não está contente, vai lá comprar um bot de 500 reais ou mais, antes de vir falar merda dos esforços alheios.

**Comment by llFerreira** [comment]
> Já sim, só tem uma transação de saída da minha carteira, nem no log do meu meta mask tem.. essa bosta do metamask deveria ter um 2FA.. mas nem isso aí a carteira fica livre aí pra qualquer um meter a mão sossegado.. tem problema não. é bom q vira xp pra próxima.. boa sorte aí pra quem quiser continuar usando.. segue o meu relato

Ele tem 2FA sim, porém com a Trezor. Tu acha a mais basica no site original por 800 pila. E tu possivelmente sofreu um contrato falso de algum site ou ate mesmo um virus. Baixe o Malwarebytes e faça uma varredura completa do PC

**Comment by jpedrocguimaraes** [comment]
![image](https://user-images.githubusercontent.com/87657677/145125852-06ebf581-c842-4b4c-84cd-e36ae477ddcd.png)
então tá na hora do dev rever o código, pq aqui não funcionou a "função" de desviar bcoin nn

**Comment by xinombr** [comment]
Espero estar enganado, mas por hora não retiro o que disse. O fato ocorreu, não está claro o que pode ter acontecido, e até o momento este era o único aplicativo rodando no momento do incidente.
O fato de ser código aberto não exclui a possibilidade de existir este tipo de coisa. só a torna mais difícil.

**Comment by jpedrocguimaraes** [comment]
> 

Cara, você pelo menos está pensando na bobagem que está escrevendo? Você pode LITERALMENTE baixar o zip final (vai que você não acredita que o github baixa o ultimo commit disponível) e abrir todos os arquivos e ler as +- 600 linhas que tá ali e procurar algo que faça o processo de desviar bcoin de uma wallet pra outra. NÃO. EXISTE. NENHUM. CÓDIGO. NESTE. PROJETO. QUE. DESVIE. BCOIN. Nenhum, é só ler. Que tonguisse, sloko.

**Comment by mpcabete** [comment]
Olá amigo, sinto mto q isso tenha acontecido com vc...
No protocolo do bep20 (da rede smartchain) existe um mecanismo pra uma conta garantir o direito das transaçoes serem feitas por outra conta. eu acho meio zuado esse mecanismo, em teoria serve pra a interaçao do usuario com o app ficar mais fluida...
Mtos golpes, scams e phishings usam esse mecanismo pra roubar os bcoin dos outros.
Da uma lida nesse artigo q ele pode te dar uma luz:
https://bnbsmartchain.com/binance-smart-chain-token-allowance-checker/
Mas nao me aprofundei mto nele, toma cuidado pq n tenho ctz q q acontece se vc revogar o acesso do bombcrypto aos seus bcoin.
Espero q isso ajude!

**Comment by kouta928** [comment]
Nunca compartilhe sua seed phrase, cheque direito e limpe os contratos que já assinou com a metamask pq proteção 100% só com cold wallet, compra uma trezor que vc dorme tranquilo. Uma pergunta, já tomou a mensagem "kick" no bomb? se sim, sua conta tá comprometida já

**Comment by walterdis** [comment]
> Nunca compartilhe sua seed phrase, cheque direito e limpe os contratos que já assinou com a metamask pq proteção 100% só com cold wallet, compra uma trezor que vc dorme tranquilo. Uma pergunta, já tomou a mensagem "kick" no bomb? se sim, sua conta tá comprometida já

Consegue passar mais informações sobre isso do kick? Eu acho que aconteceu isso comigo 1 ou 2x mas faz bastante tempo já.
Até o momento não reparei em bcoin sumindo nem nada.

**Comment by Nzjj** [comment]
Manda sua carteira, para ver o que exatamente aconteceu, Pois como tudo é feito na BlockChain não tem como seu Tokens simplesmente sumir

**Comment by newerton** [comment]
@xinombr Deve está usando windows pirata com KSMPICO falsificado, com virus que rouba criptomoedas das carteiras, e vem falar de um script de código aberto?

Se está com suspeita, primeiramente analisa o  código e posta aqui qual a linha está roubando seus bcoins.

Como você não tem conhecimento de nada, abre sua metamask e veja para qual conta foi suas bcoins. Deve ter enviado para carteira errada, e vem aqui falar asneira?

Já poderia fechar/deletar essa issue.

**Comment by xinombr** [comment]
@newerton  parabéns por espalhar o ódio. estou fazendo questionamentos, pois o fato ocorreu eu gostaria de saber oq tá acontecendo... Mas eu acredito q já descobri. po

**Comment by xinombr** [comment]
Já descobri o problema. não foi o bot.
Obrigado a todos q tentaram ajudar com o problema. 
Ao resto que só fez retribuir espalhando o ódio, meus sentimentos. espero que melhorem

**Comment by newerton** [comment]
> @newerton parabéns por espalhar o ódio. estou fazendo questionamentos, pois o fato ocorreu eu gostaria de saber oq tá acontecendo... Mas eu acredito q já descobri. po

hahahahahah

Você bate, e depois pergunta? Você que iniciou todo esse flameware aqui. Isso aqui não é sala de bate papo. Github é uma ferramenta de trabalho, e Issues é para declarar seu ódio com o bot, enganando a todos e criando fake news.

**Comment by jpedrocguimaraes** [comment]
> Já descobri o problema. não foi o bot. Obrigado a todos q tentaram ajudar com o problema. Ao resto que só fez retribuir espalhando o ódio, meus sentimentos. espero que melhorem

Você está reclamando de '"ódio" (nada aqui chegou no nível de ódio mesmo) enquanto você acusa um desenvolvedor, com seu programa de código aberto, de estar ROUBANDO dinheiro das pessoas? Sem noção mesmo.
