### ISSUE TITLE
Problema no Linux 

### ISSUE THREAD

**Issue by caiocenlep** [mpcabete/bombcrypto-bot#172]
estou tentando rodar o bot na VPS, mas ao tentar instalar os requerimentos estou tendo alguns erros

Collecting opencv-python
  Using cached https://files.pythonhosted.org/packages/bc/b6/e447d0302bc328f06b56dabd6742648372df63446725db56058a259dbda2/opencv-python-4.5.4.60.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3m1sb8ym/opencv-python/setup.py", line 10, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3m1sb8ym/opencv-python/

e outro

Using cached https://files.pythonhosted.org/packages/d7/5f/77dece686b8d08a17430e169e936722693712b8cf1ee638caa8b1cb6452b/mss-6.1.0-py3-none-any.whl
Collecting numpy==1.21.4 (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement numpy==1.21.4 (from -r requirements.txt (line 6)) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
No matching distribution found for numpy==1.21.4 (from -r requirements.txt (line 6))

alguem saberia como resolver?

**Comment by fguide** [comment]
Qual versão do Python? Pode estar desatualizado, tente:

>pip install --upgrade pip

e tente instalar também com pip3 install -r requirements.txt

**Comment by caiocenlep** [comment]
> Qual versão do Python? Pode estar desatualizado, tente:
> 
> > pip install --upgrade pip
> 
> e tente instalar também com pip3 install -r requirements.txt

3.6.9

tentei e msm assim não foi
continua o problema no numpy

**Comment by Jackcar** [comment]
Ae man, se nao conseguiu ainda, roda os comandos abaixo que vão solucionar seu problema:

**A) System Install**
```
sudo python3 -m pip install -U pip
sudo python3 -m pip install -U setuptools
```

ou 

**B) Virtual Env / Pipenv**
```
pip3 install -U pip
pip3 install -U setuptools

```

**Comment by Mata-L** [comment]
valeu, Jackar!
funcionou pra mim.

**Comment by TheoOliveira** [comment]
Muda a versão pra versão que tu tem instalada seja no python3 ou 2 no arquivo de requirements, as vezes não quebra nada. no meu não quebrou.
