### ISSUE TITLE
[Ajuda] capturar momento em que envia um herói ao trabalho

### ISSUE THREAD

**Issue by kerferber** [mpcabete/bombcrypto-bot#177]
![Screenshot_20211207-235458_Telegram](https://user-images.githubusercontent.com/95573625/145140578-67511bfc-8f62-4878-a3b8-3a1704589caf.jpg)

Pessoal, tô implementando algumas notificações via Telegram, já que passo o dia fora e não consigo acessar no trabalho.

Preciso descobrir o momento em que o Bot consegue enviar algum herói para trabalhar. Já tentei de diversas formas em vários locais mas ainda não consegui.

Preciso executar um print("X" heróis foram enviados ao trabalho) SEMPRE e somente se algum herói for enviado ao trabalho.

Por favor, Alguma dica? Obrigado!

EDIT: Tentei aproveitar a parte que grava no log quando algum herói é enviado ao trabalho mas não deu pois ela grava mesmo se ZERO heróis forem enviados. O que polui demais meu telegram. Quero ser notificado APENAS se o número de heróis enviado for maior que zero.

Quaase consegui com alguns IFs mas só funcionou no primeiro loop. Após enviar algum, no próximo loop acaba não dando certo.

**Comment by Nucito** [comment]
> ![Screenshot_20211207-235458_Telegram](https://user-images.githubusercontent.com/95573625/145140578-67511bfc-8f62-4878-a3b8-3a1704589caf.jpg)
> 
> Pessoal, tô implementando algumas notificações via Telegram, já que passo o dia fora e não consigo acessar no trabalho.
> 
> Preciso descobrir o momento em que o Bot consegue enviar algum herói para trabalhar. Já tentei de diversas formas em vários locais mas ainda não consegui.
> 
> Preciso executar um print("X" heróis foram enviados ao trabalho) SEMPRE e somente se algum herói for enviado ao trabalho.
> 
> Por favor, Alguma dica? Obrigado!
> 
> EDIT: Tentei aproveitar a parte que grava no log quando algum herói é enviado ao trabalho mas não deu pois ela grava mesmo se ZERO heróis forem enviados. O que polui demais meu telegram. Quero ser notificado APENAS se o número de heróis enviado for maior que zero.
> 
> Quaase consegui com alguns IFs mas só funcionou no primeiro loop. Após enviar algum, no próximo loop acaba não dando certo.

Ja pensou em armazenar em uma variavel toda vez que ele clicar em work?
Se o valor for maior que 1 você envia a msg '-'

**Comment by kerferber** [comment]
> > ![Screenshot_20211207-235458_Telegram](https://user-images.githubusercontent.com/95573625/145140578-67511bfc-8f62-4878-a3b8-3a1704589caf.jpg)
> > Pessoal, tô implementando algumas notificações via Telegram, já que passo o dia fora e não consigo acessar no trabalho.
> > Preciso descobrir o momento em que o Bot consegue enviar algum herói para trabalhar. Já tentei de diversas formas em vários locais mas ainda não consegui.
> > Preciso executar um print("X" heróis foram enviados ao trabalho) SEMPRE e somente se algum herói for enviado ao trabalho.
> > Por favor, Alguma dica? Obrigado!
> > EDIT: Tentei aproveitar a parte que grava no log quando algum herói é enviado ao trabalho mas não deu pois ela grava mesmo se ZERO heróis forem enviados. O que polui demais meu telegram. Quero ser notificado APENAS se o número de heróis enviado for maior que zero.
> > Quaase consegui com alguns IFs mas só funcionou no primeiro loop. Após enviar algum, no próximo loop acaba não dando certo.
> 
> Ja pensou em armazenar em uma variavel toda vez que ele clicar em work? Se o valor for maior que 1 você envia a msg '-'

Sim, em tese é isso que estou tentando, porém realmente ainda não consegui implementar.
Eu preciso armazenar este valor, e também zerar ele após notificar no telegram, porém não estou conseguindo...  :(

**Comment by trinitro2** [comment]
> > > ![Screenshot_20211207-235458_Telegram](https://user-images.githubusercontent.com/95573625/145140578-67511bfc-8f62-4878-a3b8-3a1704589caf.jpg)
> > > Pessoal, tô implementando algumas notificações via Telegram, já que passo o dia fora e não consigo acessar no trabalho.
> > > Preciso descobrir o momento em que o Bot consegue enviar algum herói para trabalhar. Já tentei de diversas formas em vários locais mas ainda não consegui.
> > > Preciso executar um print("X" heróis foram enviados ao trabalho) SEMPRE e somente se algum herói for enviado ao trabalho.
> > > Por favor, Alguma dica? Obrigado!
> > > EDIT: Tentei aproveitar a parte que grava no log quando algum herói é enviado ao trabalho mas não deu pois ela grava mesmo se ZERO heróis forem enviados. O que polui demais meu telegram. Quero ser notificado APENAS se o número de heróis enviado for maior que zero.
> > > Quaase consegui com alguns IFs mas só funcionou no primeiro loop. Após enviar algum, no próximo loop acaba não dando certo.
> > 
> > 
> > Ja pensou em armazenar em uma variavel toda vez que ele clicar em work? Se o valor for maior que 1 você envia a msg '-'
> 
> Sim, em tese é isso que estou tentando, porém realmente ainda não consegui implementar. Eu preciso armazenar este valor, e também zerar ele após notificar no telegram, porém não estou conseguindo... :(
> 
> EDIT: Na verdade eu não estou conseguindo localizar a parte do código onde efetivamente devo configurar esta notificação. Se alguém tiver um tempo pra ajudar...?
> 
> Poderia ser na função 'def clickButtons():', também na 'def clickGreenBarButtons():', ou ainda na def 'clickFullBarButtons():', as 3 fazem referência ao botão go-work, porém não consegui encontrar o efetivo clique para armazenar cada clique em uma variável

consegue divulgar o codigo desse bot de telegram?

**Comment by kerferber** [comment]
> > > > ![Screenshot_20211207-235458_Telegram](https://user-images.githubusercontent.com/95573625/145140578-67511bfc-8f62-4878-a3b8-3a1704589caf.jpg)
> > > > Pessoal, tô implementando algumas notificações via Telegram, já que passo o dia fora e não consigo acessar no trabalho.
> > > > Preciso descobrir o momento em que o Bot consegue enviar algum herói para trabalhar. Já tentei de diversas formas em vários locais mas ainda não consegui.
> > > > Preciso executar um print("X" heróis foram enviados ao trabalho) SEMPRE e somente se algum herói for enviado ao trabalho.
> > > > Por favor, Alguma dica? Obrigado!
> > > > EDIT: Tentei aproveitar a parte que grava no log quando algum herói é enviado ao trabalho mas não deu pois ela grava mesmo se ZERO heróis forem enviados. O que polui demais meu telegram. Quero ser notificado APENAS se o número de heróis enviado for maior que zero.
> > > > Quaase consegui com alguns IFs mas só funcionou no primeiro loop. Após enviar algum, no próximo loop acaba não dando certo.
> > > 
> > > 
> > > Ja pensou em armazenar em uma variavel toda vez que ele clicar em work? Se o valor for maior que 1 você envia a msg '-'
> > 
> > 
> > Sim, em tese é isso que estou tentando, porém realmente ainda não consegui implementar. Eu preciso armazenar este valor, e também zerar ele após notificar no telegram, porém não estou conseguindo... :(
> > EDIT: Na verdade eu não estou conseguindo localizar a parte do código onde efetivamente devo configurar esta notificação. Se alguém tiver um tempo pra ajudar...?
> > Poderia ser na função 'def clickButtons():', também na 'def clickGreenBarButtons():', ou ainda na def 'clickFullBarButtons():', as 3 fazem referência ao botão go-work, porém não consegui encontrar o efetivo clique para armazenar cada clique em uma variável
> 
> consegue divulgar o codigo desse bot de telegram?

Claro! 
Vou fazer um issue só pra isso, depois edito o link aqui

**Comment by thiago-molive** [comment]
da uma olhada no pull request #185, la fiz exatamente isso

**Comment by thiago-molive** [comment]
> > > ![Screenshot_20211207-235458_Telegram](https://user-images.githubusercontent.com/95573625/145140578-67511bfc-8f62-4878-a3b8-3a1704589caf.jpg)
> > > Pessoal, tô implementando algumas notificações via Telegram, já que passo o dia fora e não consigo acessar no trabalho.
> > > Preciso descobrir o momento em que o Bot consegue enviar algum herói para trabalhar. Já tentei de diversas formas em vários locais mas ainda não consegui.
> > > Preciso executar um print("X" heróis foram enviados ao trabalho) SEMPRE e somente se algum herói for enviado ao trabalho.
> > > Por favor, Alguma dica? Obrigado!
> > > EDIT: Tentei aproveitar a parte que grava no log quando algum herói é enviado ao trabalho mas não deu pois ela grava mesmo se ZERO heróis forem enviados. O que polui demais meu telegram. Quero ser notificado APENAS se o número de heróis enviado for maior que zero.
> > > Quaase consegui com alguns IFs mas só funcionou no primeiro loop. Após enviar algum, no próximo loop acaba não dando certo.
> > 
> > 
> > Ja pensou em armazenar em uma variavel toda vez que ele clicar em work? Se o valor for maior que 1 você envia a msg '-'
> 
> Sim, em tese é isso que estou tentando, porém realmente ainda não consegui implementar. Eu preciso armazenar este valor, e também zerar ele após notificar no telegram, porém não estou conseguindo... :(
> 
> EDIT: Na verdade eu não estou conseguindo localizar a parte do código onde efetivamente devo configurar esta notificação. Se alguém tiver um tempo pra ajudar...?
> 
> Poderia ser na função 'def clickButtons():', também na 'def clickGreenBarButtons():', ou ainda na def 'clickFullBarButtons():', as 3 fazem referência ao botão go-work, porém não consegui encontrar o efetivo clique para armazenar cada clique em uma variável

as 3 funcoes (clickFullBarButtons, clickGreenBarButtons, clickButtons) nada mais são do que configurações que vc diz ao programa a sua preferencia pra enviar os herois pro trabalho, com vida full ou apenas com barra verde ja serve, a ultima me parece ser contingencia, sugiro fazer na que vc usa e não pensar nas demais
