### ISSUE TITLE
F bot? (Again)

### ISSUE THREAD

**Issue by VitotEPB** [mpcabete/bombcrypto-bot#178]
🚨SERVER MAINTENANCE🚨

Server maintenance from 4:00 to 6:00 AM (UTC):
⭐️Fix bugs.
⭐️Update new Captcha.
⭐️Added new Hero skin: Ninja.
⭐️Change the Christmas UI.
⭐️Updated Claim BCOIN feature, requires 1 BCOIN on Wallet to claim.

❤️ Thank you for your understanding ❤️

**Comment by cesarfran12** [comment]
Também gostava de saber!

**Comment by pwr43nd37** [comment]
o negocio é aguardar as 2 horas e esperar p ver o que vai rolar.

**Comment by cesarfran12** [comment]
> o negocio é aguardar as 2 horas e esperar p ver o que vai rolar.

Deve ser alterado o captcha...

**Comment by kerferber** [comment]
Droga. Tava funcionando tão bem...

**Comment by cesarfran12** [comment]
> Droga. Tava funcionando tão bem...

Pois....

**Comment by jeanvetorello** [comment]
se for nos mesmo moldes blz mas se for outro tipo ai vai demorar um pouco pra quebrar lo

**Comment by Alekseyzhm** [comment]
I really ask the developer to extend the life of the bot) I LOVE YOU Thanks to you I can get some sleep

**Comment by cesarfran12** [comment]
lets hope he says something..

**Comment by cesarfran12** [comment]
Vamos tentar todos ajudar uns aos outro

**Comment by THEBESTSZ** [comment]
Nós sempre iremos nos sobressair se nos unirmos. Uni-lo-emos irmãos!

**Comment by Galinho90** [comment]
Vamos ter que aguardar, mas suspeito que seja de ficar escoolhendo entre, barco, chaminé, aviaõ etc para dificultar ainda mais.

**Comment by THEBESTSZ** [comment]
> Vamos ter que aguardar, mas suspeito que seja de ficar escoolhendo entre, barco, chaminé, aviaõ etc para dificultar ainda mais.

Tudo é resolúvel, neste caso se pode usar um banco de dados com imagens similares, ou até mesmo aplicar um modelo de machine learning pra isso

**Comment by mfsousa** [comment]
humm, este captcha vai ser complicado resolver. Talvez como solução temporaria, tocar um alarme quando detecta a presença de captcha para ser resolvida manualmente.

**Comment by igorsantana76** [comment]
![image](https://user-images.githubusercontent.com/21316534/145149235-6b30ad0c-ae69-4015-8a27-89ea14a2c832.png)
Esse vai ser mais dificil...

**Comment by mpcabete** [comment]
> humm, este captcha vai ser complicado resolver. Talvez como solução temporaria, tocar um alarme quando detecta a presença de captcha para ser resolvida manualmente.

eh mesmo mf, vou ver se consigo fazer isso aqui rapidinho enquanto agnt tenta resolver esse novo

**Comment by kerferber** [comment]
Ocr não resolve? 
Com OCR  extrair de um printscreen o saldo de bcoins em formato texto pra enviar via telegram

**Comment by pwr43nd37** [comment]
Pelo oq vi todos os números atrás de 0 a 9 são padronizados e cada um possuí somente um única imagem, o que varia é o resultado de acordo com o a sequencia dos 3, tanto no background quanto no front é o mesmo tipo de padrão fácil de reconhecer.

**Comment by rodrigobragamg** [comment]
> Pelo oq vi todos os números atrás de 0 a 9 são padronizados e cada um possuí somente um única imagem, o que varia é o resultado de acordo com o a sequencia dos 3, tanto no background quanto no front é o mesmo tipo de padrão fácil de reconhecer.

Tirar um print de cada número então para por na pasta de imagens e fazer um reconhecimento através do print screen, que o script do mc já faz.

**Comment by pwr43nd37** [comment]
acredito que tem q reconhecer cada numero separadamente e para cada numero separado reconhecido no front tem uma imagem correspondente no back. Se desse p isolar cada um....

**Comment by pwr43nd37** [comment]
![0 - front](https://user-images.githubusercontent.com/77351245/145152938-761ee3b1-eaf0-49cb-b66a-481aad03349d.PNG)
![0 - back](https://user-images.githubusercontent.com/77351245/145152948-a2f53303-32ac-4964-ae79-50948caea939.PNG)

**Comment by Hermanyo** [comment]
OCR, pytesseract, etc
A minha primeira ideia seria, salvar a estrutura dos números do front e aí ir arrastando o slide e usando OCR para reconhecer a estrutura o que tiver mais similaridade com os números do front tem grandes chances de ser a respostas (devem está na sequência correta)

**Comment by rodrigobragamg** [comment]
> OCR, pytesseract, etc A minha primeira ideia seria, salvar a estrutura dos números do front e aí ir arrastando o slide e usando OCR para reconhecer a estrutura o que tiver mais similaridade com os números do front tem grandes chances de ser a respostas (devem está na sequência correta)

É. De qualquer forma são 20% de chance de acerto mesmo que fosse no escuro, e três tentativas. E se falhar, só reconectar automaticamente e o bot tenta novamente.
Se o script já acertar pelo menos 70% das vezes de inicio já é mais do que o suficiente.

**Comment by pwr43nd37** [comment]
por exemplo:

le wild CAPTCHA appears:

Tira o print, e faz o OCR do front, 
resultado: 854 (exemplo)
são 4 saltos para a esquerda a cada salto ele muda o fundo, ai da p tentar reconhecer por similaridade, se no ultimo não encontrou volta para a posição inicial pois é o 5 salto que contem uma imagem no back no qual também tentaria identificar através de similaridade.

**Comment by pwr43nd37** [comment]
extraindo os números do back com menor interferência do front, por exemplo os que aparecem sempre atrás do =, da p tentar com 60% de similaridade.

**Comment by Hermanyo** [comment]
Usando pytesseract:
https://stackoverflow.com/questions/24385714/detect-text-region-in-image-using-opencv

**Comment by Hermanyo** [comment]
> extraindo os números do back com menor interferência do front, por exemplo os que aparecem sempre atrás do =, da p tentar com 60% de similaridade.

Dá pra "ignorar" o front, usando um thresholding binári (acho)

**Comment by HugoZanco** [comment]
> > OCR, pytesseract, etc A minha primeira ideia seria, salvar a estrutura dos números do front e aí ir arrastando o slide e usando OCR para reconhecer a estrutura o que tiver mais similaridade com os números do front tem grandes chances de ser a respostas (devem está na sequência correta)
> 
> É. De qualquer forma são 20% de chance de acerto mesmo que fosse no escuro, e três tentativas. E se falhar, só reconectar automaticamente e o bot tenta novamente. Se o script já acertar pelo menos 70% das vezes de inicio já é mais do que o suficiente.

Vale a pena citar que o número da frente altera a cada erro.

**Comment by jeanvetorello** [comment]
pelo menos esse novo captch só aparece na tela de login e algumas vezes , dá para logar na mão e deixar rolar

**Comment by yassbeno** [comment]
> 

não, isso também acontece quando você envia heróis para trabalhar depois de algum tempo

**Comment by doranelle** [comment]
Alguma mudança no código relacionada ao rastreio de movimentos, etc na tentativa de descobrir o bot?

**Comment by CorreiaDeveloper** [comment]
Rapazeada, fiquem espertos, hj ja rolou alguns posts de "Account Banned" no Grupo do Bomb do Discord...

**Comment by Galinho90** [comment]
> Rapazeada, fiquem espertos, hj ja rolou alguns posts de "Account Banned" no Grupo do Bomb do Discord...

Disseram que tem a ver com logar na mesma conta em dois pcs diferentes.

**Comment by Nucito** [comment]
> > Rapazeada, fiquem espertos, hj ja rolou alguns posts de "Account Banned" no Grupo do Bomb do Discord...
> 
> Disseram que tem a ver com logar na mesma conta em dois pcs diferentes.

Essa é uma regra bem clara do bomb:
È permitido ter mais de uma conta, mas no exato momento que vc loga com a mesma conta em dois pcs ao mesmo tempo sua conta pode ser banida permanentemente😁Ate o momento essa é a única coisa que esta gerando banimentos.

**Comment by VitotEPB** [comment]
O som deve ser emitido através de qual aplicação? Obrigado pelo empenho @mpcabete !
