### ISSUE TITLE
Novo captcha

### ISSUE THREAD

**Issue by rodrigobragamg** [mpcabete/bombcrypto-bot#179]
Agora tem que fazer um match entre o número e imagem (representando o mesmo número):

![image](https://user-images.githubusercontent.com/50714183/145147864-83d4abf1-f2d3-4c76-a6c4-661d68cd0342.png)

**Comment by Samuel-Oliveira** [comment]
Esse É pra fuder!

**Comment by rodrigobragamg** [comment]
O slide contém 05 opções (imagens) diferentes.

**Comment by mpcabete** [comment]
vamos usar o #178 pra discutir o capcha
