### ISSUE TITLE
Problemas com o Login

### ISSUE THREAD

**Issue by matheusanat** [mpcabete/bombcrypto-bot#18]
Olá! Primeiramente, muito obrigado pelo ótimo automatizador, tem sido muito benéfico.

Estou tendo um pequeno problema com a conexão ao aplicativo do jogo, pois o automatizador não finaliza da forma esperada a etapa de login, ele não seleciona o botão "SIGN/ASSINAR" na metamask.

Tentei alterar o idioma, para ser idêntico ao da imagem target, porém sem sucesso.

Poderia me auxiliar? Grato desde já.

**Comment by Scolmes1** [comment]
Olá, concordo com o Matheus, seu bot é muito útil, estou usando há alguns dias e está me ajudando muito, porém estou com o mesmo problema dele, o login não é sucedido, ele fica travado na hora que aparece a metamask para clickar (as partes hover e n hover), tenho certeza que vc irá resolver.

Mais uma vez, obrigado.

**Comment by matheusanat** [comment]
Amigo, hoje de tarde consegui resolver o problema...por hora.

Na pasta target, dentro dos arquivos do bot, após colocar a metamask em inglês, substitui a imagem de SIGN na metamask por um print do botão mais centralizado (sem a borda branca, apenas a parte azul e a escrita).

Não fiz o teste para a versão em português, mas vale a tentativa.

Não vou encerrar o tópico por motivos de ainda haverem dúvidas, mas estou a quase 1 dia rodando sem problemas.

**Comment by Scolmes1** [comment]
No meu caso, após ele clickar em ConnectWallet, ele não seleciona a metamask e dá sign, ele move o mouse para direita e cima, e após isso não faz nada.

**Comment by mpcabete** [comment]
ola, desculpem nao ter respondido antes, que bom que conseguiu arrumar matheus. era isso mesmo que iria sugerir, vou ver se tiro um tempinho pra colocar essa solução no readme pra quem estiver tendo problemas parecidos.

**Comment by mpcabete** [comment]
> No meu caso, após ele clickar em ConnectWallet, ele não seleciona a metamask e dá sign, ele move o mouse para direita e cima, e após isso não faz nada.

ola, da uma olhada se o que eu sugeri [aqui](https://github.com/mpcabete/bombcrypto-bot/issues/20#issuecomment-969851527) resolve.

**Comment by Scolmes1** [comment]
@mpcabete Bom dia, consegui resolver, aproveitei para mudar as fotos da metamask tmb, só por precaução, tirei a parte branca do hover e printei para ficar maior, e deu tudo certo, está funcionando direitinho, obrigado pela atenção e dedicação, quando tirar o pagamento te mando um agrado, obrigado :)

**Comment by eztzez** [comment]
> Olá, concordo com o Matheus, seu bot é muito útil, estou usando há alguns dias e está me ajudando muito, porém estou com o mesmo problema dele, o login não é sucedido, ele fica travado na hora que aparece a metamask para clickar (as partes hover e n hover), tenho certeza que vc irá resolver.
> 
> Pode ter certeza que uma parte do meu lucro com este jogo irá pra você, sem sombra de dúvidas.
> 
> Mais uma vez, obrigado.

Ola meu irmão
Também tenho quase tudo funcionando perfeitamente !!
Só quero que o código atualizado envie os heróis para casa, já que comprei um.
por favor me ajude
