### ISSUE TITLE
simpleaudio nao esta instalando

### ISSUE THREAD

**Issue by poloik007** [mpcabete/bombcrypto-bot#181]
Tendo problema ao instalar a biblioteca simpleaudio no windows: 

 error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

atualizei o pip mas mesmo assim continua, alguma sugestao ?

**Comment by yassbeno** [comment]
https://stackoverflow.com/a/55370133

**Comment by poloik007** [comment]
Atualizei o vistual studio e suas ferramentas e ainda assim o erro continua:
Parece que nao sou o unico com problemas para instalar essa biblioteca...

Collecting simpleaudio
  Using cached simpleaudio-1.0.4.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for simpleaudio, since package 'wheel' is not installed.
Installing collected packages: simpleaudio
    Running setup.py install for simpleaudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\PoloIk\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PoloIk\\AppData\\Local\\Temp\\pip-install-4vk55ng_\\simpleaudio_710083c9d9ef416197a8f35cd5abc12b\\setup.py'"'"'; __file__='"'"'C:\\Users\\PoloIk\\AppData\\Local\\Temp\\pip-install-4vk55ng_\\simpleaudio_710083c9d9ef416197a8f35cd5abc12b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PoloIk\AppData\Local\Temp\pip-record-a6iinj70\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\PoloIk\AppData\Local\Programs\Python\Python310\Include\simpleaudio'
         cwd: C:\Users\PoloIk\AppData\Local\Temp\pip-install-4vk55ng_\simpleaudio_710083c9d9ef416197a8f35cd5abc12b\
    Complete output (26 lines):
    running install
    C:\Users\PoloIk\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\__init__.py -> build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\shiny.py -> build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\functionchecks.py -> build\lib.win-amd64-3.10\simpleaudio
    creating build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\c.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\e.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\g.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\left_right.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\notes_2_16_44.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    running build_ext
    building 'simpleaudio._simpleaudio' extension
    creating build\temp.win-amd64-3.10
    creating build\temp.win-amd64-3.10\Release
    creating build\temp.win-amd64-3.10\Release\c_src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DDEBUG=0 -IC:\Users\PoloIk\AppData\Local\Programs\Python\Python310\include -IC:\Users\PoloIk\AppData\Local\Programs\Python\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include /Tcc_src/simpleaudio.c /Fobuild\temp.win-amd64-3.10\Release\c_src/simpleaudio.obj
    simpleaudio.c
    C:\Users\PoloIk\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\PoloIk\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PoloIk\\AppData\\Local\\Temp\\pip-install-4vk55ng_\\simpleaudio_710083c9d9ef416197a8f35cd5abc12b\\setup.py'"'"'; __file__='"'"'C:\\Users\\PoloIk\\AppData\\Local\\Temp\\pip-install-4vk55ng_\\simpleaudio_710083c9d9ef416197a8f35cd5abc12b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PoloIk\AppData\Local\Temp\pip-record-a6iinj70\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\PoloIk\AppData\Local\Programs\Python\Python310\Include\simpleaudio' Check the logs for full command output.

**Comment by poloik007** [comment]
Fechar esse issue e tratar do assunto no novo criado.
