### ISSUE TITLE
ERROR RODAR COMANDO REQUIREMENTS

### ISSUE THREAD

**Issue by Galinho90** [mpcabete/bombcrypto-bot#183]
C:\Users\leand\Documents\BombCrypto>pip install -r requirements
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements'
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\leand\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by yassbeno** [comment]
requirements.txt :)

**Comment by Galinho90** [comment]
> requirements.txt :)

ESSE E O RESULTADO

C:\Users\leand\Documents\BombCrypto>pip install -r requirements.txt
Requirement already satisfied: opencv-python in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (4.5.4.60)
Requirement already satisfied: mss in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (6.1.0)
Requirement already satisfied: pyautogui in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (0.9.53)
Requirement already satisfied: pyyaml in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 4)) (6.0)
Requirement already satisfied: requests in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (2.26.0)
Requirement already satisfied: numpy>=1.21.2 in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from opencv-python->-r requirements.txt (line 1)) (1.21.4)
Requirement already satisfied: pymsgbox in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from pyautogui->-r requirements.txt (line 3)) (1.0.9)
Requirement already satisfied: PyTweening>=1.0.1 in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from pyautogui->-r requirements.txt (line 3)) (1.0.4)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from pyautogui->-r requirements.txt (line 3)) (0.1.28)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from pyautogui->-r requirements.txt (line 3)) (0.0.9)
Requirement already satisfied: mouseinfo in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from pyautogui->-r requirements.txt (line 3)) (0.1.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 5)) (2.0.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 5)) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 5)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 5)) (1.26.7)
Requirement already satisfied: pyrect in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from pygetwindow>=0.0.5->pyautogui->-r requirements.txt (line 3)) (0.1.4)
Requirement already satisfied: pyperclip in c:\users\leand\appdata\local\programs\python\python310\lib\site-packages (from mouseinfo->pyautogui->-r requirements.txt (line 3)) (1.8.2)

**Comment by yassbeno** [comment]
muito bem, seus requisitos já estão satisfeitos, o que você quer que eu diga, inicie python index.py agora ...

**Comment by Galinho90** [comment]
> muito bem, seus requisitos já estão satisfeitos, o que você quer que eu diga, inicie python index.py agora ...

Obrigado.
