### ISSUE TITLE
Problema ao reproduzir sons em um servidor remoto

### ISSUE THREAD

**Issue by DimaxaGaming** [mpcabete/bombcrypto-bot#186]
Pessoal, fiquei intrigado aqui com a pergunta, novamente isso se deve aos sons que não me permitem iniciar o bot.

Eu executo este bot em um servidor Windows 2012 R2 remoto, todos os componentes estão instalados, mas o erro aparece na imagem.

O que pode ser feito sobre esse erro? Presumi que fosse pelo fato de os sons não funcionarem, mas tentei ligá-los e ainda não funciona. Se alguém encontrou este erro ou pode sugerir uma solução, responda nesta discussão.

Obrigado a todos.
![Screenshot_2](https://user-images.githubusercontent.com/69765601/145250846-e01a2d1f-559e-430c-a76d-997500d07536.png)

**Comment by AprendendoNodejs** [comment]
amigo, so remover as linhas. 

import simpleaudio

bell_sound = simpleaudio.WaveObject.from_wave_file("bell.wav")

bell_sound.play()

isso nao muda nada, e so uma merda de um alerta...

**Comment by DimaxaGaming** [comment]
> amigo, so remover as linhas.
> 
> import simpleaudio
> 
> bell_sound = simpleaudio.WaveObject.from_wave_file("bell.wav")
> 
> bell_sound.play()
> 
> isso nao muda nada, e so uma merda de um alerta...

Bro, mas o comando import funciona com a distribuição Linux, e eu tenho Windows.
