### ISSUE TITLE
Envio de mensagem com alerta

### ISSUE THREAD

**Issue by gabrielwjesus** [mpcabete/bombcrypto-bot#188]
Gente, eu vi já a solução de tocar um som. Acho legal. Mas no meu caso eu deixo o computador longe de mim e faço somente acesso remoto ao jogo
A ideia seria o robô continuar trabalhando de forma randômica sozinho
E quando a tela de captcha aparecer me enviar uma mensagem, um e-mail, sinal de fumaça kkkk
Vi uma solução de envio WhatsApp mas não funcionou (usando selenium), pq exige autorização do WhatsApp toda vez que abre a janela . 
Pra quem faz uso na nuvem, máquinas virtuais, etc... podem cooperar com essa ideia

**Comment by fguide** [comment]
Como você faz o acesso remoto no seu pc? Se for via RDP, a forma mais simples é habilitar o audio pela sessão RDP no seu cliente, assim você escutaria os sons no celular:

Um exemplo com RDP do windows:

![image](https://user-images.githubusercontent.com/95459411/145288464-b0d91cc2-7189-4a1d-b482-ba70e4eb03a3.png)

**Comment by zSinnK** [comment]
Usa o próprio Chrome remote, ele passa os sons do pc para o celular, só conectar e deixar o aplicativo em segundo plano que vai fazer o alerta

**Comment by Gaboo134** [comment]
o meu fecha quando esta em segundo plano

**Comment by gabrielwjesus** [comment]
> Como você faz o acesso remoto no seu pc? Se for via RDP, a forma mais simples é habilitar o audio pela sessão RDP no seu cliente, assim você escutaria os sons no celular:
> 
> Um exemplo com RDP do windows:
> 
> ![image](https://user-images.githubusercontent.com/95459411/145288464-b0d91cc2-7189-4a1d-b482-ba70e4eb03a3.png)

faço via chrome remote desktop, mas vou ver se tem alguma função assim lá

**Comment by gabrielwjesus** [comment]
> Usa o próprio Chrome remote, ele passa os sons do pc para o celular, só conectar e deixar o aplicativo em segundo plano que vai fazer o alerta

o problema é deixar o celular aberto o tempo todo, com o celular desligado ele desconecta do remoto

**Comment by kerferber** [comment]
Amigo, se for via telegram, te ajuda? Consegui configurar aqui, não é muito complicado...

![telegram](https://user-images.githubusercontent.com/95573625/145294036-9a4b5a48-2e0d-42f2-950f-d5309b5fa7da.jpg)

**Comment by Gaboo134** [comment]
como te achamos no telegram

**Comment by M1D4SG0LD3N** [comment]
> Amigo, se for via telegram, te ajuda? Consegui configurar aqui, não é muito complicado...
> 
> 
> 
> ![telegram](https://user-images.githubusercontent.com/95573625/145294036-9a4b5a48-2e0d-42f2-950f-d5309b5fa7da.jpg)
> 
> 
> 
> 
POR FAVOR NOS PASSE O CÓDIGO

**Comment by pwr43nd37** [comment]
essa do telegram ajuda é uma boa, eu estava estudando  essa ideia.

**Comment by kerferber** [comment]
Pessoal, fiz um rápido tutorial de como fiz isso no #189 

Por favor, testem e avisem se der algum bug, acho que consegui informar todos os passos

**Comment by gabrielwjesus** [comment]
> > Amigo, se for via telegram, te ajuda? Consegui configurar aqui, não é muito complicado...
> > ![telegram](https://user-images.githubusercontent.com/95573625/145294036-9a4b5a48-2e0d-42f2-950f-d5309b5fa7da.jpg)
> 
> POR FAVOR NOS PASSE O CÓDIGO

cola o codigo por favor

**Comment by gabrielwjesus** [comment]
isso ai gente, eu segui os passos do telegram e funcionou legal. Só seguir os passos.
Vou finalizar essa Issue
