### ISSUE TITLE
Carteira para doações

### ISSUE THREAD

**Issue by Zabuk** [mpcabete/bombcrypto-bot#19]
Olá mpcabete!

Gostaria confirmar contigo qual seria a moeda (BNB, BUSD), rede e carteira de sua escolha.

E obrigado pelo trabalho no bot, ajudou demais!

**Comment by mpcabete** [comment]
Oi amigo, tudo bem?
Muito obrigado por perguntar, e bom que eu já atualizo as informações.
No caso, este endereço que passei e da metamask, na rede smart chain:
0xbd06182D8360FB7AC1B05e871e56c76372510dDf
Quanto a moeda, pode me enviar a que for de sua preferência. Aceito até bcoins :)
Me avise se tiver outra informação que seja interessante eu passar também.

Agradeço muito a doação, você será o primeiro a doar, e isso me da bastante incentivo para continuar mantendo o bot e ajudando o pessoal que posta pedindo ajuda.

**Comment by Zabuk** [comment]
Peço perdão pela demora! Consegui doar hoje 5 BUSD, obrigado pelo seu trabalho! Aproveitando, tem algum plano de adaptar o bot para usar o menu rápido de seleção de heróis direto na tela do modo aventura? Valeu!
