### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Nzjj** [mpcabete/bombcrypto-bot#191]
Acho que seria interessante a criação de um discord onde poderíamos enviar as fotos do captcha e pode ter algumas atualizações sobre o andamento das atualizações

**Comment by neurose0** [comment]
verdade

**Comment by lifarrx** [comment]
up to dentro !

**Comment by THEBESTSZ** [comment]
Up!

**Comment by PinnDeath6** [comment]
UP

**Comment by viniciusfontao** [comment]
ter andamento das atualizações? basicamente ficar perguntando quanto falta pra terminarem? ficar cobrando status? eu prezo pela sanidade de quem está mexendo, então acho que não deveria ter.

**Comment by gabrielwjesus** [comment]
eu sou a favor de um grupo de desenvolvedores, seja no discord, seja no telegram.
Só fica no grupo quem tem noção em python e está disposto a quebrar a cabeça
quem não é, será excluido 
quem não sabe programar fica aqui esperando a solução

**Comment by guirar** [comment]
> eu sou a favor de um grupo de desenvolvedores, seja no discord, seja no telegram.
> 
> Só fica no grupo quem tem noção em python e está disposto a quebrar a cabeça
> 
> quem não é, será excluido 
> 
> quem não sabe programar fica aqui esperando a solução 

Já tem 😉

**Comment by LoboNFT** [comment]
ja estamos programando no discord, aguardem e nao criem mais topicos

**Comment by doranelle** [comment]
> ja estamos programando no discord, aguardem e nao criem mais topicos

Vocês poderiam avaliar cliques em locais variados dos botões e tempos randomizados depois da resolução do novo captcha?

**Comment by gabrielwjesus** [comment]
> ja estamos programando no discord, aguardem e nao criem mais topicos

Se puderem me chamar para o grupo posso ajudar nas resoluções dos problemas , se ainda tiver vaga 💪

**Comment by thiago-molive** [comment]
> ter andamento das atualizações? basicamente ficar perguntando quanto falta pra terminarem? ficar cobrando status? eu prezo pela sanidade de quem está mexendo, então acho que não deveria ter.

é so não entrar quem não entende de programação. pessoa que só quer usar espera ser liberado. e pra cobrar prazo precisa pagar, caso contrario a pessoa so estaria sendo imbecil
