### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by morgado198028** [mpcabete/bombcrypto-bot#193]
estou a ter este erro sera que alguem me consegue dizer porque 
im getting this error can some one tell me why 

C:\bot>python index.py
Traceback (most recent call last):
  File "C:\bot\index.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by fguide** [comment]
faltou instalar o modulo cv2, na pasta do bot, digite: pip install -r requirements.txt

**Comment by morgado198028** [comment]
mas eu fiz isso 
ate ja tentei 2 vezes instalar

**Comment by fguide** [comment]
Não deveria ter diferença pro ser VM, provavelmente o ambiente python da VM não está completo.

Quando você rodou o comando, qual mesnagens apareceram? Erros? Tente mandar o maximo d info possível para conseguirmos ajudar.

**Comment by morgado198028** [comment]
C:\Windows\system32>cd\bot

C:\bot>pip install -r requirements.txt
Requirement already satisfied: certifi==2021.10.8 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: charset-normalizer==2.0.9 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (2.0.9)
Requirement already satisfied: idna==3.3 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (3.3)
Requirement already satisfied: MouseInfo==0.1.3 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 4)) (0.1.3)
Collecting mss==6.1.0
  Using cached mss-6.1.0-py3-none-any.whl (76 kB)
Requirement already satisfied: numpy==1.21.4 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 6)) (1.21.4)
Collecting opencv-python==4.5.4.60
  Using cached opencv_python-4.5.4.60-cp310-cp310-win_amd64.whl (35.1 MB)
Collecting PyAutoGUI==0.9.53
  Using cached PyAutoGUI-0.9.53.tar.gz (59 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: PyGetWindow==0.0.9 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 9)) (0.0.9)
Requirement already satisfied: PyMsgBox==1.0.9 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 10)) (1.0.9)
Requirement already satisfied: pyperclip==1.8.2 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 11)) (1.8.2)
Requirement already satisfied: PyRect==0.1.4 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 12)) (0.1.4)
Requirement already satisfied: PyScreeze==0.1.28 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 13)) (0.1.28)
Collecting python3-xlib==0.15
  Using cached python3-xlib-0.15.tar.gz (132 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pytweening==1.0.4 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 15)) (1.0.4)
Collecting PyYAML==6.0
  Using cached PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
Collecting requests==2.26.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting simpleaudio==1.0.4
  Using cached simpleaudio-1.0.4.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: urllib3==1.26.7 in c:\users\bombcrypto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 19)) (1.26.7)
Using legacy 'setup.py install' for PyAutoGUI, since package 'wheel' is not installed.
Using legacy 'setup.py install' for python3-xlib, since package 'wheel' is not installed.
Using legacy 'setup.py install' for simpleaudio, since package 'wheel' is not installed.
Installing collected packages: simpleaudio, requests, PyYAML, python3-xlib, PyAutoGUI, opencv-python, mss
    Running setup.py install for simpleaudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\bombcrypto\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bombcrypto\\AppData\\Local\\Temp\\pip-install-zf2t8ls4\\simpleaudio_5622ca81952e4870a3cde7f0753e2b68\\setup.py'"'"'; __file__='"'"'C:\\Users\\bombcrypto\\AppData\\Local\\Temp\\pip-install-zf2t8ls4\\simpleaudio_5622ca81952e4870a3cde7f0753e2b68\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\bombcrypto\AppData\Local\Temp\pip-record-1moc0_na\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\bombcrypto\AppData\Local\Programs\Python\Python310\Include\simpleaudio'
         cwd: C:\Users\bombcrypto\AppData\Local\Temp\pip-install-zf2t8ls4\simpleaudio_5622ca81952e4870a3cde7f0753e2b68\
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\__init__.py -> build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\shiny.py -> build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\functionchecks.py -> build\lib.win-amd64-3.10\simpleaudio
    creating build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\c.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\e.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\g.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\left_right.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\notes_2_16_44.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    running build_ext
    building 'simpleaudio._simpleaudio' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\bombcrypto\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bombcrypto\\AppData\\Local\\Temp\\pip-install-zf2t8ls4\\simpleaudio_5622ca81952e4870a3cde7f0753e2b68\\setup.py'"'"'; __file__='"'"'C:\\Users\\bombcrypto\\AppData\\Local\\Temp\\pip-install-zf2t8ls4\\simpleaudio_5622ca81952e4870a3cde7f0753e2b68\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\bombcrypto\AppData\Local\Temp\pip-record-1moc0_na\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\bombcrypto\AppData\Local\Programs\Python\Python310\Include\simpleaudio' Check the logs for full command output.

C:\bot>python index.py
Traceback (most recent call last):
  File "C:\bot\index.py", line 2, in <module>
    from cv2 import cv2
ModuleNotFoundError: No module named 'cv2'

C:\bot>

**Comment by fguide** [comment]
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Tem que instalar o Microsoft C++ Build Tools. Veja #182

**Comment by Dfcrespi** [comment]
Traceback (most recent call last):
  File "/home/bombcrypto1/Desktop/bombcrypto-bot-main/index.py", line 696, in <module>
    solveNewCaptcha()
  File "/home/bombcrypto1/Desktop/bombcrypto-bot-main/index.py", line 692, in solveNewCaptcha
    img = images['nc']
KeyError: 'nc'

**Comment by Dfcrespii** [comment]
> Traceback (most recent call last):
> 
>   File "/home/bombcrypto1/Desktop/bombcrypto-bot-main/index.py", line 696, in <module>
> 
>     solveNewCaptcha()
> 
>   File "/home/bombcrypto1/Desktop/bombcrypto-bot-main/index.py", line 692, in solveNewCaptcha
> 
>     img = images['nc']
> 
> KeyError: 'nc'
> 
> 

Alguém sabe o que pode ser esse erro??

**Comment by teylor789** [comment]
https://i.imgur.com/aiaSdyo.png
Aqui tbm

**Comment by GdsLacerda** [comment]
@morgado198028
se for vps windows server 2012 tenta esse video
https://www.youtube.com/watch?v=TrBARrUjs1g

**Comment by Dfcrespi** [comment]
> @morgado198028 se for vps windows server 2012 tenta esse video https://www.youtube.com/watch?v=TrBARrUjs1g

VPN google Ubuntu
