### ISSUE TITLE
Error with when I did PIP Install

### ISSUE THREAD

**Issue by ggskiawp** [mpcabete/bombcrypto-bot#194]
Hi.

Can anyone help me with this error?
I received this error on the CMD after I put in the PIP Install command.

ERROR: Command errored out with exit status 1:

**Comment by fguide** [comment]
Was that the only error given? What's the output of: pytohn -V and pip -V ?

**Comment by ggskiawp** [comment]
This is the whole error message.

ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Skia\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Skia\\AppData\\Local\\Temp\\pip-install-w8buamh2\\simpleaudio_2c0a028a226f457f9070605115efd703\\setup.py'"'"'; __file__='"'"'C:\\Users\\Skia\\AppData\\Local\\Temp\\pip-install-w8buamh2\\simpleaudio_2c0a028a226f457f9070605115efd703\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Skia\AppData\Local\Temp\pip-record-2l75apuj\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Skia\AppData\Local\Programs\Python\Python310\Include\simpleaudio'
         cwd: C:\Users\Skia\AppData\Local\Temp\pip-install-w8buamh2\simpleaudio_2c0a028a226f457f9070605115efd703\
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\__init__.py -> build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\shiny.py -> build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\functionchecks.py -> build\lib.win-amd64-3.10\simpleaudio
    creating build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\c.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\e.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\g.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\left_right.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\notes_2_16_44.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    running build_ext
    building 'simpleaudio._simpleaudio' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Skia\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Skia\\AppData\\Local\\Temp\\pip-install-w8buamh2\\simpleaudio_2c0a028a226f457f9070605115efd703\\setup.py'"'"'; __file__='"'"'C:\\Users\\Skia\\AppData\\Local\\Temp\\pip-install-w8buamh2\\simpleaudio_2c0a028a226f457f9070605115efd703\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Skia\AppData\Local\Temp\pip-record-2l75apuj\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Skia\AppData\Local\Programs\Python\Python310\Include\simpleaudio' Check the logs for full command output.

**Comment by fguide** [comment]
>error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

So you need to install "Microsoft C++ Build Tools", there's #182  where they already discussed, take a look at the last replies, they are also in english.

**Comment by ggskiawp** [comment]
thank you.
