### ISSUE TITLE
Error solveNewCapta function

### ISSUE THREAD

**Issue by s1k3ira** [mpcabete/bombcrypto-bot#195]
Pessoal, está com erro em na função.

Traceback (most recent call last):
  File "index.py", line 696, in <module>
    solveNewCaptcha()
  File "index.py", line 692, in solveNewCaptcha
    img = images['nc']
KeyError: 'nc'

**Comment by s1k3ira** [comment]
> Antes de criar issue e cobrar algo, leia a pagina inicial, abraços.

Acredito, que não seja cobrar e sim contribuir caso ele ainda não tenha pegado o erro nos testes ! a parte de cobrar deixo por interpretação sua !

**Comment by krlinon** [comment]
É, tive o mesmo erro ao iniciar. Bom report!

**Comment by rodrigobg** [comment]
@0bomb4 Ninguém está cobrando nada cara. Apenas reportando o bug, erro. Simples.

**Comment by henriqueptorresbr** [comment]
Estou com o mesmo erro

**Comment by henriqueptorresbr** [comment]
Baixa a versão stable

**Comment by panghuahua2017** [comment]
Has the bot been updated to solve the newcapta?

**Comment by hamzalamou** [comment]
not yet

**Comment by Suflair3x** [comment]
> Baixa a versão stable

Onde encontro?

**Comment by s1k3ira** [comment]
> > Baixa a versão stable
> 
> Onde encontro?

Voce pode mudar a branch de main para stable

**Comment by henriqueptorresbr** [comment]
https://github.com/mpcabete/bombcrypto-bot.git

muda para a branch stable

**Comment by rodrigobg** [comment]
Pessoal a versão "main" está com uma função com erro, basta comentar essa função e adicionar "main()" 
NO final dela.
