### ISSUE TITLE
sugestão

### ISSUE THREAD

**Issue by lucasvieceli** [mpcabete/bombcrypto-bot#197]
uma ideia para melhorar o bot, e fazer que quando movimentar o mouse, colcocar uma velocidade aleatoria e tambem um percurso aleatorio, porque se o bomb tiver capturando os movimentos do mouse e perceber q sempre são iguais, poderia gerar ban

**Comment by LoboNFT** [comment]
Estamos trabalhando nisso, por favor nao crie mais topicos, vamos ter novidades neste final de semana!
