### ISSUE TITLE
Erro ao iniciar images['nc']

### ISSUE THREAD

**Issue by rodrigobg** [mpcabete/bombcrypto-bot#198]
Olá parabens pelo sistema, mas ele está com um problema ao iniciar
Traceback (most recent call last):
File "index.py", line 696, in
solveNewCaptcha()
File "index.py", line 692, in solveNewCaptcha
img = images['nc']
KeyError: 'nc'

**Comment by fguide** [comment]
Leia a pagina inicial, ainda nao esta finalizado.

**Comment by henriqueptorresbr** [comment]
Baixa a versão stable que funciona

**Comment by rodrigobg** [comment]
@henriqueptorresbr olá não sei onde baixar essa versão stable, poderia me ajudar?

**Comment by henriqueptorresbr** [comment]
![image](https://user-images.githubusercontent.com/44885654/145639386-93ef6ad5-fc5f-4f3c-b39f-07101e47dafa.png)

**Comment by zhangying927** [comment]
> ![image](https://user-images.githubusercontent.com/44885654/145639386-93ef6ad5-fc5f-4f3c-b39f-07101e47dafa.png)

Regardless of the branch of the code, there is no picture of nc,can you help me?
