### ISSUE TITLE
AntiCaptcha

### ISSUE THREAD

**Issue by testaxb3** [mpcabete/bombcrypto-bot#199]
Galera, um conhecido meu do discord desenvolveu um sistema de anticaptcha, parece funcional mas eu não entendo nada de programação. Se caso alguém tiver interesse em pegar o arquivo, acho que é só implementar no macro, bom não sei. Quem tiver interesse me manda uma mensagem aqui ou no discord pra conversar melhor, talvez ajude o pessoal aqui 

não consigo enviar o arquivo aqui, é um arquivo .model 

foi o @Nucito quem passou 
Galera ele criou um tópico 

https://github.com/Nucito/CaptchaSolver

**Comment by MauMorhy** [comment]
Coloque seus contatos...
Ou mesmo anexe o código na mensagem, todo ajuda é bem vinda

**Comment by fguide** [comment]
Não seria mais viável pegar o projeto desenvolvido e postar aqui para as pessoas analisarem e testarem? Lembrando que deve ser postado o código aberto, sem programas já compilados.

**Comment by rodrigobg** [comment]
@testaxb3  muito bom, manda pra mim, pra eu tentar implementar no código e deixar funcional.

**Comment by henriqueptorresbr** [comment]
Só faltou compartilhar o repositório

**Comment by jhones01** [comment]
> Galera, um conhecido meu do discord desenvolveu um sistema de anticaptcha, parece funcional mas eu não entendo nada de programação. Se caso alguém tiver interesse em pegar o arquivo, acho que é só implementar no macro, bom não sei. Quem tiver interesse me manda uma mensagem aqui ou no discord pra conversar melhor, talvez ajude o pessoal aqui


Manda o fonte, para que possa analisar.

**Comment by mtmassa** [comment]
Alguém sabe se o @testaxb3 disponibilizou o código?

**Comment by pointmaster2** [comment]
https://youtu.be/dshG0lY_Pgg

**Comment by kerferber** [comment]
> https://youtu.be/dshG0lY_Pgg

de novo fazendo propaganda? ajuda a comunidade, cara... se toca.

**Comment by joelsneto** [comment]
> Galera, um conhecido meu do discord desenvolveu um sistema de anticaptcha, parece funcional mas eu não entendo nada de programação. Se caso alguém tiver interesse em pegar o arquivo, acho que é só implementar no macro, bom não sei. Quem tiver interesse me manda uma mensagem aqui ou no discord pra conversar melhor, talvez ajude o pessoal aqui

Compartilhe mais, a comunidade agradece!

**Comment by riciarossi** [comment]
> 

me chama no discord, whatsapp ou telegram por favor: 18 981198039
ou discord: Myth#9180

**Comment by fguide** [comment]
> > 
> 
> me chama no discord, whatsapp ou telegram por favor: 18 981198039 ou discord: Myth#9180

Cuidado com o que você receber, o código oficial ainda não foi lançado, melhor aguardar alguns dias e ficar seguro do que arriscar com fontes não conhecidas.

**Comment by riciarossi** [comment]
> Cuidado com o que você receber, o código oficial ainda não foi lançado, melhor aguardar alguns dias e ficar seguro do que arriscar com fontes não conhecidas.

relaxa, eu sou programador... já estava desenvolvendo a minha versão por deep learning também, porem ainda falta muito e estou com pouco tempo, então se alguem já fez algo do tipo, fica muito mais fácil apenas adaptar ao bot atual.

**Comment by testaxb3** [comment]
Galera não da pra enviar aqui, mas me chama no discord

**Comment by hamzalamou** [comment]
> 

cara, qual é a sua discord

**Comment by hamzalamou** [comment]
> Galera não da pra enviar aqui, mas me chama no discord

**Comment by MauMorhy** [comment]
Chamar como cara?

**Comment by hamzalamou** [comment]
> 



> Chamar como cara?

eu não entendi o que você disse

**Comment by MauMorhy** [comment]
Esquece cara.... acho que deu pra entender já.
Alguém consegue fechar esse issue aqui?
Além de desproveitoso pode ser um tipo de golpe.
O cara não posta código, não posta contato, não posta fonte, e PARECE querer cobrar se alguém entrar em contato.

**Comment by dionatharibeiro** [comment]
@mpcabete fecha a issue aqui mano, ou pede para alguém com permissão, mais um espertinho vendendo codigo compilado.

**Comment by hamzalamou** [comment]
> 



> Esquece cara.... acho que deu pra entender já. Alguém consegue fechar esse issue aqui? Além de desproveitoso pode ser um tipo de golpe. O cara não posta código, não posta contato, não posta fonte, e PARECE querer cobrar se alguém entrar em contato.

Eu concordo com você

**Comment by IrohsTeahouse** [comment]
Nego comédia vem no codigo aberto, onde tá tendo mo esforço do pessoal pra resolver o captcha, pra oferecer o seu codigo pago kkkkkk vai se fuder.

**Comment by testaxb3** [comment]
Caralho, soubesse que ia ter tanto comentário negativo não tentava ajudar na resolução do problema, mas relaxa eu mesmo apago aqui sem problemas.

**Comment by mpcabete** [comment]
Salve amigo, ja conversei com ele no disc hj kkkk, ta bem massa a implementaçao dele, devo integrar ao bot essa madruga ainda!

**Comment by testaxb3** [comment]
Enfim não da pra apagar, não sabia que a conta minha aqui não tinha meu discord, não entendo nada disso aqui, caso alguém quiser me chamar é testa#1222 meu discord.

**Comment by testaxb3** [comment]
O programa anti captcha não é meu, e de um conhecido no discord deixei o @ dele aí.

**Comment by dionatharibeiro** [comment]
@testaxb3 é que toda hora aparece alguém vendendo aqueles códigos fechados que sabemos bem que vem lotado de logger e o caramba a 4 para roubar conta, então quando ouvimos barulho de cascos pensamos em cavalos, e não em zebra como era seu caso kkk mas que bom deu certo com o mpcabete.

**Comment by riciarossi** [comment]
> O programa anti captcha não é meu, e de um conhecido no discord deixei o @ dele aí.

te adicionei no discord, Myth,  obrigado bro

**Comment by Nucito** [comment]
> Não seria mais viável pegar o projeto desenvolvido e postar aqui para as pessoas analisarem e testarem? Lembrando que deve ser postado o código aberto, sem programas já compilados.

Isso resolve seu problema amigo?
https://github.com/Nucito/CaptchaSolver

**Comment by rodrigobragamg** [comment]
> > Não seria mais viável pegar o projeto desenvolvido e postar aqui para as pessoas analisarem e testarem? Lembrando que deve ser postado o código aberto, sem programas já compilados.
> 
> Isso resolve seu problema amigo? https://github.com/Nucito/CaptchaSolver

Parabéns @Nucito.

> > Não seria mais viável pegar o projeto desenvolvido e postar aqui para as pessoas analisarem e testarem? Lembrando que deve ser postado o código aberto, sem programas já compilados.
> 
> Isso resolve seu problema amigo? https://github.com/Nucito/CaptchaSolver

Parabéns, você quebrou o captcha primeiro então.
Mas o seu código não está com ele atrelado ao bot né?

**Comment by fguide** [comment]
> > Não seria mais viável pegar o projeto desenvolvido e postar aqui para as pessoas analisarem e testarem? Lembrando que deve ser postado o código aberto, sem programas já compilados.
> 
> Isso resolve seu problema amigo? https://github.com/Nucito/CaptchaSolver

Qual problema? Desculpa se interpretou errado a minha resposta, mas estava apenas sugerindo uma forma de interação mais de acordo com as políticas aqui do github, sem envolver redes sociais terceiras, afinal nem todo mundo utiliza discord e afins.

Enfim, obrigado pelo código, assim que possível vou dar uma olhada nele!

**Comment by cesarfran12** [comment]
> Salve amigo, ja conversei com ele no disc hj kkkk, ta bem massa a implementaçao dele, devo integrar ao bot essa madruga ainda!

fico esperando, valeu dms

**Comment by Nucito** [comment]
@rodrigobragamg Infelizmente eu fui o segundo kkkkkkk mas sim o meu so faz a leitura do captcha do fundo que era o que o pessoal estava com maior dificuldade para conseguir quebrar, o mpcabete ja tem tudo que precisa para colocar o bot rodando novamente😁

**Comment by Nucito** [comment]
> > > Não seria mais viável pegar o projeto desenvolvido e postar aqui para as pessoas analisarem e testarem? Lembrando que deve ser postado o código aberto, sem programas já compilados.
> > 
> > 
> > Isso resolve seu problema amigo? https://github.com/Nucito/CaptchaSolver
> 
> Qual problema? Desculpa se interpretou errado a minha resposta, mas estava apenas sugerindo uma forma de interação mais de acordo com as políticas aqui do github, sem envolver redes sociais terceiras, afinal nem todo mundo utiliza discord e afins.
> 
> Enfim, obrigado pelo código, assim que possível vou dar uma olhada nele!

Bom uso 😉 se gostar do projeto so deixar a estrela pra dar um help kkkkkk
