### ISSUE TITLE
Nao esta colocando os herois para trabalhar

### ISSUE THREAD

**Issue by delmarado** [mpcabete/bombcrypto-bot#2]
Oi para começar muito obrigado pelo trabalho, esta tudo funcionando mas nao ta pondo os herois para trabalhar, quando ele tenta fazer scroll so mexe um pouco e nao coloca ninguem para trabalhar, na consola fala buttons 0.
Nao sei se é so para mim tem como testar ai?

**Comment by mpcabete** [comment]
Ola, por aqui esta funcionando sim. Eu dei uma arrumada nos arquivos, tenta tirar um print screen do botão de mandar o herói trabalhar e substituir na pasta targets. Pode ser que o seu esteja um pouco diferente do meu, e por isso o BOT não reconheça.

**Comment by delmarado** [comment]
Ola eu fiz o que voce falou e agr manda trabalhar mas nao todos, ele clicka no work de cinco bonecos mas depois quando vai dar scroll para baixo nao é o suficiente para o proximo botao de work ficar totalmente visivel entao ele so fecha e entra no treasure hunt.

**Comment by delmarado** [comment]
Esta tudo funcionando menos  o scroll, quando chega na hora de dar scroll o rato da uma travadinha e nao faz scroll, tem ideia do que podera ser? Estou jogando num laptop e nao tenho mouse apenas o mousepad k vem nos laptop.

**Comment by mpcabete** [comment]
eu coloquei duas opções a mais na config que podem ajudar. Tenta mudar a "use_click_and_drag_instead_of_scroll" pra true, se nao funcionar, muda de volta pra false e aumenta o numero do scroll size

**Comment by delmarado** [comment]
Muito obrigado com o click and drag esta funcionando perfeitamente, perfeito o bot.

**Comment by mpcabete** [comment]
Sem problemas! Eu agradeceria se você pudesse contribuir com uns bcoin ou com o paypal, até agora ngm contribuiu nada :(
