### ISSUE TITLE
Alguem sabe qual pode ser o erro? atualizei o Microsoft Visual e continua a msm coisa

### ISSUE THREAD

**Issue by guiitz** [mpcabete/bombcrypto-bot#200]
C:\Bomb>pip install -r requirements.txt
Requirement already satisfied: certifi==2021.10.8 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: charset-normalizer==2.0.9 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 2)) (2.0.9)
Requirement already satisfied: idna==3.3 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 3)) (3.3)
Requirement already satisfied: MouseInfo==0.1.3 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 4)) (0.1.3)
Collecting mss==6.1.0
  Using cached mss-6.1.0-py3-none-any.whl (76 kB)
Requirement already satisfied: numpy==1.21.4 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 6)) (1.21.4)
Collecting opencv-python==4.5.4.60
  Using cached opencv_python-4.5.4.60-cp310-cp310-win_amd64.whl (35.1 MB)
Collecting PyAutoGUI==0.9.53
  Using cached PyAutoGUI-0.9.53.tar.gz (59 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: PyGetWindow==0.0.9 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 9)) (0.0.9)
Requirement already satisfied: PyMsgBox==1.0.9 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 10)) (1.0.9)
Requirement already satisfied: pyperclip==1.8.2 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 11)) (1.8.2)
Requirement already satisfied: PyRect==0.1.4 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 12)) (0.1.4)
Requirement already satisfied: PyScreeze==0.1.28 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 13)) (0.1.28)
Collecting python3-xlib==0.15
  Using cached python3-xlib-0.15.tar.gz (132 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pytweening==1.0.4 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 15)) (1.0.4)
Collecting PyYAML==6.0
  Using cached PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
Collecting requests==2.26.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting simpleaudio==1.0.4
  Using cached simpleaudio-1.0.4.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: urllib3==1.26.7 in c:\program files\python310\lib\site-packages (from -r requirements.txt (line 19)) (1.26.7)
Using legacy 'setup.py install' for PyAutoGUI, since package 'wheel' is not installed.
Using legacy 'setup.py install' for python3-xlib, since package 'wheel' is not installed.
Using legacy 'setup.py install' for simpleaudio, since package 'wheel' is not installed.
Installing collected packages: simpleaudio, requests, PyYAML, python3-xlib, PyAutoGUI, opencv-python, mss
    Running setup.py install for simpleaudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\guilh\\AppData\\Local\\Temp\\pip-install-3mvhxr34\\simpleaudio_7593fc4cba3744a5a0371b419eca5f5d\\setup.py'"'"'; __file__='"'"'C:\\Users\\guilh\\AppData\\Local\\Temp\\pip-install-3mvhxr34\\simpleaudio_7593fc4cba3744a5a0371b419eca5f5d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\guilh\AppData\Local\Temp\pip-record-7m1nxcpy\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Python310\Include\simpleaudio'
         cwd: C:\Users\guilh\AppData\Local\Temp\pip-install-3mvhxr34\simpleaudio_7593fc4cba3744a5a0371b419eca5f5d\
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\__init__.py -> build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\shiny.py -> build\lib.win-amd64-3.10\simpleaudio
    copying simpleaudio\functionchecks.py -> build\lib.win-amd64-3.10\simpleaudio
    creating build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\c.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\e.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\g.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\left_right.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    copying simpleaudio\test_audio\notes_2_16_44.wav -> build\lib.win-amd64-3.10\simpleaudio\test_audio
    running build_ext
    building 'simpleaudio._simpleaudio' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\guilh\\AppData\\Local\\Temp\\pip-install-3mvhxr34\\simpleaudio_7593fc4cba3744a5a0371b419eca5f5d\\setup.py'"'"'; __file__='"'"'C:\\Users\\guilh\\AppData\\Local\\Temp\\pip-install-3mvhxr34\\simpleaudio_7593fc4cba3744a5a0371b419eca5f5d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\guilh\AppData\Local\Temp\pip-record-7m1nxcpy\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Python310\Include\simpleaudio' Check the logs for full command output.

**Comment by fguide** [comment]
Já tentou isso? 

https://github.com/mpcabete/bombcrypto-bot/issues/182#issuecomment-988892940

**Comment by GdsLacerda** [comment]
da uma olhada no inssue #182 
nas fotos que o gus4ng postou la

**Comment by henriqueptorresbr** [comment]
Instala todas as ferramentas de desenvolvedor do visual-cpp-build-tools que funciona

**Comment by rodrigobg** [comment]
Tem que instalar o visual C++ 14 baixar direto no site da Microsoft e instalar essas bibliotecas.
