### ISSUE TITLE
Hard Wallet / Anti-Idle

### ISSUE THREAD

**Issue by TomazMPP** [mpcabete/bombcrypto-bot#201]
O novo bot vai ter uma função 'anti-idle'? Por que se o jogo ficar dando idle, não vai ter como o bot entrar na conta de quem tem hardwallet como eu, já que pra logar é necessário autorização na wallet física

**Comment by neowyse** [comment]
pqp, verdade mano, esse anti-idle ia ser a boa pq tbm tenho hard wallet

**Comment by rodrigobragamg** [comment]
Já discutido no tópico oficial escolhido pelo criador...
Expliquei que o refresh do map já faz essa função.
