### ISSUE TITLE
Sugestão de solução imediata

### ISSUE THREAD

**Issue by LabaxuriaZ** [mpcabete/bombcrypto-bot#202]
Uma solução genérica pode ser de ensinar o bot a arrastar o captcha ao mesmo local toda vez, já que não há bloqueio... Ele vai ficar tentando até acertar, a única questão é que vai tomar um tempo a mais. Faça o teste... acredito que seja uma solução imediata!

**Comment by pwr43nd37** [comment]
nao rola amigo, imagine que ficar errando o captcha varias vezes pode gerar alguma suspeita pelos devs de ser bot. e gerar algum tipo de punição. Ja foi sugerido essa ideia antes...

**Comment by 0bomb4** [comment]
relaxa que o monstro ja ta saindo da jaula
