### ISSUE TITLE
Parabéns pelo modelo

### ISSUE THREAD

**Issue by allysonlm** [mpcabete/bombcrypto-bot#203]
Já tive oportunidade de trab com ciência de dados.

Olhei parte de sua solução. Parabéns, critou um modelo com pytorch.

Irei dar minha contribuição pela dedicação, não deve ter sido nada fácil, com pouco tempo.

O bot subiu pra outro patamar, abrindo novas portas caso tenha novos captchas.

Abs.

**Comment by Nucito** [comment]
@allysonlm Fico feliz que tenha gostado do modelo kkkkk não tive como treinar ele com muitas imagens mas ate que compensou com o tratamento das imagens, o YOLOv5 deu uma baita ajuda com o processo😅
