### ISSUE TITLE
O bot não reconhece o novo captcha

### ISSUE THREAD

**Issue by DimaxaGaming** [mpcabete/bombcrypto-bot#206]
Olá pessoal. Decidi tentar o branch mpcabete atualizado onde ele adicionou arquivos para resolver o novo captcha, mas por algum motivo não tenho nenhum impacto com este captcha. O bot funciona corretamente, mas não consegue resolver o novo captcha, apenas para neste momento, esperando que eu mesmo resolva (como era antes. O que pode ser feito com esse problema?

**Comment by Yumiizera** [comment]
Leia o redme sobre.

**Comment by DimaxaGaming** [comment]
Eu olhei a data de modificação e revisão e o README foi atualizado antes do diretório "Captcha" ser adicionado. Lá, o Readme não descreve o que está errado, mas tudo o que foi escrito antes de mim.

**Comment by GdsLacerda** [comment]
**Novo captcha:
Quase pronto, deve sair esse fim de samana ainda!**

essa parte do readme

**Comment by joelsneto** [comment]
> Olá pessoal. Decidi tentar o branch mpcabete atualizado onde ele adicionou arquivos para resolver o novo captcha, mas por algum motivo não tenho nenhum impacto com este captcha. O bot funciona corretamente, mas não consegue resolver o novo captcha, apenas para neste momento, esperando que eu mesmo resolva (como era antes. O que pode ser feito com esse problema?

o sistema ainda não foi totalmente otimizado para realizar o Captcha. Na página principal aqui no Git Hub o @mpcabete deixou explícito que está na fase final de programação, talvez neste final de semana saia.

**Comment by viniciusfontao** [comment]
é só ler:
Quase pronto, deve sair esse fim de samana ainda!

**Comment by DimaxaGaming** [comment]
Obrigado, pensei que estava feito, já que mpcabete carregou os arquivos em "Captcha". Então vou esperar a atualização.
