### ISSUE TITLE
fiz um fork com algumas mudanças que pode interessar até sair o captcha

### ISSUE THREAD

**Issue by gabrielwjesus** [mpcabete/bombcrypto-bot#207]
[Mudanças](https://github.com/gabrielwjesus/bombcrypto-bot)
Eu separei em 3 modulos e logo que sairo captcha ficará em 4 modulos
1 modulo para o index 
2 modulo para o gerador de logs
3 modulo para enviar alerta no telegram caso: aparecer captcha, erro, idle, queda de conexão
4 modulo para resolver o captcha (que ainda está sendo desenvolvido)

no index eu fiz o mouse movimentar randomico, direções aleatorias, quantidade aleatorias. Clicar pra ver quantidade de moedas e jaulas. Selecionar aleatoriamente quem vai pro mapa trabalhar.... tempos aleatórios em todas as ações. 

Da pra ler o README que fiz mostrando somente o que atualizei e o que estou desenvolvendo, pode ser que algumas partes dos códigos interessem a alguem ou ao projeto aqui 

Se alguem quiser ajudar a realizar mudanças de melhoria é só chamar.

**Comment by mtmassa** [comment]
Top

**Comment by mtmassa** [comment]
Mas onde está esse fork?

**Comment by gabrielwjesus** [comment]
> Top

O código está no botão "mudanças" no começo do texto

**Comment by espinozachristian** [comment]
Boa, dei uma olhada rapida, ficou bem organizado, eu ainda não realizei nenhum teste sobre seu codigo, mas só por curiosidade, parte do captcha você foi por tentativa e erro? 
de resto parabens pela organização do codigo e deixar o codigo mais "limpo" e estruturado separando os modulos ^^

**Comment by gabrielwjesus** [comment]
> Boa, dei uma olhada rapida, ficou bem organizado, eu ainda não realizei nenhum teste sobre seu codigo, mas só por curiosidade, parte do captcha você foi por tentativa e erro? de resto parabens pela organização do codigo e deixar o codigo mais "limpo" e estruturado separando os modulos ^^

o captcha nao esta desenvolvido no codigo ainda, estou testando ele fora do codigo. Espero que de certo em breve.

**Comment by joelsneto** [comment]
Obrigado por compartilhar!

**Comment by espinozachristian** [comment]
> > Boa, dei uma olhada rapida, ficou bem organizado, eu ainda não realizei nenhum teste sobre seu codigo, mas só por curiosidade, parte do captcha você foi por tentativa e erro? de resto parabens pela organização do codigo e deixar o codigo mais "limpo" e estruturado separando os modulos ^^
> 
> o captcha nao esta desenvolvido no codigo ainda, estou testando ele fora do codigo. Espero que de certo em breve.

entendo, mas de qualquer forma ficou bom, a parte da aleatoriedade dos clicks e movimentos eu queria ter implementado no meu , então se me permite vou pegar a ideia e modificar um pouquinho kkk, eu só tinha os tempos e msg para o telegram mais customizada digamos ^^

**Comment by f4rruda** [comment]
Olá parabéns pela organização. ao iniciar o bot aparece o seguinte erro:
File "C:\Bomb\index.py", line 380, in <module>
    main()
  File "C:\Bomb\index.py", line 344, in main
    if now - last["error"] > t['error_screen']:
KeyError: 'error_screen'

**Comment by gabrielwjesus** [comment]
> Olá parabéns pela organização. ao iniciar o bot aparece o seguinte erro:
> 
> File "C:\Bomb\index.py", line 380, in <module>
> 
>     main()
> 
>   File "C:\Bomb\index.py", line 344, in main
> 
>     if now - last["error"] > t['error_screen']:
> 
> KeyError: 'error_screen'

Tenta baixar de novo os arquivos . Faz o login normal e deixa na tela do jogo 
Aí roda o script e deixa o jogo aberto
Manda aqui o que der de erro
Acabei de deixar rodando em casa

**Comment by gabrielwjesus** [comment]
> > > Boa, dei uma olhada rapida, ficou bem organizado, eu ainda não realizei nenhum teste sobre seu codigo, mas só por curiosidade, parte do captcha você foi por tentativa e erro? de resto parabens pela organização do codigo e deixar o codigo mais "limpo" e estruturado separando os modulos ^^
> 
> > 
> 
> > o captcha nao esta desenvolvido no codigo ainda, estou testando ele fora do codigo. Espero que de certo em breve.
> 
> 
> 
> entendo, mas de qualquer forma ficou bom, a parte da aleatoriedade dos clicks e movimentos eu queria ter implementado no meu , então se me permite vou pegar a ideia e modificar um pouquinho kkk, eu só tinha os tempos e msg para o telegram mais customizada digamos ^^

Manda as ideias kkkk de repente ajuda a melhorar o meu aqui

**Comment by espinozachristian** [comment]
> > > > Boa, dei uma olhada rapida, ficou bem organizado, eu ainda não realizei nenhum teste sobre seu codigo, mas só por curiosidade, parte do captcha você foi por tentativa e erro? de resto parabens pela organização do codigo e deixar o codigo mais "limpo" e estruturado separando os modulos ^^
> > 
> > 
> > > 
> > 
> > 
> > > o captcha nao esta desenvolvido no codigo ainda, estou testando ele fora do codigo. Espero que de certo em breve.
> > 
> > 
> > entendo, mas de qualquer forma ficou bom, a parte da aleatoriedade dos clicks e movimentos eu queria ter implementado no meu , então se me permite vou pegar a ideia e modificar um pouquinho kkk, eu só tinha os tempos e msg para o telegram mais customizada digamos ^^
> 
> Manda as ideias kkkk de repente ajuda a melhorar o meu aqui

Parte do telegram to terminando de organizar quando ele starta um mapa novo falando quanto rendeu o mapa antigo então, pegar start BCOIN - End BCOIN trazendo assim o valor do mapa, da até para puxa cotação atual, mas isso só gera ansiedade para venda ou desanimo kkk, tb pode dar o tempo de "farm" do mapa, pior parte é só organizar quem mandar em inicio de mapa, mas ai como eu to sem heroi melhor que raro, nao adianta mto eu trabalhar em cima disso,
Parte dos click eu curti quando vc anda com o mouse aleatorio, porem ainda é movimentos "retos" falta só as curvas, ja que é mais humano isso kkkk de resto acho que ta bem zica o seu 🍡

**Comment by gabrielwjesus** [comment]
> > > > > Boa, dei uma olhada rapida, ficou bem organizado, eu ainda não realizei nenhum teste sobre seu codigo, mas só por curiosidade, parte do captcha você foi por tentativa e erro? de resto parabens pela organização do codigo e deixar o codigo mais "limpo" e estruturado separando os modulos ^^
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > o captcha nao esta desenvolvido no codigo ainda, estou testando ele fora do codigo. Espero que de certo em breve.
> 
> > > 
> 
> > > 
> 
> > > entendo, mas de qualquer forma ficou bom, a parte da aleatoriedade dos clicks e movimentos eu queria ter implementado no meu , então se me permite vou pegar a ideia e modificar um pouquinho kkk, eu só tinha os tempos e msg para o telegram mais customizada digamos ^^
> 
> > 
> 
> > Manda as ideias kkkk de repente ajuda a melhorar o meu aqui
> 
> 
> 
> Parte do telegram to terminando de organizar quando ele starta um mapa novo falando quanto rendeu o mapa antigo então, pegar start BCOIN - End BCOIN trazendo assim o valor do mapa, da até para puxa cotação atual, mas isso só gera ansiedade para venda ou desanimo kkk, tb pode dar o tempo de "farm" do mapa, pior parte é só organizar quem mandar em inicio de mapa, mas ai como eu to sem heroi melhor que raro, nao adianta mto eu trabalhar em cima disso,
> 
> Parte dos click eu curti quando vc anda com o mouse aleatorio, porem ainda é movimentos "retos" falta só as curvas, ja que é mais humano isso kkkk de resto acho que ta bem zica o seu 🍡 

Eu li alguns projetos de movimentos humanizados em python mas é mto sinistro e ainda assim ele faz movimentos com ângulos sempre similares 
De repente da pra implementar alternando entre reta e ângulo 

A ideia de pegar o valor do bcoin eu tinha pensado em pegar o início do programa e o final do programa
Além de capturar em tempos aleatorios 
Mas tua ideia ficou mais massa

**Comment by Romario-Francisco-Soares** [comment]
Qual branch main ? 
Erro:
File "C:\bombcrypto-bot-main\index.py", line 380, in <module>
    main()
  File "C:\bombcrypto-bot-main\index.py", line 344, in main
    if now - last["error"] > t['error_screen']:
KeyError: 'error_screen'

Tentei Refazer o download, deixar o joguinho aberto e etc... o problema manteve.

**Comment by ricardofernandess** [comment]
Levei o mesmo erro que o colega acima. Tive que comentar esse trecho de código referente ao error_screen

**Comment by gabrielwjesus** [comment]
esse error é pq falta uma parte do config.yaml
vou atualizar o arquivo aqui 
essa função fica aguardando alguma tela de erro ... semelhante ao aguardar pelo captcha

**Comment by mtmassa** [comment]
Colocaram o Solve do captcha num dos issues, acho que rola voce incorporar a fun;áo no seu bot, https://github.com/Nucito/CaptchaSolver 
Credito para o Nucito.
Gostei da ideia ideia do seu, integra;áo com o telegran, etc.. parabens

**Comment by henriqueptorresbr** [comment]
Muito bacana, baixa da branch main ?

**Comment by lpstyle** [comment]
> Muito bacana, baixa da branch main ?

```
Traceback (most recent call last):
  File "c:\bomb2\index.py", line 6, in <module>
    import CaptchaSolver.captcha_solver
ModuleNotFoundError: No module named 'CaptchaSolver'
```

o meu so da esse erro.

**Comment by Nucito** [comment]
> > Muito bacana, baixa da branch main ?
> 
> ```
> Traceback (most recent call last):
>   File "c:\bomb2\index.py", line 6, in <module>
>     import CaptchaSolver.captcha_solver
> ModuleNotFoundError: No module named 'CaptchaSolver'
> ```
> 
> o meu so da esse erro.

Faça o clone do [CaptchaSolver](https://github.com/Nucito/CaptchaSolver) e coloque dentro da pasta do seu bot😁
