### ISSUE TITLE
Problemas com a Execucao dos Comandos

### ISSUE THREAD

**Issue by maycon3569** [mpcabete/bombcrypto-bot#208]
pip install -r requirements.txt  

da um erro, alguem consegue me ajudar 

  Using cached tensorboard-2.7.0-py3-none-any.whl (5.8 MB)
ERROR: Could not find a version that satisfies the requirement torch>=1.7.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.7.0

**Comment by maycon3569** [comment]
![image](https://user-images.githubusercontent.com/95973915/145682458-92ae37de-a778-4827-aa6f-a6ab5aa9ed2a.png)

**Comment by DimaxaGaming** [comment]
Necessita do python 3.9.X

**Comment by maycon3569** [comment]
onde consigo pegar isso ai

**Comment by maycon3569** [comment]
![image](https://user-images.githubusercontent.com/95973915/145683054-33cba3e1-f3ce-4536-9dce-7cab23dd1eb7.png)

**Comment by fguide** [comment]
requirements.txt, faltou a extensão.

**Comment by MauMorhy** [comment]
> onde consigo pegar isso ai

Tem que ser o 3.9?
3.10 não rola?

**Comment by MauMorhy** [comment]
> Necessita do python 3.9.X

Tem que ser o 3.9.x?
O 3.10 não funciona?

**Comment by Nucito** [comment]
@MauMorhy O python 3.10 não tem suporte oficialmente para o torch 😅

**Comment by henriqueptorresbr** [comment]
usa o comando pip install -r requirementes**.txt**

**Comment by MarcosEgles** [comment]
Alguem poderia me dizer como fazer o downgrade do python 3.10 para o 3.9.x? 
Agradeço dês de ja.

**Comment by 0bomb4** [comment]
@MarcosEgles  to testando aqui dei um unistall pelo painel de controle, e depois (como ja tinha instalado o 3.9.9) dei um repair e agora to instalando de boa aqui.

Link 3.9.9 https://www.python.org/ftp/python/3.9.9/python-3.9.9-amd64.exe

**Comment by robinhodemorais** [comment]
mesmo rodando o comando pip install -r requirements.txt não foi aqui

**Comment by MarcosEgles** [comment]
@0bomb4 Vlw maninho vou fazer o mesmo, achei que teria um comando pelo cmd pra fazer o downgrade mais facilmente.

**Comment by nasiloski** [comment]
Aqui mesmo fazendo downgrade do Python varios pacotes do php não instalaram, como o simple audio, cv2 e alguns outros.

**Comment by nasiloski** [comment]
> @0bomb4 Vlw maninho vou fazer o mesmo, achei que teria um comando pelo cmd pra fazer o downgrade mais facilmente.

Nada é fácil no windows kkkk

**Comment by poloik007** [comment]
> Aqui mesmo fazendo downgrade do Python varios pacotes do php não instalaram, como o simple audio, cv2 e alguns outros.

ta foda mesmo tendo que instalar tudo na mao

**Comment by nasiloski** [comment]
Galera ta tendo erro porque o simpleaudio nao foi removido do projeto, então quem nao tinha feito toda a função de colocar o microsoft visual c++ vai ter que fazer. Se essa lib de audio nao for usada, seria melhor remover do projeto
