### ISSUE TITLE
Interface Gráfica

### ISSUE THREAD

**Issue by BenitoMarculanoRibeiro** [mpcabete/bombcrypto-bot#209]
Alguém que sabe criar uma interface gráfica pode me ajudar aqui? Queria criar um botão Start/Stop aqui, mas não sei como parar o código de uma maneira certa. Ele sempre fica rodando por mais tempo.

**Comment by Nucito** [comment]
@BenitoMarculanoRibeiro Após fazer o CTRL+C ele ainda continua rodando? '-'

**Comment by BenitoMarculanoRibeiro** [comment]
Estou falando de fazer uma interface gráfica para ficar mais "elegante" e poder parar com um clique em um botão.
