### ISSUE TITLE
hello can someone help me 

### ISSUE THREAD

**Issue by hamzalamou** [mpcabete/bombcrypto-bot#211]
![image](https://user-images.githubusercontent.com/35382455/145688206-06d20aa7-48f3-44d8-8211-dde982951cf6.png)

**Comment by espinozachristian** [comment]
> ![image](https://user-images.githubusercontent.com/35382455/145688206-06d20aa7-48f3-44d8-8211-dde982951cf6.png)

wait the stable version :)

**Comment by hamzalamou** [comment]
> > ![image](https://user-images.githubusercontent.com/35382455/145688206-06d20aa7-48f3-44d8-8211-dde982951cf6.png)
> 
> wait the stable version :)

Okey thanks man

**Comment by henriqueptorresbr** [comment]
Baixa a versão da branch Stable

**Comment by hamzalamou** [comment]
> 



> Baixa a versão da branch Stable

Como eu posso fazer isso
eu só encontrei a nova versão com captcha
