### ISSUE TITLE
KeyError: 'nc'

### ISSUE THREAD

**Issue by mkroxm** [mpcabete/bombcrypto-bot#212]
Traceback (most recent call last):
  File "D:\1\2\index.py", line 696, in <module>
    solveNewCaptcha()
  File "D:\1\2\index.py", line 692, in solveNewCaptcha
    img = images['nc']
KeyError: 'nc' 

Any solutions

**Comment by espinozachristian** [comment]
> Traceback (most recent call last): File "D:\1\2\index.py", line 696, in solveNewCaptcha() File "D:\1\2\index.py", line 692, in solveNewCaptcha img = images['nc'] KeyError: 'nc'
> 
> Any solutions

please, read others issues, wait the new branch stable :)

**Comment by mkroxm** [comment]
ok thanks  closing it
