### ISSUE TITLE
Versão pessoal do solveCaptcha

### ISSUE THREAD

**Issue by thiago-molive** [mpcabete/bombcrypto-bot#214]
Eu consegui fazer funcionar com a ajuda do pessoal  da comunidade que disponibilizou conteúdos interessantes.

ainda não testei o suficiente e to com pouco tempo agora, ainda mais final de semana né.

quem quiser olhar ta no meu fork do git https://github.com/thiago-molive/bombcrypto-bot

não vou pedir pull request, porque eu fiz um monte de coisas e também não me preocupei, muito, com otimizações e processamento, (nem cheguei a ver o  consumo processamento da aplicação)

**Comment by pwr43nd37** [comment]
Parabéns man, ele tá funcionando com multi tela?

**Comment by mtmassa** [comment]
> Eu consegui fazer funcionar com a ajuda do pessoal da comunidade que disponibilizou conteúdos interessantes.
> 
> ainda não testei o suficiente e to com pouco tempo agora, ainda mais final de semana né.
> 
> quem quiser olhar ta no meu fork do git https://github.com/thiago-molive/bombcrypto-bot
> 
> não vou pedir pull request, porque eu fiz um monte de coisas e também não me preocupei, muito, com otimizações e processamento, (nem cheguei a ver o consumo processamento da aplicação)

Fala chefe blz, cara muito legal seu bot e as funções, no windows conseguir fazer ele rodar, mas pra diminuir problemas mudei pro linux kkk, ai nao consegui instalar o tesseract, nao consegui montar a extrutura de pastas, se puder me dar uma ajudinha nisso fico grato, valeu, parabens, obrigado
