### ISSUE TITLE
bug No module named 'simpleaudio'

### ISSUE THREAD

**Issue by Snexo** [mpcabete/bombcrypto-bot#215]
hello can any help me please ? 

`@lin5:~/Desktop/bombcrypto-bot-main$ pip install -r requirements.txt
ERROR: Double requirement given: opencv-python>=4.1.2 (from -r requirements.txt (line 24)) (already in opencv-python==4.5.4.60 (from -r requirements.txt (line 7)), name='opencv-python')
snexos@lin5:~/Desktop/bombcrypto-bot-main$ pip install -r requirements.txt
ERROR: Double requirement given: opencv-python>=4.1.2 (from -r requirements.txt (line 24)) (already in opencv-python==4.5.4.60 (from -r requirements.txt (line 7)), name='opencv-python')
@lin5:~/Desktop/bombcrypto-bot-main$ python3 index.py
Traceback (most recent call last):
  File "index.py", line 3, in <module>
    import simpleaudio
ModuleNotFoundError: No module named 'simpleaudio'
`

`

**Comment by espinozachristian** [comment]
> hello can any help me please ?
> 
> `@lin5:~/Desktop/bombcrypto-bot-main$ pip install -r requirements.txt ERROR: Double requirement given: opencv-python>=4.1.2 (from -r requirements.txt (line 24)) (already in opencv-python==4.5.4.60 (from -r requirements.txt (line 7)), name='opencv-python') snexos@lin5:~/Desktop/bombcrypto-bot-main$ pip install -r requirements.txt ERROR: Double requirement given: opencv-python>=4.1.2 (from -r requirements.txt (line 24)) (already in opencv-python==4.5.4.60 (from -r requirements.txt (line 7)), name='opencv-python') @lin5:~/Desktop/bombcrypto-bot-main$ python3 index.py Traceback (most recent call last): File "index.py", line 3, in <module> import simpleaudio ModuleNotFoundError: No module named 'simpleaudio' `
> 
> `

use cmd ->> pip install simpleaudio

**Comment by Nydoehar** [comment]
Tive problemas com o simpleaudio (ERROR: Failed building wheel for simpleaudio). Resolvi com:

sudo apt-get install libasound2-dev && pip3 install simpleaudio && pip install -r requirements.txt
