### ISSUE TITLE
ERROR: No matching distribution found for torch>=1.7.0

### ISSUE THREAD

**Issue by mtmassa** [mpcabete/bombcrypto-bot#216]
tentando rodar o novo bot mas tenho esse erro ao rodas o install requiriments

ERROR: Could not find a version that satisfies the requirement torch>=1.7.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.7.0

![image](https://user-images.githubusercontent.com/22082480/145692002-44077d9e-a1ff-40aa-b10d-4b58af242db0.png)
![image](https://user-images.githubusercontent.com/22082480/145692049-c8d322a9-5498-484d-b71c-a703bdba5c69.png)

**Comment by joelsneto** [comment]
Estou com o mesmo problema por aqui. =(

**Comment by rsilveira91** [comment]
mesmo problema no Linux

**Comment by 0bomb4** [comment]
veja aqui https://github.com/mpcabete/bombcrypto-bot/issues/208

**Comment by zSinnK** [comment]
Aconteceu aqui. Fui pelo mais simples, apaguei o torch das requirements, logo dps tele tem o torchview porém também dá erro de versão, troca o 0.8.2 por 0.2.2 

Dps disso não tá dando erro aqui, tô terminando de instalar os requirements e vou ver se roda o bot

**Comment by DimaxaGaming** [comment]
Instale o Python 3.9.X, pois ainda não há suporte para Torch no 3.10

E tente pip install torch

Deveria trabalhar ...

**Comment by mtmassa** [comment]
Obrigado a todos, lendo todas as dicas entendi que o problema era com o Python 3.10. removi ele e instalei o 3,9,9 e o visual studio e todos install pip install -r requirements.txt segui corretamente. Obrigado a todos

**Comment by kalleldf** [comment]
> Obrigado a todos, lendo todas as dicas entendi que o problema era com o Python 3.10. removi ele e instalei o 3,9,9 e o visual studio e todos install pip install -r requirements.txt segui corretamente. Obrigado a todos

como desinstala a versão 3.10 do python? só instalar a outra versão e já sobrepoe ela?
