### ISSUE TITLE
Erro ModuleNotFound torch

### ISSUE THREAD

**Issue by robinhodemorais** [mpcabete/bombcrypto-bot#217]
python index.py 
Traceback (most recent call last):
  File "index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "/home/linuxlite/Downloads/bombcrypto-bot-main/captcha/solveCaptcha.py", line 8, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by mtmassa** [comment]
mesmo erro aqui, ate abri um issue, tentei em 2 PC e o mesmo erro nos dois. tentei instalar o torch 0,1,7 sozinho mas o mesmo erro aparece.

**Comment by 0bomb4** [comment]
Boa tarde, faça o minimo e leia a pagina inicial

Solução #208
Galere evita criar multiplos issues com a mesma coisa.

**Comment by DimaxaGaming** [comment]
Instale o Python 3.9.X, pois ainda não há suporte para Torch no 3.10

E tente pip install torch

Deveria trabalhar ...

**Comment by amatoxd** [comment]
> Instale o Python 3.9.X, pois ainda não há suporte para Torch no 3.10
> 
> E tente pip install torch
> 
> Deveria trabalhar ...

Acho que só se for 64bits. No meu caso, na virtual machine, uso 32 e tenho que instalar a 3.8.6.

**Comment by VitotEPB** [comment]
> > Instale o Python 3.9.X, pois ainda não há suporte para Torch no 3.10
> 
> > 
> 
> > E tente pip install torch
> 
> > 
> 
> > Deveria trabalhar ...
> 
> 
> 
> Acho que só se for 64bits. No meu caso, na virtual machine, uso 32 e tenho que instalar a 3.8.6.

Você tem link de algum issue que ensina a rodar em mais de uma conta?

**Comment by Alt4s** [comment]
> pip install torch

valeu!

**Comment by mpcabete** [comment]
Vlw pessoal!
