### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zSinnK** [mpcabete/bombcrypto-bot#218]
primeiramente queria agradecer mpcabete pelo empenho no projeto.

então, estou tendo uns probleminhas tentando instalar as requeriments novas ( segue print ) 
tenho instalado o C++ como pede no erro, alguém consegue me dar uma luz? 
![Captura de tela 2021-12-11 185850](https://user-images.githubusercontent.com/95734505/145693074-b790706b-8bd3-43e8-9494-1047b3b7797a.png)

**Comment by Schn0z** [comment]
pior que estou com o mesmo erro

**Comment by MarsuraPedro** [comment]
aqui installei tudo do Visual dnv, e funcionou, fodendos 6.5gb ahhaha, mas funcionou
e coloquei --force no install requeriments

**Comment by zSinnK** [comment]
Gente, aqui no caso eu acabei tentando rodar o bot mesmo tendo dado esse erro nos requirements e o bot funcionou perfeitamente
