### ISSUE TITLE
Mandei meu primeiro Bcoin, confirma se recebeu depois, eh nois, assim que eu fizer saque vejo se mandar mais

### ISSUE THREAD

**Issue by MarsuraPedro** [mpcabete/bombcrypto-bot#22]
Mandei meu primeiro Bcoin, confirma se recebeu depois, eh nois, assim que eu fizer saque vejo se mandar mais

**Comment by mpcabete** [comment]
O marsura, recebi sim.
Agradeço de mais, você é o primeiro a realmente doar.

**Comment by MarsuraPedro** [comment]
Assim que eu fizer meu primeiro saque mando mais XD, eh que tinha pouco ahhahah, do que sobrou da compra
