### ISSUE TITLE
Erro ao instalar os requerimentos

### ISSUE THREAD

**Issue by cadugevaerd** [mpcabete/bombcrypto-bot#221]
Em anexo estou adicionando o log do erro ao tentar instalar
[error_requeriments.txt](https://github.com/mpcabete/bombcrypto-bot/files/7697822/error_requeriments.txt)
.

**Comment by 0bomb4** [comment]
Remove o simple audio do requeriments.txt 
Acredito que não vá afetar na funcionalidade  do objetivo principal.
