### ISSUE TITLE
ERROR - INSTALEI O PYTHON 3.9, INSTALEI TORCH, ATUALIZEI O PIP E ...

### ISSUE THREAD

**Issue by Alt4s** [mpcabete/bombcrypto-bot#224]
vamos lá: desinstalei o python e instalei o 3.9
executei o comando pip instal torch
atualizei o pip
executei o pip install requeriments
tentei rodar e continua aparecendo erro

![image](https://user-images.githubusercontent.com/95438518/145693447-30127f80-ef03-43ca-af1d-2c6e961b4914.png)

**Comment by 0bomb4** [comment]
O proprio erro na imagem está dizendo o que está faltando algo relacionado a microsoft visual studio

https://download.visualstudio.microsoft.com/download/pr/c91ba3a2-4ed9-4ada-ac4a-01f62c9c86a9/14283cd5284c019e3a40d845ee7be2501a1de0dcc51f873077d8560abc4b728a/vs_BuildTools.exe

Baixe e selecione a primeira opção algo sobre c++ e depois só clicar instalar. 
Dai voce usa o comando -pip install blabla novamente.

**Comment by Alt4s** [comment]
Consegui. O @mpcabete atualizou o requeriments e agora deu certo !!!

**Comment by 0bomb4** [comment]
O ninja está on
