### ISSUE TITLE
Torch [RESOLVIDO] 

### ISSUE THREAD

**Issue by Nzjj** [mpcabete/bombcrypto-bot#227]
Erro após a utilização do comando 
Os outros arquivos são instalado corretamente. 

`pip install -r requirements.txt`

`ERROR: Could not find a version that satisfies the requirement torch==1.10.0 (from versions: none)
ERROR: No matching distribution found for torch==1.10.0`

**Comment by EoAraujo** [comment]
aqui acontece a mesma coisa
ERROR: Could not find a version that satisfies the requirement torch>=1.7.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.7.0

**Comment by mpcabete** [comment]
tenta atualizar o requirements.txt e vê se resolve

**Comment by Nzjj** [comment]
> tenta atualizar o requirements.txt e vê se resolve

Atualizei o requirementes.txt e realmente foi. 
OBS - Eu estava com o Python 3.10 e fiz um downgrade para o 3.9.9

**Comment by Redexote** [comment]
> > tenta atualizar o requirements.txt e vê se resolve
> 
> Atualizei o requirementes.txt e realmente foi. OBS - Eu estava com o Python 3.10 e fiz um downgrade para o 3.9.9

como fazer o dowgrade?

**Comment by Nzjj** [comment]
Apenas deletei e instalei de volta. (sei que é possível fazer direto por um comando.)

**Comment by mtmassa** [comment]
> > > tenta atualizar o requirements.txt e vê se resolve
> > 
> > 
> > Atualizei o requirementes.txt e realmente foi. OBS - Eu estava com o Python 3.10 e fiz um downgrade para o 3.9.9
> 
> como fazer o dowgrade?

desinstala e instala a versao 3.9.9
