### ISSUE TITLE
cv2 error

### ISSUE THREAD

**Issue by abeltulio** [mpcabete/bombcrypto-bot#228]
C:\Bomb>python index.py
Traceback (most recent call last):
  File "C:\Bomb\index.py", line 2, in <module>
    from cv2 import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by Nucito** [comment]
> C:\Bomb>python index.py Traceback (most recent call last): File "C:\Bomb\index.py", line 2, in from cv2 import cv2 ModuleNotFoundError: No module named 'cv2'

pip install opencv-python

**Comment by abeltulio** [comment]
help again?


C:\Bomb>python index.py
Traceback (most recent call last):
  File "C:\Bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\Bomb\captcha\solveCaptcha.py", line 5, in <module>
    import mss
ModuleNotFoundError: No module named 'mss'

**Comment by DimaxaGaming** [comment]
> help again?
> 
> C:\Bomb>python index.py Traceback (most recent call last): File "C:\Bomb\index.py", line 4, in from captcha.solveCaptcha import solveCaptcha File "C:\Bomb\captcha\solveCaptcha.py", line 5, in import mss ModuleNotFoundError: No module named 'mss'

pip install mss

**Comment by abeltulio** [comment]
again

C:\Bomb>python index.py
Traceback (most recent call last):
  File "C:\Bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\Bomb\captcha\solveCaptcha.py", line 13, in <module>
    model = torch.hub.load('./captcha', 'custom', "captcha/bomb_captcha.pt", source='local')
  File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 425, in _load_local
    hub_module = import_module(MODULE_HUBCONF, hubconf_path)
  File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 76, in import_module
    spec.loader.exec_module(module)
  File "./captcha\hubconf.py", line 12, in <module>
    from models.yolo import Model
  File "C:\Bomb\./captcha\models\yolo.py", line 9, in <module>
    from models.common import *
  File "C:\Bomb\./captcha\models\common.py", line 12, in <module>
    from utils.datasets import letterbox
  File "C:\Bomb\./captcha\utils\datasets.py", line 23, in <module>
    from utils.general import xyxy2xywh, xywh2xyxy, xywhn2xyxy, xyn2xy, segment2box, segments2boxes, resample_segments, \
  File "C:\Bomb\./captcha\utils\general.py", line 18, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by Nucito** [comment]
> again
> 
> C:\Bomb>python index.py Traceback (most recent call last): File "C:\Bomb\index.py", line 4, in from captcha.solveCaptcha import solveCaptcha File "C:\Bomb\captcha\solveCaptcha.py", line 13, in model = torch.hub.load('./captcha', 'custom', "captcha/bomb_captcha.pt", source='local') File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 399, in load model = _load_local(repo_or_dir, model, *args, **kwargs) File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 425, in _load_local hub_module = import_module(MODULE_HUBCONF, hubconf_path) File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 76, in import_module spec.loader.exec_module(module) File "./captcha\hubconf.py", line 12, in from models.yolo import Model File "C:\Bomb./captcha\models\yolo.py", line 9, in from models.common import * File "C:\Bomb./captcha\models\common.py", line 12, in from utils.datasets import letterbox File "C:\Bomb./captcha\utils\datasets.py", line 23, in from utils.general import xyxy2xywh, xywh2xyxy, xywhn2xyxy, xyn2xy, segment2box, segments2boxes, resample_segments, File "C:\Bomb./captcha\utils\general.py", line 18, in import yaml ModuleNotFoundError: No module named 'yaml'

Amigo agradeço se vc colocar o seguinte comando no seu cmd:

pip install -r requirements.txt

**Comment by abeltulio** [comment]
ja fiz esse comando, e da erro e agora ta dando o erro que coloquei por ultimo

**Comment by abeltulio** [comment]
da erro em uma parte escrita simpleaudio e outra escrita pycocotools

**Comment by abeltulio** [comment]
ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abelt\\AppData\\Local\\Temp\\pip-install-b3ecieqd\\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\\setup.py'"'"'; __file__='"'"'C:\\Users\\abelt\\AppData\\Local\\Temp\\pip-install-b3ecieqd\\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\abelt\AppData\Local\Temp\pip-wheel-e7yatzhr'
       cwd: C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\simpleaudio
  copying simpleaudio\__init__.py -> build\lib.win-amd64-3.9\simpleaudio
  copying simpleaudio\shiny.py -> build\lib.win-amd64-3.9\simpleaudio
  copying simpleaudio\functionchecks.py -> build\lib.win-amd64-3.9\simpleaudio
  creating build\lib.win-amd64-3.9\simpleaudio\test_audio
  copying simpleaudio\test_audio\c.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
  copying simpleaudio\test_audio\e.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
  copying simpleaudio\test_audio\g.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
  copying simpleaudio\test_audio\left_right.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
  copying simpleaudio\test_audio\notes_2_16_44.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
  running build_ext
  building 'simpleaudio._simpleaudio' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for simpleaudio
  Running setup.py clean for simpleaudio
  Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abelt\\AppData\\Local\\Temp\\pip-install-b3ecieqd\\pycocotools_edacd52a900e4ad4aef18d9a47a276d5\\setup.py'"'"'; __file__='"'"'C:\\Users\\abelt\\AppData\\Local\\Temp\\pip-install-b3ecieqd\\pycocotools_edacd52a900e4ad4aef18d9a47a276d5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\abelt\AppData\Local\Temp\pip-wheel-yzzxt5x5'
       cwd: C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\pycocotools_edacd52a900e4ad4aef18d9a47a276d5\
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.9\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.9\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.9\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.9\pycocotools
  running build_ext
  skipping 'pycocotools\_mask.c' Cython extension (up-to-date)
  building 'pycocotools._mask' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
Failed to build simpleaudio pycocotools
Installing collected packages: simpleaudio, seaborn, PyYAML, python3-xlib, pycocotools
    Running setup.py install for simpleaudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abelt\\AppData\\Local\\Temp\\pip-install-b3ecieqd\\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\\setup.py'"'"'; __file__='"'"'C:\\Users\\abelt\\AppData\\Local\\Temp\\pip-install-b3ecieqd\\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\abelt\AppData\Local\Temp\pip-record-zoahw0pk\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Python39\Include\simpleaudio'
         cwd: C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\simpleaudio
    copying simpleaudio\__init__.py -> build\lib.win-amd64-3.9\simpleaudio
    copying simpleaudio\shiny.py -> build\lib.win-amd64-3.9\simpleaudio
    copying simpleaudio\functionchecks.py -> build\lib.win-amd64-3.9\simpleaudio
    creating build\lib.win-amd64-3.9\simpleaudio\test_audio
    copying simpleaudio\test_audio\c.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
    copying simpleaudio\test_audio\e.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
    copying simpleaudio\test_audio\g.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
    copying simpleaudio\test_audio\left_right.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
    copying simpleaudio\test_audio\notes_2_16_44.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
    running build_ext
    building 'simpleaudio._simpleaudio' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abelt\\AppData\\Local\\Temp\\pip-install-b3ecieqd\\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\\setup.py'"'"'; __file__='"'"'C:\\Users\\abelt\\AppData\\Local\\Temp\\pip-install-b3ecieqd\\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\abelt\AppData\Local\Temp\pip-record-zoahw0pk\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Python39\Include\simpleaudio' Check the logs for full command output.

**Comment by 0bomb4** [comment]
So fazer o download novamente, foi atualizado nao tem mais requeriment para o simple audio :)

**Comment by Nucito** [comment]
> pycocotools

Pode remover esses dois nenhum deles estão sendo usados😁

**Comment by Nucito** [comment]
> ## ERROR: Command errored out with exit status 1:
> command: 'C:\Program Files\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\setup.py'"'"'; **file**='"'"'C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\abelt\AppData\Local\Temp\pip-wheel-e7yatzhr'
> cwd: C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\simpleaudio_48edcf9efe944b8e908b56d4c8016a32
> Complete output (18 lines):
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build\lib.win-amd64-3.9
> creating build\lib.win-amd64-3.9\simpleaudio
> copying simpleaudio__init__.py -> build\lib.win-amd64-3.9\simpleaudio
> copying simpleaudio\shiny.py -> build\lib.win-amd64-3.9\simpleaudio
> copying simpleaudio\functionchecks.py -> build\lib.win-amd64-3.9\simpleaudio
> creating build\lib.win-amd64-3.9\simpleaudio\test_audio
> copying simpleaudio\test_audio\c.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
> copying simpleaudio\test_audio\e.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
> copying simpleaudio\test_audio\g.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
> copying simpleaudio\test_audio\left_right.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
> copying simpleaudio\test_audio\notes_2_16_44.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio
> running build_ext
> building 'simpleaudio._simpleaudio' extension
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
> ## ERROR: Failed building wheel for simpleaudio
> Running setup.py clean for simpleaudio
> Building wheel for pycocotools (setup.py) ... error
> ERROR: Command errored out with exit status 1:
> command: 'C:\Program Files\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\pycocotools_edacd52a900e4ad4aef18d9a47a276d5\setup.py'"'"'; **file**='"'"'C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\pycocotools_edacd52a900e4ad4aef18d9a47a276d5\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\abelt\AppData\Local\Temp\pip-wheel-yzzxt5x5'
> cwd: C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\pycocotools_edacd52a900e4ad4aef18d9a47a276d5
> Complete output (14 lines):
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build\lib.win-amd64-3.9
> creating build\lib.win-amd64-3.9\pycocotools
> copying pycocotools\coco.py -> build\lib.win-amd64-3.9\pycocotools
> copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.9\pycocotools
> copying pycocotools\mask.py -> build\lib.win-amd64-3.9\pycocotools
> copying pycocotools__init__.py -> build\lib.win-amd64-3.9\pycocotools
> running build_ext
> skipping 'pycocotools_mask.c' Cython extension (up-to-date)
> building 'pycocotools._mask' extension
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
> ERROR: Failed building wheel for pycocotools Running setup.py clean for pycocotools Failed to build simpleaudio pycocotools Installing collected packages: simpleaudio, seaborn, PyYAML, python3-xlib, pycocotools Running setup.py install for simpleaudio ... error ERROR: Command errored out with exit status 1: command: 'C:\Program Files\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\setup.py'"'"'; **file**='"'"'C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\abelt\AppData\Local\Temp\pip-record-zoahw0pk\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Python39\Include\simpleaudio' cwd: C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\simpleaudio_48edcf9efe944b8e908b56d4c8016a32 Complete output (18 lines): running install running build running build_py creating build creating build\lib.win-amd64-3.9 creating build\lib.win-amd64-3.9\simpleaudio copying simpleaudio__init__.py -> build\lib.win-amd64-3.9\simpleaudio copying simpleaudio\shiny.py -> build\lib.win-amd64-3.9\simpleaudio copying simpleaudio\functionchecks.py -> build\lib.win-amd64-3.9\simpleaudio creating build\lib.win-amd64-3.9\simpleaudio\test_audio copying simpleaudio\test_audio\c.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio copying simpleaudio\test_audio\e.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio copying simpleaudio\test_audio\g.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio copying simpleaudio\test_audio\left_right.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio copying simpleaudio\test_audio\notes_2_16_44.wav -> build\lib.win-amd64-3.9\simpleaudio\test_audio running build_ext building 'simpleaudio._simpleaudio' extension error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ ---------------------------------------- ERROR: Command errored out with exit status 1: 'C:\Program Files\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\setup.py'"'"'; **file**='"'"'C:\Users\abelt\AppData\Local\Temp\pip-install-b3ecieqd\simpleaudio_48edcf9efe944b8e908b56d4c8016a32\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\abelt\AppData\Local\Temp\pip-record-zoahw0pk\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Python39\Include\simpleaudio' Check the logs for full command output.

[Baixe isso](https://www.microsoft.com/pt-br/download/details.aspx?id=48145)

**Comment by abeltulio** [comment]
voltou a dar o erro do yaml mas o arquivo esta na minha pasta

**Comment by abeltulio** [comment]
C:\Bomb>python index.py
Traceback (most recent call last):
  File "C:\Bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\Bomb\captcha\solveCaptcha.py", line 13, in <module>
    model = torch.hub.load('./captcha', 'custom', "captcha/bomb_captcha.pt", source='local')
  File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 425, in _load_local
    hub_module = import_module(MODULE_HUBCONF, hubconf_path)
  File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 76, in import_module
    spec.loader.exec_module(module)
  File "./captcha\hubconf.py", line 12, in <module>
    from models.yolo import Model
  File "C:\Bomb\./captcha\models\yolo.py", line 9, in <module>
    from models.common import *
  File "C:\Bomb\./captcha\models\common.py", line 12, in <module>
    from utils.datasets import letterbox
  File "C:\Bomb\./captcha\utils\datasets.py", line 23, in <module>
    from utils.general import xyxy2xywh, xywh2xyxy, xywhn2xyxy, xyn2xy, segment2box, segments2boxes, resample_segments, \
  File "C:\Bomb\./captcha\utils\general.py", line 18, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by abeltulio** [comment]
C:\Bomb>python index.py
Traceback (most recent call last):
  File "C:\Bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\Bomb\captcha\solveCaptcha.py", line 13, in <module>
    model = torch.hub.load('./captcha', 'custom', "captcha/bomb_captcha.pt", source='local')
  File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 425, in _load_local
    hub_module = import_module(MODULE_HUBCONF, hubconf_path)
  File "C:\Program Files\Python39\lib\site-packages\torch\hub.py", line 76, in import_module
    spec.loader.exec_module(module)
  File "./captcha\hubconf.py", line 12, in <module>
    from models.yolo import Model
  File "C:\Bomb\./captcha\models\yolo.py", line 9, in <module>
    from models.common import *
  File "C:\Bomb\./captcha\models\common.py", line 14, in <module>
    from utils.plots import color_list, plot_one_box
  File "C:\Bomb\./captcha\utils\plots.py", line 15, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
