### ISSUE TITLE
Bot não consegue assinar a Metamask

### ISSUE THREAD

**Issue by CorreiaDeveloper** [mpcabete/bombcrypto-bot#23]
Notei que quando o jogo desconectava, o bot não conseguia assinar a MetaMask para conectar novamente, primeiro achei que era porque minha MetaMask estava em português, e em um dos Targets o botão estava como “Sign”, acompanhei o processo para ver, e vi que ele clica em “Connect” porém ao invés de ir com o mouse até o Sign, ele vai um pouco mais acima e não consegue prosseguir, sabe como resolvo?

**Comment by MarsuraPedro** [comment]
ola, tente aumentar a opção:
trashhold: default: 0.7
para um número maior, como 0.8 ou 0.9

**Comment by CorreiaDeveloper** [comment]
Funcionou perfeitamente alterando para 0.9
Muito obrigado!
