### ISSUE TITLE
Problema de reconexão

### ISSUE THREAD

**Issue by DimaxaGaming** [mpcabete/bombcrypto-bot#230]
O bot não consegue se reconectar ao sistema e quando você clica no botão "Conectar carteira", uma janela pop-up aparece e o bot, em vez de clicar em "Assinar", depois de um tempo clica em "Conectar carteira", fechando assim o janela de pop-up. Como isso pode ser consertado?

**Comment by Nzjj** [comment]
Primeiro, realmente apareceu Assinar na sua metamask ? Se sim, você precisa alterar a linga dela para inglês.

**Comment by mtmassa** [comment]
> O bot não consegue se reconectar ao sistema e quando você clica no botão "Conectar carteira", uma janela pop-up aparece e o bot, em vez de clicar em "Assinar", depois de um tempo clica em "Conectar carteira", fechando assim o janela de pop-up. Como isso pode ser consertado?

Tem que usar a carteira no idioma ingles . vc faz isso nas configura;óes

**Comment by DimaxaGaming** [comment]
Sim pessoal, obrigado, aparentemente pela primeira vez ocorreu algum tipo de erro e o bot decidiu não apertar o botão.

Eu fecho o galho.
