### ISSUE TITLE
ERROR - No module named 'cv2'

### ISSUE THREAD

**Issue by kalleldf** [mpcabete/bombcrypto-bot#231]
estou tendo esse erro depois de instalar o novo bot

C:\bomb>python index.py
Traceback (most recent call last):
  File "C:\bomb\index.py", line 2, in <module>
    from cv2 import cv2
ModuleNotFoundError: No module named 'cv2'

Alguém pode ajudar?

**Comment by mtmassa** [comment]
Ta rando o python 3.9.9. Instalou o visual estudio? dou o install requiriments novamente?

https://github.com/mpcabete/bombcrypto-bot/issues/182#issuecomment-988892940
