### ISSUE TITLE
Multi account

### ISSUE THREAD

**Issue by far0fa** [mpcabete/bombcrypto-bot#232]
Alguem sabe como faço pra rodar o programa em multi account?

**Comment by nascimentolf** [comment]
> 

No momento não existe multi account, é preciso de uma VM ou PC para cada conta!

**Comment by coradini1** [comment]
Vai nos pull requests tem um multi account la

**Comment by far0fa** [comment]
@coradini1 mas ja esta funcionando com esse novo bot? vi que tem diferenças nos codigos

**Comment by coradini1** [comment]
Sim, se tu ler até o final do pull, tu ve que ele já atualizou com o solve captcha

**Comment by far0fa** [comment]
@coradini1 vi que vc comentou la que estava em loop, ainda acontece isso ou ja arrumou?

**Comment by coradini1** [comment]
Pra mim n, mas é q eu tenho 5 contas rodando. Até o bot fazer a volta em todas contas demora, por isso fica em idle, se tu tiver 2-3 contas acho q fica suave

**Comment by far0fa** [comment]
aqui tambem nao foi, deu idle nas duas!

**Comment by mvpalves** [comment]
Eu to rodando minhas 5 contas em VMs diferentes.

Só que aí tb vc come o processamento do seu PC kkkk

![image](https://user-images.githubusercontent.com/94149149/145696862-949c4b2f-b5e8-47c9-8779-292d40b99b92.png)

**Comment by far0fa** [comment]
Como vocÊ fez as vms? Com vmware workstation pro? Eu tentei mas nao foi aqui, nao ta instalando o windows

**Comment by marcelosore** [comment]
eu uso hyper-v aqui

**Comment by far0fa** [comment]
Pode me adicioanr discord e me ajudar?

**Comment by rodrigobragamg** [comment]
https://github.com/mpcabete/bombcrypto-bot

**Comment by gillyanbfoz** [comment]
> eu uso hyper-v aqui

qual a diferenca desse pro da oracle vm virtual box ? esse é mais leve sera ?

**Comment by siuburu** [comment]
> Eu to rodando minhas 5 contas em VMs diferentes.
> 
> Só que aí tb vc come o processamento do seu PC kkkk
> 
> ![image](https://user-images.githubusercontent.com/94149149/145696862-949c4b2f-b5e8-47c9-8779-292d40b99b92.png)

Tudo windows?

**Comment by mvpalves** [comment]
> > Eu to rodando minhas 5 contas em VMs diferentes.
> > Só que aí tb vc come o processamento do seu PC kkkk
> > ![image](https://user-images.githubusercontent.com/94149149/145696862-949c4b2f-b5e8-47c9-8779-292d40b99b92.png)
> 
> Tudo windows?

Sim, to rodando todas com Windows 10.

Tem rodado bem no Hyper V e fácil de controlar tb 


![image](https://user-images.githubusercontent.com/94149149/145727330-c5392dcb-fefd-468f-9591-f83a98aac697.png)

**Comment by far0fa** [comment]
Mano eu tenho um i9 10900k e usa muito o prcessador qnd abre o bombcrypto, n sei pq

**Comment by far0fa** [comment]
No Hyper V
