### ISSUE TITLE
Erro ao executar o "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by davidkoll1** [mpcabete/bombcrypto-bot#233]
Boa tarde,

Quando eu vou executar o pip install -r requirements.txt da o seguinte erro.

" ERROR: Could not find a version that satisfies the requirement torch==1.10.0 (from versions: none)
ERROR: No matching distribution found for torch==1.10.0 "

Atualmente meu python é o 3.10.1.

Poderia ajudar?

**Comment by Tavinlol** [comment]
https://github.com/mpcabete/bombcrypto-bot/issues/229

**Comment by coradini1** [comment]
Lê a porra dos outros issues

**Comment by davidkoll1** [comment]
kkkkkkkk   @coradini cavalo! 

ASDIUHASDIUSH
