### ISSUE TITLE
ERROR - No module named 'yaml'

### ISSUE THREAD

**Issue by kalleldf** [mpcabete/bombcrypto-bot#234]
alguém pode ajudar?

ModuleNotFoundError: No module named 'yaml'

**Comment by Tavinlol** [comment]
Tente
pip install pyyaml

**Comment by joaoaspimienta** [comment]
> Tente pip install pyyaml
> 
> https://stackoverflow.com/questions/50868322/importerror-no-module-named-yaml/50868994

Fiz isso mas continua dando a mesma coisa

**Comment by Nucito** [comment]
> > Tente pip install pyyaml
> > https://stackoverflow.com/questions/50868322/importerror-no-module-named-yaml/50868994
> 
> Fiz isso mas continua dando a mesma coisa

Você enviando o print do erro fica mais simples...
