### ISSUE TITLE
Problema torch 1.10

### ISSUE THREAD

**Issue by fx2016** [mpcabete/bombcrypto-bot#235]
Estou com esse problema, alguém pode me ajudar, estou pagando para quem me ajudar a resolver

ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.10.0

me liga 53981265918

**Comment by Tavinlol** [comment]
https://github.com/mpcabete/bombcrypto-bot/issues/229
