### ISSUE TITLE
Erro ao atualizar requeriments.txt

### ISSUE THREAD

**Issue by Jordesom** [mpcabete/bombcrypto-bot#237]
Estou tendo problemas com o seguinte erro

Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.10.0

C:\bomb2>python index.py
Traceback (most recent call last):
  File "C:\bomb2\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\bomb2\captcha\solveCaptcha.py", line 8, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

C:\bomb2>

**Comment by fguide** [comment]
Veja: #229
