### ISSUE TITLE
Error Requirements

### ISSUE THREAD

**Issue by PorfirioLeonardo** [mpcabete/bombcrypto-bot#238]
![errobomb](https://user-images.githubusercontent.com/95990301/145697905-a53a93c9-9ec2-42ed-8f1e-1495f9410b0a.png)
Esse erro aparece após tentar instalar os requirements, estou com python 3.9.6

**Comment by Galinho90** [comment]
O meu apresentou o seguinte erro, no final da instalação: 
.
.
.

ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.10.0
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\leand\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by MochilaEstilosa** [comment]
já tentou `pip install PyMsgBox`

**Comment by Mikebriza** [comment]
> já tentou `pip install PyMsgBox`

estou com o msm erro do Galinho90, tentei esse comando, ele mostra "Requirement already satisfied"

**Comment by Mikebriza** [comment]
> ![errobomb](https://user-images.githubusercontent.com/95990301/145697905-a53a93c9-9ec2-42ed-8f1e-1495f9410b0a.png) Esse erro aparece após tentar instalar os requirements, estou com python 3.9.6

O meu tbm ta dando esses 2 últimos erros, tentei instalar o pytorch manualmente mas n consegui tbm
