### ISSUE TITLE
ERROR REQUIREMENTS  - torch

### ISSUE THREAD

**Issue by Galinho90** [mpcabete/bombcrypto-bot#239]
ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.10.0
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\leand\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by MochilaEstilosa** [comment]
a resposta está no #229

**Comment by Galinho90** [comment]
Consegui, desinstalei o Python e coloquei a versão 3.9.9. 
Obrigado
