### ISSUE TITLE
Ajuda configuração multi account/telas

### ISSUE THREAD

**Issue by beped** [mpcabete/bombcrypto-bot#24]
Opa, 
Tenho 2 monitores no PC. quando Ponho o script para rodar, ele faz movimentos errados na tela, não fazendo o que deveria. Ele não deveria funcionar em multi-monitor?
E sobre multi account. Possuo 2 contas, existe alguma forma de deixar no mesmo pc as 2 rodando?

**Comment by MarsuraPedro** [comment]
Nao, atualmente ele nao funciona para 2 monitores, ele esta se perdendo

Sobre multiconta, ele usa teu mouse, entao nao, nao da

Modo de fazer com multiconta  cria uma Vm basicona (mais fracas sao linux, mais chatinhas de configurar mas rodam)  e coloca 1 em cada Vm, mas eh necessario um pc bom
