### ISSUE TITLE
IDLE muito curto in game (edit)

### ISSUE THREAD

**Issue by amatoxd** [mpcabete/bombcrypto-bot#241]
Gente, olá. Boa noite! Tem alguma função que eu possa adicionar ao código para que o bot entre com mais frequência nos heróis, coisa de a cada 30 ~~ 50 segundos, mesmo sem herói pra colocar pra trabalhar, ou se alguém já fez um fork assim? Ñ me importo de perder eventuais bombas pq o bot foi pros heróis. Pq toda hora o jogo entra em idle, dando aquele errinho desconhecido lá, e me desconecta e o bot demora a logar de novo, até chegar no procedimento de reconectar a wallet e etc. Agradeço! O meu game entra em idle em no máximo 1 minuto após todos os bheros estarem descansando. É horrível ficar relogando a todo momento.

**Comment by amatoxd** [comment]
e.g., o que vem acontecendo muito é o bot logar no jogo, ir para o mapa, todos estarem descansando e aparecer o idle e o bot nunca ter tempo de colocar nenhum pra trabalhar. Aí fica nesse loop infinito.

**Comment by amatoxd** [comment]
> 

PQ quando loga, ele não vai imediatamente selecionar os heros, caso ele fizesse isso, uma hora teria heróis com estamina e eles iriam para o mapa, mas sem isso, só fica nesse ciclo de idle e o bot nunca funciona, só se eu colocar manualmente no começo, até q uma hora eles descansam novamente ao msm tempo e fecha de novo

**Comment by trinitro2** [comment]
edita o config.yaml

**Comment by newerton** [comment]
> e.g., o que vem acontecendo muito é o bot logar no jogo, ir para o mapa, todos estarem descansando e aparecer o idle e o bot nunca ter tempo de colocar nenhum pra trabalhar. Aí fica nesse loop infinito.

É só você abrir o arquivo config e lê o refresh_heroes_positions

**Comment by amatoxd** [comment]
> > e.g., o que vem acontecendo muito é o bot logar no jogo, ir para o mapa, todos estarem descansando e aparecer o idle e o bot nunca ter tempo de colocar nenhum pra trabalhar. Aí fica nesse loop infinito.
> 
> É só você abrir o arquivo config e lê o refresh_heroes_positions

Obrigado!! Fiz isso, setei para 50 segundos (0.5), porém acordei agora e curiosamente o bot tá parado no mapa e não mandou ninguém pra trabalhar, estão todos full estamina. Será que eu fiz alguma coisa errada? @trinitro2
