### ISSUE TITLE
(Sugestão) Rolar menos vezes pra selecionar heróis 

### ISSUE THREAD

**Issue by Gguga** [mpcabete/bombcrypto-bot#244]
Quando vai selecionar os heróis ele rola 3x após já ter finalizado a lista, só uma sugestão pra deixar ele mais rápido

**Comment by newerton** [comment]
@Gguga Ele faz isso por causa dos lags que acontece, quando bot seleciona os últimos herois.

**Comment by PacLucas** [comment]
No arquivo _config.yaml_ a variável `scroll_attemps` é para definir isso, tu pode definir lá as tentativas
