### ISSUE TITLE
ERROR: No matching distribution found for torch>=1.10.0

### ISSUE THREAD

**Issue by joaovitorbogo** [mpcabete/bombcrypto-bot#247]
Não sei o motivo, mas o torch não está instalando, já pesquisei algumas respostas pra isso, mas nada resolveu

**Comment by igorsantana76** [comment]
Tbm não consigo no meu note com AMD Ryzen 7 5700u

**Comment by trinitro2** [comment]
pip install torch

**Comment by mauriciobsilva** [comment]
Tenta esse, comigo funcionou.

pip3 install torch==1.10.0+cpu torchvision==0.11.1+cpu torchaudio==0.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html

**Comment by wandersonlt** [comment]
esse erro continua acontecendo comigo 
mesmo testando os codigos acima 
ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.10.0
