### ISSUE TITLE
Erro no Slider

### ISSUE THREAD

**Issue by fx2016** [mpcabete/bombcrypto-bot#248]
Bom dia @mpcabete, o bot funcionou desde às 21 hs de ontem perfeitamente, entretanto agora as 6:20 da manhã ele resolveu o captcha mas não soltou o slider, aí ele se desconectou sozinho no prompt de comando, como se eu tivesse dado ctrl+c.

Ocorre que ele fez isso em dois notebook's, acredito que seja algum erro a verificar.

Meu agradecimento, seu trabalho é espetacular, muito obrigado

**Comment by cmxavier** [comment]
Bom dia, o mesmo aconteceu comigo também em 2 notebooks diferentes.

Enquanto estive acompanhando o bot está excelente, só não consegui entender o que aconteceu mesmo nessa situação que foi de madrugada.

**Comment by fx2016** [comment]
> Bom dia, o mesmo aconteceu comigo também em 2 notebooks diferentes.
> 
> Enquanto estive acompanhando o bot está excelente, só não consegui entender o que aconteceu mesmo nessa situação que foi de madrugada.

Pois é, importante aparecerem mais pessoas, porque de madrugada ele fez outra vez também, obrigado @cmxavier

**Comment by cmxavier** [comment]
Aconteceu agora ![image](https://user-images.githubusercontent.com/24523474/145709169-8530fc32-31c6-446a-926b-7165d9992fa7.jpeg)

**Comment by cmxavier** [comment]
Esse bot dessa máquina é o bot para multi accounts, no outro notebook eu uso somente uma conta e também aconteceu o mesmo problema

**Comment by fx2016** [comment]
> Aconteceu agora ![image](https://user-images.githubusercontent.com/24523474/145709169-8530fc32-31c6-446a-926b-7165d9992fa7.jpeg)

Exatamente esse erro, ele sai sozinho após “no slider”

**Comment by voodee** [comment]
I also get this error. As I understand the bot can not find the slider image.

I tried two things:
1. Edit "targets/slider.png" image and trim unnecessary fields.
2. Decrease the error of image recognition in "captcha/main.py" and "captcha/solveCaptcha.py" files. From 0.85 to 0.45.

But it didn't help. Any ideas?

Maybe the slider image changes its color on hovering and it interferes with the recognition?

**Comment by rodrigotrodrigues** [comment]
Opa, mesmo problema aqui, mas percebi uma coisa agora... ele executa o slider com sucesso, mas não consegue enxergar o captcha quando começa com 0, as tres vezes que aconteceu comigo, iniciavam com 0...

**Comment by matheusanat** [comment]
Também aconteceu comigo no início da magrugada, o farm nã foi muito efetivo kkkk...

@mpcabete  Minha sugestão, e ressalvo meu pouco conhecimento perante a dificuldade de o fazer, seria no momento em que não acharia esse slider, forçar um CTRL+F5 na página, como há em outros momentos do código...dessa forma ele testaria um novo captcha, e não encerraria o código, que é o principal

**Comment by MathMassa** [comment]
![image](https://user-images.githubusercontent.com/96006470/145711487-8688c0c7-a655-42b5-8d5b-90dba6db2979.png)
Após isso para o bot

**Comment by rodrigotrodrigues** [comment]
> ![image](https://user-images.githubusercontent.com/96006470/145711487-8688c0c7-a655-42b5-8d5b-90dba6db2979.png) Após isso para o bot

Mesmo problema aqui que relatei acima, quando o captcha inicia com o 0

**Comment by HyperionSage** [comment]
Comigo aconteceu tb! Desativar o bot que é foda, se por um looping para tentar novamente é até melhor!

**Comment by fguide** [comment]
O solveCaptcha.py está saindo quando não encontra o slider, uma sugestão é alterar o exit por return e fazer a chamada do solveCaptcha novamente.

É um paliativo que eu creio que funcione mas não testei porque eu estou utilizando só o solveCaptcha em demanda, não fica rodando o tempo todo.

**Comment by reenkang** [comment]
I have updated solveCaptcha.py with below codes (in **bold**). If background number is having 0 at the front, it will add 0 to the front.

print( 'dig: {}, background_digits: {}'.format(digits, background_digits))
**number_digits_str = str(digits)
number_background_digits_str = str(background_digits)
zero_filled_number_background_digits_str = number_background_digits_str.zfill(3)
if number_digits_str == zero_filled_number_background_digits_str:**
        print('FOUND!')
        pyautogui.mouseUp()
        return

![image](https://user-images.githubusercontent.com/95399876/145715859-ad325c83-fe49-499f-8c3b-1bbbe930b8c1.png)

**Comment by rodrigotrodrigues** [comment]
Tks reenkang, but after to change the solvecaptcha.py i see this:
C:\Bomb>python index.py
Traceback (most recent call last):
  File "C:\Bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\Bomb\captcha\solveCaptcha.py", line 187
    number_background_digits_str = str(background_digits)
TabError: inconsistent use of tabs and spaces in indentation

Can you help us?

**Comment by HyperionSage** [comment]
usem a resolução 1366x768 ficou Perfeito!

**Comment by cmxavier** [comment]
> I have updated solveCaptcha.py with below codes (in **bold**). If background number is having 0 at the front, it will add 0 to the front.
> 
> print( 'dig: {}, background_digits: {}'.format(digits, background_digits)) **number_digits_str = str(digits) number_background_digits_str = str(background_digits) zero_filled_number_background_digits_str = number_background_digits_str.zfill(3) if number_digits_str == zero_filled_number_background_digits_str:** print('FOUND!') pyautogui.mouseUp() return
> 
> ![image](https://user-images.githubusercontent.com/95399876/145715859-ad325c83-fe49-499f-8c3b-1bbbe930b8c1.png)

I did the change, but still having error to identify the captcha

**Comment by kerferber** [comment]
Aconteceu aqui comigo também @mpcabete .

Ocorreu quando o bot não conseguiu identificar um dos números, mas não percebi se iniciava com Zero.

Acredito que seja simples de resolver, apenas tratar esta situação com um refresh e nova tentativa, como bem apontou @matheusanat

**Comment by gillyanbfoz** [comment]
> I have updated solveCaptcha.py with below codes (in **bold**). If background number is having 0 at the front, it will add 0 to the front.
> 
> print( 'dig: {}, background_digits: {}'.format(digits, background_digits)) **number_digits_str = str(digits) number_background_digits_str = str(background_digits) zero_filled_number_background_digits_str = number_background_digits_str.zfill(3) if number_digits_str == zero_filled_number_background_digits_str:** print('FOUND!') pyautogui.mouseUp() return
> 
> ![image](https://user-images.githubusercontent.com/95399876/145715859-ad325c83-fe49-499f-8c3b-1bbbe930b8c1.png)

thanks, i will test as soon as the server returns to normal

**Comment by joaovitorbogo** [comment]
eu "resolvi" da seguinte forma

procurei linha abaixo dentro do arquivo solveCaptcha.py dentro da pasta capcha

print( 'dig: {}, background_digits: {}'.format(digits, background_digits))

e em baixo dela eu fiz uma pequena alteração

        if digits == background_digits:
            print('FOUND!')
            pyautogui.mouseUp()
            return
        if digits !=  background_digits:
            print('NOT FOUND!')
            pyautogui.mouseUp()
            return 

Eu poderia só tirar o if mas quis adicionar um if a mais só pra ver no cmd quando der o erro

**Comment by gillyanbfoz** [comment]
> 



> eu "resolvi" da seguinte forma
> 
> procurei linha abaixo dentro do arquivo solveCaptcha.py dentro da pasta capcha
> 
> print( 'dig: {}, background_digits: {}'.format(digits, background_digits))
> 
> e em baixo dela eu fiz uma pequena alteração
> 
> ```
>     if digits == background_digits:
>         print('FOUND!')
>         pyautogui.mouseUp()
>         return
>     if digits !=  background_digits:
>         print('NOT FOUND!')
>         pyautogui.mouseUp()
>         return 
> ```
> 
> Eu poderia só tirar o if mas quis adicionar um if a mais só pra ver no cmd quando der o erro

fazendo isso quando ele nao consegue fazer o catpcha ele tenta novamente ?

**Comment by FDNiisan** [comment]
> eu "resolvi" da seguinte forma
> 
> procurei linha abaixo dentro do arquivo solveCaptcha.py dentro da pasta capcha
> 
> print( 'dig: {}, background_digits: {}'.format(digits, background_digits))
> 
> e em baixo dela eu fiz uma pequena alteração
> 
> ```
>     if digits == background_digits:
>         print('FOUND!')
>         pyautogui.mouseUp()
>         return
>     if digits !=  background_digits:
>         print('NOT FOUND!')
>         pyautogui.mouseUp()
>         return 
> ```
> 
> Eu poderia só tirar o if mas quis adicionar um if a mais só pra ver no cmd quando der o erro

Eu testei aqui. resolve o problema de sair. Mas aqui ele não resolve o Captcha. acaba que ele solta o slider na primeira posição e tenta de novo.

**Comment by joaovitorbogo** [comment]
> fazendo isso quando ele nao consegue fazer o catpcha ele tenta novamente ?

sim


> Eu testei aqui. resolve o problema de sair. Mas aqui ele não resolve o Captcha. acaba que ele solta o slider na primeira posição e tenta de novo.

É justamente pra isso, não é uma "solução" que vai fazer com que resovla o capcha, só com que tente novamente, aconteceu até de errar 3x o capcha seguido mas aí ele tentou fazer o login novamente e deu certo

**Comment by gillyanbfoz** [comment]
> > fazendo isso quando ele nao consegue fazer o catpcha ele tenta novamente ?
> 
> sim
> 
> > Eu testei aqui. resolve o problema de sair. Mas aqui ele não resolve o Captcha. acaba que ele solta o slider na primeira posição e tenta de novo.
> 
> É justamente pra isso, não é uma "solução" que vai fazer com que resovla o capcha, só com que tente novamente, aconteceu até de errar 3x o capcha seguido mas aí ele tentou fazer o login novamente e deu certo

Vou testar aqui, importante agora é deixar ele automatizado de alguma forma, até que os problemas sejam corrijidos de definito, obrigado pela ajuda.

**Comment by Alt4s** [comment]
Mesmo problema aqui, vou tentar o que disseram acima

**Comment by Alt4s** [comment]
> TabError: inconsistent use of tabs and spaces in indentation

fiz isto mas aparece erro pra mim agora
TabError: inconsistent use of tabs and spaces in indentation

**Comment by Coolhatcker** [comment]
In file **solveCaptcha.py** 

```
def solveCaptcha():
      i = 0
         .....
```

```
 if digits == background_digits:
        print('FOUND!')
        pyautogui.mouseUp()
        return
else:
        i = i+1
        if ==5:
            time.sleep(2)
            pyatogui.mouseUp()
```

**Comment by Coolhatcker** [comment]
> > TabError: inconsistent use of tabs and spaces in indentation
> 
> fiz isto mas aparece erro pra mim agora TabError: inconsistent use of tabs and spaces in indentation
> 
> *Alguém pode explicar como adicionar comando que não dê este erro?

Show screenshot solveCaptcha.py where did you add code
```
    if digits == background_digits:
        print('FOUND!')
        pyautogui.mouseUp()
        return
    if digits !=  background_digits:
        print('NOT FOUND!')
        pyautogui.mouseUp()
        return 
```

**Comment by Alt4s** [comment]
![image](https://user-images.githubusercontent.com/95438518/145725700-8c8d749e-2fbf-43ea-971b-935ea446f312.png)

**Comment by Alt4s** [comment]
> > > TabError: inconsistent use of tabs and spaces in indentation
> > 
> > 
> > fiz isto mas aparece erro pra mim agora TabError: inconsistent use of tabs and spaces in indentation
> > *Alguém pode explicar como adicionar comando que não dê este erro?
> 
> Show screenshot solveCaptcha.py where did you add code
> 
> ```
>     if digits == background_digits:
>         print('FOUND!')
>         pyautogui.mouseUp()
>         return
>     if digits !=  background_digits:
>         print('NOT FOUND!')
>         pyautogui.mouseUp()
>         return 
> ```

![image](https://user-images.githubusercontent.com/95438518/145725706-0c07111c-d0d0-4477-9695-eb890179fbd9.png)

**Comment by Coolhatcker** [comment]
> > > > TabError: inconsistent use of tabs and spaces in indentation
> > > 
> > > 
> > > fiz isto mas aparece erro pra mim agora TabError: inconsistent use of tabs and spaces in indentation
> > > *Alguém pode explicar como adicionar comando que não dê este erro?
> > 
> > 
> > Show screenshot solveCaptcha.py where did you add code
> > ```
> >     if digits == background_digits:
> >         print('FOUND!')
> >         pyautogui.mouseUp()
> >         return
> >     if digits !=  background_digits:
> >         print('NOT FOUND!')
> >         pyautogui.mouseUp()
> >         return 
> > ```
> 
> ![image](https://user-images.githubusercontent.com/95438518/145725706-0c07111c-d0d0-4477-9695-eb890179fbd9.png)

Open please in Python IDLE or Notepad++

**Comment by Alt4s** [comment]
> if digits !=  background_digits:
>         print('NOT FOUND!')
>         pyautogui.mouseUp()
>         return

Oh, good! Thank u !!!

**Comment by Alt4s** [comment]
> Oh, good! Thank u !!!



> > > > > TabError: inconsistent use of tabs and spaces in indentation
> > > > 
> > > > 
> > > > fiz isto mas aparece erro pra mim agora TabError: inconsistent use of tabs and spaces in indentation
> > > > *Alguém pode explicar como adicionar comando que não dê este erro?
> > > 
> > > 
> > > Show screenshot solveCaptcha.py where did you add code
> > > ```
> > >     if digits == background_digits:
> > >         print('FOUND!')
> > >         pyautogui.mouseUp()
> > >         return
> > >     if digits !=  background_digits:
> > >         print('NOT FOUND!')
> > >         pyautogui.mouseUp()
> > >         return 
> > > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/95438518/145725706-0c07111c-d0d0-4477-9695-eb890179fbd9.png)
> 
> Open please in Python IDLE or Notepad++

Oh, good! Thank u !!!

**Comment by Alt4s** [comment]
Continua dando o mesmo erro, não faz o captcha e tipo fica parado

**Comment by Alt4s** [comment]
> I have updated solveCaptcha.py with below codes (in **bold**). If background number is having 0 at the front, it will add 0 to the front.
> 
> print( 'dig: {}, background_digits: {}'.format(digits, background_digits)) **number_digits_str = str(digits) number_background_digits_str = str(background_digits) zero_filled_number_background_digits_str = number_background_digits_str.zfill(3) if number_digits_str == zero_filled_number_background_digits_str:** print('FOUND!') pyautogui.mouseUp() return
> 
> ![image](https://user-images.githubusercontent.com/95399876/145715859-ad325c83-fe49-499f-8c3b-1bbbe930b8c1.png)

testing, I go back to say if it worked

**Comment by jhonsstn** [comment]
É só adicionar bem aqui. Se ele errar, quando passar pelo proximo solveCaptcha do while ele vai tentar novamente e nao fechar o bot.

![image](https://user-images.githubusercontent.com/33515228/145729566-2e127f8d-f781-4c52-bbce-c3dd71e5793f.png)

**Comment by mpcabete** [comment]
amigos, fiz uma pequena atualizaçao, tenta atualizar o bot e vê se melhora

**Comment by FDNiisan** [comment]
> 

Testei aqui. Agora ele tenta de novo, mas só está soltando no primeiro número.
Vamos ver se acontece com mais alguém ou se é só comigo

**Comment by MathMassa** [comment]
> As an option. In file **solveCaptcha.py**
> 
> ```
> def solveCaptcha():
>          i = 0
>          .....
> ```
> 
> ```
> if digits == background_digits:
>         print('FOUND!')
>         pyautogui.mouseUp()
>         return
> else:
>         i = i+1
>         if i == 5:
>             time.sleep(2)
>             pyautogui.mouseUp()
> ```

Galera, essa parada aqui funciona. Pq ele deixa a função fazer as 5 tentativas antes de soltar. Só precisa a variável i iniciar com 0

**Comment by Alt4s** [comment]
> > I have updated solveCaptcha.py with below codes (in **bold**). If background number is having 0 at the front, it will add 0 to the front.
> > print( 'dig: {}, background_digits: {}'.format(digits, background_digits)) **number_digits_str = str(digits) number_background_digits_str = str(background_digits) zero_filled_number_background_digits_str = number_background_digits_str.zfill(3) if number_digits_str == zero_filled_number_background_digits_str:** print('FOUND!') pyautogui.mouseUp() return
> > ![image](https://user-images.githubusercontent.com/95399876/145715859-ad325c83-fe49-499f-8c3b-1bbbe930b8c1.png)
> 
> testing, I go back to say if it worked

its perfect!!!

Está funcionando perfeitamente agora

**Comment by matheusanat** [comment]
> mpc

Baixei novamente os arquivos e testei por duas vezes com captcha inicado em "0xx", e não houve problema...

Vou rodar durante a madrugada e amanhã informo sobre.

Obrigado.

**Comment by matheusanat** [comment]
> amigos, fiz uma pequena atualizaçao, tenta atualizar o bot e vê se melhora

Baixei novamente os arquivos e rodei o bot com dois captcha iniciados em "0xx" e funcionou sem problemas...

Deixarei rodando a madrugada toda e amanhã informo como foi.

Obrigado.

**Comment by evandroid** [comment]
> amigos, fiz uma pequena atualizaçao, tenta atualizar o bot e vê se melhora

@mpcabete , so o index.py e um arquivo lá da pasta captcha, né? Só sobrescrever estes dois só. Estou certo?
