### ISSUE TITLE
Bot versão Thiago-Molive

### ISSUE THREAD

**Issue by PinnDeath6** [mpcabete/bombcrypto-bot#249]
Cara sua fork ta boa, se tirar esses trens do telegram, complementar a função do pyclick pra ele sempre clicar em sign (quase sempre buga) e o novo captcha fica sensacional!

**Comment by ltv2** [comment]
> Cara sua fork ta boa, se tirar esses trens do telegram, complementar a função do pyclick pra ele sempre clicar em sign (quase sempre buga) e o novo captcha fica sensacional!

Telegram?
Essa parada do sign sempre buga mesmo.

**Comment by fguide** [comment]
> Cara sua fork ta boa, se tirar esses trens do telegram, complementar a função do pyclick pra ele sempre clicar em sign (quase sempre buga) e o novo captcha fica sensacional!

Dica, faça o comentário lá no fork dele, fica mais fácil pra ele ver e ainda não confunde os projetos.

https://github.com/thiago-molive/bombcrypto-bot
