### ISSUE TITLE
issue with logging in

### ISSUE THREAD

**Issue by gabrielzev1** [mpcabete/bombcrypto-bot#25]
Hi im having issues with the loggin in it dosent automatically signs in how can i fix this ?

**Comment by mpcabete** [comment]
Where is the problem happening? it is when clicking the sign button?

**Comment by gabrielzev1** [comment]
yep when connecting wallet

**Comment by Kikio1** [comment]
> Where is the problem happening? it is when clicking the sign button?

Same here, after he clicks Connect to the wallet, he never clicks select wallet- metamask
