### ISSUE TITLE
Não faz o captcha

### ISSUE THREAD

**Issue by hdjeronimo** [mpcabete/bombcrypto-bot#250]
Parabéns pelo excelente bot! nesta ultima atualização o meu bot não assume quando o captcha aparece. Fica em loop no "checking for captcha" 
Continuação de ótimo trabalho, grande abraço!

**Comment by hdjeronimo** [comment]
tentei remover e instalar o bot de novo e agora nem sequer estou a conseguir entrar nele, aparece isso no cmd:

![bug](https://user-images.githubusercontent.com/75709148/145710149-10cbd44f-03de-427a-a42b-c869d43b1925.png)

**Comment by nasiloski** [comment]
> tentei remover e instalar o bot de novo e agora nem sequer estou a conseguir entrar nele, aparece isso no cmd:
> 
> ![bug](https://user-images.githubusercontent.com/75709148/145710149-10cbd44f-03de-427a-a42b-c869d43b1925.png)

Man, desinstala o python 3.10 e instala o 3.9 (o 3.10 não suporta o torch ainda). Depois instala o MS Visual C++ pra bulidar algumas dependências do projeto que vai funcionar

**Comment by alexandernicacio** [comment]
estou tendo o mesmo problema mais nao tenho noção de como desinstalar o pithon

**Comment by alexandernicacio** [comment]
> estou tendo o mesmo problema mais não tenho noção de como desinstalar o python

pronto consegui desinstalar o python porém não estou conseguindo achar a versão 9 pra baixar alguem tem o link de onde baixar ai por favor

**Comment by trinitro2** [comment]
da um youtube tb poxa

**Comment by MochilaEstilosa** [comment]
> > estou tendo o mesmo problema mais não tenho noção de como desinstalar o python
> 
> pronto consegui desinstalar o python porém não estou conseguindo achar a versão 9 pra baixar alguem tem o link de onde baixar ai por favor

Amigo, só dar um Google 
https://www.python.org/downloads/release/python-399/

**Comment by MathMassa** [comment]
> > estou tendo o mesmo problema mais não tenho noção de como desinstalar o python
> 
> pronto consegui desinstalar o python porém não estou conseguindo achar a versão 9 pra baixar alguem tem o link de onde baixar ai por favor

https://www.python.org/downloads/release/python-399/

**Comment by Jordesom** [comment]
Resolvi com a versão 3.9.8

**Comment by hdjeronimo** [comment]
já consegui! muito obrigado! tudo a funcionar sem problemas :D
