### ISSUE TITLE
Bot does not click on Metamask "Sign in", and too many login attempts. 

### ISSUE THREAD

**Issue by BBencee** [mpcabete/bombcrypto-bot#251]
Is it common or just me, because when the BOT completes the captcha, it does not click on the sign in button just goes to next process. I've tried replacing the image with my own, but this issue was the same with the previous versions also.

**Comment by BBencee** [comment]
Also when the game is played and nothing is wrong it says Too many login attempts, and refreshes the game for no reason.

**Comment by BBencee** [comment]
I've solved the Sign in issue by adding the tim.sleep to this section: 

```
    if clickBtn(images['connect-wallet'], name='connectWalletBtn', timeout = 10):
        solveCaptcha()
        login_attempts = login_attempts + 1
        logger('🎉 Connect wallet button detected, logging in!')
        #TODO mto ele da erro e poco o botao n abre
        time.sleep(10)
```

**Comment by Fammerilia** [comment]
i tried this solution, but it is goes to next process and dont click on sign :(
