### ISSUE TITLE
Dando erro ao instalar

### ISSUE THREAD

**Issue by alexandernicacio** [mpcabete/bombcrypto-bot#253]
bom dia, Primeiramente gostaria de parabenizar a toda equipe, pelo empenho em trazer de volta esse magnifico bot. Só não consigo fazer donate pois, tenho apenas um hero e o mesmo veio comum 2,1,1,1,1 estou lutando pra ver se aparece alguma jaula que eu consiga obter pelo menos mais um hero pra ajudar a fazer as telas mais rápido, e não tenho com investir mais no jogo por motivos financeiros, mais quando eu puder, com certeza o farei, pra incentivar mais a equipe a continuar com esse belissimo trabalho.

Baixei o bot e estou tentando instalar, mais ele da a seguinte mensagem após o comando no final da instalação:

ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.10.0

daí quando vou executar o bot ele me da a seguinte msg:

C:\bomb>python index.py
Traceback (most recent call last):
  File "C:\bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\bomb\captcha\solveCaptcha.py", line 8, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

alguém consegue me ajudar a como resolver isso lembrando que não tenho noção nenhuma de programação

**Comment by viniciusfontao** [comment]
tem uma issue pinned sobre isso

**Comment by fguide** [comment]
Veja: #229

**Comment by Jordesom** [comment]
Revolvi esse problema, instalando a versão phyton 3.9.8
