### ISSUE TITLE
Informações Tela

### ISSUE THREAD

**Issue by Bugad0** [mpcabete/bombcrypto-bot#254]
Gostaria que você compartilha-se conosco qual a resolução da tela do computador que você utilizo para salvar as imagens e qual tamanho da escala 100% ou 125%, facilitaria para que nos conseguimos deixar o bot funcionando nos mesmo parametros. agradeço pela ajuda.

**Comment by fguide** [comment]
Creio que as specs iniciais não mudaram:

Resoluçao: 1920x1080 (FHD)
Escala: 100%
Zoom navegador: 100%
