### ISSUE TITLE
Limitar quantidade de heroes para enviar ao Work

### ISSUE THREAD

**Issue by espinozachristian** [mpcabete/bombcrypto-bot#255]
Galera, estou pensando em uma logica para enviar uma quantidade X de herois apenas quando sobrar poucos baus, para tentar otimizar a Run assim, alguem começou algo que gostaria de compartilhar?

**Comment by DARKSONx** [comment]
mas o bot ja envia poucos herois pra tela tendo em vista que so manda os que estão com stamina verde, dessa forma, nunca vai enviar todos de uma vez, a nao ser que seja a primeira vez no dia que voce ta entrando e todos os bonecos estao full stamina
