### ISSUE TITLE
processing last action and can't click to connect on metamask

### ISSUE THREAD

**Issue by Fammerilia** [mpcabete/bombcrypto-bot#256]
processing  last action and can't click to connect on metamask

**Comment by Kikio1** [comment]
Same here

**Comment by evandroid** [comment]
same here, it keeps clicking on "connect wallet" in loop, but when metamask windows pops up, it closes it and clicks on "connect wallet" in a loop. Edge or Firefox, 1920x1080, 100% zoom, python 3.9.9, all requirements satisfied, no error message in log.

**Comment by Coolhatcker** [comment]
1. Make screenshot icon metamask in taskbar
2. Place the icon in folder "targets" with name meta-icon.png
3. Open index.py and write this code:
![image](https://user-images.githubusercontent.com/95485725/145727975-671c677f-8eb0-485a-992a-19abf2aefb82.png)

**Comment by evandroid** [comment]
> 1. Make screenshot icon metamask in taskbar
> 
>     2. Place the icon in folder "targets" with name meta-icon.png
> 
>     3. Open index.py and write this code:
>        ![Снимок](https://user-images.githubusercontent.com/95485725/145728008-57871a82-d346-408e-93a9-a32154e4602c.JPG)

Hi! Thank you for trying to help me.

I inserted the code and did what you told. No luck: the code you above is never invoked since on line 358, that if returns true (as if the bot clicked the "sign" button). I dont know yet why it thinks it clicked the sign button while its not; but with the false positive, the login() function returns and the bot begins the loop.

By the way, here is the code typed (one must pay attention to identation) -- insertion below line 389 of actual index.py :

# ------------------>
# BEGIN: Code inserted to fix MetaMask sign-in
# ------------------>

    if not clickBtn(images['select-wallet-2'], name='signBtn'):
        logger('TRYING NEW CODE...')
        if clickBtn(images['meta-icon'], name='metaiconBtn'):
            if clickBtn(images['select-wallet-2'], name='signBtn', timeout = 20):
                login_attempts = login_attempts + 1
                if clickBtn(images['treasure-hunt-icon'], name='treasureHunt', timeout=30):
                    login_attempts = 0
                
# ------------------>
# END: Code inserted to fix MetaMask sign-in
# ------------------>

**Comment by Coolhatcker** [comment]
> > 1. Make screenshot icon metamask in taskbar
> 
> > 
> 
> >     2. Place the icon in folder "targets" with name meta-icon.png
> 
> > 
> 
> >     3. Open index.py and write this code:
> 
> >        ![Снимок](https://user-images.githubusercontent.com/95485725/145728008-57871a82-d346-408e-93a9-a32154e4602c.JPG)
> 
> 
> 
> Hi! Thank you for trying to help me.
> 
> 
> 
> I inserted the code and did what you told. No luck: the code you above is never invoked since on line 358, that if returns true (as if the bot clicked the "sign" button). I dont know yet why it thinks it clicked the sign button while its not; but with the false positive, the login() function returns and the bot begins the loop.
> 
> 
> 
> By the way, here is the code typed (one must pay attention to identation) -- insertion below line 389 of actual index.py :
> 
> 
> 
> # ------------------>
> 
> # BEGIN: Code inserted to fix MetaMask sign-in
> 
> # ------------------>
> 
> 
> 
>     if not clickBtn(images['select-wallet-2'], name='signBtn'):
> 
>         logger('TRYING NEW CODE...')
> 
>         if clickBtn(images['meta-icon'], name='metaiconBtn'):
> 
>             if clickBtn(images['select-wallet-2'], name='signBtn', timeout = 20):
> 
>                 login_attempts = login_attempts + 1
> 
>                 if clickBtn(images['treasure-hunt-icon'], name='treasureHunt', timeout=30):
> 
>                     login_attempts = 0
> 
>                 
> 
> # ------------------>
> 
> # END: Code inserted to fix MetaMask sign-in
> 
> # ------------------>

Please show your icon

**Comment by Kikio1** [comment]
> > > 1. Make screenshot icon metamask in taskbar
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > 2. Place the icon in folder "targets" with name meta-icon.png
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > 3. Open index.py and write this code:
> > > ```
> > 
> > 
> > > ```
> > >    ![Снимок](https://user-images.githubusercontent.com/95485725/145728008-57871a82-d346-408e-93a9-a32154e4602c.JPG)
> > > ```
> > 
> > 
> > Hi! Thank you for trying to help me.
> > I inserted the code and did what you told. No luck: the code you above is never invoked since on line 358, that if returns true (as if the bot clicked the "sign" button). I dont know yet why it thinks it clicked the sign button while its not; but with the false positive, the login() function returns and the bot begins the loop.
> > By the way, here is the code typed (one must pay attention to identation) -- insertion below line 389 of actual index.py :
> > # ------------------>
> > # BEGIN: Code inserted to fix MetaMask sign-in
> > # ------------------>
> > ```
> > if not clickBtn(images['select-wallet-2'], name='signBtn'):
> > 
> >     logger('TRYING NEW CODE...')
> > 
> >     if clickBtn(images['meta-icon'], name='metaiconBtn'):
> > 
> >         if clickBtn(images['select-wallet-2'], name='signBtn', timeout = 20):
> > 
> >             login_attempts = login_attempts + 1
> > 
> >             if clickBtn(images['treasure-hunt-icon'], name='treasureHunt', timeout=30):
> > 
> >                 login_attempts = 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > # ------------------>
> > # END: Code inserted to fix MetaMask sign-in
> > # ------------------>
> 
> Please show your icon and take screen folder with this file and it's name. Also try to set `time.sleep(2)` after tap to "Connect wallet" button and before tap to "Sign"
> 
> And may be can you show video with your problem?

Would you please send zipped file, it was much easier :) thanks
