### ISSUE TITLE
[BOT] Não executa nenhum comando

### ISSUE THREAD

**Issue by cardic1** [mpcabete/bombcrypto-bot#257]
• Desinstalei a versão mais recente do Python  e instalei a 3.9.7.
• Instalei requirements.txt, tudo normal (antes da atualização do captcha funcionava 100%)
• Não deu NENHUM erro.
• Dou o mando python index.py no cmd como administrador

O Gatinho de inicialização começa, todos os processos aparecem na tela, mas NÃO dectecta nenhum botão e não realização nenhuma ação o mouse não se mexe, não clica, fica como se o bot estivesse desligado.

• Ao desinstalar a versão 9.10 e instalar a 3.9x eu passei o CCLEAR, reinicia o pc tudo certinho, mesmo assim não foi

**Alguém sabe como me ajudar?**

**Comment by kerferber** [comment]
Aqui funcionou 100% sem precisar nenhum ajuste com a versão 3.9.3 64x
Será algum problema de resolução? ou 'zoom'? aqui uso com zoom do navegador em 100%.

Se não apresenta nenhum erro deveria funcionar....
No cmd ele roda legal? aparece as informações do que o programa está fazendo? (procurando botoes, procurando barras de stamina, procurando captcha etc)

**Comment by cardic1** [comment]
> 

Reinstalei o python em outro local do HD e limpei todos os arquivos temp.
Botei pra rodar de novo agora e o servidor caiu kkkk, vou aguardar e ver se funcionou, caso dê certo, vou descrever certinho o passo a passo que fiz.

**Comment by trinitro2** [comment]
> > 
> 
> Reinstalei o python em outro local do HD e limpei todos os arquivos temp. Botei pra rodar de novo agora e o servidor caiu kkkk, vou aguardar e ver se funcionou, caso dê certo, vou descrever certinho o passo a passo que fiz.

foi agora?

**Comment by evandroid** [comment]
Caiu agora sim. Agora com relação ao que o colega citou acima, eu tb estou com o mesmo problema. 100%, 1920x1080, python 3.9.9. Resolve o captcha mas nao executa nenhum comando, e no fim dá idle. Versão anterior funcionava certinho, acabei voltando a versão anterior e estou rodando com ela.

**Comment by trinitro2** [comment]
> Caiu agora sim. Agora com relação ao que o colega citou acima, eu tb estou com o mesmo problema. 100%, 1920x1080, python 3.9.9. Resolve o captcha mas nao executa nenhum comando, e no fim dá idle. Versão anterior funcionava certinho, acabei voltando a versão anterior e estou rodando com ela.

qual versao?

**Comment by cardic1** [comment]
Puts não foi ainda, mas sem problemas eu vou instalar uma máquina virtual que deve resolver.
Obrigado pela ajuda trinitro2 e evandroid

**Comment by cmxavier** [comment]
Meu irmão está com o mesmo problema, alguma solução ?

**Comment by cardic1** [comment]
> Meu irmão está com o mesmo problema, alguma solução ?

Mano, acabei criando uma máquina virtual porque não consegui corrigir esse bug não :( 
A maquina virtual da uma laguada aqui porque o note é antigo, mas funciona bem certinho o bot

**Comment by marcelosore** [comment]
cara to com mesmo problema aqui, já fiz de tudo e não deu certo. Antes funcionava 100%. tive que instalar em uma maquina virtual também. Se achar alguma outra solução me avisa, kkkk vlw

**Comment by cardic1** [comment]
> 

Estou tentando desde cedo arrumar isso, já criei outro usuário, já deletei o python e instalei em nova pasta, e mesmo assim num vai nem fodendo. a Maquina virtual aqui trava demais :( estou no aguardo de um anjo pra nos ajudar kkkkk

**Comment by evandroid** [comment]
> > Caiu agora sim. Agora com relação ao que o colega citou acima, eu tb estou com o mesmo problema. 100%, 1920x1080, python 3.9.9. Resolve o captcha mas nao executa nenhum comando, e no fim dá idle. Versão anterior funcionava certinho, acabei voltando a versão anterior e estou rodando com ela.
> 
> qual versao?

A versão de antes do @mpcabete soltar essa com o cpatcha solver.

**Comment by evandroid** [comment]
Pessoal, to dando uma estudada no código pra entender pq isso tá acontecendo, assim que tiver uma solução posto aqui. Mas uma coisa ja falo, versao 3.9.9 do python que eu to usando aqui.

**Comment by marcelosore** [comment]
Cara, consegui resolver aqui, era algo bem tosco...
Simplesmente fiquei mexendo no zoom do navegador até ele identificar as imagens e começar a rodar.
Não sei se é o mesmo caso que vocês, mas aqui resolveu.... tmj

**Comment by evandroid** [comment]
> No meu irmão instalamos a versão 3.9.8 que é a versão que eu estou usando e está funcionando no meu notebook. A unica coisa que eu achei estranho é que no pc do meu irmão não deu erro do ms tool do visual studio quando eu rodei o pip install -r requiriments.txt e por isso eu não instalei, vocês tiveram de instalar ?

Pelo que eu enteendi, ele pedia o visual studio por causa da biblioteca simpleaudio. Aí o @mpcabete resolveu isso, e não pediu mais não, acho que colocou uma substituta ou até mesmo removeu, ja que nao precisa mais avisar por audio que tem captcha. Bom, instalei em 5 maquinas, a versão com captcha solver, e nenhuma pediu visual studio mais, a instalação dos requirements foi de boa.

**Comment by cardic1** [comment]
> Cara, consegui resolver aqui, era algo bem tosco... Simplesmente fiquei mexendo no zoom do navegador até ele identificar as imagens e começar a rodar. Não sei se é o mesmo caso que vocês, mas aqui resolveu.... tmj

MANOOOOOOOOO GOD demais, deixei o meu com 110% e rodou <3
