### ISSUE TITLE
Problema com o use_click_and_drag_instead_of_scroll

### ISSUE THREAD

**Issue by Mrksales** [mpcabete/bombcrypto-bot#26]
meu caro, boa noite, agradeço bastante por fazer esse bot para a comunidade. tenho uma duvida para tirar contigo. O bot, em meu computador, quando vai colocar os bonecos para trabalhar, coloca os 5 primeiros e não rola a tela para baixo, dessa forma os demais personagens não são identificados e ficam sem trabalhar, poderia me ajudar?

**Comment by mpcabete** [comment]
a opçao use_click_and_drag_instead_of_scroll esta como true ou false no seu arquivo de confugruaçoes? Se estiver como falso tenta colocar como true

**Comment by Mrksales** [comment]
Já tá em true mano ;-;

**Comment by Mrksales** [comment]
amigo?

**Comment by mpcabete** [comment]
Oi amigo, desculpe a demora, fiquei uns dias sem ver e acumulou vários issues pra eu responder!
Olha, uma coisa que pode valer a pena testar então é colocar a opção em false e aumentar o valor da configuração
`scroll_size: 60`

Agora, talvez o problema seja que ele não esteja reconhecendo a [imagem](https://github.com/mpcabete/bombcrypto-bot/blob/main/targets/commom-text.png) q ele usa de referencia pra clickar e arrastar. Você pode tentar diminuir o a opção "trashhold: commom" na config ou substituir a imagem nos arquivos do bot, dentro da pasta target.
