### ISSUE TITLE
[Req] Need Sleep Function

### ISSUE THREAD

**Issue by mkroxm** [mpcabete/bombcrypto-bot#260]
[Req] Need Sleep Function for bot like send all working hero's on rest after x hours and but bot on sleep or send bot to sleep when no active hero in game like when there is no active hero in game for 20 or 30 minutes there no need to refresh passions and checking for captcha etc without any profit 
thanks

**Comment by kerferber** [comment]
> [Req] Need Sleep Function for bot like send all working hero's on rest after x hours and but bot on sleep or send bot to sleep when no active hero in game like when there is no active hero in game for 20 or 30 minutes there no need to refresh passions and checking for captcha etc without any profit thanks

interesting.

what i really wanted is to make the computer hibernate for 'x' time and then wake up.

for those who have few heroes, like me, it's unnecessary to leave them mining for 20 minutes and then rest for 2 hours (with the computer on)

**Comment by poloik007** [comment]
you probably would get disconnected by idle?

**Comment by mkroxm** [comment]
> you probably would get disconnected by idle?

Yes But its same as users are doing when play they don't do refresh hero's positions when no active hero it's like extra safety for accounts Like when ever you pay from your pc you are keep closing game after all hero's energy  rainout then you can close game and come back after 1 or 2 hrz then play again it's same request for bot to do the same  so accounts are more secure.
