### ISSUE TITLE
Erro ao executar versão de hoje

### ISSUE THREAD

**Issue by Cromaz** [mpcabete/bombcrypto-bot#261]
![image](https://user-images.githubusercontent.com/95131174/145722369-f44e4ecc-6a7c-4119-b420-88ce17c5b6a0.png)

Alguém me ajuda a entender o que seria esse erro? Eu baixei hj a ultima versão.

**Comment by Yumiizera** [comment]
Instala a versão do python 3.9.9 ou uma versão 3.9.X que deve resolver.

**Comment by rodrigobragamg** [comment]
`pip install opencv-python`

**Comment by Cromaz** [comment]
funcionou, coloquei a versão antes da .10 e rodei o pip novamente... foi joia. valeu.
