### ISSUE TITLE
Bot não solta o clique no slide do captcha 

### ISSUE THREAD

**Issue by VCRAZY22** [mpcabete/bombcrypto-bot#264]
Após algum tempo o bot não solta o clique ao tentar fazer o slider fazendo com q o bot encerre logo após.

**Comment by nasiloski** [comment]
Mesmo problema aqui, comigo aconteceu na primeira vez que abri o bot, daí precisei soltar o clique sozinho. Quando isso acontece o script quebra, daí precisa reiniciar o bot e contar com a sorte.

**Comment by mtmassa** [comment]
Mesmo problema aqui. Tanto na no windows como no linux

**Comment by lafaete08** [comment]
Aqui mesmo problema, já tentei várias versões do phyton  e não resolve

**Comment by rodrigobragamg** [comment]
O mpcabete soltou um update neste sentido. Só baixar o arquivo novo ou o código completo.
