### ISSUE TITLE
Macro não clica no Sign (RESOLVIDO)

### ISSUE THREAD

**Issue by yuucsx** [mpcabete/bombcrypto-bot#267]
Já tirei print da minha vm e troquei, mas mesmo assim não vai
![image]![145729136-0541d2b9-c501-4861-94cd-947e9a3be566_LI](https://user-images.githubusercontent.com/25357402/145729520-3b09aa09-b232-433f-93a8-587d4e47ed22.jpg))
![select-wallet-2](https://user-images.githubusercontent.com/25357402/145729155-f7dafd93-c795-400c-b562-e8d1496b6887.png)
![image](https://user-images.githubusercontent.com/25357402/145729169-d60395d1-e0a6-43c8-a0e8-d454d7291b5e.png)

**Comment by ltv2** [comment]
Estou com o mesmo problema, de resto tá funcionando 10, só este problema mesmo.

**Comment by yuucsx** [comment]
> Estou com o mesmo problema, de resto tá funcionando 10, só este problema mesmo.

consegui resolver mano, tirei a print assim e foi
![select-wallet-2](https://user-images.githubusercontent.com/25357402/145729435-878e8374-6c53-4752-891d-cf35c7bc0339.png)

**Comment by Coolhatcker** [comment]
1. Set `time.sleep(2)` after click button connect wallet
2 Reboot vm

**Comment by evandroid** [comment]
Hello! I tried both solutions. No luck. The bot keeps not clicking on the "sign" button. Windows 11, 1920x1080, 100% scale, 100% zoom, chrome, edge or firefox (does not click, regardless) VM on proxmox VE.

**Comment by Coolhatcker** [comment]
> Hello! I tried both solutions. No luck. The bot keeps not clicking on the "sign" button. Windows 11, 1920x1080, 100% scale, 100% zoom, chrome, edge or firefox (does not click, regardless) VM on proxmox VE.

Please show screen where do you past time.sleep (2)

**Comment by SEM202** [comment]
Hola me funciono perfectamente gracias 

> yuucsx

gracias funciona perfectamente ,nunca antes me habia funcionado e intente de todo .a tu foto hay que renombrarla como ...select-wallet-2  y usar .......
python index.py time.sleep(2)    ....gracias genio

**Comment by evandroid** [comment]
> > Hello! I tried both solutions. No luck. The bot keeps not clicking on the "sign" button. Windows 11, 1920x1080, 100% scale, 100% zoom, chrome, edge or firefox (does not click, regardless) VM on proxmox VE.
> 
> Please show screen where do you past `time.sleep (2)`

Thank you, man. What solved here was your solution (time.sleep(2) AND the new crop without rounded corners of the "sign" button. Now its working like a charm! Many thaks you all.
