### ISSUE TITLE
alguns problemas

### ISSUE THREAD

**Issue by rnesheiksilvestre** [mpcabete/bombcrypto-bot#268]
Boa noite amigos.
Estou com o bot ativo des de ontem e tive alguns problemas

- Deixei o bot rodando quando fui ver tinha sumido alguns personagem mas mostrava eles nos heroes solução foi da um ctrl f5 e resolveu
- outro problema é quando da unknown as vezes ele não clica
- outro problema é quando ele da refresh na pagina e as. vezes não clica no botão para conectar a wallet ai tem que da ctrl f5
- e um problema no captcha aconteceu uma vez comigo de travar o captcha porem vi alguns relato de quando tem 0 o bot crasha e não resolve o captcha

se alguem tiver alguma solução agradeço <3

**Comment by mtmassa** [comment]
em busca da mesma solução... aqui ta ficando mais parado que rodando kkk

**Comment by mpcabete** [comment]
da uma atualizada no bot e vê se resolve!
