### ISSUE TITLE
slider stuck fix - Apos essa atualização nao resolve mais catpcha

### ISSUE THREAD

**Issue by mtmassa** [mpcabete/bombcrypto-bot#269]
A mais ou menos 20 minutos o bot parece ter sido atualizado, o Solve captcha esta marcado com slider stuck fix. Porem aqui apos fazer a atualizacao o bot esta levando o slider todo pra direta, depois todo para a esquerda de forma rapida, nao esta resolvendo o captcha e ao chegar na esquerda ele solta o botao e o catpcha fica dando reload. Enfim nao ta resolvendo mais captcha!

**Comment by mpcabete** [comment]
ops, ta rolando isso mesmo, deixa eu ver q q ta rolando aki

**Comment by mpcabete** [comment]
Prontinho, vlw pelo toque!

**Comment by fx2016** [comment]
Opa, por favor galera, precisa rodar novamente _pip install -r requirements.txt_ ou é só trocar os arquivos na pasta?

**Comment by FDNiisan** [comment]
> Opa, por favor galera, precisa rodar novamente _pip install -r requirements.txt_ ou é só trocar os arquivos na pasta?

Eu só substituí. Sempre é bom rodar o pip pois caso tenha adicionado uma nova biblioteca já atualiza.
Testei aqui e tá fununfando até então :)
