### ISSUE TITLE
|NÃO RESOLVIDO| Para Mac como posso proceder?

### ISSUE THREAD

**Issue by Marques1233** [mpcabete/bombcrypto-bot#27]
Se conseguir já te mando 1 Bcoin. :)

**Comment by mpcabete** [comment]
Ola marques, eu não sei exatamente qual eh o processo pra instalar o python no mac, mas voce deve econtrar facilmente. Com o python e o pip(o gerenciador de pacotes do python) instalados, vc pode dar os comandos que ele deve funcionar normalmente.

**Comment by Marques1233** [comment]
[
![Captura de Tela 2021-11-17 às 18 55 36](https://user-images.githubusercontent.com/94572891/142295648-8cbb34d4-73ae-4b33-8a74-3b8b523924b5.png)
](url)

Não ta indo :(

**Comment by Marques1233** [comment]
-bash: pip: command not found

Mostra esse comando. Instalei a versão mais recente do Python.

**Comment by Marques1233** [comment]
consegui aqui ainda tem que instalar o XCode.

**Comment by EricOFreitas** [comment]
Instalei tudo e aqui está com o mesmo problema, mas uso o windows server 2012. Esse xcode é só pro mac?

**Comment by icaronaser** [comment]
aqui roda o bot mas não mexe o mouse nem clica, como conseguiu @Marques1233 ?

**Comment by gustavo-ticto** [comment]
+1

**Comment by Marques1233** [comment]
errata: eu não instalei o XCode, acabei desistindo. Instalei um Macro de Mouse. Não é a mesma coisa que esse bot, mas tem me ajudado. Se conseguirem deem update aqui.

**Comment by Marques1233** [comment]
> aqui roda o bot mas não mexe o mouse nem clica, como conseguiu @Marques1233 ?

Massa, eu não consegui nem instalar os requirements, como conseguiu?

**Comment by eduardo-romao** [comment]
Instala o xcode e instala usando o pip3, pip3 install opencv-python.
