### ISSUE TITLE
Melhor navegador para rodar o BombCrypto

### ISSUE THREAD

**Issue by pegchargue** [mpcabete/bombcrypto-bot#270]
Boa noite!!! Gostaria de saber o melhor navegador para utilizar o Bomb junto com o Bot, pois uso o Firefox e o Chrome... Mas tenho que estar trocando sempre pois fica lento ou não conecta, mesmo depois de muitas tentativas e Muitos F5...
Se alguém puder me dar uma dica para utilizar melhor e melhorar o desempenho agradeceria muito!!!

**Comment by Yumiizera** [comment]
Hoje o jogo está com problemas, rlx que o problema não é navegador

**Comment by rodrigobragamg** [comment]
Brave é mais leve que os ambos que mencionou (há também um chamaod Ghost Browser). Chrome é o mais pesado.

**Comment by pegchargue** [comment]
São seguros??? Os que falei desde que comecei a jogar ele deixa o computador muito travado... estou com um computador formatado e com ssd somente para o jogo... mas mesmo assim fica pesado!!!

**Comment by pegchargue** [comment]
instalei o Windows 8, 10 e 11 mais todos travam iguais....
