### ISSUE TITLE
Sugestão para o bot não parar o processo após a terceira tentativa de catpcha

### ISSUE THREAD

**Issue by THEBESTSZ** [mpcabete/bombcrypto-bot#271]
Eu notei que no SolveCaptcha tem um exit(), que é o que faz o bot fechar após algumas tentativas que dão erradas, alterando o código para isso:
`

```python
def getSliderPositions(screenshot, popup_pos):
    slider = position(d['slider'],img=screenshot)
    if slider is None:
        print('no slider')
        #exit()        # comentando
        pyautogui.hotkey('ctrl','f5')
        return False
```

Creio que resolva, pois ao invés de encerrar o processo ele dá um f5 no navegador reiniciando todo o processo do bot, acho que seria uma boa se ao identificar o retorno de false resetar o tempo de tudo para 0, como se fosse a primeira vez que tivesse rodando o bot

**Comment by Redexote** [comment]
> SolveCaptcha

ef getSliderPositions(screenshot, popup_pos):
    slider = position(d['slider'],img=screenshot)

    if slider is None:
        print('no slider')
        return None
    (start_x, start_y) = slider

Seria essa parte aqui amigo?,  e como ficaria depois da alteração?

**Comment by zSinnK** [comment]
> > SolveCaptcha
> 
> ef getSliderPositions(screenshot, popup_pos): slider = position(d['slider'],img=screenshot)
> 
> ```
> if slider is None:
>     print('no slider')
>     return None
> (start_x, start_y) = slider
> ```
> 
> Seria essa parte aqui amigo?, e como ficaria depois da alteração?

Não é na index.py
segue caminho: pasta " captcha " > SolveCaptcha.py

linha 131 do código
