### ISSUE TITLE
Para agradecer

### ISSUE THREAD

**Issue by gillyanbfoz** [mpcabete/bombcrypto-bot#273]
Pessoal abre Issues para cobrar, dessa vez eu venho aqui agradecer a toda equipe envolvida, o bot ta rodando mto liso com todos problemas corrigidos, de novo muito obrigado a todos que colaboraram e vamos apoiar e mandar uma colaboração pro nosso amigo mpcabete : 0xbd06182D8360FB7AC1B05e871e56c76372510dDf  e Nucito : 0x6A0A96c348BF9e8A0333B9fe12F452043AF11a30 , para que sempre possam estar nos ajudando nas futuras atualizações.

Obrigado novamente.

**Comment by trinitro2** [comment]
@mpcabete fui ver o donate por paypal mas ta em USD e diz para mim "Você não pode enviar ou receber pagamentos nessa moeda."

tem como gerar em brl?

seu email nao ta na pag inicial, queria ver um orçamento com vc tb
