### ISSUE TITLE
Movimentos reais com o mouse antes dos clicks

### ISSUE THREAD

**Issue by gabrielwjesus** [mpcabete/bombcrypto-bot#274]
Pessoal, encontrei uma biblioteca pra implementar neste projeto. Da uma olhada aqui @mpcabete 

`from pyclick import HumanClicker`
essa biblioteca movimenta o mouse de forma totalmente humana, tremendo a mão, velocidade muda até no click
as funções são:
`hc = HumanClicker()` #para criar a classe 
`hc.move(x,y,t)` #movimentação perfeita
`hc.click()` #para clicar no ponto que ele moveu o mouse
reduz uma porrada de linhas do código

o que não deu certo: scroll na hora de escolher os herois
e o move só aceita numeros inteiros. E como transformar float em inteiro? com a função round
x = 234.4
x = round(x)
x ficará 234

Simplesmente perfeito os movimentos.

**Comment by IuriDrago2** [comment]
Tem como fazer um merge já com esses ajustes e subir um repositório no seu Git?

**Comment by IuriDrago2** [comment]
> Pessoal, encontrei uma biblioteca pra implementar neste projeto. Da uma olhada aqui @mpcabete
> 
> `from pyclick import HumanClicker` essa biblioteca movimenta o mouse de forma totalmente humana, tremendo a mão, velocidade muda até no click as funções são: `hc = HumanClicker()` #para criar a classe `hc.move(x,y,t)` #movimentação perfeita `hc.click()` #para clicar no ponto que ele moveu o mouse reduz uma porrada de linhas do código
> 
> o que não deu certo: scroll na hora de escolher os herois e o move só aceita numeros inteiros. E como transformar float em inteiro? com a função round x = 234.4 x = round(x) x ficará 234
> 
> Simplesmente perfeito os movimentos.

Tem como fazer um merge já com esses ajustes e subir um repositório no seu Git?

**Comment by gabrielwjesus** [comment]
> > Pessoal, encontrei uma biblioteca pra implementar neste projeto. Da uma olhada aqui @mpcabete
> > `from pyclick import HumanClicker` essa biblioteca movimenta o mouse de forma totalmente humana, tremendo a mão, velocidade muda até no click as funções são: `hc = HumanClicker()` #para criar a classe `hc.move(x,y,t)` #movimentação perfeita `hc.click()` #para clicar no ponto que ele moveu o mouse reduz uma porrada de linhas do código
> > o que não deu certo: scroll na hora de escolher os herois e o move só aceita numeros inteiros. E como transformar float em inteiro? com a função round x = 234.4 x = round(x) x ficará 234
> > Simplesmente perfeito os movimentos.
> 
> Tem como fazer um merge já com esses ajustes e subir um repositório no seu Git?

kkk eu nao sei mexer mto bem no github ainda, estou aprendendo. Mas hoje a noite eu vou atualizar meu index.py e todo o projeto com essa mudança
mas em geral eu só mudei essa função abaixo, adicionei a biblioteca e criei uma classe pra ela. 

```
def moveToWithRandomness(x,y,t):
    #pyautogui.moveTo(addRandomness(x,10),addRandomness(y,10),t+random()/2)
    hc.move((round(x),round(y)),round(t))
```

**Comment by THEBESTSZ** [comment]
@mpcabete essa é uma boa ideiaaa
