### ISSUE TITLE
Alguém com esse error aí ? COULD NOT FIND A VERSION THAT SATISFIES THE REQUIREMENTE TORCH= 1.10.0

### ISSUE THREAD

**Issue by lifarrx** [mpcabete/bombcrypto-bot#275]
COULD NOT FIND A VERSION THAT SATISFIES THE REQUIREMENTE TORCH= 1.10.0

**Comment by lifarrx** [comment]
ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.10.0

**Comment by trinitro2** [comment]
> COULD NOT FIND A VERSION THAT SATISFIES THE REQUIREMENTE TORCH= 1.10.0

poe a versao 9 do python, nao a 10
