### ISSUE TITLE
Issues que encontrei, não sei se apresenta para outras pessoas.

### ISSUE THREAD

**Issue by lifarrx** [mpcabete/bombcrypto-bot#276]
Detecta o botão da wallet mas não clica

Resolve o captcha abre a metamask mas não clica em sign, "fecha" a meta pois parece que clica fora da aba lateral que abre, então a meta fica com aquela notificação de 1, como se tivesse uma ação pendente.

**Comment by trinitro2** [comment]
#267

troca o botao pelo que eles falaram la. muda a metamask pra ingles
