### ISSUE TITLE
Erro TypeError: Cannot Unpack non-iterable NonteType object

### ISSUE THREAD

**Issue by amatoxd** [mpcabete/bombcrypto-bot#277]
Olá, gente. O bot vem funcionando normalmente, inclusive não está stuckando mais no slider, porém o erro TypeError: Cannot Unpack non-iterable NonteType object aparece às vezes e desliga o bot, obrigando-nos a religá-lo. Alguém sabe como resolver?

**Comment by BBencee** [comment]
I've had this issue also, but only when it was trying to work and I manually changed some things on purpose
