### ISSUE TITLE
Multi Accounts Sem o VM?

### ISSUE THREAD

**Issue by Redexote** [mpcabete/bombcrypto-bot#278]
Ola pessoal , vcs conseguiram usar o bot , em multi accounts sem o VM? queria muito pois meu pc nao e dos melhores. 
vlws

**Comment by lifarrx** [comment]
up

**Comment by fguide** [comment]
A maioria dos recursos hoje são com virtualização de alguma forma, VM, Docker, Windows SandBox, etc.

Uma maneira simples para fazer isso (semvirtualização) é com script no sistema operacional que alterna o navegador, deixe dois navegadores abertos e coloque o script para alternar a tela enquanto o bot roda.

Para windows: https://www.nirsoft.net/utils/nircmd.html serve para minimizar/maximizar por CMD. Para criar o script utilize o Task Scheduler (gerenciador de tarefas?)

**Comment by ricardofernandess** [comment]
Tem o PR aberto de um colega com Dockerfile e docker-compose para rodar em container usando Ubuntu, é mais leve que rodar com VM Windows
