### ISSUE TITLE
Funcionamento do isWorking

### ISSUE THREAD

**Issue by alvesduarte97** [mpcabete/bombcrypto-bot#28]
Estou fazendo algumas mudanças no bot.

E no momento estou tentando entender a função isWorking, pq as variaveis isBelow e isAbove estão validando a posição y da barra vs a posição dos botões?

Tem disponibilidade para conversarmos sobre o código?

![image](https://user-images.githubusercontent.com/4249702/142299194-40a5fec3-19e5-40ca-8dc0-2338a117366d.png)

**Comment by mpcabete** [comment]
oi amigo, essa função recebe a posição da  barra e a posição dos botões de "ir trabalhar" que podem ser clicados.
A ideia eh ela retornar se o herói que tem a barra esta com o botão de "ir trabalhar" ou não.
Pra fazer isso, pra cada botão, a variável isBelow indica se a barra esta em baixo da parte de cima da imagem do botão(o y + altura do botao). e a isAbove indica se a barra esta acima da parte de baixo do botão(y - altura do botao). se existe um botão de "ir trabalhar" na mesma altura da barra, isso indica que o heroi daquela barra não está trabalhando.

**Comment by mpcabete** [comment]
Só por curiosidade, o que você esta mudando no bot?

**Comment by alvesduarte97** [comment]
Adicionando funcionalidade para multiplas contas, refactor do código, criando uma interface pra facilitar o uso e algumas opções de estratégia pro game.

Se quiser podemos conversar no discord, que te explico melhor.

Duarte#8425
