### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by yuribyte** [mpcabete/bombcrypto-bot#282]
O bot apresentou o seguinte erro e fechou
```
  File ".\index.py", line 518, in <module>
    main()
  File ".\index.py", line 495, in main
    login()
  File ".\index.py", line 354, in login
    solveCaptcha()
  File "C:\bomb\captcha\solveCaptcha.py", line 184, in solveCaptcha
    captcha_img = captchaImg(screenshot, popup_pos[0])
IndexError: tuple index out of range
```

**Comment by Malk4viano** [comment]
Aconteceu o mesmo aqui.

**Comment by fx2016** [comment]
O bot foi atualizado a 14 horas atrás, vcs baixaram e substituíram na pasta?

**Comment by jeanvetorello** [comment]
sim isso mesmo ultima versao ocorrendo as vezes,

ne 184, in solveCaptcha
    captcha_img = captchaImg(screenshot, popup_pos[0])
IndexError: tuple index out of range
