### ISSUE TITLE
Unknown erro

### ISSUE THREAD

**Issue by BenitoMarculanoRibeiro** [mpcabete/bombcrypto-bot#285]
![Screenshot_1](https://user-images.githubusercontent.com/49006573/145859852-f9d89522-1bb3-4797-8c78-2b08a0a0084d.jpg)
Não está passando por essa Imagem.

**Comment by BenitoMarculanoRibeiro** [comment]
![image_2021-12-13_14-48-20](https://user-images.githubusercontent.com/49006573/145862790-90525c41-5699-4a62-ae40-1e5065f8dcaf.png)
Tem esse outro erro também.

**Comment by trinitro2** [comment]
printa a img, poe no paint. recorta ela deixando uma bordinha rosa. salva na pasta targets em OK.png

**Comment by BenitoMarculanoRibeiro** [comment]
Isso serve para as duas imgs?


> printa a img, poe no paint. recorta ela deixando uma bordinha rosa. salva na pasta targets em OK.png

**Comment by trinitro2** [comment]
> Isso serve para as duas imgs?
> 
> > printa a img, poe no paint. recorta ela deixando uma bordinha rosa. salva na pasta targets em OK.png

sim, ele so detecta o botao OK

**Comment by BenitoMarculanoRibeiro** [comment]
Testei e não resolveu.

**Comment by Galinho90** [comment]
> Testei e não resolveu.
  
 Foi resolvido no #285
