### ISSUE TITLE
dificuldades com o bot

### ISSUE THREAD

**Issue by blackproblem** [mpcabete/bombcrypto-bot#288]
estou tendo esse erro com o python na versao 3.9.9
![image](https://user-images.githubusercontent.com/96033229/145902817-c87bfaf3-1190-4829-91af-83a0a661f31e.png)

**Comment by trinitro2** [comment]
voce fez o pip install -r requirements.txt?

**Comment by blackproblem** [comment]
sim, fiz todo o processo de instaçao. 
![image](https://user-images.githubusercontent.com/96033229/145903141-0aa90dc7-ce7f-4f7c-91fe-84e660660abd.png)

**Comment by yNathanZx** [comment]
desinstala o python e instala a versão abaixo da 3.10.0, acho que é 3.9.9, algo assim, foi assim que resolvi

**Comment by blackproblem** [comment]
eu estou com a 3.9.9, vou ver se outra resolve

**Comment by Galinho90** [comment]
> eu estou com a 3.9.9, vou ver se outra resolve

Instale a versão 3.9.9 que já resolve esse erro. Estava com o mesmo erro, ai aatualizei e funfou normal.

**Comment by blackproblem** [comment]
vlw pessoal, consegui rodar o bot com a versao 3.9.8
