### ISSUE TITLE
Seria Possivel ?

### ISSUE THREAD

**Issue by vtremura** [mpcabete/bombcrypto-bot#29]
Primeiramente sensacional o boot! Meus parabéns, assim que eu der um claim vou mandar um donate para vc.

Estava pensando... É possivel definir um timer para que ele coloque todos hero de uma vez, ao invés de somente colocar os que estão com a barrinha verde ?

Exemplo:
Eu defino que a cada 1h30 ele deve colocar todos os hero para trabalhar independente se a barrinha esta cheia ou não.

**Comment by mpcabete** [comment]
Oi , é sim!
Esse era o jeito que ele funcionava antigamente, você pode colocar ele nesse modo mudando a opção:
`only_click_heroes_with_green_bar: true`
no arquivo de configuração. lá voce pode ajustar os intervalos de tempo também.
