### ISSUE TITLE
[DUVIDA] O bot tem random pixel ou clica sempre no mesmo pixel da imagem?

### ISSUE THREAD

**Issue by Aronwolf1998** [mpcabete/bombcrypto-bot#290]

**Comment by FDNiisan** [comment]
O @mpcabete já implementou a aleatoriedade no bot

**Comment by Aronwolf1998** [comment]
Estava a seguir os pixeis onde era feito o clique e reparei que o rato em cada botão carregava sempre no mesmo pixel

Desativei a precisão do rato no painel de controlo e agora clica sempre em pixeis diferentes é capaz de ajudar a ser mais difícil de banirem

**Comment by Aronwolf1998** [comment]
Estava a seguir os pixeis onde era feito o clique e reparei que o rato em cada botão carregava sempre no mesmo pixel

Desativei a precisão do rato no painel de controlo e agora clica sempre em pixeis diferentes é capaz de ajudar a ser mais difícil de banirem
