### ISSUE TITLE
Confirmação da Metamask "atrás da tela"

### ISSUE THREAD

**Issue by matheusanat** [mpcabete/bombcrypto-bot#291]
A dúvida não tem a ver diretamente com o bot, mas contribuiria para quando deixamos ele sozinho

Pessoal, eu já havia visto um tópico com este assunto, mas não parece ter havido direcionamento e ele acabou esfriando...

Em alguns momentos, o jogo demora a carregar o captcha, abrindo a tela de confirmação da metamask antes, e então apenas depois o captcha...como o jogo busca resolver o captcha, ele clica na tela do jogo, enviando a tela de confirmação para segundo plano.
Desta forma, ele não encontrar mais o aceite, e quando ele roda a rotina de login novamente, a tela aberta expira a sessão, o que torna o loop infinito.

Alguém conseguiu contornar esta situação? Testei em mais de um navegador e mantém o problema, que é geralmente de madrugada e acabo perdendo o farm.

Grato.

**Comment by Ricardoadlj** [comment]
Estava com o mesmo problema, clicava no connect e na hora de ir no sign in a metamask ia para segundo plano no opera, mas baixei o google chrome e resolvi o problema

**Comment by matheusanat** [comment]
> Estava com o mesmo problema, clicava no connect e na hora de ir no sign in a metamask ia para segundo plano no opera, mas baixei o google chrome e resolvi o problema

Meu navegador principal é o chrome, porém quase toda run da madrugada acontece isso

**Comment by mtmassa** [comment]
Acontece o mesmo comigo no brave, desde de domingo  bot esta bem mais estavel, so esse problema que me incomoda ainda, poderia ter uma função pra clicar no icone da meta na barra de tarefas pra fazer ele voltar pra primeiro plano e o bot seguir com as funções... 
@mpcabete

**Comment by mtmassa** [comment]
tava pensando aqui, quando ela fica em segundo plano fica o icone dela na barra de tarefas, o bot poderia dar um click nela ao reconhecer a imagem, o que traria ela pro primeiro plano e a função seguiria... icone de exemplo...

![Captura de tela 2021-12-14 123356](https://user-images.githubusercontent.com/22082480/146037309-98bcb9f3-2f03-4ab7-806d-c240e2e607fe.png)
