### ISSUE TITLE
error when [pip install -r requirements.txt]

### ISSUE THREAD

**Issue by biulanar** [mpcabete/bombcrypto-bot#296]
ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.10.0

**Comment by Lordblackhat** [comment]
Install python 3.9.9
Dont install 3.10+

**Comment by kerferber** [comment]
> ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none) ERROR: No matching distribution found for torch>=1.10.0

baixe e instale esta versão do python https://www.python.org/downloads/release/python-399/

(após desinstalar  a anterior)

**Comment by biulanar** [comment]
1 - Veja a versão do seu python.
Se ele estiver em qualquer versão acima da 3.9.x ele não vai rodar pois o torch não foi atualizado.

2 - Se o torch mesmo assim estiver com problema recomendo instalar em uma virtualenv para saber se o problema se trata de uma incompatibilidade com algum dos seus pacotes instalados.

3 - Se mesmo assim o seu torch não conseguir ser instalado recomendo que desinstale o seu python completamente e tente reinstalar novamente.



> Install python 3.9.9 Dont install 3.10+

Worked.

**Comment by fx2016** [comment]
Bom dia povo, por favor, alguém pode me explicar o que faz o comando _pip install -r requirements.txt_ ?
