### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by adminiw** [mpcabete/bombcrypto-bot#3]
Why did I run successfully? After clicking "commect" to click, why did the mouse fly directly to the blank space in the upper right corner

**Comment by mpcabete** [comment]
Hey, yeah, that is a bug. That is probably a false positive.
The bot thinks he seed the “select wallet” button and tries to click it.
I have added a config file where you can play with some of the thresholds. Try increasing the select wallet one, that should solve the issue.

**Comment by adminiw** [comment]
Do I need to replace my browser?

**Comment by mpcabete** [comment]
nope, just download the new version. and if you change the config file just save it and restart the bot. You can kill it with ctrl + c.
