### ISSUE TITLE
não clica no work e não reconhece o captcha

### ISSUE THREAD

**Issue by pedrokeplerpkpv** [mpcabete/bombcrypto-bot#300]
bom dia, estou usando o brave e o bot parou de clicar no botão work, ele reconhece o botão mas ele clica do lado, ou seja, não manda o boneco trabalhar, alguem sabe o que pode ser? e ele também não está captando o captcha, quando aparece ele diz que não tem nenhum popup de captcha.

**Comment by denysoliveira13** [comment]
Bom dia pessoal, estou tendo o mesmo problema com o botão work, mas estou utilizando o chrome. Ele reconhece o botão, mas clica ao lado, entre o botão e a barra de stamina, não surtindo efeito.
Outro problema que estou tendo é que o meu fica em loop quando arrasta para baixo nesta mesma tela, nunca saindo dela.
