### ISSUE TITLE
Bot não loga novamente na metamask

### ISSUE THREAD

**Issue by gus4ng** [mpcabete/bombcrypto-bot#302]
Deixei rodando na madrugada, o jogo caiu e o bot não conseguiu logar novamente. Já deve ser a terceira noite que isso acontece;
Apenas uns 20 avisos de login no metamask em segundo plano.
Problema está em localizar e clicar no sign

**Comment by dionatharibeiro** [comment]
Bom dia Gus4ng,
Também tive este problema algumas vezes, solucionei de fazendo duas alterações:
1-Substitui a imagem select-wallet-2 da pasta target por um PNG tirado do meu próprio computador, sem fundo nem bordas
2- Alterei o timeout da linha abaixo dentro da def login() de 10 para 15 segundos
if clickBtn(connect_wallet_btn_img, name='connectWalletBtn', timeout = 10):

**Comment by gus4ng** [comment]
> 

Bom dia meu queridão! 
muito obrigado, tentarei no dia e retorno

**Comment by csr1995** [comment]
O meu esta dando o seguinte erro:

Traceback (most recent call last):
  File "C:/Bomb/index.py", line 522, in <module>
    main()
  File "C:/Bomb/index.py", line 499, in main
    login()
  File "C:/Bomb/index.py", line 364, in login
    if clickBtn(images['select-wallet-2'], name='sign button', timeout=15):
KeyError: 'select-wallet-2'

Já troquei a imagem, coloquei o sleep e alterei o timeout conforme as outras intruções.

**Comment by kalleldf** [comment]
alguém pode me ajudar, ele localiza a metamask, mas não clica no botão de logar, já troquei o idioma e fica do mesmo jeito.

**Comment by hamzalamou** [comment]
> alguém pode me ajudar, ele localiza a metamask, mas não clica no botão de logar, já troquei o idioma e fica do mesmo jeito.
mude a foto select-wallet-2.png na pasta "target" com sua foto
Curtiu isso
![image](https://user-images.githubusercontent.com/35382455/146098925-4d8b8e8a-5429-4945-8f4e-e32df5dae54c.png)

**Comment by gus4ng** [comment]
> Bom dia Gus4ng, Também tive este problema algumas vezes, solucionei de fazendo duas alterações: 1-Substitui a imagem select-wallet-2 da pasta target por um PNG tirado do meu próprio computador, sem fundo nem bordas 2- Alterei o timeout da linha abaixo dentro da def login() de 10 para 15 segundos if clickBtn(connect_wallet_btn_img, name='connectWalletBtn', timeout = 10):

funcionou!! muito obrigado
