### ISSUE TITLE
How to make it work in zoom out 50% only captcha solver ?

### ISSUE THREAD

**Issue by PandaGen19** [mpcabete/bombcrypto-bot#303]
How to make it work in zoom out 50% only captcha solver ?
another function only change pictures it work perfect only auto solver it's not work in 50% zoom out

**Comment by mtmassa** [comment]
I believe that the default images used Full HD resolution, you may be using a different resolution. The easiest fix would be for you to generate new images at their default resolution and replace the images in the target folder in bombcrypto-bot-main.
