### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by nezkaum** [mpcabete/bombcrypto-bot#305]
![image](https://user-images.githubusercontent.com/95445704/146017614-1ed1409b-8526-40c4-9576-7d5d14cedc39.png)

Alguem sabe como arrumar isso ?

**Comment by trinitro2** [comment]
tem uns 5 topicos com a mesma coisa.

remove o python versao 10 e poe a ultima da versao 9 e refaz os requerimentos
