### ISSUE TITLE
BOT ENCERRA AUTOMATICO ?

### ISSUE THREAD

**Issue by matheus-rpk** [mpcabete/bombcrypto-bot#307]
Uma dúvida já tinha reparado outras vezes que quando servidor ficar offline o bot para de executar as vezes, por exemplo hoje eu executei as 00:00 e as 07:00, o bot parou de rodar no terminal, tem alguma função no código sobre quando aparecer que ela mensagem do servidor offline parar de executar ?

**Comment by matheusanat** [comment]
Se por acaso ele estiver encerrando por conta do "erro no slider", basta baixar novamente o código, pois já foi atualizado.

Outros erros, se puder informar...
