### ISSUE TITLE
o que é essa atualização no bot de 12h atrás com nome "tip" ?

### ISSUE THREAD

**Issue by janwell03** [mpcabete/bombcrypto-bot#309]
o q ela mudou/melhorou no macro?
queria saber pra ver se preciso baixar dnv nas maquinas virtuais ou não.

**Comment by trinitro2** [comment]
penso que mudou o donate

**Comment by backslash-f** [comment]
Documentação e 4 segundos mais lento pra iniciar: 
https://github.com/mpcabete/bombcrypto-bot/commit/8a20f2e8e6692947a227fa57a44ab9f9106f4d78

**Comment by janwell03** [comment]
como assim documentação? 4s mais lento pra iniciar o q exatamente? :s

**Comment by jpedrocguimaraes** [comment]
> como assim documentação? 4s mais lento pra iniciar o q exatamente? :s

4s para iniciar o bot, cara, ele alterou uma mensagem de doação e ela fica a mostra por 4s até o bot começar a trabalhar.
