### ISSUE TITLE
Status Servidor

### ISSUE THREAD

**Issue by s1k3ira** [mpcabete/bombcrypto-bot#310]
Pessoal, sabem que tem alguma API ou pagina que de para pegar o status do servidor do Bomb ?

**Comment by backslash-f** [comment]
Eu acho que não tem, mas se tiver também quero saber. 
Atualmente eu uso o https://t.me/BombCryptoGroup, mas se tivesse uma API seria melhor.

**Comment by Nucito** [comment]
@s1k3ira @backslash-f Atualmente existem duas maneiras para você monitorar isso:
1 - https://api.bombcrypto.io/ccu
2 - Faça o ping para a api do websocket em que o bombcrypto esta rodando😁

**Comment by backslash-f** [comment]
@Nucito Perfeito, valeu!

**Comment by s1k3ira** [comment]
> @s1k3ira @backslash-f Atualmente existem duas maneiras para você monitorar isso: 1 - https://api.bombcrypto.io/ccu 2 - Faça o ping para a api do websocket em que o bombcrypto esta rodando😁

Esse ccu de retorno saberia oq seria  ?

**Comment by s1k3ira** [comment]
> @s1k3ira @backslash-f Atualmente existem duas maneiras para você monitorar isso: 1 - https://api.bombcrypto.io/ccu 2 - Faça o ping para a api do websocket em que o bombcrypto esta rodando😁

alias ... tem a doc das apis deles ?

**Comment by s1k3ira** [comment]
O problema pessoal que o api.bombcrypto.io bate na cloudfare que sempre ta up ....

**Comment by carloskvasir** [comment]
Esse CCU é o numero de usuários ao mesmo tempo em cada servidor
