### ISSUE TITLE
Bot não clica em sign na metamask

### ISSUE THREAD

**Issue by kalleldf** [mpcabete/bombcrypto-bot#313]
Olá pessoal, o bot resolve o captcha mas quando a metamask abre o botão do mouse fica parado e não vai na opção de sign para dar continuidade no processo, já mudei o idioma para ver se resolvia mas não deu certo, vi um pessoal que falou que mudando algumas linhas do codigo conseguiu resolver o problema, em qual pasta fica esse arquivo para eu poder editar? e se alguém tiver a imagem do sign modificada em que conseguiu resolver o problema substituindo a outra na pasta, upa ela no tópico por favor, eu não consegui baixar a minha, ela fica como arquivo url.

**Comment by fx2016** [comment]
Opa...
1) teu navegador tá com zoom de 100% ?
2) tira um print da tela, recorta o botão no paint e substitui na pasta do jogo no C:

**Comment by kalleldf** [comment]
> Opa...
> 
> 1. teu navegador tá com zoom de 100% ?
> 2. tira um print da tela, recorta o botão no paint e substitui na pasta do jogo no C:

vou tentar aqui

**Comment by kalleldf** [comment]
> Opa...
> 
> 1. teu navegador tá com zoom de 100% ?
> 2. tira um print da tela, recorta o botão no paint e substitui na pasta do jogo no C:

deu certo mano, muito obrigado

**Comment by fx2016** [comment]
> > Opa...
> > 
> > 1. teu navegador tá com zoom de 100% ?
> > 2. tira um print da tela, recorta o botão no paint e substitui na pasta do jogo no C:
> 
> deu certo mano, muito obrigado

MARAVILHA BROTHER!!!! Fico feliz em ter ajudado, grande abraço!
