### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by MrAbacateDocinho** [mpcabete/bombcrypto-bot#314]
C:\BOMB>pip install -r requirements.txt
Fatal error in launcher: Unable to create process using '"C:\Program Files\Python310\python.exe"  "C:\Program Files\Python310\Scripts\pip.exe" install -r requirements.txt': O sistema nÒo pode encontrar o arquivo especificado.

como resolver isso aí?

**Comment by MrAbacateDocinho** [comment]
Tinha dado o problema com a versão 3.10 e baixei uma anterior, como nos tópicos, porém deu esse erro depois que fiz isso

**Comment by fx2016** [comment]
Eu faria o seguinte:

1) desinstalar o Python com Iobit Uninstaller
2) deletar a pasta no C onde vc colocou o bot
3) passar CCleaner
4) reinicia o pc
5) passar CClener novamente
6) baixar a versão python 3.9.9
7) baixar a última versão do bot

**Comment by WanaColacio** [comment]
C:\Users\Waná Colácio\Desktop\Bomb>pip install -r requirements.txt
Fatal error in launcher: Unable to create process using '"C:\Program Files\Python310\python.exe"  "C:\Program Files\Python310\Scripts\pip.exe" install -r requirements.txt': O sistema nÒo pode encontrar o arquivo especificado.


C:\Users\Waná Colácio\Desktop\Bomb>python -V
Python 3.9.9



aqui permaneceu esse error mesmo instalando versões anteriores

**Comment by mtmassa** [comment]
> C:\Users\Waná Colácio\Desktop\Bomb>pip install -r requirements.txt Fatal error in launcher: Unable to create process using '"C:\Program Files\Python310\python.exe" "C:\Program Files\Python310\Scripts\pip.exe" install -r requirements.txt': O sistema nÒo pode encontrar o arquivo especificado.
> 
> C:\Users\Waná Colácio\Desktop\Bomb>python -V Python 3.9.9
> 
> aqui permaneceu esse error mesmo instalando versões anteriores

O path do 3.10 para estar marcado no sistema, pois mesmo instalando o 3.9 ainda esta apontando pro caminho do 3.10.
vai ter que resolver isso senao nao vai funconar. Tenta instalar o 3.10 marcando a op;áo de PATH, depois desinstala novamente, desinstala todos, reinicia, passa o ccleaner e limpa o regrito, reinicia e tenta instalar o 3.9

**Comment by mtmassa** [comment]
> > C:\Users\Waná Colácio\Desktop\Bomb>pip install -r requirements.txt Fatal error in launcher: Unable to create process using '"C:\Program Files\Python310\python.exe" "C:\Program Files\Python310\Scripts\pip.exe" install -r requirements.txt': O sistema nÒo pode encontrar o arquivo especificado.
> > C:\Users\Waná Colácio\Desktop\Bomb>python -V Python 3.9.9
> > aqui permaneceu esse error mesmo instalando versões anteriores
> 
> O path do 3.10 para estar marcado no sistema, pois mesmo instalando o 3.9 ainda esta apontando pro caminho do 3.10. vai ter que resolver isso senao nao vai funconar. Tenta instalar o 3.10 marcando a op;áo de PATH, depois desinstala novamente, desinstala todos, reinicia, passa o ccleaner e limpa o regrito, reinicia e tenta instalar o 3.9

Voce tambem pode ir nas variáveis de ambiente do windows e editar o caminho do PYTHON.
