### ISSUE TITLE
Alguém que usou o macro entrou na lista de banidos?

### ISSUE THREAD

**Issue by JoelFreitas** [mpcabete/bombcrypto-bot#315]
Fala gente, houve um anúncio recente no Discord repassando que algumas contas foram banidas por uso de bot, mas na descrição era dito que foram banidas por SPEEDHACK, e o bot aqui usa só o macro pra automatizar cliques do mouse. 

Alguém que estava só usando o macro entrou na lista?

Segue a lista 👉🏻https://bit.ly/banned_accounts

**Comment by Yumiizera** [comment]
Pelo link compartilhado, foram apenas contas que usavam só o speed hack mesmo. 
Vide #222
