### ISSUE TITLE
BAN LIST

### ISSUE THREAD

**Issue by gsommerlatte** [mpcabete/bombcrypto-bot#316]
Alguém se encontrou nesse ban list?

https://docs.google.com/spreadsheets/d/1mDwlskTU65vDdX2R2abAzkj60vuu_G4-CZIJmQdvydE/htmlview?fbclid=IwAR165zj89slFe0R42z8YFSPUPjN8VhmtgSf3d8E6cnrFjPwD1NiaaqFCZg0&pru=AAABfeIrx30*s4DjKWXnkTXH0rvygVuE9g#gid=0

**Comment by FDNiisan** [comment]
Seria bacana fixar esse post ou criar um específico e ver se algum usuário do bot foi banido.

**Comment by backslash-f** [comment]
Quem tá nessa lista usou hack speed bot, que não é o caso desse repo.

<img width="403" alt="Screen Shot 2021-12-15 at 14 34 56" src="https://user-images.githubusercontent.com/664951/146196125-e11548e7-ff0e-4292-8df3-11d501e661bf.png">

**Comment by FDNiisan** [comment]
> Quem tá nessa lista usou hack speed bot, que não é o caso desse repo.
> 
> <img alt="Screen Shot 2021-12-15 at 14 34 56" width="403" src="https://user-images.githubusercontent.com/664951/146196125-e11548e7-ff0e-4292-8df3-11d501e661bf.png">

Isso sim..
Mas na postagem foi mencionado que foram banidas 11k de contas com uso hacks, bugs e apps de terceiros.

Seria interessante pra vermos o que pode ser melhorado

**Comment by Yumiizera** [comment]
> > Quem tá nessa lista usou hack speed bot, que não é o caso desse repo.
> > <img alt="Screen Shot 2021-12-15 at 14 34 56" width="403" src="https://user-images.githubusercontent.com/664951/146196125-e11548e7-ff0e-4292-8df3-11d501e661bf.png">
> 
> Isso sim.. Mas na postagem foi mencionado que foram banidas 11k de contas com uso hacks, bugs e apps de terceiros.
> 
> Seria interessante pra vermos o que pode ser melhorado

![image](https://user-images.githubusercontent.com/95440041/146200286-1d5aa01e-2d21-4cb9-9603-fc5eb80ecfbf.png)

"ANTERIORMENTE"

**Comment by Galinho90** [comment]
> Alguém se encontrou nesse ban list?
> 
> https://docs.google.com/spreadsheets/d/1mDwlskTU65vDdX2R2abAzkj60vuu_G4-CZIJmQdvydE/htmlview?fbclid=IwAR165zj89slFe0R42z8YFSPUPjN8VhmtgSf3d8E6cnrFjPwD1NiaaqFCZg0&pru=AAABfeIrx30*s4DjKWXnkTXH0rvygVuE9g#gid=0

Consultei minha carteira e não esta.

**Comment by marcelosore** [comment]
Acho que ai é mais quem abusou de bugs, scam, abriu o bomb em 2 maquinas simultaneamente ou alterou velocidade e stamina dos personagem com cheat engine. 
Aqui está safe também, não levei ban em nenhuma das contas. Acredito que nosso bot seja indetectável até o momento.

**Comment by abeltulio** [comment]
Eu não levei ban, ja conferi minha carteira e não esta na lista.

**Comment by espinozachristian** [comment]
> Acho que ai é mais quem abusou de bugs, scam, abriu o bomb em 2 maquinas simultaneamente ou alterou velocidade e stamina dos personagem com cheat engine. Aqui está safe também, não levei ban em nenhuma das contas. Acredito que nosso bot seja indetectável até o momento.

se eles quiser eles conseguem detectar, vai ser mto mais por padrão de comportamento quando esta online e afins, tem isso para validar campanha de marketing em sites, porem acho que nesse momento, só pela lista inicial dos 900 banidos ja deu uma dor de cabeça...nao sei se podem arriscar mais "BANS", até porque se limpar os BOT, acredito que o mercado vai quebrar inicialmente

**Comment by mtmassa** [comment]
> > Acho que ai é mais quem abusou de bugs, scam, abriu o bomb em 2 maquinas simultaneamente ou alterou velocidade e stamina dos personagem com cheat engine. Aqui está safe também, não levei ban em nenhuma das contas. Acredito que nosso bot seja indetectável até o momento.
> 
> se eles quiser eles conseguem detectar, vai ser mto mais por padrão de comportamento quando esta online e afins, tem isso para validar campanha de marketing em sites, porem acho que nesse momento, só pela lista inicial dos 900 banidos ja deu uma dor de cabeça...nao sei se podem arriscar mais "BANS", até porque se limpar os BOT, acredito que o mercado vai quebrar inicialmente

Vamos a realidade, eles nao tem processamento nem pra manter o servidor em bom estado, da onde vai tirar processamento pra analisar padrao, isso gasta mais processamento que o proprio jogo, esse tipo de ban vai extramamente dificil de ser implementado, e outra coisa, esse jogo sem bot nao rola, se cvomeçaram a complicar demais, ao abrir o marcado odo mundo poe as coisas pra vende e vai pra cars, planes, gards, ou qualquer um que de menos trabalho, afinal o jogo e bem bosta, todo mundo ta nessa pela grana, entao e so tempo de dar payback e pular fora, e ai o jogo morre. Nunca vi um servidor tao ruim pra alguma cooisa como desses caras...

**Comment by rodolphoacp** [comment]
Minha carteira está na lista, sendo que levei ban apenas uso o bot com o navegador brave...

**Comment by Galinho90** [comment]
> Minha carteira está na lista, sendo que levei ban apenas uso o bot com o navegador brave...
> 
> Entrei em contato com o suporte para ver se é removido o ban, mas basicamente bot + brave +teamviewer

Estrano que só tu levou ban com o Bot. Mais ninguém da comunidade levou Ban.

**Comment by itxtoledo** [comment]
usei o bot mas nao levei ban

**Comment by MathBogo** [comment]
> Minha carteira está na lista, sendo que levei ban apenas uso o bot com o navegador brave...
> 
> Entrei em contato com o suporte para ver se é removido o ban, mas basicamente bot + brave +teamviewer

Voce usou speedhack alguma vez antes? se sim... foi por isso, mesmo q nao usava mais, quem usou tomou ban.

**Comment by rodolphoacp** [comment]
> 

Somente faço uso do bot

**Comment by MathBogo** [comment]
> > 
> 
> Somente faço uso do bot

como voce entrou em contato com eles? nao estou conseguindo mandar mensagem no discord.

**Comment by thb623** [comment]
usei o bot 1 dia kkkk logo antes de sair a banwave e n deu nada e nem vou usar mais agr pq quando saiu anuncio de ban n passou nem wifi e tb n baniu até pq o bot nada mais é do que um bot ele n interfere em nada mas mesmo assim prefiro garantir mas agora quem usou ai um cheat engine pra alterar stamina speed tem q se fuder mesmo

**Comment by rodolphoacp** [comment]
> > > 
> > 
> > 
> > Somente faço uso do bot
> 
> como voce entrou em contato com eles? nao estou conseguindo mandar mensagem no discord.

Entrei pelo discord, e marquei um mod que me orientou a postar minha wallet em um tópico específico, irão avaliar e até sexta-feira dar um retorno

**Comment by Ricardonacif** [comment]
> > > > 
> > > 
> > > 
> > > Somente faço uso do bot
> > 
> > 
> > como voce entrou em contato com eles? nao estou conseguindo mandar mensagem no discord.
> 
> Entrei pelo discord, e marquei um mod que me orientou a postar minha wallet em um tópico específico, irão avaliar e até sexta-feira dar um retorno

Atualiza a gnt aqui dps

**Comment by Nydoehar** [comment]
Eu não acredito que eles se importem com o tipo de bot que usamos. Claro, eles iriam preferir que não usasemos, mas desde que não fazemos nada que prejudique o jogo, como speedhack e coisas do tipo, não acho que eles vão gastar recursos para pegar bots assim.

Junte a isso o fato de ser difícil descobrir um bot como esse que usamos e não acredito que ninguém aqui será banido.

**Comment by rodolphoacp** [comment]
> Atualiza a gnt aqui dps

Meu ban foi removido

**Comment by CmPedro** [comment]
> > Atualiza a gnt aqui dps
> 
> Meu ban foi removido

rapaz obrigado por atualizar, vou por o bot aqui e ir dormir kkkkkkkkkkkkkk não farmei direito uns dias
