### ISSUE TITLE
BombCrypto não conecta

### ISSUE THREAD

**Issue by pegchargue** [mpcabete/bombcrypto-bot#317]
Não sei se é só comigo... já tentei pelo celular e por 2 computadores e não está conectando desde ontem a tarde...
Já fazem uns 3 dias que está oscilando, mas ontem parou definitivo e fica dando o aviso
![erro](https://user-images.githubusercontent.com/95758730/146190020-32fbb2ad-b470-41df-b4cf-3c93a0ba0c9c.png)
(

**Comment by gsommerlatte** [comment]
manutenção até as 14 hrs

![image](https://user-images.githubusercontent.com/12755682/146190362-8d68c367-be1a-4b0f-bef6-7c41f77edf4d.png)

**Comment by pegchargue** [comment]
desde ontem???
Tá difícil jogar depois dessa mudança do capcha...

**Comment by Hermanyo** [comment]
Manutenção até as 14:00 PM UTC, por favor não crie issues com isso. 

Não crie issues que não fazem sentido com o repositório.

**Comment by pegchargue** [comment]
> Manutenção até as 14:00 PM, por favor não crie issues com isso.
> 
> Não crie issues que não fazem sentido com o repositório.

Não deu para entender o que escreveu...

**Comment by pegchargue** [comment]
> manutenção até as 14 hrs
> 
> ![image](https://user-images.githubusercontent.com/12755682/146190362-8d68c367-be1a-4b0f-bef6-7c41f77edf4d.png)

Obrigado!!!

**Comment by yassbeno** [comment]
Join bombcrypto discord server for announcements (https://discord.gg/bombcrypto) also mark this issue as closed

**Comment by Hermanyo** [comment]
> > Manutenção até as 14:00 PM, por favor não crie issues com isso.
> > Não crie issues que não fazem sentido com o repositório.
> 
> Não deu para entender o que escreveu...

Essa issue que você criou, não tem nada a ver com o bot. O bot é uma automação, e o que você postou não faz parte da alçada do bot.
