### ISSUE TITLE
Novo Captcha pós manutenção

### ISSUE THREAD

**Issue by espinozachristian** [mpcabete/bombcrypto-bot#318]
![image](https://user-images.githubusercontent.com/37847956/146197757-9e219d15-4a4a-4ce5-82c5-6961074f21dd.png)

bom antes de começarem a criar mil insues , sim vai ter novo captcha, vai levar tempo até burlar isso novamente e agradecemos a compreensão :D

**Comment by LoboNFT** [comment]
ja estamos trabalhando nisso, nada sera impossivel para nos

**Comment by thereis** [comment]
> ja estamos trabalhando nisso, nada sera impossivel para nos

estão trabalhando pra voce ne? kkkkkkkkk

**Comment by juniortopanotti** [comment]
Uma semana trabalhando para dar patch no captcha e um dia para eles trocaram. É isso ai! Hora que abrir o marketplace eu to caindo é fora! Impossível fazer dinheiro com time comum e eles constantemente dando nerf nas boxes, e não vem me falar que é FUD, porque se tu ta lendo isso aqui tu tem o mesmo problema que eu.

**Comment by PinnDeath6** [comment]
> Uma semana trabalhando para dar patch no captcha e um dia para eles trocaram. É isso ai! Hora que abrir o marketplace eu to caindo é fora! Impossível fazer dinheiro com time comum e eles constantemente dando nerf nas boxes, e não vem me falar que é FUD, porque se tu ta lendo isso aqui tu tem o mesmo problema que eu.

100sato!

**Comment by llFerreira** [comment]
> Uma semana trabalhando para dar patch no captcha e um dia para eles trocaram. É isso ai! Hora que abrir o marketplace eu to caindo é fora! Impossível fazer dinheiro com time comum e eles constantemente dando nerf nas boxes, e não vem me falar que é FUD, porque se tu ta lendo isso aqui tu tem o mesmo problema que eu.

Velho, eu tenho quase que 100% de certeza que eles tem todos os bots sendo vistoriados por alguem ADM/MOD. E quando ver que os bots ja tao capaz de resolver o captcha, eles vao e atualiza mudando. Isso faz o jogo segurar 33% das moedas por bastante tempo. E os nerfs ta tenso, eu tenho 5 comuns e fiz 40 ontem, 1 mes jogando fiz ontem. Tambem penso em sair, porém depois de tirar o payback, o resto é lucro

**Comment by LoboNFT** [comment]
fiquei sabendo que tem gente da comunidade deles aqui dentro, precisamos fazer um bot premium para eles nao saberem do nosso projeto, vamos trabalhar nisso

**Comment by sgsilva** [comment]
o que adianta ser premiu eles vão lá e pagam! mas o trabalho do povo aqui é bom, acho que se forem reclamar estão reclamando de barriga cheia!

**Comment by Yumiizera** [comment]
> fiquei sabendo que tem gente da comunidade deles aqui dentro, precisamos fazer um bot premium para eles nao saberem do nosso projeto, vamos trabalhar nisso

"Fiquei sabendo" não quer dizer que é informação confiável.
@mpcabete já disse que o bot será público e queira ou não, será gratuito.

**Comment by PinnDeath6** [comment]
> > fiquei sabendo que tem gente da comunidade deles aqui dentro, precisamos fazer um bot premium para eles nao saberem do nosso projeto, vamos trabalhar nisso
> 
> "Fiquei sabendo" não quer dizer que é informação confiável. @mpcabete já disse que o bot será público e queira ou não, será gratuito.

Sugiro vocês usuários, assim como eu, quando tirar o roi ou até mesmo antes, ajudar com donates e tips no paypal e na wallet do desenvolvedor. Para assim mantermos o projeto gratuito a todos, querendo ou não isso é um projeto social que ajuda muita gente a dormir em paz

**Comment by juniortopanotti** [comment]
É OBVIO que os caras monitoram os BOTS, sem sombra de dúvida! Eles são programadores, assim como a maioria de todos aqui. Se eles querem eliminar esse problema eles tem que ficar de olho no que tem no mercado para saber o que fazer. E sim, se sair um patch corrigindo isso vai dar uma semana e vai aparecer outro assim por diante.


> > Uma semana trabalhando para dar patch no captcha e um dia para eles trocaram. É isso ai! Hora que abrir o marketplace eu to caindo é fora! Impossível fazer dinheiro com time comum e eles constantemente dando nerf nas boxes, e não vem me falar que é FUD, porque se tu ta lendo isso aqui tu tem o mesmo problema que eu.
> 
> Velho, eu tenho quase que 100% de certeza que eles tem todos os bots sendo monitorados por alguem ADM/MOD. E quando ver que os bots ja tao capaz de resolver o captcha, eles vao e atualiza mudando. Isso faz o jogo segurar 33% das moedas por bastante tempo. E os nerfs ta tenso, eu tenho 5 comuns e fiz 40 ontem, 1 mes jogando fiz ontem. Tambem penso em sair, porém depois de tirar o payback, o resto é lucro

**Comment by sgsilva** [comment]
> > Uma semana trabalhando para dar patch no captcha e um dia para eles trocaram. É isso ai! Hora que abrir o marketplace eu to caindo é fora! Impossível fazer dinheiro com time comum e eles constantemente dando nerf nas boxes, e não vem me falar que é FUD, porque se tu ta lendo isso aqui tu tem o mesmo problema que eu.
> 
> Velho, eu tenho quase que 100% de certeza que eles tem todos os bots sendo monitorados por alguem ADM/MOD. E quando ver que os bots ja tao capaz de resolver o captcha, eles vao e atualiza mudando. Isso faz o jogo segurar 33% das moedas por bastante tempo. E os nerfs ta tenso, eu tenho 5 comuns e fiz 40 ontem, 1 mes jogando fiz ontem. Tambem penso em sair, porém depois de tirar o payback, o resto é lucro

se você só tem 5 bonecos comum, sugiro estudar mais pra ver as coisas! máximo é 15 acho que vc deveria ter 15 na conta! aumentaria sua produção!

**Comment by kimcavalcanti** [comment]
Logicamente falando esse captcha é mais fácil que o outro para fazer o bot resolver

**Comment by Yumiizera** [comment]
> Logicamente falando esse captcha é mais fácil que o outro para fazer o bot resolver

É possível que eles tenham colocado algo nessa manutenção nos arquivos pra monitoramento?

**Comment by Yanrs** [comment]
> fiquei sabendo que tem gente da comunidade deles aqui dentro, precisamos fazer um bot premium para eles não saberem do nosso projeto, vamos trabalhar nisso

Não é porque estamos jogando joguinho de ganhar dinheiro que tudo tem de ser na base do pago. Lembre se se você esta aqui é justamente pelo projeto ser publico. 
Sobre estar "trabalhando nisso", pode compartilhar um pouco mais sobre?? porque até outra semana eu estava te respondendo em issue de como fazer o básico do básico no MacOSx. Não é querendo diminuir nem nada, mas to curioso com esses desenvolvimentos e times ocultos

**Comment by rodrigobg** [comment]
Galera a verdade é que eles sabem do bot que tem aqui no GitHub, e já tem solução para os captchas. Eu vou jogar até tirar o dinheiro que investi e vou cair fora.

**Comment by ZeddEn** [comment]
This one is easy to solve actually:
- Moving the mouse over the screen to take screenshot then merge them
- Grey our the image or remove the black letters
- Analyse the white font which is the same one we were using
Then compare using the existing script

**Comment by juniortopanotti** [comment]
> This one is easy to solve actually:
> 
> * Moving the mouse over the screen to take screenshot then merge them
> * Grey our the image or remove the black letters
> * Analyse the white font which is the same one we were using
>   Then compare using the existing script

Yes i thought same, i'm actually doing a python script to do this first, when i'm done i post here the results and code.

**Comment by sgsilva** [comment]
olha os homi ae! hahahahahahaha

**Comment by pegchargue** [comment]
Teve um camarada esses dias que configurou para ele ir fazendo testes até acertar... como configuro para ir testando também???

**Comment by juniortopanotti** [comment]
> Teve um camarada esses dias que configurou para ele ir fazendo testes até acertar... como configuro para ir testando também???

Foi eu, porém dessa vez a cada erro o número de alternativas aumenta até 10 ficando muito demorado para acertar. Para eles terem feito essa alteração eles sabem que tem bot na tentativa e erro e pode ser que agora eles estejam registrando isso.

**Comment by pegchargue** [comment]
> > Teve um camarada esses dias que configurou para ele ir fazendo testes até acertar... como configuro para ir testando também???
> 
> Foi eu, porém dessa vez a cada erro o número de alternativas aumenta até 10 ficando muito demorado para acertar. Para eles terem feito essa alteração eles sabem que tem bot na tentativa e erro e pode ser que agora eles estejam registrando isso.

Valeu pela atenção!!!

**Comment by PinnDeath6** [comment]
> Se eles monitorassem os bots, eles iriam banir e não ficar trocando captcha...

Cara, ele quis dizer monitorando como se os devs do jogo estivessem infiltrados aqui no git hub lendo tudo que escrevemos e vendo as novidades do bot programado pela comunidade (sem sombras de dúvidas afinal, tambem são devs). Por aqui dá pra saber quem são os usuários mas não quem é quem no jogo.

**Comment by MathBogo** [comment]
Galera, minhas duas contas foram banidas. Mas nao foi por conta do uso desse bot. Usei speedhack mas ja faz semans... até porque hoje em dia nem funciona mais o cheat engine. Achei puta sacanagem isso... era mais facil terem banido minhas contas antes entao, agora que nem estava mais usando eles fazem isso. Todo risco tem suas consequencias. Agora é esperar o jogo voltar pra ver se consigo ter acesso a pelo menos minhas 50bcoin que ficaram na conta, mas acho meio impossivel isso por conta que ja foi banida.

**Comment by rodrigobg** [comment]
A guerra "DEVS" contra "DEVS" kkkkk estou começando a gostar dessa porra kkkkkk
Pretendo sair do game em breve, só quero tirar meu investimento e cair fora.

**Comment by PinnDeath6** [comment]
> Galera, minhas duas contas foram banidas. Mas nao foi por conta do uso desse bot. Usei speedhack mas ja faz semans... até porque hoje em dia nem funciona mais o cheat engine. Achei puta sacanagem isso... era mais facil terem banido minhas contas antes entao, agora que nem estava mais usando eles fazem isso. Todo risco tem suas consequencias. Agora é esperar o jogo voltar pra ver se consigo ter acesso a pelo menos minhas 50bcoin que ficaram na conta, mas acho meio impossivel isso por conta que ja foi banida.

Oloco mano, mas cheat engine é muita loucura mesmo! Modifica e permite que os devs consultem os registros do jogo, diferente da automação python.

**Comment by MathBogo** [comment]
> > Galera, minhas duas contas foram banidas. Mas nao foi por conta do uso desse bot. Usei speedhack mas ja faz semans... até porque hoje em dia nem funciona mais o cheat engine. Achei puta sacanagem isso... era mais facil terem banido minhas contas antes entao, agora que nem estava mais usando eles fazem isso. Todo risco tem suas consequencias. Agora é esperar o jogo voltar pra ver se consigo ter acesso a pelo menos minhas 50bcoin que ficaram na conta, mas acho meio impossivel isso por conta que ja foi banida.
> 
> Oloco mano, mas cheat engine é muita loucura mesmo! Modifica e permite que os devs consultem os registros do jogo, diferente da automação python.

Mas é sacanagem os caras banirem agora... acredito que fizeram isso so pra "mostrarem" que estao empenhados com o jogo apos dias que vem tendo manutençao. Foi uma forma de mostrar serviço isso... perdi uma conta com 15 comum que rendia 3 bcoin por dia e outra conta com 2 super raro que rendia 7bcoin por dia.

**Comment by vini-sousa** [comment]
> > Se eles monitorassem os bots, eles iriam banir e não ficar trocando captcha...
> 
> Cara, ele quis dizer monitorando como se os devs do jogo estivessem infiltrados aqui no git hub lendo tudo que escrevemos e vendo as novidades do bot programado pela comunidade (sem sombras de dúvidas afinal, tambem são devs). Por aqui dá pra saber quem são os usuários mas não quem é quem no jogo.

Isso eu concordo demais...até já falei isso aqui e o pessoal é inocente e acha que não teme nada a ver...Tem gente de dentro aqui e só repassando aos devs

**Comment by PinnDeath6** [comment]
Voltando pro captcha, está fácil de resolver mesmo. Basta isolar o reconhecimento de todos os números e dps utilizar ocr pra utilizar a opção correta.

**Comment by Pedronet5** [comment]
O fato é que as atualizações que mudam apenas o capcha é pelo simples fato que a IA é meio dificil de saber se realmente é um bot, então o jeito é dificultar e quebrar o bot atual que dessa forma vão precisar de mais tempo pra voltar e nisso eles já vão fazendo outro.

O unico jeito de quebrar de vez é usar o captcha do google que gera imagens aleatorias (Nunca que alguém consegue saber todas as imagens)

**Comment by rubenIng93** [comment]
Hey! I made a script that produces the following image:
![test](https://user-images.githubusercontent.com/48275113/146225945-8a0bd203-4861-41b0-a8e2-9fdb30ab6973.png)
Let me know if this could be useful.

**Comment by mtmassa** [comment]
> Hey! I made a script that produces the following image: ![test](https://user-images.githubusercontent.com/48275113/146225945-8a0bd203-4861-41b0-a8e2-9fdb30ab6973.png) Let me know if this could be useful.

e a solução logica ja esta pronta kkkk. @mpcabete

**Comment by kalleldf** [comment]
Vou só recuperar o investimento e vou vazar desse game, servidor fica mais off do que on, cada atualização nova os devs colocam mais dificuldade no jogo, tenta fazer essa captcha novo pelo teamviewer é um inferno.

**Comment by voodee** [comment]
https://www.youtube.com/watch?v=q6P3fPHquBk

**Comment by cmxavier** [comment]
Captcha will appear every 60 minutes.
Idle has been removed

**Comment by Alt4s** [comment]
O novo captcha é sim mais difícil que todos os outros

**Comment by PinnDeath6** [comment]
> Basta isolar o reconhecimento de todos os números e dps utilizar ocr pra utilizar a opção correta.

Por?

**Comment by Lucao-pl** [comment]
https://user-images.githubusercontent.com/96198176/146232010-84dc1930-5954-45d0-8ada-cc392cea8092.mp4

Mandaram em um grupo aqui

**Comment by trinitro2** [comment]
> Hey! I made a script that produces the following image: ![test](https://user-images.githubusercontent.com/48275113/146225945-8a0bd203-4861-41b0-a8e2-9fdb30ab6973.png) Let me know if this could be useful.

script please =)

**Comment by gabrielwjesus** [comment]
> VID-20211215-WA0026.mp4
> 
> Mandaram em um grupo aqui

não parece verifico, é mto perfeito o sistema

**Comment by juniortopanotti** [comment]
> > VID-20211215-WA0026.mp4
> > Mandaram em um grupo aqui
> 
> não parece verifico, é mto perfeito o sistema

É veridico sim, esse captcha parece ser dificil mas é mais fácil que o último! 
![image](https://user-images.githubusercontent.com/19753097/146232956-9b193810-fb3e-4504-9bc4-f01ff16358d9.png)
Isso é o que eu já consegui até agora, mais uns ajustes ai contribuo aqui.

**Comment by gabrielwjesus** [comment]
> > > VID-20211215-WA0026.mp4
> > > Mandaram em um grupo aqui
> > 
> > 
> > não parece verifico, é mto perfeito o sistema
> 
> É veridico sim, esse captcha parece ser dificil mas é mais fácil que o último! ![image](https://user-images.githubusercontent.com/19753097/146232956-9b193810-fb3e-4504-9bc4-f01ff16358d9.png) Isso é o que eu já consegui até agora, mais uns ajustes ai contribuo aqui.

Top ein

**Comment by Galinho90** [comment]
> > > > VID-20211215-WA0026.mp4
> > > > Mandaram em um grupo aqui
> > > 
> > > 
> > > não parece verifico, é mto perfeito o sistema
> > 
> > 
> > É veridico sim, esse captcha parece ser dificil mas é mais fácil que o último! ![image](https://user-images.githubusercontent.com/19753097/146232956-9b193810-fb3e-4504-9bc4-f01ff16358d9.png) Isso é o que eu já consegui até agora, mais uns ajustes ai contribuo aqui.
> 
> o ultimo o bot nao sei como lia. eu nao conseguia kkkkk

Top, Parabéns mano !

**Comment by mtmassa** [comment]
nao sei como e a vida do mpcabete, mas parece que esse vai sair o solve em um dia kkk

**Comment by ZeddEn** [comment]
Hello, they seem to have changed the font of Connect to Wallet button so we need to update with a new screenshot. That's very cute from them, hoping this would stop the bot haha

**Comment by Yumiizera** [comment]
> Hello, they seem to have changed the font of Connect to Wallet button so we need to update with a new screenshot. That's very cute from them, hoping this would stop the bot haha

Foco deles é parar o bot ".exe" que tá tendo. Esse aqui por prints não estão tão preocupados pois não muda com a engine do game.

**Comment by davidgrunge** [comment]
eu já me decidi após o lançamento do Market estou pulando fora do projeto vou vender meus 4 super raros 1 épico e 4 raros vou pegar a grana e enfiar em outro projeto sólido, to de saco cheio de ficar sem farmar toda hora que cai o servidor

**Comment by thiago-molive** [comment]
galera ta top nesse grupo, ja vi que tão empenhados e ja têm até alguma solução então n vou gastar esforço desnecessário. desejo boa sorte ^^

**Comment by espinozachristian** [comment]
> > > VID-20211215-WA0026.mp4
> > > Mandaram em um grupo aqui
> > 
> > 
> > não parece verifico, é mto perfeito o sistema
> 
> É veridico sim, esse captcha parece ser dificil mas é mais fácil que o último! ![image](https://user-images.githubusercontent.com/19753097/146232956-9b193810-fb3e-4504-9bc4-f01ff16358d9.png)
> 
> Isso é o que eu já consegui até agora, mais uns ajustes ai contribuo aqui.

consigo contribuir man? trampo com isso, nao sei como esta sua logica e desenvolvimento mas agora saindo do trampo as 17 ja consigo da uma força :)

**Comment by gabrielwjesus** [comment]
> > Hello, they seem to have changed the font of Connect to Wallet button so we need to update with a new screenshot. That's very cute from them, hoping this would stop the bot haha
> 


concordo totalmente. Existem mtos

> > > > VID-20211215-WA0026.mp4
> > > > Mandaram em um grupo aqui
> > > 
> > > 
> > > não parece verifico, é mto perfeito o sistema
> > 
> > 
> > É veridico sim, esse captcha parece ser dificil mas é mais fácil que o último! ![image](https://user-images.githubusercontent.com/19753097/146232956-9b193810-fb3e-4504-9bc4-f01ff16358d9.png)
> > Isso é o que eu já consegui até agora, mais uns ajustes ai contribuo aqui.
> 
> consigo contribuir man? trampo com isso, nao sei como esta sua logica e desenvolvimento mas agora saindo do trampo as 17 ja consigo da uma força :)

esse jogo me fez ter interesse na parte de imagens com python kkk ate agora só fazia pyQT5, Network, Security kkkk e algumas automações com selenium kkkk Mas isso? isso de imagens é loucura. Quero aprender.

**Comment by korokoroinu** [comment]
> > > VID-20211215-WA0026.mp4
> > > Mandaram em um grupo aqui
> > 
> > 
> > não parece verifico, é mto perfeito o sistema
> 
> É veridico sim, esse captcha parece ser dificil mas é mais fácil que o último! ![image](https://user-images.githubusercontent.com/19753097/146232956-9b193810-fb3e-4504-9bc4-f01ff16358d9.png)
> 
> Isso é o que eu já consegui até agora, mais uns ajustes ai contribuo aqui.

tratando a img da pra deixar mais nitido 
![captcha2](https://user-images.githubusercontent.com/96199080/146251619-45a4c368-aa23-4c11-b01e-f0edd177aae5.png)

**Comment by juniortopanotti** [comment]
https://user-images.githubusercontent.com/19753097/146250205-22630b1d-4962-4349-b03a-ba4a71a40f29.mp4


Parte mais difícil pronta! Precisa ser feito alguns ajustes finos mas no geral já da pra utilizar, fico no aguardo do @mpcabete para passar a implementação e continuar com o resto.

**Comment by guborges** [comment]
> 2021-12-15.16-11-33.mp4 
> Parte mais difícil pronta! Precisa ser feito alguns ajustes finos mas no geral já da pra utilizar, fico no aguardo do @mpcabete para passar a implementação e continuar com o resto.

Qual a biblioteca pra fazer essa brincadeira ? :D

**Comment by rodrigobragamg** [comment]
Rapaz, esses anti-captchas na verdade agora ficaram mais difícil pra humanos mesmo (a máquina sempre será superior), daqui a pouco ninguém consegue logar. Coitado de quem for jogar tomando umas, hehe.

**Comment by Diegoarend** [comment]
os caras não entenderam ainda que essas quedas no server é o que mantém a moeda valorizada kkkk 
é a queima de moedas dos caras!

**Comment by gabrielwjesus** [comment]
> 2021-12-15.16-11-33.mp4
> 
> Parte mais difícil pronta! Precisa ser feito alguns ajustes finos mas no geral já da pra utilizar, fico no aguardo do @mpcabete para passar a implementação e continuar com o resto.

mas ainda não está atualizado no repositorio, certo?

**Comment by joaovictor7** [comment]
> 2021-12-15.16-11-33.mp4 
> Parte mais difícil pronta! Precisa ser feito alguns ajustes finos mas no geral já da pra utilizar, fico no aguardo do @mpcabete para passar a implementação e continuar com o resto.

o bot ainda não conseguiu resolver nenhum captcha com esse novo metódo aqui ainda

**Comment by n0k3zin** [comment]
Ele parece ler mas não encosta no slider, falta atualizar as imagens pelo visto só foi atualizado o movimento do captcha,

**Comment by joaovictor7** [comment]
> Ele parece ler mas não encosta no slider, falta atualizar as imagens pelo visto só foi atualizado o movimento do captcha,

aqui ele entra em loop lendo o captcha

**Comment by rodrigobragamg** [comment]
O mpc deixou bem claro que a atualização faz somente isto aqui: "reveal digits"
Ou seja, revela os dígitos.

**Comment by Hermanyo** [comment]
> 2021-12-15.16-11-33.mp4
> 
> Parte mais difícil pronta! Precisa ser feito alguns ajustes finos mas no geral já da pra utilizar, fico no aguardo do @mpcabete para passar a implementação e continuar com o resto.

Eu fiz uma solução mas demorada, na mão.

Quais fundamentos você usou?

**Comment by trinitro2** [comment]
so eu que acho que essas atualizaçoes e queda de servidor está matando o jogo? está gerando incerteza no projeto. o projeto era tao bom...ai colocaram anti bot

**Comment by cmxavier** [comment]
> so eu que acho que essas atualizaçoes e queda de servidor está matando o jogo? está gerando incerteza no projeto. o projeto era tao bom...ai colocaram anti bot

Lamento dizer, mas está assim desde de o primeiro dia que foi lançado o jogo, antes até existiam erros piores, era muito difícil logar no servidor nas primeiras semanas e mesmo assim o projeto se levantou...

**Comment by fx2016** [comment]
O captcha faz parte, mas essa coisa de tirar o servidor do ar, voltar horrível, lento, acesso péssimo, isso sim está matando o jogo

**Comment by thiago-molive** [comment]
> O captcha faz parte, mas essa coisa de tirar o servidor do ar, voltar horrível, lento, acesso péssimo, isso sim está matando o jogo

Enquanto tiver lucrativo, não importam os erros ngm sai até sugar a moeda toda

**Comment by fx2016** [comment]
> > O captcha faz parte, mas essa coisa de tirar o servidor do ar, voltar horrível, lento, acesso péssimo, isso sim está matando o jogo
> 
> Enquanto tiver lucrativo, não importam os erros ngm sai até sugar a moeda toda

Concordo, mas assim que puder vender os heroes, tô vazando, tá louco pqp

**Comment by luizxd0** [comment]
minha opiniao, a moeda esta caindo por conta da dificuldade de deixar o servidor on e a dificuldade imposta por esses captchas....
galera que usa multi account e necessita de bot acaba que desanima.
Em vez deles focarem em captcha, deveriam focar em manter o server on e soltar logo o sistema de stake vip, dessa forma a galera em vez de usar bot, iria fazer o stake pra ter os beneficios, a moeda so iria subir dessa forma. Posso estar errado, mas penso assim

**Comment by thiago-molive** [comment]
> minha opiniao, a moeda esta caindo por conta da dificuldade de deixar o servidor on e a dificuldade imposta por esses captchas.... galera que usa multi account e necessita de bot acaba que desanima. Em vez deles focarem em captcha, deveriam focar em manter o server on e soltar logo o sistema de stake vip, dessa forma a galera em vez de usar bot, iria fazer o stake pra ter os beneficios, a moeda so iria subir dessa forma. Posso estar errado, mas penso assim

Rapaz eu te falo q eu fiquei indignado em saber que pediram prazo pra trocar de servidor e na vdd tavam trabalhando em captcha

**Comment by Yumiizera** [comment]
> 

Conta a fofoca toda ai kkkk

**Comment by Yumiizera** [comment]
> > minha opiniao, a moeda esta caindo por conta da dificuldade de deixar o servidor on e a dificuldade imposta por esses captchas.... galera que usa multi account e necessita de bot acaba que desanima. Em vez deles focarem em captcha, deveriam focar em manter o server on e soltar logo o sistema de stake vip, dessa forma a galera em vez de usar bot, iria fazer o stake pra ter os beneficios, a moeda so iria subir dessa forma. Posso estar errado, mas penso assim
> 
> Rapaz eu te falo q eu fiquei indignado em saber que pediram prazo pra trocar de servidor e na vdd tavam trabalhando em captcha

Conta a fofoca toda ai kkkk

**Comment by luizxd0** [comment]
> > minha opiniao, a moeda esta caindo por conta da dificuldade de deixar o servidor on e a dificuldade imposta por esses captchas.... galera que usa multi account e necessita de bot acaba que desanima. Em vez deles focarem em captcha, deveriam focar em manter o server on e soltar logo o sistema de stake vip, dessa forma a galera em vez de usar bot, iria fazer o stake pra ter os beneficios, a moeda so iria subir dessa forma. Posso estar errado, mas penso assim
> 
> Rapaz eu te falo q eu fiquei indignado em saber que pediram prazo pra trocar de servidor e na vdd tavam trabalhando em captcha

eu acredito que se eles colocam o stake vip, reduziria os bots, o stake vip parece ser bem interessante. Mas os caras tao trabalhando em captcha e servidor continua ruim, ai fica complicado. Quem manteve a moeda alta foram os multi acc bot....
Eles tao dando um tiro no pe sem saber

**Comment by fguide** [comment]
Infelizemente está bem evidente agora (sempre esteve) que eles não estão ainda bem preparados em termos de infraestrutura, fazem alterações e correções em produção, basicamente não tem distribuição de acesso por região, etc, e por isso temos quedas de preço em um momento que o restante do mercado está subindo.

Não vejo motivo para desespero entretanto, como já disseram a estabilidade do jogo é complicada desde o lançamento porém vem melhorando, não podemos esquecer que o projeto em si tem 2 meses.

Voltando ao tema do captcha, parabéns ao pessoal que consegue dedicar tempo para encontrar soluções rapidamente!

**Comment by ZeddEn** [comment]
Last commit has the bot working :)

**Comment by gabrielwjesus** [comment]
> Last commit has the bot working :)

Didn't work here. Tried many times but this module is not getting all numbers rights.

**Comment by Nydoehar** [comment]
> > > > O captcha faz parte, mas essa coisa de tirar o servidor do ar, voltar horrível, lento, acesso péssimo, isso sim está matando o jogo
> > > 
> > > 
> > > Enquanto tiver lucrativo, não importam os erros ngm sai até sugar a moeda toda
> > 
> > 
> > Concordo, mas assim que puder vender os heroes, tô vazando, tá louco pqp
> 
> eu tambem. assim que abrir eu vendo e vou para outro projeto

As an investment, Bomb Crypto kind of suck: 

It's 24/7: 
The goddamn servers are offline 40% of the time.
Dev's communication sucks (like increase chest hp and just say something when everyone are already pissed).

The money is good but there are other games that pay almost as well with a fraction of the trouble.

When I have my ROI I gonna donate at least 10 bcoins to this project and move on.

**Comment by fx2016** [comment]
> > > > > O captcha faz parte, mas essa coisa de tirar o servidor do ar, voltar horrível, lento, acesso péssimo, isso sim está matando o jogo
> > > > 
> > > > 
> > > > Enquanto tiver lucrativo, não importam os erros ngm sai até sugar a moeda toda
> > > 
> > > 
> > > Concordo, mas assim que puder vender os heroes, tô vazando, tá louco pqp
> > 
> > 
> > eu tambem. assim que abrir eu vendo e vou para outro projeto
> 
> As an investment, Bomb Crypto kind of suck:
> 
> It's 24/7: The goddamn servers are offline 40% of the time. Dev's communication sucks (like increase chest hp and just say something when everyone are already pissed).
> 
> The money is good but there are other games that pay almost as well with a fraction of the trouble.
> 
> When I have my ROI I gonna donate at least 10 bcoins to this project and move on.

mee too

**Comment by espinozachristian** [comment]
> > Last commit has the bot working :)
> 
> Didn't work here. Tried many times but this module is not getting all numbers rights.

ele ainda irá otimizar...calma...

**Comment by espinozachristian** [comment]
Estarei fechando o inssue, rendeu um bom papo já

**Comment by kerferber** [comment]
@espinozachristian @juniortopanotti 

Boa noite,
Estou tentando reconhecer o saldo em Bcoins e transformar para texto para enviar por telegram porém não estou conseguindo com OCR.

Será que, por gentileza, poderiam dar uma olhada neste issue #627 e se possível me ajudar?
Desde já agradeço
