### ISSUE TITLE
DOAÇÃO PARA O PROJETO

### ISSUE THREAD

**Issue by Galinho90** [mpcabete/bombcrypto-bot#320]
**1. ENGLISH**
- Guys we know that the bot is made completely free of charge, so we can't forget to make donations, even if it's 1$, because they put a lot of effort into keeping the bot up to date faster. we are going to contribute, the portfolio is in the project description. LET'S SUPPORT THE DEVS._
-
**2. PORTGUÊS**
- Galera sabemos que o bot é feito de forma totalmente gratuita, então não podemos esquecer de fazer doações, nem que seja de 1$, pois eles se esforçam muito em manter o bot sempre atualizado de forma mais rápida. vamos contribuir, a carteira se encontra na descrição do projeto. VAMOS APOIAR OS DEVS._

**Comment by enthusiast33** [comment]
O link do paypal só permite doação em dólar e tá bugando meu paypal! Coloca um link Brasileiro também!

**Comment by PinnDeath6** [comment]
Uma chave pix ajudaria demais tb

**Comment by rmarquesa** [comment]
Galera os devs devem estar de olho nesse repo... Quase nem durou o solveCaptcha... Alguma ideia, criar um grupo pra ver o código...

**Comment by espinozachristian** [comment]
> Galera os devs devem estar de olho nesse repo... Quase nem durou o solveCaptcha... Alguma ideia, criar um grupo pra ver o código...

nao existe somente esse BOT ,há outros N e muitos outros são pagos...
mas voltando ao assunto original, realmente galera quem tirar seu ROI ou nao for pesar vmos contribuir! se não for com codigo e programação que seja com algo para o pessoal 🗡️ 
comunidade unida vai mais longe

**Comment by nasiloski** [comment]
Coloquem uma carteira de USDT/BNB q é moleza doar

**Comment by Lucao-pl** [comment]
> Coloquem uma carteira de USDT / BNB q é moleza doar

Já tem a carteira amigo na página inicial do bot
![Screenshot_20211215-150824_Chrome](https://user-images.githubusercontent.com/96198176/146241577-fa08504c-8019-4e87-a8be-a6140dbc0b61.jpg)

**Comment by Galinho90** [comment]
> Coloquem uma carteira de USDT/BNB q é moleza doar

Galera tem uma carteira na descrição do  código, a carteira é SMART CHAIN.

**Comment by TinasDG** [comment]
Não tem nenhuma chave pix p poder fazer a doação n?

**Comment by jeanvetorello** [comment]
no readme tem a carteira só pegar metamask pode transferir bnb busd ou bcoin e transferir para essa carteira.

**Comment by TinasDG** [comment]
doei la

**Comment by mpcabete** [comment]
o pessoal, vlw pela sugestao, vou colocar a chave pix tm!

**Comment by Alt4s** [comment]
Eu já doei 10 dólares e meu irmão também doou 10 dólares a uns dias at´ras

**Comment by jhones01** [comment]
Obrigado pelo empenho todo esse tempo.


![msg5090665586-740](https://user-images.githubusercontent.com/11988230/146278627-5428ba6a-f0b4-4174-88ab-67ea64471132.jpg)

**Comment by MochilaEstilosa** [comment]
![9D5B1C67-8362-4729-9151-BB3934EC6A81](https://user-images.githubusercontent.com/95733800/146287983-61105ffc-4e57-408f-a59a-ccdeb11cde7c.png)

bora doar galera, estão fazendo um trabalho absurdo!

**Comment by jhones01** [comment]
Up
