### ISSUE TITLE
multiplas contas

### ISSUE THREAD

**Issue by coradini1** [mpcabete/bombcrypto-bot#321]
alguem com mais de 2 contas conseguiu se conectar? ate agora to tentando entrar e so consegui entrar com 2 das 5 contas que eu tenho. Mais alguem?

**Comment by fguide** [comment]
Leia o comunicado oficial, estáo com server cheio ainda, por isso a dificuldade. POr enquanto nao tem nenhum deny por IP x contas.

**Comment by coradini1** [comment]
> Leia o comunicado oficial, estáo com server cheio ainda, por isso a dificuldade. POr enquanto nao tem nenhum deny por IP x contas.

tomei ban do discord ai n consigo ver nada kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
