### ISSUE TITLE
[off topic] alguém está conseguindo logar? 

### ISSUE THREAD

**Issue by kerferber** [mpcabete/bombcrypto-bot#322]
Alguém está conseguindo logar?
Aqui não passa dos 50%

Já troquei de navegador, limpei cache, roteei internet do celular, e nada...

Mas no meu instagram tem gente jogando....

**Comment by kalleldf** [comment]
**a empresa limitou o servidor para um determinado numero de pessoas**, na moral que bando de filho da puta esses devs desse jogo.

**Comment by kerferber** [comment]
Realmente, parece está piorando em vez de melhorar

**Comment by coradini1** [comment]
mudaram a host de AWS pra hostgator pqp

**Comment by joaovictor7** [comment]
to desde ontem a noite sem conseguir logar

**Comment by Galinho90** [comment]
O meu fica dando esse erro: 

![6065B81F-76FC-43CF-BB5D-62FD5FD7B07B](https://user-images.githubusercontent.com/95733162/146261461-32a4bc76-111a-46f5-b8a9-88be46bc4bea.jpeg)

**Comment by fernandoamvj** [comment]
> O meu fica dando esse erro:
> 
> ![6065B81F-76FC-43CF-BB5D-62FD5FD7B07B](https://user-images.githubusercontent.com/95733162/146261461-32a4bc76-111a-46f5-b8a9-88be46bc4bea.jpeg)

o meu tbm

**Comment by espinozachristian** [comment]
> **a empresa limitou o servidor para um determinado numero de pessoas**, na moral que bando de filho da puta esses devs desse jogo.

por atitudes como essa que ainda me da vontade de continuar com o bot :)

**Comment by kerferber** [comment]
ainda sem êxito. mas pelo visto é geral, rsrs. obrigado
