### ISSUE TITLE
Ant captcha atualizado 

### ISSUE THREAD

**Issue by JoseAntonio1123** [mpcabete/bombcrypto-bot#323]
https://www.youtube.com/watch?v=KamdC3fLzlE será que é verdade rapaziada ??  discord do mano do video Jean Carlos#1467 tenho minhas duvidas

**Comment by mfsousa** [comment]
o bot é verdade, eu tenho, mas esse não faz parte do projeto. Parece-me scam fazendo-se passar pelos devs do projecto, tenho cuidado

**Comment by mfsousa** [comment]
Confirmado, é scam. Falei com os devs do bot e eles não reconhecem esse Jean Carlos#1467

O bot "Bomb Farm" existe, mas não é esse ai não.

**Comment by Nucito** [comment]
https://user-images.githubusercontent.com/19374522/146275314-fb9ac535-7fa2-435a-8f3a-eca281775e69.mp4

Reconhecimento Completo😁

**Comment by Ricardonacif** [comment]
> @Cartman.6666.mp4 
> Reconhecimento Completo😁

Boa! Mandou bem! Vc vai compartilhar no seu repo la?

**Comment by Ricardonacif** [comment]
> 

Boa! Mandou bem! Vc vai compartilhar no seu repo la? Se sim vou te mandar uns bcoins :D
