### ISSUE TITLE
[OFF TOPIC] Programação | Cursos

### ISSUE THREAD

**Issue by cardic1** [mpcabete/bombcrypto-bot#325]
Pessoal, realmente estou empolgado em ver como os dev estao dando duro para solucionar esse problema para a comunidade.

Gostaria de saber se os dev ou nucito, ou outro expert.
Pode mostrar o caminho para comecar os estudos, tipo do zero mesmo.

Eu sou de outra area, e gostaria de aprender um pouco mais de programacao inicialmente como hobbie.

Por onde comecar e quais cursos trilhar ate ter esse conhecimento que voces tem?

**Comment by BBencee** [comment]
I would recomment you https://www.w3schools.com/ if you have intermediate/strong english to understand the courses. I actually started it and its soo understandable and based on practice. Take a look at it!

**Comment by PacLucas** [comment]
Curto bastante o material da [He4rt](https://github.com/he4rt/4noobs), explicam desde o básico e vale a pena participar da comunidade também pra tirar dúvidas e trocar uma ideia sobre.

**Comment by espinozachristian** [comment]
> Pessoal, realmente estou empolgado em ver como os dev estao dando duro para solucionar esse problema para a comunidade.
> 
> Gostaria de saber se os dev ou nucito, ou outro expert. Pode mostrar o caminho para comecar os estudos, tipo do zero mesmo.
> 
> Eu sou de outra area, e gostaria de aprender um pouco mais de programacao inicialmente como hobbie.
> 
> Por onde comecar e quais cursos trilhar ate ter esse conhecimento que voces tem?

depende a linguagem, no caso do python que foi a base do que foi utilizado, tem muito conteudo gratuito no YT para sair do zero, desde entender a sintaxe e monta um codigo simples, até a parte da construção de logica, indo mais a fundo no codigo do mp, que utiliza parte de opencv + modelagem + processamento de imagem, ai tem outros canais que você até consegue buscar por isso, exemplo coursera, mas assim..isso quando olhamos "somente" o bot aqui, se olhar o universo inteiro de programação pode variar muito de linguagem x framework e afins...

**Comment by fguide** [comment]
Sugiro antes de cursos procurar alguma linguagem de programacao que va atender suas necessidades atuais, tem vários fatores a considerar, por exemplo:

O que você quer fazer?
Em qual ambiente? Linux, Windows, multiplataforma?
Existe algo que você poderia melhorar na sua vida hoje com programação?

São exemplos, mas aprender com algo ligado à sua realidade vai ser bem mais fácil, talvez faz um script pra automatizar uma tarefa simples aqui, algo para te ajudar com o trabalho, e por ai você vai aprendendo naturalmente.
