### ISSUE TITLE
botao de connect wallet mudou.

### ISSUE THREAD

**Issue by jeanvetorello** [mpcabete/bombcrypto-bot#326]
alguem percebeu que o botao de conect wallet mudou a fonte dele?
poderiam atualizar?

**Comment by jeanvetorello** [comment]
infelizmente não consegui connectar no jogo para ver se os outros botoes mudaram tambem , pois o servidor ta muito ruim de logar.

**Comment by kalleldf** [comment]
não sai de 50%

**Comment by jeanvetorello** [comment]
sim , hj ta ruim mesmo tem que esperar voltar...

**Comment by kerferber** [comment]
> não sai de 50%

aqui tbm

**Comment by espinozachristian** [comment]
> alguem percebeu que o botao de conect wallet mudou a fonte dele? poderiam atualizar?

você mesmo consegue alterar isso, só tirar uma print do seu botão e colocar na pasta target substituindo o antigo
