### ISSUE TITLE
Movimento do Mouse e Scroll lento na hora dos herois

### ISSUE THREAD

**Issue by gabrielwjesus** [mpcabete/bombcrypto-bot#327]
Pessoal, ja tentei procurar onde fica a velocidade do mouse e do scroll, pq esta girando muito lenta a tela de selecionar os herois.
Nao sei se fiz algo de errado aqui
mas o  pyautogui.moveTo(x,y,t) envia para as coordenadas x e y na velocidade t, sendo t = 1 a mais rapida, certo?
no config.yaml não detalha mto as funções de cada configuração do scroll

**Comment by yassbeno** [comment]
t=0 is the fastest.. (0 seconds, mouse goes to target instantly, t=1 means mouse takes 1 sec to get to target) google is your friend!

**Comment by gabrielwjesus** [comment]
> t=0 is the fastest.. (0 seconds, mouse goes to target instantly, t=1 means mouse takes 1 sec to get to target) google is your friend!

I think that's not the problem friend.
Because all actions are going fast 
Just scroll and send heroes doesn't
