### ISSUE TITLE
Teremos mais novidades? Publicado no canal oficial do BombCrypto

### ISSUE THREAD

**Issue by gabrielwjesus** [mpcabete/bombcrypto-bot#328]
We really sorry about server maintenance But there re still have alot of players can not log in to the game. We know all u guys have waiting for near 1 day of this maintenace, this is really bad and affect to our player farming!. All u guys waiting for 24h at the same time Dev team also try their best to working on it server for 24h either🥲. We want to make strong server for all u guys so please lets us 1 day for fix and checking after sv already can start and work smoothly. We know all u guys put your trust, your money, your time with Bomb. So we never let u guys dissapointed with the potential that Bomb can get for those players here. So pleaseeee understanding, waiting and keep patient with Bomb, everything will be Ok after hard time right😊. We will make Bomb can go far and long term . So just let Bomb resting 1 day and after Bomb will stay more strong and make all u guys happy!!!. We send to all our community Sorry about that thing . Please keep calm and be wise with all the words send to us for now, we always want all the Good thing to our beloved Bombers!!!

**Comment by kerferber** [comment]
Não vi nada de novo...... kkkkk

**Comment by gabrielwjesus** [comment]
> Não vi nada de novo...... kkkkk

Eles falam pra por os heróis pra relaxar por mais 24 horas e que depois voltaram mais fortes e não nos arrependeremos disso...
Acho que vem mais mudança
Até pq o token ta caindo

**Comment by espinozachristian** [comment]
> > Não vi nada de novo...... kkkkk
> 
> Eles falam pra por os heróis pra relaxar por mais 24 horas e que depois voltaram mais fortes e não nos arrependeremos disso... Acho que vem mais mudança Até pq o token ta caindo

na real foi só um comunicado falando que estão cientes da merda que rolou no server, pediu paciencia e fim

**Comment by kerferber** [comment]
> > > Não vi nada de novo...... kkkkk
> > 
> > 
> > Eles falam pra por os heróis pra relaxar por mais 24 horas e que depois voltaram mais fortes e não nos arrependeremos disso... Acho que vem mais mudança Até pq o token ta caindo
> 
> na real foi só um comunicado falando que estão cientes da merda que rolou no server, pediu paciencia e fim

foi oq eu entendi tbm...

em resumo: mais do mesmo

**Comment by mtmassa** [comment]
Ata pra dar desculpas eles são ruim. Putz, não me lembro de nenhum jogo que tivesse uma estrutura tão ruim kkkk
