### ISSUE TITLE
Novo Botão Connect Wallet (png)

### ISSUE THREAD

**Issue by rodrigobragamg** [mpcabete/bombcrypto-bot#330]
![image](https://user-images.githubusercontent.com/50714183/146283850-9aadcd87-7bd3-46c4-8ff1-efd745c23e08.png)

Basta alterarem na pasta "targets", o título de ve ser o mesmo: connect-wallet.png

**Comment by kalleldf** [comment]
pelo que eu percebi, os devs trocaram todas as imagens, pq eu troquei a connect wallet e resolveu esse problema mas logo em seguida o bot não consegue selecionar os herois para colocar para farmar.

**Comment by rodrigobragamg** [comment]
Não cheguei a ver ainda, acabei de começar a testar. Mas se for o caso, só trocar as imagens uma a uma.

**Comment by kerferber** [comment]
Alguém poderia add todas as imagens substituídas aqui? Eu ainda não consegui logar

**Comment by trinitro2** [comment]
o new map tambem mudou a fonte?

**Comment by jhonsstn** [comment]
@kerferber Vc poderia por favor tirar os prints e alterar vc mesmo por favor?! 

@trinitro2 Vc poderia por gentileza verificar vc mesmo, ja que ja tem o jogo e o bot, se as imagens mudaram ou n?!

**Comment by kerferber** [comment]
> @kerferber Vc poderia por favor tirar os prints e alterar vc mesmo por favor?!
> 
> @trinitro2 Vc poderia por gentileza verificar vc mesmo, ja que ja tem o jogo e o bot, se as imagens mudaram ou n?!

Se vc não quiser ajudar, poderia fazer o favor de não atrapalhar?

**Comment by trinitro2** [comment]
> @kerferber Vc poderia por favor tirar os prints e alterar vc mesmo por favor?!
> 
> @trinitro2 Vc poderia por gentileza verificar vc mesmo, ja que ja tem o jogo e o bot, se as imagens mudaram ou n?!

rapaz...quanta ignorancia. eu perguntei pois nao estava logando aqui para por os herois para trabalhar. 

se ta bravo, vai pescar

**Comment by kerferber** [comment]
> > @kerferber Vc poderia por favor tirar os prints e alterar vc mesmo por favor?!
> > @trinitro2 Vc poderia por gentileza verificar vc mesmo, ja que ja tem o jogo e o bot, se as imagens mudaram ou n?!
> 
> rapaz...quanta ignorancia. eu perguntei pois nao estava logando aqui para por os herois para trabalhar.
> 
> se ta bravo, vai pescar

Exatamente. É cada um....
