### ISSUE TITLE
[Dúvida] Clicar no Baú pra ver saldo evita desconexão?

### ISSUE THREAD

**Issue by kerferber** [mpcabete/bombcrypto-bot#331]
Pessoal,

Alguém sabe se consultar o saldo evita aqueles erros que desconectam o jogo após um tempo ?

**Comment by espinozachristian** [comment]
> Pessoal,
> 
> Alguém sabe se consultar o saldo evita aqueles erros que desconectam o jogo após um tempo ?

removeram o kick que era o "indle" na tela, caso tenha outro "erro" que voce diz, talvez nao seja por inatividade

**Comment by kerferber** [comment]
Consegui conectar. Seguem os erros... IDLE realmente não vi mais, mas acredito ter apenas mudado de nome pois fui ao banheiro e na volta havia Error: Manual... 2x

**Comment by Nightly27** [comment]
aqui apareceu esse Manual também e não deu nem 2 minutos direito que eu tinha logado

**Comment by Psicrow** [comment]
> Consegui conectar. Seguem os erros... IDLE realmente não vi mais, mas acredito ter apenas mudado de nome pois fui ao banheiro e na volta havia Error: Manual... 2x

esse manual aparece mesmo que os heroes estejam trabalhando. deve ser algum dos novos bugs que veio com o patch do novo servidor kkkk

**Comment by itxtoledo** [comment]
@mpcabete eu sugiro remover a função que faz o "refresh" na posição dos heróis, pois a cada refresh tem chance de aparecer o captcha, e, agora sem o idle não vejo necessidade de fazer esse refresh tantas vezes
