### ISSUE TITLE
on Linux

### ISSUE THREAD

**Issue by s1k3ira** [mpcabete/bombcrypto-bot#333]
Alguem roda ele no Linux, sabe dizer se parou de rodar  ?

**Comment by fguide** [comment]
Como assim? Você teve algum erro? Eu particularmente uso e não tive nenhum erro.

**Comment by mtmassa** [comment]
Uso no mint. Tudo ok

**Comment by coolwateRx3** [comment]
how to install the requirements.txt in linux? 

What would be the proper command?
