### ISSUE TITLE
Captcha solving suggestion

### ISSUE THREAD

**Issue by GGarciaDev** [mpcabete/bombcrypto-bot#336]
Hey, good work on the bot, since you are looking for optimizing the Bot, I suggest taking a look in my new repo:
https://github.com/Guiaki/BombCryptoCaptchaSolver

I've made it very simple and compact, I achieved a good performance and lower computing cost and its very simple for joining with your project.

**Comment by gabrielwjesus** [comment]
Eu também tenho uma sugestão:

Eu notei que as vezes eu só interpreta dois numeros. Neste caso ele deve reiniciar o solveCaptcha
`    background_digits = getBackgroundText()
    print('background = {}'.format(background_digits))
    
    #se tiver menos de 3 numeros é por que o programa leu errado e manda reiniciar. 
    if len(str(background_digits)) < 3:
        print('The lenght of background digits has less than three numbers')
        solveCaptcha()
  `
Outro ponto. Eu notei que as vezes ele acerta 2 numeros dos 3... seja qualquer posição. Então pensei em "chutar".
Ele precisa fazer 2 pontos (acertar 2 numeros nas mesmas posições). Exemplo 153  e 193 .... e 103 com 703. Isso somente caso ele não encontre correspondente. Pra isso transformo os 3 numeros em uma lista e checo as posições e inicio um contador:

`#transforma o valor em uma lista    
    numBack = background_digits
    xList = [int(a) for a in str(numBack)]
    print('Print List = ',xList)

captcha_img = smallDigitsImg(screenshot, popup_pos[0])
        small_digits = getSmallDigits(captcha_img)
        
        if small_digits < 3:
            print('Small Digits has less than three numbers')
        else:
            count = 0
            #transforma o valor em uma lista  
            yList = [int(a) for a in str(numSmall)]
            print('Print List = ',yList)
            for pos in len(str(small_digits)):
                if numSmall[pos] == small_digits[pos]:
                    count = count + 1
`

**Comment by rodrigobragamg** [comment]
@Guiaki
Tried your script, but, even though it recognized the captcha number correctly at all times, in half of the attempts the slider would just go until the end without making the match.

**Comment by mpcabete** [comment]
Thanks, unfortunately there were some contretemps today. But I definitely will look into it tomorrow!

**Comment by rodrigobragamg** [comment]
@mpcabete 
O script dele é muito bom mesmo. Rápido e leve. Apenas não solta o slide algumas vezes, pelo menos nos meus testes.

**Comment by kaofang38573** [comment]
@Guiaki
What happened, why error?
 res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

**Comment by gabrielwjesus** [comment]
> @Guiaki What happened, why error? res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED) cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

You don't have some kind of images in your target path. Review your target path and try again.

**Comment by kaofang38573** [comment]
> 

![image](https://user-images.githubusercontent.com/58837369/146356772-526e8195-c5f3-4a66-a5a5-c182a3f5d9bb.png)


I have it all

**Comment by gabrielwjesus** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/58837369/146356772-526e8195-c5f3-4a66-a5a5-c182a3f5d9bb.png)
> 
> I have it all

this error is just because the app didn't find the image... or because you don't have it or because the name of image is not the same the app is looking for

**Comment by kaofang38573** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/58837369/146356772-526e8195-c5f3-4a66-a5a5-c182a3f5d9bb.png)
> > ฉันมีทุกอย่าง
> 
> ข้อผิดพลาดนี้เป็นเพียงเพราะแอพไม่พบภาพ หรือเนื่องจากคุณไม่มีหรือเนื่องจากชื่อของรูปภาพไม่เหมือนกับที่แอพกําลังมองหา

![image](https://user-images.githubusercontent.com/58837369/146360713-5871cbf6-f858-4b4e-aa20-953074c9fd28.png)

I sat and checked. both picture name and all codes match, but still error

**Comment by Nydoehar** [comment]
The bot your talking is the main version? 
Is the main version of the bot already solving the new captcha?

**Comment by gabrielwjesus** [comment]
> > > > 
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/58837369/146356772-526e8195-c5f3-4a66-a5a5-c182a3f5d9bb.png)
> > > ฉันมีทุกอย่าง
> > 
> > 
> > ข้อผิดพลาดนี้เป็นเพียงเพราะแอพไม่พบภาพ หรือเนื่องจากคุณไม่มีหรือเนื่องจากชื่อของรูปภาพไม่เหมือนกับที่แอพกําลังมองหา
> 
> ![image](https://user-images.githubusercontent.com/58837369/146360713-5871cbf6-f858-4b4e-aa20-953074c9fd28.png)
> 
> I sat and checked. both picture name and all codes match, but still error

I'm really sorry but this is very strange, because, look: matchTemplate has an error and positions has an error, both because the app didn't find the right image. 
change your script, trying to find another image on the same screen.

**Comment by kaofang38573** [comment]
> > > > > 
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/58837369/146356772-526e8195-c5f3-4a66-a5a5-c182a3f5d9bb.png)
> > > > ฉันมีทุกอย่าง
> > > 
> > > 
> > > ข้อผิดพลาดนี้เป็นเพียงเพราะแอพไม่พบภาพ หรือเนื่องจากคุณไม่มีหรือเนื่องจากชื่อของรูปภาพไม่เหมือนกับที่แอพกําลังมองหา
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/58837369/146360713-5871cbf6-f858-4b4e-aa20-953074c9fd28.png)
> > ฉันนั่งและตรวจสอบ ทั้งชื่อรูปภาพและรหัสทั้งหมดตรงกัน แต่ก็ยังเกิดข้อผิดพลาดอยู่
> 
> ฉันขอโทษจริงๆ แต่สิ่งนี้แปลกมากเพราะดูสิ: matchTemplate มีข้อผิดพลาดและตําแหน่งมีข้อผิดพลาดทั้งเพราะแอพไม่พบภาพที่ถูกต้อง เปลี่ยนสคริปต์ของคุณ โดยพยายามค้นหารูปอื่นบนหน้าจอเดียวกัน

now solved Maybe because the server is closed. so can't find the picture

**Comment by kaofang38573** [comment]
> > > > > 
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/58837369/146356772-526e8195-c5f3-4a66-a5a5-c182a3f5d9bb.png)
> > > > ฉันมีทุกอย่าง
> > > 
> > > 
> > > ข้อผิดพลาดนี้เป็นเพียงเพราะแอพไม่พบภาพ หรือเนื่องจากคุณไม่มีหรือเนื่องจากชื่อของรูปภาพไม่เหมือนกับที่แอพกําลังมองหา
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/58837369/146360713-5871cbf6-f858-4b4e-aa20-953074c9fd28.png)
> > ฉันนั่งและตรวจสอบ ทั้งชื่อรูปภาพและรหัสทั้งหมดตรงกัน แต่ก็ยังเกิดข้อผิดพลาดอยู่
> 
> ฉันขอโทษจริงๆ แต่สิ่งนี้แปลกมากเพราะดูสิ: matchTemplate มีข้อผิดพลาดและตําแหน่งมีข้อผิดพลาดทั้งเพราะแอพไม่พบภาพที่ถูกต้อง เปลี่ยนสคริปต์ของคุณ โดยพยายามค้นหารูปอื่นบนหน้าจอเดียวกัน

It's because I adjusted the position 
m = {
    'left': X,
    'top': Y,
    'width': width,
    'height': height
}
make it impossible to find So how do I adjust the mouse cursor to find the captcha?

**Comment by Guiaki** [comment]
> @Guiaki Tried your script, but, even though it recognized the captcha number correctly at all times, in half of the attempts the slider would just go until the end without making a match.

Actually the first commit version I released was after doing a few tweaks and the accuracy got lower, I'll try doing a update later today to adjust the parameters

> @kaofang38573
> I have it all
From what I can see, you changed the captchaBar, is it the same name and extension? you can try posting this issue in the repo cause its not really a issue for this one here.
The position you adjusted needs to be the top left corner of the game window, you can check out this [PyGetWindow](https://pypi.org/project/PyGetWindow/) to get the named window and its dimensions, also make sure there ain't no other windows named Bombcrypto cause it might tweak the bot a little

**Comment by luizxd0** [comment]
@mpcabete acorda ai, precisamos de voce kkk

**Comment by mpcabete** [comment]
kkk to começando os trabalhos aki @luizxd0

**Comment by luizxd0** [comment]
> kkk to começando os trabalhos aki @luizxd0

nice demais, so no aguardo :)

**Comment by rodrigobragamg** [comment]
@mpcabete 
Você pretende implementar essa solução aqui? Chegou a testar? É muito boa.
