### ISSUE TITLE
ERRO MANUAL

### ISSUE THREAD

**Issue by Redexote** [mpcabete/bombcrypto-bot#340]
Pessoal estou usando o VM aqui , e toda hora da esse erro MANUAL, quando utilizo o navegador do meu pc nao da esse erro alguem saberia me dizer o que fazer?

O erro so acontece na VM

**Comment by rodrigobragamg** [comment]
Leia os fixados no discord.

**Comment by Redexote** [comment]
> Leia os fixados no discord oficial do Bombcrypto.

amigo nao  eu tento entrar no discord nao vai , so consigo telegram

**Comment by fguide** [comment]
Nao sei qual OS usa em sua VM, mas vi alguns erros desse hoje relacionados à atualização do windows 10. Se for o caso tente um reboot.

**Comment by rodrigobragamg** [comment]
É um bug, falaram que foi reportado aos Devs. Mas acho que estão kikando mesmo, para não sobrecarregar o servidor.
