### ISSUE TITLE
Erro Bypass New captch

### ISSUE THREAD

**Issue by sgsilva** [mpcabete/bombcrypto-bot#341]
First, I'm grateful for everyone's efforts to solve the new capcha, second that it's unstable, sometimes it gets it right and sometimes it doesn't.

Primeiro agradeço pelo esforço de todos para a solução do novo capcha, segundo que ele está instável, as vezes ele acerta e outras não.

![image](https://user-images.githubusercontent.com/57260096/146313290-9848a310-f92e-46e9-b667-ace8860bfd68.png)

**Comment by vst212** [comment]
Just set like time.sleep(5) before solveCaptcha().
Reason is the position of slide bar is not get correctly

**Comment by sgsilva** [comment]
some times only foun 2 numbers.
and got error.
![image](https://user-images.githubusercontent.com/57260096/146363031-4562974b-3b95-4e0f-aacd-36cb5acd9e9d.png)

**Comment by thebossza101** [comment]
![image](https://user-images.githubusercontent.com/22001938/146366353-dc6947c6-00ab-48e2-8bb5-da4b6eff62e6.png)

https://github.com/Guiaki/BombCryptoCaptchaSolver

**Comment by cmxavier** [comment]
> some times only foun 2 numbers. and got error. ![image](https://user-images.githubusercontent.com/57260096/146363031-4562974b-3b95-4e0f-aacd-36cb5acd9e9d.png)

Estou tendo o mesmo problema, ele identifica o numero no backgrund corretamente, mas os numeros da frente as vezes identifica apenas dois numeros

**Comment by sgsilva** [comment]
ele não consegue captar o primeiro número pelo que eu vi! teria que aumentar a área

**Comment by Maxen47** [comment]
Os 2 últimos números do captcha São sempre diferentes, o bot poderia ignorar o primeiro número para poupar tempo e minimizar as chances de erro.

**Comment by kalleldf** [comment]
Estou com o mesmo problema, o bot faz a leitura do captcha mas erra na hora de deslizar

**Comment by poloik007** [comment]
percebi que as vezes o captcha tem numeros a mais, essa variacao nos numeros atrapalha o bot na hora de deslizar, minha sugestao seria deslizar o mouse mais devagar e verificar se houve mudanca, atualmente ele pula numeros.
