### ISSUE TITLE
longtime for relogin after mistake

### ISSUE THREAD

**Issue by btcdisk** [mpcabete/bombcrypto-bot#342]
Hello friend. my respect
When the program spends a lot of time on solving it, it does not re-enter the game again or hangs on the Connect Vallet button.
Redesigned buttons.
Often after an error, bot does not press the OK button (on any messages) for a very long time. You need to add an OK button poll more often.

The bombcrypto website added protection against bots since all bots work at 100 scale in the browser. (Manual error). If we set the scale in the game (through the browser 80-90) there is no such error. But then you need to rescan the buttons for the captcha too. OR it is better to have a scale of 100 on the login,captcha page, and zoom out on the game page.
It will be great if there are several options for a scale of 100, 90, 80

thank you from Japan

**Comment by korokoroinu** [comment]
It may be possible to run with a differente scale, but you would need to change the images the bot search for (in targets folder) with new images (just print screen and replace the images).
as for the connect wallet hanging, uncomment line 362 in index.py, so it wait a few seconds after clicking 'Connect Wallet' before continuing.

**Comment by btcdisk** [comment]
> It may be possible to run with a differente scale, but you would need to change the images the bot search for (in targets folder) with new images (just print screen and replace the images). as for the connect wallet hanging, uncomment line 362 in index.py, so it wait a few seconds after clicking 'Connect Wallet' before continuing.

but this is not help for 
"often after an error, bot does not press the OK button (on any messages) for a very long time. You need to add an OK button poll more often"   
need increase the polling frequency of the search for the OK button - how?

**Comment by btcdisk** [comment]
And somebody redo the screenshots of the buttons, they were redrawn in the game.

**Comment by korokoroinu** [comment]
> thank you. but better make this on code. 100% scale for connect and captcha , for gameplay use use another automaticaly. I cannot redo all the numbers with captchas for 80% scale (for example). How many percent do you need to reduce the scale of all the pictures in the bot in order to play the bomber with a scale of 80%? Why re-take screenshots, you need to apply math, it will be effective. An error in the game (manual) can be avoided by using a different scale in the browser, namely in the browser. ctrl + -

it is possible to search the image in different scales of course, but it would be prone to more false-positives and unexpected behaviours. 
Maybe i'll make a pull request with a configuration to rescale but it will be up to the maintaners to accept it too.
