### ISSUE TITLE
Login Erros (ideia)

### ISSUE THREAD

**Issue by luizbiazus** [mpcabete/bombcrypto-bot#343]
Olá Pessoal,

é possivel o bot ao detectar:
Socket Error
Manual
Unknown 
enfim todos os erros de login que tem no BugCrypto o bot executar um Control Swift + R e um Control + F5  antes de tentar logar ?

Muitas vezes arquivos cacheados são o problema ai fica com mais chances de login.

Grato.

**Comment by fcolnaghi** [comment]
apos 3 falhas de login em sequencia o bot ja da CTRL+F5

**Comment by luizbiazus** [comment]
a perfeito entao mestre obrigado pelo comentário...
aproveitando tem alguma solucao pra ele clicar em sign mais efetivamente? resolucao de tela ou zoom não sei? porque as vezes entro e tem 42 pedidos de assinatura .

**Comment by korokoroinu** [comment]
> a perfeito entao mestre obrigado pelo comentário... aproveitando tem alguma solucao pra ele clicar em sign mais efetivamente? resolucao de tela ou zoom não sei? porque as vezes entro e tem 42 pedidos de assinatura .

tenta descomentar a linha 362 do index.py deve ser porque esta demorando para abrir o popup do metamask

**Comment by mtmassa** [comment]
> a perfeito entao mestre obrigado pelo comentário... aproveitando tem alguma solucao pra ele clicar em sign mais efetivamente? resolucao de tela ou zoom não sei? porque as vezes entro e tem 42 pedidos de assinatura .

Tenta tbm susbtiruir o botao de sign por imagens feita em seu sistema.
