### ISSUE TITLE
Meu bot nao conecta a carteira 

### ISSUE THREAD

**Issue by pedrox97** [mpcabete/bombcrypto-bot#344]
![imagem](https://user-images.githubusercontent.com/96137023/146378203-bb7d7a17-88db-4008-a0ba-af779a7bac08.png)

Quando o jogo cai o bot nao volta a conectar a carteira e dar login. 
o que posso fazer?

**Comment by fx2016** [comment]
Esperar terminar as otimizações, o bot não está pronto.

**Comment by pedrox97** [comment]
obrigado

**Comment by mtmassa** [comment]
> ![imagem](https://user-images.githubusercontent.com/96137023/146378203-bb7d7a17-88db-4008-a0ba-af779a7bac08.png)
> 
> Quando o jogo cai o bot nao volta a conectar a carteira e dar login. o que posso fazer?

Ja saiu uma att atualizando os botoes, atualize o bot ou substitua as imagens por umas feita em seu sistema.

**Comment by trinitro2** [comment]
> ![imagem](https://user-images.githubusercontent.com/96137023/146378203-bb7d7a17-88db-4008-a0ba-af779a7bac08.png)
> 
> Quando o jogo cai o bot nao volta a conectar a carteira e dar login. o que posso fazer?

conseguiu?

**Comment by pedrox97** [comment]
onde vou buscar essa atualizaçao?

**Comment by neurose0** [comment]
o meu demora muito para ler o captha , esperando o @mpcabete lança a versao definitiva! <3 <3 <3

**Comment by trinitro2** [comment]
> onde vou buscar essa atualizaçao?

nao entendi. voce pois sua wallet em ingles e trocou o botao ja?

**Comment by pedrox97** [comment]
sim esta em ingles, qual o botao que tenho de trocar o que diz sign? 
tiro um print e coloco na pasta tragets?

**Comment by Nzjj** [comment]
Não seria sua resolução ?

**Comment by pedrox97** [comment]
> Não seria sua resolução ?

O que posso fazer para resolver ?

**Comment by mtmassa** [comment]
> sim esta em ingles, qual o botao que tenho de trocar o que diz sign ou o conect wallet? tiro um print e coloco na pasta tragets? ele fica nessa pagina que enviei print e nao carregar no botao conect wallet se eu carregar depois para a frente ja faz tudo sozinho

Atualiza o bot que vem com os botoes de carteira, heroi e barra atualizado, eu precisei trocar o botao do sign por um sem as bordas. fuuncionando legal aqui.

**Comment by mtmassa** [comment]
> onde vou buscar essa atualizaçao?

eita, cara baixar o bot e mais facil que abrir um issue!

**Comment by rsilveira91** [comment]
caso não funcione é só fazer um print  do botão de "assinar" da sua Metamask e substituir no target.
no meu tbm não ia, fiz isso e resolveu.
não sei se é por conta do navegador.
estou usando Firefox no Linux.

**Comment by luizxd0** [comment]
> caso não funcione é só fazer um print do botão de "assinar" da sua Metamask e substituir no target. no meu tbm não ia, fiz isso e resolveu. não sei se é por conta do navegador. estou usando Firefox no Linux.

isso acontece devido ao reconhecimento de imagem que o bot faz, ele procura pixel por pixel, se tiver diferente ele nao acha...
se sua resolucao estiver diferente, nao vai achar, se o o botao estiver em portugues  escrito "assinar" nao iria achar tambem por que ta configurado pra ele procurar o botao escrito "singin". Por isso que funciona quando voce troca a imagem.

**Comment by pedrox97** [comment]
Ja esta resolvido, obrigado a todos. 
acho que foi por ter baixodo a nova versao e nao apagar a antiga

**Comment by alexandernicacio** [comment]
boa noite pessoal, estou com o mesmo problema da versão passada, o bot não clica pra assinar a carteira na metamesk, minha metamesk esta me inglês, ja troquei o botão do sign por um tirado um print da minha amquina e com bordas retas, ja fiz modificações na na linha 363 para descomentar e mudar de sleep(10) para sleep(2) e nada disso resolveu dessa vez ele esta fazendo o captcha certinho mais não conecta na carteira, ja vi algumas pessoas falando que resolveram em seus computadores, mais pra mim não funcionou, alguém pode me ajudar?

**Comment by BBencee** [comment]
> good night guys, I'm having the same problem as the last version, the bot doesn't click to sign the wallet in metamesk, my metamesk is in English, I've already changed the sign button for one taken from a print of my machine and with straight edges, already I made changes in line 363 to uncomment and change from sleep(10) to sleep(2) and none of that resolved this time he is doing the captcha just right but it doesn't connect to the wallet, I've seen some people saying that they resolved it on their computers, more it didn't work for me, can someone help me?

I have the same problem, I've tried everything here
