### ISSUE TITLE
PROGRAMAR

### ISSUE THREAD

**Issue by Disuny** [mpcabete/bombcrypto-bot#345]
Voces pensam quem ensinar a programar? EX "esse BOT". Tenho interesse na areia, gostaria de saber se voces tem planos para isso ?

**Comment by juniortopanotti** [comment]
Meu deus, pessoal de fora ta achando que repositório no Github é fórum pra ficar abrindo Issue pra falar qualquer coisa...

**Comment by backslash-f** [comment]
Facehub, GitBook.

**Comment by Disuny** [comment]
> Voces pensam quem ensinar a programar? EX "esse BOT". Tenho interesse na areia, gostaria de saber se voces tem planos para isso ?
