### ISSUE TITLE
Captcha/Workers

### ISSUE THREAD

**Issue by pacote009** [mpcabete/bombcrypto-bot#346]
Eu tentei usar agora o bot e o sistema não está enviando os Herois para trabalhar, apenas rola o scroll da lista de herois mas não envia e não resolveu o captcha, estão conseguindo utilizar o bot ai?

**Comment by luizxd0** [comment]
pode ficar de boa que ainda ta sendo desenvolvido o novo captcha, talvez hoje mesmo ja saia a versao completa

**Comment by caiocenlep** [comment]
**### Quase lá!
Almost there!
Temos a primeira versão "funcional" do bot, ainda existem algumas otimizaçoes que precisam ser feitas pra ele funcionar liso, infelizmente nao consegui terminar essas otimiçaçoes hj. Mas com certeza amanhã ele ja fica lisinho!**

**Comment by pacote009** [comment]
> pode ficar de boa que ainda ta sendo desenvolvido o novo captcha, talvez hoje mesmo ja saia a versao completa

Muito obrigado, eu só queria saber mesmo se eu era o único com esses problemas.

**Comment by mtmassa** [comment]
> Eu tentei usar agora o bot e o sistema não está enviando os Herois para trabalhar, apenas rola o scroll da lista de herois mas não envia e não resolveu o captcha, estão conseguindo utilizar o bot ai?

to usando a ultima versao do bot, foi atualizado os botoes da walet, herois e barras, esta funcionando blz aqui... atualiza novamente ai.... aqui precisei so trocar o botao do sign da meta, tudo funcional

**Comment by luizxd0** [comment]
> > Eu tentei usar agora o bot e o sistema não está enviando os Herois para trabalhar, apenas rola o scroll da lista de herois mas não envia e não resolveu o captcha, estão conseguindo utilizar o bot ai?
> 
> to usando a ultima versao do bot, foi atualizado os botoes da walet, herois e barras, esta funcionando blz aqui... atualiza novamente ai.... aqui precisei so trocar o botao do sign da meta, tudo funcional

o teu resolve o captcha? aqui ele mais erra o captcha do que acerta, ai chega um momento que o script trava e da erro

**Comment by pacote009** [comment]
> > Eu tentei usar agora o bot e o sistema não está enviando os Herois para trabalhar, apenas rola o scroll da lista de herois mas não envia e não resolveu o captcha, estão conseguindo utilizar o bot ai?
> 
> to usando a ultima versao do bot, foi atualizado os botoes da walet, herois e barras, esta funcionando blz aqui... atualiza novamente ai.... aqui precisei so trocar o botao do sign da meta, tudo funcional

o que vc fez pra conseguir? consegue me explicar?

**Comment by joaovictor7** [comment]
> > > Eu tentei usar agora o bot e o sistema não está enviando os Herois para trabalhar, apenas rola o scroll da lista de herois mas não envia e não resolveu o captcha, estão conseguindo utilizar o bot ai?
> > 
> > 
> > to usando a ultima versao do bot, foi atualizado os botoes da walet, herois e barras, esta funcionando blz aqui... atualiza novamente ai.... aqui precisei so trocar o botao do sign da meta, tudo funcional
> 
> o teu resolve o captcha? aqui ele mais erra o captcha do que acerta, ai chega um momento que o script trava e da erro

verifica o zoom do teu navegador, tem que estar em 100%.
aqui o bot até erra as vezes mas no geral ele consegue acertar. to rodando já tem umas 8h seguidas sem parar.

**Comment by iurobpn** [comment]
Pessoal, uma duvida: E o tempo de solução dos captchas? Se contar os tempo do 1o clique até o ultimo clique que resolve o captcha  der sempre um valor muito proximo de tempo, não corre o risco de eles conseguirem descobrir quem usa bot pela consistencia do tempo de solução do captcha?

**Comment by luizxd0** [comment]
> Pessoal, uma duvida: E o tempo de solução dos captchas? Se contar os tempo do 1o clique até o ultimo clique que resolve o captcha der sempre um valor muito proximo de tempo, não corre o risco de eles conseguirem descobrir quem usa bot pela consistencia do tempo de solução do captcha?

cara, relaxa a piriquita que eles nao tem capacidade pra rastrear algo assim....botaram captcha pq eh a unica forma de tentar evitar bot, fora isso nao tem como eles rastrearem nada no teu pc

**Comment by kerferber** [comment]
Pessoal. Acabei de testar a última atualização e por enquanto está redondinho!!

**Comment by mpcabete** [comment]
dahoraa @kerferber q bom q ta dando certo, agora falta so eu arrumar a logica do slider pq ta com a antiga ainda, entao as vezes ele pula uns numeros

**Comment by R3pl1cant3** [comment]
Working like a charm here.

**Comment by R3pl1cant3** [comment]
> Pessoal, uma duvida: E o tempo de solução dos captchas? Se contar os tempo do 1o clique até o ultimo clique que resolve o captcha der sempre um valor muito proximo de tempo, não corre o risco de eles conseguirem descobrir quem usa bot pela consistencia do tempo de solução do captcha?

Amigo, eles mal conseguem configurar um servidor, baniram um monte de gente e desbaniram depois, estão muito perdidos. Imagino que tendo bom senso, não abusando, sem problemas. Eu programo o Windows pra fechar o jogo de madrugada, já que jogo numa Rig de mineração que fica sempre ligada =P

**Comment by vaskhan** [comment]
> > Pessoal, uma duvida: E o tempo de solução dos captchas? Se contar os tempo do 1o clique até o ultimo clique que resolve o captcha der sempre um valor muito proximo de tempo, não corre o risco de eles conseguirem descobrir quem usa bot pela consistencia do tempo de solução do captcha?
> 
> Amigo, eles mal conseguem configurar um servidor, baniram um monte de gente e desbaniram depois, estão muito perdidos. Imagino que tendo bom senso, não abusando, sem problemas. Eu programo o Windows pra fechar o jogo de madrugada, já que jogo numa Rig de mineração que fica sempre ligada =P

você tem seu próprio bot de trabalho que joga bombardeiros sem problemas e resolve todo o captcha?

**Comment by sportano** [comment]
Aqui fica assim e não faz nada, alguem pode ajudar?

![image](https://user-images.githubusercontent.com/95481359/146452442-c0c2cc4f-30d5-4c00-ab9f-b66f08987442.png)
