### ISSUE TITLE
Erro no botão de assinatura.

### ISSUE THREAD

**Issue by DimaxaGaming** [mpcabete/bombcrypto-bot#349]
O bot simplesmente não clica no botão "Assinar" e continua a clicar em "Conectar Carteira".

**Comment by fx2016** [comment]
_"New captcha update:
Quase lá!
Almost there!
Temos a primeira versão "funcional" do bot, ainda existem algumas otimizaçoes que precisam ser feitas pra ele funcionar liso, infelizmente nao consegui terminar essas otimiçaçoes hj. Mas com certeza amanhã ele ja fica lisinho!"_

**Comment by DimaxaGaming** [comment]
Boa

**Comment by mvpalves** [comment]
> O bot simplesmente não clica no botão "Assinar" e continua a clicar em "Conectar Carteira".

Assinar? O seu metamask está em inglês?

Pq precisa estar em inglês... pq ele vai tentar ler o Sign e não Assinar

**Comment by Galinho90** [comment]
Gente coloquei para rodar e nao esta assinando tbm, tentei alterar a imagem tirando um print e não funcionou não.

**Comment by filipecavalc** [comment]
@Galinho90 posta a imagem ai que eu abro um PR com a imagem atualizada pra ver se melhora pro pessoal

**Comment by Galinho90** [comment]
> @Galinho90 posta a imagem ai que eu abro um PR com a imagem atualizada pra ver se melhora pro pessoal

@filipecavalc foi desta forma que funcionou comigo, deixei bem rente. 

![select-wallet-2](https://user-images.githubusercontent.com/95733162/146590550-f17be35b-0351-47cd-bb44-f591cb114ea2.png)
