### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by sportano** [mpcabete/bombcrypto-bot#350]
![image](https://user-images.githubusercontent.com/95481359/146452442-c0c2cc4f-30d5-4c00-ab9f-b66f08987442.png)

Estou enfrentando esse erro, alguém pode ajudar?

**Comment by amatoxd** [comment]
Q erro?

**Comment by sportano** [comment]
> Q erro?

Fica aparecendo esse 99m, e o mouse não mexe...

**Comment by neurose0** [comment]
meu ta assim também

**Comment by fguide** [comment]
Isso não é erro, é na verdade uma falha de tradução de caracteres, nada para se preocupar.

O comando abaixo resolve o problema provavelmente:

chcp 65001

**Comment by sportano** [comment]
> Isso não é erro, é na verdade uma falha de tradução de caracteres, nada para se preocupar.
> 
> O comando abaixo resolve o problema provavelmente:
> 
> chcp 65001

Funcionou! Obg! Porém o bot está fechando após botar os heroes pra trabalhar, sabe oq pode ser?

**Comment by Suedera** [comment]
mine occurs the same problem and the captcha is not resolved at all, can someone help me?

**Comment by gerlim** [comment]
meu bot não está colocando os herois para farmar alguem sabe o que pode ser?

**Comment by fguide** [comment]
Vocês baixaram a atualizacao completa? Algum erro?

Did you download the entire update? What are the error messages?

**Comment by gerlim** [comment]
achei a solução, não mudem a linguagem do jogo pq não funciona direito a não ser em ingles
