### ISSUE TITLE
ERRO torch>=1.10.0

### ISSUE THREAD

**Issue by DDC19** [mpcabete/bombcrypto-bot#351]
Olá, pessoal eu utilizava as outras versões do bot normalmente.
Mas essas ultimas atualizações não estou conseguindo executar ele, da o seguinte erros:

 ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.10.
![SharedScreenshot12](https://user-images.githubusercontent.com/96269406/146463538-f055a6f4-5c3e-4362-b336-eb4e6933a3c6.jpg)
0

**Comment by brunoeggers** [comment]
Instala python 3.9.9
Você provavelmente instalou o Python 3.10+
Torch só roda na versão 3.9.x

**Comment by fguide** [comment]
Da uma olhada em: #229

**Comment by DDC19** [comment]
> Instala python 3.9.9 Você provavelmente instalou o Python 3.10+ Torch só roda na versão 3.9.x

Beleza mano realmente estou na versão mais recente.

**Comment by DDC19** [comment]
> Instala python 3.9.9 Você provavelmente instalou o Python 3.10+ Torch só roda na versão 3.9.x

Brother deu certo, muito obrigado!
