### ISSUE TITLE
ERRO CAPTCHA 

### ISSUE THREAD

**Issue by Suedera** [mpcabete/bombcrypto-bot#352]
![image](https://user-images.githubusercontent.com/96270606/146467600-0cee196e-1dfd-481c-9633-38eb7c6281a7.png)

my captcha is not made at all, could someone help me? already update to the latest version of the bot.

**Comment by neurose0** [comment]
depois que atualizei nao funcionou mais direito

**Comment by Suedera** [comment]
no captcha popup found :(

**Comment by cmxavier** [comment]
Aqui tambem parou depois da atualização

**Comment by cmxavier** [comment]
Alterei a imagem do robot, mas mesmo assim o mouse vai pro canto superior direito da tela quando abre o pop up e fica parado e nada acontece

**Comment by cmxavier** [comment]
A imagem que identifica o pop up esta dentro da pasta captcha/imagem, alterei e funcionou!

**Comment by vict1n** [comment]
@cmxavier alterou oq amigo?

**Comment by LoboNFT** [comment]
@cmxavier explain please

**Comment by vict1n** [comment]
Consegui. só tirar um print do "Até you a robot?" e cortar as bordas e substituir pelo arquivo robot.png

**Comment by n0k3zin** [comment]
Eu mesmo reconhecendo o captcha apos ele passar o mouse por todo captcha o bot fecha sozinho sem apresentar erro

**Comment by rodrigobragamg** [comment]
Troquei o png mas continua não reconhecendo no Brave. No Chrome e Firefox vai. Estranho.

**Comment by Redexote** [comment]
Galera vai na pasta captcha /Imagens  la tem o robot, ai vcs trocam essa Imagem , o meu funcionou assim. lembrem de copiar a imagem em png o formato , e ela tem que ocupar todo o espaço verde!!!!!

**Comment by rodrigobragamg** [comment]
Não é só a imagem. Tem alguma coisa haver com o threshold, o mpc fez alterações. Está tendo conflito com determinados navegadores ou pc's diferentes.

**Comment by rodrigobragamg** [comment]
O problema aqui está no Brave. Não só o problema em reconhecer o robot.png original (mudando resolve), mas todos os números do captcha, fazendo com que não seja resolvido.
No Chrome e Firefox está ok.

**Comment by Ricardoadlj** [comment]
Troca o robot.png pelo que?

**Comment by neurose0** [comment]
1148 samples taken in 25.893855333328247 seconds(44.334842580293454/s)
Processed 1148 images in 0.6261420249938965 seconds
Combined 1148 images in 0.008002519607543945 seconds
background =
Traceback (most recent call last):
  File "C:\bomb\index.py", line 522, in <module>
    main()
  File "C:\bomb\index.py", line 490, in main
    solveCaptcha()
  File "C:\bomb\captcha\solveCaptcha.py", line 311, in solveCaptcha
    x,y = position(d['slider'],img=screenshot)
TypeError: cannot unpack non-iterable NoneType object



troquei a foto do robot

**Comment by Periqe** [comment]
estou com o mesmo erro, ja troquei a foto e nao resolveu https://github.com/mpcabete/bombcrypto-bot/issues/350#issuecomment-996272433 ja fiz isso que recomendaram e tbm nao resolveu alguem pode ajudar?

**Comment by mribeirox** [comment]
> estou com o mesmo erro, ja troquei a foto e nao resolveu [#350 (comment)](https://github.com/mpcabete/bombcrypto-bot/issues/350#issuecomment-996272433) ja fiz isso que recomendaram e tbm nao resolveu alguem pode ajudar?

Estou com esse mesmo problema. Fiz os procedimentos acima e não consegui resolver.
