### ISSUE TITLE
Erro ao escolher opçao certa do captcha

### ISSUE THREAD

**Issue by llFerreira** [mpcabete/bombcrypto-bot#353]
Ele ler a numeração escondida corretamente, porém na hora de escolhe o numero certo ele escolhe qualquer numero aleatório.
Testei varias vezes e nenhuma vez ele escolheu o certo. Ele vai e vem com a barrinha 2x, as vezes 3x, e mesmo assim escolhe o errado.

**Comment by Galinho90** [comment]
> Ele ler a numeração escondida corretamente, porém na hora de escolhe o numero certo ele escolhe qualquer numero aleatório. Testei varias vezes e nenhuma vez ele escolheu o certo. Ele vai e vem com a barrinha 2x, as vezes 3x, e mesmo assim escolhe o errado.

Identifiquei o mesmo erro, mas depois de umas tres tentativas ele acerta;

**Comment by mfsousa** [comment]
@mpcabete seria possivel verificar? Para mim tb n ta conseguindo encontrar a posição do captcha correcta.

**Comment by 0bomb4** [comment]
@mfsousa  to usando teu fork, mas nao sei como resolver esse erro 
![image](https://user-images.githubusercontent.com/95734406/146486584-3028ce12-1962-4697-b210-31fc2305e6c0.png)

**Comment by AlissonVL** [comment]
> Identifiquei o mesmo erro, mas depois de umas tres tentativas ele acerta;

Eu notei aqui que quando o bot erra + 3x o jogo te desconecta e força a fazer login novamente, talvez isso possa aumentar a chances de banimento se fica sendo recorrente.

**Comment by matheus-rpk** [comment]
aguardar alguma atualização do @Nucito

**Comment by mfsousa** [comment]
> @mfsousa to usando teu fork, mas nao sei como resolver esse erro ![image](https://user-images.githubusercontent.com/95734406/146486584-3028ce12-1962-4697-b210-31fc2305e6c0.png)

nao sei porquê, tente entrar no jogo com https://app.bombcrypto.io/webgl/index.html talvez resolva, pq se for so https://app.bombcrypto.io/ o titulo fica diferente e ele detecta as janelas pelo titulo

**Comment by 0bomb4** [comment]
ah sim, belo detalhe, obrigado vou conferir aqui @mfsousa , sobre o erro de captcha nao parece ser o macro que tá com erro é algum lag, nos primeiros testes estava resolvendo de boa, tenta limpar o cache e reinicar a maquina.
Mesmo eu fazendo o captcha manualmente e acertando o jogo tava dizendo que estava errado, reiniciei tudo e resolveu

**Comment by llFerreira** [comment]
Pelo oque notei hoje, antes de sair de casa, foi que: o bot na hora do slider ele nao tira print, igual o primeiro captcha, que ele fazia o slider de vagar e printando. Nesse ele está apenas passando o slider pra lá e pra cá sem parar e soltando em qualquer número.

**Comment by Adguimar** [comment]
Conseguiu resolver?

**Comment by mpcabete** [comment]
eu vou adicionar alguns logs no bot pra ajudar agnt a descobrir qual eh o problema

**Comment by mfsousa** [comment]
@mpcabete tive q voltar com esta versao https://raw.githubusercontent.com/mpcabete/bombcrypto-bot/479e3c41b6b2ab3dcc270ed68f447411341601e0/captcha/solveCaptcha.py para ele voltar a funcionar

**Comment by mpcabete** [comment]
Pessoal da uma testada aí nessa nova versão e vê se melhora!

**Comment by llFerreira** [comment]
> @mpcabete tive q voltar com esta versao https://raw.githubusercontent.com/mpcabete/bombcrypto-bot/479e3c41b6b2ab3dcc270ed68f447411341601e0/captcha/solveCaptcha.py para ele voltar a funcionar

Aqui agora foi, com esse ai antigo. 
![image](https://user-images.githubusercontent.com/41524514/146615067-688e6704-c334-415f-892c-48cef70a95f1.png)
