### ISSUE TITLE
Cv2 + Error

### ISSUE THREAD

**Issue by WanaColacio** [mpcabete/bombcrypto-bot#355]
![image](https://user-images.githubusercontent.com/95771077/146502139-5af86da3-4133-494b-8ca4-c587cb81376a.png)

dando esse erro quando do pip install requeriments

**Comment by WanaColacio** [comment]
![image](https://user-images.githubusercontent.com/95771077/146502217-2d5873d6-6f83-4953-b00b-ccfb33225bea.png)

E esse erro quando dou python index.py

**Comment by Galinho90** [comment]
> ![image](https://user-images.githubusercontent.com/95771077/146502139-5af86da3-4133-494b-8ca4-c587cb81376a.png)
> 
> dando esse erro quando do pip install requeriments

Instale a versão do Python 3.9.9 e faça o teste, mas antes lembre-se de desinstalar esta versão. 

https://www.python.org/downloads/release/python-399/

**Comment by WanaColacio** [comment]
> > ![image](https://user-images.githubusercontent.com/95771077/146502139-5af86da3-4133-494b-8ca4-c587cb81376a.png)
> > dando esse erro quando do pip install requeriments
> 
> Instale a versão do Python 3.9.9 e faça o teste, mas antes lembre-se de desinstalar esta versão.
> 
> https://www.python.org/downloads/release/python-399/

estou com 3.9.9 e mesmo erros persistem

**Comment by wandersonlt** [comment]
tente ultilizar este comando pra mim resolveu
pip install opencv-python-headless
