### ISSUE TITLE
NÃO VÊ O CAPTCHA POR COMPLETO

### ISSUE THREAD

**Issue by Reptile0** [mpcabete/bombcrypto-bot#357]
Olá, estou com um problema, quando inicio o bot após ele reconhecer o  captcha o mouse vai para o meio dele e termina fora do mesmo, com isso ele não consegue o 1º número, alguma sugestão. OBS: Sou bem novato em Programação.

**Comment by rsilveira91** [comment]
Bom dia.
no meu caso hora reconhecia o Captcha e hora não.
não sei se é por conta da velocidade da Maquina Virtual.
dai setei o "speed" do solveCaptcha.py para "1" ao invés de "0.6"
agora melhorou bastante a taxa de acerto.

**Comment by raonigiovani** [comment]
troca os arquivos de imagens por prints tirados da sua tela ,

**Comment by Reptile0** [comment]
Consegui resolver aqui, troque o offset_x de 30 para -90 no SolveCaptcha
