### ISSUE TITLE
[SUGESTÃO] Implementar contador de baús

### ISSUE THREAD

**Issue by Yumiizera** [mpcabete/bombcrypto-bot#358]
Gostaria de dar a sugestão para que o bot tenha um contador de baú e que dê informações de quantos baús foram respawnados e as somas em valores de bcoin. 
 > Pra muitos é bem irrelevantes, pra outros é bem importante porque a gente saberia o quanto faria numa noite ou em 24h (Será até melhor que o simulador dando valores reaise podemos tirar a média)
> Será interessante pra quem anota, faz os cálculos mensais, semanais, quinzenais, etc e etc
> Dará informações também sobre as jaulas (Isso pra quem farma mais de 15 mapas por dia)

Valores atualizados da vida e bcoin:

![artcarubaus091221](https://user-images.githubusercontent.com/95440041/146540005-9692a452-bd72-4487-a0ae-d269aa5ba379.png)

**Comment by trinitro2** [comment]
sinceramente, acho desnecessário
