### ISSUE TITLE
Metamask vai para o segundo plano

### ISSUE THREAD

**Issue by k4m4h4l** [mpcabete/bombcrypto-bot#359]
Ola bom dia primeiramente muito obrigado pelo trabalho maravilhoso e o desejo de ajudar.
O bot as vezes funciona perfeito, porem algumas vezes nao sei o que acontece ele joga a metamask para o segundo plano e ai quando vamos ver tem umas 20 notificacoes na metamask e o bot nao consegue logar rmais, alguem ja conseguill resolver esse erro?

seria possivel colocar o bot para de 30 em 30 minutos +- verificar na barra de tarefas se o metamask esta aberto e clicar no x para fechar por que assim creio que reiniciara o ciclo do bot

**Comment by Gaboo134** [comment]
bom dia o meu esta acontecendo a mesma coisa

**Comment by MaikonDosSantos** [comment]
estou com o mesmo problema, notei que o que acontece, é que na hora de logar ele clicar em conect walet, mas quando abre o popup da metamask ele não clica no signin, e dali a pouco ele começa o ciclo de novo, clicando novamente em conect walet e vai acumulano na metamask as requisições e de signin

**Comment by MaikonDosSantos** [comment]
Erro no botão de assinatura.
#349

**Comment by fguide** [comment]
Veja linha 364 do index.py
> if clickBtn(images['select-wallet-2'], name='sign button', timeout=8):

Aumente o timeout de 8 para 15 ou 20. Aqui resolveu esse problema, o Sign demorava mais de 8 segundos aqui quando o server está lento e por isso o click ia pro lugar errado deixando o popup do metamask em 2ndo plano.

**Comment by MaikonDosSantos** [comment]
Meu bot nao conecta a carteira #344

**Comment by MaikonDosSantos** [comment]
> Veja linha 364 do index.py
> 
> > if clickBtn(images['select-wallet-2'], name='sign button', timeout=8):
> 
> Aumente o timeout de 8 para 15 ou 20. Aqui resolveu esse problema, o Sign demorava mais de 8 segundos aqui quando o server está lento e por isso o click ia pro lugar errado deixando o popup do metamask em 2ndo plano.

talvez pros amigos ai em cima resolva, no meu caso ele não clica mesmo. tenho que trocar a imagem do botão

**Comment by fguide** [comment]
> > Veja linha 364 do index.py
> > > if clickBtn(images['select-wallet-2'], name='sign button', timeout=8):
> > 
> > 
> > Aumente o timeout de 8 para 15 ou 20. Aqui resolveu esse problema, o Sign demorava mais de 8 segundos aqui quando o server está lento e por isso o click ia pro lugar errado deixando o popup do metamask em 2ndo plano.
> 
> talvez pros amigos ai em cima resolva, no meu caso ele não clica mesmo. tenho que trocar a imagem do botão

exato, a dica do botao é válida sim, o que eu sugeri ajudou no meu caso apenas quando o metamask demorava para abrir.

**Comment by pedrox97** [comment]
> Veja linha 364 do index.py
> 
> > if clickBtn(images['select-wallet-2'], name='sign button', timeout=8):
> 
> Aumente o timeout de 8 para 15 ou 20. Aqui resolveu esse problema, o Sign demorava mais de 8 segundos aqui quando o server está lento e por isso o click ia pro lugar errado deixando o popup do metamask em 2ndo plano.

tambem estou com o mesmo problema, como é que faço isso de aumentar o timeout em que pasta?
