### ISSUE TITLE
mss.exception.ScreenShotError

### ISSUE THREAD

**Issue by ojaneri** [mpcabete/bombcrypto-bot#360]
Alguem tem alguma ideia de como corrigir?

Linux, Gnome, Python3

![erro bombc](https://user-images.githubusercontent.com/9010906/146551126-7367d834-cc5c-49d8-a481-546e0d61a46b.PNG)

**Comment by fguide** [comment]
Tá acessando via VNC ou algo do tipo? Se for tem cara de não ter pego o display correto.

**Comment by ojaneri** [comment]
Retorno do comando xrandr 
RandR 1.5 not supported.

(Sim, via VNC)

**Comment by ojaneri** [comment]
Em tempo, rodando DISPLAY=:0 ou :2 ou 3, etc nem roda o bot...somente com =:1 e depois de uns segundos da o erro da primeira mensagem.

**Comment by fguide** [comment]
Sim, via VNC precisa exportar o display senao não vai funcionar, mas parece que você utiliza wayland, se for o caso não tenho experiência em wayland para ajudar a resolver com o wayland, mas posso sugerir que faça a instalação do xorg com algum WM (openbox por exemplo) e altere o .xstartup do vnc para utilizar o openbox. 

Dessa forma acredito que nao interfira em nada no uso da sua máquina. Outra alternativa se for máquina física, rodar o openbox em um tty separado e abrir browser e bot la.

**Comment by fguide** [comment]
Desculpe, acabei de ver o erro do Ranrd. Se você nao utiliza wayland, entao veja se consegue fazer downgrade do randr, provavelmente ajudaria.

**Comment by ojaneri** [comment]
Desativei o Wayland no /etc/gdm3/custom.conf e reiniciei, mas sem sucesso.

Vou tentando aqui e informo quando der certo, aceito mais sugestões :)

**Comment by fguide** [comment]
> Desativei o Wayland no /etc/gdm3/custom.conf e reiniciei, mas sem sucesso.
> 
> Vou tentando aqui e informo quando der certo, aceito mais sugestões :)

Você por acaso exportou o DISPLAY no arquivo de configuração do vnc? por ser via VNC precisa ser exportado ao iniciar o servidor, se fizer com ele já iniciado não vai funcionar.

**Comment by ojaneri** [comment]
Sim, testei exportando na config do VNC. Tambem troquei pro openbox. Mesmo erro e mesma situação.

**Comment by fguide** [comment]
Estranho, pelo vnc o xrandr --version ou xrandr --listmonitors também da erro?

Qual o server VNC? Tightvnc? Eu lembro de no passado ja ter tido um problema similar com ele por conta de ambientes gráficos e mudei para tigervnc.

**Comment by fguide** [comment]
Um exemplo que econtrei de arquivo xstartup, talvez ajude para comparar com seu atual.

```
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export DISPLAY=:1
#exec startxfce4
exec openbox

```
Mas se voce realmente tiver erros com xrandr o script vai falhar porque o mss usa dele para fazer o screenshot, é possível testar na máquina fisicamente para ver se o erro segue, se seguir é algo com teu ambiente grafico, e ja pode descartar o VNC

**Comment by ojaneri** [comment]
xrandr --version
xrandr program version       1.5.0
Server reports RandR version 1.1

xrandr --listmonitors
RandR 1.5 not supported

Testei com seu xstartup no ./vnc/ mas sem sucesso também :(

Cliente no Windows RealVNC, Servidor VNC (vnc4server), máquina virtual do Google.
Tentei inclusive export DISPLAY=:1 e abrir o Chromium / Firefox de outro console para ver se aparecia no X, e apareceu normalmente.

**Comment by fguide** [comment]
Você tentou iniciar o vncsever com -geometry ?

-geometry 1024x768 por exemplo

**Comment by ojaneri** [comment]
Com geometry mudada nem abriu o VNC. 

Mudei pro tightvncserver e obtive erro diferente:

>>---> Some configs can be found in the config.yaml file.
>>---> Home feature not enabled
Traceback (most recent call last):
  File "index.py", line 522, in <module>
    main()
  File "index.py", line 490, in main
    solveCaptcha()
  File "/home/janeri/bombcrypto-bot-main/captcha/solveCaptcha.py", line 302, in solveCaptcha
    screenshot = printSreen()
  File "/home/janeri/bombcrypto-bot-main/captcha/solveCaptcha.py", line 74, in printSreen
    with mss.mss() as sct:
  File "/home/janeri/.local/lib/python3.6/site-packages/mss/factory.py", line 41, in mss
    return linux.MSS(**kwargs)
  File "/home/janeri/.local/lib/python3.6/site-packages/mss/linux.py", line 308, in __init__
    raise ScreenShotError("No Xrandr extension found.")
mss.exception.ScreenShotError: No Xrandr extension found.

**Comment by fguide** [comment]
com tightvnc use a opcao -geometry e o xstartup abaixo e veja se resolve. Lembre também que voce precisa executar o script dentro da sessao do VNC (conectado pelo vnc), se for via ssh nao da certo

```
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export DISPLAY=:1
#exec startxfce4
exec openbox
```

**Comment by ojaneri** [comment]
> com tightvnc use a opcao -geometry e o xstartup abaixo e veja se resolve. Lembre também que voce precisa executar o script dentro da sessao do VNC (conectado pelo vnc), se for via ssh nao da certo
> 
> ```
> #!/bin/sh
> unset SESSION_MANAGER
> unset DBUS_SESSION_BUS_ADDRESS
> export DISPLAY=:1
> #exec startxfce4
> exec openbox
> ```

tightvncserver -geometry 1024x768
xstartup conforme indicado

Erro do Xrandr
---> Some configs can be found in the config.yaml file.
---> Home feature not enabled
Traceback (most recent call last):
File "index.py", line 522, in
main()
File "index.py", line 490, in main
solveCaptcha()
File "/home/janeri/bombcrypto-bot-main/captcha/solveCaptcha.py", line 302, in solveCaptcha
screenshot = printSreen()
File "/home/janeri/bombcrypto-bot-main/captcha/solveCaptcha.py", line 74, in printSreen
with mss.mss() as sct:
File "/home/janeri/.local/lib/python3.6/site-packages/mss/factory.py", line 41, in mss
return linux.MSS(**kwargs)
File "/home/janeri/.local/lib/python3.6/site-packages/mss/linux.py", line 308, in init
raise ScreenShotError("No Xrandr extension found.")
mss.exception.ScreenShotError: No Xrandr extension found.


:(

**Comment by fguide** [comment]
> > com tightvnc use a opcao -geometry e o xstartup abaixo e veja se resolve. Lembre também que voce precisa executar o script dentro da sessao do VNC (conectado pelo vnc), se for via ssh nao da certo
> > ```
> > #!/bin/sh
> > unset SESSION_MANAGER
> > unset DBUS_SESSION_BUS_ADDRESS
> > export DISPLAY=:1
> > #exec startxfce4
> > exec openbox
> > ```
> 
> tightvncserver -geometry 1024x768 xstartup conforme indicado
> 
> Erro do Xrandr ---> Some configs can be found in the config.yaml file. ---> Home feature not enabled Traceback (most recent call last): File "index.py", line 522, in main() File "index.py", line 490, in main solveCaptcha() File "/home/janeri/bombcrypto-bot-main/captcha/solveCaptcha.py", line 302, in solveCaptcha screenshot = printSreen() File "/home/janeri/bombcrypto-bot-main/captcha/solveCaptcha.py", line 74, in printSreen with mss.mss() as sct: File "/home/janeri/.local/lib/python3.6/site-packages/mss/factory.py", line 41, in mss return linux.MSS(**kwargs) File "/home/janeri/.local/lib/python3.6/site-packages/mss/linux.py", line 308, in init raise ScreenShotError("No Xrandr extension found.") mss.exception.ScreenShotError: No Xrandr extension found.
> 
> :(

Estranho, a única coisa que me vem a cabeça é que seja o mesmo problema que mencionei acima com o tighvnc, tente utilizar o tigervnc para testar, da mesma forma que fez com o tightvnc.

Tente rodar dentro do vnc, se funcionar é possivel chamar o terminal atraves do ssh no mesmo display do vnc.
