### ISSUE TITLE
Captcha identifica o numero mas não escolhe certo

### ISSUE THREAD

**Issue by Adguimar** [mpcabete/bombcrypto-bot#361]
Estou com um problema após a ultima atualização do bot, todas outras versões funcionavam perfeito! 

Porem essa versão estou tendo esse problema, consegue ver o numero certo do captcha porem a hora de escolher, escolhe errado!

Alguém teve esse problema e conseguiu resolver? Ou alguém sabe como resolver que possa me ajudar?

Desde já muitíssimo obrigado!

![Bot Error](https://user-images.githubusercontent.com/96298912/146557208-d7a1bbce-7688-4728-bd27-ef04202b22aa.png)

**Comment by Adguimar** [comment]
Alguém que esteja rodando e não tenha erro nenhum poderia me falar qual a versão do python que usa, falar o navegador que esta usando, qual a resolução da tela e se usa a tela maximizada ou e em janela.

**Comment by MathBogo** [comment]
Cara, usa a versão 3.9.9. Uso navegador brave. Uso a janela do navegador normal, sem maximizar. Remove todas as pastas do seu bot do computador. Baixa de novo e faz todo procedimento. Aconselho a trocar algumas imagens sem bordas tiradas diretamente do seu computador e substituir na pasta target.

**Comment by fguide** [comment]
> Cara, usa a versão 3.9.9. Uso navegador brave. Uso a janela do navegador normal, sem maximizar. Remove todas as pastas do seu bot do computador. Baixa de novo e faz todo procedimento. Aconselho a trocar algumas imagens sem bordas tiradas diretamente do seu computador e substituir na pasta target.

Exato, além disso, comparem se os prints estao minimamente parecidos com os mostrados em seu PC. Podem existir diferenças de configuração de cores, fontes, configs de VGA, etc.

**Comment by LRBarbieri** [comment]
> Alguém que esteja rodando e não tenha erro nenhum poderia me falar qual a versão do python que usa, falar o navegador que esta usando, qual a resolução da tela e se usa a tela maximizada ou e em janela.

Uso Google Chrome, navegador em metade da tela e na outra metade o bot, 2560x1080, python é o 3.9.9 se não me engano. Única imagem que mudei foi a de sign wallet
