### ISSUE TITLE
Doação e agradecimento aos dev

### ISSUE THREAD

**Issue by MathBogo** [mpcabete/bombcrypto-bot#362]
Passando pra lembrar a todos que devemos ser gratos aos devs e toda a comunidade. Sem ajuda deles nada seria possível e não estaríamos usufruindo desse lindo projeto. Para continuarmos com o projeto e levarmos a adiante, vamos ajudar nas doações nem que seja 1$ dólar. Alias… o proprio projeto está nos ajudando a ganhar dinheiro. Que tal parar um pouco e fazer aquela doação ? Nem que seja mínima. Está rodando tudo perfeito aqui na minha máquina. Inclusive fiz alguns ajustes que estão disponíveis aí nós PULL REQUEST. Implementei multi account. Usa em todos navegadores. Valeu galera. Bora pra cima. Antes de perguntar, tente procurar soluções já respondidas.

**Comment by fguide** [comment]
E pra quem ainda está buscando recuperar o investimento e não pode doar, lembre que nem toda ajuda é financeira, se não puder contribuir com moedas contribua com seu tempo e prestatividade em ajudar no que for possível.

**Comment by far0fa** [comment]
Nao to conseguindo ver essas atualizações MathBogo, consegue me ajudar?

**Comment by backslash-f** [comment]
Doei 50 euros dia desses e vou doar mais assim que o lucro for entrando. Ótimo trabalho mesmo desses LINDOS. ❤️

**Comment by MathBogo** [comment]
> Nao to conseguindo ver essas atualizações MathBogo, consegue me ajudar?

Ali em cima tem as opções: code - issue - pull request. No code e o repositório do projeto. Lá você pode baixar a última versão em .zip. Issue fica os problemas dos usuários e em pull request. Fica algumas funções feitas por outros desenvolvedores. Lá você pode pegar algumas e implantar no script caso ela ainda não foi implementado no repositório do projeto. Nessas abas também tem opção « closed » referente a tópicos que já foram fechados mas você ainda pode usar e usufruir.

**Comment by FDNiisan** [comment]
Já fiz a boa... e sempre que sobrar vou mandar nem que 10 conto pro cara...

Seloko.. posso dormir em paz enquanto o bot faz o turno da noite

**Comment by kerferber** [comment]
Eu recebo dia 20 e vou doar tbm, virei aqui confirmar! Merecem!
