### ISSUE TITLE
Erro Select Wallet 2

### ISSUE THREAD

**Issue by csr1995** [mpcabete/bombcrypto-bot#363]
Traceback (most recent call last):
  File "C:/Bomb/index.py", line 522, in <module>
    main()
  File "C:/Bomb/index.py", line 499, in main
    login()
  File "C:/Bomb/index.py", line 364, in login
    if clickBtn(images['select-wallet-2'], name='sign button', timeout=8):
KeyError: 'select-wallet-2'

Alguem sabe como resolver?

**Comment by mpcabete** [comment]
parace q vc n tem o arquivo "select-wallet-2" da pastar targets, da uma olhada la, eh esse arquivo aki:
https://github.com/mpcabete/bombcrypto-bot/blob/main/targets/select-wallet-2.png

**Comment by csr1995** [comment]
tem o arquivo sim
![image](https://user-images.githubusercontent.com/77343794/146619544-1e2a59cf-b13d-498c-bebf-d64853ae16f2.png)

ja fiz todos os testes possiveis, mas ainda quebra nessa parte kkk

**Comment by csr1995** [comment]
Consegui resolver.
Voltei o codigo pra versão anterior nessa etapa.

    if clickBtn(sign_btn_img, name='sign button', timeout=8):
        # sometimes the sign popup appears imediately
        login_attempts = login_attempts + 1
        if clickBtn(teasureHunt_icon_img, name='teasureHunt', timeout = 15):
            login_attempts = 0
        # time.sleep(15)
        return
        # click ok button
