### ISSUE TITLE
Sugestão Captcha

### ISSUE THREAD

**Issue by rsilveira91** [mpcabete/bombcrypto-bot#364]
Já notei que com ou sem robô o captcha é invalido qndo vc vai direto a resposta certa.
seria interessante implementar uma rolagem do inicio até o fim e do fim até o inicio antes de selecionar a resposta correta.

vlw.

**Comment by fguide** [comment]
Não acho que valha o esforço, ao meu ver isso é um erro do próprio captcha que devem arrumar (ou não). 

Eu já vi esse problema algumas vezes, mas não com frequência, por isso acredito ser um problema lá.
