### ISSUE TITLE
Bot simplesmente reconhece o número no Captcha e marca o errado sempre

### ISSUE THREAD

**Issue by Ricardoadlj** [mpcabete/bombcrypto-bot#367]
Já não sei oq fazer mais, troquei a png robot da pasta, já instalei a versão 3.9.9 do python e nada, o bot continua errando o captcha mesmo reconhecendo o número

**Comment by kerferber** [comment]
Aqui funcionando 100% amigo. Poucas vezes ele erra. Pouquíssimas, ou seja, o problema não está no algoritmo.

Tente desinstalar o python, limpar os caches, alterar o zoom do navegador, trocar de computador, e em último caso formate o windows pois o código está funcional. Tente tbm alterar as variáveis de treshold no arquivo de configuração....

**Comment by mpcabete** [comment]
@Ricardoadlj vc ta usando a ultima versão do bot? eu subi um update a uns 30 min q talvez resolva seu problema

**Comment by jeanvetorello** [comment]
essa ultima versao que parece que está zuado, versão anterior estava filé..

**Comment by fx2016** [comment]
> essa ultima versao que parece que está zuado, versão anterior estava filé..

Exatamente, essa última aqui não faz login, a anterior estava redonda, dava alguns erros de leitura do captcha, mas muito pouco. Essa não roda. @mpcabete @Nucito

**Comment by Galinho90** [comment]
Bot não reconhce de nenhum jeito o botão Sign, ja tentei de todas as formas alterar o print de nada.

**Comment by fx2016** [comment]
> Bot não reconhce de nenhum jeito o botão Sign, ja tentei de todas as formas alterar o print de nada. 

Também fiz de tudo, troquei imagens mas não tem jeito, voltei para anterior, que apesar de não resolver as vezes o captcha, funciona!

**Comment by amatoxd** [comment]
tentem mudar o idioma da metamask para inglês. aqui a última versão está funcionando perfeitamente (login, sign, TUDO), inclusive numa maquina virtual que deixa tudo mais lento.

**Comment by Galinho90** [comment]
> tentem mudar o idioma da metamask para inglês. aqui a última versão está funcionando perfeitamente (login, sign, TUDO), inclusive numa maquina virtual que deixa tudo mais lento.

Essa ultima versão cmg não funcionou eu tive de usar a versão anteriormente, que é o que esta dando certo e mais funcional. fiz de tudo para fazer o sign e nada .

**Comment by mpcabete** [comment]
no final o captcha funcionou nessa ultima versao @Ricardoadlj ?

**Comment by Galinho90** [comment]
> no final o captcha funcionou nessa ultima versao @Ricardoadlj ?

O captcha funciona, mas ele não assina de jeito nenhum nem trocando os prints. Tentei de tudo, voltei pra versão anterior, mesmo ele errando o captcha , ainda roda melhor.

**Comment by Nucito** [comment]
> > essa ultima versao que parece que está zuado, versão anterior estava filé..
> 
> Exatamente, essa última aqui não faz login (não clica em "sign" na metamask), a anterior estava redonda, dava alguns erros de leitura do captcha, mas muito pouco. Essa não roda. @mpcabete @Nucito

Amigo essa versão do captcha não é de minha autoria 😁

**Comment by fx2016** [comment]
> > > essa ultima versao que parece que está zuado, versão anterior estava filé..
> 
> > 
> 
> > Exatamente, essa última aqui não faz login (não clica em "sign" na metamask), a anterior estava redonda, dava alguns erros de leitura do captcha, mas muito pouco. Essa não roda. @mpcabete @Nucito
> 
> 
> 
> Amigo essa versão do captcha não é de minha autoria 😁

Perfeito, compreendido e registrado. Desculpe qualquer inconveniente, abraço!
