### ISSUE TITLE
Máquina Virtual

### ISSUE THREAD

**Issue by lucasdr98** [mpcabete/bombcrypto-bot#368]
Gostaria de saber se alguém esta rodando o bot dentro de uma máquina virtual, eu tenho duas contas e todas maquinas virtuais que usei apresentaram desempenho horrível (mesmo meu pc tendo boas configurações). Atualmente eu estou utilizando apenas o script que resolve o captcha em conjunto com o Pulover's Macro pra rodar as duas contas. Desde já agradeço de coração aos devs pelo excelente trabalho.

**Comment by fguide** [comment]
Sim, funciona bem pra mim, claro que não dá pra esperar milagres, por exemplo, uma VM com baixos recursos rodando Win10 com aceleração 3d, com outras coisas abertas, extensões no browser, etc.

Você tem que ajustar ao que tem, se a VM tem poucos recursos, tente desabilitar o uso de 3d no navegador, por exemplo. Use outro sistema operacional, ou tente alocar mais recursos.

Ajudaria também saber qual o virtualizador você usa, se está virtualizando máquina 64 ou 32, etc...

**Comment by brim001** [comment]
Rodo 2 Contas em VM. Cada conta na sua própria VM. Script funciona normal aqui!
Core i5-9400 16gb

**Comment by rzanca** [comment]
Utilize Docker, muito mais leve e eficiente que uma VM, #192.

**Comment by Jackcar** [comment]
Vc pode configurar uma VM do Google Cloud, eles dão credito para vc testar por alguns meses, assim vc poupa de ficar gastando seu pc pessoal.
