### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by Philippuchetti** [mpcabete/bombcrypto-bot#37]
gostaria de tirar umas duvidas contigo no discord e se me ajudar te da uns bcoins pela ajuda ainda nao utilizei apenas tenho umas duvidas antes de utilizar, me adiciona la PhilipUsVip#5724

**Comment by MMotenai** [comment]
Também gostaria de saber quanto cobra pra adicionar alguns comandos ao bot pra deixar ele um pouco mais lucrativo!!
a ideia seria ativar os epicos somente quando tiver baus de cristal,ouro e jaula, isso deixando eles ativos apenas até 20% da vida dos baus de  cristal e ouro , e ativos até quebrar a jaula
