### ISSUE TITLE
VM no Google Cloud

### ISSUE THREAD

**Issue by mariosss2** [mpcabete/bombcrypto-bot#371]
Alguém usando o bot com VM no Google Cloud? Se sim, quais configurações de instância usaram? Nunca criei uma e tô na dúvida sobre que OS usar, quais as configurações do dispositivo virtual, que navegador usar por lá (caso seja alguma versão de linux) e como configurar a metamask por lá.

**Comment by sbragnot** [comment]
Depois de testar algumas vezes estou usando vcpu16ram16 windows server 2019, navegador brave, não consegui usar outro sistema pelo simples fato de não saber implementar a interface gráfica, tentei milhares de vezes, tentei máquinas menos potentes mas o navegador trava muito

**Comment by fguide** [comment]
Pessoal

> Depois de testar algumas vezes estou usando vcpu16ram16 windows server 2019, navegador brave, não consegui usar outro sistema pelo simples fato de não saber implementar a interface gráfica, tentei milhares de vezes, tentei máquinas menos potentes mas o navegador trava muito

Windows server pra aplicações gráficas vai consumir muitos recursos mesmo, sugiro testar alternativas baeadas em linux pois a otimização é muito melhor. Eu por exemplo rodo em uma VM com 2 vcpus e 2gb de ram, não é o ápice de performance, mas roda o bot sem problemas, que é meu intuito.

**Comment by sbragnot** [comment]
> Pessoal
> 
> 
> 
> > Depois de testar algumas vezes estou usando vcpu16ram16 windows server 2019, navegador brave, não consegui usar outro sistema pelo simples fato de não saber implementar a interface gráfica, tentei milhares de vezes, tentei máquinas menos potentes mas o navegador trava muito
> 
> 
> 
> Windows server pra aplicações gráficas vai consumir muitos recursos mesmo, sugiro testar alternativas baeadas em linux pois a otimização é muito melhor. Eu por exemplo rodo em uma VM com 2 vcpus e 2gb de ram, não é o ápice de performance, mas roda o bot sem problemas, que é meu intuito.

Cara se puder me indicar algum tutorial ou até mesmo dar umas dicas de como fazer, eu já pesquisei muito tentei alguns processos e não consegui fazer dar certo em nada que não seja windows

**Comment by kalleldf** [comment]
> Pessoal
> 
> > Depois de testar algumas vezes estou usando vcpu16ram16 windows server 2019, navegador brave, não consegui usar outro sistema pelo simples fato de não saber implementar a interface gráfica, tentei milhares de vezes, tentei máquinas menos potentes mas o navegador trava muito
> 
> Windows server pra aplicações gráficas vai consumir muitos recursos mesmo, sugiro testar alternativas baeadas em linux pois a otimização é muito melhor. Eu por exemplo rodo em uma VM com 2 vcpus e 2gb de ram, não é o ápice de performance, mas roda o bot sem problemas, que é meu intuito.

pode explicar o processo?

**Comment by fguide** [comment]
Eu não uso GCP, por isso não tenho muita familiaridade, mas o processo é o mesmo para qualquer plataforma:

Crie uma VM com linux, instalacao minima sem interface gráfica e pacotes desnecessários
Instale um abiente grafico leve, configure o VNC ou algum outro tipo de acesso remoto
Acesse via VNC ou configure o noVNC que possibilita fazer o acesso via HTML5

Eu dei uma olhada rapida no tutorial abaixo e parece ser bem completo, talvez ajude:

https://fatorbinario.com/linux-acessando-a-interface-grafica-do-vps-via-vnc/
