### ISSUE TITLE
Sign - Pós Captcha

### ISSUE THREAD

**Issue by rsilveira91** [mpcabete/bombcrypto-bot#373]
Achei q nessa atualização o Bot do Captcha ficou muito bom.
porem não sei pq começou a pular a etapa do "sign" da Metamask, indo direto para "refresh heroes".
não sei se está sendo somente aki este problema.

**Comment by espinozachristian** [comment]
no meu pc estava normal, no pc da minha namorada nao esta indo o sign, estava até tentando resolver porem sem sucesso...nao sei se é o tempo de resposta da internet dela, mesmo dando um time sleep e aumentando o timeout ainda assim nada...

**Comment by rsilveira91** [comment]
> no meu pc estava normal, no pc da minha namorada nao esta indo o sign, estava até tentando resolver porem sem sucesso...nao sei se é o tempo de resposta da internet dela, mesmo dando um time sleep e aumentando o timeout ainda assim nada...

Pois é, tambem tentei algumas modificações.
só nao tentei trocar de navegador ainda.

**Comment by Ricardoadlj** [comment]
Mesmo problema aqui

**Comment by Lucao-pl** [comment]
Em 2 PCs está normal já em outro acontece mesma coisa, aperta para iniciar mais quando aparece o sign ele simplesmente ignora

**Comment by mribeirox** [comment]
Aqui também está com um problema no Sign ... já alterei as imagens, já cortei borda, já deixei borda e ainda não consegui. Alguém por aí já conseguiu resolver esse problema?

**Comment by Lucao-pl** [comment]
> Aqui também está com um problema no Sign ... já alterei as imagens, já cortei borda, já deixei borda e ainda não consegui. Alguém por aí já conseguiu resolver esse problema?

Estou trocando o navegador para ver se vai

**Comment by Ricardoadlj** [comment]
Troquei de navegador e deu na mesma :/

**Comment by Lucao-pl** [comment]
> Troquei de navegador e deu na mesma :/

Tenta diminuir ou aumentar a resolução da tela

**Comment by mpcabete** [comment]
Pessoal, acredito que encontrei o problema, da uma testada.

**Comment by mpcabete** [comment]
Basicamente o problema que eu encontrei testando aki, é que ele imediatamente apos clickar no connect-wallet tentava fazer o captcha, mas nao encontrava ele pq n dava tempo do popup aparecer. Dai ele ignorava e dava sequencia no processo de login sem fazer o captcha.

**Comment by mribeirox** [comment]
> Pessoal, acredito que encontrei o problema, da uma testada.

Foi liso demais agora @mpcabete!

**Comment by Ricardoadlj** [comment]
@mpcabete aqui funcionou demais, valeu mano

**Comment by rodrigobragamg** [comment]
Bem maluco. Em um PC, liso no Chrome, FF e Brave. No outro, Chrome e FF.  E em um, no Chrome, tive que  trocar o robot.png na pasta captcha, não  reconhece o original.

**Comment by fguide** [comment]
> Bem maluco. Em um PC, liso no Chrome, FF e Brave. No outro, Chrome e FF. E em um, no Chrome, tive que trocar o robot.png na pasta captcha, não reconhece o original.

Não é tão maluco assim, cada computador tem configurações diferentes e por isso a necessidade de ajustes, é bem dificil soluções do reconhecimento gráfico que funcione 100% para todos os cenários.

**Comment by espinozachristian** [comment]
> Basicamente o problema que eu encontrei testando aki, é que ele imediatamente apos clickar no connect-wallet tentava fazer o captcha, mas nao encontrava ele pq n dava tempo do popup aparecer. Dai ele ignorava e dava sequencia no processo de login sem fazer o captcha.

eu tinha modificado para segurar adicionar dentro da função do conect wallet ele ja dar um sleep e em seguida ir para o sign in xD
mas vlw vou testar sua forma 🍡
