### ISSUE TITLE
how can i set up the bot for 2 accounts ?

### ISSUE THREAD

**Issue by hamzalamou** [mpcabete/bombcrypto-bot#374]

**Comment by hamzalamou** [comment]
HELLO guys does someone know how to et up the bot for 2 accounts ?

**Comment by rsilveira91** [comment]
utilizando Maquina Virtual.

**Comment by rsilveira91** [comment]
using Virtual Machine.

**Comment by hamzalamou** [comment]
> using Virtual Machine.

Okey thanks

**Comment by kalleldf** [comment]
qual virtual machine que vocês estão usando?

**Comment by ricardofernandess** [comment]
There's also a PR open to use containers instead of VM's if you prefer

**Comment by PinnDeath6** [comment]
im using pygetwindow to control 2 accounts in unique computer(no using vm)

**Comment by hamzalamou** [comment]
> There's also a PR open to use containers instead of VM's if you prefer

where can i find that

**Comment by hamzalamou** [comment]
> 

how to use that bro if you dont mind

**Comment by hamzalamou** [comment]
> im using pygetwindow to control 2 accounts in unique computer(no using vm)

how to use that bro if you dont mind

**Comment by marcelosore** [comment]
I use this one with 3 accounts, but it works with 2 too.
https://github.com/mfsousa/bombcrypto-bot

**Comment by hamzalamou** [comment]
> I use this one with 3 accounts, but it works with 2 too. https://github.com/mfsousa/bombcrypto-bot

Can you show me how to set a delay for the bot to execute a command on each account

**Comment by marcelosore** [comment]
just edit config.yaml and run again

**Comment by hamzalamou** [comment]
> just edit config.yaml and run again

What to set in config.yaml if you dont mind
Im confused

**Comment by cesarmdev** [comment]
> I use this one with 3 accounts, but it works with 2 too. https://github.com/mfsousa/bombcrypto-bot

The game needs to be in full screen mode on the explorer or side by side?

**Comment by MochilaEstilosa** [comment]
> > I use this one with 3 accounts, but it works with 2 too. https://github.com/mfsousa/bombcrypto-bot
> 
> The game needs to be in full screen mode on the explorer or side by side?

Full screen. It doesn’t work if you set the windows side by side
