### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Alekseyzhm** [mpcabete/bombcrypto-bot#376]
I updated the bot to the latest version and ran into a problem when the bot does not solve the captcha and exits in the following way. I also want to express my deep gratitude to the developers for the work done, thank you very much.
I don't know what to do, bots are on virtual machines with Windows 10

C:\Users\aleks\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:2157.)
return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined]
dig: , background_digits: None
dig: , background_digits: None
dig: , background_digits: None
dig: , background_digits: None
dig: , background_digits: None
.
[2021-12-17 09:53:43] => 💪 48 heroes sent to work
[2021-12-17 09:53:43] => ⬆️ Processing last action.....[[270 135 501 47]]
no slider

![telegram-cloud-photo-size-2-5328036329918937244-y](https://user-images.githubusercontent.com/73239686/146634131-74f2a85a-3283-4ff7-b32b-e5d7a1cff1b1.jpg)

Everything else works fine, but captcha does not solve

**Comment by fguide** [comment]
You are using Python 3.8, install 3.9 as torch will only work with this version.

**Comment by Alekseyzhm** [comment]
> 

I installed python version 3.9.9 and still get this error
![telegram-cloud-photo-size-2-5328036329918937502-y](https://user-images.githubusercontent.com/73239686/146646515-1abf7a5c-50a5-441b-bc66-ea0ec9fb4798.jpg)

**Comment by Alekseyzhm** [comment]
> You are using Python 3.8, install 3.9 as torch will only work with this version.

I installed python version 3.9.9 and still get this error

![telegram-cloud-photo-size-2-5328036329918937502-y](https://user-images.githubusercontent.com/73239686/146646604-0c358d8e-31af-408d-9649-bb6f2ec0c571.jpg)

**Comment by fguide** [comment]
This warning can be ignored. Question: is your game in english?
I see ti detects the captcha but cannot read it. Check for screen resolution, window scaling, zoom, etc. Also, check if your browser is in Russian, not sure if that would interfere but it is worth a check.

Check on #334 where there was an error with russian charset, it does not look like your problem but it may help you.

> Для русскоговорящих, те кто столкнулся с этой проблемой, что я сделал:
> 
>     Создал нового пользователя в Винде, с английским регистром.
>     Скачал 3.9.9 Питон
>     Сначала установил pip install wheel, как написано в ссылке у того парня, который мне помог
>     Обновил какую-то шляпу. Мне написало, что есть типо шляпа поновее. Честно не помню, как эта хрень называлась, написано было желтым, там инструкции пишут.
>     upd. Вспомнил, как эта шляпа называлась, на своём скрине увидел - У меня была установлена пип версия 21.2.4 , а я установил 21.3.1. Просто прописал "pip install --upgrade pip" - вроде так
>     Ну и собственно установил бота, без всяких красных и желтых сообщений.
>     Удачи!

**Comment by Alekseyzhm** [comment]
> This warning can be ignored. Question: is your game in english? I see ti detects the captcha but cannot read it. Check for screen resolution, window scaling, zoom, etc. Also, check if your browser is in Russian, not sure if that would interfere but it is worth a check.
> 
> Check on #334 where there was an error with russian charset, it does not look like your problem but it may help you.
> 
> > Для русскоговорящих, те кто столкнулся с этой проблемой, что я сделал:
> > ```
> > Создал нового пользователя в Винде, с английским регистром.
> > Скачал 3.9.9 Питон
> > Сначала установил pip install wheel, как написано в ссылке у того парня, который мне помог
> > Обновил какую-то шляпу. Мне написало, что есть типо шляпа поновее. Честно не помню, как эта хрень называлась, написано было желтым, там инструкции пишут.
> > upd. Вспомнил, как эта шляпа называлась, на своём скрине увидел - У меня была установлена пип версия 21.2.4 , а я установил 21.3.1. Просто прописал "pip install --upgrade pip" - вроде так
> > Ну и собственно установил бота, без всяких красных и желтых сообщений.
> > Удачи!
> > ```

I am very grateful to you for your help, although the solution was completely different, but thank you very much
