### ISSUE TITLE
Bot not running

### ISSUE THREAD

**Issue by soundsticks** [mpcabete/bombcrypto-bot#377]
I have configure all the setting but seem it doesn't defect anything from my browser. 

https://ibb.co/TK3b4fb

https://ibb.co/N9qBV1k

**Comment by Alekseyzhm** [comment]
I, too, now even stopped starting

**Comment by fguide** [comment]
Can you please check if the screenshot saved under /targets/robot.png matches visually with what you see in the game? You can try replacing it by a screenshot taken from your device.

**Comment by soundsticks** [comment]
Ya, I had replace the existing image, but still stuck in reveal number
