### ISSUE TITLE
Background captcha não detectando.

### ISSUE THREAD

**Issue by jeanvetorello** [mpcabete/bombcrypto-bot#378]
Venho sofrendo com isso que o bot não esta reconhecendo o background e está acertando só Chute e demorando para passar

alguem sabe como poderia fazer um tratamento se o background estiver vazio passar outra vez ou dar um f5 ?

ou como posso melhorar esse background.

![Captura de Tela 2021-12-18 às 09 52 12](https://user-images.githubusercontent.com/12627128/146641783-cda665b8-60e0-443f-8d90-40de8e5fbf75.png)

**Comment by MauMorhy** [comment]
> Venho sofrendo com isso que o bot não esta reconhecendo o background e está acertando só Chute e demorando para passar
> 
> alguem sabe como poderia fazer um tratamento se o background estiver vazio passar outra vez ou dar um f5 ?
> 
> ou como posso melhorar esse background.
> 
> ![Captura de Tela 2021-12-18 às 09 52 12](https://user-images.githubusercontent.com/12627128/146641783-cda665b8-60e0-443f-8d90-40de8e5fbf75.png)

Ele se move na area mas não reconhece o número branco né?
Se for... to com esse problema tb

**Comment by espinozachristian** [comment]
pode acontecer...ja rolou umas 2x comigo, mas é baixo a chance disso acontecer é bem eventual, dai ele vai entrar novamente no loop e tentar novamente
