### ISSUE TITLE
Bot fica parado no captchar

### ISSUE THREAD

**Issue by lafaete0803** [mpcabete/bombcrypto-bot#379]
![image](https://user-images.githubusercontent.com/96341625/146642889-40c88c8b-accb-4e33-8a72-b9e12ef16e6d.png)
simplismente fica parado no captchar e nao faz nada

**Comment by fguide** [comment]
Eu vi um outro issue parecido com windows 11, não sei se tem alguma relação, mas, você comparou os prints que estao na pasta targets em especial o robot.png ? Veja se tem diferenças visíveis e tente substituir com um print tirado no seu pc.

**Comment by lafaete0803** [comment]
continua o erro

no captchar popup fond

![image](https://user-images.githubusercontent.com/96341625/146649880-cb97915d-00ca-4013-8d61-c8411d73769d.png)

**Comment by w4ll3ns** [comment]
também estou com o mesmo problema aqui :((

**Comment by PinnDeath6** [comment]
o bot funcionava normal e do nada parou? verifique as ultimas atualizações do windows e desinstale

**Comment by w4ll3ns** [comment]
Consegui resolver aqui tirando um novo print no jogo e substituindo o arquivo na pasta do jogo C:\PastaDoBot\captcha\images\robot.png

O novo print é esse abaixo, copie e cole talvez funcione no de vocês tbm

![robot](https://user-images.githubusercontent.com/96354596/146674502-657b4436-1c3c-40de-8367-345b5be2d51c.png)
