### ISSUE TITLE
Não está reconectando a conta!

### ISSUE THREAD

**Issue by rafarfr** [mpcabete/bombcrypto-bot#38]
Tudo bem, amigo? Primeiro muito obrigado pela script, contudo, ao dar erro unknow, ou manual, ou qualquer coisa que volte à tela de conectar a wallet o script reconhece o botão laranja de reconectar, mas a caixa branca com a seleção da carteira (no meu caso a metamask) é ignorada e os passos seguintes por consequência não são realizados, como eu poderia resolver essa situação?

**Comment by matheusgm0** [comment]
salve, eu refiz o print do metamask tentando deixar apenas as escritas e coloquei default e selecionar wallet bullet pra 0.9... tenta o mesmo que aqui resolveu

**Comment by rafarfr** [comment]
Opa, salve amigo, consegui resolver com isso mesmo que vc me indicou, valeuuu!!
