### ISSUE TITLE
Error of Install in VM | Erros de Instalação na VM

### ISSUE THREAD

**Issue by Nucito** [mpcabete/bombcrypto-bot#381]
**Português:**

Venho aqui para pedir encarecidamente para que parem de postar os erros de instalação como se fossem erros do programa, pois em 90% dos casos isso é um erro de configuração na VM.
Antes de fazer a postagem verifique se o erro persiste se você executa em sua maquina... se todo mundo ficar misturando esse tipo de coisa dificulta ate mesmo para dar suporte para bugs do próprio bot😅
Aqui vai uma lista de possíveis bugs em sua VM:

- Disco insuficiente: Tente alocar um pouco mais de espaço para a sua VM
- CPU não esta suportando executar com o nível de cores que você customizou: Tente aumentar a quantidade cores para poder compensar.
- Memoria RAM Insuficiente: Como o próprio nome presume... tente aumentar a quantidade de memoria ram que você destinou para sua VM
- Qualquer erro no python: Verifique se a versão do python que você esta usando é suportada pelo bot.
- Meu bot não reconhece a image: Vá nos arquivos de configuração e diminua o valor threshold.

ERROS: 
> cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'
 
Esse erro acontece quanto o formato da imagem não é o mesmo tipo que você especifiou... Para corrigir esse erro no PNG recomendo usar um programa chamado [PngCrush](https://github.com/Kjuly/pngcrush) use essas opções: 
**pngcrush -ow -rem allb -fix -force NOMEDAIMAGE.png**

Obs: Sei que vai ter pessoas perguntando então vou logo deixar aqui: **VM = Maquina Virtual.**

--------------------------------------------------------------------------------------------------------------------------------------

**English:**

I come here to kindly ask them to stop posting installation errors as if they were program errors, because in 90% of cases this is a configuration error in the VM.
Before posting, check if the error persists if you run it on your machine... if everyone keeps mixing this kind of thing, it makes it difficult to even support bugs from the bot😅
Here's a list of possible bugs in your VM:

- Insufficient disk: Try to allocate a little more space for your VM
- CPU is not supporting running with the level of colors you customized: Try increasing the amount of colors to compensate.
- Insufficient RAM Memory: As its name assumes... try to increase the amount of ram you have allocated to your VM
- Any errors in python: Check if the python version you are using is supported by the bot.
- My bot doesn't recognize the image: Go to the configuration files and decrease the threshold value.

ERROR: 
> cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

This error happens when the image format is not the same type as you specified... To fix this error in PNG I recommend using a program called [PngCrush](https://github.com/Kjuly/pngcrush) use these options:
**pngcrush -ow -rem allb -fix -force IMAGENAME.png**

Note: I know there will be people asking so I'll just leave it here: **VM = Virtual Machine.**

**Comment by fguide** [comment]
Problema comum com VM e linux: torch instala por padrao a versao GPU, se a VM não tiver dá erro, precisa instalar a versão CPU:

> pip3 install torch==1.10.0+cpu torchvision==0.11.1+cpu torchaudio==0.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html

**Comment by cocdcay26** [comment]
Muito inteligente

**Comment by Nucito** [comment]
Ainda tem pessoas olhando esse repo? 😅
