### ISSUE TITLE
[DUVIDA] como adiciono no meu bot as atualizações enviadas por outras pessoas no pull request?

### ISSUE THREAD

**Issue by 00foca00** [mpcabete/bombcrypto-bot#384]
vi que tem features interessantes que as pessoas adicionaram e algumas já verificadas. como faço pra adiciona-las ao meu bot?

**Comment by Nucito** [comment]
[Isso pode te ajudar](https://stackoverflow.com/questions/14947789/github-clone-from-pull-request) Você precisaria clonar o pull request que a pessoa fez diretamente no seu diretório, pois somente o autor do repo pode aceitar se coloca essa feature no código ou não.
