### ISSUE TITLE
no captchar popup found

### ISSUE THREAD

**Issue by lafaete0803** [mpcabete/bombcrypto-bot#386]
meu bot faz tudo certo , menos o captchar , quando aparece ele nao reconhece , nem tenta fazer nada, fica parado

no captchar popup found

ja alterei as prints varias vz, mudei a versao do phyton, reinstalei varias vezes, 

outra coisa da erro ao iniciar o bot com python3 , tenho q usar somente python

se alguem tiver a solucao por favor me ajude, obrigado

**Comment by fguide** [comment]
Por favor, qual o resultado de python -V ?

Você também precisa comparar o arquivo robot.png na pasta targets e ver se está parecido com o da sua tela, você pode substituir o arquivo por um capturado em sua máquina.

**Comment by Gaboo134** [comment]
estou com o mesmo problema já alterei a imagem do robot, com o print da minha tela, já alterei a imagem do slider, e ate agora sem solução, se alguém puder me dar mais alguma dica de como conseguir, obrigado desde já.
sobre o python3 também não deu certo rodar, estou colocando python index.py (sem o 3 será q pode ser isso ou o python3 foi erro de digitação)

**Comment by Gaboo134** [comment]
meu python -V é 3.9.9

**Comment by PinnDeath6** [comment]
tem que fazer umas modificações no arquivo solvecaptcha, dois clientes meus estão com o mesmo problema.

**Comment by fguide** [comment]
> tem que fazer umas modificações no arquivo solvecaptcha, dois clientes meus estão com o mesmo problema.

Quais?

Vejam: #379, caso parecido que foi resolvido alterando o robot.png

**Comment by w4ll3ns** [comment]
> > tem que fazer umas modificações no arquivo solvecaptcha, dois clientes meus estão com o mesmo problema.
> 
> Quais?
> 
> Vejam: [# 379](https://github.com/mpcabete/bombcrypto-bot/issues/379) , caso parecido que foi resolvido alterando o robot.png

Consegui resolver aqui tirando um novo print no jogo e substituindo o arquivo na pasta do jogo C:\PastaDoBot\captcha\images\robot.png

O novo print é esse abaixo, copie e cole talvez funcione no de vocês tbm

![robot](https://user-images.githubusercontent.com/96354596/146680407-e9ddc827-992a-4bbc-ad3e-1b009ca5d9c7.png)
t
