### ISSUE TITLE
Clique sobre botão do menu de heróis falhando

### ISSUE THREAD

**Issue by joaovictor7** [mpcabete/bombcrypto-bot#387]
O clique sobre o botão de heróis anda falhando frequentemente aqui comigo. O mouse chega a ser arrastado para o botão, mas não efetua o clique.

**Comment by joaovictor7** [comment]
Já descobri oque é. na linha 366 nunca subam de mais o "timeout". Aqui no meu caso estava com o valor = 20.

**Comment by fguide** [comment]
Pode ser vários motivos, lentidão do jogo por exemplo. Você viu algum erro no cmd?

**Comment by joaovictor7** [comment]
> Pode ser vários motivos, lentidão do jogo por exemplo. Você viu algum erro no cmd?

No cmd não aparece nenhum erro. Não acho que seja lentidão pois o jogo tá estável aqui já tem quase 2 dias. 
Percebi tb que o problema ocorre a partir da segunda execução.
Detalhe: minhas configs são um pouco diferente das default 

sends_heroes_for_work: 5
refresh_heroes_positions: 9
select_heroes_mode: full

**Comment by fguide** [comment]
Não tive esse problema, o seu click funciona em outras funções, pra fazer refresh dos herois por exemplo?

No arquivo config.yaml voce pode tentar alterar o parametro 'go_to_work_btn' conforme indicado lá e ver se ajuda em algo.

**Comment by joaovictor7** [comment]
Em outros clicks funciona.
Eu diminui o intervalo de busca de heróis disponíveis para 5 mas mesmo assim n adiantou.
Depois de um tempo ele até consegue clicar no botão de heróis e colocar eles pra trabalhar. Mas até chegar lá já se foram umas 3 ou 4 tentativas com intervalos de 5 min entre cada uma

**Comment by fguide** [comment]
Se os  clicks funcionam em outras funcoes e o botao é detectado eu fico sem ideias, como disse só me ver a cabeça agora alterar  'go_to_work_btn' e ver como o bot se comporta.

**Comment by pedrozun** [comment]
Esta acontecendo o mesmo comigo.

**Comment by fguide** [comment]
Alguem testou modificar o 'go_to_work_btn' para saber se melhora?

**Comment by joaovictor7** [comment]
Sim já abaixei o 'go_to_work_btn' para 0.4 e ainda continua falhando os clicks aqui

**Comment by leoweabo** [comment]
Estou com o mesmo problema, até ontem o bot estava funcionando perfeitamente

**Comment by pedrozun** [comment]
o que eu tentei aqui:

Usei o python 3.7, 3.8 e 3.9
Criei meu proprio png do go_to_work_btn
Ja usei o threshold de 0.1 até 1
Executei com cmd, windows terminal e powershell
Ele vai até o botao dos herois mas simplesmente não clica nele e acha que clicou e segue rolando o bot na pagina errada.

**Comment by joaovictor7** [comment]
o que tá tentei mas não resolveu:

comentei os "sleep" das linhas 327 e 329;
adicionei um timeout de 8, 15 e 20 seg. como parâmetro na função "clickBtn", linha 328.

**Comment by joaovictor7** [comment]
Alguém conseguiu resolver ajustando mais alguma coisa ?

**Comment by joaovictor7** [comment]
consegui resolver o problema fazendo a seguinte alteração
arquivo: /captcha/solveCaptcha.py
linha 299, substituir por:
pyautogui.PAUSE = pause

**Comment by urden7** [comment]
> pyautogui.PAUSE = pause

Em que devo mudar isto?

**Comment by joaovictor7** [comment]
Galera meu PR com a correção desse problema já foi aprovado. Atualizem as branchs locais de vocês.

**Comment by edermania** [comment]
> consegui resolver o problema fazendo a seguinte alteração arquivo: /captcha/solveCaptcha.py linha 299, substituir por: pyautogui.PAUSE = pause

Boa noite, no meu abri o arquivo solveCaptcha.py na linha 299 para fazer as alterações. mas já estava com este comando atualizado. O erro ainda perciste.

**Comment by mvpalves** [comment]
Aqui também está falhando ):

Até tentei diminuir o threshold do botão para ver se ele começava a reconhecer, mas sem sucesso.
