### ISSUE TITLE
pip install torch 

### ISSUE THREAD

**Issue by thana47230** [mpcabete/bombcrypto-bot#388]
ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.10.0

**Comment by Nucito** [comment]
> ERROR: Could not find a version that satisfies the requirement torch>=1.10.0 (from versions: none) ERROR: No matching distribution found for torch>=1.10.0

Sorry for this error, i will update the requirements.txt

**Comment by fguide** [comment]
This version is actually fine to use, are you using python 3.9? Could you try the cpu version by running:

pip install torch==1.10.0+cpu torchvision==0.11.1+cpu torchaudio==0.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html

**Comment by tiranossaur** [comment]
Eu tbm nao consigo instalar o torch, da sempre esse erro do amigo acima.

**Comment by Nucito** [comment]
@tiranossaur @thana47230 Try download the last version😁 i have been removed the torch from requirements... this is from old Captcha Solver ksksksk

**Comment by tiranossaur** [comment]
@Nucito obrigado amigo, eu instalei uma versao do pyton anterior e funfou o torch, porém essa branch oficial pra mim nao funciona, to usando a do Thiago-molive. Agradeço de coração isso ajuda bastante! Outra duvida tem algum grupo discord pra pessoal que faz donate?

**Comment by Nucito** [comment]
@tiranossaur Eu não sou o dono desse projeto... apenas ajudo quando posso, o verdadeiro criador é o mpcabete ksksksk
