### ISSUE TITLE
Error ao iniciar bot 

### ISSUE THREAD

**Issue by pedrox97** [mpcabete/bombcrypto-bot#389]
![image](https://user-images.githubusercontent.com/96137023/146658186-3a9d3375-4791-4e1c-9db6-26a072afb84e.png)
 aparece este erro quando meto o ultimo comando para iniciar o bot, o que fazer para resolver?

**Comment by fguide** [comment]
Temos alguns outros casos com windows 11 que também tiveram esse problema, tente instalar com:

>pip3 install opencv-python

veja também se está na versao 3.9 com python 3 -V

**Comment by pedrox97** [comment]
> Temos alguns outros casos com windows 11 que também tiveram esse problema, tente instalar com:
> 
> > pip3 install opencv-python
> 
> veja também se está na versao 3.9 com python 3 -V

sim estou com o o python 3.9 funcionou bem até hoje hoje é que deu este erro

**Comment by fguide** [comment]
> pip3 install opencv-python

esse comando faz a instalação ou diz que ja esta instalado?

**Comment by pedrox97** [comment]
> > pip3 install opencv-python
> 
> esse comando faz a instalação ou diz que ja esta instalado?

![image](https://user-images.githubusercontent.com/96137023/146658574-0a91a32e-e4ab-4d1f-a555-1c40dcadb3eb.png)

**Comment by fguide** [comment]
Infelizmente não tenho acesso a windows para testar, tentei ajudar um caso parecido hoje (#380) mas sem sucesso, desconfio que seja algo relacionado ao windows 11, você pode verificar por atualizações instaladas entre hoje e ontem, ou tentar algum dos passos do issue mencionado, no requirements não houve alteração de versão do opencv.

**Comment by alexandernicacio** [comment]
o meu caso é o windows 10 e esta acontecendo exatamente isso, não consigo rodar o bot

**Comment by pedrox97** [comment]
O windows 10 fez uma atualizaçao no dia 18 vou desisntalar essa atualizaçao e ver se ja funciona

**Comment by fguide** [comment]
Ultima alternativa talvez seja tentar instalar o pacote manualmente, baixe de acrdo com seu windows em:

https://files.pythonhosted.org/packages/11/a5/0ee8573422365086f065f7f54718506489db89371bc09de3b025ccc86515/opencv_python-4.5.4.60-cp39-cp39-win_amd64.whl **64 bits**
https://files.pythonhosted.org/packages/00/d0/b1c2ca5f539add3a2b73793812d07c859d44cd688ab6d327bb9674702d42/opencv_python-4.5.4.60-cp39-cp39-win32.whl **32 bits**

depois abra o CMD na pasta que salvou o arquivo e digite:
>pip install opencv_python-4.5.4.60-cp39-cp39-win_amd64.whl

lembrando que é a versao para python 3.9

**Comment by alexandernicacio** [comment]
fiz o que me recomendou e agora deu erro diferente

C:\bomb>python3 index.py                                                                                                
Traceback (most recent call last):                                                                                        
File "C:\bomb\index.py", line 4, in <module>                                                                              
from captcha.solveCaptcha import solveCaptcha                                                                         
File "C:\bomb\captcha\solveCaptcha.py", line 3, in <module>                                                               
import pyautogui                                                                                                    

ModuleNotFoundError: No module named 'pyautogui'

**Comment by fguide** [comment]
tente agora pip install -r requirements.txt ou entao pip install pyautogui

**Comment by alexandernicacio** [comment]
C:\bomb>pip install -r requirements.txt ou entao pip install pyautogui                                                  
Collecting ou                                                                                                             
Downloading ou-0.0.2-py3-none-any.whl (10 kB)                                                                         
ERROR: Could not find a version that satisfies the requirement entao (from versions: none)                              
ERROR: No matching distribution found for entao

**Comment by alexandernicacio** [comment]
testei mais continua dando o ultimo erro citado por mim acima

**Comment by fguide** [comment]
> ERROR: No matching distribution found for **entao**

sao dois comandos diferentes...

**Comment by alexandernicacio** [comment]
sim eu percebi por isso apaguei e depois teste os dois diferentes
um de cada vez

**Comment by fguide** [comment]
tente agora:

pip install wheel
pip install pygetwindow==0.0.9
pip install pyautogui

**Comment by alexandernicacio** [comment]
C:\bomb>pip install wheel                                                                                               
Collecting wheel                                                                                                          
Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)                                                                
Installing collected packages: wheel                                                                                    
Successfully installed wheel-0.37.0                                                                                                                                                                                                             C:\bomb>pip install pygetwindow==0.0.9                                                                                 
 Requirement already satisfied: pygetwindow==0.0.9 in c:\program files\python39\lib\site-packages (0.0.9)                Requirement already satisfied: pyrect in c:\program files\python39\lib\site-packages (from pygetwindow==0.0.9) (0.1.4)                                                                                                                          C:\bomb>pip install pyautogui                                                                                           
Requirement already satisfied: pyautogui in c:\program files\python39\lib\site-packages (0.9.53)                        
Requirement already satisfied: pymsgbox in c:\program files\python39\lib\site-packages (from pyautogui) (1.0.9)         Requirement already satisfied: PyTweening>=1.0.1 in c:\program files\python39\lib\site-packages (from pyautogui) (1.0.4)                                                                                                                        Requirement already satisfied: pyscreeze>=0.1.21 in c:\program files\python39\lib\site-packages (from pyautogui) (0.1.28)                                                                                                                       Requirement already satisfied: pygetwindow>=0.0.5 in c:\program files\python39\lib\site-packages (from pyautogui) (0.0.9)                                                                                                                       Requirement already satisfied: mouseinfo in c:\program files\python39\lib\site-packages (from pyautogui) (0.1.3)        Requirement already satisfied: pyrect in c:\program files\python39\lib\site-packages (from pygetwindow>=0.0.5->pyautogui) (0.1.4)                                                                                                               
Requirement already satisfied: pyperclip in c:\program files\python39\lib\site-packages (from mouseinfo->pyautogui) (1.8.2)                                                                                                                                                                                                                                             C:\bomb>python3 index.py                                                                                                
Traceback (most recent call last):                                                                                        
File "C:\bomb\index.py", line 4, in <module>                                                                              
from captcha.solveCaptcha import solveCaptcha                                                                         
File "C:\bomb\captcha\solveCaptcha.py", line 3, in <module>                                                              
 import pyautogui                                                                                                    
ModuleNotFoundError: No module named 'pyautogui'

**Comment by fguide** [comment]
Versao do numpy está estranha pela foto, tente: 

pip uninstall numpy
pip uninstall pyautogui

pip install numpy==1.21.4
pip install PyAutoGUI==0.9.53

**Comment by pedrox97** [comment]
Já tenho o meu a funcionar, foi so disistalar a atulalizaçao do windos e riniciar o computador. obrigado pela ajuda

**Comment by alexandernicacio** [comment]
sim ou não?
C:\bomb>pip uninstall numpy                                                                                             
Found existing installation: numpy 1.21.4                                                                               
Uninstalling numpy-1.21.4:                                                                                                
Would remove:                                                                                                             
c:\program files\python39\lib\site-packages\numpy-1.21.4.dist-info\*                                                    
c:\program files\python39\lib\site-packages\numpy\*                                                                    
 c:\program files\python39\scripts\f2py.exe                                                                          
Proceed (Y/n)?

**Comment by alexandernicacio** [comment]
então vou tentar desinstalar a atualização pra ver no que da pode ser isso mesmo se no dele funcionou

**Comment by fguide** [comment]
sim, pode remover e depois instalar novamente. 

Veja a resposta do @pedrox97 talvez seja seu caso tambem

**Comment by alexandernicacio** [comment]
o problema era mesmo a atualização do windows tambem resolveu aqui desinstalando valeu pessoal pela ajuda

**Comment by PinnDeath6** [comment]
qual atualização voces tiraram?

**Comment by alexandernicacio** [comment]
> 

foi uma atualização do windows 10 do dia 17/12/2021 teve duas atulalização é que tem tem o nome maior não vou lembrar agora

**Comment by rcomparim** [comment]
fguide passa seu whatsapp estou com problema aqui, acredito q vc vai resolverl

**Comment by fguide** [comment]
> fguide passa seu whatsapp estou com problema aqui, acredito q vc vai resolverl

Te respondi no seu issue.
