### ISSUE TITLE
Running the bot on MAC ?

### ISSUE THREAD

**Issue by HelliossXX** [mpcabete/bombcrypto-bot#39]
Hi, 

Is it possible to run your script on MAC please ?

Best Regards,

**Comment by icaronaser** [comment]
here it runs but doesnt move the mouse or click anywhere, anyone similar?

**Comment by felipereispt** [comment]
same problem

**Comment by renanbrandaoo** [comment]
I’m also trying to run on my MacBook Pro. Anyone can help me?

**Comment by jotapepinheiro** [comment]
Macbook plugged into a monitor works normally, I think to use it on a macbook without an external monitor you need to take prints from the retina screen, as images should be between 150 to 300 DPI

**Comment by MrHazee** [comment]
@jotapepinheiro I have macbook M1 and the script runs smooth but doesnt move my cursor at all. First i run the script and then I open the page with BombCrypto in Treasure Hunt. Is there anything else I need to do to make it work?
Thanks
