### ISSUE TITLE
Conexão automática com a wallet para facilitar a instância através do docker

### ISSUE THREAD

**Issue by Gabriel-BS** [mpcabete/bombcrypto-bot#390]
Não sei se isso já está implementado, porém, com a implementação de poder rodar um container contendo o bot, seria interessante que não houvesse a necessidade do usuário ter que configurar a conta individualmente para cada um dos containers, porém poder passar como variável de ambiente as credenciais para acesso da wallet.

E assim teríamos os seguintes passos:
1. Inicialização do projeto
2. Instalar a extensão do metamask
3. Conectar com instância do metamask
4. Configurar a conta(talvez adicionar as moedas na conta caso necessário)
5. Fluxo normal(acesso ao bombcrypto) 

OBS: não sei se isso já foi implementado, porém até onde eu vi, não tinha, isso facilitaria a automatização por exemplo

**Comment by fguide** [comment]
Eu acho meio inseguro fazer dessa forma, você precisaria armazenar de forma aberta dados importantes que podem ser acessados indevidamente.

Uma sugestão é configurar no seu navegador e salvar o diretorio em um local seguro, pode usar senha e encriptar por exemplo, e assim que subir um novo container você simplesmente substitui o diretorio salvo no container novo.

É claro que da pra fazer passando parametros, armazenar de forma encriptada, etc, porém ainda adiciona alguns fatores de risco que precisam ser considerados.

**Comment by Gabriel-BS** [comment]
Tem razão, eu não tinha levado em consideração o fator segurança. Obrigado por responder prontamente =D
