### ISSUE TITLE
Iniciar Bot

### ISSUE THREAD

**Issue by Cerberosk** [mpcabete/bombcrypto-bot#392]
![Captura de Tela (7)](https://user-images.githubusercontent.com/96361564/146661614-d08cb041-f6c8-48b5-a92a-b2fbfa7005f0.png)

alguem sabe ta assim ??

**Comment by SamuelSilveira08** [comment]
Tenta usar só python index.py
Sem o "3"

**Comment by Galinho90** [comment]
> ![Captura de Tela (7)](https://user-images.githubusercontent.com/96361564/146661614-d08cb041-f6c8-48b5-a92a-b2fbfa7005f0.png)
> 
> alguem sabe ta assim ??

Para iniciar o bot digite apenas: 

python índex.py
