### ISSUE TITLE
captcha not solved

### ISSUE THREAD

**Issue by hamzalamou** [mpcabete/bombcrypto-bot#394]
hi guys I really appreciate the work of developers
i have a little problem here 
the bot is working fine in firefox
but does not work in brave or chrome any solution ?
by the way it does all the other things..send home etc.. 
except solving the captcha

**Comment by Gaboo134** [comment]
após a atualização o bot não resolve o captch fica aparecendo somente isso, alguém pode me ajudar obrigado

[99m[2021-12-19 01:07:30] => ⬆️ Processing last action..
←[99m[2021-12-19 01:07:32] => 🎉 Connect wallet button detected, logging in!←[0m

no captcha popup found!
←[99m[2021-12-19 01:07:35] => ⬆️ Processing last action..←[99m.←[99m.←[99m.←[99m.←[99m.
no captcha popup found!

←[99m[2021-12-19 01:08:19] => 🔃 Refreshing Heroes Positions←[0m
←[99m[2021-12-19 01:08:19] => ⬆️ Processing last action..←[99m.←[99m.←[99m.
no captcha popup found!
←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.←[99m.Traceback (most recent call last):
  File "c:\bombcrypto-bot\index.py", line 524, in <module>
    main()
  File "c:\bombcrypto-bot\index.py", line 506, in main
    if clickBtn(images['new-map']):
  File "c:\bombcrypto-bot\index.py", line 169, in clickBtn
    matches = positions(img, threshold=threshold)
  File "c:\bombcrypto-bot\index.py", line 203, in positions
    result = cv2.matchTemplate(img,target,cv2.TM_CCOEFF_NORMED)
KeyboardInterrupt
^C
c:\bombcrypto-bot>

**Comment by Lordblackhat** [comment]
Depois da última atualização o captcha parou de ser resolvido. Poderia verificar @mpcabete

**Comment by fx2016** [comment]
Aqui está perfeito, o problema pode estar em alguma atualização do windows, versão do Python errada (tem que ser a 3.9.9), entre outras coisas

**Comment by Lordblackhat** [comment]
A minha versão é a 3.9.9. Acredito que o meu Windows tenha atualizado mesmo pq a máquina reiniciou. O que devo fazer?

**Comment by hamzalamou** [comment]
> A minha versão é a 3.9.9. Acredito que o meu Windows tenha atualizado mesmo pq a máquina reiniciou. O que devo fazer?

https://www.youtube.com/watch?v=TNI74Ue8Vvg#0

**Comment by noxfork** [comment]
tenho uma conta no brave que tbm nao soluciona o captcha, porem, outras 2 tbm no brave estao normais.. 
passei a conta que nao solucionava para o firefox e funcionou 100%.
Acredito que isso seja algo relacionado a resolução da tela, pois a que nao funcionou no brave é a unica maquina virtual em 1024x768, as outras estao em 1360x768

**Comment by hamzalamou** [comment]
> tenho uma conta no brave que tbm nao soluciona o captcha, porem, outras 2 tbm no brave estao normais..
> passei a conta que nao solucionava para o firefox e funcionou 100%.
> Acredito que isso seja algo relacionado a resolução da tela, pois a que nao funcionou no brave é a unica maquina virtual em 1024x768, as outras estao em 1360x768

eu tentei sua solução, mas infelizmente não funcionou para mim
o que eu quero fazer é multiaccount
mas acho que o firefox (onde o bot funciona bem) não oferece suporte a perfis como Chrome e brave

**Comment by PinnDeath6** [comment]
> > tenho uma conta no brave que tbm nao soluciona o captcha, porem, outras 2 tbm no brave estao normais..
> > passei a conta que nao solucionava para o firefox e funcionou 100%.
> > Acredito que isso seja algo relacionado a resolução da tela, pois a que nao funcionou no brave é a unica maquina virtual em 1024x768, as outras estao em 1360x768
> 
> eu tentei sua solução, mas infelizmente não funcionou para mim o que eu quero fazer é multiaccount mas acho que o firefox (onde o bot funciona bem) não oferece suporte a perfis como Chrome e brave

tem sim, eu uso multi account em 2 janelas do firefox

**Comment by hamzalamou** [comment]
> > > tenho uma conta no brave que tbm nao soluciona o captcha, porem, outras 2 tbm no brave estao normais..
> > > passei a conta que nao solucionava para o firefox e funcionou 100%.
> > > Acredito que isso seja algo relacionado a resolução da tela, pois a que nao funcionou no brave é a unica maquina virtual em 1024x768, as outras estao em 1360x768
> > 
> > 
> > eu tentei sua solução, mas infelizmente não funcionou para mim o que eu quero fazer é multiaccount mas acho que o firefox (onde o bot funciona bem) não oferece suporte a perfis como Chrome e brave
> 
> tem sim, eu uso multi account em 2 janelas do firefox

você pode me mostrar como fazer isso mano?
e como usar este bot para ambas as contas estou realmente lutando aqui meu amigo

**Comment by PinnDeath6** [comment]
> > > > tenho uma conta no brave que tbm nao soluciona o captcha, porem, outras 2 tbm no brave estao normais..
> > > > passei a conta que nao solucionava para o firefox e funcionou 100%.
> > > > Acredito que isso seja algo relacionado a resolução da tela, pois a que nao funcionou no brave é a unica maquina virtual em 1024x768, as outras estao em 1360x768
> > > 
> > > 
> > > eu tentei sua solução, mas infelizmente não funcionou para mim o que eu quero fazer é multiaccount mas acho que o firefox (onde o bot funciona bem) não oferece suporte a perfis como Chrome e brave
> > 
> > 
> > tem sim, eu uso multi account em 2 janelas do firefox
> 
> você pode me mostrar como fazer isso mano? e como usar este bot para ambas as contas estou realmente lutando aqui meu amigo

sobre o firefox é só pesquisar: como criar dois perfils firefox
sobre o multi accounting vc precisa inserir o pygetwindow
