### ISSUE TITLE
How to let heroes rest 100% only send to work

### ISSUE THREAD

**Issue by soundsticks** [mpcabete/bombcrypto-bot#395]
How to let heroes rest 100% only send to work?

**Comment by fguide** [comment]
Edit the file config.yaml, change select_heroes_mode: "green" to select_heroes_mode: "all"

Also, read the docs, there are other parameters you can adjust.

**Comment by mfsousa** [comment]
> Edit the file config.yaml, change select_heroes_mode: "green" to select_heroes_mode: "all"
> 
> Also, read the docs, there are other parameters you can adjust.

No, to only send the 100% ones you should set it to "full"

**Comment by fguide** [comment]
Yes, sorry. as I said, read the docs, don't be lie me.
