### ISSUE TITLE
Erros, gratifica-se quem puder me ajudar

### ISSUE THREAD

**Issue by WanaColacio** [mpcabete/bombcrypto-bot#396]
estou tendo varios erros ja fiz baixar o 3.9.9 e continua varios erros  

quem souber resolver e puder me ajuda eu dou quantinha em BC ou grana msm. 

pq ja tem 4 dias q to tentando e nada resolve

vou deixa discord q criei pra essa funcionalidade 

https://discord.gg/Gt54Bzyq

**Comment by llFerreira** [comment]
Poem o print do erro, que fica mais facil de ajudar

**Comment by fguide** [comment]
Melhor do que oferecer dinheiro é oferecer informações do problema para conseguirmos ajudar, tem vários tópicos de problemas já resolvidos, se nos disser o que acontece podemos ajudar.

Começe olhando #389 por exemplo, aparentemente uma atualização do windows fez o modulo cv2 e outros nao serem mais reconhecidos, removendo a atualização o problema se foi pelo que reportaram.

**Comment by Felbrou** [comment]
coloca print do error que tentamos ajudar

**Comment by pedrozun** [comment]
Ja resolvi, era instalação do python e pip comprometidas, estava tentando usar o python 3.10 tambem com o torch, que não funciona.

Agora ele usa o python 3.8.9 e foi adicionado as variaveis de ambiente no windows.
