### ISSUE TITLE
Bot para duas contas

### ISSUE THREAD

**Issue by pedrox97** [mpcabete/bombcrypto-bot#398]
É possivel por o Bot a trabalhar em duas contas? 
como fazer?

**Comment by Nucito** [comment]
@pedrox97 Sim, se for para windows eu recomendo que você estude um pouco a api do windows😁

**Comment by pedrox97** [comment]
sim é windows, o que tenho de fazer?

**Comment by Nucito** [comment]
Acabei de comentar... estude a api do windows😅 
Libs para possível uso:
- Pywin32
- Cython
- Ctypes

Recomendo estudar sobre como chamar janelas ativas no momento, alem de como puxar elas para primeiro plano... com essas duas coisas vc faz um bot para múltiplas contas kkkkkk

Desejo boa sorte nos estudos😁

**Comment by pedrox97** [comment]
Vamos la ver o que consigo fazer nao sou muito bom com informatica  ahahah

**Comment by fguide** [comment]
Sem programação existe um modo simples de fazer com Virtual desktop do windows, talvez seja mais fácil para você.

**Comment by PinnDeath6** [comment]
> Acabei de comentar... estude a api do windows😅 Libs para possível uso:
> 
> * Pywin32
> * Cython
> * Ctypes
> 
> Recomendo estudar sobre como chamar janelas ativas no momento, alem de como puxar elas para primeiro plano... com essas duas coisas vc faz um bot para múltiplas contas kkkkkk
> 
> Desejo boa sorte nos estudos😁

pygetwindow

**Comment by PinnDeath6** [comment]
> Acabei de comentar... estude a api do windows😅 Libs para possível uso:
> 
> * Pywin32
> * Cython
> * Ctypes
> 
> Recomendo estudar sobre como chamar janelas ativas no momento, alem de como puxar elas para primeiro plano... com essas duas coisas vc faz um bot para múltiplas contas kkkkkk
> 
> Desejo boa sorte nos estudos😁

vc deu o caminho, o resto é com vcs bbs

**Comment by rzanca** [comment]
Se a máquina for boa, e tiver uns 16GB de RAM, pode usar containers, #192
