### ISSUE TITLE
erro na instalação

### ISSUE THREAD

**Issue by gabrielfinck** [mpcabete/bombcrypto-bot#399]
![image](https://user-images.githubusercontent.com/96392373/146689064-662c07b7-d206-4334-a2f6-f5b24bcbf167.png)

alguém me ajuda a resolver fazendo favor

**Comment by Galinho90** [comment]
Instale o Python 3.9.9, provavel que vc esta na versão mais recente 3.10

Lembre-se de desistalar a versão recente antes.

**Comment by llFerreira** [comment]
Como o amigo ai falou, desinstala o python atual e baixa o 3.9.9 e refaça todo o processo novamente.

**Comment by gabrielfinck** [comment]
obrigado, agora aparece que o python não é encontrado, a instalação deu tudo certo
![image](https://user-images.githubusercontent.com/96392373/146714972-430399c9-73ca-4d05-ac4b-f1027ed75d78.png)

**Comment by Galinho90** [comment]
> obrigado, agora aparece que o python não é encontrado, a instalação deu tudo certo
> ![image](https://user-images.githubusercontent.com/96392373/146714972-430399c9-73ca-4d05-ac4b-f1027ed75d78.png)

Remove o “3” foi um erro de digitação: 

coloquei apenas: 


 python index.py

**Comment by gabrielfinck** [comment]
obrigado Galinho90 deu certo essa parte, agora fica processando e diz q não acha o captcha

**Comment by gabrielfinck** [comment]
consegui o problema era a resolução da minha tela, mudei para 100% e 1360x768
