### ISSUE TITLE
Poderia me ajudar?

### ISSUE THREAD

**Issue by ielepassos** [mpcabete/bombcrypto-bot#4]
Primeiramente, parabéns pela iniciativa de divulgar o bot :)
Infelizmente, não consigo executá-lo corretamente. O bot, quando ativado, informa ter clicado no botão de connect wallet, entretanto, ele apenas se movimenta para a hotbar do meu monitor e não para o botão ( com os outros botões, ele nem acha). 
Poderia me ajudar?

**Comment by mpcabete** [comment]
hmm, tenta mudar a opçao
`  trashhold:
    default: 0.7`
no arquivo config pra algo tipo 0.8

**Comment by ielepassos** [comment]
Ainda continua do mesmo jeito :(

**Comment by ielepassos** [comment]
Deu certo! Muito obrigada :)

**Comment by ielepassos** [comment]
Eu estava utilizando duas telas. Assim que despluguei uma, o bot funcionou perfeitamente :)
Tem alguma configuração que dê pra ele funcionar com as duas?

**Comment by mpcabete** [comment]
No meu computador ele funciona com duas telas, mas uma vez testei num windows com duas telas e ele realmente n~ao funcionou. Eu tanho uma ideia de qual pode ser o problema, mas talvez demore um pouco para olhar.
