### ISSUE TITLE
Problema com Raridade

### ISSUE THREAD

**Issue by martineix** [mpcabete/bombcrypto-bot#40]
Iae brother!

Primeiramente, parabéns pelo BOT. Muito bom, está me ajudando bastante. Dei a sorte de pegar um Super Raro e assim que puder sacar, vou te mandar uns BCOIN, para você continuar o projeto e melhorando cada vez mais!

Segundo, estou com um problema nas raridades, ele não coloca o Super Raro para trabalhar. Já estando com a barrinha verde, ele fica validando os Common mas quando ele faz a checagem cerca de 3, 4 vezes, ele não ativa o botão WORK do SR e vai direto clicar no fechar da janela, para voltarem ao trabalho.

Como posso resolver este problema?

**Comment by Rout222** [comment]
> Iae brother!
> 
> Primeiramente, parabéns pelo BOT. Muito bom, está me ajudando bastante. Dei a sorte de pegar um Super Raro e assim que puder sacar, vou te mandar uns BCOIN, para você continuar o projeto e melhorando cada vez mais!
> 
> Segundo, estou com um problema nas raridades, ele não coloca o Super Raro para trabalhar. Já estando com a barrinha verde, ele fica validando os Common mas quando ele faz a checagem cerca de 3, 4 vezes, ele não ativa o botão WORK do SR e vai direto clicar no fechar da janela, para voltarem ao trabalho.
> 
> Como posso resolver este problema?

Substitui a imagem do common, pelo texto do super raro. tenta pegar do mesmo jeito, q da certo.

**Comment by Rout222** [comment]
Chefe, altera o trashold até q ele pega.

vai abaixando de 0.05 em 0.05

no config.yaml

**Comment by rafarfr** [comment]
Boa tarde, amigo, você alterou qual configuração do trashold?
o meu está assim:

trashhold:
    default: 0.7
    commom: 0.8
    select_wallet_buttons: 0.8
    go_to_work_btn: 0.895
    green_bar: 0.9

**Comment by martineix** [comment]
> Chefe, altera o trashold até q ele pega.
> 
> vai abaixando de 0.05 em 0.05
> 
> no config.yaml

Mas qual você diminuiu? O default?

**Comment by rafarfr** [comment]
Eu quero saber justamente qual diminuir, eu ainda não diminuí nenhum

**Comment by Rout222** [comment]
eu uso essas configs >
---
  time_intervals:
    send_heroes_for_work: 10 #min
    refresh_heroes_positions: 3 #min
    check_for_new_map_button: 1 #min
    check_for_login: 1 #min
    interval_between_moviments: 1 #s

  # how confident the bot needs to be to click the button 0-1
  trashhold:
    default: 0.7
    commom: 0.8
    select_wallet_buttons: 0.8
    go_to_work_btn: 0.9
    green_bar: 0.85

  scroll_size: 60
  use_click_and_drag_instead_of_scroll: true
  click_and_drag_amount: 250
  only_click_heroes_with_green_bar: true

**Comment by rafarfr** [comment]
Conseguiu resolver, mano, valeu demais!!

**Comment by eztzez** [comment]
> eu uso essas configs >
> 
> ```
> ---
>   time_intervals:
>     send_heroes_for_work: 10 #min
>     refresh_heroes_positions: 3 #min
>     check_for_new_map_button: 1 #min
>     check_for_login: 1 #min
>     interval_between_moviments: 1 #s
> 
>   # how confident the bot needs to be to click the button 0-1
>   trashhold:
>     default: 0.7
>     commom: 0.8
>     select_wallet_buttons: 0.8
>     go_to_work_btn: 0.9
>     green_bar: 0.85
> 
>   scroll_size: 60
>   use_click_and_drag_instead_of_scroll: true
>   click_and_drag_amount: 250
>   only_click_heroes_with_green_bar: true
> ```

Ola!
eu também quase tudo funciona perfeitamente !!
Eu só quero que a atualização do código envie os heróis para Homee.
Eu vou te pagar é claro, basta entrar em contato comigo
Whatssap: 00212666195500

**Comment by eztzez** [comment]
> eu uso essas configs >
> 
> ```
> ---
>   time_intervals:
>     send_heroes_for_work: 10 #min
>     refresh_heroes_positions: 3 #min
>     check_for_new_map_button: 1 #min
>     check_for_login: 1 #min
>     interval_between_moviments: 1 #s
> 
>   # how confident the bot needs to be to click the button 0-1
>   trashhold:
>     default: 0.7
>     commom: 0.8
>     select_wallet_buttons: 0.8
>     go_to_work_btn: 0.9
>     green_bar: 0.85
> 
>   scroll_size: 60
>   use_click_and_drag_instead_of_scroll: true
>   click_and_drag_amount: 250
>   only_click_heroes_with_green_bar: true
> ```

Ola meu irmão
Também tenho quase tudo funcionando perfeitamente !!
Só quero que o código atualizado envie os heróis para casa, já que comprei um.
por favor me ajude

**Comment by MMotenai** [comment]
Gostaria de saber como posso entrar em contato com alguém pra tornar o bot um pouco mais produtivo, tenho 2 epicos e não compensa ficar com eles 100% ativos! Alguém ajuda ?

**Comment by cristhianbreunig** [comment]
> Gostaria de saber como posso entrar em contato com alguém pra tornar o bot um pouco mais produtivo, tenho 2 epicos e não compensa ficar com eles 100% ativos! Alguém ajuda ?

@MMotenai, explica melhor o que tu precisa, dá mais detalhes... daí pode ser que alguém se habilite a auxiliar o @mpcabete no ajuste (se for possível).

Você quer dizer utilizar somente 1 épico por vez, isso ?
Se sim, a ideia seria conseguir definir o limite máximo por tipo de herói ?
Exemplo, utilizar o máximo de heróis possível, desde que não tenha mais que 1 épico ativo, isso ?

**Comment by Rout222** [comment]
Acho que o ideal, seria criar uma pasta de times.... ou uma pasta com foto dos campeões que não podem ficar juntos...
