### ISSUE TITLE
ERROR INSTALL REQUIERIMENTS

### ISSUE THREAD

**Issue by Galinho90** [mpcabete/bombcrypto-bot#400]
Alguem pode me ajudar o que pode ser: 

ERROR: Command errored out with exit status 1:
     command: 'C:\Users\José\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\José\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\JOS~1\AppData\Local\Temp\tmphulidee2'
         cwd: C:\Users\José\AppData\Local\Temp\pip-install-xdkqy_vn\pymsgbox_f9241f7207f94bb18ad95f31e016a730
    Complete output (14 lines):
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe9 in position 0: unexpected end of data (sitecustomize.py, line 7)
    running dist_info
    creating C:\Users\José\AppData\Local\Temp\pip-modern-metadata-fdoplu5d\PyMsgBox.egg-info
    writing C:\Users\José\AppData\Local\Temp\pip-modern-metadata-fdoplu5d\PyMsgBox.egg-info\PKG-INFO
    writing dependency_links to C:\Users\José\AppData\Local\Temp\pip-modern-metadata-fdoplu5d\PyMsgBox.egg-info\dependency_links.txt
    writing top-level names to C:\Users\José\AppData\Local\Temp\pip-modern-metadata-fdoplu5d\PyMsgBox.egg-info\top_level.txt
    writing manifest file 'C:\Users\José\AppData\Local\Temp\pip-modern-metadata-fdoplu5d\PyMsgBox.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\José\AppData\Local\Temp\pip-modern-metadata-fdoplu5d\PyMsgBox.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.py' under directory 'pymsgbox'
    writing manifest file 'C:\Users\José\AppData\Local\Temp\pip-modern-metadata-fdoplu5d\PyMsgBox.egg-info\SOURCES.txt'
    creating 'C:\Users\José\AppData\Local\Temp\pip-modern-metadata-fdoplu5d\PyMsgBox.dist-info'
    error: invalid command 'bdist_wheel'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7d/ff/4c6f31a4f08979f12a663f2aeb6c8b765d3bd592e66eaaac445f547bb875/PyMsgBox-1.0.9.tar.gz#sha256=2194227de8bff7a3d6da541848705a155dcbb2a06ee120d9f280a1d7f51263ff (from https://pypi.org/simple/pymsgbox/). Command errored out with exit status 1: 'C:\Users\José\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\José\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\JOS~1\AppData\Local\Temp\tmphulidee2' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyMsgBox==1.0.9 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9)
ERROR: No matching distribution found for PyMsgBox==1.0.9
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\José\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

c:\Bomb>

**Comment by fguide** [comment]
Veja #389 talvez seu problema seja com atualização do windows como reportado lá.

**Comment by Galinho90** [comment]
@fguide  muito obrigado, vou testar.
