### ISSUE TITLE
Erro Macbook M1

### ISSUE THREAD

**Issue by mdavinicius** [mpcabete/bombcrypto-bot#401]
Pessoal boa noite,

Ja li os vários tópcios de issues aqui, tentei uma dezena de comandos, mas sempre da algum erro diferente.
Como não entendo de Python, vou abrir um tópico novo já que uso Mac, e até onde vi, a maioria do pessoal usa Windows.
Vou começar do básico, e ai conforme instrução de vocês, vou evoluindo o tópico e tentando novas idéias.

Desde já agradeço a atenção! :)) 

1. Dei o "cd diretório do bot"
2. pip install -r requirements.txt
3. Erro: 

![image](https://user-images.githubusercontent.com/85064177/146693778-fc9c4db2-e168-4a35-9075-d0963efbf820.png)

**Comment by fguide** [comment]
Atualize o python, o seu está no 2.7

**Comment by mdavinicius** [comment]
> Atualize o python, o seu está no 2.7

Cara, eu tinha baixado o Python mais novo (3.10.01)
Ai em algum tópico eu vi alguém falando pra usar a versão 3.9, e ai baixei daqui: https://www.python.org/downloads/macos/ >  Python 3.9.9 - Nov. 15, 2021 > Download macOS 64-bit universal2 installer

E fica mostrando que é a versão 2.7, mas eu instalei a 3.9.9 
O que eu faço? ._.

**Comment by fguide** [comment]
Tente usar python3

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mdavinicius** [comment]
> Tente usar python3>

Tem como ser mais específico amigo? 😔

(Por via das dúvidas, eu digitei apenas Python3 no Terminal e apareceu a versão que eu havia instalado aqui:

![image](https://user-images.githubusercontent.com/85064177/146694767-50a2de29-4429-4033-8ee9-e6c98cccd95e.png)

E agora?

**Comment by llFerreira** [comment]
Desinstala primeiro o python 2.7 que tu tem, e depois instala o 3.9.9. Reinicia e faça os mesmo processos

**Comment by fguide** [comment]
Entao, inicie o bot com python3 index.py, deve ussr a versao 3

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mdavinicius** [comment]
> Entao, inicie o bot com python3 index.py, deve ussr a versao 3 Get Outlook for Android<https://aka.ms/AAb9ysg>

O erro do print inicial foi quanto eu tentei instalar o requeriments.txt
Se eu tentar ir direto rodar o bot, da esse erro:

![image](https://user-images.githubusercontent.com/85064177/146699553-3d752ec4-1c94-4b37-90c7-41e8ebbf8328.png)

**Comment by fguide** [comment]
SIm, tente o seguinte na pasta do bot:

pip3 install -r requirements.txt 

e depois:

python3 index.py

**Comment by mdavinicius** [comment]
> SIm, tente o seguinte na pasta do bot:
> 
> pip3 install -r requirements.txt
> 
> e depois:
> 
> python3 index.py
> 
> Se o pip3 falhar, tente: python3 -m pip install -r requirements.txt

O pip3 install começa bem, mas ai depois de um tempo da um baita erro gigante:

![image](https://user-images.githubusercontent.com/85064177/146700056-436d35cd-b0f1-4663-8d27-f2001b1f1670.png)

Final do erro:
![image](https://user-images.githubusercontent.com/85064177/146700097-e1dba13c-d15e-4057-82ef-c232c842423c.png)

Como falhou, fui para o outro comando que sugeriu: python3 -m pip install -r requirements.txt
De novo, começou bem com vários 'collecting, collecting...', ai depois de um tempinho, vem erro gigante também:
![image](https://user-images.githubusercontent.com/85064177/146700291-464d78ae-27cc-4021-817d-ada1eec8c076.png)

E do meio, pro final do erro:
![image](https://user-images.githubusercontent.com/85064177/146700327-5d83f135-11e2-4937-a709-87426e68703f.png)

**Comment by fguide** [comment]
Tente instalar com pip3 install scipy, talvez seja a versao que nao esta bem para mac, se nao me engano tem que compilar do fonte, mas tente antes com esse comando para ver se ele instala em outra versao.

**Comment by fguide** [comment]
Opa, comi bola na leitura do erro, tente instalar as libraries do BLAS/LAPACK

brew install openblas
brew install lapack

Talvez tb pecise de:

brew install gcc

**Comment by mdavinicius** [comment]
> pip3 install scipy

Não sei se pode ser alguma incompatibilidade com o chip M1... mas tentando aqui o comand ocom o scipy, deu isso:
![image](https://user-images.githubusercontent.com/85064177/146701228-b921e661-86c8-467e-8c8a-a6ffc64597c1.png)

Engraçado que continuou, mas ai seguiu uns erros kilometricos..... foi instalado todas as versões do scipy de traz pra frente  🙈
![image](https://user-images.githubusercontent.com/85064177/146701419-258493f3-2ae0-4082-af93-f3f2842ef60d.png)

Vou tentar o que comentou agora pouco do brew e já volto :)

**Comment by mdavinicius** [comment]
> Opa, comi bola na leitura do erro, tente instalar as libraries do BLAS/LAPACK
> 
> brew install openblas brew install lapack
> 
> Talvez tb pecise de:
> 
> brew install gcc

Poxa poxa
![image](https://user-images.githubusercontent.com/85064177/146701906-3553cb13-cd7b-4b48-a4ea-1bc9b311da2c.png)

**Comment by fguide** [comment]
Você pode tentar baixar o wheel do scipy e tentar instalar com ele, mas talvez de erro também, baixe em:

https://pypi.org/project/scipy/#files

Escolha de acordo com sua versao de mac, depois de baixado digite pip3 install diretorio/arquivo.whl

Ou entao instale o homebrew, vai ser mais simples com ele ajustar as dependencias:

https://brew.sh/

**Comment by mdavinicius** [comment]
> SIm, tente o seguinte na pasta do bot:
> 
> pip3 install -r requirements.txt
> 
> e depois:
> 
> python3 index.py

Mals a demora. Dia corrido d+ hoje....

Começou bem a instalação:
![image](https://user-images.githubusercontent.com/85064177/146855396-c19f9187-53cb-41da-a54e-193699ef2289.png)

Mas depois de um tempo veio o erro gigantesco de novo:
- Começo do erro
![image](https://user-images.githubusercontent.com/85064177/146855646-f21e9365-033f-4a07-b39d-425a1f1d64d5.png)

- Fim do erro
![image](https://user-images.githubusercontent.com/85064177/146855589-9df8230f-1564-41d3-8cc7-78452d60acd5.png)

E ai nem adianta tentar rodar o bot que vai dar erro:
![image](https://user-images.githubusercontent.com/85064177/146855620-8272c789-d3a3-4035-8129-20299379b648.png)

**Comment by mdavinicius** [comment]
> Você pode tentar baixar o wheel do scipy e tentar instalar com ele, mas talvez de erro também, baixe em:
> 
> https://pypi.org/project/scipy/#files
> 
> Escolha de acordo com sua versao de mac, depois de baixado digite pip3 install diretorio/arquivo.whl
> 
> Ou entao instale o homebrew, vai ser mais simples com ele ajustar as dependencias:
> 
> https://brew.sh/

Mals a demora. Dia mega corrido hoje...

Sobre as sugestões que me deu, você estava certo, deu erro tentando instalar a o scipy manualmente.

Já o homebrew, deu boa! 
![image](https://user-images.githubusercontent.com/85064177/146856137-417303fb-4b3a-41d5-9134-6da6e44f1e3f.png)

O que eu deveria fazer agora?

**Comment by fguide** [comment]
tente agora com o brew:

brew install openblas
brew install lapack

depois pip3 install -r requirements.txt no diretorio do bot.

**Comment by mdavinicius** [comment]
> brew install openblas

Acabou de instalar, e deu boa pelo print, não deu?

Pq tento fazer o que me pediu, e aparece: "zsh: command not found: brew"

**Comment by mdavinicius** [comment]
> tente agora com o brew:
> 
> brew install openblas brew install lapack
> 
> depois pip3 install -r requirements.txt no diretorio do bot.

esquece de mim nao :(

**Comment by fguide** [comment]
Opa, desculpe.

**Comment by mdavinicius** [comment]
Imagina! Tu tava me ajudando pacas :)

Acho que com Mac, não da boa mesmo.... 
Eu usei uns comando que achei aqui - https://stackoverflow.com/questions/36657321/after-installing-homebrew-i-get-zsh-command-not-found-brew

E no final, da sempre o erro gigantesco :/ 
![image](https://user-images.githubusercontent.com/85064177/147311046-4045b028-4f79-41a5-9f05-8ce495628e73.png)

Final do erro
![image](https://user-images.githubusercontent.com/85064177/147311061-229ee119-cd74-4abf-97c6-d0590505230b.png)

Deixa pra la ://

**Comment by fguide** [comment]
Rapaz, tente instalar uma VM no macp ra rodar, mas dá certo sim, estou vendo que o brew ainda nao instalou o BLAS

tente: 

/opt/homebrew/bin/brew install openblas
/opt/homebrew/bin/brew install lapack
