### ISSUE TITLE
Captcha pega apenas dois numeros

### ISSUE THREAD

**Issue by Sharqboi** [mpcabete/bombcrypto-bot#402]
![gif](https://i.imgur.com/He66Q2y.gif)

alguem mais com esse erro que o bot captura apenas os dois numero ???
coloquei em gif para ficar melhor de ver o erro

**Comment by llFerreira** [comment]
Diminui teu Zoom, está muito alto. Caso nao funcione, tire print do quadrado do captcha e substitui dentro da pasta onde ele fica alocado e tenta novamente

**Comment by Sharqboi** [comment]
> Aumenta o zoom, pelo visto o zoom ta pouco para ele capturar bem a area do captcha. Caso nao funcione, tire print do quadrado do captcha e substitui dentro da pasta onde ele fica alocado e tenta novamente

esse do zoom nao adiantou nada, e nao tem como trocar a foto do captcha ele nao esta salvo em nenhuma pasta

**Comment by Reptile0** [comment]
Estou com o mesmo problema

**Comment by Sharqboi** [comment]
Resolvido no outro issue #403
