### ISSUE TITLE
Captcha começa errado e só pega 2 números 

### ISSUE THREAD

**Issue by Reptile0** [mpcabete/bombcrypto-bot#403]
Já tentei quase de tudo e não achei uma solução ainda, alguém tem alguma sugestão? Já tentei mudar algumas coisas no bot mesmo sendo bem noobzão mas não obtive sucesso, agradeço desde já a sua ajuda :)

**Comment by llFerreira** [comment]
Adicione um print, que ficará mais facil de ajudar

**Comment by Reptile0** [comment]
Me desculpe pela má qualidade
![20211220_212250](https://user-images.githubusercontent.com/96292969/146850383-79b7cd09-4a8a-4fab-9ab2-36227bf3072c.gif)

**Comment by llFerreira** [comment]
De zoom no teu navegador ate ele capturar bem a area do captcha, ou tu printa a area do captcha nesse zoom e cola na pasta destinado a ele, trocando o arquivo.

**Comment by Reptile0** [comment]
Você poderia me dar uma dica de qual seria essa pasta/arquivo que devo mudar?

**Comment by Sharqboi** [comment]
Consegui resolver o erro. É bem bobo na realidade e nao sei como nao reparei.

![robot](https://user-images.githubusercontent.com/95830499/147042334-0e974c6e-16bd-436e-9d10-8d5290e9e336.png)

so trocar essa imagem. Ele começa o ponteiro onde se inicia o printscreen do robot.png por isso esse erro acontece.

**Comment by Reptile0** [comment]
Caraca kkk, obrigado de qualquer forma !!
