### ISSUE TITLE
Aleatoriedade

### ISSUE THREAD

**Issue by LRBarbieri** [mpcabete/bombcrypto-bot#404]
Boa noite, vi que foi adicionado um tempo aleatório para executar as ações, mas gostaria de saber qual é esse intervalo. Por exemplo, se eu mudar nas configurações para colocar para trabalhar a cada 10 minutos, qual o tempo que ele vai realmente colocar? Parabéns pelo bot, você é brabo.

**Comment by fguide** [comment]
> addRandomness(t['send_heroes_for_work'] * 60):

Adiciona de 1 a 60 segundos aleatorios.

**Comment by fguide** [comment]
São 10 minutos mais algo random entre 10 ~ 60

addRandomness(t['send_heroes_for_work'] * 60)

**Comment by LRBarbieri** [comment]
> São 10 minutos mais algo random entre 10 ~ 60
> 
> addRandomness(t['send_heroes_for_work'] * 60)

Entendi, então é de 10 minutos até 60 minutos?
