### ISSUE TITLE
Importante!!! Refresh (F5)

### ISSUE THREAD

**Issue by fx2016** [mpcabete/bombcrypto-bot#406]
Bom dia, essa madrugada teve algum problema na página e ela não atualizou por completo.

O bot está funcionando perfeitamente, parabéns @mpcabete!!!, mas, em virtude do problema na página, deixou de funcionar.

Não sei se existe essa possibilidade, mas seria interessante se o bot após ficar 30 minutos sem clicar em nada, conseguisse dar uma atualizada na página e recomeçar do login.

Faz pouco tempo que estou no jogo e tenho poucos heroes, mas em breve vou fazer minha primeira (de muitas) doações para o projeto.

Muito obrigado, parabéns pelo excelente trabalho.

**Comment by yassbeno** [comment]
This exists, see pull request https://github.com/mpcabete/bombcrypto-bot/pull/84

**Comment by fx2016** [comment]
Obrigado @yassbeno, por favor, poderia me dizer se basta incluir em _config.yaml_ isso?

    # [en_US] Mouse last movement time limit before F5 (Solve stuck situations Ex: screen w/o buttons)
    # Default value (in minutes): 5 
    #
    # [pt_BR] Tempo limite que o mouse pode ficar sem se movimentar acionar o F5
    # Valor padrão (em minutos): 5
    check_for_game_crash: 5 #min

 Tem que alterar também em _index.py_?

**Comment by yassbeno** [comment]
Modifying index.py is primordial, click files changed in the pull request, and adapt your index.py accordingly  : 
![image](https://user-images.githubusercontent.com/40161273/146784994-ef3e242a-9af8-4850-b394-11cedd3c44e3.png)

**Comment by fx2016** [comment]
Infelizmente não entendo, até sei o que fazer, mas não sei como. Obrigado pela atenção @yassbeno 👍

**Comment by llFerreira** [comment]
Se nao me engano, o proprio bot ja tem essa funçao em "Loggin Attempts many", algo assim. Ele da um CTRL F5 se o jogo travar ou o bot encontrar algum error no jogo que o impossibilita de realizar a funçao por mais de 3x. Nao entendo nada de programaçao, e se eu estiver falando M alguem me corrija pfv.

![image](https://user-images.githubusercontent.com/41524514/146832695-ba402a9a-4a2e-4fa3-aba5-61ea26149284.png)

**Comment by fx2016** [comment]
> Se nao me engano, o proprio bot ja tem essa funçao em "Loggin Attempts many", algo assim. Ele da um CTRL F5 se o jogo travar ou o bot encontrar algum error no jogo que o impossibilita de realizar a funçao por mais de 3x. Nao entendo nada de programaçao, e se eu estiver falando M alguem me corrija pfv.
> 
> ![image](https://user-images.githubusercontent.com/41524514/146832695-ba402a9a-4a2e-4fa3-aba5-61ea26149284.png)

Se já tem é pior, porque não funcionou

**Comment by llFerreira** [comment]
> Se já tem é pior, porque não funcionou

Aqui funciona e muito, tem hora que funciona ate na hora que os bombers estao ativos, da uma certa raiva, mas fazer oque.
Pode ter travado o seu navegador, ao inves do jogo, nao?

**Comment by fx2016** [comment]
> > Se já tem é pior, porque não funcionou
> 
> Aqui funciona e muito, tem hora que funciona ate na hora que os bombers estao ativos, da uma certa raiva, mas fazer oque. Pode ter travado o seu navegador, ao inves do jogo, nao?

Pode ser, não descarto. Agradeço imensamente teu feedback.
