### ISSUE TITLE
Bot com raciocínio lento...

### ISSUE THREAD

**Issue by pegchargue** [mpcabete/bombcrypto-bot#408]
Queria uma ajuda a respeito da utilização do Bot... O meu quando clica em connect-wallet depois ele não ativa na metamask, ou demora muito para clicar e então aparece o aviso de tempo expirado... Eu abro a página do bomb depois abro o bot e deixo ele se conectar sozinho e como falei (as vezes ele conecta) o capcha funciona perfeitamente!!! Durante o dia ele fica conectado e fica umas 2 ou 3 oras corridas funcionando perfeitamente, as as vezes dá algum erro e tenho que reconectar manualmente, mas de madrugada não funciona. Atualizo as páginas, reinicio o prompt e deixo funcionando, mas não fica a noite toda, acho que deve ficar umas 2 ou 3 horas depois para geral... alguma dica para fazer funcionar 100% a noite toda??? se eu as vezes mexer no mouse pode atrapalhar o bot?? tem algum procedimento correto para iniciar tudo??? Obrigado desde já pela ajuda!!!

**Comment by LRBarbieri** [comment]
Tira um print do botão de sign e substitui na pasta targets se não me engano. O meu roda a noite toda sem problemas.

**Comment by pegchargue** [comment]
Já fiz isso... as vezes só funciona a primeira vez, mas depois fica igual...

**Comment by pegchargue** [comment]
Fica como se o bot ficasse pensando durante muito tempo o que tem que fazer... ele faz, mas atrasado... e acho que não é por culpa do computador, pois está trabalhando somente com o bot, não tem mais nada instalado

**Comment by llFerreira** [comment]
Vai na config e diminui o threshold do connect wallet e testa

**Comment by fx2016** [comment]
> Vai na config e diminui o threshold do connect wallet e testa

Bom dia @llFerreira, por favor, como faço isso?

**Comment by pegchargue** [comment]
> Vai na config e diminui o threshold do connect wallet e testa

Tentei fazer, mas deu erro na linha... troquei o exclui o arquivo e coloquei o outro e agora está funcionando redondinho!!! sem fazer alteração nenhuma. desde ontem a tarde quando abri o assunto. Tomara que agora que falei que está funcionando não pare de funcionar novamente....rsrsrs.
Obrigado pela ajuda!!!
