### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by Dfcrespii** [mpcabete/bombcrypto-bot#409]
Boa tarde mpcabete, gostaria de entrar em contato com você para ver se tem a possibilidade de você fazer um bot para outro jogo.

Me manda um e-mail fazendo o favor.
dfcrespi@protonmail.com

Ou me fala como posso entrar em contato com você.

Obrigado

**Comment by trinitro2** [comment]
tem um email na pagina do script. so ler

**Comment by Dfcrespii** [comment]
E tem mesmo... tinha procurado heim... mas só foi falar que achei kkkk
Putz
