### ISSUE TITLE
Novos assets pra outras raridades

### ISSUE THREAD

**Issue by henriquelbsouza** [mpcabete/bombcrypto-bot#41]
![image](https://user-images.githubusercontent.com/1070818/142652122-07c28cb5-1ca8-4cdd-8a64-3461c9ff36f0.png)
![image](https://user-images.githubusercontent.com/1070818/142652162-dea851b7-74e7-42e1-9f29-063be6ce7f5d.png)
![image](https://user-images.githubusercontent.com/1070818/142652187-d8ce7c52-0f0f-4db5-a591-9ddb26b0da51.png)
![image](https://user-images.githubusercontent.com/1070818/142652195-4ea24f84-40f4-4167-a642-661357fde3d7.png)

Os outros eu não tenho pra pegar...

**Comment by henriquelbsouza** [comment]
Vi que tem o common, mas não encontrei os outros. Não sei implementar isso em python, mas posso tentar durante a semana que vem implementar algo.

**Comment by jocieldo-soap** [comment]
Olá amigo, tu consegue a imagem de uma barrinha verde cheia? hehehe

**Comment by henriquelbsouza** [comment]
Só amanhã na hora q eu acordar kkkkk

**Comment by jocieldo-soap** [comment]
> Só amanhã na hora q eu acordar kkkkk

Show de bola kkkkk

**Comment by guirar** [comment]
Não precisa, é só ajustar o treshhold nas imagens dos personagens em 0.05 pra baixo

**Comment by henriquelbsouza** [comment]
![image](https://user-images.githubusercontent.com/1070818/142725628-d24e3540-ad80-48bf-88ce-d4ae5416b366.png)

**Comment by eztzez** [comment]
> ![image](https://user-images.githubusercontent.com/1070818/142725628-d24e3540-ad80-48bf-88ce-d4ae5416b366.png)

Ola meu irmão
Também tenho quase tudo funcionando perfeitamente !!
Só quero que o código atualizado envie os heróis para casa, já que comprei um.
por favor me ajude

**Comment by nmmorette** [comment]
queria configurar para enviar o heroi somente full e não só quando ficar um pouco verdinho. 
alguém saber como fazer? só trocar a imagem não funcionou
