### ISSUE TITLE
BOT não está rodando

### ISSUE THREAD

**Issue by martineix** [mpcabete/bombcrypto-bot#410]
Olá, parabéns pelas melhorias e funcionalidades do BOT.
Gostaria de tentar entender o que pode estar acontecendo. Meu BOT não roda. baixei a versão atualizada.

Vide abaixo, os erros aparecem logo depois de dar play.

![image](https://user-images.githubusercontent.com/67521151/146818956-1d0a29a0-f192-4b5d-9e5c-b6156c3446d5.png)

**Comment by pedrozun** [comment]
Baixa o bot denovo e apaga o que voce ta usando.

**Comment by martineix** [comment]
> Baixa o bot denovo e apaga o que voce ta usando.

Testando agora, brother... Vamos ver!

**Comment by martineix** [comment]
> Baixa o bot denovo e apaga o que voce ta usando.

Deu certo, amigo! Vocês são fera demais!
