### ISSUE TITLE
Erro Xrandr no ubuntu 20.04 lts na vm google cloud

### ISSUE THREAD

**Issue by sbragnot** [mpcabete/bombcrypto-bot#411]
Alguem pode me ajudar a criar uma vm na google cloud e instalar o bot, consegui com o windows mas é muito caro eu não posso desligar o pc, no linux não consegui fazer o bot rodar

**Comment by PacLucas** [comment]
Esse [tutorial](https://www.youtube.com/watch?v=eolNziYLe9Y&ab_channel=TechnoWorldHD) é nice e não deu erro pra mim no processo

**Comment by sbragnot** [comment]
> Esse [tutorial](https://www.youtube.com/watch?v=eolNziYLe9Y&ab_channel=TechnoWorldHD) é nice e não deu erro pra mim no processo

Vou tentar aqui, sabe me dizer se com esse processo consigo rodar o bot mesmo com o pc deligado? 
esse é meu objetivo.

**Comment by soundsticks** [comment]
Posso saber a configuração mínima para nuvem? 1 núcleo com 2 gb de RAM o suficiente?

**Comment by PacLucas** [comment]
> > Esse [tutorial](https://www.youtube.com/watch?v=eolNziYLe9Y&ab_channel=TechnoWorldHD) é nice e não deu erro pra mim no processo
> 
> Vou tentar aqui, sabe me dizer se com esse processo consigo rodar o bot mesmo com o pc deligado? esse é meu objetivo.

Consegue sim, ele roda 24/7 tranquilo, no meu caso só entro às vezes pelo NoMachine pare ver se não travou nada

**Comment by PacLucas** [comment]
> Posso saber a configuração mínima para nuvem? 1 núcleo com 2 gb de RAM o suficiente?

o meu coloquei 4 núcleos e 8gb e ele fica em uns 80% de uso constante, não liguei muito pra deixar mais leve pq com opção de preemptividade cai bastante o custo da VM

**Comment by Gaboo134** [comment]
galera boa noite tenho um noot com i3, porem ta travando muito na tela a 100%, tem como rodar o bot a 60% ou é impossível, obrigado

**Comment by sbragnot** [comment]
> > > Esse [tutorial](https://www.youtube.com/watch?v=eolNziYLe9Y&ab_channel=TechnoWorldHD) é nice e não deu erro pra mim no processo
> > 
> > 
> > Vou tentar aqui, sabe me dizer se com esse processo consigo rodar o bot mesmo com o pc deligado? esse é meu objetivo.
> 
> Consegue sim, ele roda 24/7 tranquilo, no meu caso só entro às vezes pelo NoMachine pare ver se não travou nada

root@bomb1:~# sudo apt install ./nomachine_7.7.4_1_amd64.deb
Reading package lists... Error!
E: Sub-process Popen returned an error code (2)
E: Encountered a section with no Package: header
E: Problem with MergeList /root/nomachine_7.7.4_1_amd64.deb
E: The package lists or status file could not be parsed or opened.


cara tentei o 20.04, o 18, tentei com varios jeitos e sempre da esse erro, tentei a versao do video, tentei a versao mais nova sempre da esse erro tem ideia do que seja?

**Comment by sbragnot** [comment]
Puta que pariu consegui https://youtu.be/UYLA_fFdciA assisti esse video depois de umas 40 tentativas deu certo, tem algum comando que eu preciso ativar pra ele rodar 24/7?

**Comment by fguide** [comment]
Em teoria é só deixar rodando e esquecer, acesse a cada tempo para ver se deu erro. Se você quer automatizar, ligar a VM e tudo já funcionar, é possível, porém no primeiro acesso é necessário colocar sua senha do metamask, dessa forma você precisaria armazenar de alguma forma, mesmo encriptado eu nao acho que valha o risco, é melhor colocar pra rodar manualmente e depois só conferir se deu algum problema.

Dica extra: se vc quiser acompanhar se o bot está rodando, ative a escrita de log para o disco no config.yaml e em uma sessao ssh faça tail para o arquivo de log.

**Comment by PauloBTX** [comment]
Por curiosidade alguém tentou em um raspberry?

**Comment by fguide** [comment]
> Por curiosidade alguém tentou em um raspberry?

Rodei em um RPI3b+, funcionou bem pra mim, só cuidado com refrigeração porque aqui esquentou bem.
