### ISSUE TITLE
ban risk? (risco de ban?)

### ISSUE THREAD

**Issue by lnktroll0709** [mpcabete/bombcrypto-bot#413]
queria saber do pessoal a quanto tempo vcs usam o bot e se alguem ja tomou ban do game usando o bot

**Comment by Galinho90** [comment]
> queria saber do pessoal a quanto tempo vcs usam o bot e se alguem ja tomou ban do game usando o bot

A mais de 2 semanas.

**Comment by lnktroll0709** [comment]
> > queria saber do pessoal a quanto tempo vcs usam o bot e se alguem ja tomou ban do game usando o bot
> 
> A mais de 2 semanas.

eu to usando a 3 dias, tem site falando que os devs estao monitorando o ponteiro do mouse pra ver quem ta usando bot, sera q isso pode ser verdade?

**Comment by Yumiizera** [comment]
#222

**Comment by lnktroll0709** [comment]
> > > > queria saber do pessoal a quanto tempo vcs usam o bot e se alguem ja tomou ban do game usando o bot
> > > 
> > > 
> > > A mais de 2 semanas.
> > 
> > 
> > eu to usando a 3 dias, tem site falando que os devs estao monitorando o ponteiro do mouse pra ver quem ta usando bot, sera q isso pode ser verdade?
> 
> Poderia até ser se webgl permitisse o track mouse moviments.

entao webgl n tem como dar track no mouse?

**Comment by trinitro2** [comment]
se banir quem eles acham que ta usando bot, vai banir muita gente que nem ta. igual baniram centenas de contas que nem usaram speed hack

**Comment by Nucito** [comment]
Agradeço se olhar o issue fixado!
