### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by Galinho90** [mpcabete/bombcrypto-bot#414]
Alguem consegue ajudar do que se trata o erro abaixo, ja atualizei o windows, até formatei para ver se corrigia e nada: 

![image](https://user-images.githubusercontent.com/95733162/146878820-2ad6e9c4-0a34-432d-b168-266fe1f4c7e5.png)

**Comment by pedrozun** [comment]
Eu posso ajudar.

**Comment by Galinho90** [comment]
> Eu posso ajudar.

Sim , como posso fazer pra resolver ?

**Comment by Kiera-17** [comment]
Boa noite, também gostaria de saber, estou com o mesmo problema.

**Comment by Galinho90** [comment]
> Boa noite, também gostaria de saber, estou com o mesmo problema.

Cara pelo incrível que pareça eu resolvi, reinstalei o Windows baixando o iso direto da Microsoft. Agora tá rodando filé

**Comment by pedrozun** [comment]
> > Boa noite, também gostaria de saber, estou com o mesmo problema.
> 
> Cara pelo incrível que pareça eu resolvi, reinstalei o Windows baixando o iso direto da Microsoft. Agora tá rodando filé

Não precisava, mas funciona 🤣

**Comment by Kiera-17** [comment]
> > Boa noite, também gostaria de saber, estou com o mesmo problema.
> 
> Cara pelo incrível que pareça eu resolvi, reinstalei o Windows baixando o iso direto da Microsoft. Agora tá rodando filé

Nossa parece ser difícil, irei esperar uma boa alma me ajudar, obrigada.

**Comment by Galinho90** [comment]
> > > Boa noite, também gostaria de saber, estou com o mesmo problema.
> > 
> > 
> > Cara pelo incrível que pareça eu resolvi, reinstalei o Windows baixando o iso direto da Microsoft. Agora tá rodando filé
> 
> Nossa parece ser difícil, irei esperar uma boa alma me ajudar, obrigada.

Olha igual eu falei só consegui formatando, agora como resolver sem fazer desta forma não sei informar.
