### ISSUE TITLE
O bot não funciona quando eu fecho a janela de acesso remoto ao servidor

### ISSUE THREAD

**Issue by vaskhan** [mpcabete/bombcrypto-bot#415]
O bot não funciona quando eu fecho a janela de acesso remoto ao servidor, deveria ser? Precisa sempre manter a janela de conexão com o servidor ligado?

**Comment by mtmassa** [comment]
Tive o mesmo problema com uma vps, parece que quando fecha e a janela fecha e vai pra tela de log e parece parar de funcionar, resolvido instalndo uma VM mesmo, instalei no linux ate, acabou os problemas, nao parece ser problema do bot e sim dos windows server.

**Comment by vaskhan** [comment]
> Tive o mesmo problema com uma vps, parece que quando fecha e a janela fecha e vai pra tela de log e parece parar de funcionar, resolvido instalndo uma VM mesmo, instalei no linux ate, acabou os problemas, nao parece ser problema do bot e sim dos windows server.

então você só precisa reinstalar o windows no linux?

**Comment by trinitro2** [comment]
ai é problema do servidor virtual que voce contratou que entra em modo repouso. Nao é problema do bot.

**Comment by fguide** [comment]
Crie um batch no windows com o codigo abaixo e rode ele para desconectar a sessao:

for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
  %windir%\System32\tscon.exe %%s /dest:console
)

**Comment by vaskhan** [comment]
> Crie um batch no windows com o codigo abaixo e rode ele para desconectar a sessao:
> 
> for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do ( %windir%\System32\tscon.exe %%s /dest:console )

diga-me, onde é necessário prescrever? usado em cmd " query session; tscon 1 / dest:console" mas ainda funciona intermitentemente. Talvez sua opção corrija o problema em 100%
