### ISSUE TITLE
Bot para quando servidor apresenta "Unknown"

### ISSUE THREAD

**Issue by phillcrypto** [mpcabete/bombcrypto-bot#42]
Primeiramente parabéns pelo projeto!

Toda vez que o servidor buga e aparece essa mensagem de "Unknown" o bot fica parado e não consegue relogar... Tem alguma solução?

**Comment by matheusgm0** [comment]
aqui esta funcionando 100% amigo, e algo ai com voce, tenta tirar novas fotos com qualidade melhor e substituir no targets

**Comment by yadriel123** [comment]
> aqui esta funcionando 100% amigo, e algo ai com voce, tenta tirar novas fotos com qualidade melhor e substituir no targets

Amigo o meu não está clicando no work, ele tenta clicar mas ele clica ao lado, sabe alguma config pra mudar o local que ele vai clicar pra ele clicar um pouquinho pro lado?

**Comment by matheusgm0** [comment]
esse bot nao tem por coordenada, ele se baseia por imagem, testa tirar novas fotos e trocar pelas que estao na targets com mesmo nome e com qualidade boa.  pode ser tambem: checa se voce nao esta usando 2 monitores, se tiver desconecta um e tenta, e em config testa essa:  
trashhold:
    default: 0.9
    commom: 0.8
    select_wallet_buttons: 0.5
    go_to_work_btn: 0.8
    green_bar: 0.9

**Comment by yadriel123** [comment]
> esse bot nao tem por coordenada, ele se baseia por imagem, testa tirar novas fotos e trocar pelas que estao na targets com mesmo nome e com qualidade boa. pode ser tambem: checa se voce nao esta usando 2 monitores, se tiver desconecta um e tenta, e em config testa essa: trashhold: default: 0.9 commom: 0.8 select_wallet_buttons: 0.5 go_to_work_btn: 0.8 green_bar: 0.9

Já o fiz de tirar novas fotos, porém pela configuração parece que ele não está usando a foto q eu tiro para clicar no work, ele meio que compara a print tirada da tela com a imagem, mas pra clicar não conseguir achar pra mudar a distancia ou algo do tipo, se liga nessa parte do codigo:

def positions(target, trashhold=ct['default']):
    img = printSreen()
    result = cv2.matchTemplate(img,target,cv2.TM_CCOEFF_NORMED)
    w = target.shape[1]
    h = target.shape[0]

    yloc, xloc = np.where(result >= trashhold)


    rectangles = []
    for (x, y) in zip(xloc, yloc):
        rectangles.append([int(x), int(y), int(w), int(h)])
        rectangles.append([int(x), int(y), int(w), int(h)])

    rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
    return rectangles


sinto que tá por ai kkk

**Comment by matheusgm0** [comment]
estranho... entao, se vc for mexer ai voce vai ter que alterar toda a linha colocando fixo a coordenada... porem se nao tem nenhum desses erros nao sei o que pode ser, ultima coisa seria voce confirmar se sua escala esta em 100% no windows

**Comment by yadriel123** [comment]
> 

cara consegui arrumar kkkkk, lá na parte de clickgreenbarbutton, eu mudei o offset de 130 pra 150, daí ele meio q clica pro lado um pouquinho e era oq eu precisava hahaha, vlw ai

**Comment by matheusgm0** [comment]
enx,boa!!

**Comment by phillcrypto** [comment]
Mas o bot corrige o "unknown"?

**Comment by matheusgm0** [comment]
corrige todos os erros, eu praticamente nao estou mexendo mais no meu... tudo o proprio bot detecta, so estou vendo agora em relacao a nao estar sumonando certos tipos de herois

**Comment by phillcrypto** [comment]
Qual navegador vc usa? E usa algum VPN?

**Comment by matheusgm0** [comment]
chrome, nenhum

**Comment by guirar** [comment]
> corrige todos os erros, eu praticamente nao estou mexendo mais no meu... tudo o proprio bot detecta, so estou vendo agora em relacao a nao estar sumonando certos tipos de herois

Tem que ajustar o treshhold, coloca o common em 0.75 o go_to_work 0.85 e o green_bar 0.85
Aqui deu certo, agora coloca todos pra trabalhar

**Comment by eztzez** [comment]
> > esse bot nao tem por coordenada, ele se baseia por imagem, testa tirar novas fotos e trocar pelas que estao na targets com mesmo nome e com qualidade boa. pode ser tambem: checa se voce nao esta usando 2 monitores, se tiver desconecta um e tenta, e em config testa essa: trashhold: default: 0.9 commom: 0.8 select_wallet_buttons: 0.5 go_to_work_btn: 0.8 green_bar: 0.9
> 
> Já o fiz de tirar novas fotos, porém pela configuração parece que ele não está usando a foto q eu tiro para clicar no work, ele meio que compara a print tirada da tela com a imagem, mas pra clicar não conseguir achar pra mudar a distancia ou algo do tipo, se liga nessa parte do codigo:
> 
> def positions(target, trashhold=ct['default']): img = printSreen() result = cv2.matchTemplate(img,target,cv2.TM_CCOEFF_NORMED) w = target.shape[1] h = target.shape[0]
> 
> ```
> yloc, xloc = np.where(result >= trashhold)
> 
> 
> rectangles = []
> for (x, y) in zip(xloc, yloc):
>     rectangles.append([int(x), int(y), int(w), int(h)])
>     rectangles.append([int(x), int(y), int(w), int(h)])
> 
> rectangles, weights = cv2.groupRectangles(rectangles, 1, 0.2)
> return rectangles
> ```
> 
> sinto que tá por ai kkk

Ola meu irmão
Também tenho quase tudo funcionando perfeitamente !!
Só quero que o código atualizado envie os heróis para casa, já que comprei um.
por favor me ajude
