### ISSUE TITLE
bot não clica no botão work

### ISSUE THREAD

**Issue by pedrokeplerpkpv** [mpcabete/bombcrypto-bot#420]
nao consigo por nada nesse mundo fazer o bot clicar no botao work, ele sempre clica fora, ja mudei a imagem do target varias vezes. Alguém pode me dar uma luz?

**Comment by Felipecristao** [comment]
irmao verifica se o teu game esta em linguagem brazil, se estiver muda para ingles. o bot esta configurado em ingles.
