### ISSUE TITLE
Nao faz o captcha

### ISSUE THREAD

**Issue by QuaresmaZ** [mpcabete/bombcrypto-bot#422]
Bot nao clicava em botao nenhum, ai eu troquei todas as imagens por imagem que eu tirei print e funcionou menos o captcha porque nao sei que imagem trocar. O bot nao reconhecia nada até eu trocar as imagens todas.

**Comment by Nucito** [comment]
1 - Qual seria a resolução do seu monitor?
2 - Qual sua versão do python?
3 - Já procurou nos outros issues se alguém estava com o mesmo problema?

**Comment by hamzalamou** [comment]
@Nucito olá mano você pode me ajudar em algo
não funciona muito bem no firefox
mas quando eu tento no Brave ou Chrome não funciona

**Comment by QuaresmaZ** [comment]
> 

1-2240x1400
2- 3.9
3- Já mas só nao está a dar no novo update porque no anterior consegui tirar print aos numeros do captcha e funcionou. Foi neste update que não dá. O bot tenta resolver (mexe a barra do captcha) mas nao consegue encontrar a solução e escolhe sempre a primeira opção.
