### ISSUE TITLE
Demasiados cliques.

### ISSUE THREAD

**Issue by urden7** [mpcabete/bombcrypto-bot#423]
Estou dirigindo quatro contas. Diz que demasiados cliques de herói tentam criar o limiar de trabalho btn no cmd e frequentemente não o reconhece na janela de caracteres. Como resolver isto?

**Comment by lsruiz08** [comment]
Estou com o mesmo problema, só que na hora de mandar os heróis para trabalhar, o cursor do mouse vai até o icone do herói, e nota-se que ele clica, mas nada faz.

**Comment by fguide** [comment]
#387 veja se ajuda a ultima resposta.
