### ISSUE TITLE
Heróis não são enviados para trabalhar (Heroes aren't sent to work)

### ISSUE THREAD

**Issue by lsruiz08** [mpcabete/bombcrypto-bot#424]
Pessoal, estou tendo problema para enviar os heróis para trabalhar cada tempo determinado no arquivo config.yaml.

Notei que quando chega o tempo determinado, o bot volta para tela inicial, direciona o cursor para ícone do herói (hero-icon), porém nada faz, vejo que o cursor fica "piscando", como se tivesse clicando no ícone, mas não abre a tela de seleção dos heróis.

Olhei nos logs e a mensagem de erro que aparece é:

"too many hero clicks, try to increase the go_to_work_btn threshold"

Mudei os valores, tanto para mais, quanto para menos que o padrão documentado, e mesmo assim o problema persiste.

Notei que isso começou a acontecer na madrugada de ontem para hoje, e desde então essa funcionalidade parou.

Alguém mais com esse problema? Como resolver?

---

Guys, I am having a problem sending the heroes to work each given time in the config.yaml file.

I noticed that when the determined time arrives, the bot returns to the initial screen, directs the cursor to the hero icon (hero-icon), but does nothing, I see that the cursor keeps "blinking", as if I was clicking on the icon, but does not open the hero selection screen.

I looked in the logs and the error message that appears is:

"too many hero clicks, try to increase the go_to_work_btn threshold"

I changed the values, both more and less than the documented default, and still the problem persists.

I noticed that this started happening in the early hours of yesterday to today, and since then this functionality has stopped.

Anyone else having this problem? How to solve it?

**Comment by vst212** [comment]
same, no response on hero icon

**Comment by fguide** [comment]
#387 o ultima resposta talvez ajude.

**Comment by lsruiz08** [comment]
> #387 o ultima resposta talvez ajude.

Resolveu irmão! deixou o processo um pouco mais lento, mas resolveu seguindo essa issue que você citou! Obrigado ;)
