### ISSUE TITLE
BombCrypto em Maquina Virtual (VMWARE)

### ISSUE THREAD

**Issue by CorreiaDeveloper** [mpcabete/bombcrypto-bot#425]
Galera podem me ajudar? estou tentando jogar o bomb pela VM porém nao chega nem a aparecer o botão de play ali... alguem tem alguma ideia do que possa ser?

![image](https://user-images.githubusercontent.com/57927012/147040239-2a74eec8-8537-4fad-8285-dd3deb6b7182.png)

**Comment by Stermik** [comment]
muda a URL ali do site, coloca o "app." antes do bombcrypto.io

**Comment by coradini1** [comment]
Resolução pequena demais

**Comment by fguide** [comment]
Você nao tem o metamask instalado? Pelo menos nao vejo a extensao na barra.  Resolucao eu uso 1024x76 sem problemas.

**Comment by CorreiaDeveloper** [comment]
> Você nao tem o metamask instalado? Pelo menos nao vejo a extensao na barra. Resolucao eu uso 1024x768 sem problemas.

Tenho sim amigo kkkk é que a resolução ta pequena, mas tenho sim!

**Comment by fguide** [comment]
> > Você nao tem o metamask instalado? Pelo menos nao vejo a extensao na barra. Resolucao eu uso 1024x768 sem problemas.
> 
> Tenho sim amigo kkkk é que a resolução ta pequena, mas tenho sim!

maravilha, o minimo que eu consegui foi 1024x768 sem barras nem nada, so janela do navegador!
