### ISSUE TITLE
Questão para develops

### ISSUE THREAD

**Issue by Mateuus** [mpcabete/bombcrypto-bot#427]
Se você é um desenvolvedor do bombercrypto? olhando para o código do bot, oque vocês faria para "Tentar" identificar se é bot ou não?

**Comment by Pedr0hng** [comment]
vou comentar para acompanhar, se vão tirar o captcha é um mal sinal kkkkkkk

**Comment by pedrozun** [comment]
Falaram que o webgl nao tem como fazer mouse track, é real?

**Comment by fguide** [comment]
> vou comentar para acompanhar, se vão tirar o captcha é um mal sinal kkkkkkk

Acho que na verdade é um sinal de que eles agora devem se preocupar com outras coisas, incluindo funções do jogo (que estao atrasadas), visto que por enquanto a batalha do captcha para eles é perdida.

**Comment by brunoleyne** [comment]
Sério mesmo que você quer entrar no forum público do projeto de automação e discutir ideias de como detectar e matar o projeto?

**Comment by cmxavier** [comment]
> Falaram que o webgl nao tem como fazer mouse track, é real?

Ouvi dizer que tem um navegador (ou alguma opcão) onde é possível desabilitar esse tracking, sabem dizer?

**Comment by fguide** [comment]
Todas as respostas das perguntas que vocês estão fazendo já foram respondidas aqui, é só buscar nos issues fechados.

**Comment by ricardofernandess** [comment]
Eu sei q tem vários tópicos sobre a possibilidade de detecção do bot e eu já li todos mas era dentro do contexto de uso do captcha. O consenso era que eles não conseguiriam detectar com precisão o uso de bot e implementaram o captcha para frear a navegação automatizada. 

Com a retirada do captcha será que o mesmo consenso se mantém? Será que simplesmente se "renderam" e assumiram a derrota para os bots (seja esse ou outros tantos privados por ai) ou tem algo embaixo da manga para pelo menos categorizar usuários como suspeitos (100% de precisão beira ao impossível ao meu ver, sempre terá falso positivo)

Talvez agora seja a hora de focar mais em randomização e suavizar os movimentos para parecer mais humano.

**Comment by Mateuus** [comment]
> Sério mesmo que você quer entrar no forum público do projeto de automação e discutir ideias de como detectar e matar o projeto?

Amigo você é desenvolvedor ? você consegue raciocinar oque eu quero dizer? 
Ninguém aqui quer matar o projeto e sim pensar e todos os métodos para dificultar ainda mais a detecção.

**Comment by fguide** [comment]
> Eu sei q tem vários tópicos sobre a possibilidade de detecção do bot e eu já li todos mas era dentro do contexto de uso do captcha. O consenso era que eles não conseguiriam detectar com precisão o uso de bot e implementaram o captcha para frear a navegação automatizada.
> 
> Com a retirada do captcha será que o mesmo consenso se mantém? Será que simplesmente se "renderam" e assumiram a derrota para os bots (seja esse ou outros tantos privados por ai) ou tem algo embaixo da manga para pelo menos categorizar usuários como suspeitos (não banir, mas apenas colocar numa outra lista para posterior análise, talvez um shadow ban com nerfs mais pesados nos baús, etc...)
> 
> Talvez agora seja a hora de focar mais em randomização e suavizar os movimentos para parecer mais humano.

Concordo, o problema é que por enquanto não dá para especular muito, o jogo ainda está fora e precisamos aguardar a volta para analisarmos as mudanças, se conseguimos descobrir algo diferente.

Infelizmente por enquanto só temos que aguardar o resultado da manutenção.

**Comment by brunoleyne** [comment]
> > Sério mesmo que você quer entrar no forum público do projeto de automação e discutir ideias de como detectar e matar o projeto?
> 
> Amigo você é desenvolvedor ? você consegue raciocinar oque eu quero dizer? Ninguém aqui quer matar o projeto e sim pensar e todos os métodos para dificultar ainda mais a detecção.

Sim sou Dev. Consigo entender sua lógica, mas ela faz mais mal do que bem ao projeto.
Esse projeto é código aberto, basicamente ele funciona na base de quem tem mais resiliência automatizadores x desenvolvedores do game. Basicamente você está fazendo um brainstorm de ideias de como é possível o admins detectarem o uso de bots (coisa que até o momento não aconteceu, ou pelo menos não temos provas concretas disso). Consigo ter de 2 a 3 ideias de cara de como detectar o uso desse bot (teria falso positivo). Ai te pergunto, vale a pena eu listar aqui essas ideias e detalhar exatamente como fazer isso? A chance de um dev do game ler isso é alta, vai que ele gosta e decide implementar a ideia no backend do game. Seria questão de tempo até começarmos a ter ban waves. O bot hoje só é safe de usar porque o jogo tem tanto problema de desempenho/bug/desenvolvimento novas funcionalidades(marketplace/modo historia) que os devs não estão tendo tempo de implementar uma ferramenta robusta de análise de contas, estão mais preocupados com a economia e resolver outros problemas de maior prioridade do que detectar o uso de bot. Existe um fator dificuldade de que toda ferramenta de detecção tem chance de gerar um falso positivo, ai teriam dor de cabeça pra fazer review de contas manual e ajustes no refinamento dessa ferramenta de detecção. Se quiser blindar sua conta quanto a possíveis bans, recomendo criar um fork do projeto e fazer leves alterações de comportamento para ficar mais fora do padrão e guardar pra você (guardar mesmo porque se jogar no publico, vira padrão).

**Comment by fguide** [comment]
Pessoal, eu respondi acima que existem as respostas para as perguntas nos issues, porque literalmente elas estão lá, por exemplo:

Navegador que bloqueia detecção de sensores (brave)
Biblioteca Human Clicker do python (https://github.com/patrikoss/pyclick) 
Diversas soluções de interação com bots de telegram, etc.

Ou seja, é só pesquisar soluções que atendam o que você acredita que vai te manter seguro e assumir o próprio risco.
