### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by coradini1** [mpcabete/bombcrypto-bot#429]
E ae, tá suave usar bot ainda ou n?

**Comment by victormass** [comment]
To esperando o @mpcabete se pronunciar kkkk

**Comment by noxfork** [comment]
por enquanto nao xD

**Comment by cmxavier** [comment]
Se pronunciar pq ??? O bot ta funcionando

**Comment by noxfork** [comment]
> Se pronunciar pq ??? O bot ta funcionando

@cmxavier 

https://github.com/mpcabete/bombcrypto-bot/issues/430#issue-1086795588   <- por isso!

**Comment by rodrigobragamg** [comment]
Ele não tem que se pronunciar e/ou se responsabilizar de nada... Cada um usa por sua conta e risco. Ele já deixou o aviso apropriado no github:

"Aviso:
Os desenvolvedores do jogo se pronunciaram e agora o uso de auto clickers e o uso de bots é oficialmente PROIBIDO. Não me responsabilizo por eventuais penalidades sofridas por quem usar o bot, use por sua própria conta e risco."

**Comment by noxfork** [comment]
> Ele não tem que se pronunciar e/ou se responsabilizar de nada... Cada um usa por sua conta e risco. Ele já deixou o aviso apropriado no github:
> 
> "Aviso: Os desenvolvedores do jogo se pronunciaram e agora o uso de auto clickers e o uso de bots é oficialmente PROIBIDO. Não me responsabilizo por eventuais penalidades sofridas por quem usar o bot, use por sua própria conta e risco."

mas ninguém ta falando que ele precisa se pronunciar a respeito do "possível" ban ou se responsabilizar por algo! 
vcs precisam aprender a interpretar textos e seguir o tópico inteiro antes de responder qualquer coisa q vem na cabeça..
o "se pronunciar", se vc tivesse lido meia dúzia de palavras a mais, vc saberia que estamos falando sobre ser ainda estar "suave" usar o bot (como o primeiro colega postou nesse tópico}.

**Comment by rodrigobragamg** [comment]
> > Ele não tem que se pronunciar e/ou se responsabilizar de nada... Cada um usa por sua conta e risco. Ele já deixou o aviso apropriado no github:
> > "Aviso: Os desenvolvedores do jogo se pronunciaram e agora o uso de auto clickers e o uso de bots é oficialmente PROIBIDO. Não me responsabilizo por eventuais penalidades sofridas por quem usar o bot, use por sua própria conta e risco."
> 
> mas ninguém ta falando que ele precisa se pronunciar a respeito do "possível" ban ou se responsabilizar por algo! vcs precisam aprender a interpretar textos e seguir o tópico inteiro antes de responder qualquer coisa q vem na cabeça.. o "se pronunciar", se vc tivesse lido meia dúzia de palavras a mais, vc saberia que estamos falando sobre ser ainda estar "suave" usar o bot (como o primeiro colega postou nesse tópico}.

?

Você literalmente postou um tópico que envolve uma conta supostamente suspensa para análise por uso do Script:
"#430 (comment) <- por isso!"

O post do autor, embora seja ambíguo, denota totalmente que sua preocupação se a utlização dá ban ou não.

E a resposta foi mais endereçada para outro comentário, logo abaixo do criador, que chamou o autor do script. Notou o verbo "pronunciar" na minha resposta?

Muito ao contrário do que cita, você que precisa ser adulto ou responsável e tomar suas próprias decisões. O aviso já está no github.

**Comment by noxfork** [comment]
> > > Ele não tem que se pronunciar e/ou se responsabilizar de nada... Cada um usa por sua conta e risco. Ele já deixou o aviso apropriado no github:
> > > "Aviso: Os desenvolvedores do jogo se pronunciaram e agora o uso de auto clickers e o uso de bots é oficialmente PROIBIDO. Não me responsabilizo por eventuais penalidades sofridas por quem usar o bot, use por sua própria conta e risco."
> > 
> > 
> > mas ninguém ta falando que ele precisa se pronunciar a respeito do "possível" ban ou se responsabilizar por algo! vcs precisam aprender a interpretar textos e seguir o tópico inteiro antes de responder qualquer coisa q vem na cabeça.. o "se pronunciar", se vc tivesse lido meia dúzia de palavras a mais, vc saberia que estamos falando sobre ser ainda estar "suave" usar o bot (como o primeiro colega postou nesse tópico}.
> 
> ?
> 
> Você literalmente postou um tópico que envolve uma conta supostamente suspensa para análise por uso do Script: "#430 (comment) <- por isso!"
> 
> O post do autor, embora seja ambíguo, denota totalmente que sua preocupação se a utlização dá ban ou não.
> 
> E a resposta foi mais endereçada para outro comentário, logo abaixo do criador, que chamou o autor do script. Notou o verbo "pronunciar" na minha resposta?
> 
> Muito ao contrário do que cita, você que precisa ser adulto ou responsável e tomar suas próprias decisões. O aviso já está no github.

qualquer pessoa com meio neurônio entende que, se ele respondeu "se pronunciar" em um comentário de

**Comment by noxfork** [comment]
> > > Ele não tem que se pronunciar e/ou se responsabilizar de nada... Cada um usa por sua conta e risco. Ele já deixou o aviso apropriado no github:
> > > "Aviso: Os desenvolvedores do jogo se pronunciaram e agora o uso de auto clickers e o uso de bots é oficialmente PROIBIDO. Não me responsabilizo por eventuais penalidades sofridas por quem usar o bot, use por sua própria conta e risco."
> > 
> > 
> > mas ninguém ta falando que ele precisa se pronunciar a respeito do "possível" ban ou se responsabilizar por algo! vcs precisam aprender a interpretar textos e seguir o tópico inteiro antes de responder qualquer coisa q vem na cabeça.. o "se pronunciar", se vc tivesse lido meia dúzia de palavras a mais, vc saberia que estamos falando sobre ser ainda estar "suave" usar o bot (como o primeiro colega postou nesse tópico}.
> 
> ?
> 
> Você literalmente postou um tópico que envolve uma conta supostamente suspensa para análise por uso do Script: "#430 (comment) <- por isso!"
> 
> O post do autor, embora seja ambíguo, denota totalmente que sua preocupação se a utlização dá ban ou não.
> 
> E a resposta foi mais endereçada para outro comentário, logo abaixo do criador, que chamou o autor do script. Notou o verbo "pronunciar" na minha resposta?
> 
> Muito ao contrário do que cita, você que precisa ser adulto ou responsável e tomar suas próprias decisões. O aviso já está no github.

Qualquer pessoa com meio neurônio entende que se ele respondeu "esperando ele se pronunciar" em um comentario "tá suave usar bot ainda ou n?". Se vc nao consegue ligar um ponto a outro, ai o problema é contigo, colega. E a respeito do q eu citei, sobre o outro topico do "possivel ban", foi justamente mostrando que estamos aguardando o pronunciamento de algum dos devs se algo mudou ou se continua safe usar o bot. Qualquer coisa avisa que eu desenho pra ti com o jogo dos pontinhos pra tu ligar tudo.

**Comment by rodrigobragamg** [comment]
É tão prepotente que quer falar pelo criador do Post, dando o sentido pelo qual ele criou o seu tópico.
Entrou no git 6 dias atrás, não contribui com nada. Tá explicado.  Não vale apena nem responder, não é possível que alguém seja tão ignorante assim, deve estar fazendo de propósito. Falha minha.

**Comment by noxfork** [comment]
> É tão prepotente que quer falar pelo criador do Post, dando o sentido pelo qual ele criou o seu tópico. Entrou no git 6 dias atrás, não contribui com nada. Tá explicado. Não vale apena nem responder, não é possível que alguém seja tão ignorante assim, deve estar fazendo de propósito. Falha minha.

Argumentum ad Hominem
Se vc não entendeu nem o sentido pelo qual o post foi criado, não cabe a mim continuar essa discussão 
Fica aqui um exercício pra vc aprender a interpretar um post igual gente grande.

![image](https://user-images.githubusercontent.com/96269513/147171967-a3208258-5696-4e3f-b71a-f6d80c5ddb25.png)
