### ISSUE TITLE
This Account is Under Review [N foi Ban, foi só um susto]

### ISSUE THREAD

**Issue by AllanHBC** [mpcabete/bombcrypto-bot#430]
Deixei rodando em uma conta que tinha 5 comuns como teste do que poderia acontecer. Tai o resultado:

![AnyDesk_XJYjbDN5ew](https://user-images.githubusercontent.com/34711129/147095987-d9830834-6009-4753-b9aa-eb9f8882d42f.png)

**Comment by Yumiizera** [comment]
Poderia enviar da tela toda do seu computador para ter a veracidade desta print.

**Comment by coradini1** [comment]
Explodi nos cara forjando print pra rapaziada n usar bot no joguin

**Comment by AllanHBC** [comment]
Brother, n tenho MOTIVO pra fazer um fake disso aeuheahu , se alguem quiser que eu adicione no discord e mostre ao vivo eu mostro, sem problema algum.

**Comment by AllanHBC** [comment]
Video no wetransfer, @Yumiizera  ... se quiser ver no discord, mostro.
Se qusierem que eu escreve alto num bloco de notas enquanto gravo, faço tbm. To postando pra AJUDAR e ninguem tomar ban no momento , só por isso .

https://we.tl/t-6lGabgtp3n

**Comment by AllanHBC** [comment]
> Explodi nos cara forjando print pra rapaziada n usar bot no joguin

o video acima ta bom ou quer uma call no discord?

**Comment by Reptile0** [comment]
Rodou por quanto tempo?

**Comment by coradini1** [comment]
Explodi dnv no cara se sentindo ofendido pq n acreditei em um maluco q nunca vi na vida

**Comment by trinitro2** [comment]
vi que um pessoal falou no suporte br sobre isso. gente que nao fez nada. fez saques normais

wallet 0x1efEE664F2cE2Bf1018674b636960fc38A77f3De

primeiro deu esse erro: https://media.discordapp.net/attachments/906283646443454474/923200539498516521/Screenshot_20211222-095515.png?width=252&height=560

depois deu o erro que o rapaz falou ai.

acho que é algum conflito de dados e o servidor poe a review. mais um bug que os devs fizeram que vai prejudicar muitas contas

**Comment by fx2016** [comment]
> Deixei rodando em uma conta que tinha 5 comuns como teste do que poderia acontecer. Tai o resultado:

Putz, deu ruim!!!

**Comment by AllanHBC** [comment]
@Reptile0  cara, da hora que voltou da att até perceber agora 5min antes da postagem 

@coradini1 n é questão de se ofender, mas o rolê aqui é a gente se ajudar, não é? Da pra pedir confirmação de conteúdo de N formas ao invés de partir do principio que já é troll/fake de alguém, @Yumiizera foi mto mais coerente no pedido. 

@trinitro2  espero que sejá só um bug mesmo, vamos aguardar. Qualquer update nessa conta minha eu aviso aqui.

**Comment by Yumiizera** [comment]
Sim, fui bem coerente no pedido da veracidade da print.

**Comment by Igorlegacy** [comment]
Tive isso com 2 contas, 1 já foi revisada pelo suporte e liberada... a outra ainda não tive resposta. 

Não sei o que levou, na conta que ainda não liberou, não usei o bot desde o update... talvez não tenha nada relacionado com o bot, só algo de conexão mesmo

**Comment by Yumiizera** [comment]
Parece que dar o Ctrl + F5 resolve este problema. A mensagem aparece porque o servidor aparenta está instável e/ou atualizar o jogo na página. 
OBS: Nada confirmado, apenas especulações do que eu fiz e de que amigos meus fizeram também.

**Comment by Mateuus** [comment]
@AllanHBC Você estava com o bot ligado no momento da manutenção ?

**Comment by AllanHBC** [comment]
@Yumiizera aqui o Ctrl F5 n resolveu.  Qualquer alteração eu aviso.

@Mateuus estava, mas oturas contas estavam tbm, desliguei assim que vi que tava tendo manutenção (tava dormindo acordei ja com server off) e deixei só nessa de 5bonecos qndo voltou.

**Comment by Yumiizera** [comment]
@AllanHBC Tente o Ctrl shift F5. Vê se vai reaparecer.

**Comment by fguide** [comment]
Discussões a parte, pode ser um review por login simultaneo, vc abriu ao mesmo tempo em dois lugares?

**Comment by akaneshi08** [comment]
i couple of player experiencing this one.. after they transfer bcoin to other account..
i think it has nothing to do with the bot.. my guess is the dev are trying to take precotionary measure.. if its hack account transfering assest

**Comment by joaovictor7** [comment]
galera eu acredito fielmente que esse erro não é um ban por conta da utilização do bot. to usando ele sem parar desde muito antes da att.
mas pra gente ter certeza, quem teve o erro da um retorno aqui se depois de um periodo a conta voltou ou não.

**Comment by AllanHBC** [comment]
@fguide  nops, só na vm mesmo.

@akaneshi08 thats possible. with thee ban wave with speed hacks and other things. If is that, Im 100% safe hehe

@joaovictor7 do @Igorlegacy voltou já. Aqui assim que alterar esse status pra qualquer coisa, aviso vocês :)

**Comment by Reptile0** [comment]
@AllanHBC Já tentou apagar o cache da pagina? É uma das soluções que eu utilizava para outros ocorridos.

**Comment by AllanHBC** [comment]
@Reptile0  tentei sim, apagar cache é meu padrão já hahaah

**Comment by fx2016** [comment]
> @AllanHBC Já tentou apagar o cache da pagina? É uma das soluções que eu utilizava para outros ocorridos.

Quando dá qualquer erro aqui, passo CCleaner, é um abraço!

**Comment by trinitro2** [comment]
> Aqui apareceu isso tmb, deixei rodando, acordei agora e tava isso!
> 
> edit ---
> 
> A minha que teve isso ja foi liberada estou jogando normal!

acordou com o erro e ja sumiu? usando bot?

**Comment by Adguimar** [comment]
> > Aqui apareceu isso tmb, deixei rodando, acordei agora e tava isso!
> > edit ---
> > A minha que teve isso ja foi liberada estou jogando normal!
> 
> acordou com o erro e ja sumiu? usando bot?

sim acordei tava o erro e o bot tinha parado, logo dei um ctrl +f5 e volto a funcionar... não voltei a usar o bot ainda!

**Comment by LRBarbieri** [comment]
> Deixei rodando em uma conta que tinha 5 comuns como teste do que poderia acontecer. Tai o resultado:
> 
> ![AnyDesk_XJYjbDN5ew](https://user-images.githubusercontent.com/34711129/147095987-d9830834-6009-4753-b9aa-eb9f8882d42f.png)

Uso o bot toda noite para ir dormir, e até agora nada dessa mensagem.

**Comment by backslash-f** [comment]
Mesma coisa aqui:

![Screen Shot 2021-12-22 at 16 48 22](https://user-images.githubusercontent.com/664951/147118907-acf6ef99-2c0d-4018-bda6-5bd7ac2d3cbd.png)

Cache limpo, tarará.

Acho que já era... Nota: eu não moro no Brasil, então não tem a ver com o país de origem.

**Comment by ricardofernandess** [comment]
No Discord oficial várias pessoas estão reportando isso e dizem que é uma mensagem temporária. Ao final da investigação você poderá acessar normalmente ou será banido, não tem previsão de quando será analisado mas será manual pelo que entendi. Mais informações olhar o Discord do Bomb.

Não dá pra saber se é por uso de bot ou qualquer outro motivo, naturalmente não vão divulgar essa informação.

**Comment by fx2016** [comment]
> No Discord oficial várias pessoas estão reportando isso e dizem que é uma mensagem temporária. Ao final da investigação você poderá acessar normalmente ou será banido, não tem previsão de quando será analisado mas será manual pelo que entendi. Mais informações olhar o Discord do Bomb.
> 
> Não dá pra saber se é por uso de bot ou qualquer outro motivo, naturalmente não vão divulgar essa informação.

Acredito que seja para tocar terror, meter medo nas pessoas.

**Comment by trinitro2** [comment]
falei que se fossem banir, iria um monte de gente que nao tem nada a ver com bot ou hack...

agora a gente investe num projeto e ficamos refem de como jogar o negocio. ban por speed hack e tal ok. agora vao falar que nao posso jogar de um jeito? jaja vao falar que nao pode cuidar mais de 1 cpf por conta

**Comment by MathBogo** [comment]
Usei o bot o dia inteiro, deu erro 1000 e caiu sobre under review agorinha.

**Comment by fx2016** [comment]
> Usei o bot o dia inteiro, deu erro 1000 e caiu sobre under review agorinha.

**PQP**

**Comment by Galinho90** [comment]
> Usei o bot o dia inteiro, deu erro 1000 e caiu sobre under review agorinha.

Provavel que estão monitorando os clicks, pq eu estou sem o bot, mas não me desloguei ainda do jogo e nem deu kick e pra mim não apareceu nada.

**Comment by Galinho90** [comment]
> Usei o bot o dia inteiro, deu erro 1000 e caiu sobre under review agorinha.

Após analise nos informe o que deu.

**Comment by nunes1987** [comment]
> > Usei o bot o dia inteiro, deu erro 1000 e caiu sobre under review agorinha.
> 
> Provavel que estão monitorando os clicks, pq eu estou sem o bot, mas não me desloguei ainda do jogo e nem deu kick e pra mim não apareceu nada.

Não estão monitorando o clique não, estão banindo varias pessoas aleatoriamente e espalhando o terror mesmo, tem gente que acabou de criar a conta e esta em verificação, sem contar os falso positivo.

**Comment by Galinho90** [comment]
> 



> > > Usei o bot o dia inteiro, deu erro 1000 e caiu sobre under review agorinha.
> > 
> > 
> > Provavel que estão monitorando os clicks, pq eu estou sem o bot, mas não me desloguei ainda do jogo e nem deu kick e pra mim não apareceu nada.
> 
> Não estão monitorando o clique não, estão banindo varias pessoas aleatoriamente e espalhando o terror mesmo, tem gente que acabou de criar a conta e esta em verificação, sem contar os falso positivo.

Ai ferrou né a credibilidade do jogo fica onde né? pq se a pessoa cria a conta e ja fica em analise, vao espalhar fud.,

**Comment by trinitro2** [comment]
> > 
> 
> > > > Usei o bot o dia inteiro, deu erro 1000 e caiu sobre under review agorinha.
> > > 
> > > 
> > > Provavel que estão monitorando os clicks, pq eu estou sem o bot, mas não me desloguei ainda do jogo e nem deu kick e pra mim não apareceu nada.
> > 
> > 
> > Não estão monitorando o clique não, estão banindo varias pessoas aleatoriamente e espalhando o terror mesmo, tem gente que acabou de criar a conta e esta em verificação, sem contar os falso positivo.
> 
> Ai ferrou né a credibilidade do jogo fica onde né? pq se a pessoa cria a conta e ja fica em analise, vao espalhar fud.,

tem gente que nem sacou o $ e ta com revisao de conta...
assim que abrir o mercado vo vender

**Comment by cmxavier** [comment]
![image](https://user-images.githubusercontent.com/24523474/147202352-2b2ead0a-7a1c-4eb4-9a23-6582dbae5d3c.png)

**Comment by backslash-f** [comment]
Consegui logar novamente com a conta acima. \o/

Tenho outra conta que está rodando o bot 24/7.

Então parece que agora está tudo ok mesmo.
Bah, vô metê até as bola pra dentro agora...

**Comment by snoopcrypto** [comment]
Quero por um boot pra roda rtbm

Em qui., 23 de dez. de 2021 07:30, Fernando Fernandes <
***@***.***> escreveu:

**Comment by MathBogo** [comment]
Minha conta voltou a funcionar.

**Comment by AllanHBC** [comment]
Bom dia!
Minha conta voltou ao normal depois dessa atualização que teve hoje,

**Comment by snoopcrypto** [comment]
Me ajuda no boot ??


Em qui., 23 de dez. de 2021 10:18, Prags ***@***.***>
escreveu:

**Comment by isoazevedo** [comment]
Tô com o mesmo problema this account is under review e só soltei os bonecos e sai quando voltei tava dando essa mensagem pra logar, tenho  uma conta não tem nem 15 dias ja tô bem chateado com isso.

**Comment by diegokai421** [comment]
comigo aconteceu a msm coisa hj, nunca tinha usado auto click, hj resolvi fazer isso e deu essa merda.
