### ISSUE TITLE
Arquivo TXT bagunçado

### ISSUE THREAD

**Issue by pegchargue** [mpcabete/bombcrypto-bot#433]
Alguém poderia me ajudar a arrumar isso, pois quero fazer algumas alterações, mas assim complica..
![bomb](https://user-images.githubusercontent.com/95758730/147114948-74494a41-d511-4aa8-a9e0-626b22cdc81f.png)
.

**Comment by grantyyy** [comment]
use notepad++

**Comment by pegchargue** [comment]
muito obrigado!!! Abriu correto!!!

**Comment by pegchargue** [comment]
Posso fechar ou deixo aberto por se mais alguém tem o mesmo problema???

**Comment by grantyyy** [comment]
> Posso fechar ou deixo aberto por se mais alguém tem o mesmo problema???

se foi resolvido, pode fechar.
