### ISSUE TITLE
Nova Vida dos Baús | New Life of Chests

### ISSUE THREAD

**Issue by Nucito** [mpcabete/bombcrypto-bot#434]
![image](https://user-images.githubusercontent.com/19374522/147118658-657d7762-fb58-4f1f-884a-6e4620bd7cb3.png)

**Português:**
 
Para quem pegou o ROI:

**Bau de Madeira:** 88
**Bau Roxo:** 187
**Bau Gold:** 880
**Bau Azul:** 1430
**Jaula:** 5500

Nota: Para quem não pegou os valores da vida vão ser os mesmo da ultima imagem😁Eu não sei se a jaula se encaixa na modificação dos novos valores de vida... se ela não mudou a vida vai continuar nos 5k😅 Eu tinha olhado essa informação no game ontem 8 hrs.

-------------------------------------------------------------------------------------------------------------------------------------------

**Inglês:**

For those who got the ROI:

**Wooden Chest:** 88
**Purple Bau:** 187
**Gold Bau:** 880
**Blue Bau:** 1430
**Jail:** 5500

For those who didn't get the values of life, they will be the same as in the last image😁I don't know if the cage fits the modification of the new life values... if it hasn't changed the life will continue at 5k😅 I had looked at this information in the game yesterday 8 hrs.

**Comment by lpstyle** [comment]
Como eles vao saber quem pegou ROI? bem estranho essa atualizacao.

**Comment by jpedrocguimaraes** [comment]
> Como eles vao saber quem pegou ROI? bem estranho essa atualizacao.

o jogo tá na blockchain, com certeza dá pra rastrear o que entrou e o que farmou pra tirar essa resposta.

**Comment by Nucito** [comment]
> Como eles vao saber quem pegou ROI? bem estranho essa atualizacao.

Isso é bem simples para fazer:

1 - pegue a quantidade de heróis que o carinha tem ->

[0x13f40874aae696ba6ee21657ff4fe4adf4d014db](https://bscscan.com/address/0x13f40874aae696ba6ee21657ff4fe4adf4d014db)

2 - Pegue o total de saques que o carinha fez ->

[claim.bombcrypto.io](https://claim.bombcrypto.io/claim-orders?&limit=10&offset=0&walletAddress=0x13f40874aae696ba6ee21657ff4fe4adf4d014db)

3 - Vamos fazer o uso da velha e boa matemática ->

**Herois:** 27
**Saque total:** 323.80
**Custo dos herois:** 270

Usando a matemática do de oxford: 323.80 - 270 => 53.8 BCOIN
ele no caso ja pegou o Roi e teve 53.8 BCOIN de lucro😁
