### ISSUE TITLE
Summary of error messages

### ISSUE THREAD

**Issue by khanghy3004** [mpcabete/bombcrypto-bot#435]
Source from dev ImkeiEn
[
![photo_2021-12-22_22-50-31](https://user-images.githubusercontent.com/17218425/147122296-580de32b-147f-45d2-8a05-5ad0c032a996.jpg)
](url)

**Comment by khanghy3004** [comment]
![image](https://user-images.githubusercontent.com/17218425/147122451-562336d2-de94-4c47-b28d-c2334dbe9024.png)

**Comment by khanghy3004** [comment]
Last update: There is still no official information on banning and locking accounts using bots/auto click.
Thanks.

> ![image](https://user-images.githubusercontent.com/17218425/147122451-562336d2-de94-4c47-b28d-c2334dbe9024.png)
> 
> Translate: For someone who will need it :) Just play normally like I haven't encountered any notifications since then. The message only appears when the user intentionally cheats or encounters a log in error. So whoever reports when they receive these notifications again should take a look at me :)

**Comment by fguide** [comment]
Thank you very much for the report mate.

**Comment by Galinho90** [comment]
![44A808A1-B2C7-4F81-A3A1-526A952C44E0](https://user-images.githubusercontent.com/95733162/147156952-0fa8d5d6-6a82-4d4a-93fd-80bc5591f6a5.jpeg)

**Comment by worst-coder** [comment]
Have you guys had any problems (bans, errors, messages) using the bot ?
