### ISSUE TITLE
Windows Server 2012

### ISSUE THREAD

**Issue by Igorlegacy** [mpcabete/bombcrypto-bot#436]
Alguém já testou utilizar direto no windows server com multisessões no RDP? para reduzir consumo de maquina virtual na utilização de múltiplas contas com o bot

**Comment by fguide** [comment]
Em relação a performance: infelizmente não tem muito o que fazer, o jogo em si é "pesado", mesmo utilizando navegadores mais "leves" e sem aceleracao 3d, ainda vai consumir muitos recursos.

Quanto a multisessão RDP, eu nao testei mas talvez funcione, a questão é que você precisa manter todas as sessões ativas, o Windows faz lock da sessão quando o RDP é fechado, para contornar o problema use o seguinte comando em um batch, ele manda as sessões para o console e desconecta o RDP:

```
for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
  %windir%\System32\tscon.exe %%s /dest:console
)
```

Se nao funcionar com RDP, você pode usar o VNC com várias instancias, essa forma eu sei que funciona em sistemas nao windows e nao vejo motivos para nao funcionar no windows tb.

**Comment by Igorlegacy** [comment]
> Em relação a performance: infelizmente não tem muito o que fazer, o jogo em si é "pesado", mesmo utilizando navegadores mais "leves" e sem aceleracao 3d, ainda vai consumir muitos recursos.
> 
> Quanto a multisessão RDP, eu nao testei mas talvez funcione, a questão é que você precisa manter todas as sessões ativas, o Windows faz lock da sessão quando o RDP é fechado, para contornar o problema use o seguinte comando em um batch, ele manda as sessões para o console e desconecta o RDP:
> 
> ```
> for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
>   %windir%\System32\tscon.exe %%s /dest:console
> )
> ```
> 
> Se nao funcionar com RDP, você pode usar o VNC com várias instancias, essa forma eu sei que funciona em sistemas nao windows e nao vejo motivos para nao funcionar no windows tb.

Na verdade, com o windows server a multi sessão, não dá lock após desconexão.. seria uma das vantagem quem permanece ativo...

O que tenho duvida é no funcionamento do python com o server 2012, se todos os componentes são compatíveis e tudo mais

**Comment by fguide** [comment]
> Na verdade, com o windows server a multi sessão, não dá lock após desconexão.. seria uma das vantagem quem permanece ativo...

Pelo que eu lembrava do server sempre que se desconecta uma sessão ele fazia o lock da sessão, mas faz tempo que não trabalho ativamente com windows, talvez esteja enganado. Mas mesmo se for o casso, o batch acima resolve seu problema, já testei com outras aplicações que fazem algo similar ao bot.

Quanto a compatibilidade sim, o python e os requirements funcionam bem em windows server, já foi testado aqui por várias pessoas.

> O que tenho duvida é no funcionamento do python com o server 2012, se todos os componentes são compatíveis e tudo mais

**Comment by jhonsstn** [comment]
O problema nessas maquinas virtuais em cloud geralmente e a falta de GPU. Se vc botar GPU nelas pra tentar melhorar desempenho o custo e enorme kkkkkkk

**Comment by Igorlegacy** [comment]
> 

No meu caso nem é pelo cloud, mais pelo multisessão usando 1VM... dá para abrir 3 sessões por VM (4GB/4 núcleo/256memoria de vídeo)

No meu PC consigo abrir 3 dessas maquinas virtuais, que daria 9 contas simultânea com o bot... 

Fiz uma alteração no bot para revezar entre 2 contas por sessão... resumindo, consigo rodar até 19 contas simultâneas kkkkk ainda só utilizo 10 contas, mas em breve vou precisar expandir

**Comment by fguide** [comment]
E esse setup de 3 sessoes por vm com essa config é prático? 
Windows é uma draga para recursos, mas com o tanto de vcpus que vc tem disponivel, uma instalação com linux e sessoes VNC daria pra ao menos 12, contando que seria 1 vcpu por sessao vnc.

Talvez seja bom fazer o teste

**Comment by Igorlegacy** [comment]
Ahh depois de configurado, não dá tanto trabalho... mas se linux for melhor opção, vou tentar

Comecei pelo windows server por ter mais facilidade com o windows, linux nunca havia tentado para essa finalidade

**Comment by chrisjardim** [comment]
> > Na verdade, com o windows server a multi sessão, não dá lock após desconexão.. seria uma das vantagem quem permanece ativo...
> 
> Pelo que eu lembrava do server sempre que se desconecta uma sessão ele fazia o lock da sessão, mas faz tempo que não trabalho ativamente com windows, talvez esteja enganado. Mas mesmo se for o casso, o batch acima resolve seu problema, já testei com outras aplicações que fazem algo similar ao bot.
> 
> Quanto a compatibilidade sim, o python e os requirements funcionam bem em windows server, já foi testado aqui por várias pessoas.
> 
> > O que tenho duvida é no funcionamento do python com o server 2012, se todos os componentes são compatíveis e tudo mais

Eu montei uma server 2012 R2 e nao ta funcionando nem por jesus cristo esta dando erro na linha 2 no import... sabe como resolver? ja instalei o anaconda3

**Comment by fguide** [comment]
> > > Na verdade, com o windows server a multi sessão, não dá lock após desconexão.. seria uma das vantagem quem permanece ativo...
> > 
> > 
> > Pelo que eu lembrava do server sempre que se desconecta uma sessão ele fazia o lock da sessão, mas faz tempo que não trabalho ativamente com windows, talvez esteja enganado. Mas mesmo se for o casso, o batch acima resolve seu problema, já testei com outras aplicações que fazem algo similar ao bot.
> > Quanto a compatibilidade sim, o python e os requirements funcionam bem em windows server, já foi testado aqui por várias pessoas.
> > > O que tenho duvida é no funcionamento do python com o server 2012, se todos os componentes são compatíveis e tudo mais
> 
> Eu montei uma server 2012 R2 e nao ta funcionando nem por jesus cristo esta dando erro na linha 2 no import... sabe como resolver? ja instalei o anaconda3

erro no import do cv2? eu ajudei em uns topicos e era por atualizacao do windows 10, no server nao sei se é o mesmo caso, tem algumas sugestões em #389 



> Ahh depois de configurado, não dá tanto trabalho... mas se linux for melhor opção, vou tentar
> 
> Comecei pelo windows server por ter mais facilidade com o windows, linux nunca havia tentado para essa finalidade

É, nao tem erro, instale um linux com os pacotes minimos, gerenciador de janelas de preferencia (sem iniciar automaticamente), python e vnc e já é suficiente.

**Comment by edsonalanis** [comment]
Estou com este erro  o Windows Server 12


Traceback (most recent call last):
  File "c:\bomb\index.py", line 2, in <module>
    from cv2 import cv2
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python310\lib\site-
packages\cv2init.py", line 8, in <module>
    from .cv2 import *
ImportError: DLL load failed while importing cv2: Não foi possível encontrar o m
ódulo especificado.

**Comment by rafaelsalum** [comment]
Para solucionar este problema no Windows Server 2012, siga o passo a passo abaixo, o meu está no idioma inglês, então:

1. Turn windows features on or off
2. Skip the roles screen and directly go to Feature screen
3. Select “Desktop Experience” under “User Interfaces and Infrastructure”

Após habilitar o Desktop Experience será necessário reiniciar o Windows Server.
