### ISSUE TITLE
Retirada do capctha do Cod e detectação do bot esta save ainda?

### ISSUE THREAD

**Issue by careduest** [mpcabete/bombcrypto-bot#437]
Alguem ja esta providenciando essas duas coisa?

**Comment by fguide** [comment]
Já tem tópicos fixos aqui sobre a segurança atual do bot.

Quanto a remoção do captcha, por enquanto nao é necessária, ele simplesmente não vai achar o captcha e vai pular para a próxima ação.

**Comment by Nucito** [comment]
> Alguem ja esta providenciando essas duas coisa?

Peço para que de abrir um novo issue olhe os fixados😁
