### ISSUE TITLE
Colocar para trabalhar com mínimo 50% carregado

### ISSUE THREAD

**Issue by deividlm** [mpcabete/bombcrypto-bot#438]
Olá, existe alguma configuração ( arquivo texto ou nova imagem) que o bot só coloque pra trabalhar depois de carregar pelo menos 50% (um exemplo) . Isso faria alguma diferença em relação ao total de farm? Obrigado desde já

**Comment by fguide** [comment]
> Isso faria alguma diferença em relação ao total de farm?

Dificil saber, depende dos seus herois, stamina, tempo de recarga, etc.

> Olá, existe alguma configuração ( arquivo texto ou nova imagem) que o bot só coloque pra trabalhar depois de carregar pelo menos 50% (um exemplo) .

Você pode pegar o arquivo de imagens "green" por exemplo e substituir por um tamanho maior, que represente a % que você quer.

**Comment by deividlm** [comment]
@fguide obrigado pela resposta, eu até tentei colocar outra imagem mas deu erro, então imaginei que tivesse outra configuração

**Comment by fguide** [comment]
Deu algum erro de fato ou só nao funcionou como voce esperava?

**Comment by Hermanyo** [comment]
> > Isso faria alguma diferença em relação ao total de farm?
> 
> Dificil saber, depende dos seus herois, stamina, tempo de recarga, etc.
> 
> > Olá, existe alguma configuração ( arquivo texto ou nova imagem) que o bot só coloque pra trabalhar depois de carregar pelo menos 50% (um exemplo) .
> 
> Você pode pegar o arquivo de imagens "green" por exemplo e substituir por um tamanho maior, que represente a % que você quer.

Substituir a imagem não é uma opção, uma vez que se tive 51% já não funcionária mais.

**Comment by Hermanyo** [comment]
Se você quiser implementar essa funcionalidade, tire print do ROI e então use OCR para pegar o número para que então você consiga manipular.

**Comment by deividlm** [comment]
@Hermanyo Entendi

@fguide 
 File "C:\bomb\index.py", line 524, in <module>
    main()
  File "C:\bomb\index.py", line 496, in main
    refreshHeroes()
  File "C:\bomb\index.py", line 461, in refreshHeroes
    buttonsClicked = clickGreenBarButtons()
  File "C:\bomb\index.py", line 272, in clickGreenBarButtons
    green_bars = positions(images['green-bar'], threshold=ct['green_bar'])
KeyError: 'green-bar'

**Comment by fguide** [comment]
> > > Isso faria alguma diferença em relação ao total de farm?
> > 
> > 
> > Dificil saber, depende dos seus herois, stamina, tempo de recarga, etc.
> > > Olá, existe alguma configuração ( arquivo texto ou nova imagem) que o bot só coloque pra trabalhar depois de carregar pelo menos 50% (um exemplo) .
> > 
> > 
> > Você pode pegar o arquivo de imagens "green" por exemplo e substituir por um tamanho maior, que represente a % que você quer.
> 
> Substituir a imagem não é uma opção, uma vez que se tive 51% já não funcionária mais.

Não tenho certeza, mas acredito que funcionaria uma vez que mesmo com a configuração em "green" ele clica em herois de barra cheia, na verdade acho que a barra maior atrasaria mais para o clique, não?

@deividlm 
pelo erro ele não esta encontrando o arquivo green-bar.png, ele está na pasta targets?

**Comment by deividlm** [comment]
@fguide tá sim, fiz uma nova imagem PNG

**Comment by Hermanyo** [comment]
> > > > Isso faria alguma diferença em relação ao total de farm?
> > > 
> > > 
> > > Dificil saber, depende dos seus herois, stamina, tempo de recarga, etc.
> > > > Olá, existe alguma configuração ( arquivo texto ou nova imagem) que o bot só coloque pra trabalhar depois de carregar pelo menos 50% (um exemplo) .
> > > 
> > > 
> > > Você pode pegar o arquivo de imagens "green" por exemplo e substituir por um tamanho maior, que represente a % que você quer.
> > 
> > 
> > Substituir a imagem não é uma opção, uma vez que se tive 51% já não funcionária mais.
> 
> Não tenho certeza, mas acredito que funcionaria uma vez que mesmo com a configuração em "green" ele clica em herois de barra cheia, na verdade acho que a barra maior atrasaria mais para o clique, não?
> 
> @deividlm pelo erro ele não esta encontrando o arquivo green-bar.png, ele está na pasta targets?

Não, ele clica na barra cheia porque ele pega o primeiro pedaço dela. 

No caso do 51 ele não encontraria o número. Você precisaria usar ocr para ler o número da imagem.

**Comment by fguide** [comment]
> @fguide tá sim, fiz uma nova imagem PNG

Estranho hein, sera que nao salvou com outro formato ao invés de PNG?

digita dir -a targets\ na pasta do bot e veja se esta certo

**Comment by deividlm** [comment]
@fguide a extensão da imagem que eu fiz tava maiúsculo, não deu mais erro, vou ver agora se faz diferença o tamanho da barra

**Comment by fguide** [comment]
Boa, avise aqui se deu certo!

**Comment by deividlm** [comment]
@fguide não fez diferença, assim que fica ver ele já coloca pra trabalhar.

**Comment by fguide** [comment]
Obrigado pelo retorno, então acredito que a sugestão do OCR seria mais viável para o seu caso.
