### ISSUE TITLE
Touch Screen, new update ?

### ISSUE THREAD

**Issue by MathBogo** [mpcabete/bombcrypto-bot#439]
Vocês acham que seriam possível colocar uma atualização que o bot se baseia em touch? Como se estivéssemos mexendo via controle remoto para acessar o pc. Talvez isso resolveria o monitoramento de mouse? Seria muito complexo implementar isso na situação atual do bot?

**Comment by Nucito** [comment]
Não existe monitoramento de mouse, leia os issues fixados...
