### ISSUE TITLE
AutoClick / Macro autorizados (Debate sobre ultimo comunicado)

### ISSUE THREAD

**Issue by Samuel-Oliveira** [mpcabete/bombcrypto-bot#441]
Teve esse pronunciamento: 
![image](https://user-images.githubusercontent.com/22372310/147186039-27253f89-1af0-40c9-80d5-7b51d0643ca5.png)

Ai não cita AutoClick e Macros, e gerou uma grande discussão na comunidade.
A remoção do Captcha + Esse anuncio pode indicar que eles entendem que um Autoclick não é prejudicial ao jogo/comunidade?

Sei que é questão de interpretação, mas está ai pra discutirmos.

**Comment by Galinho90** [comment]
> ![image](https://user-images.githubusercontent.com/22372310/147186039-27253f89-1af0-40c9-80d5-7b51d0643ca5.png)

Interpretação de texto, pois fala sofware para 'INTERFERIR" ALTERAR OU FALSIFICAR, então neste caso bot que é autoclik não pode ser considerado, Podde notar que eles não falam abertamente ferramentas de MACRO.

**Comment by mfsousa** [comment]
<img width="717" alt="Screen Shot 2021-12-23 at 04 49 21" src="https://user-images.githubusercontent.com/1350652/147189618-5edc22ce-e652-469d-aaeb-9b02db855c1c.png">

Isso foi o que foi dito por um dos MODs no Discord.

**Comment by jhonsstn** [comment]
![image](https://user-images.githubusercontent.com/33515228/147195583-8c2410ae-b7d2-4c3d-bc0c-0895a9360ac1.png)

Mais uma aqui só pra deixar registrado.

**Comment by hugooandradec** [comment]
Ótimo, não aguento mais acordar de 2h em 2h 😂😂

**Comment by Lemocas** [comment]
alguém poderia me ajudar ?? na instalação do bot , sempre ocorreu tudo bem, agora estou tendo um erro que faz a interrupção  da execuçao do mesmo, 


Fatal error in launcher: Unable to create process using '"C:\Program Files\Python310\python.exe"  "C:\Program Files\Python310\Scripts\pip.exe" install -r requirements.txt': O sistema nÒo pode encontrar o arquivo especificado.

alguem para me salvar? como resolvo?

**Comment by lucasvieceli** [comment]
> <img alt="Screen Shot 2021-12-23 at 04 49 21" width="717" src="https://user-images.githubusercontent.com/1350652/147189618-5edc22ce-e652-469d-aaeb-9b02db855c1c.png">
> 
> Isso foi o que foi dito por um dos MODs no Discord.

não achei essa mensagem no discord

**Comment by mfsousa** [comment]
> > <img alt="Screen Shot 2021-12-23 at 04 49 21" width="717" src="https://user-images.githubusercontent.com/1350652/147189618-5edc22ce-e652-469d-aaeb-9b02db855c1c.png">
> > Isso foi o que foi dito por um dos MODs no Discord.
> 
> não achei essa mensagem no discord

Veja nos fixados no chat portugues la do discord que vai encontrar

**Comment by lucasvieceli** [comment]
> > > <img alt="Screen Shot 2021-12-23 at 04 49 21" width="717" src="https://user-images.githubusercontent.com/1350652/147189618-5edc22ce-e652-469d-aaeb-9b02db855c1c.png">
> > > Isso foi o que foi dito por um dos MODs no Discord.
> > 
> > 
> > não achei essa mensagem no discord
> 
> Veja nos fixados no chat portugues la do discord que vai encontrar

acredito que ele apagou entao

**Comment by jhonsstn** [comment]
> acredito que ele apagou entao
> 
> ![image](https://user-images.githubusercontent.com/1795678/147242633-84cbe7da-0bed-4aae-ae63-13a5286951a1.png)

Continua la.

![image](https://user-images.githubusercontent.com/33515228/147243329-d0ef146c-b1e5-494c-989d-5cf637149475.png)

**Comment by R3pl1cant3** [comment]
Ao meu ver, eles só ajustaram o discurso, porque não conseguem identificar quem usa bot.  Além disso, se forem fazer as contas, podem perder clientes (como eu) para outros jogos, que não precisam jogar de hora em hora.
