### ISSUE TITLE
Atualizacao sobre Bots/Macros

### ISSUE THREAD

**Issue by luizfhb** [mpcabete/bombcrypto-bot#442]
AUTOCLICKERS, BOTS E MACROS

De acordo com o último anúncio, nós não iremos proibir autoclickers nesse momento. Se você utilizar, você não será banido por isso.
Porém, golpistas tentarão vender programas que conseguirão vazar a senha de sua Metamask. Também, se sua automação obstruir a operação ou tentar obter acesso não autorizado do servidor do Bombcrypto; tirar vantagens de falhas de segurança/erros do jogo ou utilizar ferramentas de hack/cheat para adulterar a integridade do mesmo, sua conta será banida.

Recado pessoal: Muito cuidado com a automação que você adquire. Como dito anteriormente, muitos programas roubam sua conta Metamask, podendo te levar ao prejuízo total.

Postado por um moderador no discord, estamos tranquilos !

**Comment by Galinho90** [comment]
> AUTOCLICKERS, BOTS E MACROS
> 
> De acordo com o último anúncio, nós não iremos proibir autoclickers nesse momento. Se você utilizar, você não será banido por isso. Porém, golpistas tentarão vender programas que conseguirão vazar a senha de sua Metamask. Também, se sua automação obstruir a operação ou tentar obter acesso não autorizado do servidor do Bombcrypto; tirar vantagens de falhas de segurança/erros do jogo ou utilizar ferramentas de hack/cheat para adulterar a integridade do mesmo, sua conta será banida.
> 
> Recado pessoal: Muito cuidado com a automação que você adquire. Como dito anteriormente, muitos programas roubam sua conta Metamask, podendo te levar ao prejuízo total.
> 
> Postado por um moderador no discord, estamos tranquilos !

Sempre faça suas concluções, até porque veio a info atraves de um HELPER e não um DEV.

**Comment by ArthurF-S** [comment]
> > AUTOCLICKERS, BOTS E MACROS
> > De acordo com o último anúncio, nós não iremos proibir autoclickers nesse momento. Se você utilizar, você não será banido por isso. Porém, golpistas tentarão vender programas que conseguirão vazar a senha de sua Metamask. Também, se sua automação obstruir a operação ou tentar obter acesso não autorizado do servidor do Bombcrypto; tirar vantagens de falhas de segurança/erros do jogo ou utilizar ferramentas de hack/cheat para adulterar a integridade do mesmo, sua conta será banida.
> > Recado pessoal: Muito cuidado com a automação que você adquire. Como dito anteriormente, muitos programas roubam sua conta Metamask, podendo te levar ao prejuízo total.
> > Postado por um moderador no discord, estamos tranquilos !
> 
> Sempre faça suas concluções, até porque veio a info atraves de um HELPER e não um DEV.

Se n me engano a mensagem de cima é dos devs e o RECADO PESSOAL é a opiniao do helper

**Comment by llFerreira** [comment]
> > AUTOCLICKERS, BOTS E MACROS
> > De acordo com o último anúncio, nós não iremos proibir autoclickers nesse momento. Se você utilizar, você não será banido por isso. Porém, golpistas tentarão vender programas que conseguirão vazar a senha de sua Metamask. Também, se sua automação obstruir a operação ou tentar obter acesso não autorizado do servidor do Bombcrypto; tirar vantagens de falhas de segurança/erros do jogo ou utilizar ferramentas de hack/cheat para adulterar a integridade do mesmo, sua conta será banida.
> > Recado pessoal: Muito cuidado com a automação que você adquire. Como dito anteriormente, muitos programas roubam sua conta Metamask, podendo te levar ao prejuízo total.
> > Postado por um moderador no discord, estamos tranquilos !
> 
> Sempre faça suas concluções, até porque veio a info atraves de um HELPER e não um DEV.

A mensagem foi de um DEV e o Helper apenas traduziu.
