### ISSUE TITLE
 novo erro ao aplicar  '' pip.exe" install -r requisitos.txt ''  Fatal error in launcher: Unable to create process using ( AJUDA ) 

### ISSUE THREAD

**Issue by Lemocas** [mpcabete/bombcrypto-bot#443]
alguem poderia me ajudar ?? na instalação do bot, sempre ocorreu tudo bem, agora estou tendo um erro que faz uma interrupção da execução do mesmo,

Erro fatal no inicializador: Não foi possível criar o processo usando '"C: \ Arquivos de programas \ Python310 \ python.exe" "C: \ Arquivos de programas \ Python310 \ Scripts \ pip.exe" install -r requisitos.txt': O sistema nÒo pode encontrar o arquivo especificado.

alguem para me salvar? como resolvo?

**Comment by fx2016** [comment]
_"pip install -r requirements.txt"_

Se não funcionar, desinstala tudo e começa do zero

**Comment by fguide** [comment]
Pelo erro o python nao está instalado, ou não está adicionado ao PATH do windows, refaça a instalação com a opção Add to PATH.

Faza um teste no CMD com esses comandos e mande o resultado:
python -V
python3 -V

pip -V
pip3 -V

**Comment by Lemocas** [comment]
como assim, adicionar caminho? sou bem leigo na programaçao do python

**Comment by Lemocas** [comment]
![image](https://user-images.githubusercontent.com/96564162/147244167-da9e3743-77ba-4d01-9fee-3ce068afdb4b.png)
