### ISSUE TITLE
[DÚVIDA] Confiabilidade do projeto

### ISSUE THREAD

**Issue by ArthurF-S** [mpcabete/bombcrypto-bot#444]
Gente sou leio nessa coisa entao estou com uma duvida que acredito que seja bem boba na vdd. Soube desse projeto pelo youtube e acabei comentado com algumas pessoas no Discord e uma pessoa disse que nao confiava muito por conta de uma API no codigo.

Voces poderiam por favor me dizer o que essa API faz e porque eu deveria acreditar nesse projeto, por mais que seja open source?

**Comment by Kaeotik** [comment]
Não sei do que essa pessoa está falando. 

Esse bot é 100% open source e várias pessoas já ajudaram esse projeto, inclusive fazendo várias forks etc.
Se houvesse algo malicioso nele, isso já teria sido descoberto. 

Chame um amigo que manja um pouco de python e peça pra ele dar uma olhada. Ou peça pra esses comentaristas de discord te mostrar aonde está esse problema e poste aqui.

**Comment by fguide** [comment]
Essa API já esteve há um tempo no script, não fazia nada de mal, era uma API do plausible, uma especie de google adsense, o maximo que fazia era contar as utilizações e adicionar views pro criador do projeto.

Já está removida, pode pedir à sua fonte de consulta que veja o código novamente e valide as alteraçoes.

**Comment by ArthurF-S** [comment]
Vlw man, realmente me deu uma nova visao ao projeto

**Comment by Nucito** [comment]
A parte mais engraçada é q o código esta literalmente ABERTO e sem nenhuma OBFUSCAÇÂO é mesmo assim o pessoal ainda esta inventando historias kkkkkk...
