### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by DDC19** [mpcabete/bombcrypto-bot#445]
![SharedScreenshot](https://user-images.githubusercontent.com/96269406/147234372-97e30198-c07b-4e21-8f5f-92ef8b095180.jpg)

**Comment by DDC19** [comment]
Meu bot começou a esse erro ontem ao executar

**Comment by fguide** [comment]
Voce nao esta na pasta do bot, precisa ser nela.

**Comment by Nucito** [comment]
> ![SharedScreenshot](https://user-images.githubusercontent.com/96269406/147234372-97e30198-c07b-4e21-8f5f-92ef8b095180.jpg)

Vc abrindo na pasta do system32 fica meio difícil de achar o arquivo kkkkkk
