### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by manassesagur** [mpcabete/bombcrypto-bot#446]
''Traceback (most recent call last):
  File "index.py", line 1, in <module>
    from cv2 import cv2
ModuleNotFoundError: No module named 'cv2'''

**Comment by fguide** [comment]
você instalou os requirements.txt ?

**Comment by Nucito** [comment]
1 - Abra o cmd dentro da pasta do bot
2 - digite: pip install -r requirements.txt
3 - Rode o bot e seja feliz.
