### ISSUE TITLE
Ajuda por favor ( Fatal error in launcher: Unable to create process using '"C:\Program Files\Python310\python.exe"  "C:\Program Files\Python310\Scripts\pip.exe" install -r requisitos.tx': O sistema nÒo pode encontrar o arquivo especificado.)

### ISSUE THREAD

**Issue by Lemocas** [mpcabete/bombcrypto-bot#447]
nao entendo muito bem, mas agora só da este tipo de erro

**Comment by hugooandradec** [comment]
coloca o print da tela do CMD aqui, mas me parece que tu ta tentando instalar os requirements sem estar na pasta do arquivo

**Comment by Lemocas** [comment]
![image](https://user-images.githubusercontent.com/96564162/147243270-521d7d46-f2da-4f09-9074-fd0324d73035.png)

**Comment by Lemocas** [comment]
fica desse jeito

**Comment by hugooandradec** [comment]
> ![image](https://user-images.githubusercontent.com/96564162/147243270-521d7d46-f2da-4f09-9074-fd0324d73035.png)

É algum erro no Python, pode ter sido quando foi instalar. Sugiro que desinstale o Python e instale tudo novamente.

**Comment by fguide** [comment]
Pelo erro parece que o python está instalado mas não encontra o pip, no caso ou precisa refazer a instalação do python marcando a opção abaixo:
![image](https://user-images.githubusercontent.com/95459411/147250479-d4b1b8ac-9f41-4832-b8a1-c312a41737b1.png)

Ou fazer a instalação do pip:
Baixe o arquivo de instalação em: https://bootstrap.pypa.io/get-pip.py
digite python get-pip.py no caminho onde voce salvou.
