### ISSUE TITLE
Personagens vagando quando resta apenas 1 baú

### ISSUE THREAD

**Issue by deividlm** [mpcabete/bombcrypto-bot#448]
Olá, eu notei uma coisa, o bot coloca pra trabalhar sempre que a barra ta verde, porém no caso de restar apenas um baú azul , por exemplo,e precisar no máximo 2 pra quebrar por conta de espaço, o bot tira os outros do rest e diminui a recarga, alguém já parou pra pensar sobre isso?

**Comment by Nucito** [comment]
> Olá, eu notei uma coisa, o bot coloca pra trabalhar sempre que a barra ta verde, porém no caso de restar apenas um baú azul , por exemplo,e precisar no máximo 2 pra quebrar por conta de espaço, o bot tira os outros do rest e diminui a recarga, alguém já parou pra pensar sobre isso?

Parar para pensar, Sim.
Mas para corrigir pode fazer um pull request com alguma solução😁

**Comment by deividlm** [comment]
@Nucito rsrsr, bem que eu queria, mas infelizmente não programo em python, 10 anos de JAVA.

**Comment by Nucito** [comment]
@deividlm Ultimamente o projeto anda bem parado... os devs ficaram indecisos em relação aos bots kkkkkkk

**Comment by Nucito** [comment]
> @Nucito rsrsr, bem que eu queria, mas infelizmente não programo em python, 10 anos de JAVA.

Rapaz... 10 anos de java '-' me espanta vc ainda ter neurônios kkkkkkk mas força de vontade vc tem de sobra ne 😁

**Comment by deividlm** [comment]
hahaha, é verdade mas tem evoluído bem JAVA, tipo dentro dos projetos que trabalho vai bem. É de Fortaleza também? trabalha remoto?

**Comment by Nucito** [comment]
> hahaha, é verdade mas tem evoluído bem JAVA, tipo dentro dos projetos que trabalho vai bem. É de Fortaleza também? trabalha remoto?

Nunca tive nenhum trabalho contratado de verdade kkkkkk
