### ISSUE TITLE
ERRO DE NÃO ENCONTRAR O PYTHON 

### ISSUE THREAD

**Issue by lifarrx** [mpcabete/bombcrypto-bot#449]
![pythonerror](https://user-images.githubusercontent.com/95596140/147245917-f946dedb-774a-45a9-836e-8f1cd0b1b487.png)

Mais alguém com esse erro ?

Já testei com a versão 3,9,9 do python e da no mesmo.

**Comment by hugooandradec** [comment]
tira esse "3" do comando "python index.py

**Comment by lifarrx** [comment]
Se for isso eu vou me jogar do 9 andar aqui do meu prédio... que ódio, agora que vi..

**Comment by hugooandradec** [comment]
kkkkkkkkkkkkkkk acontece

**Comment by lifarrx** [comment]
Resolvido mano obrigado.
