### ISSUE TITLE
Mandando Heroi errado para Home

### ISSUE THREAD

**Issue by KgoBomb** [mpcabete/bombcrypto-bot#45]
Olá!

Obrigado pelo ótimo trabalho!! Esta funcionando quase tudo perfeito!!

só tem um ponto que estou sofrendo um pouco. Ao mandar os herois pra Homee (dos que subi a imagem), ele sempre erra um e coloca outro no lugar mesmo sendo bem diferentes (um é um sapo super raro e o outro um cachorro comum). 

o que posso fazer pra resolver?

**Comment by eztzez** [comment]
Ola!
eu também quase tudo funciona perfeitamente !!
Eu só quero que a atualização do código envie os heróis para Homee.
Eu vou te pagar é claro, basta entrar em contato comigo
Whatssap: 00212666195500
