### ISSUE TITLE
Alguma dica de VPS para rodar?

### ISSUE THREAD

**Issue by far0fa** [mpcabete/bombcrypto-bot#450]
Boa tarde, tenho 4 contas no bombcrypto, recentemente adquiri uma VPS na HeavyHost mas parece q não roda mto bem, ela é uma 4CPU/4GB de RAM e parece que o bot buga sempre.

Queria rodar as 4 contas numa VPS só mas sei q isso nao eh possivel então estou disposto a comprar 4 VPS separadas para rodar visto que vou viajar e queria deixar os bonecu farmando!

Alguem tem alguma recomendação de VPS boa?

**Comment by far0fa** [comment]
Eu tenho uma VPS só que buga muito, ela nao roda direito, o mouse nao clica as vezes, da anti-idle sempre. Não sei se eh alguma configuração da VPS ou por ser windows server.

**Comment by fguide** [comment]
Como vc acessa o windows server? via remote desktop? talvez quando vc faça a desconexao o windows server fique na tela de bloqueio e por isso o erro.

**Comment by far0fa** [comment]
> 

Sim, mas eu deixei aberto também minimizado mas deu erro do msm jeito. Pedi para o host formatar e colocar windows 10, vou testar e posto aqui se funcionou.

Não sou programador então eu nao entendo nada de docker por isso optei pelas VPS, tem alguma recomendação de host bom que funcione?

**Comment by EricOFreitas** [comment]
Eu mesmo crio vps num servidor que tenho aqui na empresa e tem dado bom, mas faço o acesso tudo pelo anydesk mesmo.

**Comment by fguide** [comment]
Sinceramente não faz muita diferença o provedor desde que esteja tudo configurado certinho, ai vai da que for melhor pra vc em relacao a facilidade, custo, etc.

Com 4vpcu/4gb ram e 1 navegador aberto deve rodar bem em qualquer sistema operacional.

**Comment by EricOFreitas** [comment]
O problema é que a maioria das vps que tem preço baixo compartilham os recursos acima do ideal. Diz lá que tem 4gb de memória, mas qndo tu vai usar essa qtde o gargalo bate em horários de picos. 
Sobre o SO também acho que não faria diferença entre server ou win 7, mas eu não consegui instalar os requisitos no win server que tenho aqui.

**Comment by far0fa** [comment]
Então, engraçado que fica dando anti-idle como se o mouse nao funcionasse corretamente. ;(

**Comment by fguide** [comment]
E quando você acessa você vê o mouse fazendo o movimento? Experimente colocar o comando abaixo num arquivo .bat e rode para testar, ele vai desconectar o RDP e manter a sessao aberta em console, talvez resolva o problema com o controle do mouse:

```
for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
  %windir%\System32\tscon.exe %%s /dest:console
)
```

Outra coisa é fazer acesso remoto por outro software, por exemplo anydesk como disseram acima.

**Comment by far0fa** [comment]
Quando eu acesso eu vejo o mouse, porém tem vez que ele clica em WORK e não funciona, eu mandei formatar a maquina e colcoar windows 10 pro, pra ver se muda algo e trago os updates aqui pra vc, assim q formatar eu tento o q vc falou,

> E quando você acessa você vê o mouse fazendo o movimento? Experimente colocar o comando abaixo num arquivo .bat e rode para testar, ele vai desconectar o RDP e manter a sessao aberta em console, talvez resolva o problema com o controle do mouse:
> 
> ```
> for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
>   %windir%\System32\tscon.exe %%s /dest:console
> )
> ```
> 
> Outra coisa é fazer acesso remoto por outro software, por exemplo anydesk como disseram acima.

**Comment by fguide** [comment]
Esse problema parece com o que aconteceu em: #387, de uma olhada porque no windows 10 também tiveram esse erro e era uma mudança no script mesmo.

**Comment by siuburu** [comment]
Eu tô rodando um Windows Server na google cloud platform deu um trabalhinho no começo pra funcionar mas agr tá ok, e vou acessando ela pelo Anydesk pra olhar.

**Comment by far0fa** [comment]
> Esse problema parece com o que aconteceu em: #387, de uma olhada porque no windows 10 também tiveram esse erro e era uma mudança no script mesmo.

nao funciona msm, ele clica em house em vez de heroes, nao da refresh no mapa, n sei por qual motivo

**Comment by fguide** [comment]
Qual resolução? Se tá clicando em house é porque ta perdido no tamanho da tela

**Comment by far0fa** [comment]
> Qual resolução? Se tá clicando em house é porque ta perdido no tamanho da tela

Não consigo alterar a resolução, nao da pra ver qualque é, mas aparentemente é 1920x1080...
Tentei instalar o anydesk mas diz q nao da pra conectar, fica uma mensagem em vermelho... vou tentar o google cloud

**Comment by EricOFreitas** [comment]
Eu uso o remote manager (https://filehippo.com/download_remote-desktop-connection-manager/) com ele vc pode por mais de uma vps pra controlar mais fácil e também ir em propriedades e escolher a resolução que quer ver qndo acessa a vps.
No meu pc tinha esse prob ai eu só deixei restaurada uns 4 dedos de cada lado a janela do chrome e funcionou sem eu precisar mudar a resolução rs

**Comment by far0fa** [comment]
> 

Mas esse remote manager é para usar com as VMs criadas no SEU PC certo? Ou você consegue acessar as VPS tbm?

O que eu notei é que toda vez que eu fecho a conexão remota o computador da VPS identifica como se eu tivesse feito logoff ou algo do tipo. Até mesmo o team viewer aberto para de funcionar qdo eu fecho a conexão remota :(

**Comment by fguide** [comment]
> > 
> 
> Mas esse remote manager é para usar com as VMs criadas no SEU PC certo? Ou você consegue acessar as VPS tbm?
> 
> O que eu notei é que toda vez que eu fecho a conexão remota o computador da VPS identifica como se eu tivesse feito logoff ou algo do tipo. Até mesmo o team viewer aberto para de funcionar qdo eu fecho a conexão remota :(

Foi o que eu disse acima, você precisa usar o comando abaixo para desconectar do RDP:

```
for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
  %windir%\System32\tscon.exe %%s /dest:console
)
```

**Comment by far0fa** [comment]
> > > 
> > 
> > 
> > Mas esse remote manager é para usar com as VMs criadas no SEU PC certo? Ou você consegue acessar as VPS tbm?
> > O que eu notei é que toda vez que eu fecho a conexão remota o computador da VPS identifica como se eu tivesse feito logoff ou algo do tipo. Até mesmo o team viewer aberto para de funcionar qdo eu fecho a conexão remota :(
> 
> Foi o que eu disse acima, você precisa usar o comando abaixo para desconectar do RDP:
> 
> ```
> for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
>   %windir%\System32\tscon.exe %%s /dest:console
> )
> ```

Você é pica, consegui acessar pelo teamviewer fazendo isso, porém as resolução disponiveis o maximo é 1280x1024 ;(

**Comment by fguide** [comment]
> > > > 
> > > 
> > > 
> > > Mas esse remote manager é para usar com as VMs criadas no SEU PC certo? Ou você consegue acessar as VPS tbm?
> > > O que eu notei é que toda vez que eu fecho a conexão remota o computador da VPS identifica como se eu tivesse feito logoff ou algo do tipo. Até mesmo o team viewer aberto para de funcionar qdo eu fecho a conexão remota :(
> > 
> > 
> > Foi o que eu disse acima, você precisa usar o comando abaixo para desconectar do RDP:
> > ```
> > for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
> >   %windir%\System32\tscon.exe %%s /dest:console
> > )
> > ```
> 
> Você é pica, consegui acessar pelo teamviewer fazendo isso, porém as resolução disponiveis o maximo é 1280x1024 ;(

Tá ótimo, nessa resolucao funciona bem.

**Comment by far0fa** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Mas esse remote manager é para usar com as VMs criadas no SEU PC certo? Ou você consegue acessar as VPS tbm?
> > > > O que eu notei é que toda vez que eu fecho a conexão remota o computador da VPS identifica como se eu tivesse feito logoff ou algo do tipo. Até mesmo o team viewer aberto para de funcionar qdo eu fecho a conexão remota :(
> > > 
> > > 
> > > Foi o que eu disse acima, você precisa usar o comando abaixo para desconectar do RDP:
> > > ```
> > > for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
> > >   %windir%\System32\tscon.exe %%s /dest:console
> > > )
> > > ```
> > 
> > 
> > Você é pica, consegui acessar pelo teamviewer fazendo isso, porém as resolução disponiveis o maximo é 1280x1024 ;(
> 
> Tá ótimo, nessa resolucao funciona bem.

Agora outro erro, o bombcrypto ta falando data e hora errada
ja tentei mudar pro horario do canadá (que é onde o servidor esta hospedado) nao deu, nem do brasil :s

**Comment by fguide** [comment]
Ajusta no windows pro fuso horario correto e ativa sincronizacao automatica, deve ter segundos e atraso.

**Comment by EricOFreitas** [comment]
Se n der certo chama q vamos montar uma central de vps pra jogar bombcrypto aqui no BR msm kkkk

**Comment by far0fa** [comment]
> Se n der certo chama q vamos montar uma central de vps pra jogar bombcrypto aqui no BR msm kkkk

Não deu mano, fica dando hora errada nessa merda, desisti ja, vou é deixar meu pc ligado na casa do meu irmao qnd for viajar e acesso por lá, >_> sou burro demais com essas coisa hUEHE

**Comment by kerferber** [comment]
@fguide tentei executar seu .bat mas não funcionou,,, não sei oq estou fazendo de errado..

estou rodando uma VM no google cloud com windows server 2019 e um bot com multicount... quando estou logado através do "conexão remota de área de trabalho" funciona perfeitamente, porém quando eu fecho a conexão, a VM para de rodar...

Tentei usar seu .bat e acessar com team viewer mas não consegui. assim que fecho a VM o team viewer para de funcionar, mesmo após rodar o .bat.

Estava acostumado com o linux na VM que mesmo após fechar o remote desktop seguia funcionando normalmente,,, agora no windows server não estou conseguindo...

agradeço qualquer auxílio, obrigado

**Comment by fguide** [comment]
@kerferber o problema do google cloud é que aparentemente precisa criar um display virtual pra funcionar sem ninguém logado.

O .bat envia a sessão do remote desktop para o console, porem se nao houver display ela vai fechar, veja abaixo:

![image](https://user-images.githubusercontent.com/95459411/150523430-817b8819-f4ee-4eae-9af9-5e6dce860d1a.png)

Tente fazer essa configuração e testar novamene desconectando com o .bat
