### ISSUE TITLE
Será que da certo?

### ISSUE THREAD

**Issue by alexandernicacio** [mpcabete/bombcrypto-bot#452]
boa noite amigos agora com a retirada do captcha, será que da certo voltar a primeira versão do bot, sem as correções do captcha, ou ja estão preparando uma versão atualizada do bot sem o captcha?

**Comment by joaovictor7** [comment]
O bot continua funcionando de boa…

**Comment by Hyroshima** [comment]
> boa noite amigos agora com a retirada do captcha, será que da certo voltar a primeira versão do bot, sem as correções do captcha, ou ja estão preparando uma versão atualizada do bot sem o captcha?

tentei usar uma versão q eu tinha mas n deu certo kkk to usando a atual e está funcionando certinho mesmo n tendo o captcha
