### ISSUE TITLE
Sugestão de Feature: detecção de Jaula e gravação automatica em caso de bug.

### ISSUE THREAD

**Issue by iurobpn** [mpcabete/bombcrypto-bot#453]
Tem um bug recente em que as jaulas podem ser destruídas e não aparecerem na capsula pra gente dar claim. A solução que eles deram é de gravar/filmar o mapa com jaula e enviar para eles solicitando o hero. Com o uso do bot nem sempre se percebe se tem jaula ou não, dai a necessidade desta feature. A minha idéia é o bot detectar a jaula e gravar a tela automaticamente pra podermos solicitar os heroes.

**Comment by 0bomb4** [comment]
O problema é justamente testar na pratica, ja que a jaula quase nao aparece xD
