### ISSUE TITLE
Como não colocar personagens épicos para trabalhar

### ISSUE THREAD

**Issue by Soupxasy** [mpcabete/bombcrypto-bot#454]
Queria saber se tem um jeito de fazer com que o bot não coloque personagens da classe épica para trabalhar automaticamente.

**Comment by Nydoehar** [comment]
De ter tem, mas você precisaria alterar o código do bot. 

O bot funciona assim: "**se tiver com a barra de stamina verde, coloque para trabalhar**".

Você colocaria uma exceção:

"se tiver com a barra de stamina verde, coloque para trabalhar, **mas se for esse herói épico, deixe quieto**."

E não, eu não sei como programar isso.

**Comment by llFerreira** [comment]
> Queria saber se tem um jeito de fazer com que o bot não coloque personagens da classe épica para trabalhar automaticamente.

Eu tava sofrendo com isso quando tirei meu lendário e meu super raro segunda. Levei quase 2h quebrando a cabeça para ele botar apenas os comuns para trabalhar e consegui. Tem que editar imagens e codigo do jogo.

Se tu quiser que seja apenas os comuns, eu te passo os dados que tem que fazer

**Comment by faarys** [comment]
> > I wonder if there's a way to make the bot not automatically put characters of the epic class to work.
> 
> I was suffering from it when I took my legendary and my super rare second. It took me almost 2h racking my brain for him to put only the common ones to work and I got it. You have to edit images and game code.
> 
> If you want it to be just the common ones, I'll give you the data you have to do

can you provide it here. I only want common to work

**Comment by diogosilvadossantos** [comment]
> > Queria saber se tem um jeito de fazer com que o bot não coloque personagens da classe épica para trabalhar automaticamente.
> 
> Eu tava sofrendo com isso quando tirei meu lendário e meu super raro segunda. Quase 2h quebrando a cabeça para ele botar apenas os comuns para trabalhar e consegui. Tem que editar imagens e codigo do bot.
> 
> Se tu quiser que seja apenas os comuns, eu te passo os dados que tem que fazer

tem como ensinar?

**Comment by diogosilvadossantos** [comment]
> > Queria saber se tem um jeito de fazer com que o bot não coloque personagens da classe épica para trabalhar automaticamente.
> 
> Eu tava sofrendo com isso quando tirei meu lendário e meu super raro segunda. Quase 2h quebrando a cabeça para ele botar apenas os comuns para trabalhar e consegui. Tem que editar imagens e codigo do bot.
> 
> Se tu quiser que seja apenas os comuns, eu te passo os dados que tem que fazer

Tem como ensinar?

**Comment by llFerreira** [comment]
> > > Queria saber se tem um jeito de fazer com que o bot não coloque personagens da classe épica para trabalhar automaticamente.
> > 
> > 
> > Eu tava sofrendo com isso quando tirei meu lendário e meu super raro segunda. Quase 2h quebrando a cabeça para ele botar apenas os comuns para trabalhar e consegui. Tem que editar imagens e codigo do bot.
> > Se tu quiser que seja apenas os comuns, eu te passo os dados que tem que fazer
> 
> Tem como ensinar?

Tenho sim, tu precisa excluir a imagem full-stamina e duplicar a imagem COMMON, na pasta TARGETS. Duplica ela com o nome full-stamina, igual a que apagou. Em seguida, tu vai nas config.yaml e na opçao de enviar heroi, tu escolhe FULL e salva.
![image](https://user-images.githubusercontent.com/41524514/147370436-6b0c27f9-eaed-4e42-9515-a1e55ea44131.png)
![image](https://user-images.githubusercontent.com/41524514/147370459-12118cd1-bb62-42b3-8334-4599055aca7f.png)


Agora vai em editar o INDEX, e na linha 297: tu edita o OFFSET e poem 220
![image](https://user-images.githubusercontent.com/41524514/147370431-e70df07e-95fd-4f4a-bdf7-5ffe51c21372.png)

**Comment by diogosilvadossantos** [comment]
> > > > Queria saber se tem um jeito de fazer com que o bot não coloque personagens da classe épica para trabalhar automaticamente.
> > > 
> > > 
> > > Eu tava sofrendo com isso quando tirei meu lendário e meu super raro segunda. Quase 2h quebrando a cabeça para ele botar apenas os comuns para trabalhar e consegui. Tem que editar imagens e codigo do bot.
> > > Se tu quiser que seja apenas os comuns, eu te passo os dados que tem que fazer
> > 
> > 
> > Tem como ensinar?
> 
> Tenho sim, tu precisa excluir a imagem full-stamina e duplicar a imagem COMMON, na pasta TARGETS. Duplica ela com o nome full-stamina, igual a que apagou. Em seguida, tu vai nas config.yaml e na opçao de enviar heroi, tu escolhe FULL e salva. ![image](https://user-images.githubusercontent.com/41524514/147370436-6b0c27f9-eaed-4e42-9515-a1e55ea44131.png) ![image](https://user-images.githubusercontent.com/41524514/147370459-12118cd1-bb62-42b3-8334-4599055aca7f.png)
> 
> Agora vai em editar o INDEX, e na linha 297: tu edita o OFFSET e poem 220 ![image](https://user-images.githubusercontent.com/41524514/147370431-e70df07e-95fd-4f4a-bdf7-5ffe51c21372.png)

valeuu

**Comment by yurilagrotta** [comment]
> > > > Queria saber se tem um jeito de fazer com que o bot não coloque personagens da classe épica para trabalhar automaticamente.
> > > 
> > > 
> > > Eu tava sofrendo com isso quando tirei meu lendário e meu super raro segunda. Quase 2h quebrando a cabeça para ele botar apenas os comuns para trabalhar e consegui. Tem que editar imagens e codigo do bot.
> > > Se tu quiser que seja apenas os comuns, eu te passo os dados que tem que fazer
> > 
> > 
> > Tem como ensinar?
> 
> Tenho sim, tu precisa excluir a imagem full-stamina e duplicar a imagem COMMON, na pasta TARGETS. Duplica ela com o nome full-stamina, igual a que apagou. Em seguida, tu vai nas config.yaml e na opçao de enviar heroi, tu escolhe FULL e salva. ![image](https://user-images.githubusercontent.com/41524514/147370436-6b0c27f9-eaed-4e42-9515-a1e55ea44131.png) ![image](https://user-images.githubusercontent.com/41524514/147370459-12118cd1-bb62-42b3-8334-4599055aca7f.png)
> 
> Agora vai em editar o INDEX, e na linha 297: tu edita o OFFSET e poem 220 ![image](https://user-images.githubusercontent.com/41524514/147370431-e70df07e-95fd-4f4a-bdf7-5ffe51c21372.png)

Desse modo funciona, porem ele manda todos comuns trabalhar mesmo estando sem stamina.

**Comment by yurilagrotta** [comment]
Fiz uma alteração para resolver isso, quem quiser usar :)
Agora apenas os comuns e com barra verde vai para o trabalho. 

Edite o arquivo index.py
Função clickGreenBarButtons(): substitua por essa:

`def clickGreenBarButtons():
    # ele clicka nos q tao trabaiano mas axo q n importa
    offset = 130

    green_bars = positions(images['green-bar'], threshold=ct['green_bar'])
    logger('🟩 %d green bars detected' % len(green_bars))
    buttons = positions(images['go-work'], threshold=ct['go_to_work_btn'])
    logger('🆗 %d buttons detected' % len(buttons))
    commoms = positions(images['commom-text'], threshold = ct['commom'])
    logger('🆗 %d commoms detected' % len(commoms))

    not_working_green_bars = []
    for bar in green_bars:
        if not isWorking(bar, buttons) and isCommom(bar, commoms):
            not_working_green_bars.append(bar)
    if len(not_working_green_bars) > 0:
        logger('🆗 %d buttons with green bar detected' % len(not_working_green_bars))
        logger('👆 Clicking in %d heroes' % len(not_working_green_bars))

    # se tiver botao com y maior que bar y-10 e menor que y+10
    for (x, y, w, h) in not_working_green_bars:
        # isWorking(y, buttons)
        moveToWithRandomness(x+offset+(w/2),y+(h/2))
        pyautogui.click()
        global hero_clicks
        hero_clicks = hero_clicks + 1
        if hero_clicks > 20:
            logger('⚠️ Too many hero clicks, try to increase the go_to_work_btn threshold')
            return
        #cv2.rectangle(sct_img, (x, y) , (x + w, y + h), (0,255,255),2)
    return len(not_working_green_bars)`
    
E adicione essa função para checar se é comum ou não

`def isCommom(bar, commoms):
    y = bar[1]

    for (_,button_y,_,button_h) in commoms:
        isBelow = y < (button_y + button_h)
        isAbove = y > (button_y - button_h)
        if isBelow and isAbove:
            return True
    return False`
