### ISSUE TITLE
help

### ISSUE THREAD

**Issue by HugorRR** [mpcabete/bombcrypto-bot#455]
erro msg

![Untitled](https://user-images.githubusercontent.com/96600806/147300715-1eea2fdf-efaf-4c76-89b1-bc926876961f.png)

**Comment by Galinho90** [comment]
> 

Rode primeiro o comando: 

pip install -r requirements.txt

**Comment by HugorRR** [comment]
Ja rodei mas continua o mesmo erro

**Comment by keter45** [comment]
pip install opencv-contrib-python

resolveu aqui

**Comment by HugorRR** [comment]
Traceback (most recent call last):
  File "C:\Users\hugor\Documents\bombcrypto-bot-main\index.py", line 2, in <module>
    from cv2 import cv2
ModuleNotFoundError: No module named 'cv2'


continua com esse erro :/ infelizmente os dois nao deu certo

**Comment by fguide** [comment]
Windows... veja #389
