### ISSUE TITLE
AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'

### ISSUE THREAD

**Issue by Kiera-17** [mpcabete/bombcrypto-bot#456]
Pessoal, boa noite.

Estou com este erro ao tentar iniciar o bot, estou usando a versão 3.9.9 do python, alguém consegue me ajudar com este problema ?

obg...

![image](https://user-images.githubusercontent.com/96512953/147304590-0ed0c2c0-ada3-46c6-92cc-4abd2246146f.png)

**Comment by Nydoehar** [comment]
Resposta: https://github.com/asweigart/pyautogui/issues/598

> Hi Everyone! I hope everyone is doing well. It looks like there is an easy fix for this one.
> 
> pyautogui/pyautogui/__init__.py
> 
> Line 221 in 5e4acb8
>  locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__ 
> 
> Here on this line we just need to change
> 
> locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
> 
> To This:
> 
> locateOnWindow.__doc__ = pyscreeze.locateOnScreen.__doc__
> 
> Update this and your inputs will work. The locateOnWindow changed to locateOnScreen.
> 
> ++@asweigart, FYI
> 
> Tested on: Windows Version	10.0.19042 Build 19042
> Current Python:        3.9.2
> Current PyAutoGUI:     0.9.53
> 
> The file location for me was:
> 'C:\Users\{UserName}\AppData\Roaming\Python\Python39\site-packages\pyautogui\init.py'
> 
> Do not look in the
> C:\Program Files\Python39 folders

**Comment by Kiera-17** [comment]
> 

Eu consegui localizar o arquivo indicado "init.py", abro ele com o bloco de notas para realizar esta substituição certo? não encontrei essa parte do código para substituir, a indicação da linha, aparece em algum programa especifico ? tipo de desenvolvimento ?

**Comment by fguide** [comment]
Remova a linha 4 do codigo: 

>from captcha.solveCaptcha import solveCaptcha

O jogo esta sem captcha por enquanto, nao é necessário.
