### ISSUE TITLE
[BUG] Scroll Heroes

### ISSUE THREAD

**Issue by rzanca** [mpcabete/bombcrypto-bot#457]
Encontrei um problema no BOT, que só afeta o pessoal que possui um time bom.

Quando o Bot vai fazer o Scroll na tela de heroes. O mesmo busca a imagem "common-text". Se referindo ao tipo de herói. Porém se você não tiver pelo menos 1 comum nessa tela. Ele simplesmente não executa o scroll e só coloca os primeiros heróis trabalharem. 

Descobri isso hoje, pois dei mais mints na mesma conta. E a tela inicial, ficou sem um comum, devido a numeração. 

Teria que referenciar em outra imagem para o scroll funcionar corretamente.

**Comment by llFerreira** [comment]
Printa algo em comum, onde ele falha, e substituí a imagem do comum-text nos arquivos e tente novamente

**Comment by fguide** [comment]
@rzanca 

Uma sugestao, substitua o print do common-text por um print do Level, ex:

![image](https://user-images.githubusercontent.com/95459411/147390870-3b03e6cb-ee60-4f94-86b8-f994764e42e3.png)

Deve ajudar no seu caso.

**Comment by Alt4s** [comment]
@rzanca conseguiu resolver?

**Comment by rzanca** [comment]
Usei o Lv e resolveu.

**Comment by isacsg** [comment]
perfeito, aqui resolveu pra mim também. Obrigada!
