### ISSUE TITLE
Threshold go to work

### ISSUE THREAD

**Issue by zSinnK** [mpcabete/bombcrypto-bot#458]
![Screenshot_2021-12-24-00-33-06-255_com google chromeremotedesktop](https://user-images.githubusercontent.com/95734505/147313136-583ab94d-2e1f-46bc-9c5f-cd628afc3d6c.jpg)

Tô com isso a um tempão mas nunca fiz questão de ir atrás mas vim ver p saber se tem como arrumar
Já troquei a imagem de work na pasta e já tentei mexer no threshold porém não resolve

**Comment by fguide** [comment]
Isso significa que está fazendo muitos cliques, voce pode alterar 'go_to_work_btn' no arquivo config.yaml, mas se ta funcionando bem nao precisa nem se preocupar com isso.

**Comment by zSinnK** [comment]
> Isso significa que está fazendo muitos cliques, voce pode alterar 'go_to_work_btn' no arquivo config.yaml, mas se ta funcionando bem nao precisa nem se preocupar com isso.

Então.. ele funciona porém demora muito pra colocar todos os heros p trabalhar, coisa de 3 minutos.
Ele coloca 1 gero, scrolla pra baixo, coloca outro, scrolla dnv, coloca outro scrolla etc... E vai indo assim de 1 em 1

**Comment by RenanPFerreira** [comment]
Eu também tenho esse erro, tenho 3 heróis e ele fica clicando várias e várias vezes no Work, só depois de muito tempo que vai para o treasure hunt. Já refiz as imagens e mexi no threshold mas sem sucesso.
