### ISSUE TITLE
"Home feature not enabled"

### ISSUE THREAD

**Issue by fraga0017** [mpcabete/bombcrypto-bot#459]
Quando eu ligo o bot aparece essa mensagem
![image](https://user-images.githubusercontent.com/39146821/147325832-56793f5f-0d4f-4334-bc7e-745d75d5509a.png)

a pasta dos herois está certinha
![image](https://user-images.githubusercontent.com/39146821/147325888-bc2e6a86-9805-444f-91f5-91771acd9ea1.png)

**Comment by grantyyy** [comment]
Está certo, essa função deve ser ativa apenas para aqueles que tem casa :)

Se você possui casa, pode habilita-la no arquivo `config.yml`

![image](https://user-images.githubusercontent.com/94913189/147347432-46c520b8-5e9e-4b01-b43d-89a4141c2ed0.png)

linha 90, coloque como True, e a função estará ativa 👍

**Comment by fraga0017** [comment]
valeu mano, vou testar aqui

**Comment by leinadany** [comment]
hello, did you make it work?

**Comment by fraga0017** [comment]
yes, i left enable: True and I adjusted the rest until it was smooth

**Comment by leinadany** [comment]
How did you capture the heroes and what name did you give them?

**Comment by fraga0017** [comment]
the name of the .png file does not matter
create a folder with that name
![image](https://user-images.githubusercontent.com/39146821/148581432-7d68b15e-9d72-4987-b8e2-d209a0da2c33.png)
just take a screenshot of each hero you want sent home and that's it
![image](https://user-images.githubusercontent.com/39146821/148581652-a5bbe071-011f-4aae-b1b7-0a66244d00b5.png)

**Comment by biroandre** [comment]
![Kepernyokep_2022-01-13_135548](https://user-images.githubusercontent.com/97684687/149353004-3b1de367-374c-435a-809c-cb9a78723d2e.png)
can someone help me please with this one? when i enable house it shows me this
