### ISSUE TITLE
Usando o bot em cloud (VPS)

### ISSUE THREAD

**Issue by victorblevi** [mpcabete/bombcrypto-bot#46]
Primeiramente, muito obrigado pelo bot, ele funciona muito bem!

Gostaria de saber se é possivel rodar o bot em windows server (VPS)

Fiz várias tentativas, mas sem sucesso.

Obrigado

**Comment by mpcabete** [comment]
Ol victor, tem sim. Eu atualmente rodo ele em uma vps linux da google cloud. Imagino que em um server windows seja ainda mais fácil.  
Eu vou ver se consigo escrever um guia passo a passo hj a tarde.

**Comment by m4dro** [comment]
Olá Vitor é possivel sim, eu estou usando, certifique que esteja usando a resolucao alta 1920 x 1080

**Comment by victorblevi** [comment]
@mpcabete Muito obrigado! Vai ajudar muito!

@m4dro está usando quanto de memoria, cpu?
Ta usando linux ou win server, ah e outra coisa, ta pagando quanto por mês?


Valeu

**Comment by arthurbolsoni** [comment]
como tu roda a pyautogui no console na vps?

**Comment by m4dro** [comment]
> @mpcabete Muito obrigado! Vai ajudar muito!
> 
> @m4dro está usando quanto de memoria, cpu? Ta usando linux ou win server, ah e outra coisa, ta pagando quanto por mês?
> 
> Valeu

Fala meu caro, cara na verdade eu to usando um hyper-V msm com uma maquina do lado, mas se quiser uma VPS boa e barata essa aqui https://console.kamatera.com/servers   uns 15 dolares por mes vc monta uma maquina basica

**Comment by e9857** [comment]
> Ol victor, tem sim. Eu atualmente rodo ele em uma vps linux da google cloud. Imagino que em um server windows seja ainda mais fácil. Eu vou ver se consigo escrever um guia passo a passo hj a tarde.

Fiz hoje a primeira doação de 2 Bcoins... em cada levantamento uma parte será tua :D
Tenho num VPS de ubuntu, mas às vezes ainda ele ainda desliga, por isso um tutorial teu será muito bem vindo...

**Comment by victorblevi** [comment]
@mpcabete Acabei de fazer uma doação, 
A cada claim vou doando mais!
Tmj!

**Comment by m4dro** [comment]
> @mpcabete Acabei de fazer uma doação, A cada claim vou doando mais! Tmj!

Eu tbm fiz a doacao, achei o trabalho deste dev muito bom, nós devemos valorizar a comunidade. Doem pessoal por favor.

**Comment by victorblevi** [comment]
@mpcabete antes de tudo, muito obrigado pelas atualizações no bot!

Cara, teria previsão para esse tutorial?

abração

**Comment by VitotEPB** [comment]
Também gostaria do tutorial!
