### ISSUE TITLE
Apenas 99, 99,99 

### ISSUE THREAD

**Issue by Alison-Fernandes-dev** [mpcabete/bombcrypto-bot#460]
![erro](https://user-images.githubusercontent.com/78398094/147329160-c9513028-4533-40b2-9464-53190c8f7961.jpg)

estou usando um notebook, com a resolução em 100%.
obrigado pelo programa amigo, só falta eu conseguir rodar.

**Comment by Hyroshima** [comment]
qual a resolução da tela de seu notebook? quem ta usando em fullhd não está tendo problema, fiz pra um amigo e o pc dele a tela é 4k, dai tive q baixar pra fullhd e funcionou normal, irei fazer a substituição das imagens para o tamanoh de 4k para que o bot funcione, talvez seja isso no seu caso.

**Comment by fguide** [comment]
E qual o problema que você tem? o "99" nao é erro, só falha na tradução de caracteres unicode.

**Comment by Gaboo134** [comment]
eu tive que fazer a troca das imagens para resolver em um segundo noot, so se atente a imagem da barra verde, pois a se ela ficar muito curta o bot não clica para enviar os bonecos para farm, tem que ficar testando de acordo com sua tela

**Comment by Alison-Fernandes-dev** [comment]
> E qual o problema que você tem? o "99" nao é erro, só falha na tradução de caracteres unicode.

o problema é esse não faz nada, só da essa mensagem

**Comment by fguide** [comment]
Dá uma olhada no #397 talvez ajude!

**Comment by kushinier** [comment]
Aqui esta acontecendo o mesmo comigo apenas fica 99, 99. Alguem conseguio descobrir o que é ?

**Comment by Alison-Fernandes-dev** [comment]
> Dá uma olhada no #387 talvez ajude se for o caso de não clicar em work, se não fizer nada, nem movimento de mouse, daí pode ser outra coisa.
> 
> Curiosidade, voce deixou a tela do jogo em primeiro plano?

sim deixei, vou mudar as imagens pra ver

**Comment by Alison-Fernandes-dev** [comment]
> qual a resolução da tela de seu notebook? quem ta usando em fullhd não está tendo problema, fiz pra um amigo e o pc dele a tela é 4k, dai tive q baixar pra fullhd e funcionou normal, irei fazer a substituição das imagens para o tamanoh de 4k para que o bot funcione, talvez seja isso no seu caso.

1920x1080 a 150%

**Comment by fguide** [comment]
Coloque em 100% de scaling, e veja as respostas em #468

**Comment by Xelepinho** [comment]
Estou com o msm problema no meu notebook, alguem sabe como resolver isso?
