### ISSUE TITLE
Esta conta está em revisão

### ISSUE THREAD

**Issue by Wallace1402** [mpcabete/bombcrypto-bot#461]
![IMG-20211223-WA0162](https://user-images.githubusercontent.com/34112134/147331298-5c784c8b-f9e7-4d34-acf1-43e4da213045.jpg)

**Comment by fguide** [comment]
#430 nao se preocupe.

**Comment by lucasvieceli** [comment]
vc so usou esse bot, n tentou acessar a mesma conta em dois lugares diferenteS?
