### ISSUE TITLE
Atualizar a página

### ISSUE THREAD

**Issue by Hyroshima** [mpcabete/bombcrypto-bot#462]
Tive uma ideia que talvez seja interessante, mesmo sabendo que o bot não da ban etc.. ao fazer uso do bot praticamente ficará logado até o momento que tomar um dc ou server cair, a minha sugestão é adicionar uma opção que a cada x tempo conectado direto o bot atualize a página para que faça um novo login/sessão no bomb :D

**Comment by Yumiizera** [comment]
O bot já faz isso.

**Comment by Hyroshima** [comment]
> O bot já faz isso.

acho que vc se confundiu, o que o bot faz é voltar pra tela das seleção de modos e retorna ao mapa para atualizar as posições dos bhero, e a outra coisa q faz parecido é se vc tomar dc ele reconecta, porem se vc n tomar dc vc vai ficar 72h conectado direto entregando assim que vc é um bot, pq uma pessoa normal se ficar parada na tela do mapa é disconectado, então a ação do bot de ficar dando refresh na posição dos bhero corta esse disconect forçado, oq eu propus foi a cada X tempo conectado direto sem ter tomado dc dai então o bot force uma reconecção para se assemelhar a uma ação humana.

**Comment by Yumiizera** [comment]
> > O bot já faz isso.
> 
> acho que vc se confundiu, o que o bot faz é voltar pra tela das seleção de modos e retorna ao mapa para atualizar as posições dos bhero, e a outra coisa q faz parecido é se vc tomar dc ele reconecta, porem se vc n tomar dc vc vai ficar conectado direto entregando assim que vc é um bot, pq uma pessoa normal se ficar parada na tela do mapa é disconectado, então a ação do bot de ficar dando refresh na posição dos bhero corta esse disconect forçado, oq eu propus foi a cada X tempo conectado direto sem ter tomado dc dai então o bot force uma reconecção para se assemelhar a uma ação humana.

Ah sim, imaginei que se tratasse do "ctrl + F5" que foi implementado dentro do bot.

**Comment by llFerreira** [comment]
Não tem o pq de implementar isso, ja que bot é feito para rodar 24h. Isso, voce pode fazer manualmente a cada tempo que tu quiser

**Comment by Hyroshima** [comment]
> Não tem o pq de implementar isso, ja que bot é feito para rodar 24h. Isso, voce pode fazer manualmente a cada tempo que tu quiser

por isso falei possível ideia, até pq o proposito do bot é fazer com aque as ações seja o mais próximo de um humano, ninguém sabe como que está realmente essa situação deles não da ban por uso de bot, então quanto menos se parecer com um bot melhor será para evitar filtro de possíveis jogadores bot.
