### ISSUE TITLE
How to run 4 bot in the same time?

### ISSUE THREAD

**Issue by soundsticks** [mpcabete/bombcrypto-bot#466]
How to run 4 bot in the same time, not in vm

**Comment by mGranTY** [comment]
see here https://github.com/mpcabete/bombcrypto-bot/issues/431#issuecomment-999615099

**Comment by soundsticks** [comment]
just add

`import pygetwindow ` into index.py? What about the other setup?

**Comment by mGranTY** [comment]
> just add
> 
> `import pygetwindow ` into index.py? What about the other setup?

nope, you need to edit the def main() as i said in the other comment.

**Comment by soundsticks** [comment]
> > just add
> > `import pygetwindow ` into index.py? What about the other setup?
> 
> nope, you need to edit the def main() as i said in the other comment.
> 
> first import and then edit the main
> 
> ```
> def main():
>     time.sleep(5)
>     t = c['time_intervals']
>     
> 
>     windows = []
> 
>     for w in pygetwindow.getWindowsWithTitle('bombcrypto'):
>         windows.append({
>             "window": w,
>             "login" : 0,
>             "heroes" : 0,
>             "new_map" : 0,
>             "check_for_captcha" : 0,
>             "refresh_heroes" : 0
>             })
> 
>     while True:
>         now = time.time()
> 
>         for last in windows:
>             last["window"].activate()
>             time.sleep(2)
> 
>             if now - last["check_for_captcha"] > addRandomness(t['check_for_captcha'] * 60):
>                 last["check_for_captcha"] = now
>                 solveCaptcha(pause)
> 
>             if now - last["heroes"] > addRandomness(t['send_heroes_for_work'] * 60):
>                 last["heroes"] = now
>                 refreshHeroes()
> 
>             if now - last["login"] > addRandomness(t['check_for_login'] * 60):
>                 sys.stdout.flush()
>                 last["login"] = now
>                 login()
> 
>             if now - last["new_map"] > t['check_for_new_map_button']:
>                 last["new_map"] = now
> 
>                 if clickBtn(images['new-map']):
>                     loggerMapClicked()
> 
> 
>             if now - last["refresh_heroes"] > addRandomness( t['refresh_heroes_positions'] * 60):
>                 solveCaptcha(pause)
>                 last["refresh_heroes"] = now
>                 refreshHeroesPositions()
> 
>             #clickBtn(teasureHunt)
>             logger(None, progress_indicator=True)
> 
>             sys.stdout.flush()
> 
>             time.sleep(1)
>             
> main()
> ```

What should I edit, I have really no idea

**Comment by Yumiizera** [comment]
Eu fiz a edição e não funcionou.

**Comment by mGranTY** [comment]
> > > just add
> > > `import pygetwindow ` into index.py? What about the other setup?
> > 
> > 
> > nope, you need to edit the def main() as i said in the other comment.
> > first import and then edit the main
> > ```
> > def main():
> >     time.sleep(5)
> >     t = c['time_intervals']
> >     
> > 
> >     windows = []
> > 
> >     for w in pygetwindow.getWindowsWithTitle('bombcrypto'):
> >         windows.append({
> >             "window": w,
> >             "login" : 0,
> >             "heroes" : 0,
> >             "new_map" : 0,
> >             "check_for_captcha" : 0,
> >             "refresh_heroes" : 0
> >             })
> > 
> >     while True:
> >         now = time.time()
> > 
> >         for last in windows:
> >             last["window"].activate()
> >             time.sleep(2)
> > 
> >             if now - last["check_for_captcha"] > addRandomness(t['check_for_captcha'] * 60):
> >                 last["check_for_captcha"] = now
> >                 solveCaptcha(pause)
> > 
> >             if now - last["heroes"] > addRandomness(t['send_heroes_for_work'] * 60):
> >                 last["heroes"] = now
> >                 refreshHeroes()
> > 
> >             if now - last["login"] > addRandomness(t['check_for_login'] * 60):
> >                 sys.stdout.flush()
> >                 last["login"] = now
> >                 login()
> > 
> >             if now - last["new_map"] > t['check_for_new_map_button']:
> >                 last["new_map"] = now
> > 
> >                 if clickBtn(images['new-map']):
> >                     loggerMapClicked()
> > 
> > 
> >             if now - last["refresh_heroes"] > addRandomness( t['refresh_heroes_positions'] * 60):
> >                 solveCaptcha(pause)
> >                 last["refresh_heroes"] = now
> >                 refreshHeroesPositions()
> > 
> >             #clickBtn(teasureHunt)
> >             logger(None, progress_indicator=True)
> > 
> >             sys.stdout.flush()
> > 
> >             time.sleep(1)
> >             
> > main()
> > ```
> 
> What should I edit, I have really no idea

you need to edit index.py, change the part that i pasted :) 

add the import at one of the first lines  like this: 
![image](https://user-images.githubusercontent.com/94913189/147366608-2e1691ef-6a63-4e23-a892-7a9fec66bfd2.png)


then starting from line 452 paste the code i sent above

![image](https://user-images.githubusercontent.com/94913189/147366717-9db4a797-744d-4219-9e75-0e81d6bb0b1e.png)



and open the game using the direct link: https://app.bombcrypto.io/webgl/index.html


add me on discord :0 GranTY#8475

**Comment by mGranTY** [comment]
> Eu fiz a edição e não funcionou.

tem que entrar pelo link do jogo direito maninho https://app.bombcrypto.io/webgl/index.html

se não der certo me chama discord GranTY#8475

**Comment by Yumiizera** [comment]
> > Eu fiz a edição e não funcionou.
> 
> tem que entrar pelo link do jogo direito maninho https://app.bombcrypto.io/webgl/index.html
> 
> se não der certo me chama discord GranTY#8475

Eu fiz, porém 
![image](https://user-images.githubusercontent.com/95440041/147367189-57131265-3a3f-4cd8-8590-2c5b5e336736.png)

**Comment by mGranTY** [comment]
> > > Eu fiz a edição e não funcionou.
> > 
> > 
> > tem que entrar pelo link do jogo direito maninho https://app.bombcrypto.io/webgl/index.html
> > se não der certo me chama discord GranTY#8475
> 
> Eu fiz, porém ![image](https://user-images.githubusercontent.com/95440041/147367189-57131265-3a3f-4cd8-8590-2c5b5e336736.png)

provavelmente substituiu alguma linha que não era pra ter trocado :(

vou mandar o meu codigo, copia e cola ele por inteiro 

https://pastebin.com/raw/DStP99kx

**Comment by Yumiizera** [comment]
> > > > Eu fiz a edição e não funcionou.
> > > 
> > > 
> > > tem que entrar pelo link do jogo direito maninho https://app.bombcrypto.io/webgl/index.html
> > > se não der certo me chama discord GranTY#8475
> > 
> > 
> > Eu fiz, porém ![image](https://user-images.githubusercontent.com/95440041/147367189-57131265-3a3f-4cd8-8590-2c5b5e336736.png)
> 
> provavelmente substituiu alguma linha que não era pra ter trocado :(
> 
> vou mandar o meu codigo, copia e cola ele por inteiro
> 
> https://pastebin.com/raw/DStP99kx

Vou te chamar no discord

**Comment by mfsousa** [comment]
(For english, please translate with google translator...)

Boa tarde, essa solução indicada foi criada por mim há algum tempo. Esta aqui neste fork: https://github.com/mfsousa/bombcrypto-bot

Tem um pull request, que eu acabei por fechar, onde voces podem seguir os comentarios (especialmente os ultimos) e ver como devem fazer para configurar: https://github.com/mpcabete/bombcrypto-bot/pull/169

**Comment by Yoyozuya** [comment]
> > just add
> > `import pygetwindow ` into index.py? What about the other setup?
> 
> nope, you need to edit the def main() as i said in the other comment.
> 
> first import and then edit the main
> 
> ```
> def main():
>     time.sleep(5)
>     t = c['time_intervals']
>     
> 
>     windows = []
> 
>     for w in pygetwindow.getWindowsWithTitle('bombcrypto'):
>         windows.append({
>             "window": w,
>             "login" : 0,
>             "heroes" : 0,
>             "new_map" : 0,
>             "check_for_captcha" : 0,
>             "refresh_heroes" : 0
>             })
> 
>     while True:
>         now = time.time()
> 
>         for last in windows:
>             last["window"].activate()
>             time.sleep(2)
> 
>             if now - last["check_for_captcha"] > addRandomness(t['check_for_captcha'] * 60):
>                 last["check_for_captcha"] = now
>                 solveCaptcha(pause)
> 
>             if now - last["heroes"] > addRandomness(t['send_heroes_for_work'] * 60):
>                 last["heroes"] = now
>                 refreshHeroes()
> 
>             if now - last["login"] > addRandomness(t['check_for_login'] * 60):
>                 sys.stdout.flush()
>                 last["login"] = now
>                 login()
> 
>             if now - last["new_map"] > t['check_for_new_map_button']:
>                 last["new_map"] = now
> 
>                 if clickBtn(images['new-map']):
>                     loggerMapClicked()
> 
> 
>             if now - last["refresh_heroes"] > addRandomness( t['refresh_heroes_positions'] * 60):
>                 solveCaptcha(pause)
>                 last["refresh_heroes"] = now
>                 refreshHeroesPositions()
> 
>             #clickBtn(teasureHunt)
>             logger(None, progress_indicator=True)
> 
>             sys.stdout.flush()
> 
>             time.sleep(1)
>             
> main()
> ```

hello my error is 
![Screenshot_1](https://user-images.githubusercontent.com/96647204/147380796-60f9a771-5c9d-407f-87bc-b48d18482bb0.png)

**Comment by soundsticks** [comment]
But sometime I will get this error, then the bot will stop work 

<img width="806" alt="Screenshot 2021-12-25 at 5 11 32 PM" src="https://user-images.githubusercontent.com/6646173/147381875-966f90bf-c0ee-4981-94a0-9ae42f8a7c58.png">
