### ISSUE TITLE
BOT n detecta o ''pip install -r requirements.txt'' n ocorre a instalaçao correta, olha como fica :

### ISSUE THREAD

**Issue by Lemocas** [mpcabete/bombcrypto-bot#467]
![image](https://user-images.githubusercontent.com/96564162/147365162-1068036a-0310-438a-b0d8-c83161a21912.png)

**Comment by Yumiizera** [comment]
python index.py

Tenta esse

**Comment by mGranTY** [comment]
> ![image](https://user-images.githubusercontent.com/96564162/147365162-1068036a-0310-438a-b0d8-c83161a21912.png)

o pip deu certo, diz que ja foi baixado tudo necessário, o problema esta na execução :) 


digita `python index.py` e vê o que acontece.

**Comment by pectro174** [comment]
![hm](https://user-images.githubusercontent.com/96681674/147404240-552f2cd8-0e90-47dd-a0bb-38c4b47c48be.png)
infelizmente o meu da a mesma coisa que o amigo ai, e se eu dou "python index.py" da isso daqui:. Alguém sabe o que é e como resolvo?.

**Comment by mGranTY** [comment]
> ![hm](https://user-images.githubusercontent.com/96681674/147404240-552f2cd8-0e90-47dd-a0bb-38c4b47c48be.png) infelizmente o meu da a mesma coisa que o amigo ai, e se eu dou "python index.py" da isso daqui:. Alguém sabe o que é e como resolvo?.

ué mano isso quer dizer que o bot ta rodando, coloca na tela do jogo e ja era. Verifica se o jogo ta com zoom, se a escalabilidade do windows ta 100%

**Comment by pectro174** [comment]
deu certo dps q eu instalei a versao certa do python, mas qd tentei rodar o arquivo na mesma versao 3.10.1 no virtual machine ele da esse erro aqui ó:
obs: (no meu s.o w10 normal ja ta rodando liso
![269657028_622633785708081_9171742740381017636_n](https://user-images.githubusercontent.com/96681674/147426093-cfb55c1c-c6bf-4892-808d-f8c696992697.png)
)
