### ISSUE TITLE
O Bot não esta colocando os heróis para trabalhar. [The Bot isn't putting the heroes to work.]

### ISSUE THREAD

**Issue by edermania** [mpcabete/bombcrypto-bot#468]
O bot inicia normalmente, entra na tela de heróis arrasta para cima mas não seleciona nenhum para trabalhar, na continuação ele volta para tela de jogo e repete o loop. 

[The bot starts normally, enters the heroes screen, drags upwards but doesn't select any to work, then it goes back to the game screen and repeats the loop.]

**Comment by deividlm** [comment]
Notei isso também, será se teve alguma atualização que deixou o bot sem reconhecer as imagens?

**Comment by edermania** [comment]
Sim. Acho que foi isso... Algum erro, aparentement simples... pena que não sei progamar...

**Comment by alegalati123** [comment]
up! aqui também, mesma coisa, faz tudo certo, mas não aperta a tecla "work"

**Comment by fguide** [comment]
#387 ultima resposta deve ajudar vcs.

**Comment by deividlm** [comment]
@fguide obrigado, deu certo!

**Comment by joaovictor7** [comment]
Galera meu PR com a correção desse problema já foi aprovado. Atualizem as branchs locais de vocês.

**Comment by diogosilvadossantos** [comment]
pra mim eu fiz tudo e nao deu certo

**Comment by Novaisxd** [comment]
> Galera meu PR com a correção desse problema já foi aprovado. Atualizem as branchs locais de vocês.

eu coloco para abrir o solveCaptcha e o pyton crasha instantaneamente, é suposto abrir de algum jeito ou existe fix?

**Comment by Novaisxd** [comment]
> #387 ultima resposta deve ajudar vcs.

eu instalei o bot e ja veio com o fix

**Comment by Novaisxd** [comment]
Continuo a precisar de ajuda com o bug tho

**Comment by joaovictor7** [comment]
@Novaisxd Cara eu n entendi o problema q vc tá tendo aí

**Comment by Novaisxd** [comment]
@joaovictor7 eu continuo com o Bug de nao colocar os bonecos para trabalhar, mas o fix do captcha referido ai em cima, ja veio com a minha instalaçao inicial.

**Comment by edermania** [comment]
> @fguide obrigado, deu certo!

Segui a orientação de alteração no comando da linha 299 `pyautogui.PAUSE = pause` no meu já venho atualizada.
O que você fez?

**Comment by Novaisxd** [comment]
mes

> > @fguide obrigado, deu certo!
> 
> Segui a orientação de alteração no comando da linha 299 `pyautogui.PAUSE = pause` no meu já venho atualizada. O que você fez?

Msm coisa por aqui

**Comment by edermania** [comment]
O erro de não colocar os heróis para trabalhar ainda perciste. Fiz os procedimentos sugerisdos mas não obtive sucesso.

**Comment by Novaisxd** [comment]
Msm or aqui

**Comment by Novaisxd** [comment]
Mesmo por aqui*

**Comment by joaovictor7** [comment]
O erro que aconteceu cmg era sobre o menu de heróis que não abria. O erro de vcs é diferente. O procedimento do #387 não deve ser o suficiente.
Mauz galera. Se tivesse acontecendo cmg eu dava uma olhada.

**Comment by pedrozun** [comment]
Executem pelo Prompt de comando e não pelo Windows terminal ou Powershell, testa ai.

**Comment by edermania** [comment]
> Executem pelo Prompt de comando e não pelo Windows terminal ou Powershell, testa ai.

Sim. Eu já estava executando pelo prompt de comando.

**Comment by edermania** [comment]
![image](https://user-images.githubusercontent.com/96630872/147384747-91b27076-5821-436c-926f-9e2d474e9cb3.png)

Tentei ver onde acontece o erro na hora de execução. Parece que ele pesquisa as barras que estão em verde, e ai provavelmente deve ter um teste de `verdadeiro` ou função `SE` é dali que não esta conseguindo passar.

**Comment by edermania** [comment]
![image](https://user-images.githubusercontent.com/96630872/147384812-8b0ac1f8-fcaa-4c9c-b37f-1c8e25cecdda.png)

Tentei seguir os passos para ver onde acontece o erro. Parece que ele pesquisa as barras que estão em verde, e ai provavelmente deve ter um teste de `verdadeiro` ou algum tipo de função `SE` é ali que se encontra a falha e ao invés de clicar em "work" ele fecha e entra no loop, repetindo o processo.

**Comment by fguide** [comment]
Amigo, duas coisas, primeiro acho que não é muito interessante botar o print com ID dos seus herois...

Segundo, tente usar o jogo em inglês pra ver se faz alguma diferença.

**Comment by Novaisxd** [comment]
O problema mantém , e eu tenho o site em Inglês. Se acharem algum fix era MT bom

**Comment by fguide** [comment]
> O problema mantém , e eu tenho o site em Inglês. Se acharem algum fix era MT bom

O seu tb dá 0 buttons detected igual da imagem acima?

**Comment by jorgemtg** [comment]
@edermania e @Novaisxd o teu problema esta relacionado com o botão de go_to_work... Pode ver que ele encontra os herois com barra verde, mas não encontra botão algum... Eu estava com esse problema e resolvi primeiro de uma forma: 

* arquivo config.yaml, tu precisa alterar o padrão toleravel pelo bot de precisão, o padrão é 0.9 (90% de eficacia), aqui funcionou colocando pra 0.7... POREM TIVE PROBLEMA DE COMPORTAMENTO.... 

Depois tentei o seguinte:
* alterar o arquivo de evidencia correspondente a imagem do go_to_work, nesse caso vc precisa tirar uma print semelhante a da imagem que vá ser subsituida (formato obrigatorio .png)... PRA MIM NÃO DEU CERTO, POR ALGUM MOTIVO O SCRIPT NÃO IDENTIFICA A IMAGEM QUE EU TO INCLUINDO, NÃO IMPORTA O QUE EU FAÇA, mas pra vc pode dar certo....

E por último e que esta funcionando no momento:
* mantive tudo identico, porém alterei a resolução do meu monitor (que é ultrawide), pra 1920x1080 (monitor padrão) e até o momento tudo esta indo conforme esperado...

Obs: galera não to brigando com ninguem pelo amor de Deus, mas é aconselhavel vcs começarem a ler as informações, eu sou programador e facilita um pouco pra mim, mas no tutorial de propria instalação tem algumas dicas e macetes pra tratar esses comportamentos e que podem ajudar e muito a tentar sanar tais coisas: "https://github.com/mpcabete/bombcrypto-bot".

![image](https://user-images.githubusercontent.com/96638071/147386586-a293cb19-906c-4881-ae70-740e43fbdcc8.png)

**Comment by fguide** [comment]
> @edermania e @Novaisxd o teu problema esta relacionado com o botão de go_to_work... Pode ver que ele encontra os herois com barra verde, mas não encontra botão algum... Eu estava com esse problema e resolvi primeiro de uma forma:
> 
>     * arquivo config.yaml, tu precisa alterar o padrão toleravel pelo bot de precisão, o padrão é 0.9 (90% de eficacia), aqui funcionou colocando pra 0.7... POREM TIVE PROBLEMA DE COMPORTAMENTO....
> 
> 
> Depois tentei o seguinte:
> 
>     * alterar o arquivo de evidencia correspondente a imagem do go_to_work, nesse caso vc precisa tirar uma print semelhante a da imagem que vá ser subsituida (formato obrigatorio .png)... PRA MIM NÃO DEU CERTO, POR ALGUM MOTIVO O SCRIPT NÃO IDENTIFICA A IMAGEM QUE EU TO INCLUINDO, NÃO IMPORTA O QUE EU FAÇA, mas pra vc pode dar certo....
> 
> 
> E por último e que esta funcionando no momento:
> 
>     * mantive tudo identico, porém alterei a resolução do meu monitor (que é ultrawide), pra 1920x1080 (monitor padrão) e até o momento tudo esta indo conforme esperado...
> 
> 

Exatamente, por isso falei para colocar em INGLÊS, porque o botão work muda de acordo com o idioma.

**Comment by fguide** [comment]
>     * alterar o arquivo de evidencia correspondente a imagem do go_to_work, nesse caso vc precisa tirar uma print semelhante a da imagem que vá ser subsituida (formato obrigatorio .png)... PRA MIM NÃO DEU CERTO, POR ALGUM MOTIVO O SCRIPT NÃO IDENTIFICA A IMAGEM QUE EU TO INCLUINDO, NÃO IMPORTA O QUE EU FAÇA, mas pra vc pode dar certo....


Salvou com extensao PNG maiusculo? Se for é por isso, o script só trata minusculo.

**Comment by jorgemtg** [comment]
> > @edermania e @Novaisxd o teu problema esta relacionado com o botão de go_to_work... Pode ver que ele encontra os herois com barra verde, mas não encontra botão algum... Eu estava com esse problema e resolvi primeiro de uma forma:
> > ```
> > * arquivo config.yaml, tu precisa alterar o padrão toleravel pelo bot de precisão, o padrão é 0.9 (90% de eficacia), aqui funcionou colocando pra 0.7... POREM TIVE PROBLEMA DE COMPORTAMENTO....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Depois tentei o seguinte:
> > ```
> > * alterar o arquivo de evidencia correspondente a imagem do go_to_work, nesse caso vc precisa tirar uma print semelhante a da imagem que vá ser subsituida (formato obrigatorio .png)... PRA MIM NÃO DEU CERTO, POR ALGUM MOTIVO O SCRIPT NÃO IDENTIFICA A IMAGEM QUE EU TO INCLUINDO, NÃO IMPORTA O QUE EU FAÇA, mas pra vc pode dar certo....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > E por último e que esta funcionando no momento:
> > ```
> > * mantive tudo identico, porém alterei a resolução do meu monitor (que é ultrawide), pra 1920x1080 (monitor padrão) e até o momento tudo esta indo conforme esperado...
> > ```
> 
> Exatamente, por isso falei para colocar em INGLÊS, porque o botão work muda de acordo com o idioma.

Mas no caso o @Novaisxd falou que já tentou em ingles e nada

**Comment by jorgemtg** [comment]
> Salvou com extensao PNG maiusculo? Se for é por isso, o script só trata minusculo.

Sinceramente não me recordo, até pq tirei a print e salvei como o padrão que o proprio windows passa... Talvez possa ser isso, mais tarde eu vou tentar isso do maiusculo, vlw pela dica... xD

**Comment by fguide** [comment]
Botao em en:
![image](https://user-images.githubusercontent.com/95459411/147386752-cd03cb03-e1bf-4080-b61b-66ed73216a2d.png)
Botao em pt:
![image](https://user-images.githubusercontent.com/95459411/147386760-ff96ba8f-b02f-4ce9-aa58-da8a8d05049e.png)

Para ilustrar a diferença, é bom verificar se o mesmo acontece em sua maquina e alterar o botao de acordo.

Eu nao tenho como testar em windows, porém aconselho a verificar configurações de vídeo, fontes de windows faltando?, resolução, zoom de navegador, scaling, etc.

**Comment by Novaisxd** [comment]
Vou tentar mudar a resolução do computador obg

**Comment by jorgemtg** [comment]
> > ```
> 
> Salvou com extensao PNG maiusculo? Se for é por isso, o script só trata minusculo.

Puts, foi isso mesmo @fguid, depois vou tentar corrigir isso pra usar na resoluação padrão do meu monitor e reporto!

![image](https://user-images.githubusercontent.com/96638071/147386824-23060b41-1374-4899-8c02-6204ce0b7043.png)

**Comment by Novaisxd** [comment]
Ja tenho a imagem png em minúsculo e o meu monitor ja era 1920x1080, continua o mesmo erro tho, ...
,

**Comment by fguide** [comment]
> > > 
> > 
> > 
> > Salvou com extensao PNG maiusculo? Se for é por isso, o script só trata minusculo.
> 
> Puts, foi isso mesmo @fguid, depois vou tentar corrigir isso pra usar na resoluação padrão do meu monitor e reporto!
> 
> ![image](https://user-images.githubusercontent.com/96638071/147386824-23060b41-1374-4899-8c02-6204ce0b7043.png)

Esse botao parece estar no padrao portugues, se for o ingles talvez tenha alguma fonte faltando em seu pc, veja o exemplo que coloquei acima.

**Comment by Novaisxd** [comment]
Esse é o meu 
![image](https://user-images.githubusercontent.com/96638387/147386965-4367dcdf-3534-4d41-9364-e529ddfe408d.png)

**Comment by fguide** [comment]
> Esse é o meu ![image](https://user-images.githubusercontent.com/96638387/147386965-4367dcdf-3534-4d41-9364-e529ddfe408d.png)

Parece meio diferente do que está no repositorio, tente com o oficial, se nao der faça um print novo do seu navegador e coloque no lugar do go-work.png

![image](https://user-images.githubusercontent.com/95459411/147387028-09f2a631-3220-4f70-a5df-bd266d4da187.png)

**Comment by Novaisxd** [comment]
amigo, eu tentei tipo 10 screenshots diferentes, mas vou tentar outra vez.

**Comment by fguide** [comment]
@Novaisxd 

> > O problema mantém , e eu tenho o site em Inglês. Se acharem algum fix era MT bom
> 
> O seu tb dá 0 buttons detected igual da imagem acima?

Ele detecta o botao? É bom ter a informacao porque dai podemos imaginar qual o problema, pode ser algo relacionado ao click do python, mas é bom ter certeza de que o botao é detectado

**Comment by Novaisxd** [comment]
O que acontece é ele reconhece os herois  que estao com energia suficiente para ir trabalhar, clicka neles e dps fica com o rato mt perto do botao work e parece me que faz o click,, mas precisaria de estar um bcd a direita para estar de facto no botao work.
Exatamente como mostra a print 
![image](https://user-images.githubusercontent.com/96638387/147387474-f1d0cf06-2624-4537-bc6b-80be88160509.png)

**Comment by Novaisxd** [comment]
acabei de perceber que a print n mostra o cursor, mas é entre o lado direito da barra e o botao work,

**Comment by fguide** [comment]
Ele clica antes do botao work pelo que entendi, certo? Teste a modificação abaixo, não tenho certeza se resolve porque não testei:

Edite o arquivo index.py
Modifique a linha 270 de:
>offset = 130
para:
>offset = 140
Salve  o arquivo index.py

Em teoria isso move o offset do clique em +10px, entao se ainda estiver fora do botao voce pode ir adicionando até o clique funcionar.

**Comment by Novaisxd** [comment]
CARA FUNCIONOU , EU TE AMO

**Comment by Novaisxd** [comment]
Novo update, acho que isto n está a descer até ao fim dos heróis, para após alguns

**Comment by Novaisxd** [comment]
Concluo quue faltaria descer uma vez para olhar para todos os heróis, o problema do work desapareceu

**Comment by fguide** [comment]
Dentro do arquivo config.yaml tem a opcao scroll_attemps para ajustar isso

**Comment by Novaisxd** [comment]
Pode ensinar como mexer nisso, nunca tive programação e é a primeira vez que mexo em Python , nem sei o que é um ficheiro yalm

**Comment by edermania** [comment]
Gente expresso aqui meus agradecimentos. No meu caso, fiz só a alteração de idioma de **Pt** para **En** e tudo funcionol normalmento. O bot reconheu todos os padrões e executou perfeitamento. Grato a todos!! =D

**Comment by Novaisxd** [comment]
@fguide percebi que agora o erro que tenho, nao é o numero de scrolls la, o que acontece é o bot verifica o numero de barras verdes 1 vez no inicio dps da um scroll verifica outra vez e ai em vez de continuar neste ciclo ate que o numero de scrolls se esgote ele n desce mais e verifica todas as vezes restantes neste lugar, ficando a maior parte dos herois por verificar

**Comment by Novaisxd** [comment]
@fguide resumindo, ele n desce para verificar se existem mais herois prontos a trabalhar, verifica todas as vezes no mesmo lugar e é isso

**Comment by Novaisxd** [comment]
@fguide acabei de perceber que se eu deslizar um bocado a barra dos herois de modo a que o bot n começe a ver no incio da lista, ele funciona sem problemas, n sei o que pode estar a causar isto

**Comment by fguide** [comment]
@Novaisxd 

Pelos seus comentarios fiz um teste e encontrei mesmo um bug com scroll quando manda +20 herois a trabalhar, criei um PR que trata isso, se quiser testar: #482

**Comment by Juninhox13** [comment]
esse 482 funciona, mas eu queria saber qual linha exatamente orienta o clique no botao. se puderem me informar
