### ISSUE TITLE
Problema no macbook air M1

### ISSUE THREAD

**Issue by rcomparim** [mpcabete/bombcrypto-bot#469]
instalei tudo certinho o pip, depois na hora de executar python 3 index.py aparece isso : rcomparim@MacBook-Air-de-Rafael bomb % python3 index.py          
  File "/Users/rcomparim/Desktop/bomb/index.py", line 2
    /cd pip
    ^
SyntaxError: invalid syntax

**Comment by fguide** [comment]
Acho que vc digitou lgo errado amigo, esse erro nao esta no index.py, veja se vc digitou o comando certinho.

**Comment by rcomparim** [comment]
passa seu whatsapp, agora deu certo, aparece o gatinho e os comandos sendo executados, mas nao executa no jogo, o que sera, ja alterei o zoom!

**Comment by fguide** [comment]
Não tenho whatsapp, só uso o tox pra comunicação, se quiser pode chamar lá:

>7B9B32731CFC2F0F67B6668EDAD56746301F32EE752A89035DFE3A8115BB1B4DC101C92559C5`

Tenta ver o #387, pode ser que ajude no seu caso

**Comment by rcomparim** [comment]
nao acha os jogadores minha resoluçao é 2560x1600 no mac e nao consigo mudar
