### ISSUE TITLE
Problem Update - I'll pay you

### ISSUE THREAD

**Issue by eztzez** [mpcabete/bombcrypto-bot#47]
Hey brother!
First, congratulations on the BOT. Very good, it's helping me a lot.
I just want the update to send the heroes to House.
can I solve this problem?
I'll pay you of course, just get in touch with me
Whatssap: **00212666195500**

**Comment by mpcabete** [comment]
Hey ez, I am already working on it! 
It is not 100% yet but you can check it out [here](https://github.com/mpcabete/bombcrypto-bot/tree/home-feature)
Let me know if you notice any issues.
