### ISSUE TITLE
scrolling infinito 

### ISSUE THREAD

**Issue by Curseeeed** [mpcabete/bombcrypto-bot#470]
to com um problema scrolling infinito, o bot coloca os bonecos que estão com barra verde para trabalhar mas mesmo assim ele continua dando scroll como se tivesse mais bonecos e fica nisso e depois de um tempo ele começar a tentar dar scroll fora da pagina de personagens, tem alguma solução pra isso?

**Comment by fguide** [comment]
Eu nao tive esse problema, verifica no config.yaml se o parametro scroll_attemps está muito diferente do padrao. Resolucao de tela, quantidade de monitores, etc, tb influenciam.

**Comment by Curseeeed** [comment]
> Eu nao tive esse problema, verifica no config.yaml se o parametro scroll_attemps está muito diferente do padrao. Resolucao de tela, quantidade de monitores, etc, tb influenciam.

Eu não mexi em nada tlgdo isso q é foda, eu rodei no note e funcionou de boa mas no Pc ainda tá com esse problema

**Comment by jorgemtg** [comment]
Ta dando isso aqui:  Too many hero clicks, try to increase the go_to_work_btn threshold←[0m
Traceback (most recent call last):

**Comment by jorgemtg** [comment]
Começou agora a noite, pq de tarde e de manhã tava funcionando

**Comment by Curseeeed** [comment]
Okay, o problema tava no navegador, mudei para o Chrome e está rodando de forma normal agr

**Comment by Curseeeed** [comment]
> Ta dando isso aqui:  Too many hero clicks, try to increase the go_to_work_btn threshold←[0m
> Traceback (most recent call last):
> 

Não faço ideia de como te ajudar amigo, desculpe :/

**Comment by fguide** [comment]
> Ta dando isso aqui: Too many hero clicks, try to increase the go_to_work_btn threshold←[0m Traceback (most recent call last):

@jorgemtg 

Baixa a atualização de hoje que resolve esse seu problema.
