### ISSUE TITLE
dicas para criar VM no google cloud?

### ISSUE THREAD

**Issue by kerferber** [mpcabete/bombcrypto-bot#471]
Pessoal, criei uma conta free no google cloud e consegui instanciar um ubuntu mas não passei disso...

Consegui fazer rodar interface gráfica, instalei google chrome mas nem sequer consegui executar.. parece ter algo corrompido, desinstalei e instalei novamente e tudo igual.. o chrome nem abre..... enfim... sou newbie nessa área de VM e linux....

Alguma dica pra rodar o bomb e o bot na VM do google cloud? Algum tutorial?

Agradeço

**Comment by fguide** [comment]
Podemos ajudar, mas precisamos de mais info, tente rodar o chrome pelo terminal, dai ele vai mostrar mensagens de erro e o porque nao abre.

Não tem segredo, se tem interface grafica instalada, python e consegue acessar ele deve rodar normalmente

**Comment by jhonsstn** [comment]
> Pessoal, criei uma conta free no google cloud e consegui instanciar um ubuntu mas não passei disso...
> 
> Consegui fazer rodar interface gráfica, instalei google chrome mas nem sequer consegui executar.. parece ter algo corrompido, desinstalei e instalei novamente e tudo igual.. o chrome nem abre..... enfim... sou newbie nessa área de VM e linux....
> 
> Alguma dica pra rodar o bomb e o bot na VM do google cloud? Algum tutorial?
> 
> Agradeço
> 
> OBS: a propósito, realmente estou faz

Para ficar mais fácil, é só seguir isso aqui a risca, Nao tem erro.

https://cloud.google.com/architecture/chrome-desktop-remote-on-compute-engine

**Comment by kerferber** [comment]
Agradeço as duas dicas. Vou testá-las amanhã. Qualquer coisa retorno aqui. Obrigado

**Comment by kerferber** [comment]
Primeiramente agradeço pelo artigo @jhonsstn 

Consegui instalar o Ubuntu, o Chrome, instalei o Python versão 3.9. 
Baixei e descompactei o bot, instalei o PIP no Ubuntu.

Até ai tudo bem...

Porém ao tentar instalar os requirements, o sistema aparentemente travou após instalar algumas bibliotecas...
Parou com a seguinte mensagem no terminal: "Running setup.py bdist_wheel for opencv-python ..."

Já fiz shutdown e reinicializei a VM e novamente não sai desta etapa. Já tá ha mais de 15 minutos...
Não está completamente travado pois as barrinhas após esta frase estão se movendo... (__ .... \ ..... | .... / .... __ ) Mas não conclui a instalação..

Mais alguma dica, por favor?
Vou anexar um print do prompt do ubuntu...
![promtp travado ubuntu](https://user-images.githubusercontent.com/95573625/147389905-1048da93-1989-4842-a712-a88fd0e003e1.JPG)

OBS: Estou utilizando a seguinte configuração:
Tipo de máquina: n1-standard-4 (4 vCPUs, 15 GB de memória)
Plataforma de CPU: Intel Haswell
SO: Ubuntu

Desde já agradeço novamente

**Comment by kerferber** [comment]
Consegui resolver. Vou deixar a solução caso alguém tenha a mesma dúvida...

Bastou atualizar o pip:

pip3 install --upgrade setuptools pip
pip3 install opencv-python

**Comment by jhonsstn** [comment]
Opa, que beleza @kerferber 

Esta rodando quantas contas nessa VM? Esta liso?

**Comment by kerferber** [comment]
Estou TENTANDO rodar minha única conta kkkk

Ainda não consegui..

Agora apareceu: "you must install tkinter on linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev"

Mas ao rodar esse comando, o 'sudo' pede uma senha e dá uma mensagem de erro: "meu_nome_de_usuário is not in the sudoers file. This incident will be repored."

Já tentei diversas sugestões do stackoverflow, mas sem sucesso até agora.... :(

**Comment by fguide** [comment]
> Estou TENTANDO rodar minha única conta kkkk
> 
> Ainda não consegui..
> 
> Agora apareceu: "you must install tkinter on linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev"
> 
> Mas ao rodar esse comando, o 'sudo' pede uma senha e dá uma mensagem de erro: "meu_nome_de_usuário is not in the sudoers file. This incident will be repored."
> 
> Já tentei diversas sugestões do stackoverflow, mas sem sucesso até agora.... :(
> 
> EDIT: Consegui acessar o ROOT através do menu SSH > Abrir na janela do navegador.
> 
> O Bot está rodando. Vou testar no game

Aproveita e adiciona seu usuário ao sudoers, não é recomendável usar sessao ssh com root direto:

https://www.vivaolinux.com.br/dica/Adicionando-seu-usuario-no-arquivo-sudoers

**Comment by kerferber** [comment]
Obrigado. Consegui! Que alegria 😅

Eu tava bem incomodado por ter q deixar meu notebook ligado 24hrs por dia. Problema resolvido. Bot rodando liso na VM.

Obrigado pela ajuda @jhonsstn e @fguide 

Mais algumas dúvidas:
1 - Sobre o período gratuito, não é exatamente 3 meses, pelo que entendi, é um valor em crédito que a VM consome de acordo com a potência configurada. Estou certo?

2- Após o término desse crédito automaticamente será debitado em meu cartão de crédito ou vou precisar contratar/autorizar? Alguém sabe?

3 - Pergunto pois Após o período gratuito, pretendo utilizar outras contas do Gmail que possuo. É possível e viável? Será que dá pra migrar toda a Vm para outra conta ou preciso reinstalar tudo?

4- Por fim, tem algum local pra acompanhar quantos créditos já utilizei e quanto ainda possuo? Não localizei esta opção.

Agradeço novamente

**Comment by fguide** [comment]
@kerferber Vou ficar te devendo as respostas sobre preço/cobrança do GCP, eu não uso a plataforma. Em relação a pergunta: 
>Será que dá pra migrar toda a Vm para outra conta ou preciso reinstalar tudo?

Acredito que dê pra exportar sim, porém deve ser por meio de imagens e não ficaria muito viável. Eu recomendo que você acesse com algum software, WinSCP por exemplo, a maquina e faça o backup da pasta do bot e da pasta das configurações do navegador, a do firefox por exemplo fica em: /home/usuario/.mozilla (fica oculta)

Só tome cuidado com as conifgs do navegador, pois o metamask está "instalado e configurado" lá, ainda é necessário ter sua senha para utilizar, mesmo assim vale o cuidado.

**Comment by biezus** [comment]
Sobre rodar em linux na google cloud, quando fecha o acesso remoto o bot não consegue continuar sozinho né? (lembro de ter lido isso a tempos) Tem como fazer ele continuar para eu não ter que deixar meu pc ligado acessando remotamente?

**Comment by kerferber** [comment]
> Sobre rodar em linux na google cloud, quando fecha o acesso remoto o bot não consegue continuar sozinho né? (lembro de ter lido isso a tempos) Tem como fazer ele continuar para eu não ter que deixar meu pc ligado acessando remotamente?

Lembro de ter lido algo nesse sentido também, mas não está acontecendo aqui.
Apenas desativei a proteção de tela, conforme o artigo que o @jhonsstn citou mais acima.

Está há quase 24horas rodando sem parar. Acesso de vez em quando através do Chrome Remote Desktop, tanto no PC como no celular e sempre que vejo ganhei mais algumas moedinhas kkk

**Comment by fguide** [comment]
> Sobre rodar em linux na google cloud, quando fecha o acesso remoto o bot não consegue continuar sozinho né? (lembro de ter lido isso a tempos) Tem como fazer ele continuar para eu não ter que deixar meu pc ligado acessando remotamente?

Não, depois de iniciado o X ele continua, só mesmo e tiver protecao de tela, etc. Quem tem esse problema é o windows acessado via RDP.

**Comment by nicolobi** [comment]
> > À propos de l'exécution sous Linux sur Google Cloud, lorsque vous fermez l'accès à distance, le bot ne peut pas continuer seul, n'est-ce pas ? (Je me souviens avoir lu ceci il y a quelque temps) Existe-t-il un moyen de le faire continuer afin que je n'aie pas à laisser mon PC allumé, y accéder à distance?
> 
> Non, après avoir démarré X, cela continue, seulement s'il a un économiseur d'écran, etc. Qui a ce problème, ce sont les fenêtres accessibles via RDP.

I have the same.. If someone have the solution...

**Comment by BETINBR** [comment]
> Estou TENTANDO rodar minha única conta kkkk
> 
> Ainda não consegui..
> 
> Agora apareceu: "you must install tkinter on linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev"
> 
> Mas ao rodar esse comando, o 'sudo' pede uma senha e dá uma mensagem de erro: "meu_nome_de_usuário is not in the sudoers file. This incident will be repored."
> 
> Já tentei diversas sugestões do stackoverflow, mas sem sucesso até agora.... :(
> 
> EDIT: Consegui acessar o ROOT através do menu SSH > Abrir na janela do navegador.
> 
> O Bot está rodando. Vou testar no game

OLA, ESTOU COM ESSE MSM PROBLEMA ... OQ VC FEZ PARA RESOLVER

**Comment by kerferber** [comment]
> 

EDIT: Consegui acessar o ROOT através do menu SSH > Abrir na janela do navegador.

**Comment by kerferber** [comment]
> > Estou TENTANDO rodar minha única conta kkkk
> > Ainda não consegui..
> > Agora apareceu: "you must install tkinter on linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev"
> > Mas ao rodar esse comando, o 'sudo' pede uma senha e dá uma mensagem de erro: "meu_nome_de_usuário is not in the sudoers file. This incident will be repored."
> > Já tentei diversas sugestões do stackoverflow, mas sem sucesso até agora.... :(
> > EDIT: Consegui acessar o ROOT através do menu SSH > Abrir na janela do navegador.
> > O Bot está rodando. Vou testar no game
> 
> OLA, ESTOU COM ESSE MSM PROBLEMA ... OQ VC FEZ PARA RESOLVER

EDIT: Consegui acessar o ROOT através do menu SSH > Abrir na janela do navegador.

**Comment by KorlashKun** [comment]
estou com esse erro alguem sabe resolver ? séra q é pq o sistema é o debian ?
![image](https://user-images.githubusercontent.com/78668048/147954548-d0e57831-d5f6-496f-873d-d28ca041cc4c.png)
