### ISSUE TITLE
Mouse vai para posição errada

### ISSUE THREAD

**Issue by JuanCollin7** [mpcabete/bombcrypto-bot#473]
Testando aqui percebi que depois de ajustar as imagens o mouse vai sempre pra uma posição errada, talvez sempre um pouco abaixo e um pouco pra direita. Estou utilizando um mac. 

Alguém teve esse problema? Como eu poderia resolver?

**Comment by fguide** [comment]
Tente ver o básico, resolucao da tela, idioma do jogo, navegador, etc, se está detectando e movendo o funcionamento está "correto" mas está falhando em algo do seu cenário

**Comment by JuanCollin7** [comment]
Pois é, achei meio bizarro isso, pq se ele detecta, deveria ir pra coordenada certa kkkk Tava usando o chrome pro teste…

Como vejo esse lance da resolução da tela?

**Comment by fguide** [comment]
Entao, tem um problema similar no #468, eu sugerio um ajuste no final das respostas, de uma lida la, talvez seja seu caso.
