### ISSUE TITLE
Solução pra Trezor

### ISSUE THREAD

**Issue by VitotEPB** [mpcabete/bombcrypto-bot#475]
Bom dia; estava pensando em uma solução pras contas protegidas por hardwallet que ficam impossibilitadas de re-logar automaticamente. Você pode me ajudar a desenvolver um sistema que emita um aviso sonoro ao levar disconnect? Agradeço desde já!

**Comment by fguide** [comment]
Se você tiver noções de programação pode usar o modelo do commit abaixo que emitia um alerta sonoro no captcha, tem alternativas para telegram tb, etc, só dar uma pesquisada aí nos tópicos:

https://github.com/mpcabete/bombcrypto-bot/commit/5e2e24c74b79cd48951b6c472d8bcfedf2f07c50

**Comment by VitotEPB** [comment]
Estou disposto a remunerar quem tiver condições para tal. Algum programador on-line? Deixem seus #discord

**Comment by kerferber** [comment]
> Estou disposto a remunerar quem tiver condições para tal. Algum programador on-line? Deixem seus #discord

olá amigo, dá uma olhada neste issue que eu abri. #189
Seguindo dá pra implementar um envio de mensagem por telegram, basta você chamar a função sempre que o bot tentar logar... Não é difícil...

#189

**Comment by Nucito** [comment]
> Estou disposto a remunerar quem tiver condições para tal. Algum programador on-line? Deixem seus #discord

Email: nucito@protonmail.com
Discod: Cartman#6666
