### ISSUE TITLE
Bot inicia mas nao faz nada!

### ISSUE THREAD

**Issue by Lukakira** [mpcabete/bombcrypto-bot#476]
Bot inicia, porém ele nao executa nenhuma funçao, ja desinstalei varias vezes, e refiz todo processo. Parece que nao ta indentificando nenhuma imagem, talvez nao seja compativel com windows 11??

**Comment by TiagoSilva-dev** [comment]
Aqui no win 11 ta funcionando de boas , porem no linux nao esta rodando o bot inicia mas nao faz nada . ja verificou a versao do seu python ?

**Comment by TiagoSilva-dev** [comment]
achei a solução aqui para o meu caso , diminui o zoom da pagina , no meu caso no 80% deu certo

**Comment by Lukakira** [comment]
> achei a solução aqui para o meu caso , diminui o zoom da pagina , no meu caso no 80% deu certo

Cara muito obrigado! era isso mesmo, resolveu meu problema

**Comment by Xelepinho** [comment]
Fala rapazeada! Estou com o mesmo problema, já diminui o zoom da tela, aumentei, mas o mouse não se move. Ta rodando normalmente o cmd, porém, no notebook, não funciona por nada!

**Comment by TiagoSilva-dev** [comment]
> Fala rapazeada! Estou com o mesmo problema, já diminui o zoom da tela, aumentei, mas o mouse não se move. Ta rodando normalmente o cmd, porém, no notebook, não funciona por nada!

testou em outros zoom ?
