### ISSUE TITLE
Erro no click do botao "work"

### ISSUE THREAD

**Issue by joaovictor4444** [mpcabete/bombcrypto-bot#477]
o bot ta recconhecendo tudo certo, mas ta clicando a esquerda do botao de work e nao coloca nenhum coneco para trabalhar

**Comment by fguide** [comment]
#468 veja a parte de alterar o offset.

**Comment by diogosilvadossantos** [comment]
eu fiz uma coisa e resolveu, eu usava o jogo em português só foi eu botar para inglês de volta e resolveu.
