### ISSUE TITLE
Bot para para duas contas

### ISSUE THREAD

**Issue by pedrox97** [mpcabete/bombcrypto-bot#478]
è possivel por o bot a trabalhar em duas contas com o ecra dividido em dois?

**Comment by CorreiaDeveloper** [comment]
Acredito que ja tenha uma solução pra isso viu amigo, da uma pesquisa nas perguntas que ja foram fechadas aqui

**Comment by JuanCollin7** [comment]
Também to nessas, até agora o maximo que vi foi duas contas no mesmo navegador e nem sei se funciona. Queria saber dessa com dois navegadores diferentes com tela dividida também…
