### ISSUE TITLE
Bot para MULTI-ACCOUNT não esta funcionando direito.

### ISSUE THREAD

**Issue by far0fa** [mpcabete/bombcrypto-bot#479]
Olá pessoal, recentemente vi que tem um bot aqui que da pra usar para multi account e ele funciona legal, porém após uns updates do game, verifiquei que os personagens estavam gastando stamina porém nao dava dano nos baús, isso porque a tecla fica em segundo plano, ou seja, ela sempre tem que estar aparecendo, e o bot de multi-account nao funciona desta forma.

Alguém tem alguma solução?

**Comment by fguide** [comment]
#463
