### ISSUE TITLE
Resolução da Tela

### ISSUE THREAD

**Issue by careduest** [mpcabete/bombcrypto-bot#48]
Bom Dia,

Afim de ajudar e perguntar ao nosso magistral, especial e benevolente DEV, as resoluções que funcionam determinadas coisas do bot!

Ex:

Aqui o bot so funciona 100% em resolução 800x600. Em outras resoluções faz tudo mas se cai não se reconecta!

Tentei muda as config possíveis mas nada no meu caso ajudou.

Vlw, pela iniciativa e mandei la na carteira minha contribuição.

**Comment by matheusgm0** [comment]
voce tem apenas 1 monitor? seu windows esta em 100%?

**Comment by mvpalves** [comment]
Aqui eu uso 1152x864 e funciona perfeito

**Comment by careduest** [comment]
Sim um monitor, 100% zoom!

**Comment by careduest** [comment]
Pessoal, faz mais muitos teste e aqui para mim so funciona 100% em 800x600 e 1152x864, se nao for nessas resolução nao reconecta, agora nas demais resoluções funciona tudo menos reconexão. Veja se faz sentido para mais alguem!

**Comment by mpcabete** [comment]
Salve careduest, muuito obrigado pela contribuição!
Vc pode resolver esse problema substituindo as imagens da pasta targets com imagens q vc mesmo salvar do seu PC. É só substituir as que estiverem dando problema com uma com o mesmo nome e o bot deve voltar a funcionar!

**Comment by careduest** [comment]
Caraca que top, então deixa eu explodir esse recurso, por exemplo se quiser que a ele selecione barras mais cheias da atual escolher uma imagem com a barra mais cheia e ele começara a escolher para iniciar barras com aquele tamanho pelo menos. entendi certo?

> Salve careduest, muuito obrigado pela contribuição! Vc pode resolver esse problema substituindo as imagens da pasta targets com imagens q vc mesmo salvar do seu PC. É só substituir as que estiverem dando problema com uma com o mesmo nome e o bot deve voltar a funcionar!

**Comment by cristhianbreunig** [comment]
> Caraca que top, então deixa eu explodir esse recurso, por exemplo se quiser que a ele selecione barras mais cheias da atual escolher uma imagem com a barra mais cheia e ele começara a escolher para iniciar barras com aquele tamanho pelo menos. entendi certo?
> 
> Mais um complemento a imagem por exemplo do assinar vc pegou imagem em ingles "Sign" se o pc tiver em protugues pode dar erro tb, e bom quem tiver erros fazer essas checagem das imagens no meu, mesmo sendo em portugues e nao mudando a imagem naquela resolução funciona tudo! 800x600 ou 1152x864
> 
> > Salve careduest, muuito obrigado pela contribuição! Vc pode resolver esse problema substituindo as imagens da pasta targets com imagens q vc mesmo salvar do seu PC. É só substituir as que estiverem dando problema com uma com o mesmo nome e o bot deve voltar a funcionar!

Oi, estou tentando trabalhar nisso aqui no meu ambiente local.

Pensei em substituir a configuração `only_click_heroes_with_green_bar` para `select_heroes_mode` ou algo do tipo, a ideia daí é verificar o modo que o usuário definiu, pensei em (_full, green, any_).

Caso **full** => Seleciona somente os heróis que estão com a barra cheia
Caso **green** => Seleciona somente os heróis que estão com a barra verde (_meia stamina ou mais_)
Caso **any** => Seleciona todos os heróis (_por ordem que aparecem_)

O que acha disso @mpcabete ?

Se concordar que é uma funcionalidade útil, me avisa, que estou enfrentando alguns problemas para identificar a imagem da barra cheia.

**Comment by mpcabete** [comment]
@careduest mais ou menos, acho que talvez se você mudar pra imagem da barra cheia não funcione muito bem. Teria que fazer uns testes. Talvez uma opçao melhor seja tirar um print da parte da esquerda da barra. Eu desliguei meu bot pra alguma barra encher e vou fazer uns testes. Dai aviso vcs do que descobrir. Dai dps q tiver funcionando certinho podemos colocar na config sim @cristhianbreunig

**Comment by cristhianbreunig** [comment]
> @careduest mais ou menos, acho que talvez se você mudar pra imagem da barra cheia não funcione muito bem. Teria que fazer uns testes. Talvez uma opçao melhor seja tirar um print da parte da direita da barra cheia. Eu desliguei meu bot pra alguma barra encher e vou fazer uns testes. Dai aviso vcs do que descobrir. Dai dps q tiver funcionando certinho podemos colocar na config sim @cristhianbreunig

Deixei alguns heróis descansando aqui, assim que possível vou testar os ajustes que fiz, para ver se identifica certinho a barra cheia e se funciona em conjunto com a configuração.

**Comment by cristhianbreunig** [comment]
> @careduest mais ou menos, acho que talvez se você mudar pra imagem da barra cheia não funcione muito bem. Teria que fazer uns testes. Talvez uma opçao melhor seja tirar um print da parte da direita da barra cheia. Eu desliguei meu bot pra alguma barra encher e vou fazer uns testes. Dai aviso vcs do que descobrir. Dai dps q tiver funcionando certinho podemos colocar na config sim @cristhianbreunig

Oi, somente para atualizar, realizei alguns testes aqui e acredito que está funcionando 100%, daqui a pouco vou mandar um pull request.
