### ISSUE TITLE
Bot agora oficialmente legalizado!!!!

### ISSUE THREAD

**Issue by pegchargue** [mpcabete/bombcrypto-bot#481]
Agora que está liberada a utilização do bot posso testar outraa opções como PC virtual, mas gostaria de saber se: utilizar o virtual é melhor que o físico e se o bot vai rodar redondinho como funciona no computador físico...????

**Comment by fguide** [comment]
> Agora que está liberada a utilização do bot posso testar outraa opções como PC virtual, mas gostaria de saber se: utilizar o virtual é melhor que o físico e se o bot vai rodar redondinho como funciona no computador físico...????

Funciona bem, depende das configurações da VM também, tem vários tópicos sobre VM e similares aqui.

Melhor ou pior vai do seu uso, a maor vantagem é que não vai deixar o computador "preso" com o bot, pode deixar a VM em segundo plano e usar o computador para outras coisas.

**Comment by Hajsilveira** [comment]
Procurei bastante mas não achei, onde você encontrou informação sobre a legalização de bot?

**Comment by pegchargue** [comment]
Vai lá no discord deles e pergunta... Está liberado autoclicks, pois não faz alterações dentro do jogo!!!

**Comment by pegchargue** [comment]
> Procurei bastante mas não achei, onde você encontrou informação sobre a legalização de bot?

Vai lá no discord deles e pergunta... Está liberado autoclicks, pois não faz alterações dentro do jogo!!!
