### ISSUE TITLE
bot manda o mouse direto para o scroll do navegador

### ISSUE THREAD

**Issue by FrogxD** [mpcabete/bombcrypto-bot#483]
bot manda o mouse direto para o scroll do navegador, mesmo mudando as imagens, em qualquer etapa ele sempre manda o mouse pro maximo à direita, arrastando pra cima e pra baixo as vezes.

**Comment by fguide** [comment]
#482 talvez ajude

**Comment by FrogxD** [comment]
> #482 talvez ajude

mudei o arquivo aqui mas continua igual, alguma ideia?

**Comment by fguide** [comment]
Não seria resolução da tela? Eu nunca vi reportarem por aqui esse comportamento, pode ser por resolução, zoom do navegador, multiplas telas.

Poste as configurações que está usando, navegador, resolucao, etc

**Comment by FrogxD** [comment]
> Não seria resolução da tela? Eu nunca vi reportarem por aqui esse comportamento, pode ser por resolução, zoom do navegador, multiplas telas.
> 
> Poste as configurações que está usando, navegador, resolucao, etc

cara acabei de tentar desabilitar o segundo monitor e agora funciona normal, só que ele fica tentando mandar os bonecos trabalhar infinito, vou testar depois quando as energias ficarem vermelhas

**Comment by wenked** [comment]
Aqui fica assim tbm , tenho 2 monitores os 2 na resolução 1920x1080
