### ISSUE TITLE
Usei e fui escamado

### ISSUE THREAD

**Issue by cleisonmsilva** [mpcabete/bombcrypto-bot#484]
Usei e fui escamado para carteira 0xe23e1be7c918ccebe2677b29423b24f178eb8e88 
Transaction Hash: 0xd96143fe00ef07188672217827a9fa12d2c559f742e466bf83331a9e87acd801

**Comment by backslash-f** [comment]
Foi "escamado" porque é mongolão, não tem nada a ver com o bot.

**Comment by fguide** [comment]
Realmente não tem relação ao bot, verifique seu computador, talvez o crack do seu jogo pirateado, ou do windows, que tenha feito isso.

**Comment by jotaper0x** [comment]
Cara, sinto muito, mas não foi por conta do bot... peça pra algum conhecido que manje de programação e ele vai te mostrar que está limpo. Ou eh seu pc zoado, ou vc baixou outro bot alem desse.

**Comment by AllanHBC** [comment]
Usou e foi scamado. é uma afirmativa que pode ser verdadeira.
Só não é verdadeiro se tu disser que foi scamado POR CAUSA DESSE Bot.... ta cheio de gente no discord oficial falando que foi roubado mas tudo pq clicou no que não devia por ai....

**Comment by Yumiizera** [comment]
Foi scam por algum site que você acessou. O bot está limpo e é de código aberto, e se por ventura você pegou o bot POR AMIGO, OU POR OUTRO SITE, a responsabilidade e a deficiência de ter sido escamado é totalmente sua.

**Comment by HeeyMan** [comment]
KKKKKKKKKKKKKKKKKKK escama de peixe air? :D

**Comment by ricardofernandess** [comment]
Tem uma issue aberta de um cara com dificuldade de usar o bot mas a mensagem de início da execução do bot é diferente. Duvido nada estarem modificando esse bot e vendendo por ai com alguma alteração maliciosa

**Comment by cleisonmsilva** [comment]
Baixei direto do GitHub, segui o manual instalando o python pelo Windows store. Estava funcionando o dia inteiro mas a noite teve o saque, se quiser posso mandar o arquivo do jeito que está para vc verificarem se teve alteração.
Rede binance: Txhash 0xd96143fe00ef07188672217827a9fa12d2c559f742e466bf83331a9e87acd801

Se puder me ajudar a entender, pois estou ate formatando a maq, sendo que adorei o projeto e estava até conversando com amigo que seria muito importante colaborar com o projeto, mas foram quase mil reais  e estou muito abalado.



Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: Ricardo Fernandes de Moraes Júnior ***@***.***>
Enviado: Sunday, December 26, 2021 5:28:05 PM
Para: mpcabete/bombcrypto-bot ***@***.***>
Cc: cleisonmsilva ***@***.***>; Author ***@***.***>
Assunto: Re: [mpcabete/bombcrypto-bot] Usei e fui escamado (Issue #484)


Tem uma issue aberta de um cara com dificuldade de usar o bot mas a mensagem de início da execução do bot é diferente. Duvido nada estarem modificando esse bot e vendendo por ai com alguma alteração maliciosa

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmpcabete%2Fbombcrypto-bot%2Fissues%2F484%23issuecomment-1001238512&data=04%7C01%7C%7C8bdb7ede300b49ae894408d9c8ae3922%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761472881015222%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WRS4mK7fmzHf6TJiqvv7DP%2FoEsi%2Fl4xpf%2Bgx0ASjfuE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKVEITXWBNMOOVXPHFSWCDLUS53FLANCNFSM5KY3TMEQ&data=04%7C01%7C%7C8bdb7ede300b49ae894408d9c8ae3922%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761472881025179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CgjqBux73yPyOcXOphwTDruaTHW3b7Lh4GBjwMZbDnY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8bdb7ede300b49ae894408d9c8ae3922%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761472881025179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PttSyIxuchk8clIYisxuT%2Br79vcNbVSPNj%2B3ClOk9iM%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8bdb7ede300b49ae894408d9c8ae3922%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761472881035136%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=I%2BXPhENIea3QaXIUT37dDLFgy21DyPWN5uH3HJ5YkZc%3D&reserved=0>.

**Comment by fguide** [comment]
@cleisonmsilva 
Infelizmente estamos sujeitos a golpes na internet, mas eu posso dizer que se você realmente baixou desse repositorio, não foi por culpa dele. Seria bom você verificar se realmente baixou aqui, conferir o URL, se usou algum tutorial, ver se nele o URL aponta para cá corretamente, porque aparentemente você pode ter usado uma versão modificada, veja por exemplo #491, aquilo é uma versão modificada, não se se pelo autor do issue mas acredito que não, caso contrário ele não estaria aqui pedindo ajuda.

Você pode postar sim o arquivo index.py aqui para analisarmos e tentarmos ajudar você, mas sinceramente é muito difícil.

Existe também a possibilidade de você ter algum "tracker" no computador, alguma forma de acesso remoto, trojan, etc, que pode ter vindo com algo que você instalou...

**Comment by cleisonmsilva** [comment]
Acho que vou ter que formatar o pc e reinstalar outra vez, esse é bot de vcs?
https://github.com/mpcabete/bombcrypto-bot/archive/refs/heads/main.zip

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: fguide ***@***.***>
Enviado: Sunday, December 26, 2021 5:48:30 PM
Para: mpcabete/bombcrypto-bot ***@***.***>
Cc: cleisonmsilva ***@***.***>; Mention ***@***.***>
Assunto: Re: [mpcabete/bombcrypto-bot] Usei e fui escamado (Issue #484)


@cleisonmsilva<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcleisonmsilva&data=04%7C01%7C%7Cfe3c001fb29d4b04e41d08d9c8b1174e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761485192019556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=leH%2Fx%2FgB1D85fWzB3qXZrBo7adhcYfH%2B151LA2t33oU%3D&reserved=0>
Infelizmente estamos sujeitos a golpes na internet, mas eu posso dizer que se você realmente baixou desse repositorio, não foi por culpa dele. Seria bom você verificar se realmente baixou aqui, conferir o URL, se usou algum tutorial, ver se nele o URL aponta para cá corretamente, porque aparentemente você pode ter usado uma versão modificada, veja por exemplo #491<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmpcabete%2Fbombcrypto-bot%2Fissues%2F491&data=04%7C01%7C%7Cfe3c001fb29d4b04e41d08d9c8b1174e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761485192029514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P0cYpzzmYF6rk1MQBqSXlOhUQ7DCvTEdtbghI7%2FlnkQ%3D&reserved=0>, aquilo é uma versão modificada, não se se pelo autor do issue mas acredito que não, caso contrário ele não estaria aqui pedindo ajuda.

Você pode postar sim o arquivo index.py aqui para analisarmos e tentarmos ajudar você, mas sinceramente é muito difícil.

Existe também a possibilidade de você ter algum "tracker" no computador, alguma forma de acesso remoto, trojan, etc, que pode ter vindo com algo que você instalou...

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmpcabete%2Fbombcrypto-bot%2Fissues%2F484%23issuecomment-1001240142&data=04%7C01%7C%7Cfe3c001fb29d4b04e41d08d9c8b1174e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761485192029514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P%2BEIALOE01Z7donwY0RgZ%2FC5K%2ByOXExDC9M3BCfhWAc%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKVEITVFCDENK4CO4TVJIT3US55R5ANCNFSM5KY3TMEQ&data=04%7C01%7C%7Cfe3c001fb29d4b04e41d08d9c8b1174e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761485192039472%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FSL2IZwnFkFQI%2B5rsnWqTt5DatdjVHSM5nlCDIyOpKk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cfe3c001fb29d4b04e41d08d9c8b1174e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761485192039472%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3gjQS4zlA8wgVCCUkKrxIMP8rHNTPqaDz%2B%2B%2F5fL34Ig%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cfe3c001fb29d4b04e41d08d9c8b1174e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761485192039472%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pXgQuIFybL56hgvymAhk4L%2FMMpy3bnNlJ1lOJPprzUI%3D&reserved=0>.

**Comment by fguide** [comment]
@cleisonmsilva 

Sim, esse URL é daqui, porém seria interessante você comparar o arquivo index.py do SEU computador, com esse do arquivo zip e ver se há diferenças, se houver você baixou do lugar errado na primeira vez.

**Comment by cleisonmsilva** [comment]
Pelo que vi foi só pasta __pycache__, enviei o arquivo index e a pasta inteira com log etc...

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: fguide ***@***.***>
Enviado: Sunday, December 26, 2021 6:02:28 PM
Para: mpcabete/bombcrypto-bot ***@***.***>
Cc: cleisonmsilva ***@***.***>; Mention ***@***.***>
Assunto: Re: [mpcabete/bombcrypto-bot] Usei e fui escamado (Issue #484)


@cleisonmsilva<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcleisonmsilva&data=04%7C01%7C%7C718da3a2600b4b2e250108d9c8b30765%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761493519571124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xNAGXZtHgQirrvVp4r5K%2BP5cTISgg4%2F4kNOXUo9R024%3D&reserved=0>

Sim, esse URL é daqui, porém seria interessante você comparar o arquivo index.py do SEU computador, com esse do arquivo zip e ver se há diferenças, se houver você baixou do lugar errado na primeira vez.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmpcabete%2Fbombcrypto-bot%2Fissues%2F484%23issuecomment-1001241420&data=04%7C01%7C%7C718da3a2600b4b2e250108d9c8b30765%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761493519571124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=339IKDLRXA4cZDNU9rZyFQvckhQ2RaOFIuChRZCsF6o%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKVEITVCDHNQRCKLQRPOZJLUS57GJANCNFSM5KY3TMEQ&data=04%7C01%7C%7C718da3a2600b4b2e250108d9c8b30765%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761493519581073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uPZWu1GEhag%2FRBNVOwxBWEWXdRHbzpMKInQOHhw1XAg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C718da3a2600b4b2e250108d9c8b30765%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761493519581073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=igQNzS4iUI0XUPZBLEx88EhYjFwo3q9S5jBpWugt8JI%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C718da3a2600b4b2e250108d9c8b30765%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637761493519581073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OiN8CH29IMpLmPGfubO0Ca5aruPN0mTWNjf4M9lD49s%3D&reserved=0>.

**Comment by Yumiizera** [comment]
@cleisonmsilva Consegue posta o index pra gente? Você precisa ir em editar e vai dar um colar e copiar aqui. Vamos vê se a carteira da qual você foi escamado aparece.

**Comment by cleisonmsilva** [comment]
[index.zip](https://github.com/mpcabete/bombcrypto-bot/files/7777621/index.zip)

**Comment by cleisonmsilva** [comment]
[bomb.zip](https://github.com/mpcabete/bombcrypto-bot/files/7777623/bomb.zip)

**Comment by fguide** [comment]
Se forem esses os arquvos que estavam executando em seu PC quando ocorreu o problema, então não foi pelo bot mesmo, estão identicos aos daqui.

Como disse, tem que verificar outras coisas no seu PC e evitar utilizar programas de origem desconhecida, tem muito "ativador de windows" por exemplo que parece inofensível, porém fazem esse tipo de golpe.

É apenas um exemplo, mas seria viável verificar seu computador, não posso indicar ferramentas para windows infelizmente.

**Comment by cleisonmsilva** [comment]
essa é a carteira 
0xe23e1be7c918ccebe2677b29423b24f178eb8e88

acabei de formatar o pc e instalei o kaspersky total
devo instalar python do windows store? qual versão (to usando win11)
como ele conseguiu? 
pois ele n tem a senha nem a frase, mas o bomb fica com a carteira aberta, automaticamente pode ser feito tudo menos ver a chave pois pede senha. por isso levei a conclusão do bot.

**Comment by cleisonmsilva** [comment]
vcs tem alguma ideia que possa me ajudar a precaver disso, deipois que aconteceu,

**Comment by Yumiizera** [comment]
Acabei de criar um tópico sobre https://github.com/mpcabete/bombcrypto-bot/issues/492

**Comment by fguide** [comment]
> essa é a carteira 0xe23e1be7c918ccebe2677b29423b24f178eb8e88
> 
> acabei de formatar o pc e instalei o kaspersky total devo instalar python do windows store? qual versão (to usando win11) como ele conseguiu? pois ele n tem a senha nem a frase, mas o bomb fica com a carteira aberta, automaticamente pode ser feito tudo menos ver a chave pois pede senha. por isso levei a conclusão do bot.

Pois é, o problema é que depois de colocar a senha o metamask fica "logado" e se algum "virus" estiver rodando em seu pc, ele faz as transferencias atraves da sessão do navegador, sinceramente não tenho como afirmar o metodo utilizado, podem ter utilizado desde cross cookies até MITM, DNS poison, etc.

Outra possibilidade era você estar com um keylogger, que estava mandando tudo que você digita para algum server, não é muito dificil reconhecerem um padrao de frase secreta e senha...

Para manter segurança é recomendável acessar em um computador que seja minimamente utilizado para outras coisas, com software de procedencia segura (por exemplo, se for piratear o windows, nao baixe um ativador de qualquer site), com antivirus atualizado, etc. Talvez usar um navegador de internet separado só com metamask seja uma boa ideia.

Lembre que quanto mais coisas você acessa, maior é o seu risco.

**Comment by cleisonmsilva** [comment]
só fico na duvida como ele clamou bcoin, pois ainda estava no jogo só o bot trabalhava nele.

**Comment by Nucito** [comment]
> Usei e fui escamado para carteira 0xe23e1be7c918ccebe2677b29423b24f178eb8e88 Transaction Hash: 0xd96143fe00ef07188672217827a9fa12d2c559f742e466bf83331a9e87acd801

Vou apenas rir dessa:
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

Pelo visto vc andou usando usando algumas coisas que não deveria... a transação não foi feita por meio de contrato então o ser vivo transferiu com a sua key privada da metamask '-' se isso foi aqui do bot como vc me responde que apenas vc foi roubado? e ainda mais uma quantia tão pouca quanto 170 dólares?(Não estou chamando vc de pobre ou nada do tipo apenas saiba que tem pessoas que usam esse bot que faz isso 2x diariamente😁)
Você é livre para ler o código e ver se tem alguma coisa que possa roubar suas informações...

**Press F for this account.**

**Comment by cleisonmsilva** [comment]
Sou estou tentando entender como aconteceu, sendo q tem 1 semana que estou jogando, nunca clickei em nada ou instalei, sendo que essa foi a primeira vez que instalei, mas estou formatando e fazendo revoke de todos os contratos. 
Se vc poder dar algumas dicas para que isso não aconteça ficarei grato.

**Comment by cleisonmsilva** [comment]
esse foi quando ele clamou 0xe8b3ce8e2346506899177574fcc657a07f4f02c7b4207a3c5bc2c48e79b0c739
de que modo ele conseguiu, sendo que pra clamar tem que ser pelo jogo eu acho?

**Comment by jotaper0x** [comment]
Provavelmente seu windows estava ativado com algum ativador pirata ou você logou sua conta em algum site scam, pode ter inclusive comprometido sua carteira.. vou postar aqui umas dicas q deixei num grupo do facebook aqui.. espero que ajude:

Pessoal, eu gostaria que todos que estão iniciando nesse mundo de criptomoedas tomassem alguns cuidados.. esses dias um rapaz colega de um amigo meu colocou dinheiro da binance na metamask e questão de segundos o dinheiro sumiu e passei essas seguintes dicas, que espero que ajudem vocês também:

Formatar o computador, colocar windows original (ou deixa sem ativar);
Não instalar nenhum programa pirata, nem jogo (pode baixar os programas essenciais pelo ninite . com);
Não acessar sites suspeitos;
Não acessar pornografia (ou usar com sabedoria, sem querer aumentar o tamanho da pik ou conhecer vizinhas fogosas);
Comprar um antivirus (Kaspersky total Security);
Comprar uma hardwallet (quando possível,  e de revendedores oficiais);
Jogar fora essa seed phrase dele e fazer outra metamask (se tiver sido comprometido);
Criar um email no protonmail exclusivo para criptos, sem passar para ngm ou cadastrar em nada q nao seja corretoras e carteiras;
Usar 2fa do Authy para tudo q for possível;
Estudar bem o mundo cripto e ser mais desconfiado.

Espero que ajude.. minha intenção não eh passar de sabichão,  mas vejo muitas pessoas querendo entrar nesse mundo sem conhecer o básico, e acabam quebrando a cara.

**Comment by afbargon** [comment]
Boa tarde.
Vocês sabem informar se esse bot ainda funciona..
