### ISSUE TITLE
Não colocar legend para trabalhar

### ISSUE THREAD

**Issue by clecio-sf** [mpcabete/bombcrypto-bot#485]
Alguem poderia ajudar em uma solução para o bot nao por os herois legend para trabalhar? Por todos os outros, comum, raro, sr, epico, mas deixar somente o legend de fora. Desde já agradeço

**Comment by fguide** [comment]
@clecio-sf 

Eu modifiquei a função clickGreenBarButtons para ignorar o herois legend (ou algum outro que preferir) você apenas precisa salvar um screenshot na pasta targets com o nome legend.png, veja abaixo um exemplo:

![image](https://user-images.githubusercontent.com/95459411/147585868-4bdbb328-9a5f-42bc-8810-5ece1664aaaa.png)
(no caso o seu seria Legend)

Só um detalhe, se houver mais de 1 no momento de colocar para trabalhar, ele só coloca o primeiro, há metodo para fazer com todos, porém não desenvolvi.

Segue função, espero que ajude.
[clickGreenBarButtons.txt](https://github.com/mpcabete/bombcrypto-bot/files/7785529/clickGreenBarButtons.txt)

**Comment by clecio-sf** [comment]
> @clecio-sf
> 
> Eu modifiquei a função clickGreenBarButtons para ignorar o herois legend (ou algum outro que preferir) você apenas precisa salvar um screenshot na pasta targets com o nome legend.png, veja abaixo um exemplo:
> 
> ![image](https://user-images.githubusercontent.com/95459411/147585868-4bdbb328-9a5f-42bc-8810-5ece1664aaaa.png) (no caso o seu seria Legend)
> 
> Só um detalhe, se houver mais de 1 no momento de colocar para trabalhar, ele só coloca o primeiro, há metodo para fazer com todos, porém não desenvolvi.
> 
> Segue função, espero que ajude. [clickGreenBarButtons.txt](https://github.com/mpcabete/bombcrypto-bot/files/7785534/clickGreenBarButtons.txt)

@fguide 

Obrigado pela sua ajuda. Coloquei a imagem na pasta target, e sua modificação no index, porém infelizmente nao funcionou, ele continua pegando o legend e colocando para trabalhar. 
![Screenshot_1](https://user-images.githubusercontent.com/49460838/147603039-2c2e4376-6aba-499c-b86c-32d5bf49506c.jpeg)
![Screenshot_2](https://user-images.githubusercontent.com/49460838/147603041-508a2244-1225-4685-b3b5-a0620828d2a9.png)

**Comment by fguide** [comment]
Sim, é por conta da posição da imagem, tente alterar a linha:

>if (y1-17) == y

por:

>if ((y1-y) < 10) and ((y1-y) >0):

e veja se funciona. Eu fiz um teste com posicao fixa, nao considerei os tamanhos de tela diferentes, etc...

**Comment by clecio-sf** [comment]
> or conta da posição da imagem, tente alterar a linha:

Modifiquei a linha em questão, mesmo assim o bot continua a por o legend para trabalhar.

![Screenshot_2](https://user-images.githubusercontent.com/49460838/147604402-3e5c4c44-7a7b-4879-a265-d5ce0b19065f.png)

**Comment by JoaoMXN** [comment]
Queria essa função tb, aqui com essa imagem o bot manda o legend pra trabalhar também.

**Comment by fguide** [comment]
A funcao abaixo coloca comuns, raros e super raros para trabalhar. para colocar outras é só seguir o exemplo e fazer mais 1 for...

precisa salvar os prints conforme esta no script:
srare.png para super rare 
rare.png para rare

```
def clickGreenBarButtons():
    offset = 140
    green_bars = positions(images['green-bar'], threshold=ct['green_bar'])
    buttons = positions(images['commom-text'], threshold=ct['commom'])
    not_working_green_bars = []
    if len(green_bars) > 0:
        for bar in green_bars:
            if not isWorking(bar, buttons):
                not_working_green_bars.append(bar)

        if len(not_working_green_bars) > 0:
            for (x, y, w, h) in not_working_green_bars:
                moveToWithRandomness(x+offset+(w/2),y+(h/2),1)
                pyautogui.click()
                global hero_clicks
                hero_clicks += 1

    time.sleep(1)

    green_bars = positions(images['green-bar'], threshold=ct['green_bar'])
    buttons = positions(images['rare'], threshold=ct['commom'])
    not_working_green_bars = []
    if len(green_bars) > 0:
        for bar in green_bars:
            if not isWorking(bar, buttons):
                not_working_green_bars.append(bar)

        if len(not_working_green_bars) > 0:
            for (x, y, w, h) in not_working_green_bars:
                moveToWithRandomness(x+offset+(w/2),y+(h/2),1)
                pyautogui.click()
                hero_clicks += 1

    time.sleep(1)

    green_bars = positions(images['green-bar'], threshold=ct['green_bar'])
    buttons = positions(images['srare'], threshold=ct['commom'])
    not_working_green_bars = []
    if len(green_bars) > 0:
        for bar in green_bars:
            if not isWorking(bar, buttons):
                not_working_green_bars.append(bar)

        if len(not_working_green_bars) > 0:
            for (x, y, w, h) in not_working_green_bars:
                moveToWithRandomness(x+offset+(w/2),y+(h/2),1)
                pyautogui.click()
                hero_clicks += 1


    return 0
```

**Comment by JoaoMXN** [comment]
> A funcao abaixo coloca comuns, raros e super raros para trabalhar. para colocar outras é só seguir o exemplo e fazer mais 1 for...
> 
> precisa salvar os prints conforme esta no script: srare.png para super rare rare.png para rare
> 
> ```
> def clickGreenBarButtons():
>     offset = 140
>     green_bars = positions(images['green-bar'], threshold=ct['green_bar'])
>     buttons = positions(images['commom-text'], threshold=ct['commom'])
>     not_working_green_bars = []
>     if len(green_bars) > 0:
>         for bar in green_bars:
>             if not isWorking(bar, buttons):
>                 not_working_green_bars.append(bar)
> 
>         if len(not_working_green_bars) > 0:
>             for (x, y, w, h) in not_working_green_bars:
>                 moveToWithRandomness(x+offset+(w/2),y+(h/2),1)
>                 pyautogui.click()
>                 global hero_clicks
>                 hero_clicks += 1
> 
>     time.sleep(1)
> 
>     green_bars = positions(images['green-bar'], threshold=ct['green_bar'])
>     buttons = positions(images['rare'], threshold=ct['commom'])
>     not_working_green_bars = []
>     if len(green_bars) > 0:
>         for bar in green_bars:
>             if not isWorking(bar, buttons):
>                 not_working_green_bars.append(bar)
> 
>         if len(not_working_green_bars) > 0:
>             for (x, y, w, h) in not_working_green_bars:
>                 moveToWithRandomness(x+offset+(w/2),y+(h/2),1)
>                 pyautogui.click()
>                 hero_clicks += 1
> 
>     time.sleep(1)
> 
>     green_bars = positions(images['green-bar'], threshold=ct['green_bar'])
>     buttons = positions(images['srare'], threshold=ct['commom'])
>     not_working_green_bars = []
>     if len(green_bars) > 0:
>         for bar in green_bars:
>             if not isWorking(bar, buttons):
>                 not_working_green_bars.append(bar)
> 
>         if len(not_working_green_bars) > 0:
>             for (x, y, w, h) in not_working_green_bars:
>                 moveToWithRandomness(x+offset+(w/2),y+(h/2),1)
>                 pyautogui.click()
>                 hero_clicks += 1
> 
> 
>     return 0
> ```

Funcionou! Muito obg mesmo
