### ISSUE TITLE
Error on VM google Cloud

### ISSUE THREAD

**Issue by nicolobi** [mpcabete/bombcrypto-bot#486]
Hello, i have this error.
I have install requirements...
Thanks a lot ! 

![Capture d’écran 2021-12-26 151832](https://user-images.githubusercontent.com/38302951/147411019-cb0cb01c-ab7e-4a10-9f4a-940286dc958d.png)

**Comment by fguide** [comment]
Looks like you don't have any display available, are you running an X session?

What about trying: export DISPLAY=:1 ?

**Comment by nicolobi** [comment]
How can i run an X session ?

**Comment by nicolobi** [comment]
> Looks like you don't have any display available, are you running an X session?
> 
> What about trying: export DISPLAY=:1 ?

How can i run an X session ?
I have a graphical interface, I know how to connect remotely to the office ...

How can i export Display ??

**Comment by nicolobi** [comment]
When I run with the terminal here is what I got as an error.
I need to install tkinter but, it is already instalL..
![tk](https://user-images.githubusercontent.com/38302951/147412209-4064fbfd-919a-4191-839c-7bd139a75e3c.png)
![deja](https://user-images.githubusercontent.com/38302951/147412213-f9f92469-6563-40b2-a3ab-5fe4b3b9d888.png)

**Comment by fguide** [comment]
You have to get a X session (graphical interface) running so you can have the browser opened and the bot clicking it, do you have it running someway or are you just trying to run the bot through ssh?

If you do, acess it and run the bot from there.

If you don't, the you have to run one, I recommend doing it through vncserver, install it, acess the vnc session open the game and run the bot there.

**Comment by nicolobi** [comment]
> You have to get a X session (graphical interface) running so you can have the browser opened and the bot clicking it, do you have it running someway or are you just trying to run the bot through ssh?
> 
> If you do, acess it and run the bot from there.
> 
> If you don't, the you have to run one, I recommend doing it through vncserver, install it, acess the vnc session open the game and run the bot there.

I have an interface... The screenshot is not on SSH, is in the command in the interface...

**Comment by fguide** [comment]
Oh sorry I figured it out wrongly. Probably  you need to install python3.9-tl and python3.9-dev as you're using python3.9

**Comment by fguide** [comment]
> Oh sorry I figured it out wrongly. Probably you need to install python3.9-tk and python3.9-dev as you're using python3.9

**Comment by nicolobi** [comment]
I will try to install this version of python... Thanks .Le 26 déc. 2021 17:25, fguide ***@***.***> a écrit :
Oh sorry I figured it out wrongly. Probably  you need to install python3.9-tl and python3.9-dev as you're using python3.9

**Comment by nicolobi** [comment]
Both are already installed ... That's why I don't understand where the problem comes from ...
