### ISSUE TITLE
Valor para aula 

### ISSUE THREAD

**Issue by chwiee** [mpcabete/bombcrypto-bot#487]
Opa man beleza? Quanto tu cobraria para dar uma aula sobre o bot? Como tu fez a logica e tudo mais? Sou estudante de IA / ML e queria muito entender como tu fez a logica e tudo mais se possivel me passa seu contato

**Comment by Nucito** [comment]
> Opa man beleza? Quanto tu cobraria para dar uma aula sobre o bot? Como tu fez a logica e tudo mais? Sou estudante de IA / ML e queria muito entender como tu fez a logica e tudo mais se possivel me passa seu contato

Sobre a IA isso era um fork do meu repo, se for sobre uso do opencv para bots o mpcabete foi o criador😁
