### ISSUE TITLE
Windows 10 não detecta python ???

### ISSUE THREAD

**Issue by jokinvipo** [mpcabete/bombcrypto-bot#488]
Opa galera, tava usando o bot de boa estes dias e do nada tive de reinicar o computador e nunca mais consegui usar bot.

![image](https://user-images.githubusercontent.com/35331883/147411938-539a1d79-cec2-47cb-8954-d927a1664c38.png)

Já segui vários videos no youtube mas não consigo arrumar esse erro.

Alguém consegue ajudar ?

**Comment by kerferber** [comment]
> Opa galera, tava usando o bot de boa estes dias e do nada tive de reinicar o computador e nunca mais consegui usar bot.
> 
> ![image](https://user-images.githubusercontent.com/35331883/147411938-539a1d79-cec2-47cb-8954-d927a1664c38.png)
> 
> Já segui vários videos no youtube mas não consigo arrumar esse erro.
> 
> Alguém consegue ajudar ?

Acho que já vi essa reclamação aqui. Foi resolvido desinstalando a última atualização

**Comment by fguide** [comment]
Se você só tem o python 3.x instalado não precisa usar o comando python3, tente com python apenas.

**Comment by jokinvipo** [comment]
> Se você só tem o python 3.x instalado não precisa usar o comando python3, tente com python apenas.

Funcionou aqui, valeu mano ;)

**Comment by rbcazare** [comment]
Estou com o mesmo erro aqui, removi a atualização do windows 10 do dia 18/12/2021 e ainda continua a mensagem.
