### ISSUE TITLE
Não colocar heroi de uma raridade especifica para trabalhar

### ISSUE THREAD

**Issue by amadeu22** [mpcabete/bombcrypto-bot#489]
Existe alguma forma de fazer o bot nao colocar um heroi de uma raridade especifica para trabalhar?
ex: Nao quero por meus legend nem epicos para trabalhar

**Comment by HeeyMan** [comment]
Coloca pra trabalhar só full hp...

**Comment by amadeu22** [comment]
> 

e quando o legend, ou epico estiver com full hp????.......

**Comment by amadeu22** [comment]
> Coloca pra trabalhar só full hp...

e quando o boneco que eu nao quero que vá trabalhar estiver com stamina cheia...?? isso nao funciona.

**Comment by welbertim** [comment]
Desativa ele e roda o bot...

**Comment by amadeu22** [comment]
> Desativa ele e roda o bot...

ai o heroi nao carrega a stamina ne........... se nao sabe, nao responde kkkk

**Comment by amadeu22** [comment]
> Desativa ele e roda o bot...

Assim o heroi nao carrega a stamina...... nao funciona tbm.
