### ISSUE TITLE
Só quero que o código atualizado envie os heróis para casa, já que comprei um.

### ISSUE THREAD

**Issue by eztzez** [mpcabete/bombcrypto-bot#49]
Ola meu irmão
Também tenho quase tudo funcionando perfeitamente !!
Só quero que o código atualizado envie os heróis para casa, já que comprei um.
por favor me ajude

**Comment by mpcabete** [comment]
Olá, eu estou trabalhando nisso mas não tenho certeza se esta funcionando 100% ainda, se quiser ir testando pode baixar essa [branch](https://github.com/mpcabete/bombcrypto-bot/tree/home-feature), dai se quiser me avisar se notar algum problema eu agradeceria : )
