### ISSUE TITLE
Bot não inicia no VPS - VM!!!

### ISSUE THREAD

**Issue by netoskinha** [mpcabete/bombcrypto-bot#491]
Por favor preciso de ajuda, simplesmente não inicia, já tentei de tudo e toda vez que coloco ele fica agarrado no CMD sem dar nenhum comando nem nada.

![image](https://user-images.githubusercontent.com/96698893/147417330-f28f64f8-ccef-4a38-bf2d-27946371b576.png)

**Comment by netoskinha** [comment]
No meu pc funciona de boa, mas na VM fica assim.

**Comment by fguide** [comment]
Não sei de onde você baixou, mas pelo inicio nao é o oficial daqui.

**Comment by netoskinha** [comment]
É o daqui, mas só peguei a config pra ser o multicontas entendeu.

**Comment by netoskinha** [comment]
Basicamente este bot que estou rodando faz o seguinte, ele procura abas da internet que estejam abertas em "app.bombcrypto.io" faz todo o procedimento do bot e quando finaliza ele da alt + tab e começo tudo de novo e fica nesse ciclo.

No meu computador pessoal funciona, mas quando jogo no VM ele sequer inicia como está no print.

**Comment by Nucito** [comment]
Esse bot não é daqui😁
Abra o issue onde vc baixou ele...

**Comment by netoskinha** [comment]
Aqui de onde baixei é daqui sim!

![image](https://user-images.githubusercontent.com/96698893/147421337-bb8bf63b-b9f1-4637-9d21-b474692502db.png)

**Comment by netoskinha** [comment]
@mGranTY
