### ISSUE TITLE
[OFF-TOPIC] SE FOI SCAMADO, LEIA ESTA ISSUE.

### ISSUE THREAD

**Issue by Yumiizera** [mpcabete/bombcrypto-bot#492]
Estou vendo pessoas sendo scamados e colocando culpa no projeto do bot.
Primeiramente, o código é aberto e outra; se você perdeu as suas NFT a responsabilidade é só sua. 

Possíveis causas de que você foi scamado:

> Fulaninho me mandou baixar o bot dele modificado, mas não está no GitHub 
 Por favor né, não precisa nem explicar... Vamos ao próximo;

> Baixei por um site porque que vi o youtuber "zézinho123", que me redirecionou aqui pro GitHub
 Essa aqui parece piada, mas não é. Eu mesmo comecei a ver vídeos onde tinha sites que te redireciona aqui mesmo, e que provavelmente pode fazer alguma conexão com a sua metamask, caso você baixou e não é por esse: https://github.com/mpcabete/bombcrypto-bot , sinto muito mas não tem o que o dev fazer;

> Baixei de um amigo meu, mas sumiu da minha metamask
 Melhor rever suas amizades XD;

> Vi que o joãozinho e o pedrinho me pediram umas palavras pra acessar a minha conta da metamask
 EM HIPÓTESE NENHUMA, PASSE SUAS PALAVRAS CHAVES. NÃO SEJA BURRO;

> Eu baixei de outro dev, que fez alguma atualizações que melhora o bot e depois sumiram as minhas nfts após usar ele
 Parece estranho o que vou dizer para as pessoas leigas, mas sempre verifiquem essas modificações, postem aqui nas issues que quem entende vai dar uma olhada e vai dar um sinal verde sobre o bot (Tem pessoas que realmente se aproveita desta deficiência, então é bom sempre conferir por ser de código aberto)

>Baixei e tive que rodar um .exe pra rodar o bot
 Em hipótese nenhuma, execute algum arquivo .exe. Teve "pessoas" que estavam sim com boas intenções mas infelizmente o executável estava preparado pra dar o scam. Sim gente, acontece e se acontecer algo saiba que este bot ele é executável pelo cmd.
 
Acredito que esses são alguns (existem mais, mas espero que tenham maturidade do que estão fazendo pra proteger o seu dinheiro) possíveis scans e que as pessoas tem que ter responsabilidade. Vou deixar um link de uma pessoa confiável que ensina a configurar na versão antiga (https://www.youtube.com/watch?v=e9NNyxNCF7k&t=177s) mas ainda funciona normalmente. Aqui tem as issue que tem soluções pra possíveis erros e entendam que o bot não é o problema, e sim o que está entre a cadeira e o teclado: você.

Aquele abraço e tomem cuidado. Boas festas.

**Comment by netoskinha** [comment]
Tem um BOT aqui que vem com essa config, tem como ver se é scam?

![image](https://user-images.githubusercontent.com/96698893/147421280-c62bf7b6-e15f-4950-af5c-7f534dbce35e.png)

**Comment by Yumiizera** [comment]
> 



> Tem um BOT aqui que vem com essa config, tem como ver se é scam?
> 
> ![image](https://user-images.githubusercontent.com/96698893/147421280-c62bf7b6-e15f-4950-af5c-7f534dbce35e.png)

É o que eu disse, coloque os arquivos aqui no github e espere que analisem.

**Comment by netoskinha** [comment]
[bot multiconta.zip](https://github.com/mpcabete/bombcrypto-bot/files/7777666/bot.multiconta.zip)

foi o @mGranTY que fez esse bot em outra inssue, ta rodando liso, uma dúvida que ficou é sobre o arquivo FOREVER.py

**Comment by kerferber** [comment]
Apenas para fazer um adendo...
Acredito que a maioria dos scamados são vítimas de membros do grupo telegram.
É incrível a quantidade de pessoas inocentemente ingênuas que reclamam ter perdido suas moedas diariamente.
Normalmente o assédio ocorre após enviar alguma mensagem no grupo do telegram....

Os fraudadores entram em contato com as vítimas sob o argumento de serem do time de suporte/moderadores, e muitos com o nome do Bot Rose.

A cada mensagem que envio no grupo do telegram, ao menos 2 ou 3 golpistas me chamam no privado...

Seria prepotência de minha parte chamar as vítimas de burras, mas sim, são muito ingênuas...

**Comment by madarazm** [comment]
https://github.com/mfsousa/bombcrypto-bot
alguém poderia verificar se tem algo de errado com esse código? não entendo nada de programação 

> Estou vendo pessoas sendo scamados e colocando culpa no projeto do bot. Primeiramente, o código é aberto e outra; se você perdeu as suas NFT a responsabilidade é só sua.
> 
> Possíveis causas de que você foi scamado:
> 
> > Fulaninho me mandou baixar o bot dele modificado, mas não está no GitHub
> > Por favor né, não precisa nem explicar... Vamos ao próximo;
> 
> > Baixei por um site porque que vi o youtuber "zézinho123", que me redirecionou aqui pro GitHub
> > Essa aqui parece piada, mas não é. Eu mesmo comecei a ver vídeos onde tinha sites que te redireciona aqui mesmo, e que provavelmente pode fazer alguma conexão com a sua metamask, caso você baixou e não é por esse: https://github.com/mpcabete/bombcrypto-bot , sinto muito mas não tem o que o dev fazer;
> 
> > Baixei de um amigo meu, mas sumiu da minha metamask
> > Melhor rever suas amizades XD;
> 
> > Vi que o joãozinho e o pedrinho me pediram umas palavras pra acessar a minha conta da metamask
> > EM HIPÓTESE NENHUMA, PASSE SUAS PALAVRAS CHAVES. NÃO SEJA BURRO;
> 
> > Eu baixei de outro dev, que fez alguma atualizações que melhora o bot e depois sumiram as minhas nfts após usar ele
> > Parece estranho o que vou dizer para as pessoas leigas, mas sempre verifiquem essas modificações, postem aqui nas issues que quem entende vai dar uma olhada e vai dar um sinal verde sobre o bot (Tem pessoas que realmente se aproveita desta deficiência, então é bom sempre conferir por ser de código aberto)
> 
> > Baixei e tive que rodar um .exe pra rodar o bot
> > Em hipótese nenhuma, execute algum arquivo .exe. Teve "pessoas" que estavam sim com boas intenções mas infelizmente o executável estava preparado pra dar o scam. Sim gente, acontece e se acontecer algo saiba que este bot ele é executável pelo cmd.
> 
> Acredito que esses são alguns (existem mais, mas espero que tenham maturidade do que estão fazendo pra proteger o seu dinheiro) possíveis scans e que as pessoas tem que ter responsabilidade. Vou deixar um link de uma pessoa confiável que ensina a configurar na versão antiga (https://www.youtube.com/watch?v=e9NNyxNCF7k&t=177s) mas ainda funciona normalmente. Aqui tem as issue que tem soluções pra possíveis erros e entendam que o bot não é o problema, e sim o que está entre a cadeira e o teclado: você.
> 
> Aquele abraço e tomem cuidado. Boas festas.

https://github.com/mfsousa/bombcrypto-bot
alguém poderia verificar se tem algo de errado com esse código? não entendo nada de programação

**Comment by mGranTY** [comment]
> [bot multiconta.zip](https://github.com/mpcabete/bombcrypto-bot/files/7777666/bot.multiconta.zip)
> 
> foi o @mGranTY que fez esse bot em outra inssue, ta rodando liso, uma dúvida que ficou é sobre o arquivo FOREVER.py

não tem nada de malicioso, esse código simplesmente reinicia o bot caso ele crashe, pois comigo ele estava crashando do nada, se pra você não esta crashando, pode deletar e simplesmente não usar.
