### ISSUE TITLE
Problema ao sair da tela de heróis. (Clicar no X)

### ISSUE THREAD

**Issue by RenanPFerreira** [mpcabete/bombcrypto-bot#493]
O bot clica no work várias vezes e não clica no X para ir a tela principal e ir para o treasure hunt.
Ações que já fiz mas sem sucesso.
Diminuir/Aumentar o threshold do go_to_work_btn
Alterar escala do monitor para 100% (Uso 125%)
Alterar o desenho do [X] para um igual do meu pc.

O bot clica no Work normalmente, o problema é sair clicando no X.

**Comment by fguide** [comment]
O threshold do botao X é o 'deafult' tente modificar ele.

**Comment by RenanPFerreira** [comment]
Tentei mas sem sucesso fiz o teste com
0.5 e 0.2 também, acredito que o problema está antes também, pois encontra muitos botões (work) para clicar e não sai dessa tela nunca. (fica clicando e arrastando para baixo)

**Comment by RenanPFerreira** [comment]
> Tentei mas sem sucesso fiz o teste com
> 0.5 e 0.2 também, acredito que o problema está antes também, pois encontra muitos botões (work) para clicar e não sai dessa tela nunca. (fica clicando e arrastando para baixo) 

Já alterei o threshold do botão que clica no work também sem sucesso.

**Comment by fguide** [comment]
Vc por acaso tem muitos herois 'não-comuns' ? O scroll usa o texto de commons, talvez esteja com falha aí.

**Comment by RenanPFerreira** [comment]
> Vc por acaso tem muitos herois 'não-comuns' ? O scroll usa o texto de commons, talvez esteja com falha aí.
> 
> Ou seu problema é esse:  #470

Não tenho, no meu caso só tenho 3 heróis todos comuns.
Vou tentar com outro navegador mais tarde para ver se pode ser isso.
Achei estranho achar mais de 3 botões na tela. Último log registrou 78 botões

**Comment by mpcabete** [comment]
> Tentei mas sem sucesso fiz o teste com 0.5 e 0.2 também, acredito que o problema está antes também, pois encontra muitos botões (work) para clicar e não sai dessa tela nunca. (fica clicando e arrastando para baixo)

Parece que o problema realmente eh que ele ta dando falso positivos e vendo botões de "go_work" onde nao tem. nesse caso vc pode tentar aumentar o threshold ou substituir a imagem do "go_work", pq ele vai tentar mandar os herois trabalhar enquanto ele ver esse botão.

**Comment by RenanPFerreira** [comment]
> > Tentei mas sem sucesso fiz o teste com 0.5 e 0.2 também, acredito que o problema está antes também, pois encontra muitos botões (work) para clicar e não sai dessa tela nunca. (fica clicando e arrastando para baixo)
> 
> Parece que o problema realmente eh que ele ta dando falso positivos e vendo botões de "go_work" onde nao tem. nesse caso vc pode tentar aumentar o threshold ou substituir a imagem do "go_work", pq ele vai tentar mandar os herois trabalhar enquanto ele ver esse botão.

Eu já tinha tentado mudar a imagem do go work para uma aqui do meu navegador vou tentar refazer isso e também aumentar o threshold pra ver. Aviso se tiver novidades.

**Comment by RenanPFerreira** [comment]
> > > Tentei mas sem sucesso fiz o teste com 0.5 e 0.2 também, acredito que o problema está antes também, pois encontra muitos botões (work) para clicar e não sai dessa tela nunca. (fica clicando e arrastando para baixo)
> > 
> > 
> > Parece que o problema realmente eh que ele ta dando falso positivos e vendo botões de "go_work" onde nao tem. nesse caso vc pode tentar aumentar o threshold ou substituir a imagem do "go_work", pq ele vai tentar mandar os herois trabalhar enquanto ele ver esse botão.
> 
> Eu já tinha tentado mudar a imagem do go work para uma aqui do meu navegador vou tentar refazer isso e também aumentar o threshold pra ver. Aviso se tiver novidades.

Tentei as seguintes ações sem sucesso.
Testei em outro navegador (Google Chrome) 
Alterei a imagem do "go_work"
Testei com threshold em 0.3 0.5 0.8 0.9 e 1
E o log fica nesse loop. 
![image](https://user-images.githubusercontent.com/31439911/147473985-1e6a0b72-b4aa-4065-acdb-19e0913714e1.png)

**Comment by fguide** [comment]
Amigo, tente mudar no arquivo index.py a linha  280 de 

>return len(not_working_green_bars)
para
>return 0

E faça um teste, por favor.

**Comment by RenanPFerreira** [comment]
> Amigo, tente mudar no arquivo index.py a linha 280 de
> 
> > return len(not_working_green_bars)
> > para
> > return 0
> 
> E faça um teste, por favor.

Cara, animal, funcionou certinho agora, clicou nos 3 heróis rolou a página para conferir e clicou no X de primeira.
![image](https://user-images.githubusercontent.com/31439911/147499408-07eb7f4d-02db-4c02-ad6d-7c4164063364.png)

Obrigado time! Podem atualizar a branch com essa correção lá que é sucesso

**Comment by fguide** [comment]
Beleza! Acho que é um bug com a chamada do scroll, eu estava fazendo um codigo custom para outro user aqui e percebi isso. Vou fazer mais uns testes e depois quando der submeto a correção.
