### ISSUE TITLE
Priorizar bombheroes não comuns para estourar os baús

### ISSUE THREAD

**Issue by jotaper0x** [mpcabete/bombcrypto-bot#495]
Fala pessoal, tudo certo? Alguém sabe se seria possível criar um método em que bombheroes raros (ou talvez a partir de super raros) foquem em explodir os baús, e assim que estiverem com um restinho de vida, os bomb irem dormir e os comuns terminarem o serviço?

**Comment by Yaagod** [comment]
Que é possível com certeza, mas não seria nada fácil fazer isso, na minha opinião não vale a pena fazer isso pelo esforço necessário

**Comment by Felipecristao** [comment]
Isso nao é possivel, isso com certeza iria dar ban. é diferente de  um autoclik

**Comment by walterdis** [comment]
> Isso nao é possivel, isso com certeza iria dar ban. é diferente de um autoclik

Não da ban pois, eu faço isso manualmente quando não estou com o bot ativo (micro gerenciamento).
Problema é que fazer isso no bot é chato, não vale a pena.

**Comment by Yaagod** [comment]
Só usar em máquina virtual, eu uso o bot em 4 contas ao mesmo tempo, 4 máquinas virtuais.
Uso o Lubuntu como OS para poupar memória RAM, cada máquina usa em média 1,2GB de RAM no total com o Chrome e o bot aberto.

**Comment by hugooandradec** [comment]
@walterdis , o que o @Felipecristao quis dizer é que pra fazer isso, teria que ser um programa diferente do que esse bot, que nada mais é que um autoclick (melhorado). Provavelmente teria que "injetar" algo no jogo, para que o programa pudesse fazer as identificações necessárias para trabalhar conforme o @jotaper0x gostaria e ai sim, seria passivel de ban. Você faz manualmente, assim como 99% dos players, esse micro gerenciamento e fazer dessa forma (manualmente, é totalmente normal.

**Comment by jotaper0x** [comment]
> @walterdis , o que o @Felipecristao quis dizer é que pra fazer isso, teria que ser um programa diferente do que esse bot, que nada mais é que um autoclick (melhorado). Provavelmente teria que "injetar" algo no jogo, para que o programa pudesse fazer as identificações necessárias para trabalhar conforme o @jotaper0x gostaria e ai sim, seria passivel de ban. Você faz manualmente, assim como 99% dos players, esse micro gerenciamento, e fazer dessa forma, manualmente, é totalmente normal.

na verdade, não precisaria injetar nada.. seria utilizado o mesmo "esquema" de verificação da stamina dos bomb heroes.. mas, creio que seja um trabalho que de fato, não valha a pena implementar no bot

**Comment by hugooandradec** [comment]
> > @walterdis , o que o @Felipecristao quis dizer é que pra fazer isso, teria que ser um programa diferente do que esse bot, que nada mais é que um autoclick (melhorado). Provavelmente teria que "injetar" algo no jogo, para que o programa pudesse fazer as identificações necessárias para trabalhar conforme o @jotaper0x gostaria e ai sim, seria passivel de ban. Você faz manualmente, assim como 99% dos players, esse micro gerenciamento, e fazer dessa forma, manualmente, é totalmente normal.
> 
> na verdade, não precisaria injetar nada.. seria utilizado o mesmo "esquema" de verificação da stamina dos bomb heroes.. mas, creio que seja um trabalho que de fato, não valha a pena implementar no bot

acho que seria mais complicado que isso.. mas enfim, realmente o trabalho não seria viável

**Comment by fguide** [comment]
@jotaper0x aparentemente ha um trabalho em progresso no #512 para isso, você poderia fechar esse issue e seguir com testes lá?

**Comment by jotaper0x** [comment]
Tem um trabalho em progresso no PR 512.
