### ISSUE TITLE
Fatal error in launcher

### ISSUE THREAD

**Issue by grcavalcante** [mpcabete/bombcrypto-bot#496]
[Fatal](url) error in launcher: Unable to create process using '"C:\Program Files\Python39\python.exe"  "C:\Program Files\Python39\Scripts\pip.exe" install -r requirements.txt': O sistema nπo pode encontrar o arquivo especificado.
#496 
![Captura de Tela (25)](https://user-images.githubusercontent.com/96716551/147444959-ca806a30-bcf9-4536-9024-81fcb2da4980.png)

alguem sabe como resolver esse problema?? e poderia me ajudar por favor 
discord lacosteira#1725

**Comment by fguide** [comment]
e o comando python -m pip install -r requirements.txt ?
