### ISSUE TITLE
Utilizando com duas contas ao mesmo tempo

### ISSUE THREAD

**Issue by rbcazare** [mpcabete/bombcrypto-bot#498]
Olá,
Estou utilizando com duas contas ao mesmo tempo abertas no Firefox, lado a lado.

O bot funciona perfeitamente na primeira da esquerda, e na outra ele também funciona, mas somente para ações como: conectar o jogo quando cai, dar OK, clicar em NEW MAP.

Em outras palavras, na segunda falta apenas ele dar WORK nos heróis e aquele refresh neles. 

Acredito que falta bem pouco pros criadores fazerem funcionar em mais de uma conta, como é meu caso.

Talvez dê pra fazer uma repetição nas funções fazendo a leitura por aba do navegador e não pela tela toda, algo assim!

Fica como sugestão! Gostaria muito que funcionasse bem nas duas ou mais.

**Comment by AnderRobson** [comment]
Cara acabei de baixar o bot e fiz uns ajustes no código a onde ele coloca os personagens para trabalhar espera um pouco da um refresh no mapa e da um ALT + TAB, assim trocando de página (Para a segunda conta) e executando navamente o mesmo processo, assim dando ALT + TAB ao final de cada ciclo, tá funcionando até agora nos testes.

Vou ver se ajusto melhor o código para que esse processo fique mais dinamico antes de abrir um request.

**Comment by hugooandradec** [comment]
@rbcazare , já tem um PR aqui, pra funcionar em multiaccount, da uma olhada se funciona pra você.

**Comment by rbcazare** [comment]
> @rbcazare , já tem um PR aqui, pra funcionar em multiaccount, da uma olhada se funciona pra você.

Olá amigo, 
O que é um PR? Não estou familiarizado. Consegue me indicar onde está?
Abraços.

**Comment by hugooandradec** [comment]
> > @rbcazare , já tem um PR aqui, pra funcionar em multiaccount, da uma olhada se funciona pra você.
> 
> Olá amigo, O que é um PR? Não estou familiarizado. Consegue me indicar onde está? Abraços.

PR =  Pull Request
É quando alguém faz uma modificação no código e solicita que seja integrado ao código principal.

Nos menus, lá em cima, tu vai encontrar a seção que estou me referindo.

**Comment by mtmassa** [comment]
> Cara acabei de baixar o bot e fiz uns ajustes no código a onde ele coloca os personagens para trabalhar espera um pouco da um refresh no mapa e da um ALT + TAB, assim trocando de página (Para a segunda conta) e executando navamente o mesmo processo, assim dando ALT + TAB ao final de cada ciclo, tá funcionando até agora nos testes.
> 
> Vou ver se ajusto melhor o código para que esse processo fique mais dinamico antes de abrir um request.

Aguardando ser incorporado!

**Comment by ckascioo** [comment]
> Cara acabei de baixar o bot e fiz uns ajustes no código a onde ele coloca os personagens para trabalhar espera um pouco da um refresh no mapa e da um ALT + TAB, assim trocando de página (Para a segunda conta) e executando navamente o mesmo processo, assim dando ALT + TAB ao final de cada ciclo, tá funcionando até agora nos testes.
> 
> Vou ver se ajusto melhor o código para que esse processo fique mais dinamico antes de abrir um request.

pode compartilhar ? peguei oq tem aqui mais to com erro na janela, ele acaba dando atençao só em 1 conta na outra ele nao coloca pra trabalhar, só fica mudando da tela principal pra tela dos baus
