### ISSUE TITLE
Error Line 4 and Line 221

### ISSUE THREAD

**Issue by Jojiin** [mpcabete/bombcrypto-bot#50]
Hi i'm having this two errors, could anyone help?
Olá, estou tendo esses 2 erros, alguem poderia dar um help?

D:\bombcrypto-bot-main>python index.py
Traceback (most recent call last):
  File "D:\bombcrypto-bot-main\index.py", line 4, in <module>
    import pyautogui
  File "D:\Python\lib\site-packages\pyautogui\__init__.py", line 221, in <module>
    locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'

**Comment by matheusgm0** [comment]
you download the requirements?

**Comment by Jojiin** [comment]
yup

**Comment by opastorello** [comment]
same error
![image](https://user-images.githubusercontent.com/68306729/143189397-0d38269c-58b8-4178-aa70-46681abe0087.png)

**Comment by Jojiin** [comment]
> same error ![image](https://user-images.githubusercontent.com/68306729/143189397-0d38269c-58b8-4178-aa70-46681abe0087.png)
> 
> EDIT:
> 
> It was missing a dependency, it performed the installation and it worked normally.
> 
> `pip install wheel`

did this, but i'm still getting the same error #sadness

**Comment by opastorello** [comment]
> sadness

Do the following:

`pip uninstall wheel`
`pip uninstall pyautogui`

later

`pip install wheel`
`pip install pyautogui`

in the order given

**Comment by Jojiin** [comment]
> 

Tried this too, but same thing "/
thx again

**Comment by Jojiin** [comment]
> > sadness
> 
> Do the following:
> 
> `pip uninstall wheel` `pip uninstall pyautogui`
> 
> later
> 
> `pip install wheel` `pip install pyautogui`
> 
> in the order given

Tried this too, and still same error
Thx again

**Comment by Hermanyo** [comment]
> > > sadness
> > 
> > 
> > Do the following:
> > `pip uninstall wheel` `pip uninstall pyautogui`
> > later
> > `pip install wheel` `pip install pyautogui`
> > in the order given
> 
> Tried this too, and still same error Thx again

Install python3 and then do pip3 install pyautogui
