### ISSUE TITLE
Bot sai e entra no mapa 

### ISSUE THREAD

**Issue by osasquense** [mpcabete/bombcrypto-bot#501]
Bot saindo e entrando no mapa após 1 minuto mais ou menos, como aumento esse tempo? é pq meus comum demora pra chegar nos bau ai saindo do mapa eles vao pra lugar aleatorio e isso demora mais pra eles chegarem nos baus

**Comment by fguide** [comment]
Você diz que ele faz o refresh a cada 1 minuto? por padrão está configurado para cada 3 minutos, você pode verificar no arquivo config.yaml:

```
    # Valor padrão (em minutos): 3
    refresh_heroes_positions: 3
```

**Comment by osasquense** [comment]
Cara era isso mesmo, obrigado!

**Comment by fguide** [comment]
Ótimo, se puder, fecha o issue agora que está resolvido!
