### ISSUE TITLE
fail bot

### ISSUE THREAD

**Issue by gustavoholanda01** [mpcabete/bombcrypto-bot#504]
**Instalei o bot com os códigos atualizados e infelizmente parou de funcionar. Ele executa, mas nenhum movimento é feito para por os bonecos para trabalhar. Mexe apenas para conectar-se a carteira ao jogo e o resto não vai.

[](url)
![ds](https://user-images.githubusercontent.com/96751804/147512137-ccb7c8da-6280-42e5-b947-994bde51808a.png)

**Comment by l1lb1g** [comment]
Erro Phyton3

Desinstale a versão antiga do seu Phyton3
Instale a nova versão Phyton3
Instale a versão também pela Microsoft STORE
Instale novamente os arquivos do BOT (ATUALIZADO)
Execute o bot como ----> "python index.py" (sem as aspas)
Tmj espero ter ajudado
