### ISSUE TITLE
VM google windows server

### ISSUE THREAD

**Issue by nicolobi** [mpcabete/bombcrypto-bot#505]
Consegui instalar o bot em uma máquina virtual do Google com o servidor da Microsoft.
Quando estou na máquina virtual, está tudo bem!
Mas quando saio da máquina virtual, nada acontece. Parece que o Windows está cortando a tela ...
Verifiquei corretamente, o computador não entra no modo de hibernação e não coloca o protetor de tela. Você tem alguma ideia?

//

I managed to install the bot on a google virtual machine with the microsoft server.
When I am in the virtual machine, everything is fine!
But when I leave the virtual machine, nothing happens. Looks like windows is cutting the display ...
I have checked correctly, the computer does not go to sleep and does not put the screen saver. Do you have an idea?

**Comment by fguide** [comment]
Quando você desconecta do RDP a sessao fica locked, veja #465

Precisa usar outro sw de acesso remoto ou o comando abaixo para desconectar:

```
for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
  %windir%\System32\tscon.exe %%s /dest:console
)
```

**Comment by kerferber** [comment]
> Consegui instalar o bot em uma máquina virtual do Google com o servidor da Microsoft. Quando estou na máquina virtual, está tudo bem! Mas quando saio da máquina virtual, nada acontece. Parece que o Windows está cortando a tela ... Verifiquei corretamente, o computador não entra no modo de hibernação e não coloca o protetor de tela. Você tem alguma ideia?
> 
> //
> 
> I managed to install the bot on a google virtual machine with the microsoft server. When I am in the virtual machine, everything is fine! But when I leave the virtual machine, nothing happens. Looks like windows is cutting the display ... I have checked correctly, the computer does not go to sleep and does not put the screen saver. Do you have an idea?

Instalei aqui na VM no ubuntu e não tive este problema. Apenas desinstalei a proteção de tela

**Comment by nicolobi** [comment]
> Lorsque vous vous déconnectez de RDP, la session est verrouillée, voir #465
> 
> Besoin d'utiliser un autre logiciel d'accès à distance ou la commande ci-dessous pour vous déconnecter :
> 
> ```
> for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
>   %windir%\System32\tscon.exe %%s /dest:console
> )
> ```

Hello, thanks, 
Where can i write this command ??

**Comment by fguide** [comment]
@nicolobi 

Have a look here for reference:
https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html

**Comment by nicolobi** [comment]
> @nicolobi
> 
> Have a look here for reference: https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html

Thanks a lot ! it work !

**Comment by fguide** [comment]
Great, if you could please close the issue that be appreciated. Thanks
