### ISSUE TITLE
ERRO NO COMANDO pip install -r requirements.txt

### ISSUE THREAD

**Issue by g15zera** [mpcabete/bombcrypto-bot#506]
![ERRO PIPI](https://user-images.githubusercontent.com/96753340/147514609-bcc578f8-abd8-40ff-9427-65b50ee547c6.png)

**Comment by l1lb1g** [comment]
Desinstale a versão antiga do seu Phyton3
Instale a nova versão Phyton3
Instale a versão também pela Microsoft STORE
Instale novamente os arquivos do BOT (ATUALIZADOS)
Execute o bot como ----> "python index.py" (sem as aspas)
Tmj espero ter ajudado

**Comment by fguide** [comment]
Seu usuário do windows tem um caracter não UTF-8 (joão), faça instalação em c:\pyhon

Se não resolver, crie um usuário sem o ã
