### ISSUE TITLE
AJUDA - ERRO NO MOUSE SCROLL PARA O WORK

### ISSUE THREAD

**Issue by dokeby1** [mpcabete/bombcrypto-bot#509]
Galera, ja tentei de tudo, modifiquei imagens, tela 100%,90%,e todos % possiveis,
assim como, a linguagem sempre em ingles.
Na hora do bot selecionar o heroi para WORK, ele clica errado, clica no vão perto do work, mas nunca no work!
de resto, todas as imagens o bot clica certo.
O que pode ser ??

**Comment by RenanPFerreira** [comment]
Eu acredito que pode ser o campo offset. Tenta ajustar a linha 270 dentro do index.py 
de offset = 140
para offset = 130

**Comment by dokeby1** [comment]
Ola Renan, obrigado pelo retorno! Onde eh que eu ajusto essa linha?

**Comment by RenanPFerreira** [comment]
> Ola Renan, obrigado pelo retorno! Onde eh que eu ajusto essa linha?

Dentro do arquivo index.py, clica com botão direito e edita com notepad ++ ou bloco de notas mesmo, da um ctrl + F digita offset que deve achar.
