### ISSUE TITLE
Heroes não são selecionados 

### ISSUE THREAD

**Issue by rodtanci** [mpcabete/bombcrypto-bot#51]
Opa, parabéns pelo projeto, queria saber se tem como alterar a ordem que ele começa o jogo.. 
 A minha pergunta e pq o tempo que deixo pra ele ir em heroes ver quais estão na barra verde é de 50 minutos porque de 10 em 10 eles não estão cheio então é perca de tempo ir de 10 em 10, porem quando coloco 50 min o jogo da unknown antes então o macro reinicia faz o login e antes de dar os 50 minutos que seria pra puxar os heroes com isso ele não põe eles pra quebrar a caixa por conta que o jogo cai muito.

Ideal eu acho seria que roda vez que fizesse login ele fosse direto para os heroes depois para o mapa, acha possível alterar isso ou teria uma solução melhor que está ?

**Comment by mpcabete** [comment]
Olá, essa é uma solução muito boa! Vou colocar aqui na minha listinha de afazeres!
