### ISSUE TITLE
Bot not doing anything

### ISSUE THREAD

**Issue by WeHawt01** [mpcabete/bombcrypto-bot#510]
I launch the bot script with everything up to date the python everything. But it does not detect the game I don't know why. I open the hero menu to show the bar health of all my heroes nothing happens and the bot says 0.

![Capture d’écran 2021-12-28 033955](https://user-images.githubusercontent.com/96753610/147521930-68a724c1-7408-49c6-97c7-9cd6133b32a6.png)

**Comment by fguide** [comment]
Multiple displays? Try running on a single one to see if it works.

**Comment by gustavoholanda01** [comment]
Mano me chama lá no Whatsapp 21984269018, estou com o msm erro e antigamente rodava liso o bot e agr não funciona mais. esta aparecendo o msm erro que vc

**Comment by gustavoholanda01** [comment]
![Sem título](https://user-images.githubusercontent.com/96751804/147616510-9421d7d9-85e6-4e34-90ab-0d8cf462db40.png)

**Comment by WeHawt01** [comment]
> Multiple displays? Try running on a single one to see if it works.

no only one display one bomb crypto account. This was on single.
