### ISSUE TITLE
bot não inicia

### ISSUE THREAD

**Issue by rodtanci** [mpcabete/bombcrypto-bot#511]
Boa noite rapaziada, eu usava o bot antigamente e rodava liso até bloquearem ai parei de usar, fui voltar a usar agora que foi liberado e nao vai nem ferrando

Estou usando windows 7, Python 3.8.10 (ULTIMA VERSÃO DISPONIVEL PARA WINDOWS 7)

erro encontrado:

```
c:\bomb>python index.py
Traceback (most recent call last):
  File "index.py", line 7, in <module>
    from src.logger import logger, loggerMapClicked
  File "c:\bomb\src\logger.py", line 8, in <module>
    c = yaml.safe_load(stream)
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Ana Paula\AppData\Local\Programs\Python\Python38\lib\site-packa
ges\yaml\parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<block mapping
start>'
  in "./config.yaml", line 7, column 3
```

**Comment by rodtanci** [comment]
Ja reinstalei os requirements.txt e o python e não funcionou...

**Comment by rodtanci** [comment]
acebei de fazer um teste em outra maquina com windows 10, python 3.9.9 e acusou o mesmo erro, alguem pode me falar no que estou errando ? vlw

**Comment by l1lb1g** [comment]
Boas galera,
Então a forma de você solucionar esses dois erros são.

Erro WINDOWS

Desinstale a versão antiga do seu Phyton
Instale a nova versão que o link est no post oficial do bot
Faça o tutorial como descrito lá instalando novamente o bot ( não se esqueça de marcar launch quando instalar o phyton)
Erro Phyton3

Desinstale a versão antiga do seu Phyton3
Instale a nova versão Phyton3
Instale a versão também pela Microsoft STORE
Instale novamente os arquivos do BOT
Execute o bot como ----> "python index.py" (sem as aspas)
Tmj espero ter ajudado

**Comment by rodtanci** [comment]
> Boas galera, Então a forma de você solucionar esses dois erros são.
> 
> Erro WINDOWS
> 
> Desinstale a versão antiga do seu Phyton Instale a nova versão que o link est no post oficial do bot Faça o tutorial como descrito lá instalando novamente o bot ( não se esqueça de marcar launch quando instalar o phyton) Erro Phyton3
> 
> Desinstale a versão antiga do seu Phyton3 Instale a nova versão Phyton3 Instale a versão também pela Microsoft STORE Instale novamente os arquivos do BOT Execute o bot como ----> "python index.py" (sem as aspas) Tmj espero ter ajudado

A última versão suportada pelo Windows 7 é a 3.8.10. a partir da versão 3.9 não funciona

**Comment by gustavoholanda01** [comment]
Exatamente mano, esta acontecendo o mesmo comigo --win10, ja instalei versões antigas e as novas do python, instalei e desinstalei o bot -- pip install -r requirements.txt ... e não roda, ele fica parado o bot e antigamente rodava lisooo

**Comment by rodtanci** [comment]
Queria ter o arquivo antigo do bot mas perdi, o primeiro rodava liso pra mim

**Comment by gustavoholanda01** [comment]
eu tenho

Em qua., 29 de dez. de 2021 às 05:36, rodtanci ***@***.***>
escreveu:
