### ISSUE TITLE
Alguém sabe Oque pode ser esse erro?  ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by AndreFellipeRJ** [mpcabete/bombcrypto-bot#513]
Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python310\python.exe' 'C:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\ANDRFE~1\AppData\Local\Temp\tmp_zivpvbh'
         cwd: C:\Users\André Fellipe\AppData\Local\Temp\pip-install-nxspx3a4\pymsgbox_f959cc21e49547b8bf40c13a4ef9648f
    Complete output (14 lines):
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe9 in position 0: unexpected end of data (sitecustomize.py, line 21)
    running dist_info
    creating C:\Users\André Fellipe\AppData\Local\Temp\pip-modern-metadata-519ozsf_\PyMsgBox.egg-info
    writing C:\Users\André Fellipe\AppData\Local\Temp\pip-modern-metadata-519ozsf_\PyMsgBox.egg-info\PKG-INFO
    writing dependency_links to C:\Users\André Fellipe\AppData\Local\Temp\pip-modern-metadata-519ozsf_\PyMsgBox.egg-info\dependency_links.txt
    writing top-level names to C:\Users\André Fellipe\AppData\Local\Temp\pip-modern-metadata-519ozsf_\PyMsgBox.egg-info\top_level.txt
    writing manifest file 'C:\Users\André Fellipe\AppData\Local\Temp\pip-modern-metadata-519ozsf_\PyMsgBox.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\André Fellipe\AppData\Local\Temp\pip-modern-metadata-519ozsf_\PyMsgBox.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.py' under directory 'pymsgbox'
    writing manifest file 'C:\Users\André Fellipe\AppData\Local\Temp\pip-modern-metadata-519ozsf_\PyMsgBox.egg-info\SOURCES.txt'
    creating 'C:\Users\André Fellipe\AppData\Local\Temp\pip-modern-metadata-519ozsf_\PyMsgBox.dist-info'
    error: invalid command 'bdist_wheel'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7d/ff/4c6f31a4f08979f12a663f2aeb6c8b765d3bd592e66eaaac445f547bb875/PyMsgBox-1.0.9.tar.gz#sha256=2194227de8bff7a3d6da541848705a155dcbb2a06ee120d9f280a1d7f51263ff (from https://pypi.org/simple/pymsgbox/). Command errored out with exit status 1: 'C:\Program Files\Python310\python.exe' 'C:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\ANDRFE~1\AppData\Local\Temp\tmp_zivpvbh' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyMsgBox==1.0.9 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9)
ERROR: No matching distribution found for PyMsgBox==1.0.9
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by fguide** [comment]
> SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe9 in position 0: unexpected end of data (sitecustomize.py, line 21)
running dist_info

Seu usuário do windows tem caracter nao UTF-8 (C:\Users\Andr**é** Fellipe\). Tente usar um usuário sem caractere especiais.
