### ISSUE TITLE
Erro na segunda chamada refreshHeroes() ?

### ISSUE THREAD

**Issue by RenanPFerreira** [mpcabete/bombcrypto-bot#514]
Time, eu estou com o seguinte erro e queria saber se realmente é possível acontecer isso (devido os métodos serem iguais para todos)
O erro é o seguinte, o bot inicia normalmente, clica nos heróis, clica em work normal fecha e vai para treasure hunt.
Após 50 minutos que é o tempo que defini ele entra novamente na tela de heróis para procurar se tem alguém para trabalhar e ai fica em loop e não sai mais dessa tela.

Minha dúvida é, realmente pode ser algum bug? Pois a primeira vez funciona normal, o método def refreshHeroes(): 

Aqui começou a ficar em loop 
![image](https://user-images.githubusercontent.com/31439911/147560581-458e89ec-8297-4dbb-9282-de3dd711a7b6.png)

E depois de umas horas só ficou nesse log
![image](https://user-images.githubusercontent.com/31439911/147560649-41c0652a-de4f-40fe-b11c-92788f5f33bc.png)

Já testei com o threshold do  go_to_work_btn em 0.9 / 0.6 e 1 
Estou sem idéias de config e do que fazer para rodar 100%.

**Comment by fguide** [comment]
SIm, é um bug, eu fiz um PR que corrigiu isso #482 porem eu só apliqueio pro clickGreenBars, precisa tb fazer pros outros modos de clique, basicamente é um problema com o contador, depois de enviar +20 herois ele comeca com o erro de too many clicks.

**Comment by RenanPFerreira** [comment]
> SIm, é um bug, eu fiz um PR que corrigiu isso #500 porem nao foi feito o merge, mas basicamente é um problema com o contador, depois de enviar +20 herois ele comeca com o erro de too many clicks.
> 
> Edit: Desculpe, confundi os assuntos, agora esta certo

Só comentar então a linha 467 **if buttonsClicked == 0:** e boa?
Ou preciso alterar algo nessa linha também ? **empty_scrolls_attempts = empty_scrolls_attempts - 1**

**Comment by fguide** [comment]
Você precisa mudar disso:

```
    if buttonsClicked == 0:
        empty_scrolls_attempts = empty_scrolls_attempts - 1
```

Para: 

```

       #if buttonsClicked == 0:
       #    empty_scrolls_attempts = empty_scrolls_attempts - 1
        empty_scrolls_attempts -= 1
```

**Comment by RenanPFerreira** [comment]
> Você precisa mudar disso:
> 
> ```
>     if buttonsClicked == 0:
>         empty_scrolls_attempts = empty_scrolls_attempts - 1
> ```
> 
> Para:
> 
> ```
> 
>        #if buttonsClicked == 0:
>        #    empty_scrolls_attempts = empty_scrolls_attempts - 1
>         empty_scrolls_attempts -= 1
> ```

Beleza! Feito aqui, vou alterar e diminuir o tempo para verificar heróis para testar. Valeu

**Comment by RenanPFerreira** [comment]
Com essa alteração abaixo tá saindo da tela quando chama pela segunda vez os heróis, percebi que clica 3 vezes no meu segundo herói não sei por qual motivo ainda, mas já é um grande avanço e da para rodar de forma mais automática, vou testar por algumas horas para ver o comportamento.

       #if buttonsClicked == 0:
       #    empty_scrolls_attempts = empty_scrolls_attempts - 1
        empty_scrolls_attempts -= 1
