### ISSUE TITLE
Trabalhando com zoom diferente de 100%

### ISSUE THREAD

**Issue by neemiasbj** [mpcabete/bombcrypto-bot#515]
Bom dia,

Gostaria de saber como trabalhar com zoom diferente de 100% sem ter que tter uma imagem para cada zoom.
Alterei o bot para tarbalhar 100% multi account, porém quando tem que diminuir o zoom para adicionar mais contas na tela, tenho que refazer todas as imagens para o zoom que estou utilizando no momento.
@mpcabete é possível?

**Comment by Nucito** [comment]
> Bom dia,
> 
> Gostaria de saber como trabalhar com zoom diferente de 100% sem ter que tter uma imagem para cada zoom. Alterei o bot para tarbalhar 100% multi account, porém quando tem que diminuir o zoom para adicionar mais contas na tela, tenho que refazer todas as imagens para o zoom que estou utilizando no momento. @mpcabete é possível?

Possível é... mas daria mt trabalho sksksksk
