### ISSUE TITLE
Guys, is it possible to do this?

### ISSUE THREAD

**Issue by sds3777** [mpcabete/bombcrypto-bot#516]
My wallet is hacked, all tokens that appear in it the hacker transferred to him manually.  I would like to know if there is some way that all the tokens that fall into my wallet would automatically be transferred to my new wallet.  I have a friend who was hacked and it seems that his wallet has a bot, if it drops 0.00001 it is automatically sent to another wallet.  How do you do this?

**Comment by fguide** [comment]
I'm afraid this deviates from this projects subjects, so I'm sorry but we cannot help you. I suggest contacting metamask support and taking security measurements to avoid being hacked again.

Also, if the hacker transferred it directly you secret phrase and password are already compromised so I see no reason to keep using this wallet.
