### ISSUE TITLE
MEU BOT N CLICA NO CONNECT WALLET

### ISSUE THREAD

**Issue by Lemocas** [mpcabete/bombcrypto-bot#518]
todos os outros requesitos ele aplica com maestria e certeza, mas apenas o connect wallet ele nao esta clicando, como resolver este erro?

**Comment by kerferber** [comment]
aqui estava acontecendo isso, mas sem querer havia alterado o zoom do navegador para 90%, foi só alterar pra 100% e voltou a clicar no connect. já testou?
