### ISSUE TITLE
Estou tendo esse erro frequentemente.

### ISSUE THREAD

**Issue by rzanca** [mpcabete/bombcrypto-bot#519]
Não sei o que pode ser, mas ele para de farmar e trava as vezes nisso.

File "index.py", line 527, in <module>
    main()
  File "index.py", line 512, in main
    refreshHeroesPositions()
  File "index.py", line 324, in refreshHeroesPositions
    clickBtn(images['go-back-arrow'])
  File "index.py", line 165, in clickBtn
    moveToWithRandomness(pos_click_x,pos_click_y,1)
  File "index.py", line 82, in moveToWithRandomness
    pyautogui.moveTo(addRandomness(x,10),addRandomness(y,10),t+random()/2)
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/__init__.py", line 597, in wrapper
    failSafeCheck()
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/__init__.py", line 1722, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.
root@4b051db46a05:~/Desktop/bombcrypto-bot#

**Comment by fguide** [comment]
Você moveu o mouse pro canto da tela e fez o script falhar por conta do fail safe do pyautogui.

É recomendável nao usar o mouse ou alterar a conifiguração do failsafe.

**Comment by rzanca** [comment]
Pior que estou rodando na VM Google Cloud, com o Desktop Remote.

Sistema rodando Debian, e as Dockers de ubuntu xfce. 

E uma vez apresentou mesmo sem usar o remote.

**Comment by fguide** [comment]
Se você realmente usa em VM pode tentar adicionar a linha abixo para desabilitar o failsafe, nao é recomendavel mas deve resolver 

>pyautogui.FAILSAFE = True

**Comment by jeanvetorello** [comment]
esse ultimo commit tiraram isso ai só colcocar  novamente no seu index.py

pyautogui.FAILSAFE = False

**Comment by rzanca** [comment]
Valeu pessoal, 100% agora.
