### ISSUE TITLE
Tive um problema

### ISSUE THREAD

**Issue by sdn666** [mpcabete/bombcrypto-bot#52]
Não tava reconectando, alterei o select_wallet_buttons colocando 1, refiz os prints e agora roda perfeito no chrome, no opera nao funciona por contado reconect que a meta abre toda zuada  mas ta lindo, obrigado pelo trabalho irmao!

Meus comuns rendendo os 40 te mando alguma coisa!

**Comment by eduabc** [comment]
Man to tentando e não consigo, poderia me salvar postando as imagem que tu refez pra ver se funciona aqui man?

**Comment by lobomfz** [comment]
tenta usar minha fork, não está 100% completa mas ja da pra usar https://github.com/lobomfz/bombcrypto-bot
