### ISSUE TITLE
Erro ao Rolar Lista de Heróis Para Verificar e Coloca-los para trabalhar

### ISSUE THREAD

**Issue by Xkarrior** [mpcabete/bombcrypto-bot#520]
Pessoal, alguém com o mesmo erro? Alguém poderia ajudar?

O Bot roda blz, já reinstalei o Python, o Bot e todo resto. Interessante que também tentei em outro pc e estou com o mesmo erro.

Quando o Bot clica no botão de heróis a janela se abre e ele verifica apenas se os cinco que aparecem estão aptos para o trabalho, ele não rola a lista de herói para verificar o restante .....

Alguma dica?

**Comment by Xkarrior** [comment]
Vi o tópico "AJUDA - ERRO NO MOUSE SCROLL PARA O WORK" ... Não é o mesmo erro .... Essa pessoa está tendo erro ao clicar, clicando em local errado ... Não é o meu caso.

**Comment by Alt4s** [comment]
Já tentou substituir a imagem do common?

**Comment by Xkarrior** [comment]
Sim, já fiz e continua a mesma coisa ... Li em outro tópico, alguém sugeriu mudar por LV ... todos meus heróis sao LV3 mudei e continuou a mesma coisa, manda trabalhar apenas os herois da primeira tela, não rola a lista de heroi e sai ..... 

O meu jogo está inglês tb .... O que poderia ser a causa ... mudar a língua .....

Se dúvida tem haver com os heróis, mas não sei o que é ...

**Comment by Alt4s** [comment]
@mpcabete

**Comment by Xkarrior** [comment]
Como foi dito em outro tópico, tem haver com uma lista de heróis boas ... Sem comuns por exemplo ..... Tenho apenas 3 comuns que ficam lá em baixo .... 

Já tentei deixar um comum trabalhando e testar, para quando entrar na tela esse comum está em cima .... Não mudou nada ....

Já percebi que de forma aleatória e raramente ele rola a tela de heróis ...

**Comment by fguide** [comment]
Se o mouse não movimenta é porque ele falha para achar algo em comum na tela dos herois. Você pode tentar fazer um screenshot só do L por exemplo e mudar a configuração 'commom' no arquivo config.yaml e colocar um valor mais baixo, por exemplo 0.7.

Ou aumentar o parametro, talvez esteja muito baixo e achando muitos, por isso da erro no retorno da funcao.

**Comment by rzanca** [comment]
Utilize uma imagem do LV ou de algum raro. Pra mim ambas funcionaram.

**Comment by VitotEPB** [comment]
Aqui está acontecendo o mesmo erro. Não está rolando até meus últimos 3 heróis (tenho só 3 comuns). Já na conta full comum ele rola normalmente.

**Comment by VitotEPB** [comment]
> Utilize uma imagem do LV ou de algum raro. Pra mim ambas funcionaram.

Fiz exatamente o que o amigo indicou e funcionou. Substitua o common-text por uma imagem do das letras LV (sem o número)

**Comment by Xkarrior** [comment]
Interessante, já tentei tudo que foi mencionado, alterei os valores do common, mudei as imagens colocando LV, LV3, Rare e outros. 

Os botões são identificados, mas não rola para os demais heróis.

Testei em mais de um Pc. Estou sem opções.

**Comment by fguide** [comment]
@Xkarrior nao faz scroll? Tem um problema de scroll infinito que resolveu em #470, acho que nao é o mesmo sintoma mas nao custa tentar tb...

**Comment by fguide** [comment]
@Xkarrior  tente fazer o teste e avise.

**Comment by Xkarrior** [comment]
@fguide agradeço o auxilio. Ainda não funcionou .;... Fiz a tentativa na integra ....
Ao entrar na tela de herois dá erro e sai do bot ..

Traceback (most recent call last):
  File "C:\botold\index.py", line 527, in <module>
    main()
  File "C:\botold\index.py", line 496, in main
    refreshHeroes()
  File "C:\botold\index.py", line 449, in refreshHeroes
    scroll()
  File "C:\botold\index.py", line 204, in scroll
    x,y,w,h = commoms[len(commoms)-1]
IndexError: tuple index out of range

**Comment by waltimgv** [comment]
> Pessoal, alguém com o mesmo erro? Alguém poderia ajudar?
> 
> O Bot roda blz, já reinstalei o Python, o Bot e todo resto. Interessante que também tentei em outro pc e estou com o mesmo erro.
> 
> Quando o Bot clica no botão de heróis a janela se abre e ele verifica apenas se os cinco que aparecem estão aptos para o trabalho, ele não rola a lista de herói para verificar o restante .....
> 
> Alguma dica?

man eu tava com o mesmo problema em que vc, so tenho 3 hero comum e sao os ultimos, eles nao carregava o scroll pra baixo, eu mudei a imagem do commun para super raro e deu certo

**Comment by Xkarrior** [comment]
@waltimgv Já troquei por SUPER RARO tb, mas não funcionou aqui. Já tentei de tudo ... rs. Valeu pela ajuda

**Comment by waltimgv** [comment]
> @waltimgv Já troquei por SUPER RARO tb, mas não funcionou aqui. Já tentei de tudo ... rs. Valeu pela ajuda

tenta o raro

**Comment by Xkarrior** [comment]
@waltimgv Já tentei amigo, com todos ... com LV, com LV3 (todos meus são) nada dá certo

**Comment by fguide** [comment]
> @fguide agradeço o auxilio. Ainda não funcionou .;... Fiz a tentativa na integra .... Ao entrar na tela de herois dá erro e sai do bot ..
> 
> Traceback (most recent call last): File "C:\botold\index.py", line 527, in main() File "C:\botold\index.py", line 496, in main refreshHeroes() File "C:\botold\index.py", line 449, in refreshHeroes scroll() File "C:\botold\index.py", line 204, in scroll x,y,w,h = commoms[len(commoms)-1] IndexError: tuple index out of range

Comenta a linha x,y,w,h = commoms[len(commoms)-1] onde está dando o erro, fica:

:#x,y,w,h = commoms[len(commoms)-1]

Veja se da certo

**Comment by fguide** [comment]
> > @fguide agradeço o auxilio. Ainda não funcionou .;... Fiz a tentativa na integra .... Ao entrar na tela de herois dá erro e sai do bot ..
> > Traceback (most recent call last): File "C:\botold\index.py", line 527, in main() File "C:\botold\index.py", line 496, in main refreshHeroes() File "C:\botold\index.py", line 449, in refreshHeroes scroll() File "C:\botold\index.py", line 204, in scroll x,y,w,h = commoms[len(commoms)-1] IndexError: tuple index out of range
> 
> Comenta a linha x,y,w,h = commoms[len(commoms)-1] onde está dando o erro, fica:
> 
>#x,y,w,h = commoms[len(commoms)-1]
> 
> Veja se da certo

**Comment by Xkarrior** [comment]
Junto ao bot não consegui uma solução adequada. Para resolver o meu problema eu baixou um Macro Recorder, fiz um macro apenas para rolagem e work dos heróis e ativei ele para realizar a operação de 1 em 1 hora. Deixo os dois bots rodando simultaneamente ... Por hora foi a solução que achei.

**Comment by thereis** [comment]
@Xkarrior estou com o mesmo problema. Tentarei corrigir aqui e o avisarei caso consiga.

**Comment by thereis** [comment]
@Xkarrior fiz na base da gambiarra:

esse método estava impedindo que selecionasse os heróis pra trabalhar. Comentei as seguintes linhas e bingo!

```python
def scroll():
    # commoms = positions(images['commom-text'], threshold=ct['commom'])
    # if (len(commoms) == 0):
    #     return
    # x, y, w, h = commoms[len(commoms)-1]
    #
    # moveToWithRandomness(x, y, 1)

    if not c['use_click_and_drag_instead_of_scroll']:
        pyautogui.scroll(-c['scroll_size'])
    else:
        pyautogui.dragRel(0, -c['click_and_drag_amount'],
                          duration=1, button='left')
```

**Comment by Xkarrior** [comment]
> @Xkarrior fiz na base da gambiarra:
> 
> esse método estava impedindo que selecionasse os heróis pra trabalhar. Comentei as seguintes linhas e bingo!
> 
> ```python
> def scroll():
>     # commoms = positions(images['commom-text'], threshold=ct['commom'])
>     # if (len(commoms) == 0):
>     #     return
>     # x, y, w, h = commoms[len(commoms)-1]
>     #
>     # moveToWithRandomness(x, y, 1)
> 
>     if not c['use_click_and_drag_instead_of_scroll']:
>         pyautogui.scroll(-c['scroll_size'])
>     else:
>         pyautogui.dragRel(0, -c['click_and_drag_amount'],
>                           duration=1, button='left')
> ```

Solução Perfeita, problema resolvido. Está rolando os heróis e selecionando os green, conforme configurado. Muito Obrigado por compartilhar essa solução.

**Comment by thereis** [comment]
@Xkarrior eu criei um PR com a correção desse comportamento, é melhor do que essa gambiarra que te mandei, se puder usar no seu projeto, acredito que funcione sem problemas.

#560

**Comment by Xkarrior** [comment]
@thereis Eu vi lá ...

**Comment by Juninhox13** [comment]
> > @Xkarrior fiz na base da gambiarra:
> > esse método estava impedindo que selecionasse os heróis pra trabalhar. Comentei as seguintes linhas e bingo!
> > ```python
> > def scroll():
> >     # commoms = positions(images['commom-text'], threshold=ct['commom'])
> >     # if (len(commoms) == 0):
> >     #     return
> >     # x, y, w, h = commoms[len(commoms)-1]
> >     #
> >     # moveToWithRandomness(x, y, 1)
> > 
> >     if not c['use_click_and_drag_instead_of_scroll']:
> >         pyautogui.scroll(-c['scroll_size'])
> >     else:
> >         pyautogui.dragRel(0, -c['click_and_drag_amount'],
> >                           duration=1, button='left')
> > ```
> 
> Solução Perfeita, problema resolvido. Está rolando os heróis e selecionando os green, conforme configurado. Muito Obrigado por compartilhar essa solução.

Eu fiz isso, ele realmente mudou o lugar onde clica pra scrollar. porem ainda na hora de clicar no WORK ele insiste em clicar sempre abaixo do botao. queria aprender só editar o scroll dele. pra poder por certinho de 5 em 5 na tela, pq fica sempre um pela metade e tira o click do bot sempre

**Comment by rzanca** [comment]
> > > @Xkarrior fiz na base da gambiarra:
> > > esse método estava impedindo que selecionasse os heróis pra trabalhar. Comentei as seguintes linhas e bingo!
> > > ```python
> > > def scroll():
> > >     # commoms = positions(images['commom-text'], threshold=ct['commom'])
> > >     # if (len(commoms) == 0):
> > >     #     return
> > >     # x, y, w, h = commoms[len(commoms)-1]
> > >     #
> > >     # moveToWithRandomness(x, y, 1)
> > > 
> > >     if not c['use_click_and_drag_instead_of_scroll']:
> > >         pyautogui.scroll(-c['scroll_size'])
> > >     else:
> > >         pyautogui.dragRel(0, -c['click_and_drag_amount'],
> > >                           duration=1, button='left')
> > > ```
> > 
> > 
> > Solução Perfeita, problema resolvido. Está rolando os heróis e selecionando os green, conforme configurado. Muito Obrigado por compartilhar essa solução.
> 
> Eu fiz isso, ele realmente mudou o lugar onde clica pra scrollar. porem ainda na hora de clicar no WORK ele insiste em clicar sempre abaixo do botao. queria aprender só editar o scroll dele. pra poder por certinho de 5 em 5 na tela, pq fica sempre um pela metade e tira o click do bot sempre

A função que escolhe os heróis não é a mesma da que ele usa para o scroll, tente outra versão do bot, https://github.com/rzanca/bombcrypto-multibot/
