### ISSUE TITLE
Qual o método de funcionamento dos bonecos?

### ISSUE THREAD

**Issue by guimatheus92** [mpcabete/bombcrypto-bot#522]
Acredito que falta um pouco de explicação referente a esse bot, mas achei o trabalho muito bom!
Os bonecos da conta são colocados pra trabalhar somente com Full Stamina através da imagem `full-stamina.png`?

E se eu quiser que ele coloque TODOS os bonecos, como faz?
Porque aqui, o bot não está fazendo NADA.

Log:

> ←[99m[2021-12-28 22:32:31] => 🏢 Search for heroes to work←[0m
←[99m[2021-12-28 22:32:31] => ⬆️ Processing last action..←[99m.←[99m.
←[99m[2021-12-28 22:32:42] => 🟩 0 green bars detected←[0m
←[99m[2021-12-28 22:32:42] => 🆗 0 buttons detected←[0m
←[99m[2021-12-28 22:32:45] => 🟩 0 green bars detected←[0m
←[99m[2021-12-28 22:32:46] => 🆗 0 buttons detected←[0m
←[99m[2021-12-28 22:32:48] => 🟩 0 green bars detected←[0m
←[99m[2021-12-28 22:32:49] => 🆗 0 buttons detected←[0m
←[99m[2021-12-28 22:32:51] => 💪 0 heroes sent to work←[0m

**Comment by KamuiDC** [comment]
Eles são colocados quando estão com stamina verde. Pode ser alterado no config.
![image](https://user-images.githubusercontent.com/96802691/147620007-0430b25c-8bd5-42de-9b31-e201d4ffbc7f.png)

**Comment by guimatheus92** [comment]
> Eles são colocados quando estão com stamina verde. Pode ser alterado no config. ![image](https://user-images.githubusercontent.com/96802691/147620007-0430b25c-8bd5-42de-9b31-e201d4ffbc7f.png)

Ele funciona em qualquer navegador? To usando o brave.
De qualquer forma, alterei para `all` e mesmo assim o bot não faz nada, não clicou em Connect Wallet pra iniciar e não faz nenhum processo depois que eu começo o game.

**Comment by AnderRobson** [comment]
> > Eles são nascidos quando estão com stamina verde. Pode ser alterado sem configuração.![imagem](https://user-images.githubusercontent.com/96802691/147620007-0430b25c-8bd5-42de-9b31-e201d4ffbc7f.png)
> 
> Ele funciona em qualquer navegador? Para usar o bravo. De qualquer forma, alterei para `all`e mesmo assim o bot não faz nada, não clique em Connect Wallet pra iniciar e não faz nenhum processo depois que eu começo o jogo.

Verifique os prints dentro da pasta **targets**, atualizar os prints para os mesmo tirado para a sua tela do game ajuda a resolver esse problema.

**Comment by fguide** [comment]
> > Eles são colocados quando estão com stamina verde. Pode ser alterado no config. ![image](https://user-images.githubusercontent.com/96802691/147620007-0430b25c-8bd5-42de-9b31-e201d4ffbc7f.png)
> 
> Ele funciona em qualquer navegador? To usando o brave. De qualquer forma, alterei para `all` e mesmo assim o bot não faz nada, não clicou em Connect Wallet pra iniciar e não faz nenhum processo depois que eu começo o game.

Tem várias questões, resolução da tela, multiplos monitores, etc Seria bom tentar no setup "padrao": 1 monitor, resolucao de pelo menos 1115x862

**Comment by guimatheus92** [comment]
> > > Eles são colocados quando estão com stamina verde. Pode ser alterado no config. ![image](https://user-images.githubusercontent.com/96802691/147620007-0430b25c-8bd5-42de-9b31-e201d4ffbc7f.png)
> > 
> > 
> > Ele funciona em qualquer navegador? To usando o brave. De qualquer forma, alterei para `all` e mesmo assim o bot não faz nada, não clicou em Connect Wallet pra iniciar e não faz nenhum processo depois que eu começo o game.
> 
> Tem várias questões, resolução da tela, multiplos monitores, etc Seria bom tentar no setup "padrao": 1 monitor, resolucao de pelo menos 1115x862
> 
> Navegador eu já testei no firefox, chrome e brave, sem erros.

Resolução é 1920x1080, monitor unico, alterei a variavel para `all`, complicado de entender o porquê não vai. Aparentemente as imagens na pasta Target tão são iguais, mas estou olhando aqui.

**Comment by fguide** [comment]
Qual configuracao de scaling (nao sei o termo em portugues) do monito? 100%, 125% ? Ideal seria em 100%, e o navegador tb deve estar com 100%.

Outra coisa que é meio obvia mas é bom lembrar é que o jogo deve ficar como principal na tela, se houver outras coisas por cima (janela do cmd por exemplo) a detecção pode falhar...

**Comment by guimatheus92** [comment]
> Qual configuracao de scaling (nao sei o termo em portugues) do monito? 100%, 125% ? Ideal seria em 100%, e o navegador tb deve estar com 100%.
> 
> Outra coisa que é meio obvia mas é bom lembrar é que o jogo deve ficar como principal na tela, se houver outras coisas por cima (janela do cmd por exemplo) a detecção pode falhar...

A tela do jogo estava unica na tela sim rs
Navegador a 100%
Porém não sabia da escala da tela, ótima observação! Estava em 125% antes, mudei pra 100% e funcionou!!

**Comment by guimatheus92** [comment]
> > Qual configuracao de scaling (nao sei o termo em portugues) do monito? 100%, 125% ? Ideal seria em 100%, e o navegador tb deve estar com 100%.
> > Outra coisa que é meio obvia mas é bom lembrar é que o jogo deve ficar como principal na tela, se houver outras coisas por cima (janela do cmd por exemplo) a detecção pode falhar...
> 
> A tela do jogo estava unica na tela sim rs Navegador a 100% Porém não sabia da escala da tela, ótima observação! Estava em 125% antes, mudei pra 100% e funcionou!!

Porém ele não está colocando nenhum outro boneco pra tralhar (somente os que eu tinha deixado trabalhando), eu coloquei `all` no arquivo `.yaml`, tem mais alguma outra configuração que precisa fazer?

**Comment by cleitonleonel** [comment]
Versão "multijanelas" no linux caso alguém quiser testar, fiz de 2 modos diferentes, uma semelhante ao controle de abas sugerido aqui, porém com tab infinito e outro utilizando funções do server X do linux, para controlar as janelas existem ainda os bugs de demorar clicar para entrar, controle de botões,mas pelo que percebi isso ocorre em todas as versões do projeto...bom segue o link para quem usar linux e quiser testar...[bombcrypto-bot](https://github.com/cleitonleonel/bombcrypto-bot.git )
