### ISSUE TITLE
Bot is not finding the game

### ISSUE THREAD

**Issue by coolwateRx3** [mpcabete/bombcrypto-bot#523]
Dear Team,

I am starting the bot like in the instruction but unfortuntely it seems like it doesn't find the game.

I have no second screen an am closing every application besides the necessary ones, but it doesn't work.

Thank you for your help in advance

![image](https://user-images.githubusercontent.com/96804038/147620393-2a652a0b-feca-4154-9b3c-b2386113c2a3.png)

**Comment by AnderRobson** [comment]
Ola, @coolwateRx3,

Verifiquei se você está executando o código e trocando para a tela do navegador a onde está aberto o seu jogo e deixando ele tela inteira.
Segunda situação, é verificar os arquivos de imagens dentro da pasta **targets**, vale a pena atualizar os imagens para print-screen da sua tela do jogo, isso ajuda ele a reconhecer melhor os botões.

Qualquer coisa fico a disposição.

**Comment by coolwateRx3** [comment]
Hello @AnderRobson ,

I tried to run in full screen and I updated the target folder. But still no reaction :/

**Comment by coolwateRx3** [comment]
I already implemented new images. It still doesn't work (it doesn't find the buttons ingame. If I have the target-folder open, the bot is active and clicks on these images instead)
