### ISSUE TITLE
Multi tela SuperWide

### ISSUE THREAD

**Issue by diogobittar** [mpcabete/bombcrypto-bot#524]
Olá Amigos, acredito que tenha feito tudo corretamente, porem quando o mouse movimenta (não são todas as vezes) ele pula de uma tela para outra, tentei algumas versões aqui que até ficam na mesma tela, mas não clicam no local certo.
tenho 2 monitores super widescreen, mouse uso sensibilidade 14 do Windows (comento isso porque não sei se influencia).
Poderiam me ajudar ? Abraços

OBS: tenho 3 contas mas tentei apenas como 1 para não dar BO, alem dos erros acima existe alguma versão para multi conta?

**Comment by Igorlegacy** [comment]
Cara, a melhor solução para isso e até mais segura para sua carteira metamask é criar uma VM no seu PC e deixar rodando lá.. Dentro da VM você consegue criar mais de 1 usuário e acessar estes usuários por conexão remota do próprio Windows, assim você pode minimizar a VM ou as conexões que vai continuar rodando lá de boas...

Além que concentrar tudo dentro da VM diminui os riscos de infecção por virus ou alguns outros scams da metamask

**Comment by fguide** [comment]
> Cara, a melhor solução para isso e até mais segura para sua carteira metamask é criar uma VM no seu PC e deixar rodando lá.. Dentro da VM você consegue criar mais de 1 usuário e acessar estes usuários por conexão remota do próprio Windows, assim você pode minimizar a VM ou as conexões que vai continuar rodando lá de boas...
> 
> Além que concentrar tudo dentro da VM diminui os riscos de infecção por virus ou alguns outros scams da metamask

+1 para essa sugestão, facilita muito o uso do computador para outras atividades.

**Comment by diogobittar** [comment]
Entendido, e vc sugerem algum os que não consuma tanto recurso (afinal serão 3 VMs).

Abraços

**Comment by fguide** [comment]
Olha, infelizmente não tem muito como poupar recursos, o jogo em si é uma bomba (trocadilho :rofl)
Mas o que dá pra você fazer já que vai usar 3 contas é:

Fazer uma VM com boa disponibilidade de recursos, vcpu, ram, etc
Instalar algum linux com o minimo possivel de pacotes e um ambiente grafico mais leve (openbox ou i3wm eu sugiro, mas tem outros mais amigaveis) e colocar o ambiente grafico para NAO iniciar com boot

Instala o vncserver e roda 3 sessoes, cada uma tem o seu display e dai vc roda o bot em cada sessao.

Esse setup consome menos recursos do que 3 VMs, experiencia propria...

Infelizmente eu to sem tutoriais na mao, mas aqui mesmo nos issues ja postaram muito sobre isso, de uma olhada nos issues todo, inclusive os closed.

**Comment by Igorlegacy** [comment]
Cara, tem um esquema meio bobo mas que funciona muito bem... usei por um tempo,

Você cria 1 VM com uma config legalzinha, para até umas 4 contas você pode utilizar 4GB/ 2 ou 4 núcleos, ativa a aceleração gráfica coloca 256mb de memoria.  

No caso do windows server 2012, você abre 1 conexão que vai ser a principal e dentro dela você abre outras conexões na mesma maquina com usuários diferente, configura as contas conforme sua necessidade.

Quando for deslogar da conexão remota, joga a 1ª conexão pro console, para que não de lock e todos os demais usuários que estavam lá dentro vai ficar todos em uso normalmente.

Você pode adicionar o VNC Server para acessos externos como celular para acompanhar.


Outra opção é utilizar o bot que joga em multicontas (adaptação para ficar dando alt-tab) tem nos Pull Request, você abre 1 maquina apenas e configura as 3 contas com essa adaptação do bot. Tem alguns problemas no funcionamento, mas com o tempo você pega o jeito.

Toda vez que precisar executar a VM use a opção de Headless que consome menos recurso pois executa tipo "minimizado".

**Comment by fguide** [comment]
Eu nao consigo testar no windows, mas por acaso vocês ja testaram o recurso de virtual desktops?Win+Tab

talvez de certo pra rodar vários ao mesmo tempo com isso
