### ISSUE TITLE
PROBLEMA AO COLOCAR PARA TRABALHAR

### ISSUE THREAD

**Issue by PetersonMuller** [mpcabete/bombcrypto-bot#525]
O meu bot começa normal até abrir a pagina Heros, la ele ta clicando embaixo no botão work e fica descendo a pagina até chegar no final e entrar em loop.

Ja testei outras resoluções e zoom do navegador

**Comment by fguide** [comment]
Mas ele clica em work ou nao?

**Comment by fguide** [comment]
#522 veja o scaling do seu pc

**Comment by PetersonMuller** [comment]
> #522 veja o scaling do seu pc



> Mas ele clica em work ou nao?

Não, ele errava o clique, mas o problema era que tenho 2 monitores e tava dando problema, se eu desativo um funciona normal

**Comment by PetersonMuller** [comment]
Se alguem estiver tendo o mesmo problema e usa 2 monitores, só desativar o segundo quando for usar o bot, que vai funcionar normal.

**Comment by fguide** [comment]
Boa, depois feche o issue quando possível.
