### ISSUE TITLE
Não consigo rodar o BOT no Macbook Pro. Alguém conseguiu em algum Mac?

### ISSUE THREAD

**Issue by giulianoaccorsi** [mpcabete/bombcrypto-bot#526]
Utilizo o bot em computares Windows e funciona perfeitamente. Porém estou com uma imensa dificuldade em fazer o bot rodar no Macbook. Alguém conseguiu já? Poderia me dar uma ajuda?

**Comment by giulianoaccorsi** [comment]
Ja instalei utilizando o pip3 e ja tenho o xcode baixado

**Comment by Marques1233** [comment]
Cara instala uma máquina virtual com ubuntu, sem dor de cabeça

**Comment by rcomparim** [comment]
eu tbm nao consegui no meu!

**Comment by Williandasilvacode** [comment]
> Cara instala uma máquina virtual com ubuntu, sem dor de cabeça

como vc conseguiu roda 2 contas no ubuntu, estou tentando aqui, e não estou conseguindo, o que vc mudou para funciona?

**Comment by jiraspiom** [comment]
O bot inicia, ou não acha os locais para clicar. 
no meu caso eu fiz iniciar, porem ele ainda não achou os locais para clicar.

**Comment by mfzaguiar** [comment]
Macbook m1, aqui também não vai, inicia o bot mas sem ação nenhuma no navegador.

**Comment by rzanca** [comment]
> Macbook m1, aqui também não vai, inicia o bot mas sem ação nenhuma no navegador.

Chegou a tentar trocar os targets?

**Comment by moratelli** [comment]
Instala numa VM na Cloud e esquece ele lá. Melhor que ficar gastando o seu Macbook com Bomb.

**Comment by danielapassos** [comment]
Alguem conseguiu rodar no Mac?
