### ISSUE TITLE
Windows 10 issue

### ISSUE THREAD

**Issue by PromediaB** [mpcabete/bombcrypto-bot#53]
Hello,

After setup of requirement with pip without any issue, im getting error 
<img width="968" alt="Capture d’écran 2021-11-22 à 12 11 18" src="https://user-images.githubusercontent.com/51176677/142851906-a6cadf33-b72f-429b-abbf-a206d1a8b8aa.png">

Windows 10

**Comment by Rout222** [comment]
run pip install -r requirements.txt on the folder

**Comment by e9857** [comment]
Do you have 1 python version installed?
I had this error because have 2 versions installed...
