### ISSUE TITLE
Nada acontece ao executar em uma Nova Maquina Virtual Azure.

### ISSUE THREAD

**Issue by LupusTriskell** [mpcabete/bombcrypto-bot#530]
Abri uma maquina virtual no Microsoft Azure, instalei o Python e a dependecia do bot, porem ao executar o comando de inicio, nada acontece, literalmente. Ele so vai para proxima linha do CMD ser retornar nada. Alguem sabe se existe alguma outra dependencia a ser insitalada? Do proprio Python ou outras como Microsoft C++ Runtime Package por exemplo?

**Comment by fguide** [comment]
Ajudaria se colocasse um log do cmd para ver se está detectando os botões, barras, etc...

Você pode testar as sugestões de #522 e ver se alguma delas é o seu caso.

**Comment by LupusTriskell** [comment]
![image](https://user-images.githubusercontent.com/59267131/147705973-67765b58-983a-43da-aabf-0f062d1a1572.png)

Como eu disse, nao retorna NADA.

**Comment by LupusTriskell** [comment]
![image](https://user-images.githubusercontent.com/59267131/147706487-401de3c2-c8c2-4931-ba9a-e1236ab75ad1.png)


O comando para iniciar o bot simplesmente nao retorna nada......

**Comment by fguide** [comment]
tente só python index.py

**Comment by Igorlegacy** [comment]
Quando fez a instalação do python, você setou o path no inicio da instalação?

**Comment by LupusTriskell** [comment]
> tente só python index.py

Funcionou, obrigado!
