### ISSUE TITLE
Error at pip install -r requirements.txt

### ISSUE THREAD

**Issue by joaoaspimienta** [mpcabete/bombcrypto-bot#531]
I get this error:

Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\João\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\João\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\JOO~1\AppData\Local\Temp\tmpg6v8ufcy'
       cwd: C:\Users\João\AppData\Local\Temp\pip-install-nmkek9t4\pymsgbox_4742596aaf62470fbd4a9fad90e92e2f
  Complete output (14 lines):
  Error in sitecustomize; set PYTHONVERBOSE for traceback:
  SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe3 in position 0: unexpected end of data (sitecustomize.py, line 7)
  running dist_info
  creating C:\Users\João\AppData\Local\Temp\pip-modern-metadata-v1u94j0l\PyMsgBox.egg-info
  writing C:\Users\João\AppData\Local\Temp\pip-modern-metadata-v1u94j0l\PyMsgBox.egg-info\PKG-INFO
  writing dependency_links to C:\Users\João\AppData\Local\Temp\pip-modern-metadata-v1u94j0l\PyMsgBox.egg-info\dependency_links.txt
  writing top-level names to C:\Users\João\AppData\Local\Temp\pip-modern-metadata-v1u94j0l\PyMsgBox.egg-info\top_level.txt
  writing manifest file 'C:\Users\João\AppData\Local\Temp\pip-modern-metadata-v1u94j0l\PyMsgBox.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\João\AppData\Local\Temp\pip-modern-metadata-v1u94j0l\PyMsgBox.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.py' under directory 'pymsgbox'
  writing manifest file 'C:\Users\João\AppData\Local\Temp\pip-modern-metadata-v1u94j0l\PyMsgBox.egg-info\SOURCES.txt'
  creating 'C:\Users\João\AppData\Local\Temp\pip-modern-metadata-v1u94j0l\PyMsgBox.dist-info'
  error: invalid command 'bdist_wheel'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7d/ff/4c6f31a4f08979f12a663f2aeb6c8b765d3bd592e66eaaac445f547bb875/PyMsgBox-1.0.9.tar.gz#sha256=2194227de8bff7a3d6da541848705a155dcbb2a06ee120d9f280a1d7f51263ff (from https://pypi.org/simple/pymsgbox/). Command errored out with exit status 1: 'C:\Users\João\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\João\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\JOO~1\AppData\Local\Temp\tmpg6v8ufcy' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyMsgBox==1.0.9 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9)
ERROR: No matching distribution found for PyMsgBox==1.0.9

**Comment by gbmv33** [comment]
abre o cmd e escreve `pip install wheel`

**Comment by jvfl10** [comment]
Cara o nome do seu usuário "João", você não vai conseguir, não pode ter acento e nem espaço.. para a sua solução é criar outro usuário no Windows sem acento, ex: "joao", assim você vai conseguir rodar o pip.

**Comment by joaoaspimienta** [comment]
> 

Caraca, não acredito, depois de fazer isso eu consegui usar o pip install -r requirements.txt!! Mas agora na hora de rodar o bot dá esse erro:

D:\bomb\bombcrypto-bot-main>python3 index.py
Traceback (most recent call last):
  File "D:\bomb\bombcrypto-bot-main\index.py", line 2, in <module>
    from src.logger import logger, loggerMapClicked
  File "D:\bomb\bombcrypto-bot-main\src\logger.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by jvfl10** [comment]
Roda esse comando python index.py
aquele 3 ali pode tirar

**Comment by joaoaspimienta** [comment]
> Roda esse comando python index.py aquele 3 ali pode tirar

Agora o bot rodou, muito obrigado!! Ele só não conseguiu clicar no botao de new map que ja tava aberto

**Comment by joaoaspimienta** [comment]
> Cara o nome do seu usuário "João", você não vai conseguir, não pode ter acento e nem espaço.. para a sua solução é criar outro usuário no Windows sem acento, ex: "joao", assim você vai conseguir rodar o pip.

Eu consegui depois de usar o pip install wheel mesmo no meu usuario com acento... por quê?

**Comment by jvfl10** [comment]
Então o problema que eu tinha, eu criei outro usuário e aqui funciona tudo certinho, ele executa todos comando.. não cheguei a tentar a usar o comando pip install wheel  desta maneira.

**Comment by jvfl10** [comment]
Quando tiver um tempo tenta criar outro usuário para fazer o teste, só vai ter que instalar a MetaMesk.

**Comment by joaoaspimienta** [comment]
> Então o problema que eu tinha, eu criei outro usuário e aqui funciona tudo certinho, ele executa todos comando.. não cheguei a tentar a usar o comando pip install wheel desta maneira.

sabe como fazer pro bot clicar nos botoes de new map?
e talvez pra rodar em 2 contas?

**Comment by jvfl10** [comment]
da uma olhada aqui gh pr checkout 499

**Comment by jvfl10** [comment]
da uma olhada no Pull 499

**Comment by joaoaspimienta** [comment]
> 

funcionou perfeito, muito obrigado amigo!
