### ISSUE TITLE
CV2 / ImportError: DLL load failed while importing cv2: The specified module could not be found.

### ISSUE THREAD

**Issue by amz-khampasong** [mpcabete/bombcrypto-bot#532]
![image](https://user-images.githubusercontent.com/71713107/147727744-ce8159a1-ac73-4109-8378-097d2c646c34.png)

**Comment by amz-khampasong** [comment]
already install requirements

**Comment by doug14** [comment]
Hi,
I solved this problem by installing opencv-python last without including the suggested version and also installed opencv-python-headless.

**Comment by williamzzz1** [comment]
i solved this by command: pip install "opencv-python-headless<4.3"
