### ISSUE TITLE
PyAutoGUI fail-safe

### ISSUE THREAD

**Issue by doug14** [mpcabete/bombcrypto-bot#533]
Bom dia galera,

Há três dias ao executar o index.py estou recebendo a seguinte mensagem de erro do bot, saberiam dizer o que é?

![Screenshot_17](https://user-images.githubusercontent.com/20193075/147748795-a14a2e4c-741e-4553-a21c-d57a506cb704.png)

pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE OS NOT RECOMMENDED.

**Comment by doug14** [comment]
Seguindo a linha de ter dúvida e continuar indo atrás da resolução, encontrei isso:
https://stackabuse.com/getting-started-with-python-pyautogui/
![Screenshot_18](https://user-images.githubusercontent.com/20193075/147749469-6cb8e458-9aad-4f21-997d-cf402ffb26d5.png)

Levando em conta isso, na linha 21 do index.py adicionei o seguinte comando: pyautogui.FAILSAFE = False

Deixarei o bot rodando para verificar se o problema vai parar

**Comment by fguide** [comment]
pyautogui.FAILSAFE = False no index.py resolve o problema, ele foi removido em algum dos commits.
