### ISSUE TITLE
Bot Para NFT Zodiacs

### ISSUE THREAD

**Issue by maikelrichard** [mpcabete/bombcrypto-bot#534]
Seria possível fazer este mesmo bot pro nft zodíacs, pra quem tem acima de 3 carrinho

**Comment by trinitro2** [comment]
//FUNÇÃO NUMERO RANDOMICO
function numeroRandomico(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min)) + min;
}


//FUNÇÃO DORMIR
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}


//VARIAVEIS GLOBAIS
var qtdCarros = 30;
var execFuncao = 0;


rotinaInicial();


//ROTINA INICIAL
async function rotinaInicial() {


	//CLICA NO MENU BATTLE FIELD
	if( document.getElementsByClassName("menu-btn")[3] ){
		document.getElementsByClassName("menu-btn")[3].click();
	}
	
	
	//DORME
	await sleep(numeroRandomico(500,1000));
	
	
	//PEGA A QUANTIDADE DE CARROS
	if( document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor") ){
		var dataCarros = document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor");
		qtdCarros = Object.keys(dataCarros).length;
	}	
	
	
	//DORME
	await sleep(numeroRandomico(500,1000));


	//INICIA ROTINA DO JOGO (PASSANDO O CARRO 0 PARA INICIAR)
	rotinaJogo(0);
	
	
}


//ROTINA DO JOGO
async function rotinaJogo(carroAtual) {
	
	
	//DORME
	await sleep(numeroRandomico(500,1000));
	
	
	//VERIFICA SE O CARRO PODE CORRER E FAZ A CORRIDA
	var podeCorrer = true;
	do {
	
		//CLICA NO CARRO DA LISTA
		if( document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor")[carroAtual] ){
			document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor")[carroAtual].click();
		}


		//DORME
		await sleep(numeroRandomico(500,1000));
		

		//ID DO CARRO
		var idCarro = "";
		if( document.querySelector(".selected div").children[1] ){
			idCarro = document.querySelector(".selected div").children[1].innerText;
		}
		
		
		//NUMERO DE CORRIDAS
		var numeroCorridas = "Racing: 0/12";
		if( document.querySelector(".selected div").children[4] ){
			numeroCorridas = document.querySelector(".selected div").children[4].innerText;
		}
		
		
		//NÃO JOGA COM UM CARRO ESPECIFICO
		if (idCarro == 'Id: 0BMW...acV'){ numeroCorridas = 'Racing: 12/12';}
		
		
		if (numeroCorridas == 'Racing: 12/12'){
			
			//ACABOU AS CORRIDAS DESSE CARRO
			podeCorrer = false;
		
		
		}else{
			






			var terminou = false;
			do {
			
				//VERIFICA SE JA TEMOS O RESULTS
				if( document.getElementsByClassName("custom-btn btn-yellow")[0] ){
					if (document.getElementsByClassName("custom-btn btn-yellow")[0].innerText == 'Check Result'){
						terminou = true;
					}
				}

				
				if ( terminou == false ){
			
			
					//CLICA NO OK SE TIVER
					if( document.getElementsByClassName("ant-btn ant-btn-success")[0] ){
						if (document.getElementsByClassName("ant-btn ant-btn-success")[0].innerText == 'OK'){
							document.getElementsByClassName("ant-btn ant-btn-success")[0].click();
							await sleep(numeroRandomico(500,1000));
						}
					}
				
				
				
					//CLICA NO START RACE
					if( document.getElementsByClassName("custom-btn btn-green")[0] ){
					
						if (document.getElementsByClassName("custom-btn btn-green")[0].innerText == 'START RACE!'){
							document.getElementsByClassName("custom-btn btn-green")[0].click();
							await sleep(numeroRandomico(500,1000));
						}else{
						
							if( document.getElementsByClassName("custom-btn btn-green")[1] ){
								if (document.getElementsByClassName("custom-btn btn-green")[1].innerText == 'START RACE!'){
									document.getElementsByClassName("custom-btn btn-green")[1].click();
									await sleep(numeroRandomico(500,1000));
								}
							}
						}
					}
				
				
				}
				
				
				
			await sleep(numeroRandomico(1000,1500));	
			
			}
			while (terminou == false);
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			var deuClaim = false;
			do {
			
			
			
				//CLICA NO CLAIM
				if( document.getElementsByClassName("ant-btn ant-btn-success")[0] ){
					if (document.getElementsByClassName("ant-btn ant-btn-success")[0].innerText == 'Claim'){
						document.getElementsByClassName("ant-btn ant-btn-success")[0].click();
						deuClaim = true;
					}
				}
			


				if ( deuClaim == false ){
			
			
			
					//CLICA NO OK SE TIVER
					if( document.getElementsByClassName("ant-btn ant-btn-success")[0] ){
						if (document.getElementsByClassName("ant-btn ant-btn-success")[0].innerText == 'OK'){
							document.getElementsByClassName("ant-btn ant-btn-success")[0].click();
							await sleep(numeroRandomico(500,1000));
						}
					}
				
				
				
					//CLICA NO RESULTS
					if( document.getElementsByClassName("custom-btn btn-yellow")[0] ){
						if (document.getElementsByClassName("custom-btn btn-yellow")[0].innerText == 'Check Result'){
							document.getElementsByClassName("custom-btn btn-yellow")[0].click();
							await sleep(numeroRandomico(500,1000));
						}
					}
				

				}
				
				
				
			await sleep(numeroRandomico(1000,1500));	
			
			}
			while (deuClaim == false);
			
			




			
			
		}
		
		
	} while (podeCorrer == true)
	
	
	
	if ( carroAtual <= qtdCarros  ){
		carroAtual++;
		rotinaJogo(carroAtual);
	}else{
	
		if (execFuncao > 1){
			execFuncao++;
			rotinaJogo(0);
		}else{
			alert('Terminou todos os carros!');
		}
		
	}
	
	
	
}``

**Comment by trinitro2** [comment]
`//FUNÇÃO NUMERO RANDOMICO
function numeroRandomico(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min)) + min;
}


//FUNÇÃO DORMIR
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}


//VARIAVEIS GLOBAIS
var qtdCarros = 30;
var execFuncao = 0;


rotinaInicial();


//ROTINA INICIAL
async function rotinaInicial() {


	//CLICA NO MENU BATTLE FIELD
	if( document.getElementsByClassName("menu-btn")[3] ){
		document.getElementsByClassName("menu-btn")[3].click();
	}
	
	
	//DORME
	await sleep(numeroRandomico(500,1000));
	
	
	//PEGA A QUANTIDADE DE CARROS
	if( document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor") ){
		var dataCarros = document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor");
		qtdCarros = Object.keys(dataCarros).length;
	}	
	
	
	//DORME
	await sleep(numeroRandomico(500,1000));


	//INICIA ROTINA DO JOGO (PASSANDO O CARRO 0 PARA INICIAR)
	rotinaJogo(0);
	
	
}


//ROTINA DO JOGO
async function rotinaJogo(carroAtual) {
	
	
	//DORME
	await sleep(numeroRandomico(500,1000));
	
	
	//VERIFICA SE O CARRO PODE CORRER E FAZ A CORRIDA
	var podeCorrer = true;
	do {
	
		//CLICA NO CARRO DA LISTA
		if( document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor")[carroAtual] ){
			document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor")[carroAtual].click();
		}


		//DORME
		await sleep(numeroRandomico(500,1000));
		

		//ID DO CARRO
		var idCarro = "";
		if( document.querySelector(".selected div").children[1] ){
			idCarro = document.querySelector(".selected div").children[1].innerText;
		}
		
		
		//NUMERO DE CORRIDAS
		var numeroCorridas = "Racing: 0/12";
		if( document.querySelector(".selected div").children[4] ){
			numeroCorridas = document.querySelector(".selected div").children[4].innerText;
		}
		
		
		//NÃO JOGA COM UM CARRO ESPECIFICO
		if (idCarro == 'Id: 0BMW...acV'){ numeroCorridas = 'Racing: 12/12';}
		
		
		if (numeroCorridas == 'Racing: 12/12'){
			
			//ACABOU AS CORRIDAS DESSE CARRO
			podeCorrer = false;
		
		
		}else{
			






			var terminou = false;
			do {
			
				//VERIFICA SE JA TEMOS O RESULTS
				if( document.getElementsByClassName("custom-btn btn-yellow")[0] ){
					if (document.getElementsByClassName("custom-btn btn-yellow")[0].innerText == 'Check Result'){
						terminou = true;
					}
				}

				
				if ( terminou == false ){
			
			
					//CLICA NO OK SE TIVER
					if( document.getElementsByClassName("ant-btn ant-btn-success")[0] ){
						if (document.getElementsByClassName("ant-btn ant-btn-success")[0].innerText == 'OK'){
							document.getElementsByClassName("ant-btn ant-btn-success")[0].click();
							await sleep(numeroRandomico(500,1000));
						}
					}
				
				
				
					//CLICA NO START RACE
					if( document.getElementsByClassName("custom-btn btn-green")[0] ){
					
						if (document.getElementsByClassName("custom-btn btn-green")[0].innerText == 'START RACE!'){
							document.getElementsByClassName("custom-btn btn-green")[0].click();
							await sleep(numeroRandomico(500,1000));
						}else{
						
							if( document.getElementsByClassName("custom-btn btn-green")[1] ){
								if (document.getElementsByClassName("custom-btn btn-green")[1].innerText == 'START RACE!'){
									document.getElementsByClassName("custom-btn btn-green")[1].click();
									await sleep(numeroRandomico(500,1000));
								}
							}
						}
					}
				
				
				}
				
				
				
			await sleep(numeroRandomico(1000,1500));	
			
			}
			while (terminou == false);
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			var deuClaim = false;
			do {
			
			
			
				//CLICA NO CLAIM
				if( document.getElementsByClassName("ant-btn ant-btn-success")[0] ){
					if (document.getElementsByClassName("ant-btn ant-btn-success")[0].innerText == 'Claim'){
						document.getElementsByClassName("ant-btn ant-btn-success")[0].click();
						deuClaim = true;
					}
				}
			


				if ( deuClaim == false ){
			
			
			
					//CLICA NO OK SE TIVER
					if( document.getElementsByClassName("ant-btn ant-btn-success")[0] ){
						if (document.getElementsByClassName("ant-btn ant-btn-success")[0].innerText == 'OK'){
							document.getElementsByClassName("ant-btn ant-btn-success")[0].click();
							await sleep(numeroRandomico(500,1000));
						}
					}
				
				
				
					//CLICA NO RESULTS
					if( document.getElementsByClassName("custom-btn btn-yellow")[0] ){
						if (document.getElementsByClassName("custom-btn btn-yellow")[0].innerText == 'Check Result'){
							document.getElementsByClassName("custom-btn btn-yellow")[0].click();
							await sleep(numeroRandomico(500,1000));
						}
					}
				

				}
				
				
				
			await sleep(numeroRandomico(1000,1500));	
			
			}
			while (deuClaim == false);
			
			




			
			
		}
		
		
	} while (podeCorrer == true)
	
	
	
	if ( carroAtual <= qtdCarros  ){
		carroAtual++;
		rotinaJogo(carroAtual);
	}else{
	
		if (execFuncao > 1){
			execFuncao++;
			rotinaJogo(0);
		}else{
			alert('Terminou todos os carros!');
		}
		
	}
	
	
	
}`

**Comment by trinitro2** [comment]
//FUNÇÃO NUMERO RANDOMICO
function numeroRandomico(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min)) + min;
}


//FUNÇÃO DORMIR
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}


//VARIAVEIS GLOBAIS
var qtdCarros = 30;
var execFuncao = 0;


rotinaInicial();


//ROTINA INICIAL
async function rotinaInicial() {


	//CLICA NO MENU BATTLE FIELD
	if( document.getElementsByClassName("menu-btn")[3] ){
		document.getElementsByClassName("menu-btn")[3].click();
	}
	
	
	//DORME
	await sleep(numeroRandomico(500,1000));
	
	
	//PEGA A QUANTIDADE DE CARROS
	if( document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor") ){
		var dataCarros = document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor");
		qtdCarros = Object.keys(dataCarros).length;
	}	
	
	
	//DORME
	await sleep(numeroRandomico(500,1000));


	//INICIA ROTINA DO JOGO (PASSANDO O CARRO 0 PARA INICIAR)
	rotinaJogo(0);
	
	
}


//ROTINA DO JOGO
async function rotinaJogo(carroAtual) {
	
	
	//DORME
	await sleep(numeroRandomico(500,1000));
	
	
	//VERIFICA SE O CARRO PODE CORRER E FAZ A CORRIDA
	var podeCorrer = true;
	do {
	
		//CLICA NO CARRO DA LISTA
		if( document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor")[carroAtual] ){
			document.getElementsByClassName("content shadowed item d-flex flex-row justify-content-around cursor")[carroAtual].click();
		}


		//DORME
		await sleep(numeroRandomico(500,1000));
		

		//ID DO CARRO
		var idCarro = "";
		if( document.querySelector(".selected div").children[1] ){
			idCarro = document.querySelector(".selected div").children[1].innerText;
		}
		
		
		//NUMERO DE CORRIDAS
		var numeroCorridas = "Racing: 0/12";
		if( document.querySelector(".selected div").children[4] ){
			numeroCorridas = document.querySelector(".selected div").children[4].innerText;
		}
		
		
		//NÃO JOGA COM UM CARRO ESPECIFICO
		if (idCarro == 'Id: 0BMW...acV'){ numeroCorridas = 'Racing: 12/12';}
		
		
		if (numeroCorridas == 'Racing: 12/12'){
			
			//ACABOU AS CORRIDAS DESSE CARRO
			podeCorrer = false;
		
		
		}else{
			






			var terminou = false;
			do {
			
				//VERIFICA SE JA TEMOS O RESULTS
				if( document.getElementsByClassName("custom-btn btn-yellow")[0] ){
					if (document.getElementsByClassName("custom-btn btn-yellow")[0].innerText == 'Check Result'){
						terminou = true;
					}
				}

				
				if ( terminou == false ){
			
			
					//CLICA NO OK SE TIVER
					if( document.getElementsByClassName("ant-btn ant-btn-success")[0] ){
						if (document.getElementsByClassName("ant-btn ant-btn-success")[0].innerText == 'OK'){
							document.getElementsByClassName("ant-btn ant-btn-success")[0].click();
							await sleep(numeroRandomico(500,1000));
						}
					}
				
				
				
					//CLICA NO START RACE
					if( document.getElementsByClassName("custom-btn btn-green")[0] ){
					
						if (document.getElementsByClassName("custom-btn btn-green")[0].innerText == 'START RACE!'){
							document.getElementsByClassName("custom-btn btn-green")[0].click();
							await sleep(numeroRandomico(500,1000));
						}else{
						
							if( document.getElementsByClassName("custom-btn btn-green")[1] ){
								if (document.getElementsByClassName("custom-btn btn-green")[1].innerText == 'START RACE!'){
									document.getElementsByClassName("custom-btn btn-green")[1].click();
									await sleep(numeroRandomico(500,1000));
								}
							}
						}
					}
				
				
				}
				
				
				
			await sleep(numeroRandomico(1000,1500));	
			
			}
			while (terminou == false);
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			var deuClaim = false;
			do {
			
			
			
				//CLICA NO CLAIM
				if( document.getElementsByClassName("ant-btn ant-btn-success")[0] ){
					if (document.getElementsByClassName("ant-btn ant-btn-success")[0].innerText == 'Claim'){
						document.getElementsByClassName("ant-btn ant-btn-success")[0].click();
						deuClaim = true;
					}
				}
			


				if ( deuClaim == false ){
			
			
			
					//CLICA NO OK SE TIVER
					if( document.getElementsByClassName("ant-btn ant-btn-success")[0] ){
						if (document.getElementsByClassName("ant-btn ant-btn-success")[0].innerText == 'OK'){
							document.getElementsByClassName("ant-btn ant-btn-success")[0].click();
							await sleep(numeroRandomico(500,1000));
						}
					}
				
				
				
					//CLICA NO RESULTS
					if( document.getElementsByClassName("custom-btn btn-yellow")[0] ){
						if (document.getElementsByClassName("custom-btn btn-yellow")[0].innerText == 'Check Result'){
							document.getElementsByClassName("custom-btn btn-yellow")[0].click();
							await sleep(numeroRandomico(500,1000));
						}
					}
				

				}
				
				
				
			await sleep(numeroRandomico(1000,1500));	
			
			}
			while (deuClaim == false);
			
			




			
			
		}
		
		
	} while (podeCorrer == true)
	
	
	
	if ( carroAtual <= qtdCarros  ){
		carroAtual++;
		rotinaJogo(carroAtual);
	}else{
	
		if (execFuncao > 1){
			execFuncao++;
			rotinaJogo(0);
		}else{
			alert('Terminou todos os carros!');
		}
		
	}
	
	
	
}

**Comment by trinitro2** [comment]
nao sei pq fica assim separado mas junta tudo

**Comment by trinitro2** [comment]
poe no console do chrome e seja feliz

https://pastebin.com/vMrhBDv4

donate BSC: 0x9F9Bd77A29febA1420fD3A3CF87B4e4b965E5eb8

**Comment by maikelrichard** [comment]
pow mano, sem palavras aqui pra tu, segunda faço meu primeiro que e mando sim, pode deixa, pow muito agradecido

**Comment by maikelrichard** [comment]
> poe no console do chrome e seja feliz
> 
> https://pastebin.com/vMrhBDv4
> 
> donate BSC: 0x9F9Bd77A29febA1420fD3A3CF87B4e4b965E5eb8

 sei que você ja me ajudou muito, só gostaria de saber se é possível salvar um log (do resultado da corrida) tipo a posição em que cada carro ficou nas 12 corridas 1, 2 3, 4(lose) ) *isso é apenas pra relatório da planilha no caso

**Comment by trinitro2** [comment]
> > poe no console do chrome e seja feliz
> > https://pastebin.com/vMrhBDv4
> > donate BSC: 0x9F9Bd77A29febA1420fD3A3CF87B4e4b965E5eb8
> 
> sei que você ja me ajudou muito, só gostaria de saber se é possível salvar um log (do resultado da corrida) tipo a posição em que cada carro ficou nas 12 corridas 1, 2 3, 4(lose) ) *isso é apenas pra relatório da planilha no caso

com esse ai acho que nao da...

negocio é ir anotando na mao enquanto ele faz

**Comment by Nucito** [comment]
> 

Teria os dados do criador?🤔

**Comment by Nucito** [comment]
Curti a ideia ksksks

**Comment by Nucito** [comment]
> > poe no console do chrome e seja feliz
> > https://pastebin.com/vMrhBDv4
> > donate BSC: 0x9F9Bd77A29febA1420fD3A3CF87B4e4b965E5eb8
> 
> sei que você ja me ajudou muito, só gostaria de saber se é possível salvar um log (do resultado da corrida) tipo a posição em que cada carro ficou nas 12 corridas 1, 2 3, 4(lose) ) *isso é apenas pra relatório da planilha no caso

Seria possível fazer isso sem problemas... se algum dia eu comprar algum carrinho no zdc eu crio um bot pra isso kkkkk
