### ISSUE TITLE
Bot funciona apenas com 1 monitor

### ISSUE THREAD

**Issue by waltimgv** [mpcabete/bombcrypto-bot#537]
Galera tenho 2 monitores, mas quando eu ligo o bot ele nao funciona com os 2 ligados, tenho que desligar 1 e por pra rodar, alguem sabe como funcionar so em um monitor sem precisar desligar o outro?

**Comment by fguide** [comment]
#30 deve ajudar

**Comment by waltimgv** [comment]
> #30 deve ajudar

como faço pra baixar?

**Comment by rzanca** [comment]
Aqui funciona normalmente, o bomb precisa estar na tela principal para rodar.
Caso não esteja pode mudar essa linha e verificar
monitor = sct.monitors[0]
Mude para 2

**Comment by LeoFC97** [comment]
Mude para 1 no caso. Se voce mudar pra 2 pegará o 3 monitor.
