### ISSUE TITLE
Hi, could someone help me?  How do I get the bot not to let the heroes work?

### ISSUE THREAD

**Issue by sds3777** [mpcabete/bombcrypto-bot#538]
Guys, I have an idea here because my account was hacked.  And I would like you to help me, how do I get the boot not to put any heroes to work? Keep clicking on the "rest" button and if there was any error, log in again and keep pressing on "rest" all the time?

**Comment by fguide** [comment]
If you're using the "green" config just change the offset variable from 140 to 190 or 200, it should work.

file index.py file 251:

> offset = 140

Change to:
>offset = 190

**Comment by fguide** [comment]
btw Im curious on how that's going o help you with the hacked account...

**Comment by sds3777** [comment]
It worked well thank you, but it gets looped inifinito. When you're going to select the mouse character, you go down there and you're clicking "rest" and turning down infinity, any ideas?

The hacker is going into my account all the time, putting the hero to work because he's seeing that I have 39 coins. So if I do this and leave for a 2 days I can make the kill then quickly rsrs

**Comment by sds3777** [comment]
> If you're using the "green" config just change the offset variable from 140 to 190 or 200, it should work.
> 
> file index.py line 251:
> 
> > offset = 140
> 
> Change to:
> >offset = 190
> 

It worked well thank you, but it gets looped inifinito. When you're going to select the mouse character, you go down there and you're clicking "rest" and turning down infinity, any ideas?

**Comment by sds3777** [comment]
> btw Im curious on how that's gonna help you with the hacked account...

The hacker is going into my account all the time, putting the hero to work because he's seeing that I have 39 coins. So if I do this and leave for a 2 days I can make the kill then quickly rsrs

**Comment by fguide** [comment]
> > If you're using the "green" config just change the offset variable from 140 to 190 or 200, it should work.
> > file index.py line 251:
> > > offset = 140
> > 
> > 
> > Change to:
> > > offset = 190
> 
> It worked well thank you, but it gets looped inifinito. When you're going to select the mouse character, you go down there and you're clicking "rest" and turning down infinity, any ideas?

Yes, line 447 on index py, change from:

```
       if buttonsClicked == 0:
            empty_scrolls_attempts = empty_scrolls_attempts - 1
```
to:
```

       #if buttonsClicked == 0:
       empty_scrolls_attempts = empty_scrolls_attempts - 1
```

And it should work. Dont forget to check code indentation, it must be matching the example.

**Comment by sds3777** [comment]
> > > If you're using the "green" config just change the offset variable from 140 to 190 or 200, it should work.
> > > file index.py line 251:
> > > > offset = 140
> > > 
> > > 
> > > Change to:
> > > > offset = 190
> > 
> > It worked well thank you, but it gets looped inifinito. When you're going to select the mouse character, you go down there and you're clicking "rest" and turning down infinity, any ideas?
> 
> Yes, line 447 on index py, change from:
> 
> ```
>        if buttonsClicked == 0:
>             empty_scrolls_attempts = empty_scrolls_attempts - 1
> ```
> to:
> ```
> 
>        #if buttonsClicked == 0:
>        empty_scrolls_attempts = empty_scrolls_attempts - 1
> ```
> 
> And it should work. Dont forget to check code indentation, it must be matching the example.

How do I check code indentation? I'm very layman in Python :/
