### ISSUE TITLE
looping Infinito na hora de selecionar os Herois

### ISSUE THREAD

**Issue by willfonseca** [mpcabete/bombcrypto-bot#54]
Opa Amigo, parabens pelo trabalho!

No meu caso aqui um problema que acontece é que na hora de colocar os herois pra trabalhar ele fica selecionando os herois e nao para mais.

Alguma dica de como resolver?

**Comment by willfonseca** [comment]
Pessoal ninguém esta enfrentando esse problema?

Olhem quantas vezes ele ficou clicando nos heroes até eu interferir.

![bombcripto](https://user-images.githubusercontent.com/1868630/143180052-a0467f7f-7ab5-4dcf-80b1-875f927483f6.jpg)

**Comment by willfonseca** [comment]
adicionei uma condição na função clickGreenBarButtons que resolveu meuproblema, adicionei na linha 202:
```
        if hero_clicks > 15: 
            clickBtn(x_button_img)

```

**Comment by mpcabete** [comment]
Oi will, desculpe a demora.
Gostei da sua solução, vou adicionar no bot pra evitar esse tipo de loop.
Provavelmente o que esta causando isso é o bot interpretando que "reconhece" o botão de enviar para trabalhar quando, na verdade o botão não está visível.

Tenta aumentar um pouquinho o valor da configuração:
`go_to_work_btn: 0.9`
tipo
`go_to_work_btn: 0.95`

Se não funcionar tenta substituir a imagem go-work.png na pasta targets com um “screenshot” do seu próprio computador.

**Comment by martineix** [comment]
Bom dia. Estou passando por isto também. Vou adicionar essa condição que você colocou will.

**Comment by mpcabete** [comment]
Adicionei lá will, vlw
