### ISSUE TITLE
Linux - Did somebody manage to install the bot for Linux?

### ISSUE THREAD

**Issue by coolwateRx3** [mpcabete/bombcrypto-bot#541]
I am looking for help for the optimal setup of the bot for linux

I tried to run the bot on a VM Linux Debian 10, but when installing requirements I already get some red lines, where something couldn't be found. Also the latest possible version was linux 3.7.x.

Did somebody manage to install it the bot on Linux?
-Which operating system did you use?
-Which version of Linux?
-Did you do any additional steps than installing python and the pip before installing requirements?

Thank you in advance!

**Comment by rzanca** [comment]
Run this commands:

`sudo apt-get update
sudo apt-get install python3-pyqt5 -y
sudo apt-get install git -y
sudo apt-get install pyqt5-dev-tools -y
sudo apt-get install qttools5-dev-tools -y
sudo apt-get install xclip -y
sudo apt-get install python3-pip -y
sudo apt-get install python3-tk python3-dev -y
pip install pyautogui
pip install python-xlib
git clone https://github.com/mpcabete/bombcrypto-bot.git /root/Desktop/bombcrypto-bot
pip install -r /root/Desktop/bombcrypto-bot/requirements.txt
`

**Comment by cleitonleonel** [comment]
> Execute estes comandos:
> 
> > sudo apt-get update 
> > sudo apt-get install python3-pyqt5 -y 
> > sudo apt-get install git -y 
> > sudo apt-get install pyqt5-dev-tools -y 
> > sudo apt-get install qttools5-dev-tools -y 
> > sudo apt- get install xclip -y 
> > sudo apt-get install python3-pip -y 
> > sudo apt-get install python3-tk python3-dev -y 
> > pip instale pyautogui 
> > pip instale python-xlib 
> > git clone [https://github.com/mpcabete/bombcrypto- bot.git](https://github.com/mpcabete/bombcrypto-bot.git) / root / Desktop / bombcrypto-bot 
> > pip install -r /root/Desktop/bombcrypto-bot/requirements.txt

Please!!! 
Include this >> sudo apt-get install scrot -y

**Comment by coolwateRx3** [comment]
Thank you! it worked out

**Comment by LeonamSSoares** [comment]
on mine unfortunately it didn't work ... my is a bodhi linux 
![image](https://user-images.githubusercontent.com/97570716/149047683-ae43cbed-8a91-44cb-a9ca-705ae22b2a8b.png)
sorry for the photo unfortunately it is installed on a mini pc and i only have the television to use

I would really like help

**Comment by rzanca** [comment]
> 

Você chegou a rodar os comandos acima?

**Comment by LeonamSSoares** [comment]
sim rodei todos ... mas deu esse erro ai e o comando git clone https://github.com/mpcabete/bombcrypto- bot.git / root / Desktop / bombcrypto-bot tbm não funcionou ... eu tentei executar o ultimo  com a pasta que eu baixe e coloquei com um pendrive dentro

**Comment by rzanca** [comment]
sudo apt-get update
sudo apt-get install python3-pyqt5 -y
sudo apt-get install git -y
sudo apt-get install pyqt5-dev-tools -y
sudo apt-get install qttools5-dev-tools -y
sudo apt-get install xclip -y
sudo apt-get install python3-pip -y
sudo apt-get install python3-tk python3-dev -y
sudo apt-get install scrot -y
pip install pyautogui
pip install python-xlib
git clone https://github.com/mpcabete/bombcrypto-bot.git /root/Desktop/bombcrypto-bot
pip install -r /root/Desktop/bombcrypto-bot/requirements.txt

**Comment by LeonamSSoares** [comment]
meu rei tentei mas infelizmente não foi não... da esse erro ai .... sou burro pra caralho em linux mas será que é o nome do meu linux q ta diferente ?  
O mini pc q eu to usando é um ULTRATOP LIVA X2 PROCESSADOR - PROCESSADOR INTEL® DUAL CORE™ N3060MEMÓRIA - 2GB 1600MHZ DDR3L  . 
Caso recomende outro linux q rode nele de boa eu instalo  e vejo no que vai dar .
![image](https://user-images.githubusercontent.com/97570716/149445361-e4048a94-6416-4d1f-aeb2-d36f566f2d2d.png)
