### ISSUE TITLE
Bot para na tela de erro / Bot stop on error screen

### ISSUE THREAD

**Issue by KruegerVox** [mpcabete/bombcrypto-bot#543]
Olá. Estou usando em uma maquina virtual remota e encontrei um único problema até agora:

Tudo funciona, exceto, após todos os heróis estarem dormindo aparece uma tela de erro dizendo:  "The account automatically exits because it has not been used for a long time".
Nesta tela, o bot só funciona se abro a VM máquina remotamente.

Alguma sugestão?

Obrigado!

_________________

Hi. I'm using it on a remote virtual machine and I've encountered only one problem so far:

Everything works, except after all heroes are asleep an error screen appears saying: "The account automatically exits because it has not been used for a long time".
On this screen, the bot only works if I open the machine VM remotely.

Any suggestion?

Thanks!

**Comment by fguide** [comment]
É timeout do jogo, deve ter configurado o refresh de herois para um tempo muito algo

**Comment by doug14** [comment]
Estou tendo o mesmo problema e o estranho que o refresh está no padrão de 3 minutos e a verificação de envio dos heróis para trabalhar esta em 9 minutos.

**Comment by KruegerVox** [comment]
Eu estava acessando a VM pela area de trabalho remota, quando eu saia o bot continuava só que depois de um tempo dava este erro (Windows 7, quando sai do remoto ele não faz logoff). O problema parou depois que fiz login diretamente na VM (Hyper-v) e fechei. Ele continua com o sistema aberto, diferente de quando conecta pela área de trabalho remota. Vai pra 1 dia sem interrupção.
