### ISSUE TITLE
Como alterar o green para quase 100% ?

### ISSUE THREAD

**Issue by rvinicius396g** [mpcabete/bombcrypto-bot#544]
Para o Select_heroes_mode: "green" o algoritmo já coloca os heros que estão com o HP verde, eu troquei a imagem do green-bar.png por uma foto que esteja com a barra maior(com no mínimo 75 ou 80%) , só que ai o algoritmo ao invés de colocar eles para trabalhar começou a colocar eles para descansar (mesmo já estando descansando)

**Comment by kerferber** [comment]
> Para o Select_heroes_mode: "green" o algoritmo já coloca os heros que estão com o HP verde, eu troquei a imagem do green-bar.png por uma foto que esteja com a barra maior(com no mínimo 75 ou 80%) , só que ai o algoritmo ao invés de colocar eles para trabalhar começou a colocar eles para descansar (mesmo já estando descansando)

Excelente pergunta. Eu também estava querendo implementar isso

**Comment by diogosilvadossantos** [comment]
> Para o Select_heroes_mode: "green" o algoritmo já coloca os heros que estão com o HP verde, eu troquei a imagem do green-bar.png por uma foto que esteja com a barra maior(com no mínimo 75 ou 80%) , só que ai o algoritmo ao invés de colocar eles para trabalhar começou a colocar eles para descansar (mesmo já estando descansando)

voce mudo o tamanho da barra ai ele clica um pouco pro lado no descansar, voce tem que ir no index e procurar o offset = 140 voce vai diminuindo esse valor ate ele clicar no work

**Comment by fguide** [comment]
> > Para o Select_heroes_mode: "green" o algoritmo já coloca os heros que estão com o HP verde, eu troquei a imagem do green-bar.png por uma foto que esteja com a barra maior(com no mínimo 75 ou 80%) , só que ai o algoritmo ao invés de colocar eles para trabalhar começou a colocar eles para descansar (mesmo já estando descansando)
> 
> voce mudo o tamanho da barra ai ele clica um pouco pro lado no descansar, voce tem que ir no index e procurar o offset = 140 voce vai diminuindo esse valor ate ele clicar no work

^+1 nesse metodo, funciona pra mim pelo menos...

**Comment by rvinicius396g** [comment]
> 

Fiz alteração do OffSet para 100 e agora ele clicou no Work, unica questão é que ele ainda continua clicando em todos os heroes com barra verde, e não com quase 100% igual a foto que eu coloquei;
![image](https://user-images.githubusercontent.com/16687195/147883067-ce908a41-6e87-4570-87c1-a10b21e4137b.png)

**Comment by kerferber** [comment]
> > 
> 
> Fiz alteração do OffSet para 100 e agora ele clicou no Work, unica questão é que ele ainda continua clicando em todos os heroes com barra verde, e não com quase 100% igual a foto que eu coloquei; ![image](https://user-images.githubusercontent.com/16687195/147883067-ce908a41-6e87-4570-87c1-a10b21e4137b.png)

Não tive tempo ainda pra tentar implementar aqui. 

Mas será que não é devido a configuração no config.yaml?

Como está lá? Teria que deixar "green" pra funcionar como vc quer, certo?

**Comment by rvinicius396g** [comment]
> > > 
> > 
> > 
> > Fiz alteração do OffSet para 100 e agora ele clicou no Work, unica questão é que ele ainda continua clicando em todos os heroes com barra verde, e não com quase 100% igual a foto que eu coloquei; ![image](https://user-images.githubusercontent.com/16687195/147883067-ce908a41-6e87-4570-87c1-a10b21e4137b.png)
> 
> Não tive tempo ainda pra tentar implementar aqui.
> 
> Mas será que não é devido a configuração no config.yaml?
> 
> Como está lá? Teria que deixar "green" pra funcionar como vc quer, certo?

Isso mesmo, e já está select_heroes_mode: "green"

**Comment by kerferber** [comment]
> > > > 
> > > 
> > > 
> > > Fiz alteração do OffSet para 100 e agora ele clicou no Work, unica questão é que ele ainda continua clicando em todos os heroes com barra verde, e não com quase 100% igual a foto que eu coloquei; ![image](https://user-images.githubusercontent.com/16687195/147883067-ce908a41-6e87-4570-87c1-a10b21e4137b.png)
> > 
> > 
> > Não tive tempo ainda pra tentar implementar aqui.
> > Mas será que não é devido a configuração no config.yaml?
> > Como está lá? Teria que deixar "green" pra funcionar como vc quer, certo?
> 
> Isso mesmo, e já está select_heroes_mode: "green"

Poxa. Então deveria funcionar.

Quem sabe alterando o treshold?

**Comment by cristianomg** [comment]
> > 
> 
> Fiz alteração do OffSet para 100 e agora ele clicou no Work, unica questão é que ele ainda continua clicando em todos os heroes com barra verde, e não com quase 100% igual a foto que eu coloquei; ![image](https://user-images.githubusercontent.com/16687195/147883067-ce908a41-6e87-4570-87c1-a10b21e4137b.png)

se vc colocar a barra inteira, o robô só irá reconhecer os heróis que tenham exatamente essa barra, ou seja, se a barra passar do nivel da imagem, o herói não será reconhecido e o robô não colocará ele para trabalhar

**Comment by rvinicius396g** [comment]
> > > 
> > 
> > 
> > Fiz alteração do OffSet para 100 e agora ele clicou no Work, unica questão é que ele ainda continua clicando em todos os heroes com barra verde, e não com quase 100% igual a foto que eu coloquei; ![image](https://user-images.githubusercontent.com/16687195/147883067-ce908a41-6e87-4570-87c1-a10b21e4137b.png)
> 
> se vc colocar a barra inteira, o robô só irá reconhecer os heróis que tenham exatamente essa barra, ou seja, se a barra passar do nivel da imagem, o herói não será reconhecido e o robô não colocará ele para trabalhar

Sim, por isso mesmo eu coloquei uma barra com quase 100% cheia, aproximadamente, 75% ou 80%. Ainda assim, o algoritmo continua colocando todos os heroes com a barra simplesmente verde e com um tamanho bem menor

**Comment by kerferber** [comment]
Eu ACHO que li algum comentário aqui de alguém que conseguiu fazer isso.. mas não encontrei... deve ter alguma maneira

**Comment by rvinicius396g** [comment]
Consegui resolver o problema, basicamente, era só colocar só a foto da barra verde sem a parte final. Dessa forma, agora funcionou
![image](https://user-images.githubusercontent.com/16687195/147994506-0751b438-8953-44fc-8f6f-a98645e731f1.png)

**Comment by cristianomg** [comment]
> Consegui resolver o problema, basicamente, era só colocar só a foto da barra verde sem a parte final. Dessa forma, agora funcionou
> 
> ![image](https://user-images.githubusercontent.com/16687195/147994506-0751b438-8953-44fc-8f6f-a98645e731f1.png)
> 
> 

Foi oq eu tinha dito lá encima de não colocar a imagem full

**Comment by kerferber** [comment]
> Consegui resolver o problema, basicamente, era só colocar só a foto da barra verde sem a parte final. Dessa forma, agora funcionou ![image](https://user-images.githubusercontent.com/16687195/147994506-0751b438-8953-44fc-8f6f-a98645e731f1.png)

Perfeito. Excelente. Faz total sentido. Obrigado por compartilhar conosco. Vou implementar aqui este mod

**Comment by kerferber** [comment]
> > Consegui resolver o problema, basicamente, era só colocar só a foto da barra verde sem a parte final. Dessa forma, agora funcionou
> > ![image](https://user-images.githubusercontent.com/16687195/147994506-0751b438-8953-44fc-8f6f-a98645e731f1.png)
> 
> Foi oq eu tinha dito lá encima de não colocar a imagem full

Verdade, agora entendi oq tu quis dizer. Mas na primeira vez que li não havia ficado tão claro. Mas de qualquer maneira, obrigado. A intenção é nos ajudarmos

**Comment by AendersonBR** [comment]
Pessoal, sera que da pra configurar pro boot so selecionar os herois comuns? eu consegui mudar a img do green
![image](https://user-images.githubusercontent.com/97134359/148137973-3ad38b8f-1831-4e96-b4d5-4de9a2695060.png)
mas na hora ela consegui selecionar somente os comuns, mas nao click em work, mudei o tal do offset, mas agora nem selecionar mais os bonecos ta fazendo, eu altero ess offset no arquivo Index?

**Comment by cristianomg** [comment]
> Pessoal, sera que da pra configurar pro boot so selecionar os herois comuns? eu consegui mudar a img do green ![image](https://user-images.githubusercontent.com/97134359/148137973-3ad38b8f-1831-4e96-b4d5-4de9a2695060.png) mas na hora ela consegui selecionar somente os comuns, mas nao click em work, mudei o tal do offset, mas agora nem selecionar mais os bonecos ta fazendo, eu altero ess offset no arquivo Index?

da sim, adicione essa função ao seu script 
![image](https://user-images.githubusercontent.com/53766118/148140633-316c7e53-cdbd-4616-93d5-643265e34dc8.png)



ela faz a mesma verificação que a função `isWorking` porem em vez de validar se o hero já está trabalhando valida se o hero é comum 

busque pelo trecho de codigo 
`
    buttons = positions(images['go-work'], threshold=ct['go_to_work_btn'])
`
abaixo dele insira a linha 

`
commoms = positions(images['commom-text'], threshold=0.8)
`

busque pelo trecho de codigo 
![image](https://user-images.githubusercontent.com/53766118/148140658-7440284f-f640-4040-94c7-574143eee3d2.png)

e altere por 
![image](https://user-images.githubusercontent.com/53766118/148140684-48c95dcd-f6ac-48e6-9773-276ddc6e3741.png)

ps: desculpa as imagens, o codigo não estava ficando identado.

**Comment by AendersonBR** [comment]
Cristiano consegue ma ajudar no privado, pago pelo serviço, realmente nao manjo nada de Programação, só consegui fazer a alteração da img, mas chegou no codigo ja nao sei mais nada.
PS. Procurei por IsWorkink no Ctrl+F no arquivo Index e nao achei essa linha. Estou procurando no arquivo certo?

**Comment by cristianomg** [comment]
> 

passa seu contato, ajudo sim

**Comment by AendersonBR** [comment]
zap zap 31 98896-9892
