### ISSUE TITLE
Rodando o Bot em máquina Linux!

### ISSUE THREAD

**Issue by themexdev** [mpcabete/bombcrypto-bot#545]
Pessoal, boa tarde.
Eu estou rodando o Bot em uma máquina virtual Linux, porém quando eu início ele , logo no primeiro comando é como se ele desse um Alt Tab e segurasse a tecla, no Windows isso não acontece, alguém sabe o que pode ser?
Outra coisa, vocês rodam em máquina virtual o Bot , alguma  recomendação?

**Comment by kerferber** [comment]
> Pessoal, boa tarde. Eu estou rodando o Bot em uma máquina virtual Linux, porém quando eu início ele , logo no primeiro comando é como se ele desse um Alt Tab e segurasse a tecla, no Windows isso não acontece, alguém sabe o que pode ser? Outra coisa, vocês rodam em máquina virtual o Bot , alguma recomendação?

Estranho.
Aqui estou rodando em uma VM com Linux tbm e nunca ocorreu isso. Está perfeito. Farmando 24h/dia.

Tá utilizando a versão original do bot ou a multiaccount?

Aqui a única coisa que preciso fazer é deixar o navegador em tela cheia na VM (equivalente a tecla F11).

Utilizo Google chrome

**Comment by themexdev** [comment]
Estou utilizando a versão com multi account e validação da raridade de baus.
A sua VM você roda na sua máquina mesmo? Consome muita CPU? Porque a minha faz a CPU do notebook esquentar bastante, bater tipo uns 80 graus quando eu abro o Bomb.

**Comment by cleitonleonel** [comment]
Rodando liso aqui no ubuntu 20.04 versão original com alguns ajustes que fiz..

https://user-images.githubusercontent.com/11451914/147861430-8222f6ac-0d64-4dcc-b629-35ff221cc1a8.mp4

.

**Comment by kerferber** [comment]
> Estou utilizando a versão com multi account e validação da raridade de baus. A sua VM você roda na sua máquina mesmo? Consome muita CPU? Porque a minha faz a CPU do notebook esquentar bastante, bater tipo uns 80 graus quando eu abro o Bomb.

Eu só tenho uma conta, não tenho como testar o multiaccount.

Sobre a VM, estou rodando no Google Cloud.

Quando estava rodando o bot no meu notebook também esquentava bastante. Eu estava preocupado pois estava deixando 24h/dia o notebook bastante aquecido.

Esse foi o principal motivo de eu ter migrado pra VM no google cloud. Deu um pouco de trabalho pra acertar tudo mas valeu a pena. Agora o farm não para e meu notebook tá lá quietinho, desligado. Rsrsrs

**Comment by themexdev** [comment]
Ah, boa, vou dar uma olhada lá no GCP, quanto você esta pagando?

**Comment by JonesCunha** [comment]
> 

Fala Amigo, na GCP eu coloquei uma e2-medium com 2vcpu e 8gb, mas após alguns dias rodando e operando com alta carga, o proprio gcp subir pra 4vcpu e ficou muito liso!
Pra criar uma máquina assim, tem a opção Custom na hora de especificar.
Quanto ao custo, ainda estou usando os créditos grátis, depois quando fechar os relatórios de faturamento eu posto aqui.

**Comment by themexdev** [comment]
Estranho, estou tentando rodar em um Ubuntu com interface grafica, 6GB de RAM 6 vCPU e esta parecendo uma carroça, qual o segredo...rs?

**Comment by kerferber** [comment]
Aqui estou usando também custom, com 4 vCPUs, 8 GB de memória.

O uso do processador fica entre 90 e 95%
Está funcionando bem.

Já aumentei as especificações mas estava consumindo meus créditos muito rapidamente com consumo de processamento em 80%. Então reduzi.

**Comment by cleitonleonel** [comment]
Versão "multijanelas" no linux caso alguém quiser testar, fiz de 2 modos diferentes, uma semelhante ao controle de abas sugerido aqui, porém com tab infinito e outro utilizando funções do server X do linux, para controlar as janelas existem ainda os bugs de demorar clicar para entrar, controle de botões,mas pelo que percebi isso ocorre em todas as versões do projeto...bom segue o link para quem usar linux e quiser testar...[bombcrypto-bot](https://github.com/cleitonleonel/bombcrypto-bot.git )
