### ISSUE TITLE
Identifica os heroes verdes mas não coloca para trabalhar.

### ISSUE THREAD

**Issue by GstvCnb** [mpcabete/bombcrypto-bot#548]
Identifica os heroes verdes e fica clicando no "rest" em looping.
No CMD ele mostra:
    
    4 green bars detected 
    5 buttons detected 
    4 buttons with green bars detected
    clicking in 4 heroes

e fica nesse looping.

**Comment by mrkraft87** [comment]
Já me aconteceu ontem. Hoje vou ver se acontece de novo ou não

**Comment by dilneiss** [comment]
aqui também está acontecendo em 3 contas

**Comment by mrkraft87** [comment]
já li aqui algures que o problema era por estar em PT/BR em vez de EN. Alterei, vou ver se pega!

**Comment by eoliveiramg** [comment]
Realmente colocar em inglês resolve o problema!
