### ISSUE TITLE
Como editar o "delay" do clique nas imagens? 

### ISSUE THREAD

**Issue by fumasa21** [mpcabete/bombcrypto-bot#549]
Ola! parabens a todos os envolvidos pelo excelente trabalho, tenho um pc fraco, quando a imagem do botao aparece o bot ja clicou e o ponteiro mouse fica parado sem açao ate a proxima tarefa, isso acontece muitas vezes gostaria de editar esse time de quando cursor chega na imagem ficar uns 5 segundos e depois clicar, muito obrigado.

**Comment by cristianomg** [comment]
a função de click nos botões é `clickBtn(img,name=None, timeout=3, threshold = ct['default'])` , vc pode colocar um delay após a função `moveToWithRandomness` (função que movimenta o mouse até o botão.

para adicionar um delay utilize a função `time.sleep(tempo_em_segundos)` (substitua o tempo_em_segundos pelo tempo de delay que vc quer colocar.

ps: cuidado para n colocar um delay muito grande para não afetar o login, pois se colocar um tempo muito grande poderá causar o erro login expired

**Comment by fumasa21** [comment]
> a função de click nos botões é `clickBtn(img,name=None, timeout=3, threshold = ct['default'])` , vc pode colocar um delay após a função `moveToWithRandomness` (função que movimenta o mouse até o botão.
> 
> para adicionar um delay utilize a função `time.sleep(tempo_em_segundos)` (substitua o tempo_em_segundos pelo tempo de delay que vc quer colocar.
> 
> ps: cuidado para n colocar um delay muito grande para não afetar o login, pois se colocar um tempo muito grande poderá causar o erro login expired
