### ISSUE TITLE
Need help in refresh page

### ISSUE THREAD

**Issue by mkroxm** [mpcabete/bombcrypto-bot#55]
Is there any option for refresh page when login page detected coz some time it's got stuck in login page so it's better to refresh page eatch time before login 
In index.py

if login_attempts > 3:
        sys.stdout.write('\ntoo many login attempts, refreshing.')
        login_attempts = 0
        pyautogui.press('f5')
        return

This one is not working for me any solution 😔

**Comment by mpcabete** [comment]
Hey, the code only recognized an "login attempt" when the sign button was clicked maybe that is why it is not working for you. 
The code now increases the login attempt when the connect wallet button is clicked, try to download the new version and check if it is working now :)
