### ISSUE TITLE
Importante! Bot Fez Scam em um usuario? Leia e contribua com informações para tirarmos conclusões

### ISSUE THREAD

**Issue by Manccininft** [mpcabete/bombcrypto-bot#550]
Ola Comunidade. 
Estava procurando algumas Features e acabei me deparando com uma denuncia de Scam supostamente feita por este bot, em um tópico chamado "Account in Background/Contas em Segundo plano" e gostaria de compartilhar as prints aqui para que todos possam visualizar o ocorrido
![Primeira print](https://user-images.githubusercontent.com/96998211/147899522-360249e8-3908-41f9-9a4f-6413ba629054.png)
![segundo print](https://user-images.githubusercontent.com/96998211/147899525-5263c0d8-a3e4-4b0f-a00c-9c1fc7734bd7.png)
![Terceiro Print](https://user-images.githubusercontent.com/96998211/147899528-f1512fd6-1837-4144-9e7d-03423c544bc3.png)
![Quarta print](https://user-images.githubusercontent.com/96998211/147899529-bc7fc147-73ed-4493-84f0-2a5d16ec5461.png)
![Quinta print](https://user-images.githubusercontent.com/96998211/147899530-0c05c711-b2ce-44d0-b09e-1e6105f4728a.png)
![Sexta Print](https://user-images.githubusercontent.com/96998211/147899531-b805934c-0c62-4dc5-99db-52453f2baa31.png)

Este foi o debate ocorrido e gostaria que mais pessoas avalia-sem para tirarmos algumas conclusões:

1ªRealmente foi este bot realizou o Scan? Avaliei o link por ele enviado e o Codigo deste bot com um outro amigo programador e a grosso modo nao consegui visualizar nada no codigo que poderia agir de forma maliciosa.
2ºO link que ele pegou o bot da direto neste repositorio, o que indica que nao foi um link Malicioso.
3º Avaliei a Hash de transação na BSC que ele postou e percebi que a conta que recebeu os BNB's transferidos realmente tinha caracteristica de uma conta Scan: Varios trades de carteiras metamask diferentes foram realizados para a Metamask scan e ela manda no mesmo dia, para uma outra Metamask todas as moedas recebidas. 
Todas tinham algo em comum: Sempre tinha Bcoin sendo transferido, então sustenta a Tese de que possivelmente, a porta de entrada foi o Bombcrypto para o scan, sustentando a tese de que realmente foi um Bot de Bombcrypto. 

Gostaria que outros colegas programadores ajudassem a procurar possiveis Malwares ou Informações no Codigo para definirmos se este codigo de Bot é seguro ou não e se o Scan ocorrido com o Usuario mostrado nos prints foi mesmo deste bot ou não.

**Comment by cleitonleonel** [comment]
> Ola Comunidade. Estava procurando algumas Features e acabei me deparando com uma denuncia de Scam supostamente feita por este bot, em um tópico chamado "Account in Background/Contas em Segundo plano" e gostaria de compartilhar as prints aqui para que todos possam visualizar o ocorrido ![Primeira print](https://user-images.githubusercontent.com/96998211/147899522-360249e8-3908-41f9-9a4f-6413ba629054.png) ![segundo print](https://user-images.githubusercontent.com/96998211/147899525-5263c0d8-a3e4-4b0f-a00c-9c1fc7734bd7.png) ![Terceiro Print](https://user-images.githubusercontent.com/96998211/147899528-f1512fd6-1837-4144-9e7d-03423c544bc3.png) ![Quarta print](https://user-images.githubusercontent.com/96998211/147899529-bc7fc147-73ed-4493-84f0-2a5d16ec5461.png) ![Quinta print](https://user-images.githubusercontent.com/96998211/147899530-0c05c711-b2ce-44d0-b09e-1e6105f4728a.png) ![Sexta Print](https://user-images.githubusercontent.com/96998211/147899531-b805934c-0c62-4dc5-99db-52453f2baa31.png)
> 
> Este foi o debate ocorrido e gostaria que mais pessoas avalia-sem para tirarmos algumas conclusões:
> 
> 1ªRealmente foi este bot realizou o Scan? Avaliei o link por ele enviado e o Codigo deste bot com um outro amigo programador e a grosso modo nao consegui visualizar nada no codigo que poderia agir de forma maliciosa. 2ºO link que ele pegou o bot da direto neste repositorio, o que indica que nao foi um link Malicioso. 3º Avaliei a Hash de transação na BSC que ele postou e percebi que a conta que recebeu os BNB's transferidos realmente tinha caracteristica de uma conta Scan: Varios trades de carteiras metamask diferentes foram realizados para a Metamask scan e ela manda no mesmo dia, para uma outra Metamask todas as moedas recebidas. Todas tinham algo em comum: Sempre tinha Bcoin sendo transferido, então sustenta a Tese de que possivelmente, a porta de entrada foi o Bombcrypto para o scan, sustentando a tese de que realmente foi um Bot de Bombcrypto.
> 
> Gostaria que outros colegas programadores ajudassem a procurar possiveis Malwares ou Informações no Codigo para definirmos se este codigo de Bot é seguro ou não e se o Scan ocorrido com o Usuario mostrado nos prints foi mesmo deste bot ou não.

Vi a discussão toda e nada a ver o que o cara falou desse bot, pelo menos a versão original não tem nada de roubar conta não, a versão que o Youtuber postou é que me parece ter umas coisinhas diferentes, baixei agora pra testar, e ver onde está o bicho papão, estou adaptando uma versão aqui no Linux multiaccounts kkkk e tá funcionando bem ...

**Comment by KikoBMa** [comment]
Eu utilizo esse BOT baixado direto do mesmo link em 4 contas minhas pelo sistema de Multiaccounts e não tive problema nenhum.. ele deve ter clicado em algo que não devia em um outro lugar e foi SCAMADO.

**Comment by Yaagod** [comment]
Cara o código do robô é aberto, qualquer um pode ver, se tivesse algo malicioso no código aqui do GitHub, algum dos milhares de usuários perceberia né k

**Comment by walterdis** [comment]
O código é aberto, qualquer um pode analisar e, se não souber, pagar alguém que faça isso por vc.
Na própria "issue" que vc mostrou, já foi desacreditado.
O infeliz que deve passar o dia abrindo coisas que não devem no pc que joga.

Daqui a pouco o DEV se irrita e para de atualizar o repo por causa de tópico desse nível.

**Comment by pedrozun** [comment]
Primeira coisa que ele deveria ter feito é ver em quais lugares a metamask foi conectada e não vir aqui.

**Comment by Igorlegacy** [comment]
Desnecessário esse tipo de inssue... o código está ai, para qualquer um com mínimo de conhecimento consegue dar uma lida em todos os arquivos e entender por cima o que cada coisa está sendo feita.

Acredito que os arquivos do mpcabate, seja um reutilizado como base para diversos projetos e incrivelmente até agora, nenhuma pessoa com "conhecimento" reportou algo anormal..

Alías, são sempre as mesmas pessoas "leigas" que reportam scam... talvez tão leigas a ponto de cair em outro tipo de scam besta e o primeiro lugar para vir reclamar é aqui.

**Comment by fguide** [comment]
Mais uma vez essa historia... as pessoas usam metamask em conta logada o google account ou firefox account e depois reclamam do bot, claro...

Sejam menos ingênuos.

**Comment by kerferber** [comment]
Acho uma tremenda falta de respeito isto. 
Conforme já dito acima, o bot possui código aberto para qualquer um analisar e tirar sua próprias conclusões.

Não entende nada de programação? Não use este Bot código aberto. COMPRE um qualquer '.exe' que não deverá ter código malicioso... (CONTÉM IRONIA)

Este bot é mais que um bot, é uma OBRA DE ARTE, e ainda gratuito e opensource. Eu particularmente fiz doação através de pix pois o dev merece, e pretendo doar mais.

Existem centenas de relatos de scam no grupo oficial do telegram, provavelmente clicou no lugar errado e tem a AUDÁCIA de acusar um bot com código fonte aberto. 

Se eu fosse o desenvolvedor processaria o acusador que proferiu acusação infundada e exigiria reparação na esfera judicial. Internet não é terra de ninguém...

**Comment by thereis** [comment]
@Manccininft se tu não tem a capacidade de analisar um código ou aprender alguma linguagem de programação, faça o favor de não postar merda.

Que issue mais inútil.

**Comment by backslash-f** [comment]
Algum admin por favor fecha essa issue e bloqueia os pau no cu que abrem essas merda. Bah, tomar no cu esse maluco meu, porra, haja paciência...

https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-personal-account

**Comment by emsjustin** [comment]
É pra isso que o código é opensource... 99% dos bots que tem por ai é só copia do mpcabete com algum PR que ainda não foi aprovado.

**Comment by cleitonleonel** [comment]
> É pra isso que o código é opensource... 99% dos bots que tem por ai é só copia do mpcabete com algum PR que ainda não foi aprovado.

Sabe de algum multicontas que funcione em linux???? fiz 2 versões aqui pra linux uma com o esquema de tabs infinitos e outro manipulando as janelas do sistema com xdotooll, wmctrl e xprop , fiz também um esquema manipulando o display pra rodar em background usando pyvirtualdisplay e Xorg com selenium, funciona bem, mas estou em busca de algo desenvolvido para linux em que outros devs tenham feito melhor.

**Comment by cleitonleonel** [comment]
Um método simples no windows com pygetwindow que nem funciona no linux que tive que criar aqui é o getWindowsWithTitle('Untitled'), tive que fazer do zero....

```
def get_windows_with_title(title):
    # sudo apt-get install xdotool wmctrl
    windows_list = [w.split() for w in run_command(["wmctrl", "-lG"]).splitlines()]

    # check if the window is "normal" and / or minimized
    windows_with_title = [
        {"id": w[0], "is_minimized": all([
            "_NET_WM_STATE_HIDDEN" not in run_command(["xprop", "-id", w[0]]),
            "_NET_WM_WINDOW_TYPE_NORMAL" in run_command(["xprop", "-id", w[0]])]),
            "application": " ".join(w[-2:]).replace("–", "").lstrip(), "title": w[7]
         } for w in windows_list if title in w[7]]

    return windows_with_title
```

**Comment by maykoHGP** [comment]
Aconteceu comigo ontem, perdi meus bnbs e bcoin, foi durante o horario que deixei o bot rodando e fui trabalhar, não lembro de ter clicado em algo malicoso, mas não culpo o bot eu devo ter feito algo de errado

**Comment by cleitonleonel** [comment]
Versão "multijanelas" no linux caso alguém quiser testar, fiz de 2 modos diferentes, uma semelhante ao controle de abas sugerido aqui, porém com tab infinito e outro utilizando funções do server X do linux, para controlar as janelas existem ainda os bugs de demorar clicar para entrar, controle de botões,mas pelo que percebi isso ocorre em todas as versões do projeto...bom segue o link para quem usar linux e quiser testar...[bombcrypto-bot](https://github.com/cleitonleonel/bombcrypto-bot.git )

**Comment by Manccininft** [comment]
Após esses dias cheguei a algumas conclusões:
Alguns programadores são burros. Sabem ler codigos de programação mas não tem capacidade de ler um texto feito pelo autor do Tópico. 
Criei o post e disse que nao consegui visualizar nada malicioso e alguns corroboraram minha analise junto a outro colega programador, e deixei bem especifico que o post era para validarmos as nossas informações em conjunto. Cheguei a um veredicto que os scans nao estão rolando deste bot. 
A ideia do Post é para um leigo no quesito programação mas que é entusiasta no bombcrypto venha, leia as nossas analises e se sinta mais seguro sobre o que é um codigo opensource. 

Para os que pediram Ban e xingaram, espero sinceramente um pessimo ano porque gente estupida merece. Leia o intuito do post e o quanto ele é reconfortante para quem é leigo que esta baixando o BOT. O post tem varios programadores diferentes dizendo "nao é scan, eu li eu garanto".

Enfim, parabens aos que responderam a fim de tirar as duvidas e medos. Voces passaram pelo pré-zinho e aprenderam a ler um tópico.
Aos leigos, acreditamos que não é um scan, todavia, precisamos que vocês que foram lesados por Scan's noBombcrypto façam uma retrospectiva de onde clicaram/do que baixaram até o scan ocorrido. Se buscaram outro bot antes de chegar neste, etc.

As criticas aqui feitas para a estupides humana esta direcionada principalmente ao @Blacslash-f e ao @Thereis. Tudode ruim pra voces

**Comment by kerferber** [comment]
> Após esses dias cheguei a algumas conclusões: Alguns programadores são burros. Sabem ler codigos de programação mas não tem capacidade de ler um texto feito pelo autor do Tópico. Criei o post e disse que nao consegui visualizar nada malicioso e alguns corroboraram minha analise junto a outro colega programador, e deixei bem especifico que o post era para validarmos as nossas informações em conjunto. Cheguei a um veredicto que os scans nao estão rolando deste bot. A ideia do Post é para um leigo no quesito programação mas que é entusiasta no bombcrypto venha, leia as nossas analises e se sinta mais seguro sobre o que é um codigo opensource.
> 
> Para os que pediram Ban e xingaram, espero sinceramente um pessimo ano porque gente estupida merece. Leia o intuito do post e o quanto ele é reconfortante para quem é leigo que esta baixando o BOT. O post tem varios programadores diferentes dizendo "nao é scan, eu li eu garanto".
> 
> Enfim, parabens aos que responderam a fim de tirar as duvidas e medos. Voces passaram pelo pré-zinho e aprenderam a ler um tópico.

Pessoas como tu deviam passar longe de uma comunidade de desenvolvedores. Usurpar a boa fé de quem só quer ajudar sem cobrar nada em troca levantando pseudo suspeitas não tem meu respeito.

Passar bem

**Comment by Manccininft** [comment]
> > Após esses dias cheguei a algumas conclusões: Alguns programadores são burros. Sabem ler codigos de programação mas não tem capacidade de ler um texto feito pelo autor do Tópico. Criei o post e disse que nao consegui visualizar nada malicioso e alguns corroboraram minha analise junto a outro colega programador, e deixei bem especifico que o post era para validarmos as nossas informações em conjunto. Cheguei a um veredicto que os scans nao estão rolando deste bot. A ideia do Post é para um leigo no quesito programação mas que é entusiasta no bombcrypto venha, leia as nossas analises e se sinta mais seguro sobre o que é um codigo opensource.
> > Para os que pediram Ban e xingaram, espero sinceramente um pessimo ano porque gente estupida merece. Leia o intuito do post e o quanto ele é reconfortante para quem é leigo que esta baixando o BOT. O post tem varios programadores diferentes dizendo "nao é scan, eu li eu garanto".
> > Enfim, parabens aos que responderam a fim de tirar as duvidas e medos. Voces passaram pelo pré-zinho e aprenderam a ler um tópico.
> 
> Pessoas como tu deviam passar longe de uma comunidade de desenvolvedores. Usurpar a boa fé de quem só quer ajudar sem cobrar nada em troca levantando pseudo suspeitas não tem meu respeito.
> 
> Passar bem

Percebi que voce também nao sabe ler. 

Tudo de ruim para você

**Comment by cleitonleonel** [comment]
Relaxa galera, fui um dos primeiros a me posicionar sobre esse assunto, vi a discussão e achei um pouco de ingenuidade do rapaz autor do tal comentário lá sobre scam, discordei das palavras dele assim como discordo de bastante palavras ditas aqui nesse tópico...
Se era pra ajudar acabou aguçando a falta de empatia de alguns...
Vamos com calma, como desenvolvedor reitero aqui que não existe código malicioso na versão original,nem nas versões multijanelas que testei...durmam bem amigos.

**Comment by kerferber** [comment]
> > > Após esses dias cheguei a algumas conclusões: Alguns programadores são burros. Sabem ler codigos de programação mas não tem capacidade de ler um texto feito pelo autor do Tópico. Criei o post e disse que nao consegui visualizar nada malicioso e alguns corroboraram minha analise junto a outro colega programador, e deixei bem especifico que o post era para validarmos as nossas informações em conjunto. Cheguei a um veredicto que os scans nao estão rolando deste bot. A ideia do Post é para um leigo no quesito programação mas que é entusiasta no bombcrypto venha, leia as nossas analises e se sinta mais seguro sobre o que é um codigo opensource.
> > > Para os que pediram Ban e xingaram, espero sinceramente um pessimo ano porque gente estupida merece. Leia o intuito do post e o quanto ele é reconfortante para quem é leigo que esta baixando o BOT. O post tem varios programadores diferentes dizendo "nao é scan, eu li eu garanto".
> > > Enfim, parabens aos que responderam a fim de tirar as duvidas e medos. Voces passaram pelo pré-zinho e aprenderam a ler um tópico.
> > 
> > 
> > Pessoas como tu deviam passar longe de uma comunidade de desenvolvedores. Usurpar a boa fé de quem só quer ajudar sem cobrar nada em troca levantando pseudo suspeitas não tem meu respeito.
> > Passar bem
> 
> Percebi que voce também nao sabe ler.
> 
> Tudo de ruim para você

Paz e luz na tua vida. Está precisando.

**Comment by thereis** [comment]
> Após esses dias cheguei a algumas conclusões:
> 
> Alguns programadores são burros. Sabem ler codigos de programação mas não tem capacidade de ler um texto feito pelo autor do Tópico. 
> 
> Criei o post e disse que nao consegui visualizar nada malicioso e alguns corroboraram minha analise junto a outro colega programador, e deixei bem especifico que o post era para validarmos as nossas informações em conjunto. Cheguei a um veredicto que os scans nao estão rolando deste bot. 
> 
> A ideia do Post é para um leigo no quesito programação mas que é entusiasta no bombcrypto venha, leia as nossas analises e se sinta mais seguro sobre o que é um codigo opensource. 
> 
> 
> 
> Para os que pediram Ban e xingaram, espero sinceramente um pessimo ano porque gente estupida merece. Leia o intuito do post e o quanto ele é reconfortante para quem é leigo que esta baixando o BOT. O post tem varios programadores diferentes dizendo "nao é scan, eu li eu garanto".
> 
> 
> 
> Enfim, parabens aos que responderam a fim de tirar as duvidas e medos. Voces passaram pelo pré-zinho e aprenderam a ler um tópico.
> 
> Aos leigos, acreditamos que não é um scan, todavia, precisamos que vocês que foram lesados por Scan's noBombcrypto façam uma retrospectiva de onde clicaram/do que baixaram até o scan ocorrido. Se buscaram outro bot antes de chegar neste, etc.
> 
> 
> 
> As criticas aqui feitas para a estupides humana esta direcionada principalmente ao @Blacslash-f e ao @Thereis. Tudode ruim pra voces

Não tenho culpa se você é um asno. Passar bem.

**Comment by rafaelvacci** [comment]
E ai pessoal, alguma novidade sobre o assunto?

Estive analisando bastante e teve somente esse caso citado, ninguém mais reportou.

Vários amigos até com lendario na conta usam, eu também estou usando.. vários comentarios no youtube de pessoas usando, mas só esse de scam.

Venho até aqui pelo seguinte motivo, um amigo teve a carteira roubada e eu indiquei o bot a ele, por eu usar e muitos outros amigos usarem também, porém a carteira dele foi roubada e ele mencionou que de suspeito só usou o bot mesmo. 

Acredito que por ter o código aberto e muitos usuários sem nenhum tipo de problema, o bot do mpcabete parece ser bem confiável, inclusive tem gente que usa até com diversas contas e nenhum report até agora.

Porém o caso dele suspeito que seja scam por outra forma, analisamos e não tinha nenhum contrato suspeito e nenhum site estranho conectado, somente o bomb.

Carteira dele para análise: 0xDB672A5E7aBA9ae56938bF722c8d926Badf67e7D

**Comment by thereis** [comment]
> E ai pessoal, alguma novidade sobre o assunto?
> 
> 
> 
> Estive analisando bastante e teve somente esse caso citado, ninguém mais reportou.
> 
> 
> 
> Vários amigos até com lendario na conta usam, eu também estou usando.. vários comentarios no youtube de pessoas usando, mas só esse de scam.
> 
> 
> 
> Venho até aqui pelo seguinte motivo, um amigo teve a carteira roubada e eu indiquei o bot a ele, por eu usar e muitos outros amigos usarem também, porém a carteira dele foi roubada e ele mencionou que de suspeito só usou o bot mesmo. 
> 
> 
> 
> Acredito que por ter o código aberto e muitos usuários sem nenhum tipo de problema, o bot do mpcabete parece ser bem confiável, inclusive tem gente que usa até com diversas contas e nenhum report até agora.
> 
> 
> 
> Porém o caso dele suspeito que seja scam por outra forma, analisamos e não tinha nenhum contrato suspeito e nenhum site estranho conectado, somente o bomb.
> 
> 
> 
> Carteira dele para análise: 0xDB672A5E7aBA9ae56938bF722c8d926Badf67e7D

Uso o bot há 2 meses e não tive nenhum scam. Seu amigo deve ter utilizado alguma extensão maliciosa de navegador ou até mesmo o ativador do Windows. Dou 200% de certeza que foi problema e erro do seu amigo do que a ferramenta daqui.

Qualquer leigo em Python pode abrir o código e ver que não há nenhuma requisição pra serviço externo ou back doors pra invadir carteira.

Essa merda de thread já deveria ter sido arquivada/deletada há muito tempo.

**Comment by thereis** [comment]
> E ai pessoal, alguma novidade sobre o assunto?
> 
> 
> 
> Estive analisando bastante e teve somente esse caso citado, ninguém mais reportou.
> 
> 
> 
> Vários amigos até com lendario na conta usam, eu também estou usando.. vários comentarios no youtube de pessoas usando, mas só esse de scam.
> 
> 
> 
> Venho até aqui pelo seguinte motivo, um amigo teve a carteira roubada e eu indiquei o bot a ele, por eu usar e muitos outros amigos usarem também, porém a carteira dele foi roubada e ele mencionou que de suspeito só usou o bot mesmo. 
> 
> 
> 
> Acredito que por ter o código aberto e muitos usuários sem nenhum tipo de problema, o bot do mpcabete parece ser bem confiável, inclusive tem gente que usa até com diversas contas e nenhum report até agora.
> 
> 
> 
> Porém o caso dele suspeito que seja scam por outra forma, analisamos e não tinha nenhum contrato suspeito e nenhum site estranho conectado, somente o bomb.
> 
> 
> 
> Carteira dele para análise: 0xDB672A5E7aBA9ae56938bF722c8d926Badf67e7D

Acabei de ver aqui que ele tem ZDC (zodiacs) na carteira. Pode ter certeza que foi esse contrato que scammou ele. Há relatos de outros trocentos jogadores que tiveram suas carteiras hackeadas depois de terem assinado e comprado o token zodiacs
