### ISSUE TITLE
Image recognition error in google chrome - windows

### ISSUE THREAD

**Issue by coolwateRx3** [mpcabete/bombcrypto-bot#551]
I already created an issue report and tried to solve it, but I am very lost and might need some help please. I have really no clue.

The bot works, but doesn't recognize the google chrome images - just the one from the folder (which are screens of the chrome app.bombcrypto)

Running it on:
-windows 2019
-python 3.9.9
-I am starting the bot, when the google chrome windows is open and app.bombcrypto already started.

Thank you in advance :)

To the other issue request:
https://github.com/mpcabete/bombcrypto-bot/issues/523

**Comment by fguide** [comment]
Multiple displays?
Resolution?
Scaling config?
Browser zoom?

**Comment by coolwateRx3** [comment]
-no multiple Displays
-1920x1080
-normally 125% but I also tried 100% already
-normally 125% but tried 100% as well. I have also tried fullscreen.

I am about to despair lol^^

**Comment by fguide** [comment]
Well I kinda don't understand this:
>The bot works, but doesn't recognize the google chrome images - just the one from the folder (which are screens of the chrome app.bombcrypto)

So does CMD show any green bars detected?

You should set everything to 100%. Have you tried another browser? Also, aren't you by any chance running on limited video config? shuch as 16bit, etc

**Comment by fguide** [comment]
I believe you can check it by running 'ms-settings:display' on CMD and then going through advanced settings.

Sorry I can't test it on windows server as I have no access to it.
