### ISSUE TITLE
Google VM linux

### ISSUE THREAD

**Issue by KorlashKun** [mpcabete/bombcrypto-bot#552]
alguem sabe resolver ? to usando o Debian, no vm da google
![image](https://user-images.githubusercontent.com/78668048/147954797-ccc10245-c0a7-4d30-929b-9de3db46d2f9.png)

**Comment by fguide** [comment]
Amigo, tá escrito no erro, não é suportado PyGetWindow no linux, vc deve estar com a versão multi janelas...

**Comment by rzanca** [comment]
Use a versão original e VNC para abrir múltiplas contas. Ou utilize Docker.

**Comment by cleitonleonel** [comment]
> alguem sabe resolver ? to usando o Debian, no vm da google ![image](https://user-images.githubusercontent.com/78668048/147954797-ccc10245-c0a7-4d30-929b-9de3db46d2f9.png)

Passei por isso e tentei resolver o esquema "multijanelas" no linux e até que consegui algo satisfatório vou deixar aqui o link da versão customizada que fiz, se puder testar e dar um feedback ... https://github.com/cleitonleonel/bombcrypto-bot.git

**Comment by victormass** [comment]
Salve @cleitonleonel, vi sua alteração aqui mas no caso você abre duas abas, ai no caso fica uma conta em cada aba, porém se altera a conta de uma aba na metamask, acaba alterando para as duas, se uma das contas cair ai o bot vai tentar entrar na mesma conta.

Porque não deixar a gente abrir as duas contas em usuários no firefox diferente e ao iniciar o bot você só olha estas abas?

**Comment by victormass** [comment]
aqui está dando esse erro @cleitonleonel 
![image](https://user-images.githubusercontent.com/36490153/148439573-4ab46b24-336e-4fe8-a6d8-2fe00d6444d2.png)

**Comment by cleitonleonel** [comment]
> aqui está dando esse erro @cleitonleonel ![image](https://user-images.githubusercontent.com/36490153/148439573-4ab46b24-336e-4fe8-a6d8-2fe00d6444d2.png)

wmctrl not found, instala esse pacote aí....e também xdotool

**Comment by cleitonleonel** [comment]
> Salve @cleitonleonel, vi sua alteração aqui mas no caso você abre duas abas, ai no caso fica uma conta em cada aba, porém se altera a conta de uma aba na metamask, acaba alterando para as duas, se uma das contas cair ai o bot vai tentar entrar na mesma conta.
> 
> Porque não deixar a gente abrir as duas contas em usuários no firefox diferente e ao iniciar o bot você só olha estas abas?

verdade, testei aqui o esquema multijanela, não me atentei ao detalhe das multicontas para vários perfis do chrome, na verdade estou fazendo isso...sua colocação é pertinente.

**Comment by victormass** [comment]
> > aqui está dando esse erro @cleitonleonel ![image](https://user-images.githubusercontent.com/36490153/148439573-4ab46b24-336e-4fe8-a6d8-2fe00d6444d2.png)
> 
> wmctrl not found, instala esse pacote aí....e também xdotool

infelizmente mesmo instalando os 2 continua dando erro =\

**Comment by cleitonleonel** [comment]
> > > aqui está dando esse erro @cleitonleonel ![image](https://user-images.githubusercontent.com/36490153/148439573-4ab46b24-336e-4fe8-a6d8-2fe00d6444d2.png)
> > 
> > 
> > wmctrl not found, instala esse pacote aí....e também xdotool
> 
> infelizmente mesmo instalando os 2 continua dando erro =\

abra um novo terminal e execute o seguinte comandos "wmctrl -lG" e poste aqui a saída desse comando.

**Comment by victormass** [comment]
Aborta... consegui instalar aqui, porém agora ele abre as duas abas do firefox e ele dá o erro:

>>---> No window with the name bombcrypto was found

**Comment by victormass** [comment]
> > > > aqui está dando esse erro @cleitonleonel ![image](https://user-images.githubusercontent.com/36490153/148439573-4ab46b24-336e-4fe8-a6d8-2fe00d6444d2.png)
> > > 
> > > 
> > > wmctrl not found, instala esse pacote aí....e também xdotool
> > 
> > 
> > infelizmente mesmo instalando os 2 continua dando erro =\
> 
> abra um novo terminal e execute o seguinte comandos "wmctrl -lG" e poste aqui a saída desse comando.

Aborta... consegui instalar aqui, porém agora ele abre as duas abas do firefox e ele dá o erro:

>>---> No window with the name bombcrypto was found

**Comment by cleitonleonel** [comment]
> > > > > aqui está dando esse erro @cleitonleonel ![image](https://user-images.githubusercontent.com/36490153/148439573-4ab46b24-336e-4fe8-a6d8-2fe00d6444d2.png)
> > > > 
> > > > 
> > > > wmctrl not found, instala esse pacote aí....e também xdotool
> > > 
> > > 
> > > infelizmente mesmo instalando os 2 continua dando erro =\
> > 
> > 
> > abra um novo terminal e execute o seguinte comandos "wmctrl -lG" e poste aqui a saída desse comando.
> 
> Aborta... consegui instalar aqui, porém agora ele abre as duas abas do firefox e ele dá o erro:
> 
> > > ---> No window with the name bombcrypto was found

Eis a questão, só foi testado para chrome, use chrome ou aguarde uma correção para firefox.Deve sair em algumas horas.

**Comment by victormass** [comment]
Maravilha, no aguardo então 

> > > > > > aqui está dando esse erro @cleitonleonel ![image](https://user-images.githubusercontent.com/36490153/148439573-4ab46b24-336e-4fe8-a6d8-2fe00d6444d2.png)
> > > > > 
> > > > > 
> > > > > wmctrl not found, instala esse pacote aí....e também xdotool
> > > > 
> > > > 
> > > > infelizmente mesmo instalando os 2 continua dando erro =\
> > > 
> > > 
> > > abra um novo terminal e execute o seguinte comandos "wmctrl -lG" e poste aqui a saída desse comando.
> > 
> > 
> > Aborta... consegui instalar aqui, porém agora ele abre as duas abas do firefox e ele dá o erro:
> > > > ---> No window with the name bombcrypto was found
> 
> Eis a questão, só foi testado para chrome, use chrome ou aguarde uma correção para firefox.Deve sair em algumas horas.

Maravilha, no aguardo então.

**Comment by cleitonleonel** [comment]
> Maravilha, no aguardo então.

subi as alterações, aqui no ubuntu funcionou tanto em chrome quanto no firefox...

**Comment by vict1n** [comment]
@cleitonleonel quais configurações você tá usando? Tô usando Ubuntu tbm, mas o bomb tá travando muito

**Comment by cleitonleonel** [comment]
> @cleitonleonel quais configurações você tá usando? Tô usando Ubuntu tbm, mas o bomb tá travando muito

Tô usando as configurações da minha versão do bot, https://github.com/cleitonleonel/bombcrypto-bot

**Comment by vict1n** [comment]
@cleitonleonel tô usando ela e ta rodando legal. queria saber da configuração da máquina (aqui ta engasgando), você usa o Google cloud? Se sim, quais configurações?

**Comment by cleitonleonel** [comment]
> @cleitonleonel tô usando ela e ta rodando legal. queria saber da configuração da máquina (aqui ta engasgando), você usa o Google cloud? Se sim, quais configurações?

Ah claro, não, uso na minha máquina Ubuntu mesmo...
