### ISSUE TITLE
Solução erro ao fechar janela de acesso remoto

### ISSUE THREAD

**Issue by theduzzy** [mpcabete/bombcrypto-bot#554]
Eu uso uma máquina da google cloud para rodar o bot nas contas, mas sempre tive o problema do console simplesmente fechar se eu encerrasse a sessão remota, a máquina continuava ligada, intacta, porém o bot fechava.

Consegui encontrar no log um erro relacionado a pyautogui.FAILSAFE
Em resumo, é um bloqueio padrão para caso o mouse vá para um canto extremo da tela, toda vez que eu fechava o acesso remoto, o mouse da máquina "resetava" e ia pra um canto, e isso dava um sinal e o bot fechava através do "pyautogui.FAILSAFE"

Pra contornar isso, apenas adicionei `pyautogui.FAILSAFE = False` no início do código em index.py
Ficando assim: # Load config file.
stream = open("config.yaml", 'r')
c = yaml.safe_load(stream)
ct = c['threshold']
ch = c['home']
pause = c['time_intervals']['interval_between_moviments']
pyautogui.PAUSE = pause
pyautogui.FAILSAFE = False

**Comment by fguide** [comment]
Seu problema no windows não seria também pelo motivo do #505 ?
