### ISSUE TITLE
Error No module named 'yaml'. Alguém consegue me ajudar!!!

### ISSUE THREAD

**Issue by Rodrizeira** [mpcabete/bombcrypto-bot#556]
![Captura de tela 2022-01-04 114550](https://user-images.githubusercontent.com/97109495/148076448-0f770f5c-7771-4b0e-a836-e851fe087b01.png)

**Comment by cristianomg** [comment]
você instalou o modulo ? tente rodar o comando `pip3 install yaml` antes de rodar o comando para executar o bot

**Comment by jevemozer** [comment]
> ![Captura de tela 2022-01-04 114550](https://user-images.githubusercontent.com/97109495/148076448-0f770f5c-7771-4b0e-a836-e851fe087b01.png)

Estou com o mesmo erro, ja tentei o comando `pip3 install yaml` mas não funcionou.

**Comment by fguide** [comment]
Se vocês só tiverem uma versão de python instalada, nao tem necessidade de usar o comando python3, usem apenas python para ver se funciona.

outra dica: python -m pip install -r requirementes.txt dee ajudar com erros de instalação.

**Comment by rzanca** [comment]
> ![Captura de tela 2022-01-04 114550](https://user-images.githubusercontent.com/97109495/148076448-0f770f5c-7771-4b0e-a836-e851fe087b01.png)

Utilize apenas python index.py

**Comment by alefbz** [comment]
usei esse ultimo comando e o bot iniciou. 
Mas não esta reconhecendo os heroes e os dados da tela.

Sabe o que pode ser?

**Comment by Cupoz** [comment]
> você instalou o modulo ? tente rodar o comando `pip3 install yaml` antes de rodar o comando para executar o bot

![image](https://user-images.githubusercontent.com/98434897/151081910-fe2bdb78-3730-4e25-8a56-3a7424b54a68.png)

Este problema aparece, así que no funciona

**Comment by rzanca** [comment]
> > você instalou o modulo ? tente rodar o comando `pip3 install yaml` antes de rodar o comando para executar o bot
> 
> ![image](https://user-images.githubusercontent.com/98434897/151081910-fe2bdb78-3730-4e25-8a56-3a7424b54a68.png)
> 
> Este problema aparece, así que no funciona

pip3 install pyyaml
