### ISSUE TITLE
VM linux

### ISSUE THREAD

**Issue by sbragnot** [mpcabete/bombcrypto-bot#557]
![WhatsApp Image 2022-01-04 at 15 38 57](https://user-images.githubusercontent.com/56848420/148109649-74c128ac-0d5a-4734-bd8c-d0698393f7fe.jpeg)

Estou tendo problemas com lotação dessa pasta e nao consigo apagar ou evitar que ela encha, alguem sabe como apagar a pasta?

**Comment by fguide** [comment]
Amigo, essa é a pasta principal do sistema (como c:\ no WIndows). Deve estar cheia por vários motivos, uma vez que praticamente tudo no sistema fica nela. Com o comando abaixo vai saber as 20 maiores e dai vai conseguindo fazer sua limpeza:


>du -a / | sort -n -r | head -n 20

**Comment by sbragnot** [comment]
> 

Cara a vm não para de encher a memoria sozinha, eu tenho 50bg de espaço unico download que fiz foi o bot e ela fica enchendo tem alguma ideia do pq? e eu nao consigo esvaziar tbm

**Comment by sbragnot** [comment]
Se alguem tiver com o mesmo problema basta reiniciar a maquina
