### ISSUE TITLE
Bot para CryptoCars

### ISSUE THREAD

**Issue by themexdev** [mpcabete/bombcrypto-bot#559]
Pessoal, é possível adaptar esse bot para que ele funcionou no CryptoCars ou mesmo criar alguma coisa mais simples que funcione com este jogo?
Eu tentei adaptar o script aqui mas ele é bem complexo, ao menos para o meu conhecimento python atual :-(
Imensamente agradecido!!

**Comment by cleitonleonel** [comment]
> Pessoal, é possível adaptar esse bot para que ele funcionou no CryptoCars ou mesmo criar alguma coisa mais simples que funcione com este jogo? Eu tentei adaptar o script aqui mas ele é bem complexo, ao menos para o meu conhecimento python atual :-( Imensamente agradecido!!

Manda esse script aí que vc tentou adaptar, posso tentar... envie aqui para que outros possam ajudar, desde já adianto que sim é possível desenvolver bots para CryptoCars...

**Comment by themexdev** [comment]
Eu tentei adaptar o script do Bomb mas não cheguei em lugar algum então nem vale compartilhar o que tentei fazer porque infelizmente não saiu nenhum resultado dessa experiência...rs

Mas blz, vou tentando aqui .
Obrigado!

**Comment by cleitonleonel** [comment]
> Eu tentei adaptar o script do Bomb mas não cheguei em lugar algum então nem vale compartilhar o que tentei fazer porque infelizmente não saiu nenhum resultado dessa experiência...rs
> 
> Mas blz, vou tentando aqui . Obrigado!

Esse do bomb é específico demais amigo, foi feito com pyautogui justamente por não ser possível com Selenium ou outro esquema de automação, nesse caso do Ccars é mais próprio pra Selenium, pois ele é um site padrão e não webassembly como o bomb...

**Comment by cleitonleonel** [comment]
> Pessoal, é possível adaptar esse bot para que ele funcionou no CryptoCars ou mesmo criar alguma coisa mais simples que funcione com este jogo? Eu tentei adaptar o script aqui mas ele é bem complexo, ao menos para o meu conhecimento python atual :-( Imensamente agradecido!!

Tô com um rascunho de um bot para cryptocars aqui...

**Comment by fguide** [comment]
Eu tomaria cuidado com metodos usando selenium, javascript ou qualquer tipo de execução de código direta, como o jogo tem captcha e o sistema de quick race, podem punir por cheat.

Seria mais seguro um modelo de automacao de clique parecido com esse bot junto ao OCR do captcha usando pytesseract, dá inclusive pra usar o código antigo aqui do bot para server de exemplo.

**Comment by cleitonleonel** [comment]
> Eu tomaria cuidado com metodos usando selenium, javascript ou qualquer tipo de execução de código direta, como o jogo tem captcha e o sistema de quick race, podem punir por cheat.
> 
> Seria mais seguro um modelo de automacao de clique parecido com esse bot junto ao OCR do captcha usando pytesseract, dá inclusive pra usar o código antigo aqui do bot para server de exemplo.

Nos testes que fiz o bot faz o básico, os clicks podem ser substituídos por clicks com pyautogui, mas não tem nenhum tipo de injeção de código, o sistema de clicks selenium é baseado na interação humana assim como pyautogui, a diferença é que pyautogui faz a nível de sistema e selenium apenas utilizando os recursos do browser.
Todavia vale o bom senso no uso dessas ferramentas.

**Comment by themexdev** [comment]
Seria possível compartilhar o rascunho que você tem @cleitonleonel ?
