### ISSUE TITLE
about multi account

### ISSUE THREAD

**Issue by dtribale** [mpcabete/bombcrypto-bot#561]
hello, since tab is not working anymore and heroes keep going off the map.

can the setting reduce to 33-50% zoom? 100% zoom is working fine, but I want to know if it's possible to run at 33-50% zoom? thank you

**Comment by jeffplv** [comment]
How were you able to get multi to work? How many accounts total?

**Comment by VitotEPB** [comment]
> How were you able to get multi to work? How many accounts total?
> 
> 

#169

**Comment by Enzoerb** [comment]
Try to update the images inside “targets” to 33% or 50% zoom

**Comment by jeffplv** [comment]
is there a way to send certain heros to home?

**Comment by dtribale** [comment]
> Try to update the images inside “targets” to 33% or 50% zoom

how to update the images inside? what app do I need to screenshot 33% and 50%. is using snipping tool working?
