### ISSUE TITLE
[MUDANÇAS] Atualização 05/01

### ISSUE THREAD

**Issue by Yumiizera** [mpcabete/bombcrypto-bot#564]
Tempo de manutenção do servidor estendido para 10:30 de Brasilia.
⭐️ Adicionado recurso Work all & Rest All.
⭐️ Recurso adicionado após 10 segundos automaticamente vai para "NOVO MAPA"
⭐️ Adicionada IU de Ano Novo Lunar.
⭐️ Corrigir bugs.
⭐️  Redução de recompensas em 6%.

Nós consideramos propor soluções para tornar o jogo do BombCrypto mais confortável para os usuários e equilibrar a economia. Reduziremos a quantidade total de BCOIN extraída em 6%, dependendo da taxa de mineração de cada pessoa, a quantidade de BCOIN recebida mudará de forma diferente.
Em tempos não tão bons para o mercado de Gamefi quando é difícil encontrar um bom projeto. O BombCrypto ainda está aqui tentando se tornar um local de investimento confiável para todos. 

>Quero deixar a seguinte informação de que mudou alguns layout e; se isso prejudicará no funcionamento do bot?

**Comment by AllanHBC** [comment]
o Work All é legal que da pra fazer o bot clicar só no Work a cada X minutos (30 por exemplo) e sucesso, diminui drasticamente os clics e TALVEZ facilite em algo pra dinâmica de várias janelas abertas uma do lado da outra

**Comment by kerferber** [comment]
Aqui tive a leve impressão de que a janela/jogo está maior? Continuo no zoom 100% mas me parece que as barras de rolagem aumentaram. Pode dar problema no offset e etc. Ainda não consegui logar pra testar

**Comment by lsruiz08** [comment]
![image](https://user-images.githubusercontent.com/96508916/148225720-0dda1908-9bd0-4007-8dda-8d702b9e450e.png)

⭐️ Adicionado recurso Work all & Rest All

**Comment by LRBarbieri** [comment]
Agora da para fazer o bot clicar em All ao invés de herói por herói. Ansioso pela atualização 😁

**Comment by luisflavio-ms** [comment]
Testei o bot na nova att, tudo funcionando.

**Comment by kerferber** [comment]
Bot rodando liso aqui. 100%

**Comment by Liperim** [comment]
Seria interessante um discord para termos contato direto com o criador do bot, comunicação ficaria mais fácil, se bem que tudo funciona perfeitamente e de graça então só agradecimentos

**Comment by bmlima7** [comment]
To tentando fazer as modificaçoes aqui pra clicar no botao all, se alguem conseguir ai posta aqui pra a gente compartilhar

**Comment by FgTeaMBR** [comment]
Por agora a soluçao que fiz foi criar uma nova imagem com o botao "all", nomeala para "all.png"
Nova funçao:


def send_work():
      if clickBtn(images['go-back-arrow']):
          logger('Arrow Found, click!')
          time.sleep(2)
      if clickBtn(images['hero-icon']):
          logger('Hero Button found, click!')
          time.sleep(2)
      if clickBtn(images['all']):
          logger('All button found, click!')
          logger('Heros sucesfully reseted!')
          goToGame()
      global login_attempts
      login_attempts = 0
      time.sleep(2)


depois modifique no while o **refreshHereos()** para   **send_work()**


            if now - last["heroes"] > addRandomness(t['send_heroes_for_work'] * 60):
                last["heroes"] = now
                refreshHeroes()




somente temporario guys.

**Comment by gillyanbfoz** [comment]
> Por agora a soluçao que fiz foi criar uma nova imagem com o botao "all", nomeala para "all.png" Nova funçao:
> 
> def send_work(): if clickBtn(images['go-back-arrow']): logger('Arrow Found, click!') time.sleep(2) if clickBtn(images['hero-icon']): logger('Hero Button found, click!') time.sleep(2) if clickBtn(images['all']): logger('All button found, click!') logger('Heros sucesfully reseted!') goToGame() global login_attempts login_attempts = 0 time.sleep(2)
> 
> depois modifique no while o **refreshHereos()** para **send_work()**
> 
> ```
>         if now - last["heroes"] > addRandomness(t['send_heroes_for_work'] * 60):
>             last["heroes"] = now
>             refreshHeroes()
> ```
> 
> somente temporario guys.

Consegue disponibilizar o arquivo index ? fiz aqui e deu erro

**Comment by FgTeaMBR** [comment]
Indente corretamente a função.

aqui tem um arquivo de texto com ela indentada corretamente.
[send_work.txt](https://github.com/mpcabete/bombcrypto-bot/files/7816931/send_work.txt)

**Comment by gabrielwjesus** [comment]
o botão de X agora esta vermelho, é só tirar print e atualizar
o botão de Ok talvez precise ser atualizado, não testei ainda
mudou a cor da janela de erro
e realmente, evitar o desgaste e tempo do scrolll fazendo clicar somente no All seria legal pra quem ja joga no modo enviar Todos.

**Comment by FgTeaMBR** [comment]
Botao X e Ok funcionando normal

**Comment by ByPivete** [comment]
Aqui não funciona kkkk.

**Comment by mixellita** [comment]
Funcionando perfeitamente aqui.

Ah, e o botão X tá de boa aqui também.

**Comment by ByPivete** [comment]
> Funcionando perfeitamente aqui mas realmente, uma atualizacao no código pra clicar só em ALL seria mais rápido.
> 
> Ah, e o botão X tá de boa aqui também.

fez alguma modificação no arquivo? fui dormir estava funcionando. acordei e não ta mais kkk

**Comment by guilhermestudart** [comment]
Não consigo fazer essas sugestões funcionarem. Não tem como mandar uma txt pra eu testar aqui?

**Comment by luisflavio-ms** [comment]
o BOT tem a função de só colocar pra trabalhar os herois que estão com status verde, se vcs colocarem all eles vao ir com a barra vermelha, ao meu ver não compensa, a não ser que tenha como configurar pra ele colocar 1 em 1 hora por exemplo, ai sim compensaria....

**Comment by FgTeaMBR** [comment]
> o BOT tem a função de só colocar pra trabalhar os herois que estão com status verde, se vcs colocarem all eles vao ir com a barra vermelha, ao meu ver não compensa, a não ser que tenha como configurar pra ele colocar 1 em 1 hora por exemplo, ai sim compensaria....

ja tem essa opcao em config/send_heroes_for_work: x

**Comment by LRBarbieri** [comment]
> o BOT tem a função de só colocar pra trabalhar os herois que estão com status verde, se vcs colocarem all eles vao ir com a barra vermelha, ao meu ver não compensa, a não ser que tenha como configurar pra ele colocar 1 em 1 hora por exemplo, ai sim compensaria....

Não tem diferença alguma no farm colocar herói verde ou vermelho para trabalhar.

**Comment by guilhermestudart** [comment]
o problema é que o bot aqui não abre mais depois da att

**Comment by doug14** [comment]
Depois da mudança piorou o reconhecimento no botão OK, mesmo trocando a imagem. Alguém tem alguma solução?
Cheguei a ativar os print() no código para ver se estava passando pelo código, está passando mas não está reconhecendo.

**Comment by dilneiss** [comment]
opa, lancei uma atualização para a nova interface do dia 05/01/2022, essa versão vai clicar no botão all pra mandar todos trabalharem, funciona com infinita janelas. somente windows, linux não funciona, fique a vontade pra usar se quiser: https://github.com/dilneiss/bombcrypto-bot-1

**Comment by mixellita** [comment]
ah, o jogo ta desconectando qdo fica muito tempo iddle  e o bot nao corrige.

**Comment by mixellita** [comment]
> 

concordo !!!! Nao acho a opção ALL interessante, Como está o bot tá bem melhor.

**Comment by mixellita** [comment]
> o BOT tem a função de só colocar pra trabalhar os herois que estão com status verde, se vcs colocarem all eles vao ir com a barra vermelha, ao meu ver não compensa, a não ser que tenha como configurar pra ele colocar 1 em 1 hora por exemplo, ai sim compensaria....

concordo !!!! Nao acho a opção ALL interessante, Como está o bot tá bem melhor.

**Comment by maxuelgamer** [comment]
Realizei algumas alterações para clicar direto no all-btn ao invés de mandar hero por hero.

Vou enviar o index aqui pra quem quiser.

Basta trocar a extensão de TXT para PY.

[index.txt](https://github.com/mpcabete/bombcrypto-bot/files/7823920/index.txt)
