### ISSUE TITLE
Novo robô para a nova interface

### ISSUE THREAD

**Issue by JONASUK0** [mpcabete/bombcrypto-bot#566]
Novo robô. Você pode criar um novo bot para a nova interface que envia todos os heróis a cada 30 minutos, por favor. Muito obrigado.

**Comment by gabok2** [comment]
mas já existe isso mano, na config tem uma função que vc coloca quantos x minutos vc quer que ele verifique se existe herois disponíveis para trabalhar. Ai vc tb coloca no all se quiser que ele bota a cada 30m todos os herois para trabalhar ou green pra botar só os herois com stamina verde

**Comment by JONASUK0** [comment]
Independentemente da resistência que cada um tenha, quero enviar todos eles a cada 30 min na nova função da nova interface (enviar todos)

**Comment by JONASUK0** [comment]
você pode enviar para trabalhar com resistência em vermelho, (não precisa ser em verde)

**Comment by gabok2** [comment]
# [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
    # Valor padrão (em minutos): 10
    send_heroes_for_work: 127
na config tem essa parada ai, eu deixo 127 que a cada 2h e uns minutos ele vai botar todos meus herois para trabalhar. Vai apertar work por work.

**Comment by gabok2** [comment]
# [pt_BR]
  # Valor padrão: green
  # Opções disponíveis:
  # all   = seleciona todos os heróis (independente da barra de stamina)
  # green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
  # full  = seleciona somente os heróis com a barra de stamina cheia
  select_heroes_mode: "all"

e nessa parte eu deixo em all pra ele botar todos para trabalhar mesmo que esteja com stamina vermelha. A cada 2h e uns minutos ele vai botar todos para trabalhar

**Comment by JONASUK0** [comment]
Infelizmente não sei como editar o código, por isso gostaria que o criador do bot criasse um novo apenas para esta função

**Comment by gabok2** [comment]
vou te mandar um video que explica como acessar essa parte

**Comment by JONASUK0** [comment]
muito obrigado amigo

**Comment by gabok2** [comment]
pra adiantar, baixar o vscode. Escreve isso no google e baixa ele

**Comment by gabok2** [comment]
manda teu email, vou gravar o video ai te mando

**Comment by JONASUK0** [comment]
você pode carregar o link para a unidade do Google para que todos que lêem este comentário possam usá-lo

**Comment by gabok2** [comment]
blz

**Comment by JONASUK0** [comment]
desculpe por erros de ortografia, eu uso um tradutor, eu sou espanhol e eu não sei português

**Comment by JONASUK0** [comment]
Eu só quero usar o novo recurso (enviar tudo a cada 30 minutos ou mais) Eu não me importo se a resistência está em verde ou vermelho. Eu também gostaria de usar a nova flechita marrom que aparece abaixo da tela sem ter que clicar no ícone heróis

**Comment by JONASUK0** [comment]
sem ter que sair para a tela anterior, a partir da mesma tela de jogo, há uma nova seta marrom e há o ícone heróis, não há necessidade de ir para a tela anterior

**Comment by gabok2** [comment]
no inicio do video eu mostro como abrir o arquivo usando vscode e também amostro como abrir usando bloco de notas
https://drive.google.com/file/d/1PrRlMdZVK4Jw9l6ekRWQFcR5F-RHYL_H/view?usp=sharing

**Comment by kerferber** [comment]
só eu achei um pouco petulante suas exigências?

já é possível (sempre foi) enviar todos os heróis a cada 30 minutos, basta ler e fazer simples alterações no config.yaml

No config.yaml você altera esta variável para o tempo que quiser....
```
  time_intervals:
    # [en_US] Time interval for check if there are available heroes to work
    # Default value (in minutes): 10
    #
    # [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
    # Valor padrão (em minutos): 10
    send_heroes_for_work: 15
```

e mais abaixo, no mesmo config.yaml você altera o GREEN para ALL.. ele vai enviar todos os heróis independentemente da cor da barra...
```
 # [en_US]
  # Default value: green
  # Available options:
  # all   = select all heroes (regardless of the stamina bar)
  # green = select the heroes with green stamina bar (half or full)
  # full  = select only the heroes with full stamina bar
  #
  # [pt_BR]
  # Valor padrão: green
  # Opções disponíveis:
  # all   = seleciona todos os heróis (independente da barra de stamina)
  # green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
  # full  = seleciona somente os heróis com a barra de stamina cheia
  select_heroes_mode: "green"
```

APENAS isso.. pode editar este arquivo até mesmo no bloco de notas do windows (notepad)...

**Comment by gabok2** [comment]
ele não sabia como entrar nesse arquivo

**Comment by kerferber** [comment]
> ele não sabia como entrar nesse arquivo

me desculpe, mas se não conseguir entrar nesse arquivo irá conseguir instalar o python e rodar o bot?

**Comment by LRBarbieri** [comment]
> só eu achei um pouco petulante suas exigências?
> 
> já é possível (sempre foi) enviar todos os heróis a cada 30 minutos, basta ler e fazer simples alterações no config.yaml
> 
> No config.yaml você altera esta variável para o tempo que quiser....
> 
> ```
>   time_intervals:
>     # [en_US] Time interval for check if there are available heroes to work
>     # Default value (in minutes): 10
>     #
>     # [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
>     # Valor padrão (em minutos): 10
>     send_heroes_for_work: 15
> ```
> 
> e mais abaixo, no mesmo config.yaml você altera o GREEN para ALL.. ele vai enviar todos os heróis independentemente da cor da barra...
> 
> ```
>  # [en_US]
>   # Default value: green
>   # Available options:
>   # all   = select all heroes (regardless of the stamina bar)
>   # green = select the heroes with green stamina bar (half or full)
>   # full  = select only the heroes with full stamina bar
>   #
>   # [pt_BR]
>   # Valor padrão: green
>   # Opções disponíveis:
>   # all   = seleciona todos os heróis (independente da barra de stamina)
>   # green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
>   # full  = seleciona somente os heróis com a barra de stamina cheia
>   select_heroes_mode: "green"
> ```
> 
> APENAS isso.. pode editar este arquivo até mesmo no bloco de notas do windows (notepad)...

Calma cara, que petulância? Pelo jeito que ele escreve parece que ele usou google tradutor, que não fala português.

**Comment by kerferber** [comment]
> > só eu achei um pouco petulante suas exigências?
> > já é possível (sempre foi) enviar todos os heróis a cada 30 minutos, basta ler e fazer simples alterações no config.yaml
> > No config.yaml você altera esta variável para o tempo que quiser....
> > ```
> >   time_intervals:
> >     # [en_US] Time interval for check if there are available heroes to work
> >     # Default value (in minutes): 10
> >     #
> >     # [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
> >     # Valor padrão (em minutos): 10
> >     send_heroes_for_work: 15
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > e mais abaixo, no mesmo config.yaml você altera o GREEN para ALL.. ele vai enviar todos os heróis independentemente da cor da barra...
> > ```
> >  # [en_US]
> >   # Default value: green
> >   # Available options:
> >   # all   = select all heroes (regardless of the stamina bar)
> >   # green = select the heroes with green stamina bar (half or full)
> >   # full  = select only the heroes with full stamina bar
> >   #
> >   # [pt_BR]
> >   # Valor padrão: green
> >   # Opções disponíveis:
> >   # all   = seleciona todos os heróis (independente da barra de stamina)
> >   # green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
> >   # full  = seleciona somente os heróis com a barra de stamina cheia
> >   select_heroes_mode: "green"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > APENAS isso.. pode editar este arquivo até mesmo no bloco de notas do windows (notepad)...
> 
> Calma cara, que petulância? Pelo jeito que ele escreve parece que ele usou google tradutor, que não fala português.

Sim. Percebi. Tô calmo, tanto q tentei ajudar... vai ver eu estou exagerando mesmo... 

Valeuu.. peace

**Comment by dilneiss** [comment]
opa, lancei uma atualização para a nova interface do dia 05/01/2022, essa versão vai clicar no botão all pra mandar todos trabalharem, funciona com infinita janelas. somente windows, linux não funciona, fique a vontade pra usar se quiser: https://github.com/dilneiss/bombcrypto-bot-1

**Comment by JONASUK0** [comment]
muito obrigado a todos

**Comment by cesarmdev** [comment]
> 

otimo, muito obrigado!
uma duvida, as janelas precisam estar em full screen ou lado a lado ?

**Comment by cesarmdev** [comment]
> opa, lancei uma atualização para a nova interface do dia 05/01/2022, essa versão vai clicar no botão all pra mandar todos trabalharem, funciona com infinita janelas. somente windows, linux não funciona, fique a vontade pra usar se quiser: https://github.com/dilneiss/bombcrypto-bot-1

otimo, muito obrigado!
uma duvida, as janelas precisam estar em full screen ou lado a lado ?

**Comment by dilneiconectala** [comment]
> > opa, lancei uma atualização para a nova interface do dia 05/01/2022, essa versão vai clicar no botão all pra mandar todos trabalharem, funciona com infinita janelas. somente windows, linux não funciona, fique a vontade pra usar se quiser: https://github.com/dilneiss/bombcrypto-bot-1
> 
> otimo, muito obrigado! uma duvida, as janelas precisam estar em full screen ou lado a lado ?

só deixar elas abertas normal, o bot vai alternar de janelas e fazer o processo em cada uma.
obs. é necessário abrir o game pelo link: https://app.bombcrypto.io/webgl/index.html

**Comment by cesarmdev** [comment]
> > > opa, lancei uma atualização para a nova interface do dia 05/01/2022, essa versão vai clicar no botão all pra mandar todos trabalharem, funciona com infinita janelas. somente windows, linux não funciona, fique a vontade pra usar se quiser: https://github.com/dilneiss/bombcrypto-bot-1
> > 
> > 
> > otimo, muito obrigado! uma duvida, as janelas precisam estar em full screen ou lado a lado ?
> 
> só deixar elas abertas normal, o bot vai alternar de janelas e fazer o processo em cada uma. obs. é necessário abrir o game pelo link: https://app.bombcrypto.io/webgl/index.html

entendi, muito obrigado pela ajuda!

**Comment by harinhlb** [comment]
> opa, lancei uma atualização para a nova interface do dia 05/01/2022, essa versão vai clicar no botão all pra mandar todos trabalharem, funciona com infinita janelas. somente windows, linux não funciona, fique a vontade pra usar se quiser: https://github.com/dilneiss/bombcrypto-bot-1

Opa,  se eu deixar em "all" a cada 30min, se eu usar com 6 contas,  vai dar certo ou as outras contas vão cair por ausencia de 10min? 

Abc

**Comment by kerferber** [comment]
> opa, lancei uma atualização para a nova interface do dia 05/01/2022, essa versão vai clicar no botão all pra mandar todos trabalharem, funciona com infinita janelas. somente windows, linux não funciona, fique a vontade pra usar se quiser: https://github.com/dilneiss/bombcrypto-bot-1

sabe me dizer pq não funciona em linux? Alguma forma de tentar implementar?
