### ISSUE TITLE
bot errando o click no botao work

### ISSUE THREAD

**Issue by kaduzin1** [mpcabete/bombcrypto-bot#567]
meu bot quando vai clicar no work ele erra o lugar por pouco, o que eu faço? ja tentei mudar a imagem/resolução não vai

**Comment by dilneiss** [comment]
opa, lancei uma atualização para a nova interface do dia 05/01/2022, essa versão vai clicar no botão all pra mandar todos trabalharem, funciona com infinita janelas. somente windows, linux não funciona, fique a vontade pra usar se quiser: https://github.com/dilneiss/bombcrypto-bot-1

**Comment by cleitonleonel** [comment]
> opa, lancei uma atualização para a nova interface do dia 05/01/2022, essa versão vai clicar no botão all pra mandar todos trabalharem, funciona com infinita janelas. somente windows, linux não funciona, fique a vontade pra usar se quiser: https://github.com/dilneiss/bombcrypto-bot-1

Fiz essa versão que funciona com multijanelas (windows, linux) e "all_go_work_button" ... https://github.com/cleitonleonel/bombcrypto-bot.git
