### ISSUE TITLE
Bot so coloca pra trabalhar os 5 primeiros

### ISSUE THREAD

**Issue by brandaogabriel** [mpcabete/bombcrypto-bot#568]
Galera, depois dessa atualização do dia 05/01, o meu bot so está colocando os 5 primeiros pra trabalhar, alguem teve esse problema e sabe como resolver?

**Comment by fguide** [comment]
Talvez ajude o #560

**Comment by brandaogabriel** [comment]
@fguide é referente a atualização de ontem, acredito que depois que adicionaram os botoes "all", pode ter bugado..

**Comment by fguide** [comment]
Eu acredito que não tenha a ver amigo, até onde sei continua funcionando normal (vários relatos aqui nos issues), talvez tenha dado um bug relacionado ao PR que enviei pra você.

Ou tenha mudado algo nos botoes aí, idioma do jogo, etc

**Comment by brandaogabriel** [comment]
Entendi, vou tentar pelo do pr e qualquer coisa eu falo

**Comment by fguide** [comment]
Beleza, tente ver se esta detectando os botoes e barras certinho, se nao estiver é ai o problema

**Comment by rootfast** [comment]
atualiza as imgs mano que resolve

**Comment by brandaogabriel** [comment]
@rnesheiksilvestre, vc tem elas ai?

**Comment by maxuelgamer** [comment]
Realizei algumas alterações para clicar direto no all-btn ao invés de mandar hero por hero.

Vou enviar o index aqui pra quem quiser.

Basta trocar a extensão de TXT para PY.

[index.txt](https://github.com/mpcabete/bombcrypto-bot/files/7823920/index.txt)

**Comment by brandaogabriel** [comment]
@maxuelgamer nao precisa da imagem dos botoes nao?

**Comment by Hermanyo** [comment]
Replace work.png to the new button with text "All" then set scroll attemps to 0

**Comment by maxuelgamer** [comment]
> @maxuelgamer nao precisa da imagem dos botoes nao?

sim, esqueci de mencionar, cria uma imagem com o nome de all-btn.png
