### ISSUE TITLE
bot nao esta reconhecendo os botoes

### ISSUE THREAD

**Issue by Deivd16** [mpcabete/bombcrypto-bot#570]
o bot nao está reconhecendo os botoes de work, ele fica num loop infinito de scroll e work, nunca saindo da aba de herois e pausando o farm até que eu o faça manualmente, aguardo ansiosamente por uma nova att de acordo com a nova interface do bomb :)

**Comment by HeeyMan** [comment]
Mesma coisa aqui, já realizei a troca das imagens e ate coloquei os codigos que mandaram em outras issues mas nada resolve

**Comment by maxuelgamer** [comment]
Realizei algumas alterações para clicar direto no all-btn ao invés de mandar hero por hero.

Vou enviar o index aqui pra quem quiser.

Basta trocar a extensão de TXT para PY.

[index.txt](https://github.com/mpcabete/bombcrypto-bot/files/7823920/index.txt)

**Comment by Vitaonx** [comment]
> Realizei algumas alterações para clicar direto no all-btn ao invés de mandar hero por hero.
> 
> Vou enviar o index aqui pra quem quiser.
> 
> Basta trocar a extensão de TXT para PY.
> 
> [index.txt](https://github.com/mpcabete/bombcrypto-bot/files/7823920/index.txt)

Alguém que entende pode checar aqui pra nois kkkkk

**Comment by fguide** [comment]
A alteração está segura, só desabilita o scroll e clica em "Work all", podem usar.

Agora quanto ao loop infinito, tem o motivo em #500

**Comment by Raoniq** [comment]
Aqui o scroll está tranquilo. Quanto ao "work all" eu não achei tão interessante, principalmente se o mapa estiver quase vazio de baús e cheio de pedras, pois irá mandar os SR+ também. De madrugada até rola mas enquanto estamos disponíveis pra traçar uma estratégia no mapa creio que o work green seja melhor.
