### ISSUE TITLE
Connect wallet em português

### ISSUE THREAD

**Issue by Fpereirinha** [mpcabete/bombcrypto-bot#572]
o processo para se conectar está funcionando para mim em português, houve  alguma atualização ?
ou caso funcionou por acaso, melhor trocar para ingles ?

**Comment by ByPivete** [comment]
eu estou usando em inglês mesmo...

**Comment by LRBarbieri** [comment]
> o processo para se conectar está funcionando para mim em português, houve alguma atualização ? ou caso funcionou por acaso, melhor trocar para ingles ?

Tenho um bom conselho para te dar, se o bagulho tá funcionando não mexe kkkkkkk

**Comment by cleitonleonel** [comment]
> o processo para se conectar está funcionando para mim em português, houve alguma atualização ? ou caso funcionou por acaso, melhor trocar para ingles ?

muita gente aqui tá com erro e não sabe que pode ser pelo fato de estar usando PT-BR  e as imagens do jogo estarem em português, enquanto que as imagens do projeto são todas EN ...
