### ISSUE TITLE
House dont works :(

### ISSUE THREAD

**Issue by leinadany** [mpcabete/bombcrypto-bot#574]
Hi, i got the bot up and running and everything is great, I put it on a VPS. The only problem I have is that he doesn't send the heroes to the home.

I took a screenshot of each hero and put it in a folder, then put "True" in the configurator. I'm missing something? Thanks

https://i.ibb.co/WsJqnk4/carpet.jpg
https://i.ibb.co/fqSzzct/carpet2.jpg
https://i.ibb.co/pvPSmHv/carpet3.jpg

Its all ok? any error? thanks...

**Comment by fguide** [comment]
Try changing your heroes screenshot to something like this:

![image](https://user-images.githubusercontent.com/95459411/148462154-021277c3-f0d8-4f5b-b282-cbf4c2fb158e.png)

If you put the whole bar it'll be different each time so you may want to have it a bit more generic to avoid detection errors.

**Comment by leinadany** [comment]
Ok i will try this, thanks friend.

**Comment by galerito322** [comment]
@fguide Here the heroes are sent home normally, but they cannot return to work if they are in the house. Can you help me ?
