### ISSUE TITLE
Idéia e ajuda dos desenvolvedores do bot. (também dúvida minha, pois não sei se estou correto)

### ISSUE THREAD

**Issue by pegchargue** [mpcabete/bombcrypto-bot#576]
No Bot se não me engano a cada três minutos ele vai na seta verde para voltar e depois volta para o mapa, (para que os heróis não fiquem presos) mas não sei se é correto isso (se tiverem 10 bombas no mapa e não estourarem antes dessa volta elas não funcionam como dano nos baús... mas tira mana dos heróis que a soltaram...) isso é correto??
Se formos contabilizar isso em um dia de trabalho acredito que isso faz desperdiçar muitas bombas... Pois juntando isso as idas para buscar heróis disponíveis para trabalhar então o desperdiço é maior ainda...
Tem um botão flutuante na parte inferior do mapa para selecionar os heróis, correto???
Se fosse utilizado aquele botão não diminuiria esse desperdiço???
E se junto fosse aumentado o tempo de volta para uns 5 ou 8 minutos também não ajudaria???
Eu já tentei efetuar a alteração de tempo, mas parece que quando faço o bot para de funcionar 100%
Se eu estiver falando besteira me desculpem.

**Comment by pegchargue** [comment]
@mpcabete, dê um confere aí...

**Comment by luismello** [comment]
O refresh eu removi do Index, mas essa do botão flutuante até pensei em mudar as imagens mas ainda não testei.

**Comment by ghost** [comment]
A intenção de voltar pro menu e ir pro mapa é pra resetar a posição dos heróis quando começam a andar tudo junto, atualizar o mapa evita isso. Os heróis só gastam mana quando a bomba explode, você mesmo pode fazer o teste com um boneco, deixar ele colocar a bomba e voltar pra verificar se ele gastou de fato mana.

**Comment by theduzzy** [comment]
A mana só contabiliza após a explosão da bomba, e caso o personagem que a soltou não estiver em work, não contabiliza nem o dano no baú e nem a mana.

**Comment by pegchargue** [comment]
Valeu pelas respostas e desculpa pelo questionamento inútil...rsrsr eu tinha prestado atenção somente nas barras de energia dos heróis e do baú (no mapa), não tinha me atentado em ver lá na casa deles... Valeu e obrigado pelas informações!!!

**Comment by kelvinkrisna** [comment]
O unico momento que contabiliza antes da explosão é quando o Heroi tem só 1 de mana. Que ele coloca a bomba e já dorme.
