### ISSUE TITLE
Bot não inicia [ModuleNotFoundError: No module named 'yaml']

### ISSUE THREAD

**Issue by alefbz** [mpcabete/bombcrypto-bot#578]
Alguém teve esse problema?

C:\Users\alefg\Documents\bombcrypto-bot-main>python3 index.py
Traceback (most recent call last):
  File "C:\Users\alefg\Documents\bombcrypto-bot-main\index.py", line 2, in <module>
    from src.logger import logger, loggerMapClicked
  File "C:\Users\alefg\Documents\bombcrypto-bot-main\src\logger.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

Já removi e reinstalei o python e ainda não funcionou.

**Comment by cleitonleonel** [comment]
#556

**Comment by cleitonleonel** [comment]
> Alguém teve esse problema?
> 
> C:\Users\alefg\Documents\bombcrypto-bot-main>python3 index.py Traceback (most recent call last): File "C:\Users\alefg\Documents\bombcrypto-bot-main\index.py", line 2, in from src.logger import logger, loggerMapClicked File "C:\Users\alefg\Documents\bombcrypto-bot-main\src\logger.py", line 4, in import yaml ModuleNotFoundError: No module named 'yaml'
> 
> Já removi e reinstalei o python e ainda não funcionou.

#556

**Comment by alefbz** [comment]
Usei o comando ‘ python index.py’ e iniciou o bot, porém não reconhece os bonecos e nem os botões da tela.

alguém sabe o que pode ser?
