### ISSUE TITLE
bot não funciona em multi acc

### ISSUE THREAD

**Issue by aanyris** [mpcabete/bombcrypto-bot#579]
O Google teve uma atualização que removeu o occlusion, o bot só reconhece uma conta, ele não alterna entre as duas mesmo ambas sendo do Chrome. Alguém encontrou alguma solução? 
Aliás, ele não tá funcionando em dois monitores também :(

**Comment by mGranTY** [comment]
Solução do primeiro problema: https://github.com/mpcabete/bombcrypto-bot/issues/463#issuecomment-1006136917

Problema 2: O bot só reconhece uma conta sua? primeiro verifique se esta logado pelo link direto: https://app.bombcrypto.io/webgl/index.html

sem ver diretamente o que esta acontecendo não tem muito o que eu te falar pra fazer, me chama discord GranTY#8475

Solução do terceiro problema: https://github.com/mpcabete/bombcrypto-bot/issues/537
