### ISSUE TITLE
Deploy hero evey 1 hour

### ISSUE THREAD

**Issue by johndavemanuel** [mpcabete/bombcrypto-bot#581]
What do I need to chnage in the index.py to make it deploy hero every 1 hour not 15 minutes

**Comment by Raoniq** [comment]
Change the value from 10 to 60 in config.yaml:

  _time_intervals:
    # [en_US] Time interval for check if there are available heroes to work
    # Default value (in minutes): 10
    #
    # [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
    # Valor padrão (em minutos): 10
    send_heroes_for_work:_ **60**

**Comment by Hikarusomai** [comment]
Hi @Johndavemanuel, does it works better with 1 hour ?

**Comment by johndavemanuel** [comment]
Hey! depending on your character's stamina and if it has a battery ability.

**Comment by johndavemanuel** [comment]
@downloadkct nice thanks.
