### ISSUE TITLE
ModuleNotFoundError: No module named 'src.logger'

### ISSUE THREAD

**Issue by virginonline** [mpcabete/bombcrypto-bot#582]
ModuleNotFoundError: No module named 'src.logger'

**Comment by MathCarv** [comment]
Conseguiu resolver ? Estou com mesmo erro. 
Traceback (most recent call last):
  File "/bombcrypto-bot/index.py", line 2, in <module>
    from src.logger import logger, loggerMapClicked
ModuleNotFoundError: No module named 'src.logger'
