### ISSUE TITLE
Python: Executar função uma vez por dia, em determinado horário...?

### ISSUE THREAD

**Issue by kerferber** [mpcabete/bombcrypto-bot#584]
Bom dia pessoal,

Gostaria de implementar uma função que gravasse um log uma vez ao dia, sempre no mesmo horário, com o número de Bcoins, para acompanhar a evolução do Farm.

Estou treinando o OCR pra reconhecer os caracteres, pois muitas vezes ele está confundindo o Zero com o Oito na hora das leituras, mas gostaria de saber se alguém recomenda uma forma de executar determinada função uma vez ao dia em um horário determinado?

Alguém já fez algo parecido ou tem algum norte?
Desde já agradeço

OBS: Sim, não é um issue, desculpem

**Comment by cleitonleonel** [comment]
> Bom dia pessoal,
> 
> Gostaria de implementar uma função que gravasse um log uma vez ao dia, sempre no mesmo horário, com o número de Bcoins, para acompanhar a evolução do Farm.
> 
> Estou treinando o OCR pra reconhecer os caracteres, pois muitas vezes ele está confundindo o Zero com o Oito na hora das leituras, mas gostaria de saber se alguém recomenda uma forma de executar determinada função uma vez ao dia em um horário determinado?
> 
> Alguém já fez algo parecido ou tem algum norte? Desde já agradeço
> 
> OBS: Sim, não é um issue, desculpem

No Linux use crontab no Windows use o agendador de tarefas...

**Comment by kerferber** [comment]
> > Bom dia pessoal,
> > Gostaria de implementar uma função que gravasse um log uma vez ao dia, sempre no mesmo horário, com o número de Bcoins, para acompanhar a evolução do Farm.
> > Estou treinando o OCR pra reconhecer os caracteres, pois muitas vezes ele está confundindo o Zero com o Oito na hora das leituras, mas gostaria de saber se alguém recomenda uma forma de executar determinada função uma vez ao dia em um horário determinado?
> > Alguém já fez algo parecido ou tem algum norte? Desde já agradeço
> > OBS: Sim, não é um issue, desculpem
> 
> No Linux use crontab no Windows use o agendador de tarefas...

Obrigado mas preciso fazer isso dentro do próprio bot, sem utilizar outro script. Acho que com o crontab não daria, né?

**Comment by cleitonleonel** [comment]
> > > Bom dia pessoal,
> > > Gostaria de implementar uma função que gravasse um log uma vez ao dia, sempre no mesmo horário, com o número de Bcoins, para acompanhar a evolução do Farm.
> > > Estou treinando o OCR pra reconhecer os caracteres, pois muitas vezes ele está confundindo o Zero com o Oito na hora das leituras, mas gostaria de saber se alguém recomenda uma forma de executar determinada função uma vez ao dia em um horário determinado?
> > > Alguém já fez algo parecido ou tem algum norte? Desde já agradeço
> > > OBS: Sim, não é um issue, desculpem
> > 
> > 
> > No Linux use crontab no Windows use o agendador de tarefas...
> 
> Obrigado mas preciso fazer isso dentro do próprio bot, sem utilizar outro script. Acho que com o crontab não daria, né?

vc vai deixar o bot rodando o dia todo??? se sim basta especificar um determinado harário e checar com datetime uma vez por dia gerando esse relatório, agora se o bot não vai estar em execução 24 horas por dia creio que somente usando apps externos.

**Comment by fguide** [comment]
Sugestao acima ^, ou, faz via cron/task sch um script para parar (kill) o bot, checar saldo e fazer o que precisa, e depois iniciar o bot novamente.

**Comment by kerferber** [comment]
@fguide e @cleitonleonel 

MUUUITO obrigado.

Realmente, é só fazer uma função que compare as datas, pois sim, meu bot roda 24 horas por dia.
Mais fácil que pensei, novamente obrigado!!! Bom final de semana à todos nós
