### ISSUE TITLE
"human like" mouse movements

### ISSUE THREAD

**Issue by xclover0** [mpcabete/bombcrypto-bot#585]
is it possible to implement bezier curves or "human like" movements when the bot is moving our mouse/cursor?

python library:
https://github.com/patrikoss/pyclick

example:
https://stackoverflow.com/questions/44467329/pyautogui-mouse-movement-with-bezier-curve

I think this one will make our bot harder from their detection. thanks

**Comment by fguide** [comment]
This has been discussed already but I believe it won't be implemented any soon as the game is not forbidding bots/autoclicks anymore.

**Comment by cleitonleonel** [comment]
https://user-images.githubusercontent.com/11451914/148665236-d111d244-fe90-4301-b4d7-52dbaea6c261.mp4

**Comment by cleitonleonel** [comment]
https://user-images.githubusercontent.com/11451914/148666188-de3ff5c7-a16a-4fcf-9d17-8cc27b9cdcc7.mp4

**Comment by xclover0** [comment]
> This has been discussed already but I believe it won't be implemented any soon as the game is not forbidding bots/autoclicks anymore.

I think they will ban again the bot/macros users as I saw a moderator announced on our discord channel on the previous day. you may look at this screenshot of the announcement: https://imgur.com/a/1xU3Myr

**Comment by xclover0** [comment]
> Peek.08-01-2022.22-51.mp4

you're doing a good job mate. care to make a pull request when you finished the code/script?

**Comment by fguide** [comment]
> > This has been discussed already but I believe it won't be implemented any soon as the game is not forbidding bots/autoclicks anymore.
> 
> I think they will ban again the bot/macros users as I saw a moderator announced on our discord channel on the previous day. you may look at this screenshot of the announcement: https://imgur.com/a/1xU3Myr

It's convenient for them to tell this as they are releasing VIP Staking services which will include "autoclick" functions..

That said, if you really have evidence they can really "track" your movements, than this should be a concern. Just an advice, try to use some not so well-known solution (such as pyclick) as this would probably make their identification easier. Best scenario would be matching this with some other randomizer script.

**Comment by cleitonleonel** [comment]
> > Peek.08-01-2022.22-51.mp4
> 
> você está fazendo um bom trabalho, companheiro. se importa em fazer uma solicitação de pull quando terminar o código / script?

Of course, as soon as I get it resolved here with this implementation, I will do a pull request, no problems...

**Comment by cleitonleonel** [comment]
> > Peek.08-01-2022.22-51.mp4
> 
> you're doing a good job mate. care to make a pull request when you finished the code/script?

Of course, as soon as I get it resolved here with this implementation, I will do a pull request, no problems...
