### ISSUE TITLE
Minha versão do bot - zoom\work all\mac\multi-account

### ISSUE THREAD

**Issue by MatheusHAS** [mpcabete/bombcrypto-bot#587]
Fala pessoal, eu fiz um fork desse repositório, para fazer uns ajustes e acabei nem mandando ao pull request, pois alterei toda estrutura de arquivos.

O Bot em si contém toda a mesma lógica do @mpcabete !
Algumas coisas que adicionei na minha versão do bot, e que não foram 100% testadas.

- **Usar multiplas contas no mesmo monitor**
Peguei a mesma idéia sugerida na thread #431 sobre mult browser, e segui na minha linha de raciocinio para conseguir usar 1 conta ao lado da outra dessa forma:
![image](https://user-images.githubusercontent.com/7914887/148659094-606db816-2565-4768-a981-f1dd2f1f3501.png)

No `config.yaml` existe a configuração `multiples_accounts_same_monitor` onde é possível habilitar ou também trocar o texto que ele usa para identificar as janelas do navegador com o jogo caso necessário.

- PS: no meu monitor normal, só consigo usar 2 contas usando o zoom 100%, mas se seu monitor cabe mais ou caso você altere o zoom do browser. Não é necessário deixar as janelas lado a lado, se você só tiver todas janelas maximizadas, deveria funcionar da mesma forma.

- PS [2]: Note que eu estou usando para abrir o jogo na url direta do iframe do game, para que não execute apenas o necessário.

- PS [3]: Se você criar um atalho para executar o bot, e esse atalho tiver o nome `bombcrypto` no titulo, ele vai bugar, pois é esse texto que ele usa para identificar as janelas do jogo. Eu carinhosamente chamo meu atalho para executar o bot de `bombCREPTO`.

<hr/>

- **Usar zoom diferente no browser**
Adicionei no `config.yaml` as configurações do `scale_image` onde é possível alterar a escala quando está usando um zoom diferente, porém lembre-se, isso também afeta a janela de notificação de login para a metamask, também é necessário mudar nela para garantir o funcionamento correto para login também.

<hr/>

- **MAC com tela retina**
Durante tests em um mac do meu irmão, foi identificado a necessidade de um tratamento diferente para executar a movimentação do mouse, devido ao tamanho da resolução das telas retina. Existe uma opção no `config.yaml` chamada `is_retina_screen`, basta você trocar para `True`.

<hr/>

- **Velocidade dos movimentos do mouse**
O mouse antes tinha uma velocidade X para todas ações de movimentação, agora é possível alterar isso trocando o valor no `config.yaml` do campo `mouse_move_speed` e colocar um valor de 0.1 (mais rapido) até 1 (mais lento). 

<hr/>

- Mandar todos bonecos pra trabalhar (work all)
Fiz a implementação também para quando no `config.yaml` a config `select_heroes_mode` está com valor `all` e o `home` (casa) está desabilitado, para usa esse botão para mandar trabalhar.

<hr/>

O código está disponível em:
https://github.com/MatheusHAS/bombcrypto-bot

Para executar o bot, você pode rodar o arquivo `run.bat` na pasta principal do bot.

é isso ai que tinha, qum quiser testar, sinta-se a vontade.

Falou!

**Comment by kerferber** [comment]
Não vou testar pois não tenho 2 contas e nem Mac kkkkk

Mas parabéns pela iniciativa e por disponibilizar aos demais!!!

**Comment by LRBarbieri** [comment]
> Fala pessoal, eu fiz um fork desse repositório, para fazer uns ajustes e acabei nem mandando ao pull request, pois alterei toda estrutura de arquivos.
> 
> O Bot em si contém toda a mesma lógica do @mpcabete ! Algumas coisas que adicionei na minha versão do bot, e que não foram 100% testadas.
> 
> * **Usar multiplas contas no mesmo monitor**
>   Peguei a mesma idéia sugerida na thread [Multi browser #431](https://github.com/mpcabete/bombcrypto-bot/issues/431) sobre mult browser, e segui na minha linha de raciocinio para conseguir usar 1 conta ao lado da outra dessa forma:
>   ![image](https://user-images.githubusercontent.com/7914887/148659094-606db816-2565-4768-a981-f1dd2f1f3501.png)
> 
> No `config.yaml` existe a configuração `multiples_accounts_same_monitor` onde é possível habilitar ou também trocar o texto que ele usa para identificar as janelas do navegador com o jogo caso necessário.
> 
> * PS: no meu monitor normal, só consigo usar 2 contas usando o zoom 100%, mas se seu monitor cabe mais ou caso você altere o zoom do browser. Não é necessário deixar as janelas lado a lado, se você só tiver todas janelas maximizadas, deveria funcionar da mesma forma.
> * PS [2]: Note que eu estou usando para abrir o jogo na url direta do iframe do game, para que não execute apenas o necessário.
> * PS [3]: Se você criar um atalho para executar o bot, e esse atalho tiver o nome `bombcrypto` no titulo, ele vai bugar, pois é esse texto que ele usa para identificar as janelas do jogo. Eu carinhosamente chamo meu atalho para executar o bot de `bombCREPTO`.
> 
> * **Usar zoom diferente no browser**
>   Adicionei no `config.yaml` as configurações do `scale_image` onde é possível alterar a escala quando está usando um zoom diferente, porém lembre-se, isso também afeta a janela de notificação de login para a metamask, também é necessário mudar nela para garantir o funcionamento correto para login também.
> 
> * **MAC com tela retina**
>   Durante tests em um mac do meu irmão, foi identificado a necessidade de um tratamento diferente para executar a movimentação do mouse, devido ao tamanho da resolução das telas retina. Existe uma opção no `config.yaml` chamada `is_retina_screen`, basta você trocar para `True`.
> 
> * **Velocidade dos movimentos do mouse**
>   O mouse antes tinha uma velocidade X para todas ações de movimentação, agora é possível alterar isso trocando o valor no `config.yaml` do campo `mouse_move_speed` e colocar um valor de 0.1 (mais rapido) até 1 (mais lento).
> 
> * Mandar todos bonecos pra trabalhar (work all)
>   Fiz a implementação também para quando no `config.yaml` a config `select_heroes_mode` está com valor `all` e o `home` (casa) está desabilitado, para usa esse botão para mandar trabalhar.
> 
> O código está disponível em: https://github.com/MatheusHAS/bombcrypto-bot
> 
> Para executar o bot, você pode rodar o arquivo `run.bat` na pasta principal do bot.
> 
> é isso ai que tinha, qum quiser testar, sinta-se a vontade.
> 
> Falou!

Boa noite, você tem algum meio de contato? Tentei usar mas o bot não faz nada

**Comment by zSinnK** [comment]
Opa tranquilo? então, testei o bot porém ele só trabalha em uma conta ( da esquerda ) e não interage com a outra
organizei a tela dessa maneira:

![Captura de tela 2022-01-08 212148](https://user-images.githubusercontent.com/95734505/148664435-7a38d38e-efad-451f-b83e-69c10ba62737.png)

**Comment by MatheusHAS** [comment]
> Opa tranquilo? então, testei o bot porém ele só trabalha em uma conta ( da esquerda ) e não interage com a outra
> organizei a tela dessa maneira:
> 
> ![Captura de tela 2022-01-08 212148](https://user-images.githubusercontent.com/95734505/148664435-7a38d38e-efad-451f-b83e-69c10ba62737.png)
> 
> 

E aí mano, tudo bão? 

Cara, você ativou a opção no config.yaml?

**Comment by zSinnK** [comment]
> > Opa tranquilo? então, testei o bot porém ele só trabalha em uma conta ( da esquerda ) e não interage com a outra
> > organizei a tela dessa maneira:
> > ![Captura de tela 2022-01-08 212148](https://user-images.githubusercontent.com/95734505/148664435-7a38d38e-efad-451f-b83e-69c10ba62737.png)
> 
> E aí mano, tudo bão?
> 
> Cara, você ativou a opção no config.yaml?

Era isso mesmo, não tinha reparado foi mal
Funcionou perfeitamente depois de ativar a opção, parabéns pelo trabalho irmão!

**Comment by 8driano** [comment]
> Fala pessoal, eu fiz um fork desse repositório, para fazer uns ajustes e acabei nem mandando ao pull request, pois alterei toda estrutura de arquivos.
> 
> O Bot em si contém toda a mesma lógica do @mpcabete ! Algumas coisas que adicionei na minha versão do bot, e que não foram 100% testadas.
> 
> * **Usar multiplas contas no mesmo monitor**
>   Peguei a mesma idéia sugerida na thread [Multi browser #431](https://github.com/mpcabete/bombcrypto-bot/issues/431) sobre mult browser, e segui na minha linha de raciocinio para conseguir usar 1 conta ao lado da outra dessa forma:
>   ![image](https://user-images.githubusercontent.com/7914887/148659094-606db816-2565-4768-a981-f1dd2f1f3501.png)
> 
> No `config.yaml` existe a configuração `multiples_accounts_same_monitor` onde é possível habilitar ou também trocar o texto que ele usa para identificar as janelas do navegador com o jogo caso necessário.
> 
> * PS: no meu monitor normal, só consigo usar 2 contas usando o zoom 100%, mas se seu monitor cabe mais ou caso você altere o zoom do browser. Não é necessário deixar as janelas lado a lado, se você só tiver todas janelas maximizadas, deveria funcionar da mesma forma.
> * PS [2]: Note que eu estou usando para abrir o jogo na url direta do iframe do game, para que não execute apenas o necessário.
> * PS [3]: Se você criar um atalho para executar o bot, e esse atalho tiver o nome `bombcrypto` no titulo, ele vai bugar, pois é esse texto que ele usa para identificar as janelas do jogo. Eu carinhosamente chamo meu atalho para executar o bot de `bombCREPTO`.
> 
> * **Usar zoom diferente no browser**
>   Adicionei no `config.yaml` as configurações do `scale_image` onde é possível alterar a escala quando está usando um zoom diferente, porém lembre-se, isso também afeta a janela de notificação de login para a metamask, também é necessário mudar nela para garantir o funcionamento correto para login também.
> 
> * **MAC com tela retina**
>   Durante tests em um mac do meu irmão, foi identificado a necessidade de um tratamento diferente para executar a movimentação do mouse, devido ao tamanho da resolução das telas retina. Existe uma opção no `config.yaml` chamada `is_retina_screen`, basta você trocar para `True`.
> 
> * **Velocidade dos movimentos do mouse**
>   O mouse antes tinha uma velocidade X para todas ações de movimentação, agora é possível alterar isso trocando o valor no `config.yaml` do campo `mouse_move_speed` e colocar um valor de 0.1 (mais rapido) até 1 (mais lento).
> 
> * Mandar todos bonecos pra trabalhar (work all)
>   Fiz a implementação também para quando no `config.yaml` a config `select_heroes_mode` está com valor `all` e o `home` (casa) está desabilitado, para usa esse botão para mandar trabalhar.
> 
> O código está disponível em: https://github.com/MatheusHAS/bombcrypto-bot
> 
> Para executar o bot, você pode rodar o arquivo `run.bat` na pasta principal do bot.
> 
> é isso ai que tinha, qum quiser testar, sinta-se a vontade.
> 
> Falou!
Estou tentando usar o multi dessa maneira, tem como? Pois o meu não esta conseguindo logar na metamask dessa forma
![image](https://user-images.githubusercontent.com/85385771/148665484-b003f2db-586a-4c1b-985b-c04d7f3f1448.png)

**Comment by santosrennan** [comment]
Funciona bem em linux?

**Comment by zSinnK** [comment]
![Screenshot_2022-01-09-03-30-20-855_com google chromeremotedesktop](https://user-images.githubusercontent.com/95734505/148671916-acbbcfca-d704-4fdf-9bd1-7f7ea2f5fdf7.jpg)

Tô tendo esse probleminha aqui dps de um tempinho usando

**Comment by danylocp** [comment]
> Fala pessoal, eu fiz um fork desse repositório, para fazer uns ajustes e acabei nem mandando ao pull request, pois alterei toda estrutura de arquivos.
> 
> O Bot em si contém toda a mesma lógica do @mpcabete ! Algumas coisas que adicionei na minha versão do bot, e que não foram 100% testadas.
> 
> * **Usar multiplas contas no mesmo monitor**
>   Peguei a mesma idéia sugerida na thread [Multi browser #431](https://github.com/mpcabete/bombcrypto-bot/issues/431) sobre mult browser, e segui na minha linha de raciocinio para conseguir usar 1 conta ao lado da outra dessa forma:
>   ![image](https://user-images.githubusercontent.com/7914887/148659094-606db816-2565-4768-a981-f1dd2f1f3501.png)
> 
> No `config.yaml` existe a configuração `multiples_accounts_same_monitor` onde é possível habilitar ou também trocar o texto que ele usa para identificar as janelas do navegador com o jogo caso necessário.
> 
> * PS: no meu monitor normal, só consigo usar 2 contas usando o zoom 100%, mas se seu monitor cabe mais ou caso você altere o zoom do browser. Não é necessário deixar as janelas lado a lado, se você só tiver todas janelas maximizadas, deveria funcionar da mesma forma.
> * PS [2]: Note que eu estou usando para abrir o jogo na url direta do iframe do game, para que não execute apenas o necessário.
> * PS [3]: Se você criar um atalho para executar o bot, e esse atalho tiver o nome `bombcrypto` no titulo, ele vai bugar, pois é esse texto que ele usa para identificar as janelas do jogo. Eu carinhosamente chamo meu atalho para executar o bot de `bombCREPTO`.
> 
> * **Usar zoom diferente no browser**
>   Adicionei no `config.yaml` as configurações do `scale_image` onde é possível alterar a escala quando está usando um zoom diferente, porém lembre-se, isso também afeta a janela de notificação de login para a metamask, também é necessário mudar nela para garantir o funcionamento correto para login também.
> 
> * **MAC com tela retina**
>   Durante tests em um mac do meu irmão, foi identificado a necessidade de um tratamento diferente para executar a movimentação do mouse, devido ao tamanho da resolução das telas retina. Existe uma opção no `config.yaml` chamada `is_retina_screen`, basta você trocar para `True`.
> 
> * **Velocidade dos movimentos do mouse**
>   O mouse antes tinha uma velocidade X para todas ações de movimentação, agora é possível alterar isso trocando o valor no `config.yaml` do campo `mouse_move_speed` e colocar um valor de 0.1 (mais rapido) até 1 (mais lento).
> 
> * Mandar todos bonecos pra trabalhar (work all)
>   Fiz a implementação também para quando no `config.yaml` a config `select_heroes_mode` está com valor `all` e o `home` (casa) está desabilitado, para usa esse botão para mandar trabalhar.
> 
> O código está disponível em: https://github.com/MatheusHAS/bombcrypto-bot
> 
> Para executar o bot, você pode rodar o arquivo `run.bat` na pasta principal do bot.
> 
> é isso ai que tinha, qum quiser testar, sinta-se a vontade.
> 
> Falou!

**Comment by danylocp** [comment]
Meu bom! Tem como mandar hero especifico para a casa?

**Comment by Raoniq** [comment]
Alguém que manje bem pra dar uma olhada só pra garantir se está tudo ok ? rsrs.
Nada pessoal em MatheusHAS, agradeço por compartilhar.

**Comment by zeph44** [comment]
O bot ja vem com opção de clicar mo work all ?

**Comment by MatheusHAS** [comment]
> 

Boa mano, vou dar uma olhada sobre o uso de monitor dessa forma hehe, ele chega aparecer a janela da metamask ? ele maximiza ela mas nao clica? é isso?

**Comment by MatheusHAS** [comment]
> ![Screenshot_2022-01-09-03-30-20-855_com google chromeremotedesktop](https://user-images.githubusercontent.com/95734505/148671916-acbbcfca-d704-4fdf-9bd1-7f7ea2f5fdf7.jpg)
> 
> Tô tendo esse probleminha aqui dps de um tempinho usando

Cara, da maneira como fiz o bot, ele força da janela ser ativa, antes de tirar as print screens da tela, pra poder realizar os calculos e realizar as ações, no meu tbm acontece isso quando eu vou usar o PC, enquanto o bot está rodando

**Comment by MatheusHAS** [comment]
> O bot ja vem com opção de clicar no work all ?

Quando você coloca o `select_heroes_mode` com valor `all` no arquivo `config.yaml` e e você não tem `house` habilitada, ele tenta utilizar o botão de work all, se ele nao conseguir, ele vai sair clicando normal como o bot já fazia

**Comment by MatheusHAS** [comment]
> Meu bom! Tem como mandar hero especifico para a casa?

Cara, tem sim, mas atualmente não está 100% funcional, ele basicamente "envia quando quer" pra casinha kkk, mas funciona da mesma maneira como o bot já funcionava, você já chegou a utilizar esse recurso do bot?

**Comment by MatheusHAS** [comment]
> Funciona bem em linux?

Rapaz, se me fez uma boa pergunta, mas eu ja tava pensando em coLocar uma maquina com linux pra rodar, vou fazer o teste hehe

**Comment by olivete** [comment]
opa! primeiramente, obrigado por fazer esse codigo extra :)
antes deu iniciar o uso, gostaria de tirar umas duvidas
1. no caso eu tenho dois monitores, posso usar meu monitor secundario (ele é um ultra wide, cabe mais contas), o bot vai detectar?
2. até quantas contas eu posso usar? no momento tenho 6, mas pretendo colocar mais contas.
3. configuracao que eu preciso pra rodar 6 janelas no mesmo monitor, zoom 50% seria:
[pt_BR] Opção para usar multiplas contas no mesmo monitor
Valor padrão: False
 multiples_accounts_same_monitor:
 enable: True

[pt_BR] Habilita para usar uma escala diferente de visão em seu navegador
Valor padrão: False
  enable: True
 
[pt_BR] Quando a escala está habilitada, especificar o valor de escala utilizada em seu navegador
Valor padrão: 100
  percent: 50
  
  Obviamente, sabendo que com ese zoom de 50% pode dar problema, mas gostaria de testar.
  
  Aguardo resposta, obrigado!!!

**Comment by ericanholete** [comment]
> > Funciona bem em linux?
> 
> Rapaz, se me fez uma boa pergunta, mas eu ja tava pensando em coLocar uma maquina com linux pra rodar, vou fazer o teste hehe

Não consegui rodar aqui

![image](https://user-images.githubusercontent.com/63925846/148703783-89cd4df0-6123-44db-af41-22234dacf5eb.png)

**Comment by zSinnK** [comment]
> > > Funciona bem em linux?
> > 
> > 
> > Rapaz, se me fez uma boa pergunta, mas eu ja tava pensando em coLocar uma maquina com linux pra rodar, vou fazer o teste hehe
> 
> Não consegui rodar aqui
> 
> ![image](https://user-images.githubusercontent.com/63925846/148703783-89cd4df0-6123-44db-af41-22234dacf5eb.png)

Pelo que entendi ele alerta que a função de identificar as janelas não funciona no linux. Vou testar aqui em uma vm pra ver se roda e volto aqui 



Edit---- não funciona em linux, tive o mesmo erro que o amigo acima

**Comment by Romario-Francisco-Soares** [comment]
Imagem:
https://user-images.githubusercontent.com/65358034/148765695-969564ed-9127-49ec-9aa2-532c4e930bdb.png

minha configuração:
# [pt_BR] Opção para usar multiplas contas no mesmo monitor
# Valor padrão: False
multiples_accounts_same_monitor:
  enable: True
  window_contains_title: "bombcrypto"

# [en_US] If you have macbook or laptop with Retina screen, enable this feature
# Default value: False
#
# [pt_BR] Se você tem um macbook ou notebook com tela retina, habilite essa função
# Valor padrão: False
is_retina_screen: False

# [en_US] Speed of mouse move for automation
# Default value: 1
#
# [pt_BR] Velocidade do movimento do mouse para a automação
# Valor padrão: 1
mouse_move_speed: 0.6



descrição: quando clico no .bat ele mostra aquela imagem e após, fecha sem que o robô seja executado...

**Comment by rcomparim** [comment]
opa aqui nao rodou no mac, pode passar seu whatsapp fazendo favor, acho q pode ser algum outro ajuste

**Comment by hugolfreitas** [comment]
boa!
quando acabei de fazer os ajustes aqui pra funcionar 2 contas com tela dividida eu achei seu post aqui hahahah
mas vai servir pra pegar umas ideias e aprimorar la, valeu!

essa é a beleza do open source colaborativo haha

**Comment by ThomWilliam** [comment]
NÃO FUNCIONA, ele não controla o mouse e dá alguns erros:







[2022-01-10 16:44:16] ERROR:   File "C:\bomb\src\bot\action.py", line 107, in activeWindow
    env.window_object.activate()
[2022-01-10 16:44:16] ERROR:   File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
[2022-01-10 16:44:16] ERROR:   File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
[2022-01-10 16:44:16] ERROR: pygetwindow.PyGetWindowException: Error code from Windows: 0 - A operação foi concluída com êxito.
[2022-01-10 16:44:16] ERROR: 
During handling of the above exception, another exception occurred:

[2022-01-10 16:44:16] ERROR: Traceback (most recent call last):
[2022-01-10 16:44:16] ERROR:   File "C:\bomb\index.py", line 16, in <module>
    runMultiAccount()
[2022-01-10 16:44:16] ERROR:   File "C:\bomb\src\main_multi_account.py", line 48, in runMultiAccount
    Action.activeWindow()
[2022-01-10 16:44:16] ERROR:   File "C:\bomb\src\bot\action.py", line 110, in activeWindow
    env.window_object.activate()
[2022-01-10 16:44:16] ERROR:   File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
[2022-01-10 16:44:16] ERROR:   File "C:\Users\Thomas\AppData\Local\Programs\Python\Python310\lib\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
[2022-01-10 16:44:16] ERROR: pygetwindow.PyGetWindowException: Error code from Windows: 0 - A operação foi concluída com êxito.

**Comment by Raoniq** [comment]
Aqui está funcionando perfeitamente no Windows com 2 telas no chrome, obrigado !!

**Comment by cleitonleonel** [comment]
> > > > Funciona bem em linux?
> > > 
> > > 
> > > Rapaz, se me fez uma boa pergunta, mas eu ja tava pensando em coLocar uma maquina com linux pra rodar, vou fazer o teste hehe
> > 
> > 
> > Não consegui rodar aqui
> > ![image](https://user-images.githubusercontent.com/63925846/148703783-89cd4df0-6123-44db-af41-22234dacf5eb.png)
> 
> Pelo que entendi ele alerta que a função de identificar as janelas não funciona no linux. Vou testar aqui em uma vm pra ver se roda e volto aqui
> 
> Edit---- não funciona em linux, tive o mesmo erro que o amigo acima

Versão que fiz para funcionar em linux multijanelas...https://github.com/cleitonleonel/bombcrypto-bot

**Comment by kendikaku** [comment]
Estou com um problema, ele funciona tudo perfeito, mas na hora de colocar os heróis pra trabalhar, ele tá colocando heróis aleatórios, colocando sempre o meu épico e o meu lendário sem vida verde e deixando de colocar outros com vida verde, oque pode ser?

**Comment by badyami** [comment]
Oie sabe me dizer se consigo usar essa versão com 5 continhas ? obrigada desde ja

**Comment by VuMiner** [comment]
https://github.com/rzanca/bombcrypto-multibot
5 Acc 1 PC
*Tr**ân Trọng!*

*            -----------------*

*   Ph**ạm Tuấn Vũ*

*  Điện thoại*  :  0777 779 776 -  0938 013 030

*  Thư: ***@***.***   ***@***.***>


Vào Th 3, 18 thg 1, 2022 vào lúc 22:02 badyami ***@***.***>
đã viết:

**Comment by aseriosouza** [comment]
cara qual biblioteca esta utilizando para enterpretrar os icones ali no shell?

> Opa tranquilo? então, testei o bot porém ele só trabalha em uma conta ( da esquerda ) e não interage com a outra organizei a tela dessa maneira:
> 
> ![Captura de tela 2022-01-08 212148](https://user-images.githubusercontent.com/95734505/148664435-7a38d38e-efad-451f-b83e-69c10ba62737.png)

**Comment by aseriosouza** [comment]
Fala Matheus blz?! Cara, parabéns pelo seu fork acertei alguns parâmetros de meu gosto aqui e esta funcionando muito bem!
Porem algumas vezes quando minha conta desconecta ele abre  a metamask de tela cheia e muitas vezes ela fica por trás da tela do jogo!  já viu algum caso parecido? tem alguma dica de como resolver?

**Comment by badyami** [comment]
> 

vc sabe com quantas contas ele funciona ? tentei aqui com 5 mas n ta indo x.x

**Comment by badyami** [comment]
> Fala Matheus blz?! Cara, parabéns pelo seu fork acertei alguns parâmetros de meu gosto aqui e esta funcionando muito bem! Porem algumas vezes quando minha conta desconecta ele abre a metamask de tela cheia e muitas vezes ela fica por trás da tela do jogo! já viu algum caso parecido? tem alguma dica de como resolver?

pode me ajudar por favor ? aqui o bot não faz nada configurei tudo bonitinho mas so não vai, se puder dar uma olhada seria mto grata, muito obrigada desde já.
![image](https://user-images.githubusercontent.com/96646539/150935511-2f07ce90-a96e-4835-a5f1-562f3eab2828.png)

**Comment by sage-iorran** [comment]
No meu macbook nao funcionou. Testei em todas as resoluções.
