### ISSUE TITLE
Problema com Ximage no ubuntu 20.04.03 LTS

### ISSUE THREAD

**Issue by AlisonMartins01** [mpcabete/bombcrypto-bot#59]
Primeiramente muito obrigado pelo bot, com certeza irei realizar algumas doações kkk. Estou tentando instalar na minha primeira maquina, entretanto estou recebendo a seguinte mensagem de erro no console.

Sending heroes to work..Traceback (most recent call last):
  File "index.py", line 353, in <module>
    main()
  File "index.py", line 324, in main
    refreshHeroes()
  File "index.py", line 286, in refreshHeroes
    goToHeroes()
  File "index.py", line 207, in goToHeroes
    if clickBtn(arrow_img):
  File "index.py", line 101, in clickBtn
    matches = positions(img, trashhold=trashhold)
  File "index.py", line 128, in positions
    img = printSreen()
  File "index.py", line 124, in printSreen
    sct_img = np.array(sct.grab(sct.monitors[0]))
  File "/home/alexandre/.local/lib/python3.8/site-packages/mss/base.py", line 88, in grab
    return self._grab_impl(monitor)
  File "/home/alexandre/.local/lib/python3.8/site-packages/mss/linux.py", line 460, in _grab_impl
    raise ScreenShotError(
mss.exception.ScreenShotError: [XImage] bits per pixel value not (yet?) implemented: 16.

Verifquei em varios forums e artigos entretanto não achei nenhuma solução para este problema. Caso tenha alguma ideia de correção ficaria muito grato e me disponho a gratificar um pouco quem puder auxiliar. Obrigado desde já.

**Comment by mpcabete** [comment]
Oi, amigo, tenta rodar:
`sudo apt update`
`sudo apt upgrade`
`pip install mss -U`

**Comment by mpcabete** [comment]
Vou fechar o issue pra ajudar na organização, pode responder por aqui que eu vejo.

**Comment by fumasa21** [comment]
> Primeiramente muito obrigado pelo bot, com certeza irei realizar algumas doações kkk. Estou tentando instalar na minha primeira maquina, entretanto estou recebendo a seguinte mensagem de erro no console.
> 
> Sending heroes to work..Traceback (most recent call last): File "index.py", line 353, in main() File "index.py", line 324, in main refreshHeroes() File "index.py", line 286, in refreshHeroes goToHeroes() File "index.py", line 207, in goToHeroes if clickBtn(arrow_img): File "index.py", line 101, in clickBtn matches = positions(img, trashhold=trashhold) File "index.py", line 128, in positions img = printSreen() File "index.py", line 124, in printSreen sct_img = np.array(sct.grab(sct.monitors[0])) File "/home/alexandre/.local/lib/python3.8/site-packages/mss/base.py", line 88, in grab return self._grab_impl(monitor) File "/home/alexandre/.local/lib/python3.8/site-packages/mss/linux.py", line 460, in _grab_impl raise ScreenShotError( mss.exception.ScreenShotError: [XImage] bits per pixel value not (yet?) implemented: 16.
> 
> Verifquei em varios forums e artigos entretanto não achei nenhuma solução para este problema. Caso tenha alguma ideia de correção ficaria muito grato e me disponho a gratificar um pouco quem puder auxiliar. Obrigado desde já.

Ola ! baixei hoje e tenho o mesmo problema ubunto.

**Comment by 1x10** [comment]
> Primeiramente muito obrigado pelo bot, com certeza irei realizar algumas doações kkk. Estou tentando instalar na minha primeira maquina, entretanto estou recebendo a seguinte mensagem de erro no console.
> 
> Sending heroes to work..Traceback (most recent call last): File "index.py", line 353, in main() File "index.py", line 324, in main refreshHeroes() File "index.py", line 286, in refreshHeroes goToHeroes() File "index.py", line 207, in goToHeroes if clickBtn(arrow_img): File "index.py", line 101, in clickBtn matches = positions(img, trashhold=trashhold) File "index.py", line 128, in positions img = printSreen() File "index.py", line 124, in printSreen sct_img = np.array(sct.grab(sct.monitors[0])) File "/home/alexandre/.local/lib/python3.8/site-packages/mss/base.py", line 88, in grab return self._grab_impl(monitor) File "/home/alexandre/.local/lib/python3.8/site-packages/mss/linux.py", line 460, in _grab_impl raise ScreenShotError( mss.exception.ScreenShotError: [XImage] bits per pixel value not (yet?) implemented: 16.
> 
> Verifquei em varios forums e artigos entretanto não achei nenhuma solução para este problema. Caso tenha alguma ideia de correção ficaria muito grato e me disponho a gratificar um pouco quem puder auxiliar. Obrigado desde já.

Para conectar na VM voce esta usando qual método?
