### ISSUE TITLE
e ae mano. blz?

### ISSUE THREAD

**Issue by danylocp** [mpcabete/bombcrypto-bot#590]
Tem como mandar hero especifico para a casa?

**Comment by fguide** [comment]
Amigo, leia a página inicial, está lá o processo para fazer a configuração.

**Comment by hugolfreitas** [comment]
> e ae mano. blz? 

q issue boa kkkkkkkkkkkkkkkk

**Comment by cristhianbreunig** [comment]
@danylocp já resolveu seu problema ?

Se sim, encerra a issue por gentileza, dessa forma o projeto fica mais organizado e melhor para quem está dando suporte / auxiliando.
