### ISSUE TITLE
Bot parou de funcionar

### ISSUE THREAD

**Issue by amadeu22** [mpcabete/bombcrypto-bot#593]
Estava utilizando o bot normalmente, hoje do nada ele começou apresentar o erro da imagem, alguem sabe o que pode ser?

![Screenshot_5](https://user-images.githubusercontent.com/96693813/148699356-80c93701-376d-442d-a239-134932cccdc3.png)

**Comment by fguide** [comment]
Provavelmente configuração de video, está operando em algo diferente do padrão (32 ou 24 bit).

Veja se houve aleração de drivers, configuracao, etc.

**Comment by heitoor** [comment]
Mesmo problema aqui, não sei o que fazer. Nada mudou no meu notebook
