### ISSUE TITLE
Alguém pode ajudar?

### ISSUE THREAD

**Issue by noLEAL** [mpcabete/bombcrypto-bot#595]
Requirement already satisfied: MouseInfo==0.1.3 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (0.1.3)
Requirement already satisfied: mss==6.1.0 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (6.1.0)
Requirement already satisfied: numpy==1.21.4 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (1.21.4)
Requirement already satisfied: opencv-python==4.5.4.60 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 4)) (4.5.4.60)
Requirement already satisfied: PyAutoGUI==0.9.53 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (0.9.53)
Requirement already satisfied: PyGetWindow==0.0.9 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 6)) (0.0.9)
Requirement already satisfied: PyMsgBox==1.0.9 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 7)) (1.0.9)
Requirement already satisfied: pyperclip==1.8.2 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 8)) (1.8.2)
Requirement already satisfied: PyRect==0.1.4 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 9)) (0.1.4)
Requirement already satisfied: PyScreeze==0.1.28 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 10)) (0.1.28)
Requirement already satisfied: pytweening==1.0.4 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 11)) (1.0.4)
Requirement already satisfied: PyYAML==6.0 in c:\users\bboyb\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 12)) (6.0)

**Comment by fguide** [comment]
Nada de errado, diz que voce ja tem todos pacotes instalados.

**Comment by noLEAL** [comment]
e sobre isso 


![image](https://user-images.githubusercontent.com/83329725/148711190-6296d176-1414-4085-92a7-c87bc326e431.png)

**Comment by fguide** [comment]
tente iniciar com: python index.py
