### ISSUE TITLE
Bot parou de funcionar

### ISSUE THREAD

**Issue by ArthurEnrique15** [mpcabete/bombcrypto-bot#596]
![image](https://user-images.githubusercontent.com/77863834/148712361-6a462275-c329-4396-b12f-3e50f6802880.png)

O bot parou de funcionar no meu pc a alguns dias, baixei a ultima versão aqui do github, não tem nenhuma alteração.

Já tentei apagar a pasta e clonar de novo, mas não resolveu.

Como dá pra ver no print, ele não está detectando mais nenhum botão na tela. Alguém sabe o que pode ser? 
(uso Linux, Ubuntu LTS 20.04)

**Comment by fguide** [comment]
Verifique as configurações de video, resolucao, scaling, etc. 

Se estava funcionando e parou, é mais provavel que seja algo em seu pc porque funciona normalmente com as configurações corretas, fiz uma instalação nova hoje sem erros.

**Comment by cleitonleonel** [comment]
> ![image](https://user-images.githubusercontent.com/77863834/148712361-6a462275-c329-4396-b12f-3e50f6802880.png)
> 
> O bot parou de funcionar no meu pc a alguns dias, baixei a ultima versão aqui do github, não tem nenhuma alteração.
> 
> Já tentei apagar a pasta e clonar de novo, mas não resolveu.
> 
> Como dá pra ver no print, ele não está detectando mais nenhum botão na tela. Alguém sabe o que pode ser? (uso Linux, Ubuntu LTS 20.04)

Funcionando aqui https://github.com/cleitonleonel/bombcrypto-bot

**Comment by jeffersonveloso** [comment]
> > ![image](https://user-images.githubusercontent.com/77863834/148712361-6a462275-c329-4396-b12f-3e50f6802880.png)
> > O bot parou de funcionar no meu pc a alguns dias, baixei a ultima versão aqui do github, não tem nenhuma alteração.
> > Já tentei apagar a pasta e clonar de novo, mas não resolveu.
> > Como dá pra ver no print, ele não está detectando mais nenhum botão na tela. Alguém sabe o que pode ser? (uso Linux, Ubuntu LTS 20.04)
> 
> Funcionando aqui https://github.com/cleitonleonel/bombcrypto-bot

Boa noite, sabe me dizer se é possível utilizar o bot com mais de uma conta e se tem um navegador específico ?

**Comment by cleitonleonel** [comment]
> > > ![image](https://user-images.githubusercontent.com/77863834/148712361-6a462275-c329-4396-b12f-3e50f6802880.png)
> > > O bot parou de funcionar no meu pc a alguns dias, baixei a ultima versão aqui do github, não tem nenhuma alteração.
> > > Já tentei apagar a pasta e clonar de novo, mas não resolveu.
> > > Como dá pra ver no print, ele não está detectando mais nenhum botão na tela. Alguém sabe o que pode ser? (uso Linux, Ubuntu LTS 20.04)
> > 
> > 
> > Funcionando aqui https://github.com/cleitonleonel/bombcrypto-bot
> 
> Boa noite, sabe me dizer se é possível utilizar o bot com mais de uma conta e se tem um navegador específico ?

Esse que te passei é uma implementação minha, fiz pra rodar multijanelas no Linux, mas testei pouco aqui, sou desenvolvedor e nem tenho os heróis apenas uma conta para testes de usabilidade.
