### ISSUE TITLE
still working?

### ISSUE THREAD

**Issue by zorelix69** [mpcabete/bombcrypto-bot#597]
is it still working and safe guys? im wondering if its still safe to use this. pls reply thanks :D

**Comment by fguide** [comment]
Yes it works. We cannot assure safety, this needs to be used on own risks.

You'd better be checking it with official support but as far as it's disclosed it is allowed.

**Comment by zorelix69** [comment]
im a bit confuse they annouce that script/macro are allowed on the announcement but when i ask on general chat discord they always said no

**Comment by zorelix69** [comment]
i will use it right now hehe hope i dont get ban hammer :D
