### ISSUE TITLE
Bot funcionando aqui, versão multi account, PORÉM.... TEM UM ERRO.

### ISSUE THREAD

**Issue by lifarrx** [mpcabete/bombcrypto-bot#598]
Tenho uma conta que todos os bonecos são SUPER RAROS e o restante são RAROS.

Então na hora de colocar os bonecos para trabalhar ele coloca só a primeira página pois não tem nenhum comum, alguém tem uma versão multi account que isso esteja resolvido? o #560 não resolve no meu caso, preciso que seja multi account + essa correção de scroll.

**Comment by zorelix69** [comment]
how long has youve been using the bot sir?

**Comment by fguide** [comment]
A maneira mais simples e sem alteração de codigo pra você resolver isso é trocar a imagem "common-text.png" por um scrennshot do LV, como mencionado em: #457

**Comment by lifarrx** [comment]
> how long has youve been using the bot sir?

About 2 weeks running this code.

**Comment by lifarrx** [comment]
> A maneira mais simples e sem alteração de codigo pra você resolver isso é trocar a imagem "common-text.png" por um scrennshot do LV, como mencionado em: #457

Vou tentar isso obrigado !

**Comment by fguide** [comment]
Se funcionar por favor feche o issue.
