### ISSUE TITLE
help not working :(

### ISSUE THREAD

**Issue by zorelix69** [mpcabete/bombcrypto-bot#599]
![269962378_2160443504107237_3411109231431448077_n](https://user-images.githubusercontent.com/97457948/148810886-575ed4da-8fe7-4104-8a8f-2197de9401e2.png)

help not working :(

**Comment by fguide** [comment]
You have probably not checked the "Add to Path" option when installing, as below:

![imagen](https://user-images.githubusercontent.com/95459411/148813209-77db816b-9fd0-4143-9505-2ddaed8d2163.png)

**Comment by zorelix69** [comment]
finish reinstalling hehe i forgot xD

**Comment by zorelix69** [comment]
![270797749_439473281252121_1978449325078753957_n](https://user-images.githubusercontent.com/97457948/148821609-a47c8d0b-2c63-40f9-af22-8febadf63951.png)
when i enter the last command nothing happen do i need to update pyton?
