### ISSUE TITLE
Hi, can you help me?

### ISSUE THREAD

**Issue by Diephi** [mpcabete/bombcrypto-bot#6]
Big thanks for the bot man, im getting this error after using the python index.py

C:\Users\diegu\Desktop\bombcrypto-bot-main>python index.py
Traceback (most recent call last):
  File "C:\Users\diegu\Desktop\bombcrypto-bot-main\index.py", line 7, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

thank you in advance!

**Comment by mpcabete** [comment]
Hi, I have forgotten to add a package to requirements.txt, thanks for letting me know. I have added it now. You can fix yours running the command
`pip install pyyaml`

**Comment by Diephi** [comment]
Opa cara obrigado por responder, dei uma viajada e mandei a duvida em inglês.
Agora apareceu outro problema, segue:
C:\Users\diegu\Desktop\bombcrypto-bot-main>
C:\Users\diegu\Desktop\bombcrypto-bot-main>python index.py
Traceback (most recent call last):
  File "C:\Users\diegu\Desktop\bombcrypto-bot-main\index.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Obrigado pela ajuda, se eu conseguir rodar esse bot vou te dar um donate

**Comment by MarsuraPedro** [comment]
Roda esse comando, que ja resolve 

pip3 install requests

**Comment by mpcabete** [comment]
Sim, o que o amigo sugeriu deve funcionar, arrumei o código também!

**Comment by Diephi** [comment]
Salve, tô até me sentindo chato de voltar aqui toda hora kkk
mas agora achei outro problema, o scroll ta bugado, ele tenta descer a tela mas desce muito pouco.. tipo milímetros.
ai como ele não vê nenhum novo ele sai da tela e vai pro treasure hunt
Obrigado pela disponibilização do bot

**Comment by mpcabete** [comment]
Salve, relaxa,se der certo manda uma gorjetinha depois e ta tudo certo hehehe
tanta mudar essa config pra true no arquivo config.yaml
use_click_and_drag_instead_of_scroll: false

**Comment by Diephi** [comment]
blz mano, se pegar direitinho vou te mandar um donate sim. Obrigado pelo suporte
