### ISSUE TITLE
Rodar mais de uma conta ao mesmo tempo

### ISSUE THREAD

**Issue by Hiwry** [mpcabete/bombcrypto-bot#60]
Alguém sabe rodar mais de uma conta ao mesmo tempo uma do lado da outra no monitor?

**Comment by cristhianbreunig** [comment]
> Alguém sabe rodar mais de uma conta ao mesmo tempo uma do lado da outra no monitor?

Isso ainda não é possível, o criador @mpcabete já comentou que pode funcionar em máquinas virtuais...

Dá uma olhada nessas issues:
https://github.com/mpcabete/bombcrypto-bot/issues/24
https://github.com/mpcabete/bombcrypto-bot/issues/46

**Comment by mpcabete** [comment]
Obrigado cristhian
