### ISSUE TITLE
@mpcabete DOGEDASH BOT , novo desafio bora?

### ISSUE THREAD

**Issue by Tom-Ethical** [mpcabete/bombcrypto-bot#601]

**Comment by fguide** [comment]
Que perda de tempo, hein amigo?

Tanto com o pedido quanto com o doge dash em si...

**Comment by Tom-Ethical** [comment]
faz que eu te pago

**Comment by fguide** [comment]
Não sou programador, e não tenho interesse no projeto, mas espero que encontre alguém que faça para você.

Porém o ideal não seria aqui, se quer cogitar a possibilidade do mpcabete criar um para você, seria mais viável mandar um e-mail para ele ou mesmo deixar seu contato para alguém que tiver o interesse te chamar, não acha?

**Comment by Tom-Ethical** [comment]
caso alguem queira fazer este projeto meu contato (12) 9 9229-1248 , somente aqueles que realmente souber fazer!

**Comment by Nucito** [comment]
🌚
