### ISSUE TITLE
Bot multi account não funciona, vários erros

### ISSUE THREAD

**Issue by ThomWilliam** [mpcabete/bombcrypto-bot#604]
Tentei utilizar o bot versão #587, porém ele não move o mouse e está dando diversos erros, funciona somente quando seleciono para somente 1 conta, atualmente tentei testar com 3, lado a lado (navegador Edge), configurei para 67% do zoom, mudei tudo que deveria no arquivo de configurações para que funcionasse...

![Sem título](https://user-images.githubusercontent.com/97475320/148832547-6011468f-7cd3-4de3-b51e-b2ab6656f0f2.png)

**Comment by fguide** [comment]
Não sei se vai ajudar criar outro issue sobre o assunto, você já tem uma no tópico mencionado correto? 

Seria mais fácil também você abrir um issue diretamente no rpositorio de quem criou a versao: https://github.com/MatheusHAS/bombcrypto-bot

Dessa forma o criador é notificado e tem mais chances de ver o problema.
