### ISSUE TITLE
certain hero epic/super rare

### ISSUE THREAD

**Issue by zorelix69** [mpcabete/bombcrypto-bot#605]
is there a features for auto rest even with energy so the strong heroes doesnt get really tired?

**Comment by Yumiizera** [comment]
Não, teve alguns que tentaram fazer esse tipo de modificação mas estava dando muita inconsistência no farm.

**Comment by zorelix69** [comment]
so it wasnt safe to use auto rest?

**Comment by fguide** [comment]
Possible - yes
Worth it? - IMO no, resting time is the same if the energy is full, empty or whatever state it is, so why not having better heroes getting tired?

It would make sense to make some heroes rest more/less than others depending on their stats, but that is not implemented on the official version though.
