### ISSUE TITLE
Suspensão de vps google 

### ISSUE THREAD

**Issue by biezus** [mpcabete/bombcrypto-bot#606]
Google suspendeu minha maquina virtual por mineração de crypto cripto. Algumém teve essa mensagem? Tem algo que de pra fazer sem ter que pagar?

**Comment by ByPivete** [comment]
usa o oracle, lá tá de graça... só vai ter que configurar o bot no linux

**Comment by fguide** [comment]
Nenhuma plataforma de VPS vai deixar um uso de CPU total por 24h em modo grátis..

Agora se o seu plano for pago, sem problemas..

**Comment by kerferber** [comment]
> Google suspendeu minha maquina virtual por mineração de crypto cripto. Algumém teve essa mensagem? Tem algo que de pra fazer sem ter que pagar?

Poxa. Que péssima notícia.
Após quanto tempo de uso foi suspenso?
Outra coisa, seu consumo de CPU ficava muito alto? Qts contas vc rodava e qual sua configuração de Vm?

**Comment by kerferber** [comment]
> usa o oracle, lá tá de graça... só vai ter que configurar o bot no linux

Totalmente de graça?
Estou usando Ubuntu, seria só trocar?
Obrigado

**Comment by biezus** [comment]
2 contas em duas vps diferentes, nos ultimos dias estava com 8vcpus rodando a 70% e 4 de ram em 50%. Ficou on por um mes mais ou menos.

**Comment by kerferber** [comment]
> 2 contas em duas vps diferentes, nos ultimos dias estava com 8vcpus rodando a 70% e 4 de ram em 50%. Ficou on por um mes mais ou menos.

Que droga. Estou quase há um mês...
Acho que vou tentar desligar a VM ao menos umas 2x ao dia pra tentar evitar esse banimento. Será que adiantaria?

**Comment by fguide** [comment]
> > 2 contas em duas vps diferentes, nos ultimos dias estava com 8vcpus rodando a 70% e 4 de ram em 50%. Ficou on por um mes mais ou menos.
> 
> Que droga. Estou quase há um mês... Acho que vou tentar desligar a VM ao menos umas 2x ao dia pra tentar evitar esse banimento. Será que adiantaria?

Aumentar vCPUs seria uma solucao porque nao topa o uso em 100%. 
Outra opcao seria atribuir um ou dois vcpus apenas para o browser assim o uso geral cai, por exemplo 4vCPus, 2 em 100% e e 2 idle o consumo total cai pra média de 50%...
