### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by MarSap7** [mpcabete/bombcrypto-bot#607]
I dont know why.
Any one can help me?
nothing is happening
![Capture](https://user-images.githubusercontent.com/97485964/148859402-aa35233e-8053-40e5-b5a8-0b59aca28c44.PNG)

**Comment by fguide** [comment]
Be sure to use single monitor, 100% scaling, 100% zoom on browser and max 1920x1080 resolution.

**Comment by MarSap7** [comment]
> Be sure to use single monitor, 100% scaling, 100% zoom on browser and max 1920x1080 resolution.

Thank you so match. It was the scaling.
Thanks again.
