### ISSUE TITLE
Problema na vps windoww 

### ISSUE THREAD

**Issue by Samuray92** [mpcabete/bombcrypto-bot#608]
Toda vez que deslogo da minha vps fica dando esse erro

![Screenshot_20220110-233720_Microsoft Remote Desktop](https://user-images.githubusercontent.com/97490209/148871790-616adf49-cfc1-4d63-aecd-3bfb07e30170.jpg)

**Comment by Xkarrior** [comment]
@Samuray92 Qual a VPS vc usa?

**Comment by Samuray92** [comment]
Eu uso vps da contabo, eu estava vendo aqui até mesmo se eu minimiza o acesso da vps da esse erro. Preciso deixa aberto.... aí aí bot não dá erro

**Comment by fguide** [comment]
Você acessa via Remote Desktop, certo? Sempre que fecha a conexão a sessão fica travada, você precisa usar o comando abaixo para desconectar:

```
for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
  %windir%\System32\tscon.exe %%s /dest:console
)
```

Mais informações sobre: https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html

Ou, utilize outra ferramenta de acesso, VNC, AnyDesk, etc

**Comment by Samuray92** [comment]
> Você acessa via Remote Desktop, certo? Sempre que fecha a conexão a sessão fica travada, você precisa usar o comando abaixo para desconectar:
> 
> ```
> for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
>   %windir%\System32\tscon.exe %%s /dest:console
> )
> ```
> 
> Mais informações sobre: https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html
> 
> Ou, utilize outra ferramenta de acesso, VNC, AnyDesk, etc

desculpe a ignorância mais eu não entendi muito bem o que eu devo fazer. e para criar um arquivo .bat?

**Comment by fguide** [comment]
Sim, um arquivo .bat com o comando acima, sempre que for desconectar execute ele e a sessão vai para console, continua aberta e provavelmente não dá o erro.

**Comment by jeffersonveloso** [comment]
> Eu uso vps da contabo, eu estava vendo aqui até mesmo se eu minimiza o acesso da vps da esse erro. Preciso deixa aberto.... aí aí bot não dá erro

Qual plano de vps você está utilizando ?

**Comment by wellclever** [comment]
> Você acessa via Remote Desktop, certo? Sempre que fecha a conexão a sessão fica travada, você precisa usar o comando abaixo para desconectar:
> 
> ```
> for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
>   %windir%\System32\tscon.exe %%s /dest:console
> )
> ```
> 
> Mais informações sobre: https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html
> 
> Ou, utilize outra ferramenta de acesso, VNC, AnyDesk, etc

Como eu faço para ajustar para uma resolução aceitável? Quando desconecto com o .bat do RDP, a resolução no AnyDesk e afins fica minúscula.

**Comment by fguide** [comment]
@wellclever 

Você por acaso já tentou trocar a resolução pelo anydesk e depois fazer o teste com o RDP? Nunca vi isso acontecer mas imagino que sua VPS esteja com resolucao baixa por padrao, e quando vc conecta com RDP ele usa as configuracoes de resolução do seu PC.

Se não resolver talvez vc possa usar o QRes ([link](https://sourceforge.net/projects/qres/)) e alterar o .bat conforme abaixo. Não esqueca de colocar o caminho de onde está o qres.exe no path do windows.

Não uso windows ha um bom tempo, talvez isso não funcione mais, precisa testar... Ainda acho que mudando a resolucao no anydesk ou vnc funcionaria

```
for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
  %windir%\System32\tscon.exe %%s /dest:console
  timeout 5
  qres /X 1920 /Y 1080 /C 32
)
```

**Comment by wellclever** [comment]
> @wellclever
> 
> Você por acaso já tentou trocar a resolução pelo anydesk e depois fazer o teste com o RDP? Nunca vi isso acontecer mas imagino que sua VPS esteja com resolucao baixa por padrao, e quando vc conecta com RDP ele usa as configuracoes de resolução do seu PC.
> 
> Se não resolver talvez vc possa usar o QRes ([link](https://sourceforge.net/projects/qres/)) e alterar o .bat conforme abaixo. Não esqueca de colocar o caminho de onde está o qres.exe no path do windows.
> 
> Não uso windows ha um bom tempo, talvez isso não funcione mais, precisa testar... Ainda acho que mudando a resolucao no anydesk ou vnc funcionaria
> 
> ```
> for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
>   %windir%\System32\tscon.exe %%s /dest:console
>   timeout 5
>   qres /X 1920 /Y 1080 /C 32
> )
> ```

Obrigado pelo retorno. No AnyDesk não deixa eu mudar a resolução, fica apenas uma opção mesmo. Vou tentar esse comando e aviso aqui.

**Comment by wellclever** [comment]
> > @wellclever
> > Você por acaso já tentou trocar a resolução pelo anydesk e depois fazer o teste com o RDP? Nunca vi isso acontecer mas imagino que sua VPS esteja com resolucao baixa por padrao, e quando vc conecta com RDP ele usa as configuracoes de resolução do seu PC.
> > Se não resolver talvez vc possa usar o QRes ([link](https://sourceforge.net/projects/qres/)) e alterar o .bat conforme abaixo. Não esqueca de colocar o caminho de onde está o qres.exe no path do windows.
> > Não uso windows ha um bom tempo, talvez isso não funcione mais, precisa testar... Ainda acho que mudando a resolucao no anydesk ou vnc funcionaria
> > ```
> > for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
> >   %windir%\System32\tscon.exe %%s /dest:console
> >   timeout 5
> >   qres /X 1920 /Y 1080 /C 32
> > )
> > ```
> 
> Obrigado pelo retorno. No AnyDesk não deixa eu mudar a resolução, fica apenas uma opção mesmo. Vou tentar esse comando e aviso aqui.

É, continuou o mesmo problema. Ao fechar o RDP, o AnyDesk muda para uma resolução super pequena. Vou pesquisar aqui. Valeu pela ajuda.

**Comment by fguide** [comment]
Veja se nao tem opção de configurar resolução no console do seu provedor de VPS... O anydesk deveria deixar vc mudar, a resolucao pelo que eu lembro...

O Qres nao funcionou?

**Comment by wellclever** [comment]
Usando Google Cloud. Não tem opção de mudar resolução. O Qres infelizmente não resolveu também.

**Comment by Samuray92** [comment]
> Sim, um arquivo .bat com o comando acima, sempre que for desconectar execute ele e a sessão vai para console, continua aberta e provavelmente não dá o erro.

Irmão acho que deu certo aqui viu.....

**Comment by Samuray92** [comment]
> > Eu uso vps da contabo, eu estava vendo aqui até mesmo se eu minimiza o acesso da vps da esse erro. Preciso deixa aberto.... aí aí bot não dá erro
> 
> Qual plano de vps você está utilizando ?

Uso o plano mais barato na contabo so que via windows

**Comment by Samuray92** [comment]
> Veja se nao tem opção de configurar resolução no console do seu provedor de VPS... O anydesk deveria deixar vc mudar, a resolucao pelo que eu lembro...
> 
> O Qres nao funcionou?
realmente a resolução muda para uma pequena depois que desconecta

**Comment by fguide** [comment]
É, eu realmente nunca vi isso em outros provedores ou em máquinas hospedadas nos lugares que trabalhei, talvez seja alguma limitacao do GCP? Creio que nao também porque outras pessoas usam normalmente.

Veja se ajuda:
https://cloud.google.com/compute/docs/instances/enable-instance-virtual-display

**Comment by wellclever** [comment]
Opa @fguide 

Consegui resolver. Esse link que enviou também tem a solução, no GCP quando é feito a VPS com Windows precisa marcar uma opção de Display Enable, aí você consegue acessar por aplicativos de conexão remota sem ser o RDP e não desconfigurar a tela. 

Só estava usando o Ubuntu, mas acho que o Windows é melhor para múltiplas contas, mesmo com a opção de usar o docker.

**Comment by fguide** [comment]
@wellclever bom saber, das proximas ja indico pro pessoal. Valeu!
