### ISSUE TITLE
Funcionalidade para enviar heróis para casa

### ISSUE THREAD

**Issue by neddles01** [mpcabete/bombcrypto-bot#61]
Possuo uma Tinny house e ele não manda ninguém para a casa, apenas para rest por padrão, teria a possibilidade de um update, ou versão para quem possui casa?

**Comment by mpcabete** [comment]
Oi needles, eu estou trabalhando nisso, mas ainda não ta 100%. É meio difícil pra mim testar o bot pq n tenho casa.
Vc pode encontrar a branch em que estou trabalhando nisso [aqui](https://github.com/mpcabete/bombcrypto-bot/tree/home-feature)
Da uma olhada que coloquei umas instruções lá de como usar.

**Comment by DobbyZer** [comment]
Conseguiste que las casas funcionasen?

**Comment by mpcabete** [comment]
@neddles01 mto obrigado! vc conseguiu colocar ele pra funcionar pelo link que eu mandei? Se estiver funcionando tudo certinho aí me avise que começo a colocar ele na versão definitiva do bot

**Comment by Cromaz** [comment]
Fala Amigo, eu vou testar hj... assim que o bomb deixar... mas dou um feedback

**Comment by neddles01** [comment]
> @neddles01 mto obrigado! vc conseguiu colocar ele pra funcionar pelo link que eu mandei? Se estiver funcionando tudo certinho aí me avise que começo a colocar ele na versão definitiva do bot

Irei testar hoje pela noite, dou um feedback aqui!

**Comment by Cromaz** [comment]
Inicialmente não mandou herois para casa, mudei a configuração para hero_trashhold: 0.9 e home_button_trashhold: 0.6 ai ele começou a mandar os herois pra casa, mas manda herois errados. 

O erro eu acho que ocorre pq quando ele tira o print os herois estão na posição X e quando ele clica na casa o jogo manda o heroi pra ultimo da lista. Ou seja muda as posições da foto que ele tirou.
Talvez se ele tirar uma nova foto toda vez que mandar um heroi pra casa resolve.

O teste foi bem prejudicado pela estabilidade do bomb hj. Se quiser acompanhar em tempo real, podemos marcar uma call no disc pra vc ver funcionando.

**Comment by mpcabete** [comment]
ahh dahora cromaz, faz sentido, vou configurar ele pra tirar o screenshot dps de clickar na house. Dou uma avisada por aqui quando atualizar ele!

**Comment by DobbyZer** [comment]
I make some test, i touch some ligne but still have some problem. Do you have any code about this ? Go talk on discord if you want DobbyElfe#4436

**Comment by Cromaz** [comment]
Fala @mpcabete meu jovem, conforme prometido, mandei 50dol ai na sua carteira pra te dar uma motivação. Obrigado por seu empenho =]
