### ISSUE TITLE
Multi Account Chrome flags

### ISSUE THREAD

**Issue by MarSap7** [mpcabete/bombcrypto-bot#611]
Is it possible that in the new version of chrome (97.0.4692.71) is impossible to disable the occlusion windows? 
I can not find

**Comment by fguide** [comment]
access chrome://flags/ and disable it on "Calculate window occlusion on Windows"

**Comment by MarSap7** [comment]
In which version of Chrome have you found this flag?

**Comment by fguide** [comment]
Sorry I don't use chrome (and dont even recommend it, perhaps chromium would be a better option?) so I got the answer from #463

**Comment by bigorna23** [comment]
https://github.com/mpcabete/bombcrypto-bot/issues/463#issuecomment-1006136917

**Comment by MarSap7** [comment]
Thanks at all

**Comment by deftandre** [comment]
Alguém sabe como proceder quando o chrome atualizou a opção não aparece mais
