### ISSUE TITLE
Bot colocar todos os heroes para dormir antes da manutenção!

### ISSUE THREAD

**Issue by themexdev** [mpcabete/bombcrypto-bot#612]
Galera, é possível colocar os bots para dormir sempre que uma manutenção for divulgada agora com essa nova interface?

**Comment by cristhianbreunig** [comment]
> Galera, é possível colocar os bots para dormir sempre que uma manutenção for divulgada agora com essa nova interface?

Penso que é possível colocar uma função simples no bot para que seja possível pelo menos em primeiro momento configurar um horário para o bot parar e outro para ele começar novamente.

Daí ajustar para que dentro desse horário ele não mande os heróis para trabalhar, para isso seria necessário também uma função para mandar eles descansarem (_acredito que não temos essa opção ainda, mas é algo que pretendo implementar para melhorar o bot_).

**Comment by kerferber** [comment]
A ideia é interessante. Acredito que não seja muito complexo de fazer visto que o texto que informa as notificações de manutenção é selecionável. 

Alguém conseguiu perceber quanto tempo antes da manutenção eles informaram na página do bomb?

**Comment by cristianomg** [comment]
até daria, o problema é q nem sempre anunciam manutenção la na interface. vou procurar se é possivel integrar com o discord caso seja possivel da pra fazer sim

**Comment by themexdev** [comment]
Eu tinha pensado em pegar a mensagem "Maintenance" lá no servidor como imagem mesmo e fazer uma lógica em cima disso, mas tem essa questão do quanto tempo antes eles informam lá, não consegui acompanhar um aviso de manutenção programada ainda.

**Comment by themexdev** [comment]
Percebi aqui que seja manutenção programada ou não, a mensagem de status é atualizada no jogo e não cai logo de cara, então tão logo a mensagem de MAINTENANCE ou OFFLINE seja apresentada, daria para fazer a lógica em cima disso e colocar todos os heroes para dormir de uma só vez aproveitando a nova interface e done!

**Comment by fguide** [comment]
> Percebi aqui que seja manutenção programada ou não, a mensagem de status é atualizada no jogo e não cai logo de cara, então tão logo a mensagem de MAINTENANCE ou OFFLINE seja apresentada, daria para fazer a lógica em cima disso e colocar todos os heroes para dormir de uma só vez aproveitando a nova interface e done!

Use api pra isso:

http://api.bombcrypto.io/ccu

Com python consegue tratar JSON e requests pra pegar o resultado, se offline ou online.

Mas nao tenho certeza se realmente mudam antes de cair, acredito que nao.

**Comment by themexdev** [comment]
Mas neste caso, usando API não seria contra as regras, até então leitura de imagem na tela não é proibido, mas se entra nessa questão de API eu acho que já seria, não?

**Comment by fguide** [comment]
Acredito que não, é uma API pública e apenas o método GET... 
Além disso o seu navegador já acessa a API pra mostrar as informações na tela.
