### ISSUE TITLE
Multi Account Nao funciona

### ISSUE THREAD

**Issue by GersonNydes** [mpcabete/bombcrypto-bot#613]
Ola, tenho duas contas uma no Chrome e outra no Firefox. porem nao está funcionando o multi account. Ele nao troca de tela. Mas funciona certinho na tela em que está, e tenho que ficar trocando o navegador manualmente.
Como consigo corrigir isso ?

**Comment by rzanca** [comment]
Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot

**Comment by fernando-cacavaio** [comment]
> Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot

boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?

**Comment by rzanca** [comment]
> > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> 
> boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?

Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. 
Não precisa abrir pelo link. Pode usar a versão normal.

Essa versão incluí,
Notificações do Telegram 
Human Clicker
Melhorias nas funções

**Comment by fernando-cacavaio** [comment]
> > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > 
> > 
> > boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?
> 
> Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. Não precisa abrir pelo link. Pode usar a versão normal.
> 
> Essa versão incluí, Notificações do Telegram Human Clicker Melhorias nas funções

Legal, e se eu nao quiser usar o Telegram, sou obrigado? Pois o mesmo esta dando erro se nao configuro o TOKEN.

**Comment by kendikaku** [comment]
> > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > 
> > 
> > boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?
> 
> Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. Não precisa abrir pelo link. Pode usar a versão normal.
> 
> Essa versão incluí, Notificações do Telegram Human Clicker Melhorias nas funções

Boa tarde,
você consegue fazer uma multaccount com essa melhorias do seu bot dessa forma? conforme o item [587](https://github.com/mpcabete/bombcrypto-bot/issues/587)

**Comment by rzanca** [comment]
> > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > 
> > > 
> > > boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?
> > 
> > Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. Não precisa abrir pelo link. Pode usar a versão normal.
> > 
> > Essa versão incluí, Notificações do Telegram Human Clicker Melhorias nas funções
> 
> Legal, e se eu nao quiser usar o Telegram, sou obrigado? Pois o mesmo esta dando erro se nao configuro o TOKEN. 


Até o momento sim, vou incluir essa alteração ainda hoje. Assim será possível desabililitar o mesmo.

**Comment by rzanca** [comment]
> > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > 
> > > 
> > > boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?
> > 
> > 
> > Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. Não precisa abrir pelo link. Pode usar a versão normal.
> > Essa versão incluí, Notificações do Telegram Human Clicker Melhorias nas funções
> 
> Boa tarde, você consegue fazer uma multaccount com essa melhorias do seu bot dessa forma? conforme o item [587](https://github.com/mpcabete/bombcrypto-bot/issues/587)

Sim é possível, eu já estou trabalhando em uma versão com diversas mudanças, inclusive seguindo uma estrutura mais organizada e com Poetry nas dependências.

**Comment by kendikaku** [comment]
> > > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > > 
> > > > 
> > > > boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?
> > > 
> > > 
> > > Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. Não precisa abrir pelo link. Pode usar a versão normal.
> > > Essa versão incluí, Notificações do Telegram Human Clicker Melhorias nas funções
> > 
> > 
> > Boa tarde, você consegue fazer uma multaccount com essa melhorias do seu bot dessa forma? conforme o item [587](https://github.com/mpcabete/bombcrypto-bot/issues/587)
> 
> Sim é possível, eu já estou trabalhando em uma versão com diversas mudanças, inclusive seguindo uma estrutura mais organizada e com Poetry nas dependências.

Bem legal, o multi account dando alt tab buga os heróis direto, tentei usar o seu mas acontecia direto dos heróis parar fora do mapa, aí eu testei esse aí que mencionei e está perfeito, só falta mesmo essa interação aí com o Telegram e quem sabe no futuro botar os heróis raros entre outros especificamente, aguardo seu bot atualizado então para testar.

**Comment by rzanca** [comment]
> > > > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > > > 
> > > > > 
> > > > > boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?
> > > > 
> > > > 
> > > > Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. Não precisa abrir pelo link. Pode usar a versão normal.
> > > > Essa versão incluí, Notificações do Telegram Human Clicker Melhorias nas funções
> > > 
> > > 
> > > Boa tarde, você consegue fazer uma multaccount com essa melhorias do seu bot dessa forma? conforme o item [587](https://github.com/mpcabete/bombcrypto-bot/issues/587)
> > 
> > 
> > Sim é possível, eu já estou trabalhando em uma versão com diversas mudanças, inclusive seguindo uma estrutura mais organizada e com Poetry nas dependências.
> 
> Bem legal, o multi account dando alt tab buga os heróis direto, tentei usar o seu mas acontecia direto dos heróis parar fora do mapa, aí eu testei esse aí que mencionei e está perfeito, só falta mesmo essa interação aí com o Telegram e quem sabe no futuro botar os heróis raros entre outros especificamente, aguardo seu bot atualizado então para testar.

Esse erro é causado pelos navegadores Chromium, você precisa mudar as flags para que ele não mude o gerenciamento. 
Temporarily unexpire M96 flags. = Enabled
Calculate Native Windows Occlusion = Disabled

**Comment by kendikaku** [comment]
> > > > > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > > > > 
> > > > > > 
> > > > > > boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?
> > > > > 
> > > > > 
> > > > > Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. Não precisa abrir pelo link. Pode usar a versão normal.
> > > > > Essa versão incluí, Notificações do Telegram Human Clicker Melhorias nas funções
> > > > 
> > > > 
> > > > Boa tarde, você consegue fazer uma multaccount com essa melhorias do seu bot dessa forma? conforme o item [587](https://github.com/mpcabete/bombcrypto-bot/issues/587)
> > > 
> > > 
> > > Sim é possível, eu já estou trabalhando em uma versão com diversas mudanças, inclusive seguindo uma estrutura mais organizada e com Poetry nas dependências.
> > 
> > 
> > Bem legal, o multi account dando alt tab buga os heróis direto, tentei usar o seu mas acontecia direto dos heróis parar fora do mapa, aí eu testei esse aí que mencionei e está perfeito, só falta mesmo essa interação aí com o Telegram e quem sabe no futuro botar os heróis raros entre outros especificamente, aguardo seu bot atualizado então para testar.
> 
> Esse erro é causado pelos navegadores Chromium, você precisa mudar as flags para que ele não mude o gerenciamento. Temporarily unexpire M96 flags. = Enabled Calculate Native Windows Occlusion = Disabled

O primeiro comando eu achei, agora esse Windows occlusion não existe mais na versão que estou usando

edit: desconsidera, achei os dois comandos, efetuei a troca e agora ta funcionando normalmente.

**Comment by olivete** [comment]
> > > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > > 
> > > > 
> > > > boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?
> > > 
> > > 
> > > Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. Não precisa abrir pelo link. Pode usar a versão normal.
> > > Essa versão incluí, Notificações do Telegram Human Clicker Melhorias nas funções
> > 
> > 
> > Legal, e se eu nao quiser usar o Telegram, sou obrigado? Pois o mesmo esta dando erro se nao configuro o TOKEN.
> 
> Até o momento sim, vou incluir essa alteração ainda hoje. Assim será possível desabililitar o mesmo.

Poxa se tu conseguir fazer o multi account com as janelas lado a lado tipo 50%, vai ficar show! Eu prefiro muito ver todas janelas abertas do que o bot dando alt tab. Esperoq ue consiga, vou ficar de olho. Obrigado!

**Comment by rzanca** [comment]
> > > > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > > > 
> > > > > 
> > > > > boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?
> > > > 
> > > > 
> > > > Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. Não precisa abrir pelo link. Pode usar a versão normal.
> > > > Essa versão incluí, Notificações do Telegram Human Clicker Melhorias nas funções
> > > 
> > > 
> > > Legal, e se eu nao quiser usar o Telegram, sou obrigado? Pois o mesmo esta dando erro se nao configuro o TOKEN.
> > 
> > 
> > Até o momento sim, vou incluir essa alteração ainda hoje. Assim será possível desabililitar o mesmo.
> 
> Poxa se tu conseguir fazer o multi account com as janelas lado a lado tipo 50%, vai ficar show! Eu prefiro muito ver todas janelas abertas do que o bot dando alt tab. Esperoq ue consiga, vou ficar de olho. Obrigado!

A ideia é reescrever toda a estrutura do bot, e fazer diversas melhorias, já estava acompanhando o trabalho de outros membros também e o pessoal tem trazido soluções interessantes.

**Comment by rzanca** [comment]
> > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > 
> > > 
> > > boa vou dar uma olhada, como esta funcionando o esquema de multi contas? Precisa ser em navagador diferente e abrindo pelo app.bomb?
> > 
> > 
> > Mesmo navegador, pode separar via perfil. Recomendo o uso do Edge, pois pode nomear cada perfil e ele aparece nas notificações do Telegram. Não precisa abrir pelo link. Pode usar a versão normal.
> > Essa versão incluí, Notificações do Telegram Human Clicker Melhorias nas funções
> 
> Legal, e se eu nao quiser usar o Telegram, sou obrigado? Pois o mesmo esta dando erro se nao configuro o TOKEN.

Na versão 0.4.0 que acabei de postar, está incluso a verificação do token, caso não esteja configurado, ele avisa, mas continua rodando o bot normal. 
Obrigado pela sugestão

**Comment by kendikaku** [comment]
> 

Tem previsão de quando vai ter essa versão?

**Comment by kerferber** [comment]
> Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot

Sabe se este funciona multiacount no Linux?

**Comment by rzanca** [comment]
> > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> 
> Sabe se este funciona multiacount no Linux?

Ainda não, está em fase de testes. Logo vai ser implementado.

**Comment by kerferber** [comment]
> > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > 
> > 
> > Sabe se este funciona multiacount no Linux?
> 
> Ainda não, está em fase de testes. Logo vai ser implementado.

Show. Vi que envia saldo por telegram. Ele envia em formato texto ou print?

**Comment by rzanca** [comment]
> > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > 
> > > 
> > > Sabe se este funciona multiacount no Linux?
> > 
> > Ainda não, está em fase de testes. Logo vai ser implementado.
> 
> Show. Vi que envia saldo por telegram. Ele envia em formato texto ou print?

Está enviando via Print. 
O tessaract falha muito. Por enquanto sem condições de um uso confiável. Precisa ajustar bem ele antes de soltar no ar a versão texto.

**Comment by petryck** [comment]
Alguma solução para usar no linux ?

**Comment by petryck** [comment]
> > > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > > 
> > > > 
> > > > Sabe se este funciona multiacount no Linux?
> > > 
> > > 
> > > Ainda não, está em fase de testes. Logo vai ser implementado.
> > 
> > 
> > Show. Vi que envia saldo por telegram. Ele envia em formato texto ou print?
> 
> Está enviando via Print. O tessaract falha muito. Por enquanto sem condições de um uso confiável. Precisa ajustar bem ele antes de soltar no ar a versão texto.

Alguma solução para usar no linux ?

**Comment by kerferber** [comment]
> > > > > Utilize uma versão com suporte a multi contas. https://github.com/rzanca/bombcrypto-multibot
> > > > 
> > > > 
> > > > Sabe se este funciona multiacount no Linux?
> > > 
> > > 
> > > Ainda não, está em fase de testes. Logo vai ser implementado.
> > 
> > 
> > Show. Vi que envia saldo por telegram. Ele envia em formato texto ou print?
> 
> Está enviando via Print. O tessaract falha muito. Por enquanto sem condições de um uso confiável. Precisa ajustar bem ele antes de soltar no ar a versão texto.

Pois é. Eu estou com o mesmo problema. Fiz com o tesseract... a maior parte das vezes ele acerta, mas erra bastante. 

De qualquer forma, obrigado. Vou testar o Bot

**Comment by kendikaku** [comment]
Boa noite, o seu bot, quando acontece de desconectar do server aparece aquela mensagem de desconexão e pede para esperar 10 minutos, o seu bot da ok na mensagem e da um reload na página?

**Comment by rzanca** [comment]
> Boa noite, o seu bot, quando acontece de desconectar do server aparece aquela mensagem de desconexão e pede para esperar 10 minutos, o seu bot da ok na mensagem e da um reload na página?

Infelizmente não ocorreu em nenhum dos meus testes e até o momento não 9obtive um feedback sobre.

**Comment by kendikaku** [comment]
> > Boa noite, o seu bot, quando acontece de desconectar do server aparece aquela mensagem de desconexão e pede para esperar 10 minutos, o seu bot da ok na mensagem e da um reload na página?
> 
> Infelizmente não ocorreu em nenhum dos meus testes e até o momento não 9obtive um feedback sobre.

essa versao funcionaria se tivesse 6 contas em VM do google cloud?

**Comment by rzanca** [comment]
> > > Boa noite, o seu bot, quando acontece de desconectar do server aparece aquela mensagem de desconexão e pede para esperar 10 minutos, o seu bot da ok na mensagem e da um reload na página?
> > 
> > 
> > Infelizmente não ocorreu em nenhum dos meus testes e até o momento não 9obtive um feedback sobre.
> 
> essa versao funcionaria se tivesse 6 contas em VM do google cloud?

Sim, mas precisa ser Windows por enquanto

**Comment by deftandre** [comment]
Alguém sabe como proceder quando o chrome atualizou a opção não aparece mais
