### ISSUE TITLE
Não coloca todos os bonecos para trabalhar

### ISSUE THREAD

**Issue by 8driano** [mpcabete/bombcrypto-bot#614]
Galera a maioria das vezes o bot não coloca todos os bonecos para trabalhar, por exemplo: Ele colocou a primeira pagina e depois que ele da o scroll na tela ele só coloca 1 boneco pra trabalhar e os outros verdes são ignorados e ele da scroll novamente e coloca +1 e fica nisso.

**Comment by fguide** [comment]
Você por acaso viu no cmd se ele detecta todos que deveria?

**Comment by 8driano** [comment]
> Você por acaso viu no cmd se ele detecta todos que deveria?

Ele só detecta uma vez só

**Comment by Pedr0hng** [comment]
aqui volta e meia acontece isso, ele detecta mas clicka em um só até o momento não consegui resolver

**Comment by Mytic-Slander** [comment]
No meu caso ele só coloca os 5 primeiros caso esteja com a stamina verde, mas não desce para por os outros para trabalhar. Já tentei de tudo mas não rola para por os outros 10...

**Comment by Pedr0hng** [comment]
Bom pra resolver isso acabei aumentando o tempo de colocar os bombers pra trabalhar e subistitui o "green" por "all" melhor que ficar bomber pra tras kkkkkkkkk
