### ISSUE TITLE
Erro com SandBox

### ISSUE THREAD

**Issue by rxphaa** [mpcabete/bombcrypto-bot#615]
Estou tentando instalar o bot no Windows Sandox porem quanto tento executar o comando pip install -r requirements.txt.
Ele retorna o erro da imagem
![image](https://user-images.githubusercontent.com/97586428/149078570-e6348c5a-7c08-4b84-a4a8-ff62579777b8.png)

**Comment by Hikarusomai** [comment]
try this one of those lines:
`py pip install -r requirements.txt`
or:
`python pip install -r requirements.txt`

**Comment by fguide** [comment]
Você provavelmente esqueceu a opcao abaixo quando instalou o Python:
![image](https://user-images.githubusercontent.com/95459411/149142160-5ba705e5-21c7-4752-81a3-77f55a866683.png)
