### ISSUE TITLE
No issue but request

### ISSUE THREAD

**Issue by MarSap7** [mpcabete/bombcrypto-bot#616]
Someone can help me to do a .exe file from the multiaccount project.
I tried to used pyinstaller, but i dont understand the parameters that i have to put.
I need only the command line string or the .spec file.
Thanks in advance

**Comment by fguide** [comment]
Be careful requesting this kind of help, people might send a fucked up .exe for you...

That said I recommend you 'auto-py-to-exe', here's a quick tutorial which might be helpful:

https://towardsdatascience.com/how-to-easily-convert-a-python-script-to-an-executable-file-exe-4966e253c7e9

**Comment by MarSap7** [comment]
En fact i dont Need the exe, but Only the strong or .spec correct, because i tried to understand already your link, but i m new on python and it's difficult for me

**Comment by fguide** [comment]
Not sure why you're trying to compile it but it seems that going through using the spec file would be the harder way...

auto-py-to-exe needs just to be installed (pip install auto-py-to-exe) and then run on cmd, it'll open an http page where you can compile it "visually"

There's a video on the bottom of that page, you actully don't even need  audio, just follow the quick steps and you'll be good to go.
