### ISSUE TITLE
hd lotado

### ISSUE THREAD

**Issue by clabortoli** [mpcabete/bombcrypto-bot#617]
depois de instalar, e botar pra funcionar, reparei uns dias depois,  que o bot tava comendo muito espaço do hd, minha repartição de 77gb lotou em questão de alguns dias,  queria saber onde é salvo os prints para que eu possa apagar e liberar espaço pra que continue a usar o bot.

**Comment by cristhianbreunig** [comment]
> depois de instalar, e botar pra funcionar, reparei uns dias depois, que o bot tava comendo muito espaço do hd, minha repartição de 77gb lotou em questão de alguns dias, queria saber onde é salvo os prints para que eu possa apagar e liberar espaço pra que continue a usar o bot.

Oi, dá uma olhada na tua partição pra ver o que está usando o espaço do disco.

No bot a única coisa que pode ir "pesando" é o arquivo de log se não me engano (_mas acho que é bem improvável_), se for o caso, você pode apagar as informações de dentro do arquivo (_serve somente para registrar as operações que o bot realizou_)

**Comment by fguide** [comment]
Linux? Teve um caso parecido que resolveram com reboot, infelizmente a pessoa nao informou o que estava fazendo o consumo ser alto.

Tente ver com comando 'du' o que está com maior tamanho, ou simplemente tente um reboot.

**Comment by clabortoli** [comment]
entáo, eu sou usuario windos, e instalei o bot no meu disco com mais espaço, mas ele ta pesando meu disco c: na qual estar instalado o windos,  depois de eu colocar na repartição o bot, eu ativei e deixei rodando, e todo dia reiniciava o pc, mas ai de domingo pra ca, o chrome começou a dizer que estava lotado, limpei o cech e o bot voltou a funcionar, no mesmo dia ele disse que tava lotado, o cech nao tava nem com 1 mg de utilização, ai abri o meu pc, e o disco c/; lotado, limpei tudo que eu podia e consegui liberar 6 gb.  isso domingo, ontem tinha 2 gb e hoje ta lotado de novo

tenho certeza que foi o bot.  por isso queria saber se tem algum jeito de eu descobrir onde é salvo as prints, ou talvez seja um bug sei la.

**Comment by fguide** [comment]
Use alguma ferramenta de analise de disco e descubra onde está o problema.

WinDirStat por exemplo.
