### ISSUE TITLE
Consumo do pc e temperatura dos processadores

### ISSUE THREAD

**Issue by kendikaku** [mpcabete/bombcrypto-bot#618]
Boa tarde
Porque sempre que executo o meu notebook fica com consumo alto e as ventoinhas no máximo? E a temperatura dos processadores por volta de 80 cada núcleo, somente quando executo algo com comando Python, alguém pode ajudar?

**Comment by BBencee** [comment]
I have an old laptop which runs at 100% also with the bot, I have downloaded this CPU limiter: https://mion.yosei.fi/BES/ and lowered the cpu usage of python.exe around -60%. Now the consumption is better and the laptop is quieter.

**Comment by fguide** [comment]
@Japa18244 Por acaso não é o proprio jogo?

Eu não tenho esse problema de consumo, mas sugiro fazer alguns testes com o script e sem, se ralmente for ele tem algumas variáveis que podem estar erradas aí, por exemplo arquitetura de python que vc esta usando, navegador com aceleracao de hardware, etc

**Comment by kendikaku** [comment]
> @Japa18244 Por acaso não é o proprio jogo?
> 
> Eu não tenho esse problema de consumo, mas sugiro fazer alguns testes com o script e sem, se ralmente for ele tem algumas variáveis que podem estar erradas aí, por exemplo arquitetura de python que vc esta usando, navegador com aceleracao de hardware, etc

Já fiz o teste sem estar executando o Python e não fica igual, eu instalei o Python conforme o tópico original mpcabete, tem alguma sugestão que posso tentar?

**Comment by fguide** [comment]
Em teoria é por conta do loop do script, porém tem um pause de 1 segundo no final para previnir isso, mande as configurações do seu PC, memoria, processador, sistema operacional e versao do python com o comando: python -V

**Comment by kendikaku** [comment]
> Em teoria é por conta do loop do script, porém tem um pause de 1 segundo no final para previnir isso, mande as configurações do seu PC, memoria, processador, sistema operacional e versao do python com o comando: python -V

Notebook
I5-1135G7
Memoria Ram 16gb 3200mhz Kingston
Windows 11 (windows 10 tambem fazia a mesma coisa)
Python 3.10.1
Navegador Brave (2 abas, multaccount)

**Comment by fguide** [comment]
É, a config é boa e não deveria dar esse tipo de problema. Eu infelizmente não tenho acesso a Windows para testar, mas posso sugerir algumas coisas:

0 - Você está usando uma versão multiaccount, ou seja, nao é a oficial daqui, então verifique se a versão que você usa tem a seguinte linha no final do arquivo index.py (coloquei só o final da funcao main pra nao ficar muito grande, vc precisa verficar a linha time.sleep(1) se está presente:

(...)
        **time.sleep(1)**



if __name__ == '__main__':


1 - Verificar arquitetura do python e windows, provavelmente o windows é 64 bits, entao vc precisa usar o python 64 bits também.
2 - Trocar versão do python para uma mais baixa, 3.10.0 ou 3.9.x, talvez tenha algum bug com windows e a versão.
3 - Limitar o uso do prython em apenas um core ou colocar prioridade mais baixa, veja o exemplo abaixo que peguei na internet de como fazer alteração de prioridade. Se você escolher a opção 'affinity' é possível selecionar os cores que vc quer utilizar:
![image](https://user-images.githubusercontent.com/95459411/149219345-5f666052-5fb3-4745-a4fa-82e5ab6597b4.png)

A opcao 3 aparentemente pode ser feita com o software mencionado pelo @BBencee, porém seria melhor fazer com recursos do proprio windows como mencionei acima.

**Comment by kendikaku** [comment]
> É, a config é boa e não deveria dar esse tipo de problema. Eu infelizmente não tenho acesso a Windows para testar, mas posso sugerir algumas coisas:
> 
> 0 - Você está usando uma versão multiaccount, ou seja, nao é a oficial daqui, então verifique se a versão que você usa tem a seguinte linha no final do arquivo index.py (coloquei só o final da funcao main pra nao ficar muito grande, vc precisa verficar a linha time.sleep(1) se está presente:
> 
> (...) **time.sleep(1)**
> 
> if **name** == '**main**':
> 
> 1 - Verificar arquitetura do python e windows, provavelmente o windows é 64 bits, entao vc precisa usar o python 64 bits também. 2 - Trocar versão do python para uma mais baixa, 3.10.0 ou 3.9.x, talvez tenha algum bug com windows e a versão. 3 - Limitar o uso do prython em apenas um core ou colocar prioridade mais baixa, veja o exemplo abaixo que peguei na internet de como fazer alteração de prioridade. Se você escolher a opção 'affinity' é possível selecionar os cores que vc quer utilizar: ![image](https://user-images.githubusercontent.com/95459411/149219345-5f666052-5fb3-4745-a4fa-82e5ab6597b4.png)
> 
> A opcao 3 aparentemente pode ser feita com o software mencionado pelo @BBencee, porém seria melhor fazer com recursos do proprio windows como mencionei acima.

# -*- coding: utf-8 -*-    
from time import sleep
from src.main import run
from src.main_multi_account import runMultiAccount
from src.utils.config import loadConfigsFromFile
from src.bot.logger import logger, exception

config = loadConfigsFromFile()
run_multi_account = config['multiples_accounts_same_monitor']['enable']

logger('Bombcrypto BOT starting', color='yellow')
while True:
    try:
        if run_multi_account:
            logger('Running bot for MULTI ACCOUNT ON SAME MONITOR', color='cyan')
            runMultiAccount()
        else:
            logger('Running bot', color='cyan')
            run()
    except KeyboardInterrupt:
        break
    except Exception as e:
        logger('Bombcrypto BOT crashed... restarting in 5 seconds.', color='red')
        logger("Exception: %s" % (str(e)), color='red')
        exception(e)
        sleep(5)
        continue

segue tudo oque tem no Index.py

mas eu usava a oficial e mesmo assim o cooler do processador ficava no maximo tambem, 

segue o multaccount que estou usando https://github.com/mpcabete/bombcrypto-bot/issues/587

**Comment by fguide** [comment]
Aparentemente falta o sleep no final mesmo, vc pode tentar adicionar conforme abaixo e testar:

```
# -*- coding: utf-8 -*-    
from time import sleep
from src.main import run
from src.main_multi_account import runMultiAccount
from src.utils.config import loadConfigsFromFile
from src.bot.logger import logger, exception

config = loadConfigsFromFile()
run_multi_account = config['multiples_accounts_same_monitor']['enable']

logger('Bombcrypto BOT starting', color='yellow')
while True:
    try:
        if run_multi_account:
            logger('Running bot for MULTI ACCOUNT ON SAME MONITOR', color='cyan')
            runMultiAccount()
        else:
            logger('Running bot', color='cyan')
            run()
    except KeyboardInterrupt:
        break
    except Exception as e:
        logger('Bombcrypto BOT crashed... restarting in 5 seconds.', color='red')
        logger("Exception: %s" % (str(e)), color='red')
        exception(e)
        sleep(5)
        continue
    sleep(1)
```

**Comment by kendikaku** [comment]
> Aparentemente falta o sleep no final mesmo, vc pode tentar adicionar conforme abaixo e testar:
> 
> ```
> # -*- coding: utf-8 -*-    
> from time import sleep
> from src.main import run
> from src.main_multi_account import runMultiAccount
> from src.utils.config import loadConfigsFromFile
> from src.bot.logger import logger, exception
> 
> config = loadConfigsFromFile()
> run_multi_account = config['multiples_accounts_same_monitor']['enable']
> 
> logger('Bombcrypto BOT starting', color='yellow')
> while True:
>     try:
>         if run_multi_account:
>             logger('Running bot for MULTI ACCOUNT ON SAME MONITOR', color='cyan')
>             runMultiAccount()
>         else:
>             logger('Running bot', color='cyan')
>             run()
>     except KeyboardInterrupt:
>         break
>     except Exception as e:
>         logger('Bombcrypto BOT crashed... restarting in 5 seconds.', color='red')
>         logger("Exception: %s" % (str(e)), color='red')
>         exception(e)
>         sleep(5)
>         continue
>     sleep(1)
> ```

Fiz todos os passos que você me falou, e parece que continua na mesma, tipo a temperatura do processador fica em 70 a 85 variando, somente com o Python ativado.

**Comment by kendikaku** [comment]
![image](https://user-images.githubusercontent.com/97619573/149223585-d64bf71e-b757-4c0d-9f17-5db1ab76d89d.png)

nao sei mais oque fazer, olha isso, bate quase 100 graus, imagina isso a longo prazo vai fuder meu notebook.

**Comment by fguide** [comment]
Olha, dentro da pasta src tem o arquivo 'main_multi_account.py', aparentemente o sleep está fora de identação, tente modificiar ele da forma abaixo.

Seria interessante tb refazer um teste com o bot original só para ter certeza...

```
import time
import sys
import pygetwindow

from src.utils.number import addRandomness
import src.bot.logger as Log
import src.env as env
import src.bot.heroes as Heroes
import src.bot.login as Auth
import src.bot.action as Action

def runMultiAccount():
    time.sleep(5)
    intervals = env.cfg['time_intervals']

    windows = []
    title = env.multi_account_same_monitor['window_contains_title']

    Log.logger('🆗 Start')
    Log.logger('Searching for windows with contains title: {}'.format(title), color='yellow')

    for w in pygetwindow.getWindowsWithTitle(title):
        windows.append({
            "window": w,
            "login" : 0,
            "heroes" : 0,
            "new_map" : 0,
            "refresh_heroes" : 0
        })

    Log.logger('Found {} window(s):'.format(len(windows)), color='cyan')
    for index, last in enumerate(windows):
        Log.logger('{} -> {}'.format(index+1, last['window'].title), color='cyan')

    if len(windows) == 0:
        Log.logger('Exiting because dont have windows contains "{}" title'.format(title), color='red')
        exit()

    while True:
        now = time.time()
        
        for last in windows:
            env.window_object = last["window"]
            Log.logger('Client active window: {}'.format(last['window'].title), color='green')
            time.sleep(5)
            
            if now - last["login"] > addRandomness(intervals['check_for_login'] * 60):
                Action.activeWindow()
                sys.stdout.flush()
                last["login"] = now
                Auth.login()

            if now - last["heroes"] > addRandomness(intervals['send_heroes_for_work'] * 60):
                Action.activeWindow()
                last["heroes"] = now
                Heroes.refreshHeroes()

            if now - last["new_map"] > intervals['check_for_new_map_button']:
                Action.activeWindow()
                last["new_map"] = now
                Action.goToNextMap()

            if now - last["refresh_heroes"] > addRandomness( intervals['refresh_heroes_positions'] * 60):
                Action.activeWindow()
                last["refresh_heroes"] = now
                Action.refreshHeroesPositions()

	Log.logger(None, progress_indicator=True)
	sys.stdout.flush()
	time.sleep(1)
```

**Comment by kendikaku** [comment]
> Olha, dentro da pasta src tem o arquivo 'main_multi_account.py', aparentemente o sleep está fora de identação, tente modificiar ele da forma abaixo.
> 
> Seria interessante tb refazer um teste com o bot original só para ter certeza...
> 
> ```
> import time
> import sys
> import pygetwindow
> 
> from src.utils.number import addRandomness
> import src.bot.logger as Log
> import src.env as env
> import src.bot.heroes as Heroes
> import src.bot.login as Auth
> import src.bot.action as Action
> 
> def runMultiAccount():
>     time.sleep(5)
>     intervals = env.cfg['time_intervals']
> 
>     windows = []
>     title = env.multi_account_same_monitor['window_contains_title']
> 
>     Log.logger('🆗 Start')
>     Log.logger('Searching for windows with contains title: {}'.format(title), color='yellow')
> 
>     for w in pygetwindow.getWindowsWithTitle(title):
>         windows.append({
>             "window": w,
>             "login" : 0,
>             "heroes" : 0,
>             "new_map" : 0,
>             "refresh_heroes" : 0
>         })
> 
>     Log.logger('Found {} window(s):'.format(len(windows)), color='cyan')
>     for index, last in enumerate(windows):
>         Log.logger('{} -> {}'.format(index+1, last['window'].title), color='cyan')
> 
>     if len(windows) == 0:
>         Log.logger('Exiting because dont have windows contains "{}" title'.format(title), color='red')
>         exit()
> 
>     while True:
>         now = time.time()
>         
>         for last in windows:
>             env.window_object = last["window"]
>             Log.logger('Client active window: {}'.format(last['window'].title), color='green')
>             time.sleep(5)
>             
>             if now - last["login"] > addRandomness(intervals['check_for_login'] * 60):
>                 Action.activeWindow()
>                 sys.stdout.flush()
>                 last["login"] = now
>                 Auth.login()
> 
>             if now - last["heroes"] > addRandomness(intervals['send_heroes_for_work'] * 60):
>                 Action.activeWindow()
>                 last["heroes"] = now
>                 Heroes.refreshHeroes()
> 
>             if now - last["new_map"] > intervals['check_for_new_map_button']:
>                 Action.activeWindow()
>                 last["new_map"] = now
>                 Action.goToNextMap()
> 
>             if now - last["refresh_heroes"] > addRandomness( intervals['refresh_heroes_positions'] * 60):
>                 Action.activeWindow()
>                 last["refresh_heroes"] = now
>                 Action.refreshHeroesPositions()
> 
> 	Log.logger(None, progress_indicator=True)
> 	sys.stdout.flush()
> 	time.sleep(1)
> ```

Parcialmente solucionado,
Baixei o throttlestop e desativei o turbo dessa merda, agora não passa de 50 graus.

Olhei dentro dessa pasta src e tem o sleep da forma que você me passou.

**Comment by fguide** [comment]
> > Olha, dentro da pasta src tem o arquivo 'main_multi_account.py', aparentemente o sleep está fora de identação, tente modificiar ele da forma abaixo.
> > Seria interessante tb refazer um teste com o bot original só para ter certeza...
> > ```
> > import time
> > import sys
> > import pygetwindow
> > 
> > from src.utils.number import addRandomness
> > import src.bot.logger as Log
> > import src.env as env
> > import src.bot.heroes as Heroes
> > import src.bot.login as Auth
> > import src.bot.action as Action
> > 
> > def runMultiAccount():
> >     time.sleep(5)
> >     intervals = env.cfg['time_intervals']
> > 
> >     windows = []
> >     title = env.multi_account_same_monitor['window_contains_title']
> > 
> >     Log.logger('🆗 Start')
> >     Log.logger('Searching for windows with contains title: {}'.format(title), color='yellow')
> > 
> >     for w in pygetwindow.getWindowsWithTitle(title):
> >         windows.append({
> >             "window": w,
> >             "login" : 0,
> >             "heroes" : 0,
> >             "new_map" : 0,
> >             "refresh_heroes" : 0
> >         })
> > 
> >     Log.logger('Found {} window(s):'.format(len(windows)), color='cyan')
> >     for index, last in enumerate(windows):
> >         Log.logger('{} -> {}'.format(index+1, last['window'].title), color='cyan')
> > 
> >     if len(windows) == 0:
> >         Log.logger('Exiting because dont have windows contains "{}" title'.format(title), color='red')
> >         exit()
> > 
> >     while True:
> >         now = time.time()
> >         
> >         for last in windows:
> >             env.window_object = last["window"]
> >             Log.logger('Client active window: {}'.format(last['window'].title), color='green')
> >             time.sleep(5)
> >             
> >             if now - last["login"] > addRandomness(intervals['check_for_login'] * 60):
> >                 Action.activeWindow()
> >                 sys.stdout.flush()
> >                 last["login"] = now
> >                 Auth.login()
> > 
> >             if now - last["heroes"] > addRandomness(intervals['send_heroes_for_work'] * 60):
> >                 Action.activeWindow()
> >                 last["heroes"] = now
> >                 Heroes.refreshHeroes()
> > 
> >             if now - last["new_map"] > intervals['check_for_new_map_button']:
> >                 Action.activeWindow()
> >                 last["new_map"] = now
> >                 Action.goToNextMap()
> > 
> >             if now - last["refresh_heroes"] > addRandomness( intervals['refresh_heroes_positions'] * 60):
> >                 Action.activeWindow()
> >                 last["refresh_heroes"] = now
> >                 Action.refreshHeroesPositions()
> > 
> > 	Log.logger(None, progress_indicator=True)
> > 	sys.stdout.flush()
> > 	time.sleep(1)
> > ```
> 
> Parcialmente solucionado, Baixei o throttlestop e desativei o turbo dessa merda, agora não passa de 50 graus.
> 
> Olhei dentro dessa pasta src e tem o sleep da forma que você me passou.

SIm, o sleep está lá, porém o alinhamento dele está incorreto, deveria ficar na mesma coluna do while True: acima

**Comment by kendikaku** [comment]
> > > Olha, dentro da pasta src tem o arquivo 'main_multi_account.py', aparentemente o sleep está fora de identação, tente modificiar ele da forma abaixo.
> > > Seria interessante tb refazer um teste com o bot original só para ter certeza...
> > > ```
> > > import time
> > > import sys
> > > import pygetwindow
> > > 
> > > from src.utils.number import addRandomness
> > > import src.bot.logger as Log
> > > import src.env as env
> > > import src.bot.heroes as Heroes
> > > import src.bot.login as Auth
> > > import src.bot.action as Action
> > > 
> > > def runMultiAccount():
> > >     time.sleep(5)
> > >     intervals = env.cfg['time_intervals']
> > > 
> > >     windows = []
> > >     title = env.multi_account_same_monitor['window_contains_title']
> > > 
> > >     Log.logger('🆗 Start')
> > >     Log.logger('Searching for windows with contains title: {}'.format(title), color='yellow')
> > > 
> > >     for w in pygetwindow.getWindowsWithTitle(title):
> > >         windows.append({
> > >             "window": w,
> > >             "login" : 0,
> > >             "heroes" : 0,
> > >             "new_map" : 0,
> > >             "refresh_heroes" : 0
> > >         })
> > > 
> > >     Log.logger('Found {} window(s):'.format(len(windows)), color='cyan')
> > >     for index, last in enumerate(windows):
> > >         Log.logger('{} -> {}'.format(index+1, last['window'].title), color='cyan')
> > > 
> > >     if len(windows) == 0:
> > >         Log.logger('Exiting because dont have windows contains "{}" title'.format(title), color='red')
> > >         exit()
> > > 
> > >     while True:
> > >         now = time.time()
> > >         
> > >         for last in windows:
> > >             env.window_object = last["window"]
> > >             Log.logger('Client active window: {}'.format(last['window'].title), color='green')
> > >             time.sleep(5)
> > >             
> > >             if now - last["login"] > addRandomness(intervals['check_for_login'] * 60):
> > >                 Action.activeWindow()
> > >                 sys.stdout.flush()
> > >                 last["login"] = now
> > >                 Auth.login()
> > > 
> > >             if now - last["heroes"] > addRandomness(intervals['send_heroes_for_work'] * 60):
> > >                 Action.activeWindow()
> > >                 last["heroes"] = now
> > >                 Heroes.refreshHeroes()
> > > 
> > >             if now - last["new_map"] > intervals['check_for_new_map_button']:
> > >                 Action.activeWindow()
> > >                 last["new_map"] = now
> > >                 Action.goToNextMap()
> > > 
> > >             if now - last["refresh_heroes"] > addRandomness( intervals['refresh_heroes_positions'] * 60):
> > >                 Action.activeWindow()
> > >                 last["refresh_heroes"] = now
> > >                 Action.refreshHeroesPositions()
> > > 
> > > 	Log.logger(None, progress_indicator=True)
> > > 	sys.stdout.flush()
> > > 	time.sleep(1)
> > > ```
> > 
> > 
> > Parcialmente solucionado, Baixei o throttlestop e desativei o turbo dessa merda, agora não passa de 50 graus.
> > Olhei dentro dessa pasta src e tem o sleep da forma que você me passou.
> 
> SIm, o sleep está lá, porém o alinhamento dele está incorreto, deveria ficar na mesma coluna do while True: acima

OK,
efetuei a alteração

**Comment by fguide** [comment]
OK, tente rodar um pouco sem a ferramenta de limite e veja se resolve, nos avise aqui dai podemos avisar ao dev para ajustar a versão dele.

**Comment by kendikaku** [comment]
> OK, tente rodar um pouco sem a ferramenta de limite e veja se resolve, nos avise aqui dai podemos avisar ao dev para ajustar a versão dele.

Tentei rodar e não foi, com essa alteração sua o bot abre e fecha na mesma hora, depois coloquei o arquivo original voltou a funcionar

**Comment by fguide** [comment]
Abre a janela do CMD e executa por lá, dai nao vai fechar e vc vai poder ver qual o erro

**Comment by kendikaku** [comment]
> 

![image](https://user-images.githubusercontent.com/97619573/149233899-225425ef-c896-4740-8563-0aa69ac8af9e.png)

segue erro.

**Comment by fguide** [comment]
Erro meu, usei TAB no lugar de espaço :rofl segue;

```
import time
import sys
import pygetwindow

from src.utils.number import addRandomness
import src.bot.logger as Log
import src.env as env
import src.bot.heroes as Heroes
import src.bot.login as Auth
import src.bot.action as Action

def runMultiAccount():
    time.sleep(5)
    intervals = env.cfg['time_intervals']

    windows = []
    title = env.multi_account_same_monitor['window_contains_title']

    Log.logger('🆗 Start')
    Log.logger('Searching for windows with contains title: {}'.format(title), color='yellow')

    for w in pygetwindow.getWindowsWithTitle(title):
        windows.append({
            "window": w,
            "login" : 0,
            "heroes" : 0,
            "new_map" : 0,
            "refresh_heroes" : 0
        })

    Log.logger('Found {} window(s):'.format(len(windows)), color='cyan')
    for index, last in enumerate(windows):
        Log.logger('{} -> {}'.format(index+1, last['window'].title), color='cyan')

    if len(windows) == 0:
        Log.logger('Exiting because dont have windows contains "{}" title'.format(title), color='red')
        exit()

    while True:
        now = time.time()
        
        for last in windows:
            env.window_object = last["window"]
            Log.logger('Client active window: {}'.format(last['window'].title), color='green')
            time.sleep(5)
            
            if now - last["login"] > addRandomness(intervals['check_for_login'] * 60):
                Action.activeWindow()
                sys.stdout.flush()
                last["login"] = now
                Auth.login()

            if now - last["heroes"] > addRandomness(intervals['send_heroes_for_work'] * 60):
                Action.activeWindow()
                last["heroes"] = now
                Heroes.refreshHeroes()

            if now - last["new_map"] > intervals['check_for_new_map_button']:
                Action.activeWindow()
                last["new_map"] = now
                Action.goToNextMap()

            if now - last["refresh_heroes"] > addRandomness( intervals['refresh_heroes_positions'] * 60):
                Action.activeWindow()
                last["refresh_heroes"] = now
                Action.refreshHeroesPositions()

    Log.logger(None, progress_indicator=True)
    sys.stdout.flush()
    time.sleep(1)
```

**Comment by kendikaku** [comment]
> Erro meu, usei TAB no lugar de espaço :rofl segue;
> 
> ```
> import time
> import sys
> import pygetwindow
> 
> from src.utils.number import addRandomness
> import src.bot.logger as Log
> import src.env as env
> import src.bot.heroes as Heroes
> import src.bot.login as Auth
> import src.bot.action as Action
> 
> def runMultiAccount():
>     time.sleep(5)
>     intervals = env.cfg['time_intervals']
> 
>     windows = []
>     title = env.multi_account_same_monitor['window_contains_title']
> 
>     Log.logger('🆗 Start')
>     Log.logger('Searching for windows with contains title: {}'.format(title), color='yellow')
> 
>     for w in pygetwindow.getWindowsWithTitle(title):
>         windows.append({
>             "window": w,
>             "login" : 0,
>             "heroes" : 0,
>             "new_map" : 0,
>             "refresh_heroes" : 0
>         })
> 
>     Log.logger('Found {} window(s):'.format(len(windows)), color='cyan')
>     for index, last in enumerate(windows):
>         Log.logger('{} -> {}'.format(index+1, last['window'].title), color='cyan')
> 
>     if len(windows) == 0:
>         Log.logger('Exiting because dont have windows contains "{}" title'.format(title), color='red')
>         exit()
> 
>     while True:
>         now = time.time()
>         
>         for last in windows:
>             env.window_object = last["window"]
>             Log.logger('Client active window: {}'.format(last['window'].title), color='green')
>             time.sleep(5)
>             
>             if now - last["login"] > addRandomness(intervals['check_for_login'] * 60):
>                 Action.activeWindow()
>                 sys.stdout.flush()
>                 last["login"] = now
>                 Auth.login()
> 
>             if now - last["heroes"] > addRandomness(intervals['send_heroes_for_work'] * 60):
>                 Action.activeWindow()
>                 last["heroes"] = now
>                 Heroes.refreshHeroes()
> 
>             if now - last["new_map"] > intervals['check_for_new_map_button']:
>                 Action.activeWindow()
>                 last["new_map"] = now
>                 Action.goToNextMap()
> 
>             if now - last["refresh_heroes"] > addRandomness( intervals['refresh_heroes_positions'] * 60):
>                 Action.activeWindow()
>                 last["refresh_heroes"] = now
>                 Action.refreshHeroesPositions()
> 
>     Log.logger(None, progress_indicator=True)
>     sys.stdout.flush()
>     time.sleep(1)
> ```

deu certo, funcionou, mas o consumo de energia do python ainda se mantem alto, acho que é problema do notebook mesmo, vou deixar limitado a frequencia do processador.

**Comment by KorlashKun** [comment]
eu tenho o problema bem parecido, depois de 1h, 1h:30 rodando o script a minha maquina chegava a desligar, provavelmente pelas altas temperaturas, vou testar as coisas acima e ver se resolve meu problema. grato

**Comment by kendikaku** [comment]
> eu tenho o problema bem parecido, depois de 1h, 1h:30 rodando o script a minha maquina chegava a desligar, provavelmente pelas altas temperaturas, vou testar as coisas acima e ver se resolve meu problema. grato

Alguma solução? A única alternativa que tive para diminuir foi limitar o clock do meu processador,

**Comment by fguide** [comment]
Infelizmente eu acho que está relacionado ao jogo mesmo, nao ao script.  Como disse é UNITY, tem vários tópicos na internet com problemas similares.

Fiz um teste hoje, deixei apenas o jogo rodando por 10 min em uma maquina nova, resultado: 

      Adapter: ISA adapter
      Package id 0:  +91.0°C  (high = +84.0°C, crit = +100.0°C)
      Core 0:        +91.0°C  (high = +84.0°C, crit = +100.0°C)
      Core 1:        +90.0°C  (high = +84.0°C, crit = +100.0°C)

Ok, liguei o script por mais 10 minutos, não houve alteração. Fechei o navegador (com script aberto), 5 segundos depois:

      Adapter: ISA adapter
      Package id 0:  +61.0°C  (high = +84.0°C, crit = +100.0°C)
      Core 0:        +61.0°C  (high = +84.0°C, crit = +100.0°C)
      Core 1:        +57.0°C  (high = +84.0°C, crit = +100.0°C)

Para ter certeza que o "problema" está no jogo, setei firefox apenas para o core 0:

        -- taskset 0x1 firefox &
        [1] 552824
        -- taskset -cp 552824
        pid 552824's current affinity list: 0

Feito isso, veja a diferença de temperatura dos cores:

          Adapter: ISA adapter
          Package id 0:  +91.0°C  (high = +84.0°C, crit = +100.0°C)
          Core 0:        +91.0°C  (high = +84.0°C, crit = +100.0°C)
          Core 1:        +67.0°C  (high = +84.0°C, crit = +100.0°C)

E em consumo tb, core 0 esta em 100% e os demais IDLE.

**Comment by KorlashKun** [comment]
> > eu tenho o problema bem parecido, depois de 1h, 1h:30 rodando o script a minha maquina chegava a desligar, provavelmente pelas altas temperaturas, vou testar as coisas acima e ver se resolve meu problema. grato
> 
> Alguma solução? A única alternativa que tive para diminuir foi limitar o clock do meu processador,

só parou depois de eu trocar a pasta térmica do meu processador, agora ta suave o bot mas mesmo assim ele anda exigindo de mais do meu processador
