### ISSUE TITLE
Don't work on VPS Google Server 

### ISSUE THREAD

**Issue by WantTo1** [mpcabete/bombcrypto-bot#619]
When i close RDP connection and minimize RDP. Bot don't work, idk how to fix it. As i'm understand that rdp connection taking my mouse and use.

**Comment by fguide** [comment]
When you close the RDP connection the session gets locked.

Please check this: https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html

Alternatively, use a protocol other than RDP to connect

**Comment by WantTo1** [comment]
No i using google cloud. Connection does not close. What protocol would you recommend?

**Comment by fguide** [comment]
> No i using google cloud. Connection does not close. What protocol would you recommend?

No, it does not close, it gets **locked**, that's why I sent the link, there's a suggestion of a batch file to disconnect and avoid it.

I recommend VNC as it's an open source protocol.

**Comment by WantTo1** [comment]
This https://www.realvnc.com/en/connect/download/viewer/ ?

**Comment by fguide** [comment]
Yes, that would work.

**Comment by WantTo1** [comment]
I can't connect)

**Comment by WantTo1** [comment]
Using external ip

**Comment by fguide** [comment]
Probably you need to enable cloud connection:

https://help.realvnc.com/hc/en-us/articles/360002249737-All-About-Cloud-Connections/

**Comment by brunobaco** [comment]
Try to connect using the Chrome Remote Desktop. I was with issues like that e this fixed!!! https://cloud.google.com/compute/docs/instances/connecting-to-windows#chrome-remote-desktop

**Comment by WantTo1** [comment]
> Try to connect using the Chrome Remote Desktop. I was with issues like that e this fixed!!! https://cloud.google.com/compute/docs/instances/connecting-to-windows#chrome-remote-desktop

Thanks, but how to change resolution on this remote connection?

**Comment by fguide** [comment]
As per https://cloud.google.com/compute/docs/instances/enable-instance-virtual-display you need to enable display

**Comment by brunobaco** [comment]
> 

You cant. I tried a lot, but those VMs hasn't a video hardware. But using Chrome Remote, I could to use macros. That are the only resolutions that I have.
![image](https://user-images.githubusercontent.com/53538872/149446418-b696420e-20b8-462b-a498-e98c8a8a83f0.png)

**Comment by WantTo1** [comment]
> > 
> 
> You cant. I tried a lot, but those VMs hasn't a video hardware. But using Chrome Remote, I could to use macros. That are the only resolutions that I have. ![image](https://user-images.githubusercontent.com/53538872/149446418-b696420e-20b8-462b-a498-e98c8a8a83f0.png)

Can you write to me a telegram because I still can't find a solution @WannaParadise

**Comment by fguide** [comment]
Once more:

![image](https://user-images.githubusercontent.com/95459411/149539525-b6e370be-8d3b-4f97-9645-e2737226e03c.png)

**Comment by WantTo1** [comment]
> Once more:
> 
> ![image](https://user-images.githubusercontent.com/95459411/149539525-b6e370be-8d3b-4f97-9645-e2737226e03c.png)

Thanks! Now it work, last question when you closing vnc viewer the program will work?

**Comment by fguide** [comment]
Yes, it will!
