### ISSUE TITLE
The bot runs but doesn't move the pointer

### ISSUE THREAD

**Issue by Zek92** [mpcabete/bombcrypto-bot#62]
Dear developer,

first of all thanks a lot for all the efforts you put in this, I see the bot is being extremely helpful for a lot of people. Unfortunately, even if the installation went smoothly and I am able to run the bot, the pointer is standing still on the open website app.bombcrypto.io . I can see the pointer blinking a little bit every now and then, I guess that is related to the bot running, but it does not move. I am using both monitor and Chrome at 100% resolution.
![PrintCMD](https://user-images.githubusercontent.com/95019197/143404722-d2aa3114-0baa-4a67-bd1d-4235a64db483.JPG)

I attached the screen from the CMD in case that may be helpful.

Thanks a lot in advance!

**Comment by cristhianbreunig** [comment]
Hey, I'm not the developer of this project, but i think that i can help you, please check with version of python are you running with this command: `python --version`

I had problems with multiple Python versions on my computer and i needed to install Python 3.10 and run the project with this command: `python3.10 index.py`

I hope this help you.

**Comment by Zek92** [comment]
Hi Cristhian,

Thanks a lot for your advice! I installed Python 3.10, I will try your command as soon as the game is back online.

I will let you know if it solved the problem.

**Comment by Zek92** [comment]
![Python310](https://user-images.githubusercontent.com/95019197/143548516-40024cf9-6ed8-402e-b9f6-1f8943cf8229.JPG)

Update: The suggestion of Cristhian did not work. The "python --version" command showed that I am using the 3.10 version but the "python3.10 index.py" command was not recognized. I keep having the same issue with the bot

**Comment by andremoller3** [comment]
same problem here

**Comment by mpcabete** [comment]
@Zek92  try using the command python3 index.py

**Comment by mpcabete** [comment]
It seems that the bot is running, but it is not recognizing the buttons to click. Check if the zoom in the browser is at 100%

**Comment by Zek92** [comment]
Hi mpcabete, thanks for your answer. The browser is at 100% zoom and the monitor at 100% resolution.

Any other idea?

**Comment by mpcabete** [comment]
try replacing some of the images in the target folder. just to make sure it works test it first with the [go-back-arrow.png](https://github.com/mpcabete/bombcrypto-bot/blob/main/targets/go-back-arrow.png). if you start the bot in the treasure hunt screen it should click the button if it works.

**Comment by Zek92** [comment]
Thanks a lot for your suggestion. I replaced almost all the in-game target images and that seemed to change something since finally the pointer is moving. Problem is that it is not moving correctly, it has a weird pathing. For example: if I start the bot when I am in the hero list, instead of scrolling down the list of heroes the pointer goes to the right side of the screen and it start scrolling down the web page. In treasure hunt instead it doesn't recognize that I am in treasure hunt and it keeps trying to send heroes to work.

**Comment by mpcabete** [comment]
Probably the bot scrolling the web page is a problem with an false positive in the commom-text.png image, it uses the commom text to find the last hero, so it can click in it and scroll up.
Try increasing it's threshold or replacing the image
