### ISSUE TITLE
só chama para trabalho uma vez

### ISSUE THREAD

**Issue by famigomes** [mpcabete/bombcrypto-bot#621]
boa noite, preciso de uma ajuda, sou leigo em programação, mas consegui instalar corretamente o bot. ele começa funcionando tudo normal, chama para o primeiro trabalho tudo normal, mas quando os heroes se cansam na primeira tela, o mouse não mexe mais, e o bot não volta para a lista de heroes para buscar novos heroes que estejam bons para trabalhar. segue a tela do bot na hora que fica tudo parado.
![err bomb](https://user-images.githubusercontent.com/97640710/149240172-23cdb152-b034-4c57-b0ab-6b3ce3117106.png)

**Comment by jeffersonveloso** [comment]
Boa noite, verifica se a pasta do script não contem bomcrypto no nome, se isso estiver acontecendo quebra a execução do script pq detecta a pasta como uma janela do jogo.

**Comment by famigomes** [comment]
Bom dia, coloquei outro nome

**Comment by esnunes1** [comment]
olá pessoal vocês conseguiram arrumar? ou sabe me ajudar? o nome da pasta está como somente bomb mas as vidas ficam verdes alguns com 100% má ele não poe pra trabalhar. grato
