### ISSUE TITLE
Problema ao iniciar o bot

### ISSUE THREAD

**Issue by eoiluminado** [mpcabete/bombcrypto-bot#623]
Ao iniciar o bot e deixar ele na pagina do jogo, o cursor vai totalmente para a direita da minha tela e não executa nenhuma ação. 

Oque fazer?

Obrigado!

**Comment by fguide** [comment]
Usa dois monitores? Resolucao? Escala do monitor? Zoom do navegador?

**Comment by john-pelegrini** [comment]
meu bot esta com o mesmo problema, mesmo desconectando a segunda tela não muda. resolucão 1366x768 (maximo)  zoom do navegador 100% 90% não funcionou escala do monitor do notebook em 100% e 125% tbm não funcionou
