### ISSUE TITLE
bombcrypto API endpoints

### ISSUE THREAD

**Issue by xclover0** [mpcabete/bombcrypto-bot#624]
hello, anyone have endpoints of bombcrypto's API (https://api.bombcrypto.io)? I just want to create bcoin tracker using its API. thank you.

**Comment by fguide** [comment]
https://api.bombcrypto.io/ccu/ try to crawl it, upfront it just got the server status, not sure what else you'd need.

**Comment by fguide** [comment]
Oh, BTW I forgto to mention, if you are looking for PRICE monitoring, bombcrypto itself is using CoinGecko's API to do it, so...

**Comment by cleitonleonel** [comment]
> hello, anyone have endpoints of bombcrypto's API (https://api.bombcrypto.io)? I just want to create bcoin tracker using its API. thank you.

Encontrei alguns links interessantes... 

https://claim.bombcrypto.io/claim-orders?&limit=1&offset=0&walletAddress=0x869456d33a8ee50d15aa72d2bea8b3ba699bd0bd 
Sendo o valor de walletAddress é a hash da conta da carteira metamask o resultado é o seguinte : 
```{
data: {
items: [
{
id: 3438066,
status: "successful",
request_id: "Qwoiw036uc71Zgglo6gG0SIuDjgmdU2r",
wallet_address: "0x869456d33a8ee50d15aa72d2bea8b3ba699bd0bd",
amount_of_bcoin: 47.16554,
amount_of_bcoin_claimed: 42.448986,
tx_hash: "0xfec9ed3702b6275a3238feb0e0b66165cc35ace2f8b3a6ed770eb4e4707dff65",
claimed_at: "2022-02-02T16:19:29.587481Z"
}
],
total: 11
}
}

**Comment by cleitonleonel** [comment]
https://claim.bombcrypto.io/claim-orders?&limit=10&offset=0 pega todas as contas...

**Comment by cleitonleonel** [comment]
https://claim.bombcrypto.io/bhero/claim-orders?&limit=1&offset=0&walletAddress=0x869456d33a8ee50d15aa72d2bea8b3ba699bd0bd

**Comment by cleitonleonel** [comment]
https://api.coingecko.com/api/v3/coins/bomber-coin

**Comment by cleitonleonel** [comment]
https://bombcryptosimulator.com/apidata.txt

**Comment by kojakeugenio** [comment]
Do you have the endpoints for bcoin that is still in the chest?

**Comment by inscyo** [comment]
api for unclaim bcoin?

**Comment by kojakeugenio** [comment]
> api for unclaim bcoin?

Yes..

**Comment by inscyo** [comment]
i ask that on discord months ago admin said that the api for that is not public

**Comment by inscyo** [comment]
i ask that question on discord months ago admin said that the api for that is not public
