### ISSUE TITLE
Problema ao rodar no Macbook Pro 2019

### ISSUE THREAD

**Issue by danielapassos** [mpcabete/bombcrypto-bot#625]
Como posso fazer rodar no Macbook Pro 2019? Melhor maneira de ajustar imagens seria com screenshot mesmo?

**Comment by fguide** [comment]
Você tentou instalar? Teve algum problema?

**Comment by Pedrobertucci** [comment]
estou com a mesma duvida, nao consigo aqui rodar o bot, mouse nunca acerta o ponto certo xD, troquei de resolucao algumas vezes para ver e nada de dar certo =(

**Comment by danielapassos** [comment]
> Você tentou instalar? Teve algum problema?

Sim, instalei e teve problema. Creio que não rode por conta da resolução.

**Comment by fguide** [comment]
Tente essa versão:

https://github.com/MatheusHAS/bombcrypto-bot

**Comment by Pedrobertucci** [comment]
Buenas @fguide, maninho, tentei aqui e nao consegui, consegue algum conselho? basicamente o ponteiro do mouse nunca acerta no lugar certo, tenho no mac o tamanho normal 1440x900 que fica por default, mesmo assim nao funciona, ja troquei para enable o is_retina e nao consegui ainda... o bot tb fecha a guia do browser do jogo, acho estranho... teve alguma destas experiencias.

**Comment by fguide** [comment]
@Pedrobertucci  Nessa resolucao deveria funcionar normalmente pois é abaixo de 1920x1080, veja se nao tem zoom no noavegador, ou o scaling do mac, eles precisam estar em 100%

**Comment by Pedrobertucci** [comment]
@fguide poise, eu tentei aqui e nao deu certo, resolucao esta normal, segue os prints a baixo para talvez me ajudar =D
<img width="1440" alt="Screenshot 2022-01-15 at 15 46 50" src="https://user-images.githubusercontent.com/12385019/149628023-40a64e79-c506-49b7-bfff-b48012fc7bf8.png">

<img width="663" alt="Screenshot 2022-01-15 at 15 45 12" src="https://user-images.githubusercontent.com/12385019/149628026-24db1da2-5874-4c9e-a4c8-a4a8f473933c.png">

**Comment by Pedrobertucci** [comment]
Basicamente fica assim sempre o terminal.
<img width="563" alt="Screenshot 2022-01-15 at 15 52 50" src="https://user-images.githubusercontent.com/12385019/149628262-6900f14e-c409-4a7b-a3c5-af371fffa532.png">

**Comment by fguide** [comment]
Infelizmente nao tenho exp com MAC, mas talvez vc pode tentar substituir as imagens na pasta target e ver se resolve...
