### ISSUE TITLE
Rip Careful everyone!! 

### ISSUE THREAD

**Issue by zorelix69** [mpcabete/bombcrypto-bot#626]
![image](https://user-images.githubusercontent.com/97457948/149289634-5064f0b7-2787-462a-83c9-99d572a16619.png)

careful devs starting to punish us! i hope new mechanics comes on the bot so we dont have to worry about this.

**Comment by Igorlegacy** [comment]
bot não é hack/cheat... autoclickers e macro ainda continuam liberados desde que não altere o funcionamento do jogo.

**Comment by zorelix69** [comment]
![image](https://user-images.githubusercontent.com/97457948/149298206-8250518a-1c3d-4860-afa3-5b09fa8483ef.png)

im worried about this one.

**Comment by AllanHBC** [comment]
> ![image](https://user-images.githubusercontent.com/97457948/149298206-8250518a-1c3d-4860-afa3-5b09fa8483ef.png)
> 
> im worried about this one.

I think they are talking about hacks like Cheat Engine wich change speed of game

**Comment by zorelix69** [comment]
thats hilarious if people do speed hax using CE xD how long have you been using this program? ive been using it for almost a week now but not 24hrs a day only like when its time to sleep and when i wake up i do manual farming

**Comment by fguide** [comment]
> thats hilarious if people do speed hax using CE xD how long have you been using this program? ive been using it for almost a week now but not 24hrs a day only like when its time to sleep and when i wake up i do manual farming

Matter of fact people did use cetus engine to cheat on the game previously.

If you read  #432 you'd have a hint on it and wouldn't be worried about it.
