### ISSUE TITLE
Change Chrome window

### ISSUE THREAD

**Issue by MarSap7** [mpcabete/bombcrypto-bot#628]
Good afternoon,
In the multi account bot, Some time the bot dont change the Chrome window for the other account. It Is like he try to change, in the taskbar Is highlighted the correct One but the window that i see Is Always the same
Any idea?

**Comment by fguide** [comment]
I've seen someone saying to change the bot folder name to not contain "bombcrypto" so it wouldn't mix things up.

Can't test it, I don't use multiaccount.

**Comment by MarSap7** [comment]
No solved.
My folder was already with another Mame.
It happen Only some times

**Comment by bigorna23** [comment]
It probably won't solve your problem, but you can try accessing the game by the other link. Just remember to change the string in the code.

If link is "https://app.bombcrypto.io/":
`pygetwindow.getWindowsWithTitle('Bombcrypto')`

If link is "https://app.bombcrypto.io/webgl/index.html":
`pygetwindow.getWindowsWithTitle('bombcrypto')`

**Comment by MarSap7** [comment]
It Is already in this way, damn

**Comment by mGranTY** [comment]
> It Is already in this way, damn

inside def main()

increase time.sleep()


example:
![image](https://user-images.githubusercontent.com/94913189/149424757-43569627-8bf0-4a11-845e-bd0c5e80d8a1.png)
