### ISSUE TITLE
house not working

### ISSUE THREAD

**Issue by biroandre** [mpcabete/bombcrypto-bot#630]
![Kepernyokep_2022-01-13_135548](https://user-images.githubusercontent.com/97684687/149353169-9047a06f-7b44-472b-9f36-36766818554b.png)
I got this error when I enable house in the config, can someone please help me with this? Thank you

**Comment by fguide** [comment]
Looks like some graphical issue, did you replace the home screenshot on the folder? CHeck if you saved on the same format it war originally.

Does it happen just when home is enabled?
