### ISSUE TITLE
Não coloca os herois para trabalhar

### ISSUE THREAD

**Issue by AlissonResende** [mpcabete/bombcrypto-bot#631]
Ele reconhece os herois e os botões mas não coloca pra trabalhar, eu estava usando a versão mais antiga, antes mesmo do captcha e ela funciona perfeitamente, mas como recentemente adquiri mais uma conta, queria rodar o multiacc, porém ela não manda os herois para trabalhar. 
obs:Rodando em maquina virtual

**Comment by fguide** [comment]
Versão oficial nao tem multi contas, utilize alguma adaptada, ex:

https://github.com/rzanca/bombcrypto-multibot

**Comment by AlissonResende** [comment]
> Versão oficial nao tem multi contas, utilize alguma adaptada, ex:
> 
> https://github.com/rzanca/bombcrypto-multibot

Achei que tivesse pois vi umas atualizações pelo Anderson que era para multiaccount, mas vou testar esse ai que você enviou.

**Comment by fguide** [comment]
Ele subiu um PR para juntar na oficial mas não foi visto ainda, você pode baixar essa versao diretamente do repositorio dele também

**Comment by AlissonResende** [comment]
> Ele subiu um PR para juntar na oficial mas não foi visto ainda, você pode baixar essa versao diretamente do repositorio dele também

Eu baixei a versão dele, mas não funcionou, vou baixar a que você indicou para testar, muito obrigado mesmo pela ajuda ! 
Essa versão que você mandou é segura ?

**Comment by fguide** [comment]
Eu não utilizei para testar porque nao tenho outras contas mas acredito que seja sim, foi feito por um usuário aqui do repositorio e pelo que vi rapidamente no codigo nao encontrei nada de errado.

Outra versão que também parece funcionar bem, mas também nao testei:

https://github.com/MatheusHAS/bombcrypto-bot

**Comment by jeffersonveloso** [comment]
> Eu não utilizei para testar porque nao tenho outras contas mas acredito que seja sim, foi feito por um usuário aqui do repositorio e pelo que vi rapidamente no codigo nao encontrei nada de errado.
> 
> Outra versão que também parece funcionar bem, mas também nao testei:
> 
> https://github.com/MatheusHAS/bombcrypto-bot

Está funcionando bem sim, já estou utilizando a 2 dias.

**Comment by 8driano** [comment]
> > Versão oficial nao tem multi contas, utilize alguma adaptada, ex:
> > https://github.com/rzanca/bombcrypto-multibot
> 
> Achei que tivesse pois vi umas atualizações pelo Anderson que era para multiaccount, mas vou testar esse ai que você enviou.

fica dando esse erro, alguém sabe corrigir? 
![image](https://user-images.githubusercontent.com/85385771/149457545-6756b74f-bc8b-43e5-b463-7ddbd6410031.png)

**Comment by rzanca** [comment]
> > > Versão oficial nao tem multi contas, utilize alguma adaptada, ex:
> > > https://github.com/rzanca/bombcrypto-multibot
> > 
> > Achei que tivesse pois vi umas atualizações pelo Anderson que era para multiaccount, mas vou testar esse ai que você enviou.
> 
> fica dando esse erro, alguém sabe corrigir? 
> ![image](https://user-images.githubusercontent.com/85385771/149457545-6756b74f-bc8b-43e5-b463-7ddbd6410031.png)
> 

pip install Pillow

**Comment by ibuselatto** [comment]
No meu pc ele encontra a green bar porém não dá o start, fica trocando de tela e não coloca os heroes para trabalhar, como eu arrumo?

**Comment by rzanca** [comment]
> No meu pc ele encontra a green bar porém não dá o start, fica trocando de tela e não coloca os heroes para trabalhar, como eu arrumo?

Qual resolução da máquina?
Qual escala do monitor?
Jogo está em inglês?
Metamask está em inglês?

**Comment by ibuselatto** [comment]
> 
Qual resolução da máquina? 1366  768 (note)
Qual escala do monitor? 14 pol
Jogo está em inglês? sim
Metamask está em inglês? sim

**Comment by rzanca** [comment]
> Qual resolução da máquina? 1366 768 (note) Qual escala do monitor? 14 pol Jogo está em inglês? sim Metamask está em inglês? sim

Tente uma outra versão e verifique se vai resolver. 
https://github.com/rzanca/bombcrypto-multibot

**Comment by ibuselatto** [comment]
Não aparece o chatid
{"ok":true,"result":[]}

**Comment by fguide** [comment]
https://api.telegram.org/botXXXXXX:XXXXXXX/getUpdates?offset=-1

Vai mostrar a ultima msg do bot com ID do chat. Substituia a chave de acordo com a sua e manda uma msg pro bot antes de verificar.

**Comment by ibuselatto** [comment]
Sem retorno
{"ok":true,"result":[]}

**Comment by YanHappy** [comment]
> Sem retorno {"ok":true,"result":[]}
you need to send/start the command at the chatbox of the bot, then re-load URL, U can see what you want.
