### ISSUE TITLE
Faster Is better

### ISSUE THREAD

**Issue by MarSap7** [mpcabete/bombcrypto-bot#632]
Witch parameters i can change to go faster?
Because when you have more than 4 account the spend a lot of time to change window and maybe the First One go offline. Aldo give more Speed to the arrow

**Comment by jeffersonwms** [comment]
Try to set the value of "interval_between_moviments" to 0.5 (recommended 0.7)  in config.yml
and change the bellow function in index.py:

```python
def moveToWithRandomness(x, y, t):
    pyautogui.moveTo(addRandomness(x, 10), addRandomness(y, 10), 0.5 + random() / 2)
```
now, cursor moviments will be faster.

**Comment by zorelix69** [comment]
> Witch parameters i can change to go faster? Because when you have more than 4 account the spend a lot of time to change window and maybe the First One go offline. Aldo give more Speed to the arrow


may i see a picture on how do u place your multi account window on the window screen. im trying to make mine work but i dont have any idea how am i gonna place my account windows on screen since it requires 100% zoom

**Comment by MarSap7** [comment]
> > Witch parameters i can change to go faster? Because when you have more than 4 account the spend a lot of time to change window and maybe the First One go offline. Aldo give more Speed to the arrow
> 
> may i see a picture on how do u place your multi account window on the window screen. im trying to make mine work but i dont have any idea how am i gonna place my account windows on screen since it requires 100% zoom

all the window in full screen, after disable the flag of the occlusion in chrome:\\flags
there is a question that explain this issue

**Comment by zorelix69** [comment]
> > > Witch parameters i can change to go faster? Because when you have more than 4 account the spend a lot of time to change window and maybe the First One go offline. Aldo give more Speed to the arrow
> > 
> > 
> > may i see a picture on how do u place your multi account window on the window screen. im trying to make mine work but i dont have any idea how am i gonna place my account windows on screen since it requires 100% zoom
> 
> all the window in full screen, after disable the flag of the occlusion in chrome:\flags there is a question that explain this issue

im using brave browser can you teach me how can i use the bot with multi accounts

**Comment by MarSap7** [comment]
> > > > Witch parameters i can change to go faster? Because when you have more than 4 account the spend a lot of time to change window and maybe the First One go offline. Aldo give more Speed to the arrow
> > > 
> > > 
> > > may i see a picture on how do u place your multi account window on the window screen. im trying to make mine work but i dont have any idea how am i gonna place my account windows on screen since it requires 100% zoom
> > 
> > all the window in full screen, after disable the flag of the occlusion in chrome:\flags there is a question that explain this issue
> 
> im using brave browser can you teach me how can i use the bot with multi accounts 

You have to open another issue for this topic.

**Comment by MarSap7** [comment]
> Try to set the value of "interval_between_moviments" to 0.5 (recommended 0.7)  in config.yml
> and change the bellow function in index.py:
> 
> ```python
> def moveToWithRandomness(x, y, t):
>     pyautogui.moveTo(addRandomness(x, 10), addRandomness(y, 10), 0.5 + random() / 2)
> ```
> now, cursor moviments will be faster.
>     

If i change Only the "interval_between_moviments" Is the same. Or i'm wrong? 
Anyway Is not enought, the function that take 1 minute (less or more) Is the login control. Someone know How optimize?

**Comment by fguide** [comment]
> > Try to set the value of "interval_between_moviments" to 0.5 (recommended 0.7)  in config.yml
> > and change the bellow function in index.py:
> > ```python
> > def moveToWithRandomness(x, y, t):
> >     pyautogui.moveTo(addRandomness(x, 10), addRandomness(y, 10), 0.5 + random() / 2)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > now, cursor moviments will be faster.
> 
> If i change Only the "interval_between_moviments" Is the same. Or i'm wrong? Anyway Is not enought, the function that take 1 minute (less or more) Is the login control. Someone know How optimize?

Inside the login() function you can change the timeouts of the clicks, they are 20 seconds average, you can lower that down and test if it breaks the script.

**Comment by MarSap7** [comment]
But the problem Is that Also if the button "connect" there isn't It takes that time.
When there Is a button the time Is correct, because depends Also from your CPU
________________________________

**Comment by fguide** [comment]
Yes, that's because timeout is the amount of seconds the script waits if the image isn't found, if it's found then it just promptly clicks the button, got it? For instance:
    
    if clickBtn(images['connect-wallet'], timeout = 10):

it'll wait 10 seconds if the button is not found, if it is, then it'll click immediately.

**Comment by MarSap7** [comment]
> Yes, that's because timeout is the amount of seconds the script waits if the image isn't found, if it's found then it just promptly clicks the button, got it? For instance:
> 
> ```
> if clickBtn(images['connect-wallet'], timeout = 10):
> ```
> 
> it'll wait 10 seconds if the button is not found, if it is, then it'll click immediately.

But
if this condition "if clickBtn(images['connect-wallet'], timeout = 10):" is false that one 
"if clickBtn(images['select-wallet-2'], name='sign button', timeout=5):" is useless, is correct?
We can put inside the First of condition

**Comment by ezera23** [comment]
Guys....why dont add a click when its disconnected??
