### ISSUE TITLE
Problemas usando um Macbook.

### ISSUE THREAD

**Issue by Pedrobertucci** [mpcabete/bombcrypto-bot#635]
Alguem ja teve esse problema? 

Estou com problemas nas configuracoes da resolucao? alguem tentou rodar usando o macbook e qual a melhor para utilizar o bot?

**Comment by fguide** [comment]
Provavelmente por ser tela retina. VOcê pode ajustar pra 1920x1080 ou usar a versao abaixo que tem ajuste para MAC:


https://github.com/MatheusHAS/bombcrypto-bot
