### ISSUE TITLE
Usar botão full ou mandar heróis individual?

### ISSUE THREAD

**Issue by kendikaku** [mpcabete/bombcrypto-bot#636]
Boa tarde, estou em dúvida, compensa mais mandar todos os heróis de 1 hora em 1 hora ou mandar heróis com a vida verde de 10 em 10 minutos?
Qual dos dois gera mais farm?

**Comment by fguide** [comment]
A forma mais fácil de você descobrir isso é testando com seu time, nao tem formula genérica, cada time tem uma configuração de herois, tempo de recarga, energia, etc...

Faça testes com o bot em diversas configurações e veja qual é mais produtiva pro seu caso.
