### ISSUE TITLE
BOT a Venda?

### ISSUE THREAD

**Issue by LeandroBraccio** [mpcabete/bombcrypto-bot#637]
Olá,

Gostaria de saber, se puder do proprio desenvolvedor, se o bot foi colocado a venda, pois acabei de ver um video postado no youtube, canal com mais 200mil inscritos, oferecendo o bot a venda. Segue link do video https://www.youtube.com/watch?v=KUyMji8eMV8

Apesar de não mostrar o bot em si, em alguns momentos percebe-se a similaridade. Sei que o codigo é aberto e livre pra quem entende programar, podendo fazer quaisquer alterações, mas acho anti ético fazer uma cópia e sair vendendo por ai (minha opinião).

O que vcs acham?

**Comment by fguide** [comment]
Nem perca seu tempo, tem gente no mundo todo usando esse bot pra vender as versões "exclusivas" dele. 

O autor já ganhou um boa grana em doações, que foi a intenção dele desde sempre, então tá tudo certo. 

Aliás, aqui mesmo o pessoal só desenvolvia algumas funções com meta de doação, então fazer o que? Dog eat dog.

**Comment by LeandroBraccio** [comment]
Nada contra o youtuber em si. Mas não é certo vender algo disponibilizado gratuitamente. Além do que, a pessoa que compra, pode estar entrando numa fria, já que houve modificações no codigo por outro desenvolvedor (que está vendendo), podendo haver algum tipo de SCAM. Pois jamais ele passaria o bot para ser analisado, antes da pessoa comprar. É a mesma coisa que vender o Mouse Click Recorder...mas pelo o que você disse, tem mta gente praticando isso, então é perca de tempo mesmo. Uma pena para o criador ter que passar por isso.

**Comment by fguide** [comment]
É o velho dilema do open source amigo... quantos produtos proprietários existem com base em código livre? O próprio bombcrypto copiou o gameplay do bomberman, porque gameplay nao é patenteável...

Pense o seguinte, se ele vende uma solucao dele e oferece por exemplo um bom suporte, já pode ser viável pra muita gente, uma vez que o suporte aqui é todo feito voluntariamente por usuários sem nenhuma obrigação... 

Quanto à ele possivelmente enganar pessoas com código modificado: fazer o que? Cada um é responsável pela sua propria segurança, ao menos cobrando pelo "produto" ele também pode ser responsabilizado por qualquer problema...

**Comment by LeandroBraccio** [comment]
Entendo...sim...concordo contigo...se realmente o bot que ele oferece tem particularidades que o torna melhor e mais eficiente, com opções melhores, talvez sim poder cobrar...pelo menos no video unica diferença que eu vi é que o bot manda status do jogo no seu proprio Telegram (não sei se isso ja foi disponibilizado aqui, pois tem um tempo que não acompanho o desenvolvimento do codigo aqui). Mas enfim, obrigado por esse bate papo. Vou manter aberto por mais algumas horas, caso alguem queira acrescentar, ou se algum moderador quiser fechar o topico, fique a vontade!

**Comment by fguide** [comment]
> 

Dá uma pesquisada aqui no repositório, tem versões bem mais completas que a oficial, com suporte a multi account, telegram, etc, todas grátis obviamente! 
Provavelmente ele fez com base em alguma delas. Alguns exemplos:

https://github.com/afkapp/bombcrypto-bcbot

https://github.com/rzanca/bombcrypto-multibot

https://github.com/MatheusHAS/bombcrypto-bot

**Comment by roaceu** [comment]
é possível fazer integração com o WhatsApp? Para envio de informações

**Comment by Igorlegacy** [comment]
É como o cara em cima falou, apesar do código de ser open source existe muitas versões que possuem suas particularidades e funções extras... eu mesmo possuo minha versão personalizada utilizando como base do mpcabete no qual até comercializo entre alguns amigos que possuem conhecimento 0 do assunto, faço a configuração para eles do 0 em VPS e presto suporte e manutenções e sempre acrescento alguma função nova que seja útil quando solicitado...

Eu não precisei cobrar para estes amigos... maioria deles somente falou, "ahh configura tudo pra mim e te pago para você manter rodando 24hr."

**Comment by cleitonleonel** [comment]
> > 
> 
> Dá uma pesquisada aqui no repositório, tem versões bem mais completas que a oficial, com suporte a multi account, telegram, etc, todas grátis obviamente! Provavelmente ele fez com base em alguma delas. Alguns exemplos:
> 
> https://github.com/afkapp/bombcrypto-bcbot
> 
> https://github.com/rzanca/bombcrypto-multibot
> 
> https://github.com/MatheusHAS/bombcrypto-bot

Também tenho uma versão personalizada https://github.com/cleitonleonel/bombcrypto-bot

**Comment by cleitonleonel** [comment]
> é possível fazer integração com o WhatsApp? Para envio de informações

Sim, é possível  com wppconnect, Venom-bot, Baileys
