### ISSUE TITLE
Kick por afk

### ISSUE THREAD

**Issue by Bjickzz** [mpcabete/bombcrypto-bot#639]
Gostaria de saber se é possivel evitar esses kicks por afk, pois deixo o bot on a noite e quando acordo a  conta ta parada la por ter sido kickada.

**Comment by fguide** [comment]
Kick nao é por AFK, quando aparece KICK é porque te chutaram do server pra manutenção, etc. A mensagem de AFK diz que caiu por inatividade...

**Comment by Bjickzz** [comment]
> 



> Kick nao é por AFK, quando aparece KICK é porque te chutaram do server pra manutenção, etc. A mensagem de AFK diz que caiu por inatividade...
eu sei q o kick em especifico n é por afk, mas cair por inatividade tmb é uma forma de kick. Foi isso que quis dizer

**Comment by fguide** [comment]
Sim, mas o bot com configuração padrão por exemplo não cai por inatividade, talvez os intervalos estejam muito altos no seu pc.

**Comment by Bjickzz** [comment]
> Sim, mas o bot com configuração padrão por exemplo não cai por inatividade, talvez os intervalos estejam muito altos no seu pc.

Po, mas eu n mexi em nada :/ só rodo ele em uma vps q é bem boa ainda

**Comment by fguide** [comment]
> > Sim, mas o bot com configuração padrão por exemplo não cai por inatividade, talvez os intervalos estejam muito altos no seu pc.
> 
> Po, mas eu n mexi em nada :/ só rodo ele em uma vps q é bem boa ainda

Deve ser aí o seu problema, VPS windows? Vc acessa via RDP? Lembre que sempre que desconecta via RDP a sessao fica travada e o bot nao funciona. Tem tópicos sobre isso e como resolver aqui.

**Comment by Bjickzz** [comment]
> > > Sim, mas o bot com configuração padrão por exemplo não cai por inatividade, talvez os intervalos estejam muito altos no seu pc.
> > 
> > 
> > Po, mas eu n mexi em nada :/ só rodo ele em uma vps q é bem boa ainda
> 
> Deve ser aí o seu problema, VPS windows? Vc acessa via RDP? Lembre que sempre que desconecta via RDP a sessao fica travada e o bot nao funciona. Tem tópicos sobre isso e como resolver aqui.

sim, vps Windows via rdp, ja tentei usar o código que vc disponibilizou, desconecta da sessão do controle remoto, porém o teamviewer também para de funcionar

**Comment by fguide** [comment]
do google? Vc criou o display virtual nas configuracoes da VM?
