### ISSUE TITLE
Vendendo seu bot

### ISSUE THREAD

**Issue by Gayedo6766** [mpcabete/bombcrypto-bot#64]
Boa noite, primeiro de tudo gostaria de agradecer e parabenizar o seu bot, muito obrigado mesmo, agora posso dormir em paz e continuar farmando bcoins, obrigado mesmo!
Agora gostaria de lhe alertar que tem várias pessoas vendendo seu bot, inclusive achei em um anúncio em um site, não sei se é o seu, mas pela imagem ali do prompt de comando acredito que seja, dá uma conferida aí:
https://www.dfgames.com.br/pt/outros/bombcrypto-bot-vitalicio-966174796
Abraços!

**Comment by mpcabete** [comment]
audsfhaudfh que engraçado, n imaginei q alguém ia vender ele nao
mas pelomenos pelo site parece q ngm comprou ainda.
Valeu pelo aviso! vou fechar o issue pra ajudar na minha organização, mas pode mandar mensagem aqui que eu vejo 🙂
