### ISSUE TITLE
Erro: ModuleNotFoundError: No module named 'src.logger' (RESOLVIDO)

### ISSUE THREAD

**Issue by MathCarv** [mpcabete/bombcrypto-bot#640]
Olá, estou com este erro no módulo do python. Já tentei reinstalar o python, atualizar todas as dependências envolvidas e reinstalar o bot com os requirements. Alguém poderia me ajudar ? 

Estou utilizando: "python3 index.py"

Mesmo erro aconteceu com "python index.py"

Traceback (most recent call last):
  File "/home/peixe/Área de trabalho/bombcrypto-bot/index.py", line 2, in <module>
    from src.logger import logger, loggerMapClicked
ModuleNotFoundError: No module named 'src.logger'

**Comment by fguide** [comment]
Amigo, salve em um diretório que nao tenha espaço nem caracter especial (área de trabalho) e deve funcionar, o espaço no diretorio quebra a chamada...

**Comment by MathCarv** [comment]
@fguide, coloquei em "Documentos" e o erro ainda continua

**Comment by fguide** [comment]
estranho, tenta rodar de novo o comando pip install -r requirements.txt no diretorio novo. Outra coisa, veja se o diretorio src esta na do diretorio do bot tambem...

**Comment by MathCarv** [comment]
Rodei um "ll", esses são as pastas dentro.

total 64
-rw-r--r-- 1 root root  3878 jan 14 22:33 config.yaml
-rw-r--r-- 1 root root 16981 jan 14 22:33 index.py
drwxr-xr-x 2 root root  4096 jan 14 22:33 logs
-rw-r--r-- 1 root root  4762 jan 14 22:33 README.en.md
drwxr-xr-x 2 root root  4096 jan 14 22:33 readme-images
-rw-r--r-- 1 root root  8834 jan 14 22:33 README.md
-rw-r--r-- 1 root root   198 jan 14 22:33 requirements.txt
drwxr-xr-x 2 root root  4096 jan 14 22:33 src
drwxr-xr-x 2 root root  4096 jan 14 22:33 targets

**Comment by Fishverse** [comment]
Resultado do "pip install -r requirements.txt"

Requirement already satisfied: MouseInfo==0.1.3 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 1)) (0.1.3)
Requirement already satisfied: mss==6.1.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (6.1.0)
Requirement already satisfied: numpy==1.21.4 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (1.21.4)
Requirement already satisfied: opencv-python==4.5.4.60 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 4)) (4.5.4.60)
Requirement already satisfied: PyAutoGUI==0.9.53 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 5)) (0.9.53)
Requirement already satisfied: PyGetWindow==0.0.9 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 6)) (0.0.9)
Requirement already satisfied: PyMsgBox==1.0.9 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 7)) (1.0.9)
Requirement already satisfied: pyperclip==1.8.2 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 8)) (1.8.2)
Requirement already satisfied: PyRect==0.1.4 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 9)) (0.1.4)
Requirement already satisfied: PyScreeze==0.1.28 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 10)) (0.1.28)
Requirement already satisfied: pytweening==1.0.4 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 11)) (1.0.4)
Requirement already satisfied: PyYAML==6.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 12)) (6.0)
Requirement already satisfied: python3-Xlib in /usr/local/lib/python3.9/dist-packages (from MouseInfo==0.1.3->-r requirements.txt (line 1)) (0.15)

**Comment by fguide** [comment]
Tudo certo aparentemente, qual sua versao de python (ja vi que é 3.9)? Tem mais de uma instalada?

**Comment by fguide** [comment]
Ahh, perai... vc esta executando com root? porque as permissoes estao para root...

**Comment by Fishverse** [comment]
Testei tudo com root e sem root, mesmo erro para ambos. 
python3 -V
Python 3.9.9

**Comment by ZaryImortal** [comment]
mesma coisa aqui, tava usando até agora, fui fechar o programa e abrir dnv, e da esse error

**Comment by Fishverse** [comment]
Galera, to achando que é a versão do python. 

Rodei: "sudo ln -sf /usr/bin/python3.10 /usr/bin/python3"

Assim meu python agora ficou com a versão 3.10, porém o erro mudou, ficando:

Traceback (most recent call last):
  File "/home/peixe/Documentos/bombcrypto-bot/index.py", line 3, in <module>
    from cv2 import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by fguide** [comment]
Sim, provaelmente é por multi versao, faça o seguinte:

sudo chown -R peixe:peixe /home/peixe/Documentos/bombcrypto-bot/ (Ajuste pra usuario e caminho conforme estiver aí, chutei pelos logs que vc mandou)
cd ~/Documentos/bombcrypto-bot
pip install -r requirements.txt

python index.py

Veja se resolve

**Comment by MathCarv** [comment]
Solução para o erro "ModuleNotFoundError: No module named 'src.logger'" - Linux/Kali linux:

1 - Altere a versão do python3 para 3.10
   sudo ln -sf /usr/bin/python3.10 /usr/bin/python3
   
2 - Instale as dependências novamentte: 
    pip install -r requirements.txt

**Comment by MathCarv** [comment]
@fguide, muito obrigado pela ajuda! Para aqueles que estiverem tendo o mesmo erro, sigam o tutorial acima e vejam se funciona!
