### ISSUE TITLE
Meu bot nao esta funcionando

### ISSUE THREAD

**Issue by kaynathon** [mpcabete/bombcrypto-bot#642]
Nao sei o que fazer, sou bem leigo com essas coisas, porem meu bot nao esta funcionando ate dois dias atras funcionava tudo normal, hoje ja comecou da uns problema, e agora nem move o mouse mais

**Comment by luizsergiorf** [comment]
Boa noite, qual erro está aparecendo no terminal? Sugiro que você não utiliza o bot no sistema direto, crie um Docker ou uma máquina virtual. Assim você consegue ter mais segurança e não "perde" o computador apenas executando o bot.

**Comment by kaynathon** [comment]
Tipo de vez enquanto quando coloco no all, aí vamos falar que tem 1 boneco com 0 de estamina, ele fica tentando colocar o boneco pra trabalhar mas nunca da aí vai e desconecta do jogo

**Comment by Felipecristao** [comment]
Seu game esta em portugues ou ingles?, se tiver em Br muda para ingles
