### ISSUE TITLE
background

### ISSUE THREAD

**Issue by badyami** [mpcabete/bombcrypto-bot#643]
gente o chrome atualizou e removeu a opção de desativar  o Calculate window occlusion on Windows consegui fazer o downgrade do chrome mas mesmo desabilitando os serviços do chrome update depois de um tempo ele reativa e o chrome refaz o update encontrei no redit a seguinte dica, clicar no propriedades no icone do seu navegador e logo apos acabar as aspas da guia destino cole isso dando um espaço  --disable-backgrounding-occluded-windows que volta  a funcionar obs : tentei no chrome e não foi mas no brave funcionou  fica a dica pessoal ♥

**Comment by gabok2** [comment]
isso serve pra que Calculate window occlusion?

**Comment by badyami** [comment]
> isso serve pra que Calculate window occlusion?

para que seu bomb funcione com a aba minimizada no multi account

**Comment by deftandre** [comment]
Alguém sabe como proceder quando o chrome atualizou a opção não aparece mais
