### ISSUE TITLE
Bot não manda todos os heróis trabalhar

### ISSUE THREAD

**Issue by fvbcks** [mpcabete/bombcrypto-bot#645]
Bom dia pessoal. Perdão se esse issue já foi solucionado aqui, não consegui achar.

Tenho 15 heróis na conta e quando ele abre a janela de heróis ele manda todos os heróis que estão no topo da janela com a barra verde para trabalhar, mas quando ele faz o scroll pra baixo para checar os outros ele desce tudo e manda os que estão em baixo. Na maioria das vezes fica uns 2 heróis totalmente full sem trabalhar que são sempre os que estão no meio da página que só podem ser checados se o bot parar no meio da barra de scroll e não descer totalmente. Alguém sabe como resolver?

A única coisa que fiz foi modificar a barra de 
![green-bar](https://user-images.githubusercontent.com/97397928/149625190-7e1a7719-bbed-4e4e-9af5-efb103b338fb.png)
 para 
![green-bar](https://user-images.githubusercontent.com/97397928/149625197-ecafaf36-cbac-4d70-91c3-cda1f67f3a05.png)

Obrigado.

**Comment by fguide** [comment]
No arquivo config.yaml mude o parametro click_and_drag_amount para um numero menor e teste ate ter o efeito desejado.

Se diminuir muito vai precisar aumentar o scroll_attemps tb
