### ISSUE TITLE
Como alterar o bot???

### ISSUE THREAD

**Issue by willianleo** [mpcabete/bombcrypto-bot#646]
E ai galera, como eu altero este bot para mandar todos os herois trabalharem a cada 20 minutos independente da barra de estamina?

**Comment by walterdis** [comment]
Abre o config.yaml que tem as configurações para isso ali dentro.

**Comment by willianleo** [comment]
Eu tentei nessas configurações mas entrava no menu e nao colocava todos os personagens, como eu faço?

**Comment by kerferber** [comment]
Tente aumentar a quantidade de "scroll" no config.yaml
