### ISSUE TITLE
Página congelando, como fazer o bot dar CTRL + F5?

### ISSUE THREAD

**Issue by Vitaonx** [mpcabete/bombcrypto-bot#648]
![Sem título](https://user-images.githubusercontent.com/96921060/149645723-c3bc80c0-cc0d-4779-99ff-8e3b2d57a45e.png)

Esse erro está aparecendo sempre, e o interessante é que só acontece em uma conta pois no outro perfil da outra conta não acontece, e com isso a tela do navegador congela e o bot não tem o que reconhecer. Gostaria de saber como eu faço pro bot dar um CTRL F5 quando não detecta nada na tela? ou até mesmo até x minutos.

**Comment by joaopalmeidao** [comment]
acredito que nesse pullrequest tem essa função #647  

> ![Sem título](https://user-images.githubusercontent.com/96921060/149645723-c3bc80c0-cc0d-4779-99ff-8e3b2d57a45e.png)
> 
> Esse erro está aparecendo sempre, e o interessante é que só acontece em uma conta pois no outro perfil da outra conta não acontece, e com isso a tela do navegador congela e o bot não tem o que reconhecer. Gostaria de saber como eu faço pro bot dar um CTRL F5 quando não detecta nada na tela? ou até mesmo até x minutos.

acredito que nesse pull request #647 já tem essa fução

**Comment by Vitaonx** [comment]
> acredito que nesse pullrequest tem essa função #647
> 
> > ![Sem título](https://user-images.githubusercontent.com/96921060/149645723-c3bc80c0-cc0d-4779-99ff-8e3b2d57a45e.png)
> > Esse erro está aparecendo sempre, e o interessante é que só acontece em uma conta pois no outro perfil da outra conta não acontece, e com isso a tela do navegador congela e o bot não tem o que reconhecer. Gostaria de saber como eu faço pro bot dar um CTRL F5 quando não detecta nada na tela? ou até mesmo até x minutos.
> 
> acredito que nesse pull request #647 já tem essa fução

Cara, mt obrigado, vou testar
