### ISSUE TITLE
too many hero clicks 

### ISSUE THREAD

**Issue by Bjickzz** [mpcabete/bombcrypto-bot#649]
Alguma solução para o erro de too many hero clicks, try to increase the go_to_work_btn threshold? o bot fica tentando clicar em work de herói que ja está trabalhando, e ignorando o resto dos q não estão em work, travando nesse loop por horas

**Comment by fguide** [comment]
Na verdade isso é um falso positivo, depois de mandar 20 herois esse "erro" aparece, mas na verdade não é bem um erro, é um bug no contador.

Agora que versao vc está usando? Porque isso foi em teoria corrigido há um tempo já... (NAO FOI CORRIGIDO PARA MODO GREEN E FULL, VER ULTIMAS RESPOSTAS)

**Comment by gabrielwjesus** [comment]
eu coloquei pra ele clicar no X caso ocorra isso e vou diminuir pra 15, que é o máximo de herois que ele pode enviar. 
![image](https://user-images.githubusercontent.com/54075771/149777890-5df44211-a4c4-4642-aed6-8c7c247a5924.png)

**Comment by fguide** [comment]
> eu coloquei pra ele clicar no X caso ocorra isso e vou diminuir pra 15, que é o máximo de herois que ele pode enviar. ![image](https://user-images.githubusercontent.com/54075771/149777890-5df44211-a4c4-4642-aed6-8c7c247a5924.png)

Amigo, não tem necessidade de fazer isso... veja o problema do too many clicks em: #482 
foi implementado um contador a parte para nao ter confusão com o hero_clicks

A questão é que foi feito apenas para o ,odo green.

E sendo bem sincero, contar a quantidade de clicks enquanto envia nem faz duferença, essa parte de código eu nem uso mais ha muito tempo:

```
        if hero_clicks_cnt > 20:
            logger('too many hero clicks, try to increase the go_to_work_btn threshold')
            return
```

**Comment by gabrielwjesus** [comment]
> > eu coloquei pra ele clicar no X caso ocorra isso e vou diminuir pra 15, que é o máximo de herois que ele pode enviar. ![image](https://user-images.githubusercontent.com/54075771/149777890-5df44211-a4c4-4642-aed6-8c7c247a5924.png)
> 
> Amigo, não tem necessidade de fazer isso... veja o problema do too many clicks em: #482 foi implementado um contador a parte para nao ter confusão com o hero_clicks
> 
> A questão é que foi feito apenas para o ,odo green.
> 
> E sendo bem sincero, contar a quantidade de clicks enquanto envia nem faz duferença, essa parte de código eu nem uso mais ha muito tempo:
> 
> ```
>         if hero_clicks_cnt > 20:
>             logger('too many hero clicks, try to increase the go_to_work_btn threshold')
>             return
> ```

valeu, vou corrigir essa parte

**Comment by Bjickzz** [comment]
> Na verdade isso é um falso positivo, depois de mandar 20 herois esse "erro" aparece, mas na verdade não é bem um erro, é um bug no contador.
> 
> Agora que versao vc está usando? Porque isso foi em teoria corrigido há um tempo já...

to usando a versão mais recente, mas continua dando esse "bug", talvez pq eu alterei o send heroes pra all e n apenas os com barrinha verde

**Comment by fguide** [comment]
> > Na verdade isso é um falso positivo, depois de mandar 20 herois esse "erro" aparece, mas na verdade não é bem um erro, é um bug no contador.
> > Agora que versao vc está usando? Porque isso foi em teoria corrigido há um tempo já...
> 
> to usando a versão mais recente, mas continua dando esse "bug", talvez pq eu alterei o send heroes pra all e n apenas os com barrinha verde

Você precisa editar o arquivo index.py e apagar as linhas 223, 224 e 225.

**Comment by leandrodoc** [comment]
Boas, fiquei um pouco perdido nesse histórico, estou usando a versão atualizada e continuo com o mesmo problema, ele não faz rolagem para os heróis abaixo.
