### ISSUE TITLE
Ignorar legend

### ISSUE THREAD

**Issue by JoaoMXN** [mpcabete/bombcrypto-bot#650]
Tem como fazer o bot ignorar o meu herói legend? Como a stamina dele demora 20 anos pra restaurar, eu quero colocar ele manualmente em momentos específicos e o resto tudo ir por bot.

Tentei as instruções desse tópico mas não funcionou, infelizmente o bot ainda coloca o legend pra trabalhar.
https://github.com/mpcabete/bombcrypto-bot/issues/485

**Comment by fguide** [comment]
Respondi no topico original.

**Comment by JoaoMXN** [comment]
Resolvido com a ajuda do @fguide

Quem estiver procurando o código, só ver neste post: https://github.com/mpcabete/bombcrypto-bot/issues/485#issuecomment-1014442326
