### ISSUE TITLE
2 itens a analisar: Escolher tipo de heroi Randomico e capturar quantidade de Coins para log 

### ISSUE THREAD

**Issue by gabrielwjesus** [mpcabete/bombcrypto-bot#651]
1. Nas configs voce pode escolher entre green, full e all.
eu adicionei o random entre as palavras. Então,toda vez que ele vai enviar ele sorteia aleatoriamente entre os 3 modos. 
porém , eu queria que a probabilidade escolher um verde fosse maior que as outras. (aceito ideias para lidar com a parte de probabilidade ou de repente um contador para que não fique só num mesmo modo por muito tempo.
![image](https://user-images.githubusercontent.com/54075771/149778221-42e5040d-135f-4d61-b419-6b67fcd81ac2.png)

2. criei uma função para abrir o baú e capturar a quantidade de moedas capturadas até aquele momento, mas seria legal se ele capturasse também ao iniciar cada mapa.
o problema é que não consegui ler somente os números, estou pegando o texto todo bagunçado. Alguém me ajuda nessa função?
` if now - last["new_map"] > t['check_for_new_map_button']:

            last["new_map"] = now

            if clickBtn(images['new-map']):

                loggerMapClicked()

                logger('Opening box and getting amount')

                openBox() 
`

`def openBox():

    clickBtn(images['box'])    

    logger('You have x coins right now')

    clickBtn(images['x'])
`
um item adicional e **inútil**: com medo do ban (agora eu sei que não da ban pois já publicaram isso) eu fiz ate uma função para entrar nas configs do jogo e sair kkkkk

**Comment by fguide** [comment]
Sugiro dar uma olhada nessa versão, uma vez que o repositorio aqui anda meio "parado" de atualizações:

https://github.com/afkapp/bombcrypto-bcbot

Tem opcao de notificar via telegram, envia report de mapa, de saldo e mais outras funções. Eu testei e é muito bom, não utilizo porque tem funções demais pra mim que não são necessárias.

**Comment by kendikaku** [comment]
> Sugiro dar uma olhada nessa versão, uma vez que o repositorio aqui anda meio "parado" de atualizações:
> 
> https://github.com/afkapp/bombcrypto-bcbot
> 
> Tem opcao de notificar via telegram, envia report de mapa, de saldo e mais outras funções. Eu testei e é muito bom, não utilizo porque tem funções demais pra mim que não são necessárias.

Qual bot você usa atualmente? Vi que você e bem ativo aqui na comunidade.

**Comment by gabrielwjesus** [comment]
> Sugiro dar uma olhada nessa versão, uma vez que o repositorio aqui anda meio "parado" de atualizações:
> 
> https://github.com/afkapp/bombcrypto-bcbot
> 
> Tem opcao de notificar via telegram, envia report de mapa, de saldo e mais outras funções. Eu testei e é muito bom, não utilizo porque tem funções demais pra mim que não são necessárias.

 a função do telegram foi uma das primeiras que implementei, antes mesmo de lançarem o primeiro captcha. Eu tinha medo de travar e não voltar kkkkk 
agora a função de adicionar mais detalhes nos logs é interessante

**Comment by fguide** [comment]
@gabrielwjesus sim, eu lembro disso! Nesse bot está bem completo, você pode até controlar o script pelo bot do telegram, vale a pena ver...

@Japa18244 Eu uso a oficial com as modificações que eu fiz para mim, atualmente cheguei na conclusao que pra mim vale a pena enviar tudo de uma vez a cada 2h, por isso eu fiz uma funçao pra clicar em all e coloquei o intervalo em 120 minutos.

**Comment by kendikaku** [comment]
> @gabrielwjesus sim, eu lembro disso! Nesse bot está bem completo, você pode até controlar o script pelo bot do telegram, vale a pena ver...
> 
> @Japa18244 Eu uso a oficial com as modificações que eu fiz para mim, atualmente cheguei na conclusao que pra mim vale a pena enviar tudo de uma vez a cada 2h, por isso eu fiz uma funçao pra clicar em all e coloquei o intervalo em 120 minutos.

Entendi, eu ainda estou usando a versão https://github.com/MatheusHAS/bombcrypto-bot

Foi a que mais se encaixou comigo, fiz o teste de colocar todos os heróis de hora em hora mas parece que o farm não rende tanto quanto colocar de 10 em 10 minutos somente os heróis com barra verde,
As minhas duas contas são

1 épico(bateria e escudo) 2 raros(escudo) e 12 comum( alguns com bateria)


1 lendario(escudo) 1 raro(escudo) restante comum.

**Comment by fguide** [comment]
@Japa18244 

Em teoria a única diferença que eu notei (no meu caso) é enviar os mais fortes no começo do mapa e sozinhos enquanto os comuns descansam (a estratégia do +30% de profit), porém meu mais forte demora 23h para carregar total e 7 horas pra chegar em verde (30%). 
Eu acabei percedendo que é melhor enviar ele a cada 2h pra ajudar a limpar o mapa, mesmo com os comuns trabalhando.

E durante o dia quando tenho tempo eu interajo manualmente, o bot fica rodando sozinho mais quando estou ocupado. Mas eu tenho só uma conta, entao fica mais fácil de administrar.

**Comment by gabrielwjesus** [comment]
outro ponto legal que voces citaram: leitura do mapa, quantidade de baus, rochas, etc... 
pq quando só tem um ou dois baus no mapa é legal usar os herois aos poucos, aumentando o tempo de descanso, enviando 1 ou 2 herois por vez até eles cansarem. 
Pra mim, deixar alternando tem sido ótimo por isso, as vezes os herois acabam descansando mais tempo que o normal, as vezes vai todo mundo, etc....
agora se eu conseguir ler o mapa fica mais inteligente o envio de herois e aproveitamento

**Comment by fguide** [comment]
Em teoria fizeram isso em #647 mas nao testei.

**Comment by joaopalmeidao** [comment]
> Em teoria fizeram isso em #647 mas nao testei.

Eu cheguei a testar durante pouco tempo, no que vi so enviava os meus comuns pra trabalhar, não sei se quando os heróis mais raros estiverem com a stamina full ele colocará pra trabalhar.
E depois de um tempo rodando ele não vê alguns herois na tela e não poe pra trabalhar, agora eu não sei se o probelma seria de não estar reconhecendo as barras verdes ou se seria a função que ele usou pra calcular quais herois vão trabalhar.
Mas acredito que tá no caminho certo, vo deixar o bot que eu uso atualmente, deixo rodando quase que 24hr por dia e não costuma travar, mesmo quando eu interfiro no controle do pc com o bot, segue o link:
https://github.com/joaopalmeida420/bombcrypto-bot
Sou novo aqui, então acho que fiz o pull request errado, o bot q uso ta dendo da PASTA "bomb"

**Comment by kendikaku** [comment]
> @Japa18244
> 
> Em teoria a única diferença que eu notei (no meu caso) é enviar os mais fortes no começo do mapa e sozinhos enquanto os comuns descansam (a estratégia do +30% de profit), porém meu mais forte demora 23h para carregar total e 7 horas pra chegar em verde (30%). Eu acabei percedendo que é melhor enviar ele a cada 2h pra ajudar a limpar o mapa, mesmo com os comuns trabalhando.
> 
> E durante o dia quando tenho tempo eu interajo manualmente, o bot fica rodando sozinho mais quando estou ocupado. Mas eu tenho só uma conta, entao fica mais fácil de administrar.

O meu épico demora 10 horas pra full e o meu lendario 20 horas pra full, será que compensa fazer essa de 30%, eu deixo o bot 24horas nem vou mais no pc

**Comment by fguide** [comment]
> > @Japa18244
> > Em teoria a única diferença que eu notei (no meu caso) é enviar os mais fortes no começo do mapa e sozinhos enquanto os comuns descansam (a estratégia do +30% de profit), porém meu mais forte demora 23h para carregar total e 7 horas pra chegar em verde (30%). Eu acabei percedendo que é melhor enviar ele a cada 2h pra ajudar a limpar o mapa, mesmo com os comuns trabalhando.
> > E durante o dia quando tenho tempo eu interajo manualmente, o bot fica rodando sozinho mais quando estou ocupado. Mas eu tenho só uma conta, entao fica mais fácil de administrar.
> 
> O meu épico demora 10 horas pra full e o meu lendario 20 horas pra full, será que compensa fazer essa de 30%, eu deixo o bot 24horas nem vou mais no pc

Eu sinceramente parei de preocupar com isso porque realmente deu na mesma, eu faço de 2 em 2h porque é o tempo mais rápido que um heroi meu chega em 100%, e pelos meus testes faz praticamente a mesma coisa que mandando sempre em verde.
E também tem a questão de ser difícil comparar o rendimento porque os mapas sao bem aleatórios, tem dias que todo mapa tem bau azul, tem dias que nem vejo bau auzl, entao o rendimento em moedas acaba sendo menor porque o proprio game me "mandou" menos moedas, nao por causa da maneira que eu farmei...
