### ISSUE TITLE
Erro desconhecido no bot

### ISSUE THREAD

**Issue by klaylton** [mpcabete/bombcrypto-bot#652]
Estou tentando rodar o bot no meu notebook e não estou conseguindo. Fiz exatamente o mesmo processo no meu PC e ocorreu tudo certo, mas no notebook não está rodando corretamente. Print do erro abaixo.

![Erro](https://i.ibb.co/bF2gPYv/screenshot-09.jpg)

**Comment by fguide** [comment]
Amigo, pelo screenshot parece que seu monitor está com escala maior que 100%, precisa estar em 100% para funcionar.

E Resolucao maxima 1920x1080.

**Comment by leonardoafs** [comment]
Prezado @bboyguil ,

conseguiu resolver o problema?
Eu fiquei batendo cabeça o dia todo hoje com esse problema. Basicamente troquei a carteira do navegador e o bot parou de funcionar.

A coisa que solucionou pra mim foi refazer todos os print localizados em /bombcrypto-bot-main/targets. Utilizei a ferramenta de captura e fui refazendo imagem por imagem (não consegui refazer todas). Isso resolveu meu problema por ora. Tinha tentado todas as resoluções e nada!

**Comment by klaylton** [comment]
Olá @leonardoafs, o que funcionou pra mim foi ajustar a resolução da tela. Um outro amigo estava com o mesmo problema. Depois que o colega acima (@fguide ) deu a dica de ajustar a resolução, o problema foi resolvido. Vale lembrar que tem que se atentar para a resolução e a escala do navegador, conforme foi citado.
