### ISSUE TITLE
How to execute bot in linux?

### ISSUE THREAD

**Issue by alanlucena** [mpcabete/bombcrypto-bot#653]

**Comment by fguide** [comment]
Same way you'd do on Windows, install python, download bot, cd into dir, pip -r install requirements.txt and then run it.

**Comment by martinsssgabriel** [comment]
@alanlucena , talvez vc esteja com o mesmo erro que eu. Está estourando uma exception no momento de rodar o bot

**Comment by Frisoni** [comment]
No linux tem que usar outras bibliotecas. Eu fiz uma versão que está rodando no linux, dá uma conferida: https://github.com/Frisoni/bombcrypto-bot

**Comment by piagja** [comment]
> No linux tem que usar outras bibliotecas. Eu fiz uma versão que está rodando no linux, dá uma conferida: https://github.com/Frisoni/bombcrypto-bot

Po, eu tentei usar aqui e deu esse erro
Engraçado que com python index.py e python3 index.py dão erros diferentes!
Não manjo de Python =/

Ubuntu 20.04.3 LTS
Tudo instalado certinho, opencv, python latest, pip, simpleaudio

ERR Python3 ➜  bombcrypto-bot git:(main) python3 index.py               
Traceback (most recent call last):
  File "/home/pia/Documentos/Blockchain/Games/bombcrypto-bot/index.py", line 2, in <module>
    from src.logger import logger, loggerMapClicked
  File "/home/pia/Documentos/Blockchain/Games/bombcrypto-bot/src/logger.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'


ERR Python ➜  bombcrypto-bot git:(main) python index.py
Traceback (most recent call last):
  File "index.py", line 2, in <module>
    from src.logger import logger, loggerMapClicked
ImportError: No module named src.logger

Agradeço o help o/

**Comment by Frisoni** [comment]
> > No linux tem que usar outras bibliotecas. Eu fiz uma versão que está rodando no linux, dá uma conferida: https://github.com/Frisoni/bombcrypto-bot
> 
> Po, eu tentei usar aqui e deu esse erro Engraçado que com python index.py e python3 index.py dão erros diferentes! Não manjo de Python =/
> 
> Ubuntu 20.04.3 LTS Tudo instalado certinho, opencv, python latest, pip, simpleaudio
> 
> ERR Python3 ➜ bombcrypto-bot git:(main) python3 index.py Traceback (most recent call last): File "/home/pia/Documentos/Blockchain/Games/bombcrypto-bot/index.py", line 2, in from src.logger import logger, loggerMapClicked File "/home/pia/Documentos/Blockchain/Games/bombcrypto-bot/src/logger.py", line 4, in import yaml ModuleNotFoundError: No module named 'yaml'
> 
> ERR Python ➜ bombcrypto-bot git:(main) python index.py Traceback (most recent call last): File "index.py", line 2, in from src.logger import logger, loggerMapClicked ImportError: No module named src.logger
> 
> Agradeço o help o/

Confere os passos da instalação do bot e ve se você instalou as dependencias corretamente.
`pip install -r requirements.txt`

**Comment by alanlucena** [comment]
Meu problema é com o pyautogui, sempre da erro na importação dele

```
Starting index.py
Traceback (most recent call last):
  File "index.py", line 9, in <module>
    import pyautogui
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.8/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'

```

**Comment by piagja** [comment]
> 

Tudo devidamente instalado.
Não entendo por que não consigo rodar o bot. Ta fazendo muita falta esses dias que tenho que ficar no Linux trampando.

**Comment by martinsssgabriel** [comment]
gente, acredito que esse video vá ajudar vcs
https://www.youtube.com/watch?v=KTHbFm_IyAc&t=313s&ab_channel=AchaJogo
