### ISSUE TITLE
Ao rodar multi-acc em linux, erro em PyGetWindow + ofereço ajuda pra melhorias no código

### ISSUE THREAD

**Issue by hugolfreitas** [mpcabete/bombcrypto-bot#656]
> @mpcabete primeiramente **muito obrigado** pelo código disponibilizado, ta sendo muito útil e já até fiz minha **doação** de alguns dolares como agradecimento e estou encorajando amigos á fazerem o mesmo.

Tenho um pouco de conhecimento com python e adaptei o código para multi accounts usando a dica do proprio dev.
porém essa lib PyGetWindow não está funcionando em linux (ubuntu), e gostaria de saber se alguem tem uma dica para resolver isso ou alguma outra lib que faz o mesmo, só que pra linux, para que eu possa arrumar isso aqui no código e disponibilizar pro pessoal também.

Erro ao rodar o código:

> /usr/local/lib/python3.6/dist-packages/pygetwindow/__init__.py in <module>()
> 40     Window = Win32Window
> 41 else:
> ---> 42     raise NotImplementedError('PyGetWindow currently does not support Linux. If you have Xlib knowledge, please contribute! https://github.com/asweigart/pygetwindow')
>

**Comment by hugolfreitas** [comment]
só encontrei isso aqui de decente sobre o problema:
https://github.com/asweigart/pyautogui/issues/291

mas não resolveu ainda

**Comment by fguide** [comment]
Já tem várias versões rodando por aí com suporte a multiaccount em linux.

Só olhar nos PRs https://github.com/mpcabete/bombcrypto-bot/pulls

**Comment by cleitonleonel** [comment]
Tenho um pouco de conhecimento com python e adaptei o código para multi accounts usando a dica do proprio dev. porém essa lib PyGetWindow não está funcionando em linux (ubuntu), e gostaria de saber se alguem tem uma dica para resolver isso ou alguma outra lib que faz o mesmo, só que pra linux, para que eu possa arrumar isso aqui no código e disponibilizar pro pessoal também.

https://github.com/cleitonleonel/bombcrypto-bot fiz essa versão com suporte a multijanelas no windows e linux, de duas maneiras sendo 1 utilizando a função tab e outra em um modo nativo, no windows utilizando PyGetWindow e no linux com as libs xdotool e wmctrl ambas instaladas com "sudo apt install <lib_package>"....

**Comment by cleitonleonel** [comment]
> > @mpcabete primeiramente **muito obrigado** pelo código disponibilizado, ta sendo muito útil e já até fiz minha **doação** de alguns dolares como agradecimento e estou encorajando amigos á fazerem o mesmo.
> 
> Tenho um pouco de conhecimento com python e adaptei o código para multi accounts usando a dica do proprio dev. porém essa lib PyGetWindow não está funcionando em linux (ubuntu), e gostaria de saber se alguem tem uma dica para resolver isso ou alguma outra lib que faz o mesmo, só que pra linux, para que eu possa arrumar isso aqui no código e disponibilizar pro pessoal também.
> 
> Erro ao rodar o código:
> 
> > /usr/local/lib/python3.6/dist-packages/pygetwindow/**init**.py in ()
> > 40     Window = Win32Window
> > 41 else:
> > ---> 42     raise NotImplementedError('PyGetWindow currently does not support Linux. If you have Xlib knowledge, please contribute! https://github.com/asweigart/pygetwindow')

https://github.com/cleitonleonel/bombcrypto-bot fiz essa versão com suporte a multijanelas no windows e linux, de duas maneiras sendo 1 utilizando a função tab e outra em um modo nativo, no windows utilizando PyGetWindow e no linux com as libs xdotool e wmctrl ambas instaladas com "sudo apt install <lib_package>"....

**Comment by cleitonleonel** [comment]
```python3
def run_command(command):
    output, error = subprocess.Popen(command,
                                     stdout=subprocess.PIPE,
                                     stderr=subprocess.PIPE,
                                     shell=True).communicate()
    result = output.decode().strip()
    return result.split("\n")


def get_windows_with_title(title, only_id=False):
    if only_id:
        return run_command(f"xdotool search --name {title}")
    windows_list = [w.split() for w in run_command(" ".join(["wmctrl", "-lG"]))]
    windows_with_title = [
        {"id": int(w[0], 16), "is_minimized": all([
            "_NET_WM_STATE_HIDDEN" not in run_command(" ".join(["xprop", "-id", w[0]])),
            "_NET_WM_WINDOW_TYPE_NORMAL" in run_command(" ".join(["xprop", "-id", w[0]]))]),
         "application": " ".join(w[-2:]).replace("–", "").lstrip(), "title": w[7]
         } for w in windows_list if title in w[7]]

    return windows_with_title


def activate_window(window_id):
    return run_command(f"xdotool windowactivate {window_id}")


def get_window_title():
    return run_command("xdotool getactivewindow getwindowname")[0]
```

**Comment by hugolfreitas** [comment]
valeuuuu galera, vou testar isso em breve, mt obrigado!
