### ISSUE TITLE
[Dúvida] Virtual Desktop para multi account 

### ISSUE THREAD

**Issue by luizsergiorf** [mpcabete/bombcrypto-bot#658]
Boa tarde pessoal, queria tirar uma dúvida com vocês, seria viável utilizar o recurso de Virtual Desktop do Windows ou Linux para conseguir a multi account. Assim executaria cada desktop um perfil diferente do navegador e com o bot independente. 

Alguém já testou essa solução?

**Comment by fguide** [comment]
Eu acredito que não uma vez que virtual desktops nao tem controle de mouse individuais, por enquanto a melhor alternativa é setar o VNC server com várias sessoes, cada uma é independente e funciona sem depender da outra.

Não sei se é possível multisessao VNC no windows, no Linux posso afirmar que é.

**Comment by monacothi** [comment]
Não é possível usar o RDP para multisession, exceto em versões específicas do windows, como as server, por exemplo. E mesmo assim, as conexões simultâneas ficam limitadas pela quantidade de licenças disponíveis na máquina.

**Comment by fguide** [comment]
RDP multisessao só com TS, mas VNC talvez seja possível...

Como disse, no linux tenho certeza que funciona, no windows nunca testei.

**Comment by luizsergiorf** [comment]
> Eu acredito que não uma vez que virtual desktops nao tem controle de mouse individuais, por enquanto a melhor alternativa é setar o VNC server com várias sessoes, cada uma é independente e funciona sem depender da outra.
> 
> Não sei se é possível multisessao VNC no windows, no Linux posso afirmar que é.

Boa noite, obrigado por responder. Vou tentar utilizar o VNC. Criei uma VM em lubuntu com o Vmware Player e vou instalar o VNC. Consigo criar múltipla instancia com perfil de usuários diferentes no linux? Assim consigo utilizar o firefox com multiplos usuários.

**Comment by fguide** [comment]
Consegue sim, algumas sugestões:

Use tigervnc, dá pra colocar os usuários (do linux) no arquivo de configuracao e atribuir uma sessão pra cada
Sugiro usar nas sessoes do VNC um gerenciador de janela (openbox, i3) pra sessão gráfica é mais que suficiente e não carrega todo um DE e fica bem mais eficiente
Depois de pronto instalar o novnc pra gerenciar via html5, dai vc acessa de quaquer dispositivo que suporte html5

Um guia pra ajudar:
https://wiki.archlinux.org/title/TigerVNC

**Comment by luizsergiorf** [comment]
> Consegue sim, algumas sugestões:
> 
> Use tigervnc, dá pra colocar os usuários (do linux) no arquivo de configuracao e atribuir uma sessão pra cada Sugiro usar nas sessoes do VNC um gerenciador de janela (openbox, i3) pra sessão gráfica é mais que suficiente e não carrega todo um DE e fica bem mais eficiente Depois de pronto instalar o novnc pra gerenciar via html5, dai vc acessa de quaquer dispositivo que suporte html5
> 
> Um guia pra ajudar: https://wiki.archlinux.org/title/TigerVNC

Obrigado pela ajuda, estou fazendo as configurações, estou na dúvida onde eu configuro para criar mais sessões e atribuir a cada usuário. Estava seguindo alguns tutorial e na parte de de configurar para inciar junto com o boot, o arquivo systemd, fiquei perdido onde atribuir as sessões para cada usuario.  Segue um arquivo que eu encontrei de configuração:

```
[Unit]
Description=Start TigerVNC server at startup
After=syslog.target network.target
[Service]
Type=forking
User=YOUR_USERNAME
Group=YOUR_USERNAME
WorkingDirectory=/home/YOUR_USERNAME
PIDFile=/home/YOUR_USERNAME/.vnc/%H:%i.pid
ExecStartPre=-/usr/bin/vncserver -kill :%i > /dev/null 2>&1
ExecStart=/usr/bin/vncserver -depth 24 -geometry 1280x800 -localhost :%i
ExecStop=/usr/bin/vncserver -kill :%i
[Install]
WantedBy=multi-user.target
```

**Comment by fguide** [comment]
Na verdade não seria no unit do systemd, e sim no arquivo /etc/tigervnc/vncserver.users, exemplo:

:1=user1
:2=user2
:3=user3

o primeiro parametro é o numero da sessao, user 1 roda na porta 5901, user2 na 5902, e por ai vai.

No systemd vc faz só a chamada pro vncserver mesmo.
