### ISSUE TITLE
Mapas Farmados...

### ISSUE THREAD

**Issue by pegchargue** [mpcabete/bombcrypto-bot#659]
Seria mais uma sugestão... Seria possível colocar um contador de mapas fechados? Assim poderíamos saber quantos mais foram feitos em 24h e quantos bcoins foram minerados nesses mapas... Desde já valeu pela ajuda!!!

**Comment by rafaelrabaco** [comment]
Dentro da pasta logs tem a data e hora que foi concluido cada mapa...
Não é um contador, mas da pra contar manualmente

**Comment by pegchargue** [comment]
Valeu, obrigado pela informação!!!!

**Comment by pegchargue** [comment]
> Dentro da pasta logs tem a data e hora que foi concluido cada mapa... Não é um contador, mas da pra contar manualmente

Valeu, obrigado pela informação!!

**Comment by kelvinkrisna** [comment]
Acho que não vai te dar um valor preciso... pois a mensagem agora fecha automatica em 10 segundos
ou teria que diminuir o tempo de check de novo mapa para menos de 10 segundos onerando o processamento.
