### ISSUE TITLE
Erro ao executar no VPS Linux Ubuntu

### ISSUE THREAD

**Issue by klaylton** [mpcabete/bombcrypto-bot#660]
Criei uma instância do Ubuntu 20.04 na Vultr. Fiz a instalação do ubuntu-desktop e tentei rodar o bot, no entanto, me deparei com o seguinte erro (ver imagem). Já fiz diversas tentativas, mas sem sucesso.

![erro](https://blogger.googleusercontent.com/img/a/AVvXsEgY1SG4yvbkIDPNpJS4T0OVBL0CYVAvf8Y2tGWbqrAINh54ykBStHqhHaEyemlCl3nH5LwIreBAXey_1y15UtSUket2EbrQzPhGMiwc73UJQu3w8NJV9ulV4Jh4tbAwAlnhXkYyIT06vwOpRSkmZEbBC6EGrrmtoo-HG3g6A05Rwk2nCtTazZwa8xAvqQ)

**Comment by fguide** [comment]
Verifique a configuracao no xorg.conf, deve estar em 16bit, precisa ser 24 ou 32.

**Comment by klaylton** [comment]
Pode me dar instruções de como fazer isso?

**Comment by fguide** [comment]
Geralmente o color depth é 24 por padrao, com que SW vc acessa remot? Talvez ele esteja fazendo essa modificação.

Qual o resultado do comando:

> xwininfo -root | grep Depth

**Comment by klaylton** [comment]
Ta saindo: xwininfo: error: unable to parse display name ""

**Comment by fguide** [comment]
Não encontrou o display pelo visto. Nao conheço a Vultr, talvez tenha que fazer uma config pra habilitar display remoto..

Como você acessa a máquina? Via SSH? Algum outro software?

**Comment by klaylton** [comment]
Estou usando o NoMachine. Você pode me recomendar outro server que tenha suporte?

**Comment by fguide** [comment]
Ah, certamente o problema está no NoMachine, nao sei como mudar as configurações de video porque não utilizo, eu sugiro que você utilize o VNC, posteriormente você pode ate configurar o noVNC e acessar via navegador. Veja um tutorial na Vultr pra isso abaixo. Ou tente encontrar onde mudar as configurações de video no NoMachine, geralmente é aumentado a qualidade (porém pode deixar a conexao mais lenta)

https://www.vultr.com/docs/install-gui-environment-for-ubuntu

**Comment by klaylton** [comment]
@fguide, segui o tutorial, conseguir acessar a interface, mas o erro continua. Estou a vasculhar a internet a procura de uma solução. Se eu conseguir resolver, volto aqui pra relatar.

**Comment by fguide** [comment]
Qual gerenciador de janela ta usando? o XFCE?

o que sai do comando: 

> echo $DISPLAY

**Comment by Zwep951** [comment]
fguide estou com o mesmo problema que ele só que o comando deu resposta xwininfo -root | grep Depth      Deu a seguinte resposta:
![image](https://user-images.githubusercontent.com/98366404/150893959-5218ed9d-2b03-4701-8ba6-f7b2d5a6a823.png)

**Comment by Zwep951** [comment]
@fguide estou com o mesmo problema que ele só que o comando deu resposta xwininfo -root | grep Depth Deu a seguinte resposta
![Sem título](https://user-images.githubusercontent.com/98366404/150897131-36b5d85e-ee3b-4cbf-9e2a-f331ba065be1.png)
: mas o meu echo $DISPLAY foi :0

**Comment by klaylton** [comment]
@fguide a resposta do meu ao executar o comando `echo $DISPLAY` foi `:0`.

Ao rodar: `xwininfo -root | grep Depth`
Resposta:  `Depth: 16`

**Comment by fguide** [comment]
Acredito que vocês estejam usando o Wayland, tente rodar 
> echo $XDG_SESSION_TYPE

É indicado usar o Xorg no lugar de wayland por conta de problemas de compatibilidade entre o mss e wayland

**Comment by klaylton** [comment]
O resultado foi `x11`.

Existe ao que posso fazer para mudar?

**Comment by fguide** [comment]
De fato está usando X11, você pode configurar o xorg como abaixo, apenas ignore a parte do virtualbox:

https://www.maketecheasier.com/set-ubuntu-guest-to-32-bit-display-in-virtualbox/

**Comment by Zwep951** [comment]
@fguide Na segunda linha **Device        "VirtualBox graphics card"** Mantém? ou retira ?

**Comment by fguide** [comment]
Pode colocar o nome que quiser nas linhas Identifier, device e monitor, é só descriçao, as outras mantem igual.

Lembrando que caso der algum erro ao reiniciar, é preciso acessar via ssh e apagar o arquivo para voltar ao normal.

**Comment by klaylton** [comment]
Tentei executar o comando do tutorial, mas retornou o seguinte:

**comando:** `gksu gedit /etc/X11/xorg.conf`
**output:**
Command 'gksu' not found, did you mean:

  command 'gosu' from deb gosu (1.10-1ubuntu0.20.04.1)
  command 'ksu' from deb krb5-user (1.17-6ubuntu4.1)
  command 'ksu' from deb heimdal-clients (7.7.0+dfsg-1ubuntu1)

Try: apt install <deb name>`

**Comment by Zwep951** [comment]
> Tentei executar o comando do tutorial, mas retornou o seguinte:
> 
> **comando:** `gksu gedit /etc/X11/xorg.conf`
> **output:**
> Command 'gksu' not found, did you mean:
> 
>   command 'gosu' from deb gosu (1.10-1ubuntu0.20.04.1)
>   command 'ksu' from deb krb5-user (1.17-6ubuntu4.1)
>   command 'ksu' from deb heimdal-clients (7.7.0+dfsg-1ubuntu1)
> 
> Try: apt install <deb name>`

Olha eu coloquei e funcionou testa assim:
gedit /etc/X11/xorg.conf

Estou com o bot ativo está funcionando perfeitamente lá na vps

**Comment by klaylton** [comment]
@Zwep951 vc contratou o vps em qual empresa. Estou tentando na Vultr e até agora não consegui. 
rodei `gedit /etc/X11/xorg.conf` e o resultado foi:

```
Unable to init server: Could not connect: Connection refused

(gedit:34301): Gtk-WARNING **: 22:40:19.618: cannot open display:
```

**Comment by Zwep951** [comment]
@bboyguil Estou rodando no kronichostbrasil em um servidor no canada onde que é mais barato.
