### ISSUE TITLE
Baus / Blocos Indestrutíveis

### ISSUE THREAD

**Issue by ldayrell** [mpcabete/bombcrypto-bot#661]
É possível de fazer uma função que da "ctrl+f5" caso o botão de "new map" não seja detectado em X minutos? Não tenho a expertise para tal..

Atualmente esta tendo um bug onde alguns blocos não se destroem por nada. Este problema confundiu o bot e deixou meu farm parado a madrugada toda tentando passar do mesmo mapa, gastando a energia de todos os meus heróis.

**Comment by fguide** [comment]
Isso é bug do jogo, não faz sentido implementar algo que em teoria será corrigido pela empresa.

Em tempo, tente essa versão, ela faz reload toda vez que acha um novo mapa.

https://github.com/afkapp/bombcrypto-bcbot

**Comment by tiagocostafx** [comment]
Estou com o mesmo problema. Espero que arrumem logo esse bug. @ldayrell você está usando vm?

**Comment by RonaldoPerini** [comment]
https://www.youtube.com/watch?v=BWXwS7l6vfw, assistam... resolveu

**Comment by ldayrell** [comment]
> Estou com o mesmo problema. Espero que arrumem logo esse bug. @ldayrell você está usando vm?

Estou não. Usando no pc normalmente.

**Comment by ldayrell** [comment]
> https://www.youtube.com/watch?v=BWXwS7l6vfw, assistam... resolveu

Eu acabei mexendo ontem o dia inteiro no código do python (mesmo sem muita noção) e consegui fazer o bot dar crtl+f5 a cada X minutos.. aí quando ele da new map ele zera o cronometro. Mas a solução do vídeo também é ótima. Obrigado por compartilhar amigo.

**Comment by fguide** [comment]
Não era mais fácil enviar um ctrl+f5 junto a funcao de refresh heroes ou mesmo de login?

Nao sou favoravel ao uso de extensoes de navegador desnecessárias, cada coisa a mais aumenta seu risco.

Lembrem que a carteira de vocês também é uma extensão do navegador, mesmo que essa extensão em si nao seja maliciosa ela pode abrir brechas para dar acesso indevido às informacoes de vocês...

**Comment by RonaldoPerini** [comment]
> Não era mais fácil enviar um ctrl+f5 junto a funcao de refresh heroes ou mesmo de login?
> 
> Nao sou favoravel ao uso de extensoes de navegador desnecessárias, cada coisa a mais aumenta seu risco.
> 
> Lembrem que a carteira de vocês também é uma extensão do navegador, mesmo que essa extensão em si nao seja maliciosa ela pode abrir brechas para dar acesso indevido às informacoes de vocês...

super estou de acordo, o problema de quem nao manja de python fica a deriva :/

**Comment by fguide** [comment]
Aproveite que nao se usa mais a função do captcha e faça o seguinte:

Altere no config.yaml o parametro check_for_captcha na quantidade de minutos pra fazer reload.

Altere o index.py adicionando a linha abaixo depois da linha 492, vai ficar assim:

> pyautogui.hotkey('ctrl','f5')

```
        if now - last["check_for_captcha"] > addRandomness(t['check_for_captcha'] * 60):
            last["check_for_captcha"] = now
            pyautogui.hotkey('ctrl','f5')
```

Imagino que seja o mesmo comportamento da extensão direto no script, vai fazer ctrl+f5 a cada x minutos.

**Comment by RonaldoPerini** [comment]
> Aproveite que nao se usa mais a função do captcha e faça o seguinte:
> 
> Altere no config.yaml o parametro check_for_captcha na quantidade de minutos pra fazer reload.
> 
> Altere o index.py adicionando a linha abaixo depois da linha 492, vai ficar assim:
> 
> > pyautogui.hotkey('ctrl','f5')
> 
> ```
>         if now - last["check_for_captcha"] > addRandomness(t['check_for_captcha'] * 60):
>             last["check_for_captcha"] = now
>             pyautogui.hotkey('ctrl','f5')
> ```
> 
> Imagino que seja o mesmo comportamento da extensão direto no script, vai fazer ctrl+f5 a cada x minutos.

muito obrg, vou testar agr!

**Comment by isacsg** [comment]
> Aproveite que nao se usa mais a função do captcha e faça o seguinte:
> 
> Altere no config.yaml o parametro check_for_captcha na quantidade de minutos pra fazer reload.
> 
> Altere o index.py adicionando a linha abaixo depois da linha 492, vai ficar assim:
> 
> > pyautogui.hotkey('ctrl','f5')
> 
> ```
>         if now - last["check_for_captcha"] > addRandomness(t['check_for_captcha'] * 60):
>             last["check_for_captcha"] = now
>             pyautogui.hotkey('ctrl','f5')
> ```
> 
> Imagino que seja o mesmo comportamento da extensão direto no script, vai fazer ctrl+f5 a cada x minutos.

Funcionou perfeitamente aqui, muito obrigada @fguide

**Comment by kendikaku** [comment]
> Aproveite que nao se usa mais a função do captcha e faça o seguinte:
> 
> Altere no config.yaml o parametro check_for_captcha na quantidade de minutos pra fazer reload.
> 
> Altere o index.py adicionando a linha abaixo depois da linha 492, vai ficar assim:
> 
> > pyautogui.hotkey('ctrl','f5')
> 
> ```
>         if now - last["check_for_captcha"] > addRandomness(t['check_for_captcha'] * 60):
>             last["check_for_captcha"] = now
>             pyautogui.hotkey('ctrl','f5')
> ```
> 
> Imagino que seja o mesmo comportamento da extensão direto no script, vai fazer ctrl+f5 a cada x minutos.

bom dia,

onde eu consigo fazer essa alteração no bot abaixo?

https://github.com/MatheusHAS/bombcrypto-bot

eu nao entendi muito bem como alterar.

**Comment by kendikaku** [comment]
> > Aproveite que nao se usa mais a função do captcha e faça o seguinte:
> > Altere no config.yaml o parametro check_for_captcha na quantidade de minutos pra fazer reload.
> > Altere o index.py adicionando a linha abaixo depois da linha 492, vai ficar assim:
> > > pyautogui.hotkey('ctrl','f5')
> > 
> > 
> > ```
> >         if now - last["check_for_captcha"] > addRandomness(t['check_for_captcha'] * 60):
> >             last["check_for_captcha"] = now
> >             pyautogui.hotkey('ctrl','f5')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Imagino que seja o mesmo comportamento da extensão direto no script, vai fazer ctrl+f5 a cada x minutos.
> 
> bom dia,
> 
> onde eu consigo fazer essa alteração no bot abaixo?
> 
> https://github.com/MatheusHAS/bombcrypto-bot
> 
> eu nao entendi muito bem como alterar.

Alguém pra me ajudar?

**Comment by kendikaku** [comment]
> > https://www.youtube.com/watch?v=BWXwS7l6vfw, assistam... resolveu
> 
> Eu acabei mexendo ontem o dia inteiro no código do python (mesmo sem muita noção) e consegui fazer o bot dar crtl+f5 a cada X minutos.. aí quando ele da new map ele zera o cronometro. Mas a solução do vídeo também é ótima. Obrigado por compartilhar amigo.

Dá um help ai, não sei nada de Python
