### ISSUE TITLE
como usar o bot em vm em resolução fora da padrão 

### ISSUE THREAD

**Issue by manotroll** [mpcabete/bombcrypto-bot#663]
tem alguma forma de usar ele em resolução fora do padrão 1080P ?
e pra rodar na vm ja que no momento ainda não tenho um 2 pc disponível pra deixar rodando

**Comment by fguide** [comment]
Se vc vai rodar em VM é só fazer uma com resolucao "padrao"...

**Comment by fguide** [comment]
Em tempo, não é que só funciona em 1080P, esse é o limite máximo de resolucao, da pra usar 1366x768, 1152x864, 1024x768 (dependendo das configs, navegador, etc) e por aí vai.

**Comment by manotroll** [comment]
bem eu consegui fazer rodar mais ficou uma duvida coloquei em 1080P mesmo a resolução remota
quando eu minimizo a vm eu tiro a seta do mause dela a duvida e continua funcionando ?

**Comment by fguide** [comment]
> bem eu consegui fazer rodar mais ficou uma duvida coloquei em 1080P mesmo a resolução remota quando eu minimizo a vm eu tiro a seta do mause dela a duvida e continua funcionando ?

Sim, é pra funcionar normalmente. Sugiro também desabilitar a integração de mouse no virtualbox, assim o mouse da VM não corre o risco de ser capturado pelo mouse da maquina host por engano.
