### ISSUE TITLE
Problema de rolagem tendo poucos bonecos

### ISSUE THREAD

**Issue by jaonetu** [mpcabete/bombcrypto-bot#666]
Estou com uma conta com apenas 4 bonecos, e quando ele arrasta pra baixo procurando outros bonecos ele volta pra cima e fica repetidamente apertando work no mesmo personagem, algum jeito de tirar a rolagem?

**Comment by fguide** [comment]
Edite o parameto scroll_attempt para 1 no arquivo config.yaml

**Comment by leandrodoc** [comment]
Boas pessoal, o meu acontece ao contrário, ele parou de procurar a baixo! O que faço? Obrigado

**Comment by fguide** [comment]
> Boas pessoal, o meu acontece ao contrário, ele parou de procurar a baixo! O que faço? Obrigado

@leandrodoc 
Seu problema provavelmente é o mesmo do #649
