### ISSUE TITLE
 missing the target

### ISSUE THREAD

**Issue by KcassPr** [mpcabete/bombcrypto-bot#667]
Hello, the bot works normally, but when it finds the target, it goes to it but misses, clicking between "WORK" and "REST". The image is correct and updated in the Targets folder.

**Comment by leandrodoc** [comment]
![go-work](https://user-images.githubusercontent.com/47541461/150548932-d601fbdc-24fe-463d-95eb-8c9509ca9d7b.png)

**Comment by KcassPr** [comment]
I think I understand the problem, I put an image with the stamina bar with about 80%. Because of that, and I don't know how, but when the bot has a larger image (like the bar) the mouse doesn't hit the target. I need to place a smaller image or decrease it gradually until the bot hits the "WORK" button. So this has to do with the image itself, the bigger the green bar you put, the further to the right the pointer will go.

PT-BR * Acho que entendi o problema, eu coloquei uma imagem com a barra da stamina com uns 80%. Por causa disso, e não sei como, mas o bot ao ter uma imagem maior (como a barra) o mouse não acerta o alvo. Preciso colocar uma imagem menor ou ir diminuindo ela gradativamente ate que o bot acerte o Botão "WORK". Então isso tem haver com a imagem em si, quanto maior a barra verde que você colocar, mais para a Direita o ponteiro irá.

**Comment by leandrodoc** [comment]
Yes! You need adjust the picture for bot, they has chamged too the word WORK.
