### ISSUE TITLE
Bot em loop em heroes que estão trabalhando 

### ISSUE THREAD

**Issue by ghmmiranda** [mpcabete/bombcrypto-bot#668]
E ai mans, 2 coisas estão acontecendo. 1ºao verificar se existe heroes disponíveis para trabalhar, o bot ele sempre clica nos que estão trabalhando independente se tenha novos heroes aptos. 2º que quando chega la embaixo e tiver algum heroe que esteja trabalhando ele fica clicando e rolando para baixo e fica nesse loop infinito sem sair dali. Me ajudem pls.

**Comment by leandrodoc** [comment]
Boas, verifique se as imagens estão atualizadas com o Bomb, eu percebi que houve ligeiras alterações principalmente no botão WORK, caso seja o seu tire novos prints e substitua na pasta targets e quanto ao scroll segua aqui uma correção que podes fazer Edite o parameto scroll_attempt para 1 no arquivo config.yaml

**Comment by ghmmiranda** [comment]
Vlw mano, irei fazer o teste e trago um feedback.

**Comment by ghmmiranda** [comment]
Deu certo, vlw
