### ISSUE TITLE
Google Cloud - Ajuda

### ISSUE THREAD

**Issue by Gbrtenorio** [mpcabete/bombcrypto-bot#67]
Boa madrugada amigo

Primeiramente parabéns pelo Bot :) . Entendo bastante de Python e consigo ver que o código está bem safe hehe

Estou rodando o Bot em uma Google Cloud Plataform em um linux com Google Chrome...
Meu problema é: Quando estou com a aba aberta acessando remotamente a VM do Cloud, o bot funciona perfeitamente.... Mas quando fecho a aba, o Bot só consegue voltar pra tela inicial do bomb e não acha personagem.

Alguma dica? Abs!

**Comment by mpcabete** [comment]
Não acha personagem vc diz nao envia os herois pra trabalhar?
na minha eu tive que desabilitar a opçao de desligar a tela do pc dps de um tempo de inatividade nas opçoes de energia. Talvez seja uma boa tentar isso

**Comment by fguide** [comment]
Esse problema é por conta de acessar via remote desktop, você pode utilizar o VNC como sugeriram ou utilizar o comando abaixo toda vez que desconectar da VM, o único ponto é que ele mantem a sessão aberta, se for um provedor privado não há tanto risco de segurança.

for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (tscon.exe %%s /dest:console)

Esse comando envia a sessão RDP para o console, e assim ela fica ativa com o bot rodando. Fica a dica para quando sair a versão corrigida.

**Comment by rodrigofc93** [comment]
> Esse problema é por conta de acessar via remote desktop, você pode utilizar o VNC como sugeriram ou utilizar o comando abaixo toda vez que desconectar da VM, o único ponto é que ele mantem a sessão aberta, se for um provedor privado não há tanto risco de segurança.
> 
> for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (tscon.exe %%s /dest:console)
> 
> Esse comando envia a sessão RDP para o console, e assim ela fica ativa com o bot rodando. Fica a dica para quando sair a versão corrigida.

Boa tarde, sabe me dizer como fazer isso no windows? Não consegui configurar o vnc
