### ISSUE TITLE
erro desconhecido preciso de ajuda 

### ISSUE THREAD

**Issue by rafaell02** [mpcabete/bombcrypto-bot#671]
ModuleNotFoundError: No module named 'yaml' 

essa mensagem aparece pra mim no cmd, segui os passo a passo corretamente , alguem pode me ajudar ?

**Comment by rafaell02** [comment]
C:\bomb>python3 index.py
Traceback (most recent call last):
  File "index.py", line 2, in <module>
    from src.logger import logger, loggerMapClicked
  File "C:\bomb\src\logger.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

aqui todas as informações do erro

**Comment by leandrodoc** [comment]
Boas, você fez a atualização no CMD "pip install -r requirements.txt" como administrador?
