### ISSUE TITLE
Bot não está colocando para trabalhar

### ISSUE THREAD

**Issue by viniciuspgng** [mpcabete/bombcrypto-bot#673]
Mais alguém está com problemas com o bot para colocar pra trabalhar?
os meus não estão indo mais.

**Comment by leandrodoc** [comment]
Boas, como assim? explica melhor!

**Comment by viniciuspgng** [comment]
> Boas, como assim? explica melhor!

Boa tarde! Cara, o bot não está colocando pra trabalhar os heróis, desde a última atualização do bomb. O bot abre a tela dos players roda o scroll mas nao clica no work, mesmo com energia 100%

**Comment by viniciuspgng** [comment]
Apenas complementando, eu tinha instalado pra um amigo, e está acontecendo o mesmo com ele

**Comment by leandrodoc** [comment]
![go-work](https://user-images.githubusercontent.com/47541461/150655089-6ebbaf86-a02d-42ba-9f92-fdc58bd34f1b.png)

**Comment by leandrodoc** [comment]
Veja se a palavra WORK do seu bot está igual a essa?
Eles mudaram depois da atualização, é somente substituir na pasta targets

**Comment by viniciuspgng** [comment]
> Veja se a palavra WORK do seu bot está igual a essa? Eles mudaram depois da atualização, é somente substituir na pasta targets

Está assim:
![image](https://user-images.githubusercontent.com/17165077/150661541-3b594233-c333-4388-9ac3-86c2cdc2bf51.png)

vou trocar por essa que você mandou pra ver, obrigado!

**Comment by leandrodoc** [comment]
Vai dar certo!

**Comment by HlDANN** [comment]
Estou com o mesmo problema, minha imagem está certa. Ele rola a lista e não coloca pra trabalhar

**Comment by leandrodoc** [comment]
Boas, está em qual idioma? Verifica se as imagens da sua barra verde está igual a do jogo!

**Comment by HlDANN** [comment]
> Boas, está em qual idioma? Verifica se as imagens da sua barra verde está igual a do jogo!

Resolvi o problema! O idioma estava correto, ele não estava detectando o botão "Work" então tirei print da minha tela e substitui. Aconselho quem mais estiver com esse tipo de problema a tirar print da própria tela e não baixar de outras.
Apesar disso me deparei com outro problema hoje.
Quando o BHERO está com a barra verde e está em último na lista, o bot não está reconhecendo a barra verde. Dessa vez tirar print da minha tela e substituir não funcionou :/

**Comment by leandrodoc** [comment]
Entendi, faz o seguinte 
![Captura de ecrã 2022-01-30 230809](https://user-images.githubusercontent.com/47541461/151721810-ca1136ce-0bcc-4b87-bd72-623501e863dd.png)

Substitua essa imagem pela a common.png.
O que está acontecendo, o bot para fazer scroll ele usa a imagem common que é dos bombers comuns, no caso como temos outras variedades tipo raro etc ele não roda o scroll, mas com a imagem LV ele vai procurar em todos.

**Comment by HlDANN** [comment]
Entendi, agora que você falou eu lembrei, o bomber que ficou por último era raro. Vou fazer a substituição e checar se vai funcionar. Obrigado. @leandrodoc

**Comment by HlDANN** [comment]
> Entendi, faz o seguinte ![Captura de ecrã 2022-01-30 230809](https://user-images.githubusercontent.com/47541461/151721810-ca1136ce-0bcc-4b87-bd72-623501e863dd.png)
> 
> Substitua essa imagem pela a common.png. O que está acontecendo, o bot para fazer scroll ele usa a imagem common que é dos bombers comuns, no caso como temos outras variedades tipo raro etc ele não roda o scroll, mas com a imagem LV ele vai procurar em todos.

Então, olhando aqui pelos meus targets só encontrei a imagem commom-text.png. Após fazer a substituição por está, ele parou de rodar a página. Corrigindo o que havia falado, realmente aparece o LV na listagem, porém meu bot nao estava reconhecendo. Vou tentar tirar print da minha tela.

**Comment by leandrodoc** [comment]
ok

**Comment by HlDANN** [comment]
> ok

Funcionou, parece que utilizar print da propria tela é o melhor caminha. Obrigado pela ajuda!

**Comment by leandrodoc** [comment]
Ah sim pois tem diferença nas cores e resolução, desculpas pelo enviou não levei isso em conta!
