### ISSUE TITLE
BOT PARA CASA 

### ISSUE THREAD

**Issue by Sp3cTr3r0x** [mpcabete/bombcrypto-bot#678]
Gostaria de algumas alteraçoes no BOT para versão com casa.
Quem conseguir fazer a alteraçao que preciso me chame....

Telegram - @amartins1984

Att

**Comment by fguide** [comment]
Seria mais fácil dizer o que você quer e talvez alguém já tenho algo pronto para compartilhar, meio difícil precisar de algo e pedir para entrarem em contato com você...
