### ISSUE TITLE
Estamina

### ISSUE THREAD

**Issue by RMFilho** [mpcabete/bombcrypto-bot#679]
Teria como alterar o bot para ele mandar farmar só quando herói tiver 50 de estamina?

Os meus quando fica verde ele já coloca e vai mto rápido a estamina deles tenho só 10 herói sendo 1 raro e 9 comum!

**Comment by KcassPr** [comment]
Eu tentei mudar a imagem "green-bar" em targets, mas se voce fizer isso, não sei porque, mas o Bot começa a errar o botão WORK, e pode dar problema. Tenta ai, muda a imagem green-bar para uma em que a stamina esteja em 50%, mas fique de olho para ver como o Bot irá agir.

**Comment by RMFilho** [comment]
> Eu tentei mudar a imagem "green-bar" em targets, mas se você fizer isso, não sei porque, mas o Bot começa a errar o botão WORK, e pode dar problema. Tenta ai, muda a imagem green-bar para uma em que a resistência seja em 50%, mas fique de olho para ver como o Bot agir.

Eu mudei a minha mas acho que não mudou nada pq quando fica verde ele coloca pra trabalhar!

**Comment by KcassPr** [comment]
Eu acho que nesse Bot em especifico, não tem como mudar muita coisa, ou deixar muito especifico, eu tambem queria que ele só colocasse pra trabalhar depois dos 80% da Stamina, mas acho q nao tem como :(

**Comment by KcassPr** [comment]
o máximo que eu consegui foi esse.. mais que isso, o bot erra o botão.
![green-bar](https://user-images.githubusercontent.com/98131972/150712327-5ec65b67-9fa7-4b2e-8101-dc953f6339c5.png)

**Comment by fguide** [comment]
Já tem tudo isso discutido aqui, só precisa pesquisar...

#544

A parte de enviar apenas comuns, raros, etc, também foi discutida em: #527
