### ISSUE TITLE
Suporte a propaganda do Brave

### ISSUE THREAD

**Issue by feLiruc** [mpcabete/bombcrypto-bot#68]
Eu não sei quem mais ai utiliza o navegador Brave pra jogar, ou pra navegar na internet mesmo, mas seria legal implementar uma opção pra ele fechar as notificações de propaganda dele, quando você aceita receber propaganda em troca de criptomoedas BAT. 
Ajudaria no farm de BAT hahaha

**Comment by mpcabete** [comment]
hahaha, eu uso o brave no dia a dia, mas meu bot eu deixo rodando no chrome mesmo.
Não sei se vou conseguir adicionar essa funcionalidade tao cedo, to meio atrasado nas atualizações que prometi pro pessoal hehehe
