### ISSUE TITLE
Blocos e baús que não destroem

### ISSUE THREAD

**Issue by Koefiel** [mpcabete/bombcrypto-bot#680]
Ei ai pessoal, estou me deparando com um provável bug do jogo onde no final do mapa quando sobram baús com pouca vida ou até mesmo somente aqueles blocos que seriam destruidos com uma unica bomba os bombs não destroem mais os blocos nem os baús e é necessário um refresh da página para voltar ao normal. Isso tem acontecido pelo menos uma vez por dia depois da ultima atualização.

https://user-images.githubusercontent.com/98292763/150707574-752617e3-d5e3-4269-9e6e-b56799ce5b5e.mp4

Não conheço muito pyton, mas como eu poderia criar uma nova ação dentro do bot pra que ele desse esse refresh na página a cada x tempo?

Qualquer ajuda agradeço.

**Comment by walterdis** [comment]
Nesse exato momento o bomb está em manutenção para correção de bugs (provavelmente esse também)
Caso não corrija, instala o Tab Reloader (extensão de browser) e coloca pra dar refresh a cada 30 minutos ;)

**Comment by kendikaku** [comment]
> Nesse exato momento o bomb está em manutenção para correção de bugs (provavelmente esse também) Caso não corrija, instala o Tab Reloader (extensão de browser) e coloca pra dar refresh a cada 30 minutos ;)

corrigiu bosta nenhuma
continua do mesmo jeito

**Comment by Koefiel** [comment]
> Nesse exato momento o bomb está em manutenção para correção de bugs (provavelmente esse também) Caso não corrija, instala o Tab Reloader (extensão de browser) e coloca pra dar refresh a cada 30 minutos ;)

Poderia dar mais detalhes de como fazer isso?

**Comment by walterdis** [comment]
> > Nesse exato momento o bomb está em manutenção para correção de bugs (provavelmente esse também) Caso não corrija, instala o Tab Reloader (extensão de browser) e coloca pra dar refresh a cada 30 minutos ;)
> 
> Poderia dar mais detalhes de como fazer isso?

Não tem segredo cara.
Procura pela extensão "Tab Reloader" no seu navegador (eu uso o chrome).
Ai tem ali o tempo que vc quer q ela espere antes de dar o reload. Seta ali e depois clica em enable.

![image](https://user-images.githubusercontent.com/1938830/150832517-d614c933-565a-44eb-a5f8-c1e08c0c7887.png)

**Comment by Koefiel** [comment]
> > > Nesse exato momento o bomb está em manutenção para correção de bugs (provavelmente esse também) Caso não corrija, instala o Tab Reloader (extensão de browser) e coloca pra dar refresh a cada 30 minutos ;)
> > 
> > 
> > Poderia dar mais detalhes de como fazer isso?
> 
> Não tem segredo cara. Procura pela extensão "Tab Reloader" no seu navegador (eu uso o chrome). Ai tem ali o tempo que vc quer q ela espere antes de dar o reload. Seta ali e depois clica em enable.
> 
> ![image](https://user-images.githubusercontent.com/1938830/150832517-d614c933-565a-44eb-a5f8-c1e08c0c7887.png)

Boa Walterdis!

Eu acabei alterando o programa, mas isso também funciona!

Valeu!
