### ISSUE TITLE
Not detecting targets

### ISSUE THREAD

**Issue by Daceqt** [mpcabete/bombcrypto-bot#682]
Hello,so after doing all the steps to install the bot it didn't work (because of target images) I tried to open the folder of the target images the bot start working there but when I open bombcrypto the mouse don't move and don't detect anything?
Is there any updated version of targeted images? 
Thank you

**Comment by cienzz** [comment]
same here, i tried it on windows 10, python 3.10
already follow the steps
- install python
- pip install -r requirements.txt
- python index.py
![2022-01-25 10_49_27-167 71 202 119 - Remote Desktop Connection](https://user-images.githubusercontent.com/10008086/150907578-946658a7-920b-4c2b-9d5e-eeeea9d20faa.png)

**Comment by fguide** [comment]
This is related to your graphic settings, follow the checklist below:

Use only 1 monitor/screen (other versions support multiscreen setups, this does not)
Screen Resolution 1920x1080 (MAXIMUM, can be smaller than this)
Screen Scaling: 100% (or 1 in some linux DEs)
Zoom browser: 100% (no more nor less)
Game language: English (if you change it, the buttons are gonna be different, so you'll have to change them as well)

**Comment by Daceqt** [comment]
So the problem was my screen scale through windows was 125% thank you a lot
