### ISSUE TITLE
ERRO COM NOME DE USUARIO utf -8

### ISSUE THREAD

**Issue by zemendonca1** [mpcabete/bombcrypto-bot#683]
Estou tendo problemas com o codigo UTF -8, pois o meu nome de usuário é Zé, porém nao consigo alterar o nome do user no cmd, sempre termina assim, alguem poderia me ajudar?

**Comment by fguide** [comment]
Seria bom postar os erros que você tem.

Em teoria não precisa mudar o usuário, basta apenas colocar o bot em um diretório fora do seu usuário (C:\bot por exemplo) e setar as variáveis TEMP e TMP do seu usuário para fora do diretório do seu usuário (C:\Windows\Temp por exemplo).
