### ISSUE TITLE
Bot não executa nenhum comando

### ISSUE THREAD

**Issue by z1zzles** [mpcabete/bombcrypto-bot#684]
Ao executar o comando no terminal o bot não está clicando em nada, seguem as configurações e um print do terminal:

Sistema operacional: Mac OS Big Sur 11.6.2
Resoluções testadas: 1280x800 e 1440x900
Idioma: Inglês

Fiz o teste também no Windows 10, entretanto no Windows eu utilizo 2 monitores e um deles tem resolução maior do que 1920x1080, dificultando o uso nele. Já tentei com as configurações padrão e também com fotos dos meus próprios botões na pasta "/target", em nenhum dos casos funcionou. Já tentei diminuir um pouco o threshold, mas o resultado é semelhante, ou então o bot passa a clicar em qualquer coisa aleatoriamente.
<img width="568" alt="Screen Shot 2022-01-25 at 15 08 06" src="https://user-images.githubusercontent.com/46331236/151034229-78ceaf0c-0ea1-4dc9-bcee-e8c640ce8130.png">

**Comment by fguide** [comment]
Verifique a escala das configurações de vídeo, deve estar em padrão, ou o equivalente a 100%.

Talvez nao funcione em 1440x900 mas não tenho certeza, em 1280x800 funciona bem.

https://support.apple.com/en-us/HT202471

**Comment by EmanoelV** [comment]
também to com o mesmo erro, só que no linux usando firefox, a resolução ta 1280x720

**Comment by EmanoelV** [comment]
Resolvi mudando a resolução pra 1280x800, o bot funciona melhor em resoluções com proporções 16x10
