### ISSUE TITLE
Bot selecionando sozinho para troca de tela

### ISSUE THREAD

**Issue by RMFilho** [mpcabete/bombcrypto-bot#685]
Opa 

Eai galera o bot está tentando troca de tela sozinho eu fecho ele e fica normal o notebook será oque pode ser?

Vlw galera
![P_20220125_195600](https://user-images.githubusercontent.com/98262720/151073673-cdadcd73-fada-4fe9-8efc-e3c5d96522aa.jpg)
https://files.fm/u/tmecnbwma
Link acima e 1 vídeo mostrando como está

**Comment by fguide** [comment]
Tente utilizar uma tela só com navegador em janela normal, nao full screen.

**Comment by RMFilho** [comment]
> Tente utilizar uma tela só com navegador em janela normal, nao full screen.

TB fica do mesmo jeito eu coloquei Full pra ver se parava

**Comment by fguide** [comment]
Desative a tela secundária, o bot por padrão funciona em uma só.

**Comment by RMFilho** [comment]
> Desative a tela secundária, o bot por padrão funciona em uma só.

Não sei aondr desativa já procurei e não achei

**Comment by fguide** [comment]
Se nao me engano, telca do Windows + P até selecionar a primeira opcao "Tela do computador somente "

**Comment by RMFilho** [comment]
> Se nao me engano, telca do Windows + P até selecionar a primeira opcao "Tela do computador somente "

Já fiz isso é só pra selecionar mas voltar e meia ela fica abrindo a abra de projetar em outra tela eu queria era desativar essa função
