### ISSUE TITLE
[SOLVED] ModuleNotFoundERROR: No module named "yaml" 

### ISSUE THREAD

**Issue by Cupoz** [mpcabete/bombcrypto-bot#686]
![yaml](https://user-images.githubusercontent.com/98434897/151081309-9dde1dcf-32c2-4198-b765-e176acf3b602.PNG)

*Use Google Translator*

Estoy teniendo este problema, Revise todo el repositorio de problemas sin embargo no encontré alguna soluciona este problema.

**Comment by fguide** [comment]
Utilice python index.py y no python3 index.py para llamar el bot.

**Comment by Cupoz** [comment]
> Utilice python index.py y no python3 index.py para llamar el bot.

Thank you, that worked
