### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by TiagoMsSO** [mpcabete/bombcrypto-bot#687]
![Erro Bot](https://user-images.githubusercontent.com/52792700/151082576-56841429-4242-45b7-a530-caa1fedb937c.png)

HEEEEELP MEEE !!!

**Comment by fguide** [comment]
pip install -r requirements.txt 

This shoul should install all dependencies. Run it on bot's directory

**Comment by SamuelSilvaG** [comment]
Tive esse erro também.

Executa isso pip install opencv-python

**Comment by zDARKYz** [comment]
![image](https://user-images.githubusercontent.com/101432141/157984380-43270f5d-b5be-4fc1-8e30-62851f643ab2.png)

Dá esse erro ai, ao executar o comando
