### ISSUE TITLE
Resoluçao 1440x900

### ISSUE THREAD

**Issue by Jabiroo** [mpcabete/bombcrypto-bot#688]
Alguem consegue mudar o codigo para rodar em resolucoes diferentes? tenho um monitor 1440x900 e nao roda de jeito nenhum. Alguem tem um solução? Obrigado (:

O bot nao acerta nenhum botao. Nem o botao de "heroes". O bot em si funciona, mas a resoluçao do monitor nao deixa com que ele acerte os botoes .

**Comment by fguide** [comment]
É só substituir os prints da pasta targets (arquivos .png) com os mesmos capturados no seu pc.

**Comment by Jabiroo** [comment]
irei tentar, estou trocando as imagens aqui e ja falo. Caso de certo, modifico o topico como "[solved]" Obrigado

**Comment by Jabiroo** [comment]
> É só substituir os prints da pasta targets (arquivos .png) com os mesmos capturados no seu pc.

substui as imagens como aparece no meu pc e ele continua com o mesmo erro, selecionando um pouco abaixo dos botoes certos. Ainda na procura de uma solução.
