### ISSUE TITLE
ele ta fazendo tudo errado 

### ISSUE THREAD

**Issue by 00coelho01** [mpcabete/bombcrypto-bot#689]
ele começa a fazer tudo normal, ai chega na parte de colocar os boneco pra trabalhar, ele n coloca nenhum, ai eu mexi em alguns codigo, ai ele so coloca os q estão em vermelho ou nem coloca, oq pode ser ? eu queria que isso funcionasse normal, se alguem tiver os codigos certos ou funcionando normal, poderia me ajudar e mandar pfv

**Comment by giovanniglsbl** [comment]
Coloca o bomb em ingles pra ver se funciona
