### ISSUE TITLE
Preciso de alteraçao no bot, pago com bcoin

### ISSUE THREAD

**Issue by fraga0017** [mpcabete/bombcrypto-bot#69]
é esse o título, pago 15 bcoin, entra em contato

**Comment by cristhianbreunig** [comment]
> é esse o título, pago 15 bcoin, entra em contato

Amigo, não sou o dev do projeto tá.

Se tu acha que é algo útil para os demais jogadores, escreve aí, quando vê alguém ajuda a desenvolvedor e melhorar ainda mais o bot.

**Comment by mpcabete** [comment]
Salve fraga, sim, o que o christian sugeriu é uma boa, no momento eu estou trabalhando naquelas coisas que coloquei no cronograma na pagina incial do bot.
Eu vou fechar esse issue pra ajudar na minha organização, qualquer coisa pode falar aqui que eu vejo!

**Comment by fraga0017** [comment]
Bom, eu nao tenho a mínima noçao, mas a ideia inicial é o bot ter utilidade pra quem possui casa

**Comment by fraga0017** [comment]
O difícil seria como o bot ia identificar quando acabar a energia do heroi para coloca-lo na casa, já que o jogo nao poe o heroi automaticamente na casa após acabar a energia, mesmo designando eles para casa(super raro pra cima por exemplo), e

**Comment by mpcabete** [comment]
Então, no momento eu estou desenvolvendo essa funcionalidade, esta indo um pouco mais devagar pq n tenho casa pra ir testando, mas o pessoal ta me ajudando.
agnt ta conversando por esse issue:
#61 

Se você testar e funcionar eu agradeceria muito alguns bcoins hehehe
