### ISSUE TITLE
Erro line 7 column 3

### ISSUE THREAD

**Issue by ricardoalesantiago** [mpcabete/bombcrypto-bot#695]
Oi pessoal,

Editei o arquivo config para alterar o valor de send_heroes_for_work de 10 para 30, fazer um teste. Executei o bot informou erro no arquivo config.yml line 7 column 3.

Já mudei outros campos e acontece sempre esse mesmo erro. 

Alguém sabe o que pode ser?

Utilizo a versão mais recente do python e já desinstalei e instalei novamente.

**Comment by gcxmtv** [comment]
qual erro? o que aparece escrito?

**Comment by ricardoalesantiago** [comment]
> qual erro? o que aparece escrito?
[https://ibb.co/dtYZ2x7](https://ibb.co/dtYZ2x7)

**Comment by fguide** [comment]
Voce editou o arquivo de forma incorreta, talvez tenha usado algum software como word, por exemplo.

Sugiro baixar o config.yaml novamente, substituir em seu pc e editar com bloco de notas apenas os parametros que quer alterar e salvar.

**Comment by ricardoalesantiago** [comment]
> Voce editou o arquivo de forma incorreta, talvez tenha usado algum software como word, por exemplo.
> 
> Sugiro baixar o config.yaml novamente, substituir em seu pc e editar com bloco de notas apenas os parametros que quer alterar e salvar.

Eu editei no bloco de notas somente o campo send_heroes_for_work de 10 para 30, salvei e tentei abrir novamente e aparece esse erro. 

Mesmo eu alterando para 10 novamente, ele dá o mesmo erro. Aí tive que substituir o arquivo para o original e aí sim voltou a funcionar, mas não consegui alterar o valor para 30 ou outro valor.

**Comment by gcxmtv** [comment]
Na hora de salvar você tá salvando como txt.. edita ele com o bloco de notas e na hora de salvar, vá em salvar como e altera o tipo de arquivo para todos os arquivos... Veja se funciona

**Comment by ricardoalesantiago** [comment]
> Na hora de salvar você tá salvando como txt.. edita ele com o bloco de notas e na hora de salvar, vá em salvar como e altera o tipo de arquivo para todos os arquivos... Veja se funciona

Fiz o processo e não deu certo.

**Comment by gcxmtv** [comment]
> > Na hora de salvar você tá salvando como txt.. edita ele com o bloco de notas e na hora de salvar, vá em salvar como e altera o tipo de arquivo para todos os arquivos... Veja se funciona
> 
> Fiz o processo e não deu certo. 

Qual teu email ? Me fala a config que você quer, vou lhe enviar .

**Comment by ricardoalesantiago** [comment]
> > > Na hora de salvar você tá salvando como txt.. edita ele com o bloco de notas e na hora de salvar, vá em salvar como e altera o tipo de arquivo para todos os arquivos... Veja se funciona
> > 
> > 
> > Fiz o processo e não deu certo.
> 
> Qual teu email ? Me fala a config que você quer, vou lhe enviar .

send_heroes_for_work para 30.

ricardoalexandre.santiago@gmail.com

Obrigado!

**Comment by fguide** [comment]
Por que nao tentar:

cmd -> powershell.exe

**Comment by fguide** [comment]
Tente:

cmd.exe -> powershell.exe

cd DIRETORIO_BOT [enter]

get-content config.yaml | %{$_ -replace "send_heroes_for_work: 10","send_heroes_for_work: 30"}

**Comment by ricardoalesantiago** [comment]
> Tente:
> 
> cmd.exe -> powershell.exe
> 
> cd DIRETORIO_BOT [enter]
> 
> get-content config.yaml | %{$_ -replace "send_heroes_for_work: 10","send_heroes_for_work: 30"}

Fiz e não deu certo.

Executei o bot e ele abriu os heroes não respeitando o tempo. Abri o arquivo config para ver se tinha salvo os 30, mas estava ainda 10 lá.

Enfim, não sei o que pode ser, mas se não der para mudar mantenho os 10, está farmando. Só queria testar um tempo maior.

**Comment by gcxmtv** [comment]
> > > > Na hora de salvar você tá salvando como txt.. edita ele com o bloco de notas e na hora de salvar, vá em salvar como e altera o tipo de arquivo para todos os arquivos... Veja se funciona
> > > 
> > > 
> > > Fiz o processo e não deu certo.
> > 
> > Qual teu email ? Me fala a config que você quer, vou lhe enviar .
> 
> send_heroes_for_work para 30.
> 
> ricardoalexandre.santiago@gmail.com
> 
> Obrigado!

Eu acabei de mandar.. só ajeita o nome do arquivo e pronto..

**Comment by ricardoalesantiago** [comment]
> > > > > Na hora de salvar você tá salvando como txt.. edita ele com o bloco de notas e na hora de salvar, vá em salvar como e altera o tipo de arquivo para todos os arquivos... Veja se funciona
> > > > 
> > > > 
> > > > Fiz o processo e não deu certo.
> > > 
> > > 
> > > Qual teu email ? Me fala a config que você quer, vou lhe enviar .
> > 
> > 
> > send_heroes_for_work para 30.
> > [ricardoalexandre.santiago@gmail.com](mailto:ricardoalexandre.santiago@gmail.com)
> > Obrigado!
> 
> Eu acabei de mandar.. só ajeita o nome do arquivo e pronto..

Deu certo!

Muito obrigado.
