### ISSUE TITLE
Problema ao iniciar bot no Windows Server 2016

### ISSUE THREAD

**Issue by felipearon** [mpcabete/bombcrypto-bot#698]
![image](https://user-images.githubusercontent.com/1236269/151671649-d45e8080-b020-4226-a881-dfb3d8dbdccd.png)

Fiz a instalação normal dos pacotes e ao executar o bot no Windows Server 2016 dá esse erro. Como resolver?

**Comment by fguide** [comment]
pip install opencv-python opencv-python-headless

**Comment by felipearon** [comment]
> pip install opencv-python opencv-python-headless

Executei o comando porém nada feito. O erro persiste. :(

**Comment by fguide** [comment]
Se nao me engano o windows server precisa ter algumas features habilitadas em relação ao modo de experiencia de desktop:

https://docs.vmware.com/br/VMware-Horizon/2106/published-desktops-applications/GUID-13F25FDB-654C-467F-9BC9-F2F9C4E4EAD7.html

**Comment by felipearon** [comment]
> Se nao me engano o windows server precisa ter algumas features habilitadas em relação ao modo de experiencia de desktop:
> 
> https://docs.vmware.com/br/VMware-Horizon/2106/published-desktops-applications/GUID-13F25FDB-654C-467F-9BC9-F2F9C4E4EAD7.html

Perfeito, funcionou. Vou testar agora o bot aqui no Windows Server 2016, já mando um feedback.

**Comment by felipearon** [comment]
O único problema agora é que, se eu fechar o acesso remoto o bot fica travado, só volta funcionar ao acessar novamente. Você sabe algo a respeito? Será que tem alguma forma de funcionar sem precisar deixar o acesso e tela ativa?

**Comment by fguide** [comment]
#505
