### ISSUE TITLE
Alguem pode me dar uma luz nesse erro? ERROR: Command errored out with exit

### ISSUE THREAD

**Issue by japcorrea1** [mpcabete/bombcrypto-bot#699]
ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python310\python.exe' 'C:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\JOO~1\AppData\Local\Temp\tmpf__b8vrn'
       cwd: C:\Users\João\AppData\Local\Temp\pip-install-3ummfzr6\pymsgbox_a1e34b3c453d4705aa13823aa74016fc
  Complete output (14 lines):
  Error in sitecustomize; set PYTHONVERBOSE for traceback:
  SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe3 in position 0: unexpected end of data (sitecustomize.py, line 21)
  running dist_info
  creating C:\Users\João\AppData\Local\Temp\pip-modern-metadata-itb89v7a\PyMsgBox.egg-info
  writing C:\Users\João\AppData\Local\Temp\pip-modern-metadata-itb89v7a\PyMsgBox.egg-info\PKG-INFO
  writing dependency_links to C:\Users\João\AppData\Local\Temp\pip-modern-metadata-itb89v7a\PyMsgBox.egg-info\dependency_links.txt
  writing top-level names to C:\Users\João\AppData\Local\Temp\pip-modern-metadata-itb89v7a\PyMsgBox.egg-info\top_level.txt
  writing manifest file 'C:\Users\João\AppData\Local\Temp\pip-modern-metadata-itb89v7a\PyMsgBox.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\João\AppData\Local\Temp\pip-modern-metadata-itb89v7a\PyMsgBox.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.py' under directory 'pymsgbox'
  writing manifest file 'C:\Users\João\AppData\Local\Temp\pip-modern-metadata-itb89v7a\PyMsgBox.egg-info\SOURCES.txt'
  creating 'C:\Users\João\AppData\Local\Temp\pip-modern-metadata-itb89v7a\PyMsgBox.dist-info'
  error: invalid command 'bdist_wheel'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7d/ff/4c6f31a4f08979f12a663f2aeb6c8b765d3bd592e66eaaac445f547bb875/PyMsgBox-1.0.9.tar.gz#sha256=2194227de8bff7a3d6da541848705a155dcbb2a06ee120d9f280a1d7f51263ff (from https://pypi.org/simple/pymsgbox/). Command errored out with exit status 1: 'C:\Program Files\Python310\python.exe' 'C:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\JOO~1\AppData\Local\Temp\tmpf__b8vrn' Check the logs for full command output.

ERROR: Could not find a version that satisfies the requirement PyMsgBox==1.0.9 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9)
ERROR: No matching distribution found for PyMsgBox==1.0.9

**Comment by fguide** [comment]
> SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe3 in position 0: 

> C:\Users\João\

Tem espaço e caracter especial, vc provavelmente vai precisar instalar o python com opcao para todos usuários ou trocar o nome de usuário do windows, pois está fora das práticas e só vai te causar problema (não só com o bot). Veja que em partes o windows tenta fazer conversao para nome compatível com DOS (C:\Users\JOO~1\) mas mesmo assim falha.

O indicado é fazer um usuário sem espaços nem carcteres especiais e mudar o "Display Name" para aparecer formatado como você quer.

**Comment by japcorrea1** [comment]
Quase consegui mano, so deu esse problema dai

ERROR: Could not install packages due to an OSError: [WinError 5] Acesso negado: 'C:\\Users\\japcorrea\\AppData\\Local\\Temp\\pip-uninstall-p8h2okf5\\pip.exe'

Consider using the `--user` option or check the permissions.

**Comment by fguide** [comment]
Reinstala o python com opcao de todos usuarios.
