### ISSUE TITLE
Browser Motion Sensors

### ISSUE THREAD

**Issue by pehpe-grill** [mpcabete/bombcrypto-bot#70]
Hello, mate! Thanks for your amazing work. It's been very useful.

I've noticed since last update Brave browser warning Bomb Crypto is using motion sensors APIs.

After some research I found out it could be used to detect bots: https://www.theinternetpatrol.com/about-motion-sensors-and-motion-sensor-blocking-in-brave-and-chrome-browsers/

It's something to keep an eye on.

**Comment by mpcabete** [comment]
Thanks!
