### ISSUE TITLE
Consegui instalar o bot normalmente em qualquer windows, mas numa maquina virtual nao funciona de jeito nenhum

### ISSUE THREAD

**Issue by Juninhox13** [mpcabete/bombcrypto-bot#700]
Se tiver alguma configuraçao pra VM me passem por favor.

**Comment by Juninhox13** [comment]
Starting index.py
Traceback (most recent call last):
  File "C:\Users\Bomb é Lua\Desktop\Bot Atualizado\index.py", line 9, in <module>
    import mss
ModuleNotFoundError: No module named 'mss'

esse erro em especifico

**Comment by cleitonleonel** [comment]
> ModuleNotFoundError: No module named 'mss'

Esse aí é o seu erro...basta instalar essa lib que falta ué... pip ou pip3 install mss

**Comment by fguide** [comment]
E provavelmente seu problema também está em: "C:\Users\Bomb é Lua" 
Tem espaço e caracter especial, vc provavelmente vai precisar instalar o python com opcao para todos usuários ou trocar o nome de usuário do windows, pois está fora das práticas e só vai te causar problema (não só com o bot).

O indicado é fazer um usuário sem espaços nem carcteres especiais e mudar o "Display Name" para aparecer formatado como você quer.

**Comment by cleitonleonel** [comment]
> E provavelmente seu problema também está em: "C:\Users\Bomb é Lua" Tem espaço e caracter especial, vc provavelmente vai precisar instalar o python com opcao para todos usuários ou trocar o nome de usuário do windows, pois está fora das práticas e só vai te causar problema (não só com o bot).
> 
> O indicado é fazer um usuário sem espaços nem carcteres especiais e mudar o "Display Name" para aparecer formatado como você quer.

Kkkk realmente não é um nome de usuário muito comum kkkk

**Comment by Juninhox13** [comment]
> > E provavelmente seu problema também está em: "C:\Users\Bomb é Lua" Tem espaço e caracter especial, vc provavelmente vai precisar instalar o python com opcao para todos usuários ou trocar o nome de usuário do windows, pois está fora das práticas e só vai te causar problema (não só com o bot).
> > O indicado é fazer um usuário sem espaços nem carcteres especiais e mudar o "Display Name" para aparecer formatado como você quer.
> 
> Kkkk realmente não é um nome de usuário muito comum kkkk

sim, eu tbm pensei nisso. sou de infra, nao entendo nada de programaçao. porem a primeira coisa q eu pensei foi no usuario mesmo. acabou q no final eu instalei outra ISO de windows. e funcionou. agora o problema é q o bot q eu peguei ali, um q diferencia os comuns dos demais na hora de por pra trabalhar ele scrolla a barrinha e clica nuns lugar tudo torto, ces fraga arrumar isso?

**Comment by fguide** [comment]
> peguei ali, um q diferencia os comuns dos demais

Não é a versão daqui então, dificil ajudarmos, ainda mais com a descrição do problema não muito detalhada.

Se está clicando em lugares errados é por problema de resolução, escala de desktop, zoom no navegador, etc. Pesquise no repositorio que praticamente todos os problemas mais comuns já foram respondidos...

**Comment by Juninhox13** [comment]
pior q ele faz tudo certo, até os primeiros clicks de por pra trabalhar saem certinhos, é na hora q ele da o scroll q fica um pouco mais pra cima a lista, e ele clica embaixo do botao verde, tentei mexer nas resoluçoes e continuou. vou poder ver isso só depois de 20h hj. mas eu vou testar com mais resoluçoes. enfim obrigado mano

**Comment by manotroll** [comment]
> Starting index.py Traceback (most recent call last): File "C:\Users\Bomb é Lua\Desktop\Bot Atualizado\index.py", line 9, in import mss ModuleNotFoundError: No module named 'mss'
> 
> esse erro em especifico

não pode usar caracteres especiais e espaço

**Comment by Juninhox13** [comment]
![click](https://user-images.githubusercontent.com/98700148/152073391-79e3e972-8ab3-4848-9839-19037551e7de.png)
 ele sempre q scrolla clica ali no ponto vermelho. ja tentei de tudo o dia inteiro e nada

**Comment by manotroll** [comment]
a % da tela ta em 100% ?

**Comment by Juninhox13** [comment]
ta mano, ja olhei tudo q dava pra olhar. eu só queria q ele scrolasse e deixasse certinho as barras, pq elas ficam pela metade e ai esse click sai sempre torto
