### ISSUE TITLE
Traceback (most recent call last): Line 512, line 477, line 246, line 99

### ISSUE THREAD

**Issue by RamonGarcia30** [mpcabete/bombcrypto-bot#701]
Bom dia! Coloquei o robô multiacount no sistema vps windows server data center 2016. Funciona perfeitamente se deixo o pc ou o celular na tela da vps, porém dá esse erro quando deixo só o vps (desconecto o pc e o celular). Gostaria de uma ajuda, obrigado!

Segue a foto dos erros citados:
![image](https://user-images.githubusercontent.com/98825371/151984432-a3e92971-0576-4c19-86ab-65553377ee3d.png)

![image](https://user-images.githubusercontent.com/98825371/151984561-57a17a85-b904-4f71-9f7b-0b6c6321d497.png)

**Comment by fguide** [comment]
#505
