### ISSUE TITLE
Meu bot reconhece os heroes e barra verde mas nada acontece, nao meche o mouse. Macbook com monitor externo de 1920x1080. ja troquei as fotos na pasta targets mas continua n funcionando

### ISSUE THREAD

**Issue by gabetav** [mpcabete/bombcrypto-bot#705]
![Screen Shot 2022-02-01 at 6 35 43 PM](https://user-images.githubusercontent.com/16855537/152093107-8d96ec87-567c-4d3a-b15b-f2ec4e87d8a6.png)

**Comment by fguide** [comment]
> monitor externo

É por esse motivo, o bot "original" só funciona com 1 monitor.

**Comment by gabetav** [comment]
> > monitor externo
> 
> É por esse motivo, o bot "original" só funciona com 1 monitor.

mesmo usando o meu proprio monitor do laptop nao ta funcionando, o mouse n ta mechendo, fala ta q ta clikind mas nao meche.
