### ISSUE TITLE
Sistema para controle de investimentos/lucros

### ISSUE THREAD

**Issue by dilneiconectala** [mpcabete/bombcrypto-bot#707]
Olá pessoal, sou programador e estava sentindo muita falta de algumas coisas para poder acompanhar os meus custos e ganhos no jogo, as planilhas disponibilizadas na internet são muito pesadas, não são web e não supre toda minha necessidade de exigente.. Então desenvolvi essa aplicação para me auxiliar e não precisar ficar abrindo um milhão de site para acompanhar, assim com essa dashboard eu consigo acompanhar tudo que é de mais importante 🙂
Hoje mesmo terminei de desenvolver mais algumas etapas importantes da plataforma, se preencher o endereço da carteira corretamente, meu sistema vai escanear de hora em hora todas as carteiras e alertar na tela se tiver algo errado, como por exemplo: novo contrato adicionado a carteira, contrato na carteira já listado como fraude, tudo isso para evitar scam e poder agir imediatamente. 
Obs. Cadastros já liberados, o sistema está em fase beta, então bem provável que alguém encontre algum probleminha, caso encontrar ou tiver sugestão, abre um ticket pra mim pela plataforma por favor.
Se tiver uma boa aderência dos usuários, irei ainda programar muito mais coisas interessantes, prometo :)
Url para quem quiser testar: https://www.bombcrypto.center

![image](https://user-images.githubusercontent.com/88105346/152155579-849ca808-ac33-4a1d-bd7f-eabe8933a6ce.png)
![image](https://user-images.githubusercontent.com/88105346/152155615-1d302bbf-e465-4fdb-bdb2-7c3b1a44cc2b.png)

**Comment by dilneiconectala** [comment]
Em breve farei uma integração do próprio robo para ficar enviando o saldo de moedas para o sistema de forma automática :)

**Comment by fguide** [comment]
Boa sorte com o projeto, parece interessante.

Seria interessantes desenvolver os alertas (relacionados ao jogo, nao a conta individual) para serem enviados para uma lista sem necessidade de cadastro, muita gente talvez queira receber sem ter que cadastrar o endereço da carteira em uma base de dados...

**Comment by dilneiss** [comment]
> Boa sorte com o projeto, parece interessante.
> 
> Seria interessantes desenvolver os alertas (relacionados ao jogo, nao a conta individual) para serem enviados para uma lista sem necessidade de cadastro, muita gente talvez queira receber sem ter que cadastrar o endereço da carteira em uma base de dados...

você está sugerindo uma página sem cadastro? e dai mostrar aqueles alertas sem se cadastrar, seria isso?

**Comment by wellclever** [comment]
Muito bacana seu projeto. Parabéns. Uma sugestão que eu dou é criar um script para escanear quando uma wallet for cadastrada e recuperar o histórico de gastos e ganhos do token, isso abre um gap para muita outras possibilidades.

**Comment by dilneiss** [comment]
> Muito bacana seu projeto. Parabéns. Uma sugestão que eu dou é criar um script para escanear quando uma wallet for cadastrada e recuperar o histórico de gastos e ganhos do token, isso abre um gap para muita outras possibilidades.

boa, vou anotar aqui, valeuu
