### ISSUE TITLE
Bot funciona Ok em uma conta, mas nao na segunda.

### ISSUE THREAD

**Issue by ghost** [mpcabete/bombcrypto-bot#708]
Olá, o bot estava rodando normal em minhas duas contas. De um dia por outro, parou de funcionar em uma delas. Ele não manda os heróis pra trabalhar.  Acontece duas situações:

1 - o cursor vai no botão de "_heroes_" no canto direito inferior da tela e não clica.

2- quando eu altero o _threshold_ pra mais nada acontece, e pra menos,  ele reconhece os heróis verdes, vai ate o o botão "_work_" mas não clica.

A segunda conta funciona perfeitamente. Alguma sugestão?

Obrigado.

**Comment by rzanca** [comment]
https://github.com/rzanca/bombcrypto-multibot
