### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Tormuka** [mpcabete/bombcrypto-bot#709]
Alguma solução para funcionar no linux?

**Comment by fguide** [comment]
O script funciona em linux, qual o problema que vc tem?

**Comment by Tormuka** [comment]
No linux tenho o python3 instalado, no caso esse script é o de multiacc, o .bat não executa, então entro da forma tradicional, no terminal e executo o comando python3 forever.py index.py e ele me retornar a seguinte mensagem '' Starting index.py
/bin/sh: 1: python: not found", tenha paciência sou muito leigo ainda kkkkkk , pode ser problema na instalação tbm, qual o passo a passo pra abrir em linux?

**Comment by fguide** [comment]
Nao faço ideia de qual versao vc esta usando, mas certamente ao é pelo .bat que se inicia...

tente procurar um arquivo com final .sh, e se existir, execute com o comando: 
> bash arquivo.sh

Outra coisa é tentar só 'python' e não 'python3', talvez tenha duas versoes instaladas...

**Comment by Tormuka** [comment]
Só python tbm não funciona (diz que o comando python não foi encontrado) e tbm não tem nenhum arquivo .sh, está examente como no git hub

**Comment by fguide** [comment]
Você precisa instalar o pyhon de acordo com instrucoes do se sistema, em debian e derivados (ubuntu, mint, etc) no terminal:

sudo apt install python3 python3-dev

No diretorio do bot execute:
pip install -r requirements.txt

**Comment by Tormuka** [comment]
Beleza, vou tentar aqui
