### ISSUE TITLE
Alteração na seleção do herói

### ISSUE THREAD

**Issue by nmmorette** [mpcabete/bombcrypto-bot#71]
Queria fazer uma alteração para enviar o hero somente com a barra cheia. 
tentei alterar só a imagem, porém não funcionou. 
Alguém sabe como posso fazer essa alteração?

**Comment by cristhianbreunig** [comment]
> Queria fazer uma alteração para enviar o hero somente com a barra cheia. tentei alterar só a imagem, porém não funcionou. Alguém sabe como posso fazer essa alteração?

Oi, também tentei fazer isso, comentei com o desenvolvedor aqui:
https://github.com/mpcabete/bombcrypto-bot/issues/48

Não continuei no item pois ele ainda não respondeu à respeito.

**Comment by cristhianbreunig** [comment]
> Queria fazer uma alteração para enviar o hero somente com a barra cheia. tentei alterar só a imagem, porém não funcionou. Alguém sabe como posso fazer essa alteração?

Oi, só pra atualizar, terminei essa funcionalidade, fiz um pull request.

Acredito que depois de testar o @mpcabete vai aceitar para o projeto 😄

**Comment by mdavinicius** [comment]
> > Queria fazer uma alteração para enviar o hero somente com a barra cheia. tentei alterar só a imagem, porém não funcionou. Alguém sabe como posso fazer essa alteração?
> 
> Oi, só pra atualizar, terminei essa funcionalidade, fiz um pull request.
> 
> Acredito que depois de testar o @mpcabete vai aceitar para o projeto 😄

To na expectativa desse update :p

**Comment by mpcabete** [comment]
@mdavinicius ta atualizado!
Mto obrigado dnovo @cristhianbreunig

**Comment by mpcabete** [comment]
Estou fechando o issue pra ajudar na organização.
