### ISSUE TITLE
Erro no Ubuntu

### ISSUE THREAD

**Issue by rafakasi** [mpcabete/bombcrypto-bot#710]
Boa noite pessoal, tudo bem com vocês? Espero que sim.

Fiz todo o processo de instalação no Ubuntu, porém quando executo o comando, aparece o seguinte erro. Poderiam me ajudar?

> [2022-02-04 19:23:57] => 🏢 Search for heroes to work
[2022-02-04 19:23:57] => ⬆️ Processing last action..Traceback (most recent call last):
  File "/home/rafakasi/bomb/index.py", line 527, in <module>
    main()
  File "/home/rafakasi/bomb/index.py", line 496, in main
    refreshHeroes()
  File "/home/rafakasi/bomb/index.py", line 425, in refreshHeroes
    goToHeroes()
  File "/home/rafakasi/bomb/index.py", line 304, in goToHeroes
    if clickBtn(images['go-back-arrow']):
  File "/home/rafakasi/bomb/index.py", line 156, in clickBtn
    matches = positions(img, threshold=threshold)
  File "/home/rafakasi/bomb/index.py", line 183, in positions
    img = printSreen()
  File "/home/rafakasi/bomb/index.py", line 174, in printSreen
    sct_img = np.array(sct.grab(monitor))
  File "/home/rafakasi/.local/lib/python3.9/site-packages/mss/base.py", line 88, in grab
    return self._grab_impl(monitor)
  File "/home/rafakasi/.local/lib/python3.9/site-packages/mss/linux.py", line 446, in _grab_impl
    ximage = self.xlib.XGetImage(
  File "/home/rafakasi/.local/lib/python3.9/site-packages/mss/linux.py", line 191, in validate
    raise ScreenShotError(err, details=details)
mss.exception.ScreenShotError: XGetImage() failed

**Comment by fguide** [comment]
Parece que as versões recentes de ubuntu vem com wayland no lugar de xorg, veja se é o seu caso e se for tente trocar de wayland para xorg.

Não testei, mas aparentemente instalar o pacote gnome-screenshot funciona pra resolver no wayland.

**Comment by rafakasi** [comment]
> Parece que as versões recentes de ubuntu vem com wayland no lugar de xorg, veja se é o seu caso e se for tente trocar de wayland para xorg.
> 
> Não testei, mas aparentemente instalar o pacote gnome-screenshot funciona pra resolver no wayland.

Fala amigo, o problema era exatamente esse, troquei pro Xorg e funcionou perfeitamente, muito obrigado

**Comment by rafakasi** [comment]
> Parece que as versões recentes de ubuntu vem com wayland no lugar de xorg, veja se é o seu caso e se for tente trocar de wayland para xorg.
> 
> Não testei, mas aparentemente instalar o pacote gnome-screenshot funciona pra resolver no wayland.

**Comment by rafakasi** [comment]
> Parece que as versões recentes de ubuntu vem com wayland no lugar de xorg, veja se é o seu caso e se for tente trocar de wayland para xorg.
> 
> Não testei, mas aparentemente instalar o pacote gnome-screenshot funciona pra resolver no wayland.

Fala amigo! O problema era exatamente esse que você mencionou, troquei pra Xorg e funcionou perfeitamente, muito obrigado

**Comment by Rheyder** [comment]
Qual versão do bot você está usando?
Estou usando no Ubuntu e está dando aquele erro do PyGetWindow... só consigo usar a versão sem multi-account...
O meu está no Xorg...

**Comment by fguide** [comment]
PyGetWindow é biblioteca exclusiva de windows, nao vai funcionar mesmo, tem que procurar alguma versao que seja compatível com linux e multi account.

**Comment by Rheyder** [comment]
Encontrei uma aqui que está funcionando 100%... valeu!
