### ISSUE TITLE
Bot para Luna Rush

### ISSUE THREAD

**Issue by HappyDark12** [mpcabete/bombcrypto-bot#711]
Pessoal estou disponibilizando o bot de Luna Rush.
Onde o mesmo realiza todas as operação.
Obs:Somente para um time 3 até o momento quando realizado o upgrade do mesmo estarei disponibilizando no meu diretorio tambem.
https://github.com/HappyDark12/LunaRushBot.git

**Comment by CorreiaDeveloper** [comment]
Pqp, vim aqui NESSE EXATO MOMENTO, só pra pedir isso kkkkkkkk

**Comment by Celiojrfoda** [comment]
Funciona multi account?
