### ISSUE TITLE
WHY DOES ALL THE CONFIGURATION APPEAR IN 0?

### ISSUE THREAD

**Issue by Mclov1** [mpcabete/bombcrypto-bot#712]
![image](https://user-images.githubusercontent.com/97806100/152735029-62df9997-ed56-4c2a-bdd3-e7f665ca8352.png)

**Comment by fguide** [comment]
It looks like your screen scale is bigger than 100%, it needs to be set on 100% (or you can change the screenshots on the target folder, accordingly to your screen settings)

**Comment by nashy15973** [comment]
same problem
