### ISSUE TITLE
Link para Bot de Luna Rush sem restrições e funcional

### ISSUE THREAD

**Issue by walterdis** [mpcabete/bombcrypto-bot#714]
@mpcabete se não for permitido, pode excluir o tópico ;)

Terminei recentemente um bot para luna rush.
Óbviamente motivado pelo que o mpcabete fez aqui.

A principio está funcional, sem restrições de personagens e nem de fase (famoso "no meu computador funciona" [no do meu amigo também funcionou])

https://github.com/walterdis/lunarush-bot

Tem bastante coisas a serem feitas ainda mas quis disponibilizar algo funcional o mais rápido possível.

**Comment by JONASUK0** [comment]
um bot é necessário para o espaço cripto por favor

**Comment by walterdis** [comment]
> s

Eu estou fazendo já, mas, o jogo é cheio de peculiaridades que fazem o bot se perder direto.
No meu PC ele funciona legalzinho mas, para duas pessoas que enviei ele se perde, provavelmente 90% das pessoas vão ter que refazer as fotos e ainda sim existe chance do bot dar problema.

Ainda sim, vou ver se consigo finalizar aqui e deixar ele "usável / aceitável" e disponibilizo depois no meu repositório ;)

**Comment by walterdis** [comment]
> um bot é necessário para o espaço cripto por favor

Try this one i recently made ;)

https://github.com/walterdis/spacecrypto-bot

**Comment by marciodavi** [comment]
tem como mundar o tempo de 2h pra tres 3h ele entra,e colocar dois 2 personagens de 2 em 2 tem como mundar isso?
