### ISSUE TITLE
mpcabete precisamos urgentemente de um bot de luna rush!!

### ISSUE THREAD

**Issue by GigaMonka** [mpcabete/bombcrypto-bot#716]
Por favor saia de onde estiver escondido! haha

**Comment by walterdis** [comment]
> Por favor saia de onde estiver escondido! haha

Testa o que eu fiz, se tiver algum bug avisa que eu conserto ;)
Segundo dia que deixo rodando a noite e rodou sem problemas

https://github.com/walterdis/lunarush-bot

**Comment by fguide** [comment]
Tem literalmente DOIS bots pra esse jogo na página de Issues, é só pesquisar...

**Comment by GigaMonka** [comment]
Pow mas ai tem que confiar ne kkk

**Comment by walterdis** [comment]
> Pow mas ai tem que confiar ne kkk

Código aberto, já teve discussão sobre isso e tudo nesse projeto.

Não faz sentido a pessoa colocar um projeto de código aberto com trechos malicioso que todos possam ver e, se queimar no mercado, principalmente se é a sua profissão.

Ainda sim entendo o seu lado, principalmente com o pessoal que não entende de programação.
O que podes fazer, é tentar falar com algum conhecido que tenha algum conhecimento para dar uma analisada. 😁

**Comment by GigaMonka** [comment]
Então... os dois bots que vi são de criadores que n tem mais nada além desse bot. Então n tem histórico nenhum.

**Comment by walterdis** [comment]
> 

Um deles é o meu (o que postei o link acima e tem mais coisas sim) 😁 https://github.com/walterdis?tab=repositories

Como não tinha nenhum bot funcionando 100% ou eram pagos / código fechado, eu fiz ele pra poder dormir em paz a noite e disponibilizei para quem quiser usar e colaborar (fora que é bom para portifólio).

Como disse, o código é aberto, qualquer um pode analisar e, não vou queimar o meu nome no mercado e arriscar o meu repositório (que tenho desde 2013) para tentar sacanear outras pessoas.

Fica a seu critério. Te recomendo conversar com alguém de confiança que tenha algum conhecimento em programação que possa dar uma analisada no que eu fiz e te dar um parecer.

**Comment by GigaMonka** [comment]
Vou dar uma olhada, o teu manda todas as lunas pra batalha e da click aleatorio?

**Comment by walterdis** [comment]
> Vou dar uma olhada, o teu manda todas as lunas pra batalha e da click aleatorio?

Sim, conecta na metamask, seleciona o estágio disponível (algumas pessoas estão tendo problema, tem uma issue ali que podes ler pra solucionar).
Pega as com energia cheia, manda pra batalha e qndo acaba a energia coloca outras.
Se não tiver nenhuma com energia, volta pra seleção de estágio e fica parado por umas 2 hrs +-

Não está totalmente randomizado, fiz ele para funcionar logo. Ao longo do tempo agora vou implementar isso dos movimentos randomicos (estou usando apenas durante a noite na hora de deitar ou quando vou ficar longe do pc)

Eu fiz o máximo possivel para deixar o projeto bem separado, da uma olhada na pasta "src" que os métodos estão bem descritivos do que fazem (se tiver alguma duvida do que algo faz, pergunta que te explico) ;)

Qualquer coisa abre uma issue lá se der algum problema que eu vejo para consertar.

Ah, o jogo tem que estar configurado para inglês e com a qualidade mínima

**Comment by TheoOliveira** [comment]
Paga ele ué

**Comment by CorreiaDeveloper** [comment]
Bot funcional e limpo viu? sou Dev tmb, e ja estou utilizando

**Comment by sim-lipotril** [comment]
Alguém testou e está funcionando certinho?

**Comment by marciodavi** [comment]
funciona blz,tem como mundar a hora de entra pra 3h de difrença,e colocar 2 em 2 pra luta,seu bot funciona parabens pelo trabalho obrigado...
