### ISSUE TITLE
Problema com a janela de assinar do metamask abrindo atrás do chrome

### ISSUE THREAD

**Issue by THEBESTSZ** [mpcabete/bombcrypto-bot#72]
Alguém teve esse problema? Como resolveram? Tem como configurar pra janela sempre ter prioridade ou algo assim?

**Comment by diogo85** [comment]
Eu to com o mesmo problema. O bot funciona tudo bem, menos conseguir fazer o Sign no Metamask... e como o jogo cai toda hora, fica complicado.

**Comment by mpcabete** [comment]
hmm, qual navegador estão usando?

**Comment by diogo85** [comment]
Edge. Eu refiz os botões tirando a parte branca e deu tudo certo agora!

**Comment by THEBESTSZ** [comment]
Tô usando brave, diogo como que você refez, vc poderia explicar pra gente, por favor?

**Comment by diogo85** [comment]
> Tô usando brave, diogo como que você refez, vc poderia explicar pra gente, por favor?

Eu printei o botão "Sign" do Metamask e editei a imagem cortando a parte branca ao redor. Substitui o arquivo na pasta do bot. Aí ele começou a identificar e clicar. 

Tem uma solução no FAQ (arquivo README) que tem como configurar pra ele ficar "menos exigente" com as imagens. Talvez resolva também. Qualquer dúvida pode me falar.

**Comment by LRBarbieri** [comment]
> > Tô usando brave, diogo como que você refez, vc poderia explicar pra gente, por favor?
> 
> Eu printei o botão "Sign" do Metamask e editei a imagem cortando a parte branca ao redor. Substitui o arquivo na pasta do bot. Aí ele começou a identificar e clicar.
> 
> Tem uma solução no FAQ (arquivo README) que tem como configurar pra ele ficar "menos exigente" com as imagens. Talvez resolva também. Qualquer dúvida pode me falar.

Eu tentei fazer isso, ele abre a janela do metamask onde está o Sign porém não clica em nada. Uso o Chrome

**Comment by thiago-molive** [comment]
estou tendo esse problema, não é frequente. aconteceu quando deixo a noite enquanto vou dormir. se eu ficar monitorando enquanto o bot trabalha ele trabalha bem.
mas à noite acabo perdendo o farm todo com conta desse bug
