### ISSUE TITLE
Could you create a bot for space crypto?

### ISSUE THREAD

**Issue by GCarin1** [mpcabete/bombcrypto-bot#724]
Your bomb bot works very well, it would be really cool if you created one for space crypto

**Comment by bhrama-br** [comment]
https://github.com/bhrama-br/spacecryto-bombcrypto-bot

**Comment by walterdis** [comment]
> Your bomb bot works very well, it would be really cool if you created one for space crypto

Take a look ;)
https://github.com/walterdis/spacecrypto-bot

Use chrome at 50% zoom
