### ISSUE TITLE
Linux 20.04

### ISSUE THREAD

**Issue by gusw3** [mpcabete/bombcrypto-bot#725]
![SPACE](https://user-images.githubusercontent.com/99927153/154606938-bc6ef907-5840-4cc2-912c-69fe6564c39a.png)
Alguém poderia me ajudar?

**Comment by ZaryImortal** [comment]
esse git é do bomb, mas parece que o problema é a resolução do seu monitor

**Comment by fguide** [comment]
Tá usando Wayland, tem que mudar pra Xorg.

**Comment by gusw3** [comment]
> Tá usando Wayland, tem que mudar pra Xorg.

Como posso mudar?

**Comment by gusw3** [comment]
> esse git é do bomb, mas parece que o problema é a resolução do seu monitor

Mil desculpas eu coloquei a print do bot do bomb mas mesmo assim o do space e do bomb esta dando o mesmo erro

**Comment by gusw3** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/99927153/154698291-2435af45-3eed-4df0-9a8b-e8a925453a26.png)
