### ISSUE TITLE
Send heroes home (problema e teoria para solução)

### ISSUE THREAD

**Issue by rodrigobragamg** [mpcabete/bombcrypto-bot#726]
Andei testando e ocorre o seguinte com o script atual:

O script reconhece devidamente cada hero conforme os prints e faz os cliques, porém, quando há MAIS DE 01 HERO na mesma tela/ print screen tirado pelo script, o segundo hero na ordem a ser mandado para a Home acaba sendo trocado pelo  Hero que estava embaixo dele, pois, ao mandar o primeiro Hero descansar a ordem muda e o segundo sobe uma fileira, ou seja, acaba ocupando o slot daquele que deveria ir para a home.

Para resolver isso mais fácil teria que ser capturado um Print da posição para cada clique, ou seja, cada hero a ser enviado para a home... 

Quebrando a cabeça aqui mas ainda não consegui.

**Comment by farawaykcmm** [comment]
Basta clicar de baixo pra cima na hora de mandar pra home

**Comment by rodrigobragamg** [comment]
Não... A mesma coisa ocorreria quando um comum estivesse antes do mais raro a ser enviado para a casa.

Além disso, todo o script é estruturado no scrolll de cima par abaixo, precisa mudar tudo.

**Comment by J3Z1N63R57** [comment]
does anyone of you know how i have to screenshot the heroes so i can send them home? i tried everything but nothing works?

**Comment by Sezorok** [comment]
estou com o mesmo problema... mas ainda tenho outro pior, os heros na casa estão as vezes ficando "full" e não estão sendo colocados de volta para trabalhar

**Comment by isacsg** [comment]
mesmo problema aqui
