### ISSUE TITLE
Update please <3

### ISSUE THREAD

**Issue by zorelix** [mpcabete/bombcrypto-bot#728]
update please new BC update came and bot cant press the "CONNECT WALLET" button since the first pop up was the new login panel

**Comment by Neibis** [comment]
If you want i've edited mine so it can change between browsers and upated for the new connect button, i'll let the link [here](https://github.com/Neibis/bombcryptobot_update.git).

**Comment by joaovictor091** [comment]
Neibis vc fez as alterações no arquivo index.py ?

**Comment by Neibis** [comment]
Sim apenas adicionei o novo login e a opção de ter mais do que uma conta, para que o bot troque entre browsers, para isso tire print ao icon do browser aberto e edite as imagens browser1 e browser2 na pasta principal
