### ISSUE TITLE
Como inserir segundo clique login Wallet

### ISSUE THREAD

**Issue by caiomaggiore** [mpcabete/bombcrypto-bot#733]
Caros amigos, 
sou programador intermediário e notei que esse código realmente não é complicado, consegui fazer uma alteração simples num IF logo após " **if clickBtn(images['connect-wallet']**"...

Usei a **Ferramenta de Captura** do Windows e printei o segundo botão de login
![connect-wallet-2](https://user-images.githubusercontent.com/100660682/156101541-7f26a300-efb0-43a9-90f6-e149cfdee9a8.png)

Depois salvei na pasta "**Target**" com o nome de "**connect-wallet-2**".
![image](https://user-images.githubusercontent.com/100660682/156101784-668e1d57-fb3a-4062-b95f-cebfb9ff5d0f.png) ![image](https://user-images.githubusercontent.com/100660682/156102247-ebf0130f-80ac-4a96-a4ef-41ad4314b65f.png)

Em seguida abra o arquivo "index.py" pelo Bloco de Notas, clique sobre o arquivo com  botão direito do mouse e clique em "**Abrir Com > Bloco de Notas**" para inserir um código.
![image](https://user-images.githubusercontent.com/100660682/156102158-00ba9099-f77d-42cf-ad46-4294f8dcd973.png)

Procure a função "**def login():**" e copie o código que deixei logo abaixo cole depois  de "**if clickBtn(images['connect-wallet']**"
```
if clickBtn(images['connect-wallet-2'], timeout = 10):
logger('🎉 Connect wallet button 2 detected, logging in now!')
login_attempts = login_attempts + 1
#TODO mto ele da erro e poco o botao n abre
# time.sleep(10)
```
No final vai ficar como no exemplo abaixo...
![image](https://user-images.githubusercontent.com/100660682/156102629-a9ab5da1-072d-4abd-91e0-a5dd4344e8a1.png)

Salve o arquivo e execute o "**index.py**"

Espero que tenha ajudado!

**Comment by isacsg** [comment]
rapaz do ceú, vc me salvou demais. Muito obrigada!!

**Comment by xerifex7** [comment]
valeu mano, me salvou desse problema!!! muito obrigado, tmj!! :D

**Comment by felipejiman** [comment]
A ultima atualização mudou a imagem do "connect-wallet".
Para voltar a funcionar precisa substituir a imagem por essa nova imagem:
![connect-wallet](https://user-images.githubusercontent.com/42502253/156765202-2b02b14a-5d38-4a0b-bba6-b992e0121bc5.PNG)

**Comment by Minddx3** [comment]
Caio, segui da forma que explicou mas o bot retorna a seguinte mensagem:

> File "C:\bomb\index.py", line 517, in <module>
    main()
  File "C:\bomb\index.py", line 496, in main
    login()
  File "C:\bomb\index.py", line 346, in login
    if clickBtn(images['connect-wallet-2'], name='connectWalletBtn2', timeout = 10):
KeyError: 'connect-wallet-2'

Conseguiria me ajudar com isso, por favor?

**Comment by caiomaggiore** [comment]
> Caio, segui da forma que explicou mas o bot retorna a seguinte mensagem:
> 
> > File "C:\bomb\index.py", line 517, in 
> > main()
> > File "C:\bomb\index.py", line 496, in main
> > login()
> > File "C:\bomb\index.py", line 346, in login
> > if clickBtn(images['connect-wallet-2'], name='connectWalletBtn2', timeout = 10):
> > KeyError: 'connect-wallet-2'
> 
> Conseguiria me ajudar com isso, por favor?

Manda Print do Erro e também da alteração que fez no código.
Outra coisa, salvou a imagem do segundo botão de Connect na pasta target?

**Comment by Minddx3** [comment]
> Manda Print do Erro e também da alteração que fez no código. Outra coisa, salvou a imagem do segundo botão de Connect na pasta target?

![image](https://user-images.githubusercontent.com/101192665/157332895-0c69ea7f-5c1d-4e21-a1eb-7a84ab90fd79.png)

![image](https://user-images.githubusercontent.com/101192665/157333035-b9b5e42e-1ea3-4ecf-8352-6923cfbe77e7.png)

Sim, salvei a imagem:

![image](https://user-images.githubusercontent.com/101192665/157333104-c1e2920c-f1da-4796-93dc-1558672408c7.png)

**Comment by caiomaggiore** [comment]
Tira esse name que aponta para algum botão que não existe.

 name='connectWalletBtn2

```
    if login_attempts > 3:
        logger('🔃 Too many login attempts, refreshing')
        login_attempts = 0
        pyautogui.hotkey('ctrl','f5')
        return

    if clickBtn(images['connect-wallet'], timeout = 10):
        logger('🎉 Connect wallet button detected, wait!')
        login_attempts = login_attempts + 1
        #TODO mto ele da erro e poco o botao n abre
        # time.sleep(10)

    if clickBtn(images['connect-wallet-2'], timeout = 10):
        logger('🎉 Connect wallet button 2 detected, logging in!')
        login_attempts = login_attempts + 1
        #TODO mto ele da erro e poco o botao n abre
        # time.sleep(10)
```

No meu código não tem essa referencia de nome, tenta tirar isso e me avisa.

**Comment by LucasBonafe** [comment]
Funcionando, já temos o Ctrl+F5 e alguma tratativa após atualizações (servidor Offline)?

Onde está o @mpcabete que não integra esse _update_?
