### ISSUE TITLE
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

### ISSUE THREAD

**Issue by nashy15973** [mpcabete/bombcrypto-bot#734]
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by nashy15973** [comment]
how this one fix?

**Comment by fguide** [comment]
You don't have python installed, just install it using the option "add to PATH" as on the readme.
