### ISSUE TITLE
A NodeJS implementation (no browser required) / Uma implementação NodeJS (não precisa do navegador)

### ISSUE THREAD

**Issue by john-titor-master** [mpcabete/bombcrypto-bot#735]
Hi guys,

I quit bombcrypto recently...
I decided to make my personal bot open-source. It is already integrated with Docker and can run hundreds of accounts at the same time. I also plays **Adventure Mode** for you.

Have fun: https://github.com/john-titor-master/bombcrypto-superbot

--

Oi pessoal

Eu saí do Bombcrypto recentemente...
Eu decidi abrir o código do meu Bot pessoal. Ele já está integrado com o Docker e pode rodar centenas de contas ao mesmo tempo. Ele também joga o **modo aventura** para você.

Divirtam-se: https://github.com/john-titor-master/bombcrypto-superbot

**Comment by jeanvetorello** [comment]
DAhora hein. Seria massa se fosse com user e senha já.

**Comment by john-titor-master** [comment]
Pra fazer login basta inserir o ID da Wallet. Não precisa da chave da mesma. É uma falha de segurança do jogo que eu explorei para fazer o bot. Nesse caso, não faz sentido se preocupar com usuário e senha para entrar no jogo, dado que com apenas o ID da Wallet não é possível realizar saques nem nenhuma operação protegida.

**Comment by odilklein** [comment]
O quão safe é usar sem se preocupar com ban ou algo do tipo por parte do Bomb, já que essa questão de logar sem autenticação é uma falha de segurança do Bomb? Ótimo Bot, parabéns!

**Comment by dilneiss** [comment]
alguém aqui já está usando e pode dar um feedback? @john-titor-master parabéns cara, sempre quis fazer um bot assim para não ocupar meu PC principal e não me preocupar com nada ehhe, pode dar dicas de como você conseguiu isso?

**Comment by john-titor-master** [comment]
> O quão safe é usar sem se preocupar com ban ou algo do tipo por parte do Bomb, já que essa questão de logar sem autenticação é uma falha de segurança do Bomb? Ótimo Bot, parabéns!

O processo de login do bot é exatamente igual ao processo de login do jogo (o jogo só informa o ID da Wallet para fazer login, ou seja, esta é a falha de segurança).

**Comment by john-titor-master** [comment]
> alguém aqui já está usando e pode dar um feedback? @john-titor-master parabéns cara, sempre quis fazer um bot assim para não ocupar meu PC principal e não me preocupar com nada ehhe, pode dar dicas de como você conseguiu isso?

Eu mesmo utilizei por 3 meses sem nenhum problema. Para construir o bot você precisa de diversas ferramentas de engenharia reversa para WASM e ferramentas de inspeção de memória do jogo. Além disso, você precisa decodificar o canal de comunicação do jogo (WebSocket sobre TCP).

**Comment by kyubruno1** [comment]
É só indicar o endereço da carteira que o bot já funciona?

**Comment by john-titor-master** [comment]
> É só indicar o endereço da carteira que o bot já funciona?

Exatamente. `WALLET_ID=<Coloca o endereço aqui> yarn go`. Precisa ser em um terminal bash, CMD não funciona.

**Comment by dilneiss** [comment]
@john-titor-master opa blz mano? consegui usar o bot até ontem de boa, depois dessa ultima atualização não roda mais.. consegue ajudar? sabe dizer se os caras corrigiram essa falha de segurança? ou só mudaram alguma coisa? e como podemos fazer pra corrigir? ele estava funcionando perfeitamente, pra minha surpresa fazia até o modo aventura, passando tudo inclusive chefes..

**Comment by jeanvetorello** [comment]
> @john-titor-master opa blz mano? consegui usar o bot até ontem de boa, depois dessa ultima atualização não roda mais.. consegue ajudar? sabe dizer se os caras corrigiram essa falha de segurança? ou só mudaram alguma coisa? e como podemos fazer pra corrigir? ele estava funcionando perfeitamente, pra minha surpresa fazia até o modo aventura, passando tudo inclusive chefes..

só baixar a ultima versão.

**Comment by john-titor-master** [comment]
Basta baixar a última versão que disponibilizei hoje depois da atualização.

**Comment by zomanuniverse** [comment]
can we do send house feature? if you need a wallet with a house let me know .
and also how we can donate to you

**Comment by john-titor-master** [comment]
@zomanuniverse Send me your wallet address on telegram `t.me/john_titor_master`. Also, in order to implement the house feature, I need you to record some steps and send me a HAR file.

If you really want this:

- Open BombCrypto game page
- Open Inspector (F12)
- Go to the 'Network'tab
- With this open, make the login process
- Open the Heroes tab and send some heroes to Home
- Then send them back to work
- On the 'Network' tab, select the subtab 'WS'
- There will be a 'websocket' entry in the list
- With the right mouse click, select 'Save all as HAR file with content'

Send me the file on the telegram link I provided.

A screenshot to help:
![image](https://user-images.githubusercontent.com/100624964/156906442-befbf8b4-6d19-47a1-95b4-b336976013ca.png)

**Comment by waelsy123** [comment]
how do you know if bot is still running and track progress?

**Comment by nowsys** [comment]
Hello,  thanks for providing your great work!!  If I understand correctly, I will have to set up for an enviornment where the NodeJS could be executed in PC and putting an wallet ID for executing a script.  Correct?

it would be appreciated if you could provide an instruction on how to set up an execution enviroment.  Thanks in advance.

**Comment by john-titor-master** [comment]
> Hello, thanks for providing your great work!! If I understand correctly, I will have to set up for an enviornment where the NodeJS could be executed in PC and putting an wallet ID for executing a script. Correct?
> 
> it would be appreciated if you could provide an instruction on how to set up an execution enviroment. Thanks in advance.

Take a look at the new README of the project :wink:

**Comment by rafgl** [comment]
Deixei rodando 5 contas no meu desktop linux, e ontem fui ver e acabou que encheu o SSD inteiro, o linux somente era usado para o bot, nada mais, alguma indicação sobre o que pode ter ocorrido?

**Comment by nowsys** [comment]
> > Hello, thanks for providing your great work!! If I understand correctly, I will have to set up for an enviornment where the NodeJS could be executed in PC and putting an wallet ID for executing a script. Correct?
> > it would be appreciated if you could provide an instruction on how to set up an execution enviroment. Thanks in advance.
> 
> Take a look at the new README of the project 😉

Thanks a lot!

**Comment by Manowgu** [comment]
queria que fosse facil usar  :/
