### ISSUE TITLE
Bot working?

### ISSUE THREAD

**Issue by jeffplv** [mpcabete/bombcrypto-bot#737]
Hi guys, does the bot still work with the new log in request?

**Comment by felippetadeu** [comment]
Here is working and multiaccount: https://github.com/felippetadeu/bombcrypto-multibot

**Comment by gusstta** [comment]
@felippetadeu suggestion, update the bot to send the screen of "your chest" daily on telegram, I'm using your fork and it was very good, thanks!!!!

**Comment by felippetadeu** [comment]
> @felippetadeu suggestion, update the bot to send the screen of "your chest" daily on telegram, I'm using your fork and it was very good, thanks!!!!

Atualizado!

**Comment by gusstta** [comment]
> > @felippetadeu suggestion, update the bot to send the screen of "your chest" daily on telegram, I'm using your fork and it was very good, thanks!!!!
> 
> Atualizado!

obrigado, atualizei aqui
