### ISSUE TITLE
alguem já fez algo com o novo login e senha sem utilizar a metamask?

### ISSUE THREAD

**Issue by jeanvetorello** [mpcabete/bombcrypto-bot#738]
opa alguem já fez o ajuste para utilizar login e senha , sem a metamask?

**Comment by Vitaonx** [comment]
Mano, configura você mesmo um macro, muito mias fácil e tem 0 bugs.

**Comment by felipejiman** [comment]
Já foi feito, olha para o #733

**Comment by felippetadeu** [comment]
Já foi feito nesse fork https://github.com/felippetadeu/bombcrypto-multibot
