### ISSUE TITLE
Heroes work time

### ISSUE THREAD

**Issue by nashy15973** [mpcabete/bombcrypto-bot#744]
Can I change the time interval for working heroes to 60 minutes? or more?

**Comment by caiomaggiore** [comment]
Yes, open the config.yaml file and right at the beginning there is the break time, in my place 65 minutes.
![image](https://user-images.githubusercontent.com/100660682/156954662-8d0996c1-28fa-43b5-8f93-eaa605402b9e.png)

```
  # [en_US] Time intervals configuration
  #
  # [pt_BR] Configurações de intervalos de tempo
  #
  time_intervals:
    # [en_US] Time interval for check if there are available heroes to work
    # Default value (in minutes): 65
    #
    # [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
    # Valor padrão (em minutos): 65
    send_heroes_for_work: 65
    
```
Where there is hashtag # are comments.
just change the value "send_heroes_for_work: 65"

Save and rerun Index.py
