### ISSUE TITLE
Basic login support

### ISSUE THREAD

**Issue by waelsy123** [mpcabete/bombcrypto-bot#745]
Currently there is no support for basic login with username/password. I noticed that the credentials will be saved and all we want from bot click on **login** when disconnect. This way the account would be more safe as bot will have no access to the wallet.

Is there any kind heart can add this feature? 

<img width="380" alt="Screen Shot 2022-03-08 at 11 43 44 AM" src="https://user-images.githubusercontent.com/1936754/157223131-c1e1a21b-ef61-4e8e-b567-8b0bb056cb67.png">

**Comment by gustasrod** [comment]
https://github.com/mpcabete/bombcrypto-bot/issues/746
