### ISSUE TITLE
Como logar com o usuário e senha

### ISSUE THREAD

**Issue by gustasrod** [mpcabete/bombcrypto-bot#746]
Salve galera, vi que alguns estão querendo que o bot use o usuário e senha, pois bem, agora q o bomb salva as credenciais e graças ao @[caiomaggiore](https://github.com/caiomaggiore) com o post (https://github.com/mpcabete/bombcrypto-bot/issues/733) isso é possível.

Basta seguir o passo a passo dele, mas em vez de usar a imagem "connect" usar a imagem "login"

![connect-wallet-2](https://user-images.githubusercontent.com/101228105/157349201-52621e05-bb00-41fd-b75d-419789e86c9d.png)

**Comment by isacsg** [comment]
obggg

**Comment by mixellita** [comment]
Perfeito
