### ISSUE TITLE
can't open file

### ISSUE THREAD

**Issue by zDARKYz** [mpcabete/bombcrypto-bot#748]
Boa noite, hj de meio dia cheguei em casa, desativei o bot pra usar o pc um pouco, ai quando fui ativar de novo não quer ir de jeito nenhum, alguem sabe pq
![Sem título](https://user-images.githubusercontent.com/101432141/157975494-39625b08-8818-4a6a-a2ca-a29a78bac00d.png)
?

**Comment by xclover0** [comment]
I guess you mistyped..

**python index.py**

**Comment by zDARKYz** [comment]
![image](https://user-images.githubusercontent.com/101432141/158040816-5f199b6e-d337-4b39-9a78-26acb65a8f5f.png)
