### ISSUE TITLE
Bot não enviando heróis raros para trabalhar. 

### ISSUE THREAD

**Issue by Lorethor** [mpcabete/bombcrypto-bot#75]
Olá Mpcabete!
Primeiro, parabéns!! Não só pelo bot, mas por dividir com a galera e ajudar todo mundo.
Eu quero te fazer uma contribuição, mas não quero por Paypal, e preciso saber qual é a rede da carteira (BEP2, BEP 20, ERC-20 etc).

Sobre alterações, eu te pergunto por favor: deixei hoje a primeira vez o bot rodando a noite. Mas percebi que ele só colocou os comuns pra trabalhar. Os meus raros, e o meu épico, ficaram com a barra full. Tem como alterar isso também? Obrigado,
Abraços!
Lorethor

**Comment by Lorethor** [comment]
Outra coisa: os desenvolvedores se posicionaram ONTEM oficialmente no discord: BOT está LIBERADO até que falem o contrário. @mpcabete 
Abraços!!

**Comment by cristhianbreunig** [comment]
> Olá Mpcabete! Primeiro, parabéns!! Não só pelo bot, mas por dividir com a galera e ajudar todo mundo. Eu quero te fazer uma contribuição, mas não quero por Paypal, e preciso saber qual é a rede da carteira (BEP2, BEP 20, ERC-20 etc).
> 
> Sobre alterações, eu te pergunto por favor: deixei hoje a primeira vez o bot rodando a noite. Mas percebi que ele só colocou os comuns pra trabalhar. Os meus raros, e o meu épico, ficaram com a barra full. Tem como alterar isso também? Obrigado, Abraços! Lorethor

Oi, estou utilizando o bot já fazem alguns dias, não identifiquei esse problema do envio dos heróis... ele envia o meu raro e super raro quando tem energia suficiente. Esses heróis que tu disse estavam ativos ?

**Comment by mpcabete** [comment]
Oi lorethor, a carteira eh na rede bep 20. Que estranho que ele tenha mandado só os comuns pra trabalhar, não consigo imaginar o que tenha causado isso. Vc pode me dar mais detalhes sobre esse problema? Talvez tente mudar a opção de só mandar os heróis com a barra verde e vê se ele continua ignorando os heróis que nao sao comuns.

**Comment by viniciusmartinsds** [comment]
@Lorethor foi em algum anúncio oficial que falaram q é permitido? E sabe se o uso o tempo todo também é?

**Comment by Lorethor** [comment]
> Oi lorethor, a carteira eh na rede bep 20. Que estranho que ele tenha mandado só os comuns pra trabalhar, não consigo imaginar o que tenha causado isso. Vc pode me dar mais detalhes sobre esse problema? Talvez tente mudar a opção de só mandar os heróis com a barra verde e vê se ele continua ignorando os heróis que nao sao comuns.

@mpcabete primeira coisa, mandei 50 BUSD e foi pouco não só pela utilidade do bot, mas pela sua atitude de compartilhar com a galera free. Gostaria de mandar mais, mas comprei a casa (menor, claro haha) e agora tô meio quebrado (por enquanto rs).

Então, depois de deixar rodar a segunda noite, eu vi o seguinte: não é só o comum que ele manda trabalhar, mas ele manda só de 0 a 3 workers, tipo isso, e ignora o resto. Agora de amanhã, por exemplo, tinham DEZ com a barra FULL dormindo, 2 só trabalhando quase morrendo hahaha, e três com a barra vermelha que tinham acabado de descansar. Olhando o log, eu vi que ele só mandou umas 6 vezes os workers trabalhar durante a noite, sempre 1, 2 ou 3 caras. Não sei onde mexe nessa config...
(@cristhianbreunig vi que você comentou, aqui eu me corrijo na questão dos comuns, depois de uma nova noite observando).

Outra coisa, agora que tô com a casa, gostaria de ver se a gente tem como entrar em contato direto e tentar uma customização nele (paga, claro rs) para colocar os com maior stamina pra dormir na casa, tirar proveito da recuperação rápida de stamina.

Obrigado, abraços!

**Comment by Lorethor** [comment]
> @Lorethor foi em algum anúncio oficial que falaram q é permitido? E sabe se o uso o tempo todo também é?

Sim, anúncio oficial deles no discord. Se você ainda não está no grupo, não deixa de entrar, é importante. CUIDADO com os SCAMs, tem muita gente querendo roubar lá se passando por eles. Não responde mensagem privada, só nos grupos oficiais.

**Comment by mpcabete** [comment]
Muito obrigado pela contribuição, fez minha semana 😊!

Eu fiquei observando o bot e realmente, em uma das vezes ele não enviou o meu herói raro para trabalhar, mas eu to com um pouco de dificuldade de reproduzir o problema com consistência, o que dificulta um pouco descobrir qual está sendo o problema.

Minhas hipóteses atuais são que por algum motivo o bot ta tendo dificuldade de reconhecer a imagem "green-bar.png" ou a "go-work.png".
Eu escrevi [um pequeno texto](https://github.com/mpcabete/bombcrypto-bot#ajustando-o-bot) hoje explicando como ajustar o bot.
tenta diminuir a opção `go_to_work_btn` ou a `green_bar` um pouquinho, pra algo como 0.85, e me avisa se funcionar, se não der certo talvez o problema seja outro.

Se tiver alguma ideia de como posso fazer para reproduzir o problema também pode mandar!

**Comment by mpcabete** [comment]
Em relação a casa, eu separei o issue #61 pra isso, eu nao sei se ficou mto claro la, mas se tiver dúvidas pode mandar la que eu tento explicar melhor.

**Comment by Lorethor** [comment]
> Muito obrigado pela contribuição, fez minha semana 😊!
> 
> Eu fiquei observando o bot e realmente, em uma das vezes ele não enviou o meu herói raro para trabalhar, mas eu to com um pouco de dificuldade de reproduzir o problema com consistência, o que dificulta um pouco descobrir qual está sendo o problema.
> 
> Minhas hipóteses atuais são que por algum motivo o bot ta tendo dificuldade de reconhecer a imagem "green-bar.png" ou a "go-work.png". Eu escrevi [um pequeno texto](https://github.com/mpcabete/bombcrypto-bot#ajustando-o-bot) hoje explicando como ajustar o bot. tenta diminuir a opção `go_to_work_btn` ou a `green_bar` um pouquinho, pra algo como 0.85, e me avisa se funcionar, se não der certo talvez o problema seja outro.
> 
> Se tiver alguma ideia de como posso fazer para reproduzir o problema também pode mandar!

Que legal amigo, fico feliz de ajudar sua meta!!
Eu já tinha até tentado diminuir a green bar, porque pensei que os números da stamina de heróis mais raros (por exemplo o texto 350/350 em cima da barra verde) ficassem maiores que (150/150) e pudessem ocupar mais espaço e atrapalhar o reconhecimento, então peguei só o iniciozinho do verde, mas não deu certo tampouco.

Quando inicia a rotina de "enviando herois", ele às vezes só abre a tela de herois, fica uns segundos com ela parada (não dá scroll, nem clica em ninguém), depois fecha e volta pro mapa.

Hoje de manhã de novo tinha 5 morrendo e 10 caras de boa verdões :))))
Será que tem algum lugar que ele limita a quantidade de verdes que manda?

Vou substituir todas as imagens relacionadas na dica que você me deu, e diminuir pra .85, vou avisando.

Em tempo: a atualização da casa é muito importante e potencialmente muito lucrativa.
Eu me disponibilizo a te ajudar a testar, se quiser me incluir como beta-tester, to dentro rs.

Agora sugestão: não distribua gratuitamente a casa. Uma coisa é ajudar a galera que tá começando a ganhar dinheiro ou tem pouco pra investir, fazendo o bot gratuito. Quem já comprou casa tá em outro nível de fazer grana, aí já pode - e deve - contribuir. Tipo, ter uma versão free (sem casa) e uma paga (com casa). Só uma sugestão.

Abraços!

**Comment by Lorethor** [comment]
Atualizando alguns dados:
(1) Realmente parece randomica a escolha da quantidade de heróis que ele decide mandar pra trabalhar. "clicking in 3 heroes", ou 2, ou 1, ele escolhe. Tem como configurar isso?
(2) Acho que descobri por que ele não está mandando parte dos meus para trabalhar. A imagem do go-work pega um pedaço do "rest" aceso. Quando eles estão na casa, os dois botões (work e rest) estão apagados. Já tentei pegar só o work, mas tá dando ruim hahaha. Ele acha que todo mundo agora tá descansando. Mas esse não é único problema, porque da galera que tava FULL hoje de manhã, a maior parte tava só rest. 
Vou continuar mexendo nos parametros e informando.

**Comment by Lorethor** [comment]
Atualizando... conseguir fazer ele reconhecer meu próprio print do go-work só com verde apagado, com 0.95 de confiança.
O clicking in x heroes não é aleatório, é o que falta pra completar 5 heróis, ele faz de 0 a 5. Tem alguma forma de configurar isso?
Acho que se puder configurar isso pra deixar tipo 7 heróis de cada vez, e meter os 6 piores na casinha, vai ficar 10000% perfeito

**Comment by Lorethor** [comment]
Atualizando 2... é aleatório sim... agora botei todo mundo pra descansar e ele só clicou em 4 hahaha

**Comment by mpcabete** [comment]
(1) Em relação ao "clicking in x heroes":
Este numero nao deveria ser aleatorio, o jeito que ele deveria funcionar é o seguinte:
1. O bot procura quantos herois dos que ele esta enxergando esta com a barrinha verde. o máximo vai ser 5, pq só cabem 5 herois na tela por vez.
2. o bot checha quais destes herois nao estão trabalhando. Ele faz isso procurando pelo botão apagado,
ele então clicka em todos os heróis que satisfazem estas condições, e depois da o scroll na tela e repete.

Um exemplo: 
o bot vê 5 herois, 3 deles estão com a barrinha verde, mas 2 destes 3 já esta trabalhando.
O bot vai clickar somente no que tem a barrinha verde não esta trabalhando.

Eu adicionei um log pro bot falar quantas barrinhas verdes ele detecta e quantos destes nao estão trabalhando. Nao sei se você ta com a ultima versão do bot, eu adicionei ontem
Talvez isso ajude a descobrir aonde o bot ta errando, se é na hora de reconhecer as barrinhas, na hora de reconhecer quem esta trabalhando ou em algum outro momento.

**Comment by Lorethor** [comment]
> (1) Em relação ao "clicking in x heroes": Este numero nao deveria ser aleatorio, o jeito que ele deveria funcionar é o seguinte:
> 
> 1. O bot procura quantos herois dos que ele esta enxergando esta com a barrinha verde. o máximo vai ser 5, pq só cabem 5 herois na tela por vez.
> 2. o bot checha quais destes herois nao estão trabalhando. Ele faz isso procurando pelo botão apagado,
>    ele então clicka em todos os heróis que satisfazem estas condições, e depois da o scroll na tela e repete.
> 
> Um exemplo: o bot vê 5 herois, 3 deles estão com a barrinha verde, mas 2 destes 3 já esta trabalhando. O bot vai clickar somente no que tem a barrinha verde não esta trabalhando.
> 
> Eu adicionei um log pro bot falar quantas barrinhas verdes ele detecta e quantos destes nao estão trabalhando. Nao sei se você ta com a ultima versão do bot, eu adicionei ontem Talvez isso ajude a descobrir aonde o bot ta errando, se é na hora de reconhecer as barrinhas, na hora de reconhecer quem esta trabalhando ou em algum outro momento.

Entendi, mas ele não faz scroll pra procurar mais heróis? Ele faz algumas vezes sim, outras não...
Vou pegar o novo! Valeu, abraço

**Comment by Lorethor** [comment]
Tem como alterar o código por aqui pra mandar todos os heróis com barra verde? Tipo, se tiver 8, manda os oito?
Outro ponto, se puder, queria muito realmente poder contratar seu trabalho pra fazer algumas customizações :)
Se tiver o tempo, me manda um discord no lorethor#0379
Valeu!

**Comment by Lorethor** [comment]
Bom dia, @mpcabete ! Depois de mais uma noite testando, realmente ele não tá buscando barra verde mais pra baixo, só nos 5 que estão na tela. Como eu ajusto o scroll pra ele sempre buscar de 5 ou 6 heróis fixo, rolando pra baixo pra procurar? O cenário é minerou só com os 5 primeiros e os outros 10 estão 100% rs

**Comment by Lorethor** [comment]
Só pra deixar mais claro: Você disse acima 
"o bot checha quais destes herois nao estão trabalhando. Ele faz isso procurando pelo botão apagado,
ele então clicka em todos os heróis que satisfazem estas condições, e depois da o scroll na tela e repete."

O final, scroll na tela e repete, não tá fazendo.

**Comment by felipeissa** [comment]
Opa, reproduzi no meu aqui esse problema de não enviar o heroi super raro pra trabalhar. O que acontece é que o meu heroi super raro tem bem mais energia que os comuns, então o bot não estava dando match da green-bar porque a o texto preto da energia começa bem. Minha solução local foi diminuir o tamanho 'verde' da imagem 'green-bar.png' e funcionou certinho

**Comment by Lorethor** [comment]
> (1) Em relação ao "clicking in x heroes": Este numero nao deveria ser aleatorio, o jeito que ele deveria funcionar é o seguinte:
> 
> 1. O bot procura quantos herois dos que ele esta enxergando esta com a barrinha verde. o máximo vai ser 5, pq só cabem 5 herois na tela por vez.
> 2. o bot checha quais destes herois nao estão trabalhando. Ele faz isso procurando pelo botão apagado,
>    ele então clicka em todos os heróis que satisfazem estas condições, e depois da o scroll na tela e repete.
> 
> Um exemplo: o bot vê 5 herois, 3 deles estão com a barrinha verde, mas 2 destes 3 já esta trabalhando. O bot vai clickar somente no que tem a barrinha verde não esta trabalhando.
> 
> Eu adicionei um log pro bot falar quantas barrinhas verdes ele detecta e quantos destes nao estão trabalhando. Nao sei se você ta com a ultima versão do bot, eu adicionei ontem Talvez isso ajude a descobrir aonde o bot ta errando, se é na hora de reconhecer as barrinhas, na hora de reconhecer quem esta trabalhando ou em algum outro momento.

Consegui descobrir a parada do scroll!! Tá certinho agora. Pode fechar o bug se quiser.
Você pode me contactar, @mpcabete? Para uma customização contratada? 
Me adiciona no discord, lorethor#0379, abraço!!
