### ISSUE TITLE
I guess you mistyped..

### ISSUE THREAD

**Issue by zDARKYz** [mpcabete/bombcrypto-bot#750]
I guess you mistyped..

**python index.py**

_Originally posted by @xclover0 in https://github.com/mpcabete/bombcrypto-bot/issues/748#issuecomment-1065909173_

yes but even typing right the command an error occurs

**Comment by zDARKYz** [comment]
![image](https://user-images.githubusercontent.com/101432141/158040798-6fffa7c4-5b5f-48ee-ba16-fcacabbd74be.png)

**Comment by plunck1337** [comment]
Maybe, made changes in config.yaml using Windows and corrupt the file.
Or you just don't have the config with ext .yaml on folder.

Try: 
1 - Copy what you need change in config.yaml and save into new.txt;
2 - Put the original config.yaml on bot folder(without changes/corrupts);
3 - Open the new.txt with the configs changes that you need and "save as.." config.yaml, overwrite the config.yaml and don't change the file in Windows.

Now start the script index.py!
