### ISSUE TITLE
Bot Pegaxy...

### ISSUE THREAD

**Issue by pegchargue** [mpcabete/bombcrypto-bot#753]
Boa noite!
Sei que não cabe aqui, mas como já tenho confiança neste bot e na galera daqui pensei em pesquisar aqui...
Alguém tem ou sabe de um bot de confiança e que seja funcional para o Pegaxy???
Novamente desculpas por estar perguntando aqui.

**Comment by booyxlo** [comment]
eu tenho, caso tenha interesse iLoP#0560 no disc.

**Comment by booyxlo** [comment]
> Boa noite!
> Sei que não cabe aqui, mas como já tenho confiança neste bot e na galera daqui pensei em pesquisar aqui...
> Alguém tem ou sabe de um bot de confiança e que seja funcional para o Pegaxy???
> Novamente desculpas por estar perguntando aqui.

eu tenho, caso tenha interesse iLoP#0560 no disc.
