### ISSUE TITLE
Problemas com VPS

### ISSUE THREAD

**Issue by rodrigofc93** [mpcabete/bombcrypto-bot#76]
Boa noite, alguém roda o bot em alguma VPS? To rodando em uma da Google Cloud, o problema é que quando saio da conexão remota o mouse some, e depois o bot não continua trabalhando corretamente, alguém teria alguma dica? Quando rodo meu notebook roda liso sem problemas, e lá está acontecendo isso.

**Comment by news12** [comment]
vc precisa de uma renderização de tela, se tu não tiver uma screen ativa ele não tem como calcular, uso uma vps aqui dentro de um dedicado que tenho, e abro a vps pelo painel pois la no painel vai ficar renderizando a tela, se acessar por uma tela remota, a sua tela remota é a renderização se fechar, perde a renderização.

**Comment by rodrigofc93** [comment]
> vc precisa de uma renderização de tela, se tu não tiver uma screen ativa ele não tem como calcular, uso uma vps aqui dentro de um dedicado que tenho, e abro a vps pelo painel pois la no painel vai ficar renderizando a tela, se acessar por uma tela remota, a sua tela remota é a renderização se fechar, perde a renderização.

No caso eu to usando servidor do Google Cloud, não tem como acessar pelo painel, só pela conexão remota do windows, alguma dica do que fazer?

**Comment by mpcabete** [comment]
Eu não uso a do windows, sera que não tem aquela opção de suspender ou desligar a tela nas configurações? talvez em "energia"

Talvez vale a pena dar uma testada se resolve
Eu uso em uma vps e ela funciona sem eu estar conectado sim, mas tive que desligar a opção de desligar a tela

**Comment by viniciusmeneses** [comment]
Pra quem utiliza VPS com Windows Server, você consegue manter a GUI do sistema mesmo após desconectar se utilizar o TightVNC ao invés do Windows RDP pra se conectar.

Você precisa instalar o TightVNC Server no seu VPS e o TightVNC Client no seu computador. Depois de instalar, abra as configurações do client e marque a opção `Let remote server deal with cursor` na categoria `Mouse Cursor`. Já no server, certifique-se de que na configuração `When last client disconnects` está marcada a opção `Do nothing`.

Eu também desabilitei o logoff automático quando não tem ninguém conectado na VPS, [aqui](https://www.sevenforums.com/tutorials/118889-remote-desktop-set-time-limit-idle-sessions.html) tem um tutorial mostrando como desabilitar.

**Comment by Yamatorr** [comment]
Alguém que manja pode me ajudar pfv? O meu fica dando erro, ele demora muito para logar e o bomb da time out

**Comment by testaxb3** [comment]
> Pra quem utiliza VPS com Windows Server, você consegue manter a GUI do sistema mesmo após desconectar se utilizar o TightVNC ao invés do Windows RDP pra se conectar.
> 
> Você precisa instalar o TightVNC Server no seu VPS e o TightVNC Client no seu computador. Depois de instalar, abra as configurações do client e marque a opção `Let remote server deal with cursor` na categoria `Mouse Cursor`. Já no server, certifique-se de que na configuração `When last client disconnects` está marcada a opção `Do nothing`.
> 
> Eu também desabilitei o logoff automático quando não tem ninguém conectado na VPS, [aqui](https://www.sevenforums.com/tutorials/118889-remote-desktop-set-time-limit-idle-sessions.html) tem um tutorial mostrando como fazer isso.

Amigo, comprei duas vps aqui para ligar meus bombs com o macro mas estou tendo dificuldade, vi que tu entende do assunto, será que podia me ajudar?

**Comment by Yamatorr** [comment]
> > Pra quem utiliza VPS com Windows Server, você consegue manter a GUI do sistema mesmo após desconectar se utilizar o TightVNC ao invés do Windows RDP pra se conectar.
> > Você precisa instalar o TightVNC Server no seu VPS e o TightVNC Client no seu computador. Depois de instalar, abra as configurações do client e marque a opção `Let remote server deal with cursor` na categoria `Mouse Cursor`. Já no server, certifique-se de que na configuração `When last client disconnects` está marcada a opção `Do nothing`.
> > Eu também desabilitei o logoff automático quando não tem ninguém conectado na VPS, [aqui](https://www.sevenforums.com/tutorials/118889-remote-desktop-set-time-limit-idle-sessions.html) tem um tutorial mostrando como fazer isso.
> 
> Amigo, comprei duas vps aqui para ligar meus bombs com o macro mas estou tendo dificuldade, vi que tu entende do assunto, será que podia me ajudar?



> > Pra quem utiliza VPS com Windows Server, você consegue manter a GUI do sistema mesmo após desconectar se utilizar o TightVNC ao invés do Windows RDP pra se conectar.
> > Você precisa instalar o TightVNC Server no seu VPS e o TightVNC Client no seu computador. Depois de instalar, abra as configurações do client e marque a opção `Let remote server deal with cursor` na categoria `Mouse Cursor`. Já no server, certifique-se de que na configuração `When last client disconnects` está marcada a opção `Do nothing`.
> > Eu também desabilitei o logoff automático quando não tem ninguém conectado na VPS, [aqui](https://www.sevenforums.com/tutorials/118889-remote-desktop-set-time-limit-idle-sessions.html) tem um tutorial mostrando como fazer isso.
> 
> Amigo, comprei duas vps aqui para ligar meus bombs com o macro mas estou tendo dificuldade, vi que tu entende do assunto, será que podia me ajudar?

Add Yamator#0639 se quiser a gente tenta fazer junto

**Comment by fguide** [comment]
Esse problema é por conta de acessar via remote desktop, você pode utilizar o VNC como sugeriram ou utilizar o comando abaixo toda vez que desconectar da VM, o único ponto é que ele mantem a sessão aberta, se for um provedor privado não há tanto risco de segurança.

for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (tscon.exe %%s /dest:console)

Esse comando envia a sessão RDP para o console, e assim ela fica ativa com o bot rodando. Fica a dica para quando sair a versão corrigida.

**Comment by leomsfreitas** [comment]
Se você estiver usando um servidor Ubuntu ou Linux e estiver fazendo o acesso remoto pelo SSH tente isso:

`npm install pm2@latest -g`

Isso vai instalar o PM2 que é responsavel por deixar rodando os arquivos 24/7 sem precisar de uma conexão remota. Após a instalação você vai buscar seu arquivo executável com o `ls` depois de um `cd nomedoarquivooupasta` agora só executar o comando `pm2 start app.js` -> np "app.js" você coloca o nome do arquivo que quer executar. 

Mais comandos do PM2 diponível aqui: https://pm2.keymetrics.io/docs/usage/quick-start/

Espero ter ajudado!
