### ISSUE TITLE
Go to work problem

### ISSUE THREAD

**Issue by MarcosEgles** [mpcabete/bombcrypto-bot#764]
Anyone having problems with the new green bar look?
I have changed the images on the folders but when it goes to click on "go-work" it does it on the wrong place ( coordenate ), over the bar because the new one is bigger than the old one, any solutions to change the coordenate of the "work" click ?
Thanks

**Comment by kristiansendm** [comment]
Hi mate!

I'm having the same problem as you.
Anyone with a solution??
Also the bot is confusing the green bars, as we have the stamina bar and the shield bar, now it's identifying as the bar is always green, and then sending the heroes to work everytime, even when they are exhausted!

Thx!

**Comment by lnlessa** [comment]
> Hi mate!
> 
> I'm having the same problem as you. Anyone with a solution?? Also the bot is confusing the green bars, as we have the stamina bar and the shield bar, now it's identifying as the bar is always green, and then sending the heroes to work everytime, even when they are exhausted!
> 
> Thx!

well at least yours are working! how did you edit the images? mine refuses to click on the work button and I've tried pretty much everything.

**Comment by kristiansendm** [comment]
> > Hi mate!
> > I'm having the same problem as you. Anyone with a solution?? Also the bot is confusing the green bars, as we have the stamina bar and the shield bar, now it's identifying as the bar is always green, and then sending the heroes to work everytime, even when they are exhausted!
> > Thx!
> 
> well at least yours are working! how did you edit the images? mine refuses to click on the work button and I've tried pretty much everything.

Actually it's not working. I took a new picture of the green bar, sometimes it does click to work, sometimes it doesnt, but a lot of bugs. Then it freezes and disconnect.

**Comment by lnlessa** [comment]
well, while nobody finds a fix for this, I changed the config file to send all heroes to work every 10 minutes and changed the work button to the "all" button in the targets folder. not ideal but at least they are working.

**Comment by GilbertoRosendo** [comment]
I changed the "go-work", "green-bar" and "full-stamina" buttons, for now it's working perfectly.

**Comment by lnlessa** [comment]
> I changed the "go-work", "green-bar" and "full-stamina" buttons, for now it's working perfectly.

can you send us yours?

**Comment by domingosiglesias** [comment]
> I changed the "go-work", "green-bar" and "full-stamina" buttons, for now it's working perfectly.

Você pode enviar as imagens novas ? tentei fazer aqui por conta não deu certo ele passa direto pelos verdinhos....

**Comment by MarcosEgles** [comment]
I did some work, take a loot of images and finally found 1 working good for me so far guys,
U guys can try it out, but i had to change the threshold value of "green-bar" to 0.8 for it to work, hope it helps.
![green-bar](https://user-images.githubusercontent.com/95984745/171714297-f6edde4f-947f-4eaf-9f38-0cab4e2440a2.png)
![go-work](https://user-images.githubusercontent.com/95984745/171714922-c016cfe2-d34b-4600-aa9e-b278941a7e83.png)

**Comment by lnlessa** [comment]
> I did some work, take a loot of images and finally found 1 working good for me so far guys, U guys can try it out, but i had to change the threshold value of "green-bar" to 0.8 for it to work, hope it helps. ![green-bar](https://user-images.githubusercontent.com/95984745/171714297-f6edde4f-947f-4eaf-9f38-0cab4e2440a2.png) ![go-work](https://user-images.githubusercontent.com/95984745/171714922-c016cfe2-d34b-4600-aa9e-b278941a7e83.png)

just tested, it works most of the time but sometimes it still misses the work button

**Comment by domingosiglesias** [comment]
> I did some work, take a loot of images and finally found 1 working good for me so far guys, U guys can try it out, but i had to change the threshold value of "green-bar" to 0.8 for it to work, hope it helps. ![green-bar](https://user-images.githubusercontent.com/95984745/171714297-f6edde4f-947f-4eaf-9f38-0cab4e2440a2.png) ![go-work](https://user-images.githubusercontent.com/95984745/171714922-c016cfe2-d34b-4600-aa9e-b278941a7e83.png)

Deu certo aqui está funcionando... obrigado!

**Comment by hashbuster-art** [comment]
![image](https://user-images.githubusercontent.com/106784200/171752657-fe3cf1d2-a36d-477e-a518-7c7043503d25.png)
![image](https://user-images.githubusercontent.com/106784200/171752702-5e2deeed-1c92-49ad-98c8-f4eca2f281ee.png)
try this doesnt miss

**Comment by MarcosEgles** [comment]
> > I did some work, take a loot of images and finally found 1 working good for me so far guys, U guys can try it out, but i had to change the threshold value of "green-bar" to 0.8 for it to work, hope it helps. ![green-bar](https://user-images.githubusercontent.com/95984745/171714297-f6edde4f-947f-4eaf-9f38-0cab4e2440a2.png) ![go-work](https://user-images.githubusercontent.com/95984745/171714922-c016cfe2-d34b-4600-aa9e-b278941a7e83.png)
> 
> just tested, it works most of the time but sometimes it still misses the work button

Here it's working just fine... did u change the treshold?

**Comment by ZecaRodrigues** [comment]
Sorry for the total lack of knowledge, but certain I appreciate your help!  
But I changed the button "Work" ok, but then i did not understand what I have to change on the green bar. Do I have to change this file for all "hero_bar_0, 10, 20,..."? 
Once again, sorry for my total lack of knowledge and thanks in advance.

**Comment by dosanjosbreno** [comment]
Gente, alguém arruma aí pra gente, por favor! Tá foda.
Guys, someone fix it for us, please!

**Comment by domingosiglesias** [comment]
mesmo mudando as imagens e mudado o green-bar" para 0.8 ainda estou com problemas no bot, alguém tem uma solução ? não quero perder noites sem dormir novamente kkkkkkkkk

**Comment by kristiansendm** [comment]
> mesmo mudando as imagens e mudado o green-bar" para 0.8 ainda estou com problemas no bot, alguém tem uma solução ? não quero perder noites sem dormir novamente kkkkkkkkk

Bom dia, ferramenta!
Eu troquei o threshold do greenbar pra 0.8 e o Go to Work Button pra 0.95. Não está perfeito, mas está funcionando. Se não conseguir, tenta tirar prints de diferentes partes da barra verde, que ele vai mudando a localização de click na tela.

Abraço

**Comment by ZecaRodrigues** [comment]
Fala

> > mesmo mudando as imagens e mudado o green-bar" para 0.8 ainda estou com problemas no bot, alguém tem uma solução ? não quero perder noites sem dormir novamente kkkkkkkkk
> 
> Bom dia, ferramenta! Eu troquei o threshold do greenbar pra 0.8 e o Go to Work Button pra 0.95. Não está perfeito, mas está funcionando. Se não conseguir, tenta tirar prints de diferentes partes da barra verde, que ele vai mudando a localização de click na tela.
> 
> Abraço

Fala cara, onde mudo essas configurações? Em qual arquivo? Desde já agradeço imensamente!

**Comment by kristiansendm** [comment]
> Fala
> 
> > > mesmo mudando as imagens e mudado o green-bar" para 0.8 ainda estou com problemas no bot, alguém tem uma solução ? não quero perder noites sem dormir novamente kkkkkkkkk
> > 
> > 
> > Bom dia, ferramenta! Eu troquei o threshold do greenbar pra 0.8 e o Go to Work Button pra 0.95. Não está perfeito, mas está funcionando. Se não conseguir, tenta tirar prints de diferentes partes da barra verde, que ele vai mudando a localização de click na tela.
> > Abraço
> 
> Fala cara, onde mudo essas configurações? Em qual arquivo? Desde já agradeço imensamente!

No "config.yaml".
