### ISSUE TITLE
Problema em Go to Work 

### ISSUE THREAD

**Issue by kristiansendm** [mpcabete/bombcrypto-bot#769]
Alguém mais com problema pro bot clicar em Work depois da última atualização que foram alterados os botões?
Novos prints já feitos, porém o bot clica no local errado da tela.

**Comment by Frisoni** [comment]
Sim, tive esse problema.
Lá no index.py, procura por essas linhas:
def clickGreenBarButtons():
    # ele clicka nos q tao trabaiano mas axo q n importa
    offset = 220

Vai aumentando o offset e testando até funcionar. O meu, em 220 clicou legal.

**Comment by philipperay** [comment]
O meu funciou com o offset = 200

Mas agora nao esta mais funcionando o comando de rolar para baixo para selecionar os outros heros. Alguem sabe a soluçao?

**Comment by kristiansendm** [comment]
> O meu funciou com o offset = 200
> 
> Mas agora nao esta mais funcionando o comando de rolar para baixo para selecionar os outros heros. Alguem sabe a soluçao?

O meu também está dessa forma...

**Comment by kristiansendm** [comment]
> O meu funciou com o offset = 200
> 
> Mas agora nao esta mais funcionando o comando de rolar para baixo para selecionar os outros heros. Alguem sabe a soluçao?

Meu amigo, uma forma que encontrei para contornar esse problema colocando os heroes para trabalhar, mas sem usar o scroll. Conforme ele clica nos greens, os que estão sem stamina vem pro topo e assim ele vai clicando ao longo do tempo, colocando todos para trabalhar.

    # Valor padrão: 0.9
    go_to_work_btn: 0.95


Em config.yaml altere o o valor do gotowork para 0.95

**Comment by Frisoni** [comment]
Precisa trocar a imagem do scroll também.
Substitui a commom-text.png.
Tenta usar essa que eu fiz que tá funcionando aqui: https://raw.githubusercontent.com/Frisoni/bombcrypto-bot/main/targets/commom-text.png

**Comment by philipperay** [comment]
Obrigado pelas dicas, aqui agora está funcionando 100%

**Comment by kristiansendm** [comment]
> Precisa trocar a imagem do scroll também. Substitui a commom-text.png. Tenta usar essa que eu fiz que tá funcionando aqui: https://raw.githubusercontent.com/Frisoni/bombcrypto-bot/main/targets/commom-text.png

Boa Frisoni. Deu certo aqui! 
Obrigado

**Comment by Pilvx** [comment]
ALguem por favor poderia enviar o arquivo completo pra mim aqui nao esta funcionando

**Comment by Pilvx** [comment]
O que eu baxei do frisoni esta dando um erro de import gi

**Comment by brunnofrancis** [comment]
aqui ja troquei as imagens mais o bot conecta mais clica no modo amazon para começa o farme
