### ISSUE TITLE
contato

### ISSUE THREAD

**Issue by xeteu10** [mpcabete/bombcrypto-bot#772]
gostaria de saber se voce poderia me ajudar a fazer um bot para um jogo web bem simples, e quanto ficaria, meu contato matagoliveira @gmail. com

**Comment by Nucito** [comment]
> gostaria de saber se voce poderia me ajudar a fazer um bot para um jogo web bem simples, e quanto ficaria, meu contato matagoliveira @gmail. com

Entra em contato pelo discord: Cartman#6666
