### ISSUE TITLE
memory error(-4:Insufficient memory)

### ISSUE THREAD

**Issue by pavelbush** [mpcabete/bombcrypto-bot#78]
Sometimes i get this error, how to fix it?

![2021-11-28_17-59-34](https://user-images.githubusercontent.com/27809657/143765209-35bc9b94-3ea2-490b-95e0-ab27b35473d0.png)

**Comment by mpcabete** [comment]
vish, qual eh o sistema q ta rodando ele? eh num desktop ou numa vps?

**Comment by pavelbush** [comment]
> vish, qual eh o sistema q ta rodando ele? eh num desktop ou numa vps?

Virtual box, windows 10 (6 gb ram, 20 gb space)

**Comment by mpcabete** [comment]
Que estanho, não sei por que ta dando esse erro não, pela mensagem de erro parece que ele não esta conseguindo alocar memoria ram suficiente, mas pelos meus cálculos aquilo da 17 megas só.
Vamo ve se mais alguém aparece com o mesmo problema ou alguma ideia

**Comment by jeffersfp** [comment]
hey @pavelbush check your memory usage when running the bot... it looks like you're running out of memory for some reason, maybe you are running to much stuff while also running the bot or the bot itself might be eating too much memory

**Comment by Novaisxd** [comment]
What was the fix to this?

**Comment by Nucito** [comment]
> What was the fix to this?

Increase your memory ram🙂
