### ISSUE TITLE
Só enviar comuns para trabalho.

### ISSUE THREAD

**Issue by aLexNFT1** [mpcabete/bombcrypto-bot#79]
Olá, primeiramente gostaria de parabenizar o trabalho, está realmente ajudando muitas pessoas, ainda não fiz minha contribuição mas em breve vou estar enviando.
Gostaria de dar minha sujestão para melhorar ainda mais o BOT.

- Adicionar a opção de colocar apenas herois comuns para trabalhar. (Geralmente eu uso meus herois raros, super raros, epicos e etc com uma certa estratégia, então colocando essa opção ajudaria muito.

Por enquanto é isso, muito obrigado!

**Comment by mdavinicius** [comment]
Não sei se é possível, mas achei sensacional a ideia!

**Comment by mpcabete** [comment]
Opa, que bom que esta gostando do bot.
Gostei da sugestão, pode ser bem util pro pessoal mesmo!
Assim que eu terminar as atualizações que estou trabalhando vou adicionar essa opção!
Pode ir me cobrando se eu demorar hehehe

**Comment by mdavinicius** [comment]
Eu só consigo falar com base na minha experiência (e da minha conta, que só tem 3 raros, o resto comum). 
De acordo com o Bomb Simulator, meus raros demoram de 5h a 8h20 pra recuperar full HP.

Hoje, depois do ultimo update, eu uso o bot com a configuração de só por Hero pra jogar quando esta com a barra FULL.
Não sei se seria possível fazer o bot ter definições de tempo para cada raridade / nivel da barra.
Ex:
- Comum - sempre que tiver full
- Raro - a cada 5hrs
- Epico - a cada X horas
- etc etc etc

Assim os comuns iriam entrar em jogo ASAP, e os mais fortes no range de horas que você definir.

E ai quando eu ponho os Raros em campo, eu não deixo Comum atrapalhando la.
Então por uma regra de que Se selecionar um hero mais forte que Normal, poe todos os normais pra descansar.

Mas eu tambem não sei se por várias condições assim vai fazer o bot ficar muito tempo na tela de seleção pra por o set up pra rodar . Foram só idéias xD

**Comment by cristhianbreunig** [comment]
> Eu só consigo falar com base na minha experiência (e da minha conta, que só tem 3 raros, o resto comum). De acordo com o Bomb Simulator, meus raros demoram de 5h a 8h20 pra recuperar full HP.
> 
> Hoje, depois do ultimo update, eu uso o bot com a configuração de só por Hero pra jogar quando esta com a barra FULL. Não sei se seria possível fazer o bot ter definições de tempo para cada raridade / nivel da barra. Ex:
> 
> * Comum - sempre que tiver full
> * Raro - a cada 5hrs
> * Epico - a cada X horas
> * etc etc etc
> 
> Assim os comuns iriam entrar em jogo ASAP, e os mais fortes no range de horas que você definir.
> 
> E ai quando eu ponho os Raros em campo, eu não deixo Comum atrapalhando la. Então por uma regra de que Se selecionar um hero mais forte que Normal, poe todos os normais pra descansar.
> 
> Mas eu tambem não sei se por várias condições assim vai fazer o bot ficar muito tempo na tela de seleção pra por o set up pra rodar . Foram só idéias xD

Eu acho que inicialmente precisamos identificar essa classificação dos heróis, daí com isso podemos criar uma nova configuração. Nessa configuração, seria definido se queremos controlar a seleção de heróis por raridade (_padrão = não, para manter como está hoje_) com isso, poderíamos controlar o modo de envio.

Se a configuração de raridade está marcada como sim, utilizaríamos outras configurações, que seriam configuráveis de acordo com a raridade, com isso já iria melhorar bastante o controle do envio dos heróis (_no meu caso seria bem útil quando pretendo deixar o bot funcionando por um curto período de tempo, daí poderia definir para utilizar somente os que desejo_), segue exemplo do que pensei:

#utilizado para verificar se o envio (_verificação da energia_) será geral ou conforme o tipo
select_heroes_by_rarity = True

#configuração para envio, conforme a raridade, se a configuração acima estiver = "True"
select_common_heroes_mode = "green"
select_rare_heroes_mode = "green"
select_super_rare_heroes_mode = "full"
select_epic_heroes_mode = "full"
select_legendary_heroes_mode = "full"

Vejo que isso seria bem útil para posterior uso com as estratégias, a ideia seria verificar essas configurações na hora de mandar os heróis, porém, além disso seria verificado a ordem de relevância.

O que imagino sobre a relevância é ter um controle para não enviar dois super raros ao mesmo tempo por exemplo, ou não enviar os comuns junto com algum mais forte (_para não gastar energia à toa_)

**Comment by mpcabete** [comment]
Gostei bastante da divisão das tarefas christian, eu acabei nao pesquisando mto de estrategia pq eu so tenho 1 heroi raro, o resto é tudo comum, entao só deixo rodando lá mesmo.
Mas gostei bastante de como vc dividiu o desafio em pedaços menores. pode ser divertido tentar implementar essa funcionalidade.
Para estimar a dificuldade do mapa um script pra contar quantos de cada baú tem no mapa seria bem tranquilo de fazer, dai so n sei mto como usar essas informações pra escolher a estratégia hehehe
