### ISSUE TITLE
Scrolling insuficiente

### ISSUE THREAD

**Issue by hyrton091099** [mpcabete/bombcrypto-bot#8]
Boa noite! Primeiro quero agradecer pelo bot, ele tá ajudando muito.
O único problema aqui é que na hora de colocar os heros pra trabalhar, ele não scrolla o suficiente para alcançar o último hero de baixo. O botão "work" fica pela metade ou menos e o bot acaba não detectando. Como posso resolver isso?

**Comment by mpcabete** [comment]
tanta mudar essa config pra true no arquivo config.yaml
use_click_and_drag_instead_of_scroll: false
pra
use_click_and_drag_instead_of_scroll: true

**Comment by hyrton091099** [comment]
funcionou!! Obrigado
