### ISSUE TITLE
Metamask

### ISSUE THREAD

**Issue by tocadiscosz** [mpcabete/bombcrypto-bot#80]
No meu caso na hora de confirmar a metamask o mouse não está indo pro lado direito, ele está indo pra cima, assim o bot não reconecta quando da erro por exemplo, de resto ta funcionando normal.

**Comment by mpcabete** [comment]
Olá tocas, da uma olhada [nessa parte](https://github.com/mpcabete/bombcrypto-bot#ajustando-o-bot) que eu adicionei agora ao manual do bot, acredito que o seu problema seja um falso positivo no momento de clickar no botao de confirmar a metamask.
Depois me da um retorno se deu pra entender certinho o texto, ou se algo ficou confuso 🙂
Vou fechar o issue pra poder manter a organização, mas pode falar por aqui  que eu vejo.
