### ISSUE TITLE
heroi super-raro não sendo reconhecido.

### ISSUE THREAD

**Issue by cadugevaerd** [mpcabete/bombcrypto-bot#81]
Por vezes ao selecionar os herois paraa trabalhar, o mesmo ignora o super-raro.. fazendo com que ele seja o único a não ir farmar.

**Comment by mpcabete** [comment]
Parece que bastante gente está tendo esse problema, vou usar este issue pra gnt ir conversando e tentar descobrir o que está acontecendo.

**Comment by mpcabete** [comment]
Olá cadu, parece que mais gente esta tendo este problema, eu mudei o nome de outro issue que abriram sobre este problema e vou te direcionar, pra lá pra gnt ir conversando e tentar resolver este problema juntos!

**Comment by cadugevaerd** [comment]
Só para deixar como observação, não é sempre que acontece. então no final não atrapalha muito o farm
