### ISSUE TITLE
Multi Account

### ISSUE THREAD

**Issue by drwillsmith** [mpcabete/bombcrypto-bot#82]
Boa tarde! 

Tenho interesse em contribuir com o projeto, mas estava procurando a possibilidade de usar o bot em multi-account.

Existe alguma forma de negociarmos isso? 

Aguardo Resposta, forte abraço.

**Comment by mpcabete** [comment]
Olá, por enquanto o bot não suporta multi conta não. Programei ele pensando em rodar em uma conta só.
A próxima coisa que eu vou fazer vai ser um guia de como rodar este bot em uma VPS, com essa estratégia fica bem facil rodar mais de uma conta, cada um em um computador diferente.
Se tudo der certo o guia deve sair ainda essa semana. Rodar em máquinas virtuais usando virtual box também funcionaria pra rodar em um computador só, mas eh meio chatinho de configurar :/

**Comment by pavelbush** [comment]
> Olá, por enquanto o bot não suporta multi conta não. Programei ele pensando em rodar em uma conta só. A próxima coisa que eu vou fazer vai ser um guia de como rodar este bot em uma VPS, com essa estratégia fica bem facil rodar mais de uma conta, cada um em um computador diferente. Se tudo der certo o guia deve sair ainda essa semana. Rodar em máquinas virtuais usando virtual box também funcionaria pra rodar em um computador só, mas eh meio chatinho de configurar :/

Thank you! For me all works nice, only i need to check virtuals sometimes :)

**Comment by dpb666** [comment]
sa ne fonctionne pas
