### ISSUE TITLE
Sugestão de Configuração

### ISSUE THREAD

**Issue by Cromaz** [mpcabete/bombcrypto-bot#83]
Olá, Primeiramente parabenizar por compartilhar seu código. Amanhã é dia de saque e mandarei minha contribuição, pois agora posso ir dormir ainda mais tranquilo, merece.

Na verdade tenho uma sugestão e apontar um problema. 

Sugestão: Mandar para casa. Adicionar nas configurações do bot para pode escolher enviar herois para a casa e também pode setar a raridade dos herois que vão pra casa.

Problema: Por algum motivo o bot não manda meus herois de raridade maior do que Raro para trabalhar, ele ignora super-raro pra cima. Não sei se é assim pra todo mundo, mas comigo está acontecendo isso.

**Comment by mpcabete** [comment]
Olá, eu ficaria mto feliz com a contribuição 😊!
Em relação ao problema, parece que mais pessoas estao tendo esse problema, to conversando com o pessoal pra tentar resolver.
Eu renomeei esse issue pra algo mais descritivo pra podermos conversar melhor:
#75 

Em relação à sugestão, eu ja estou trabalhando nisso, vou ver se consigo separar um issue pro pessoal que quer esta funcionalidade ir me ajudando a testar. Vou mandar o link aqui se lembrar.
Vou fechar o issue pra ajudar na organização, qualquer coisa pode falar aqui também que eu vejo.

**Comment by mpcabete** [comment]
por enquanto eu deixei o #61 aberto, la eu comentei sobre como a funcionalidade, se tiver dúvidas manda la que eu explico melhor como faz, não sei se ta mto claro.
