### ISSUE TITLE
 Bot não ta clicando em signIn

### ISSUE THREAD

**Issue by marcuscaum** [mpcabete/bombcrypto-bot#85]
O bot nao ta clicando mais no botão de signin do metamask...

**Comment by aLexNFT1** [comment]
Sua metamask está em inglês? se tiver em português não vai funcionar.

**Comment by marcuscaum** [comment]
ta em ingles

**Comment by marcuscaum** [comment]
o connect wallet ta rodando, ele abre o modal da metamask mas nao clica no botao azul sign

**Comment by marcuscaum** [comment]
tentei alterar tanto o trashold quanto a image e mesmo assim nao esta rolando...

**Comment by mpcabete** [comment]
o threshold vc diminuiu?

**Comment by HeeyMan** [comment]
Aqui também está assim, na maquina virtual que usava antes estava indo de boas, mas na com o windows 7 na hora de clicar em sing in no lugar de ir pro canto superior direito, ele vai pra esquerda/centro superior

**Comment by marcuscaum** [comment]
@mpcabete simm diminui até 0.5

**Comment by mpcabete** [comment]
Seguinte, se o mouse não meche, vc tem q diminuir o threshold, se ele meche, mas vai pro lugar errado vc tem q aumentar.

**Comment by marcuscaum** [comment]
resolvi setando manualmente a position do cursor
