### ISSUE TITLE
Bot não espera para ver se vai dar erro na hora de conectar

### ISSUE THREAD

**Issue by mauricioleft121** [mpcabete/bombcrypto-bot#87]
Então, percebi que no código onde você faz o login, não acontece a questão de esperar para ver se ele vai dar erro ou coisa do tipo,
não sou programador de python então não sei ao certo como mexer, mas a minha sugestão é colocar em loop a parte de tentar login testando se vai aparecer o botão de OK de erro, e assim que conseguisse logar, ele saia do loop.
Gostaria muito de ajudar, mas só trabalho com javascript, mas gostaria de deixar minha dica pois me parece algo fácil de se solucionar.

**Comment by mauricioleft121** [comment]
Uma edição que eu fiz aliás, com meu pouco conhecimento de pyautogui, foi mudar o simples refresh de F5 para um shift+F5 para que ele de refresh no cache tbm.

**Comment by reynario** [comment]
@mauricioleft121 também estou com esse problema, como posso alterar esse comando ? 

Se bem que o meu quando dá erro não vai para lugar nenhum, o bot pensa q esta rodando e fica como se estivesse esperando os bomber trabalhar mas não atualiza a página  a página em momento nenhum.

**Comment by mauricioleft121** [comment]
> @mauricioleft121 também estou com esse problema, como posso alterar esse comando ?
> 
> Se bem que o meu quando dá erro não vai para lugar nenhum, o bot pensa q esta rodando e fica como se estivesse esperando os bomber trabalhar mas não atualiza a página a página em momento nenhum.

Cara, a real é q é só esperar, ele vai voltar na tentativa de login, vai reconhecer o OK e vai seguir o caminho dele, a sugestão que dei é q ele não siga o caminho dele até q consiga executar o login.
