### ISSUE TITLE
Poderia me dar uma ajuda?

### ISSUE THREAD

**Issue by rdiegoss** [mpcabete/bombcrypto-bot#9]
Olá amigo, tudo bem? Primeiramente MUITO OBRIGADO pelo bot, a comunidade precisa de mais gente como vc, disposta a ajudar os outros, na verdade, o mundo precisa de mais gente assim.

Não manjo nada de Python, porém, instalei tudo certinho e coloquei para rodar, porém, nada acontece no jogo, já deixei na tela de "treasure hunter" na de connect wallet tb, porém, nada acontece.... Poderia me explicar como fazer rodar ?

Só fica preso nesse print:
<img width="398" alt="Screen Shot 2021-11-10 at 09 53 52" src="https://user-images.githubusercontent.com/10976074/141119523-2fafefc7-e19d-4087-b000-f4d4f708d3ae.png">

Já rodei e deixei a tela do jogo aberta tb, mas simplesmente nada acontece....

SO: MacOS
Browser: Firefox

Agradeço demais amigo.

**Comment by mpcabete** [comment]
Bem, pelas mensagens parece que o bot ta rodando, mas por algum motivo ele não esta reconhecendo os botoes. Tenta mudar o zoom da página pra 100%.

**Comment by rdiegoss** [comment]
Esses "time outs" são normais? Ou era para já esta acontecendo algo? Tentei por em 100% mas continua do mesmo jeito :(

**Comment by mpcabete** [comment]
São sim, estes são os botoes que ele procura pra fazer login, se você nao estiver na tela de login ele vai dar os time-outs mesmo. Tenta abrir a pasta targets e vê se ele reconhece as imagens que estao lá, se você deixar a imagem aberta ele deveria clickar nelas.
Outra coisa, você usa um monitor ou dois

**Comment by rdiegoss** [comment]
Muito obrigado pela resposta amigo, eu estou usando apenas no monitor mesmo no MacBook, é um de 13. 

Tentei fazer o teste de abrir as imagens individualmente da pasta target, rodar o bot, mas realmente não acontece nada.

Deixei a imagem de "connect Wallet", e quando chegou na parte "waiting for "connectWalltBtn" ainda deu timeout ... 

Mas tudo bem, acontece, deve ser algo com minha resolução ou algo do tipo.

**Comment by jbbbenji08** [comment]
ola eu tenho o mesmo problema, você poderia resolver isso?
