### ISSUE TITLE
[Dúvida] É possivel jogar com o monitor desligado?

### ISSUE THREAD

**Issue by Joaowo** [mpcabete/bombcrypto-bot#90]
Uma vez que o bot reconhece as imagens na tela, gostaria de saber se tem como jogar com o monitor desligado ou sem monitor ( as vezes eu preciso trocar ele de computador para usar em outras coisas  e quero deixar o bot rodando )

Obrigado!

**Comment by Hermanyo** [comment]
> Uma vez que o bot reconhece as imagens na tela, gostaria de saber se tem como jogar com o monitor desligado ou sem monitor ( as vezes eu preciso trocar ele de computador para usar em outras coisas e quero deixar o bot rodando )
> 
> Obrigado!

Pode sim, só não vai funcionar se você colocar algum tipo de proteção de tela, ou algo que fique na frente. E você também não pode mexer no mouse. Tirar o monitor vai funcionar do mesmo jeito.
