### ISSUE TITLE
Linux server configuration

### ISSUE THREAD

**Issue by emiarg10** [mpcabete/bombcrypto-bot#92]
First of all, thank you very much for the bot!

Hello, I am trying to leave it configured in a linux server of google cloud, but when executing the python file I get the following error:
![error](https://user-images.githubusercontent.com/59748355/144326664-ec84abab-bd28-4e53-90fa-6eb884a2c6e8.png)

**mss.exception.screenshoterror: noxrandr extension found.**

I imagine that it has something to do with the visualization of the screen, since the only active monitor is the one of my connection through vnc viewer. And I suppose that I will have to configure so that I always have an active monitor even if I am not connected or something like that. Can you help me please?

Thank you

**Comment by rafaelgalani** [comment]
I can't tell whether that's an SSH or a VNC - it looks like the former. 
If that's the case, then it won't work. You need an X environment for it to work properly. 
Try running `xrandr` and pasting the output here so we can help you further.
