### ISSUE TITLE
Puzzle

### ISSUE THREAD

**Issue by rodrigobragamg** [mpcabete/bombcrypto-bot#95]
Deixando aqui soluções já criadas previamente, cujo quais resolvem o puzzle estilo "jigsaw" que foi implementado no Bomb:
https://gist.github.com/licensed/51f12b36bdef083cb3e37597fb62003b
https://pythonmana.com/2021/02/20210223164623700z.html

**Comment by mdavinicius** [comment]
Que rapido!

**Comment by gabrielwjesus** [comment]
top, vou tentar hoje essa solução, mas por enqto o negócio é fazer uma atualização que gere um alerta caso o jogo caia... tipo emitir um som alto ou mensagem pelo whatsapp para te acordar e reiniciar o jogo.

**Comment by cryptoenthusiast33** [comment]
I couldn't resolve the situation myself but I found this guys and they managed to make it work:
Não consegui resolver a situação eu mesmo mas achei esse pessoal que conseguiu no Discord abaixo:

https://discord.me/BombFarm

**Comment by mpcabete** [comment]
O primeiro parece que ele manipula o driver do browser, mas o segundo eh promissor, vou ver se consigo fazer funcionar

**Comment by 3Riders** [comment]
> O primeiro parece que ele manipula o driver do browser, mas o segundo eh promissor, vou ver se consigo fazer funcionar

Tenho fé em ti, excelente trabalho. Estou em pulgas para testar.

**Comment by wanderaugusto** [comment]
> O primeiro parece que ele manipula o driver do browser, mas o segundo eh promissor, vou ver se consigo fazer funcionar

tenho fé que vai conseguir e quando upar o codigo novo vou te dar 5bcoin pode cobrar . Obrigado ai

**Comment by gabrielwjesus** [comment]
eu reparei que o captcha aparece em momentos aleatorios, com imagens aleatorias... e isso dificulta um pouco pois teriamos que criar um banco de dados com possiveis imagens do jogo. Ela tira foto da tela, valida com o banco de dados qual a imagem mais proxima e então encontra o gap e desliza. Isso é bem complexo. 
outra opção (que eu ainda não verifiquei) é procurar pela imagem do puzzle e fazer deslizar a imagem até em cima da area do puzzle (problema é que eu não sei se o puzzle é sempre igual ou não).

**Comment by Nydoehar** [comment]
> O primeiro parece que ele manipula o driver do browser, mas o segundo eh promissor, vou ver se consigo fazer funcionar

Temos fé em você. Assim que tirar meu ROI (jogo a uns 8 dias) faço questão de te enviar 10Bcoins.

**Comment by Nydoehar** [comment]
> outra opção (que eu ainda não verifiquei) é procurar pela imagem do puzzle e fazer deslizar a imagem até em cima da area do puzzle (problema é que eu não sei se o puzzle é sempre igual ou não).

Acredito que o mpcabete está tentando fazer isso. Rezemos para que ele consiga!

**Comment by Psicrow** [comment]
> Deixando aqui soluções já criadas previamente, cujo quais resolvem o puzzle estilo "jigsaw" que foi implementado no Bomb: https://gist.github.com/licensed/51f12b36bdef083cb3e37597fb62003b https://pythonmana.com/2021/02/20210223164623700z.html

eu achei esse modelo. e to tentando adptar 
https://github.com/ralbertazzi/jigsaw-puzzle-solver
site de fonte: https://towardsdatascience.com/solving-jigsaw-puzzles-with-python-and-opencv-d775ba730660

**Comment by xfefe** [comment]
https://filipvitas.medium.com/how-to-bypass-slider-captcha-with-js-and-puppeteer-cd5e28105e3c 
https://www.jqueryscript.net/form/image-puzzle-slider-captcha.html

sei muito pouco ou quase nada sobre programação, porem andei pesquisando, talvez ajude ou não '-'

**Comment by Nydoehar** [comment]
Eu testei o bot (versão '**puzzle**'), ele está funcionando!!! Muito obrigado! 

Contudo notei que:

1 - Quando o captcha está na tela e ativamos o bot, o captcha é resolvido imediatamente e o bot segue normalmente. 

2 - Mas quando o bot já está ativo e sai da tela 'treasure hunt' e o captcha aparece, o bot demora cerca de 20 segundos para identificar e resolver o captcha. Depois ele vai para a tela 'characters' e passa mais de 1 minuto parado lá. 

Olhando no prompt de comando vi que enquanto estava parado ele estava '=> Refreshing Heroes Positions.'. 

Ou seja, quando resolve o captcha o bot entra na tela 'characters' mas pensa que está na tela 'treasure hunt', daí fica tentando atualizar a posição dos personagens e só depois de algum tempo é que ele percebe que está em outra tela.

De resto está funcionando perfeitamente.

**Comment by gabrielwjesus** [comment]
> Eu testei o bot (versão '**puzzle**'), ele está funcionando!!! Muito obrigado! 
> 
> 
> 
> Contudo notei que:
> 
> 
> 
> 1 - Quando o captcha está na tela e ativamos o bot, o captcha é resolvido imediatamente e o bot segue normalmente. 
> 
> 
> 
> 2 - Mas quando o bot já está ativo e sai da tela 'treasure hunt' e o captcha aparece, o bot demora cerca de 20 segundos para identificar e resolver o captcha. Depois ele vai para a tela 'characters' e passa mais de 1 minuto parado lá. 
> 
> 
> 
> Olhando no prompt de comando vi que enquanto estava parado ele estava '=> Refreshing Heroes Positions.'. 
> 
> 
> 
> Ou seja, quando resolve o captcha o bot entra na tela 'characters' mas pensa que está na tela 'treasure hunt', daí fica tentando atualizar a posição dos personagens e só depois de algum tempo é que ele percebe que está em outra tela.
> 
> 
> 
> De resto está funcionando perfeitamente.

Pense o seguinte: se ele for mto rápido nas ações ... nao der erros, etc... vai identificar no jogo um robô 
Tento ações automáticas e com a mesma frequência

**Comment by Nydoehar** [comment]
> > Eu testei o bot (versão '**puzzle**'), ele está funcionando!!! Muito obrigado!
> > Contudo notei que:
> > 1 - Quando o captcha está na tela e ativamos o bot, o captcha é resolvido imediatamente e o bot segue normalmente.
> > 2 - Mas quando o bot já está ativo e sai da tela 'treasure hunt' e o captcha aparece, o bot demora cerca de 20 segundos para identificar e resolver o captcha. Depois ele vai para a tela 'characters' e passa mais de 1 minuto parado lá.
> > Olhando no prompt de comando vi que enquanto estava parado ele estava '=> Refreshing Heroes Positions.'.
> > Ou seja, quando resolve o captcha o bot entra na tela 'characters' mas pensa que está na tela 'treasure hunt', daí fica tentando atualizar a posição dos personagens e só depois de algum tempo é que ele percebe que está em outra tela.
> > De resto está funcionando perfeitamente.
> 
> Pense o seguinte: se ele for mto rápido nas ações ... nao der erros, etc... vai identificar no jogo um robô Tento ações automáticas e com a mesma frequência

Good point!

**Comment by wanderaugusto** [comment]
> Eu testei o bot (versão '**puzzle**'), ele está funcionando!!! Muito obrigado!
> 
> Contudo notei que:
> 
> 1 - Quando o captcha está na tela e ativamos o bot, o captcha é resolvido imediatamente e o bot segue normalmente.
> 
> 2 - Mas quando o bot já está ativo e sai da tela 'treasure hunt' e o captcha aparece, o bot demora cerca de 20 segundos para identificar e resolver o captcha. Depois ele vai para a tela 'characters' e passa mais de 1 minuto parado lá.
> 
> Olhando no prompt de comando vi que enquanto estava parado ele estava '=> Refreshing Heroes Positions.'.
> 
> Ou seja, quando resolve o captcha o bot entra na tela 'characters' mas pensa que está na tela 'treasure hunt', daí fica tentando atualizar a posição dos personagens e só depois de algum tempo é que ele percebe que está em outra tela.
> 
> De resto está funcionando perfeitamente.

Não tomou ban ainda ?

**Comment by Nydoehar** [comment]
> > Eu testei o bot (versão '**puzzle**'), ele está funcionando!!! Muito obrigado!
> > Contudo notei que:
> > 1 - Quando o captcha está na tela e ativamos o bot, o captcha é resolvido imediatamente e o bot segue normalmente.
> > 2 - Mas quando o bot já está ativo e sai da tela 'treasure hunt' e o captcha aparece, o bot demora cerca de 20 segundos para identificar e resolver o captcha. Depois ele vai para a tela 'characters' e passa mais de 1 minuto parado lá.
> > Olhando no prompt de comando vi que enquanto estava parado ele estava '=> Refreshing Heroes Positions.'.
> > Ou seja, quando resolve o captcha o bot entra na tela 'characters' mas pensa que está na tela 'treasure hunt', daí fica tentando atualizar a posição dos personagens e só depois de algum tempo é que ele percebe que está em outra tela.
> > De resto está funcionando perfeitamente.
> 
> Não tomou ban ainda ?

Não. Como o bot não interage diretamente com o jogo é bem difícil de pegar, juntando a isso, eu uso o computador com frequência daí fica ainda mais difícil de ser detectado.

Uso o bot mais para não ter que ficar 24 horas olhando para o jogo.

**Comment by Nydoehar** [comment]
> > Eu testei o bot (versão '**puzzle**'), ele está funcionando!!! Muito obrigado!
> > Contudo notei que:
> > 1 - Quando o captcha está na tela e ativamos o bot, o captcha é resolvido imediatamente e o bot segue normalmente.
> > 2 - Mas quando o bot já está ativo e sai da tela 'treasure hunt' e o captcha aparece, o bot demora cerca de 20 segundos para identificar e resolver o captcha. Depois ele vai para a tela 'characters' e passa mais de 1 minuto parado lá.
> > Olhando no prompt de comando vi que enquanto estava parado ele estava '=> Refreshing Heroes Positions.'.
> > Ou seja, quando resolve o captcha o bot entra na tela 'characters' mas pensa que está na tela 'treasure hunt', daí fica tentando atualizar a posição dos personagens e só depois de algum tempo é que ele percebe que está em outra tela.
> > De resto está funcionando perfeitamente.
> 
> Não tomou ban ainda ?

Não.

**Comment by doranelle** [comment]
Alguém sabe como gerar a piece.png?

**Comment by gabrielwjesus** [comment]
> Alguém sabe como gerar a piece.png?

as imagens estão dentro da pasta target

**Comment by doranelle** [comment]
> > Alguém sabe como gerar a piece.png?
> 
> as imagens estão dentro da pasta target 

Sim, mas como gerar para substituição. O bot está falhando para acertar o captcha comigo mesmo na resolução correta. Antes ele nem funcionava, aí tive que ir substituindo todas as targets, falta apenas a piece.

**Comment by gabrielwjesus** [comment]
> > > Alguém sabe como gerar a piece.png?
> > 
> > 
> > as imagens estão dentro da pasta target
> 
> Sim, mas como gerar para substituição. O bot está falhando para acertar o captcha comigo mesmo na resolução correta. Antes ele nem funcionava, aí tive que ir substituindo todas as targets, falta apenas a piece.

cara, aqui ele está funcionando perfeito pra resolver os captchas. Veja se voce esta usando a versão certa.

**Comment by doranelle** [comment]
> > > > Alguém sabe como gerar a piece.png?
> > > 
> > > 
> > > as imagens estão dentro da pasta target
> > 
> > 
> > Sim, mas como gerar para substituição. O bot está falhando para acertar o captcha comigo mesmo na resolução correta. Antes ele nem funcionava, aí tive que ir substituindo todas as targets, falta apenas a piece.
> 
> cara, aqui ele está funcionando perfeito pra resolver os captchas. Veja se voce esta usando a versão certa.

Versão certinha, de ontem a noite.
