### ISSUE TITLE
Novo capcha

### ISSUE THREAD

**Issue by cunhaminers** [mpcabete/bombcrypto-bot#96]
Fala meu querido! Obrigado por devolver minhas noites de sono! Graças ao seu bot voltei a dormir mano, pqp! Enfim, quanto aos capcha agora, vai adicionar alguma atualização? Outra coisa, vi que parece que teve alterações quanto a você poder escolher se quer mandar eles trabalharem com meia barra ou full agora, li certo? isso procede? Desculpe mandar msg aqui mas não achei nenhum outro meio :/ forte abraço!
aaaaahhh eu e meu cunhado que usamos o seu bot, estaremos enviado uns dols aí para dar uma motivação pra atualizar ele kkkkk abraço

**Comment by mpcabete** [comment]
Oi cunha, mto obrigado!
Pretendo resolver esse capcha sim, vou começar a trabalhar nisso agora!
Teve essa alteração sim, vc pode configurar pelo arquivo config.yaml.

**Comment by cunhaminers** [comment]
Pergunta bem de leigo noob kkkk
Para cada atualização que tu faz aqui, eu tenho que baixar o bot novamente?


Em qui., 2 de dez. de 2021 às 10:09, mpcabete ***@***.***>
escreveu:

**Comment by cristhianbreunig** [comment]
Sim @cunhaminers, se tu baixou (_não fez o clone o projeto_), precisa baixar novamente...

Se clonou o projeto, tem que dar um "_pull_" no projeto

**Comment by cunhaminers** [comment]
Blz irmão, brigadao


Em qui., 2 de dez. de 2021 às 11:20, Cristhian Breunig <
***@***.***> escreveu:
