### ISSUE TITLE
Desenvolvi um macro e estou disponibilizando para ajudar a quem vai continuar nosso macro aqui.

### ISSUE THREAD

**Issue by edumi538** [mpcabete/bombcrypto-bot#98]
Galera estava desenvolvendo um macro tbm a um tempo atrás e ele estava quase pronto, porem estava sem tempo para melhorar as validações e adaptações em relação as quedas do servidor. Por medida de necessidade decidi me unir ao desenvolvimento do macro da galera aqui que está muito legal e melhor desenvolvido que o meu. Por isso estou fazendo disponibilizando o código para tentar ajudar quem está tentando quebrar o captcha do role. Se gostarem do meu projeto tbm e quiserem continua-lo fiquem a vontade tbm, estarei analisando e subindo o pull request de quem quiser.

https://github.com/edumi538/dk-bomb-bot

**Comment by TeteuInfinity** [comment]
Bom dia irmão, está com anti-captcha?
Tem discord? posso auxiliar no projeto.

**Comment by cryptoenthusiast33** [comment]
I couldn't resolve the situation myself but I found this guys and they managed to make it work:
Não consegui resolver a situação eu mesmo mas achei esse pessoal que conseguiu no Discord abaixo:

https://discord.me/BombFarm

**Comment by mauricioleft121** [comment]
> Galera estava desenvolvendo um macro tbm a um tempo atrás e ele estava quase pronto, porem estava sem tempo para melhorar as validações e adaptações em relação as quedas do servidor. Por medida de necessidade decidi me unir ao desenvolvimento do macro da galera aqui que está muito legal e melhor desenvolvido que o meu. Por isso estou fazendo disponibilizando o código para tentar ajudar quem está tentando quebrar o captcha do role. Se gostarem do meu projeto tbm e quiserem continua-lo fiquem a vontade tbm, estarei analisando e subindo o pull request de quem quiser.
> 
> https://github.com/edumi538/dk-bomb-bot

Cara, eu programo em javascript, tentei usar o robot.js e vei, q bagulho complicado, da erro pra builda, e pra rebuildar, não sei se eu fiz algo de errado, mas só instalar as dependencias e executar o rebuild n adiantou, pq ele n reconhece o robot.js

**Comment by felipearon** [comment]
Esse Bot roda no MacOS?
