### ISSUE TITLE
Onde coloco o codigo

### ISSUE THREAD

**Issue by Hiwry** [mpcabete/bombcrypto-bot#99]
onde eu coloco esse codigo pra poder testar?

**Comment by pwr43nd37** [comment]
nao tem que colocar o codigo, voce roda ele, veja as instruções que constam na pagina do bot, na parte de instalacao, voce baixa os arquivos em .zip, salva em um diretorio, descompacta, instala o python, baixa a dependências, e atraves do cmd voce executa o index.py
